### ISSUE TITLE
2.2.0.BUILD-SNAPSHOT版本mvn install 失败

### ISSUE THREAD

**Issue by wujincheng2333** [alibaba/spring-cloud-alibaba#1011]
https://repo.spring.io/libs-milestone-local/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom  
无法找到这个pom文件，导致mvn install安装卡住

**Comment by fangjian0423** [comment]
It works well in my local and circleci.

**Comment by vnobo** [comment]
2.2.0.BUILD-SNAPSHOT 你怎么配置的,我怎么没有找到  BUILD-SNAPSHOT 说明
