### ISSUE TITLE
I find that dubbo.consumer.group=myGroup can work but dubbo.registry.group=myGroup can't work in nacos registration center

### ISSUE THREAD

**Issue by flushCoder** [alibaba/spring-cloud-alibaba#1013]
I find that **dubbo.consumer.group=myGroup** can work but **dubbo.registry.group=myGroup** can't work in nacos registration center

**Comment by fangjian0423** [comment]
try `spring.cloud.nacos.discovery.group`, but need waiting new version release.

**Comment by flushCoder** [comment]
wait new version
