### ISSUE TITLE
Upgrade  apache-dubbo-2.7.4.1

### ISSUE THREAD

**Issue by gang0713** [alibaba/spring-cloud-alibaba#1020]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 
https://github.com/apache/dubbo/releases

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fangjian0423** [comment]
could you pls create a PR to finish it?
