### ISSUE TITLE
nacos can't built with open jdk 11,or using mysql 8.0 

### ISSUE THREAD

**Issue by shihuaguo** [alibaba/spring-cloud-alibaba#1022]
1.is nacos support build by jdk1.8+ or only jdk1.8? 
2.using mysql 8.0 version to store config, i got the following error:
Caused by: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.

**Comment by WunHwanTseng** [comment]
same to me.when i use java 11, nacos client connect server timeout.

**Comment by fangjian0423** [comment]
Refer https://github.com/alibaba/nacos/issues/2042.
