### ISSUE TITLE
nacos does not support springboot-2.2.0-release?

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/spring-cloud-alibaba#1027]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config

**Describe what problem you have encountered**

see here https://github.com/alibaba/nacos/issues/1982

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by vnobo** [comment]
Now spring cloud alibaba is 2.1.0.release support  spring boot 2.1.x.

Now spring cloud alibaba is 2.2.0.release support spring boot 2.2.x
but 2.2.0.release Has not been released

**Comment by shihuaguo** [comment]
when will spring cloud alibaba 2.2.0.release be released?

**Comment by imgoby** [comment]
when will spring cloud alibaba 2.2.0.release be released?

**Comment by fangjian0423** [comment]
duplicate with https://github.com/alibaba/spring-cloud-alibaba/issues/1153
