### ISSUE TITLE
用nacos做配置中心和注册中心，在单元测试时，进行数据库操作，报错

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/spring-cloud-alibaba#1031]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config

**Describe the bug**

seee here https://github.com/alibaba/nacos/issues/1968

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xlb** [comment]
mark

**Comment by fangjian0423** [comment]
HikariPool will shutdown when receive RefreshEvent and Nacos send RefreshEvent when loading configuration first time.

You could change HikariPool to other DataSource Pool or waiting Nacos fix this problem.

**Comment by fangjian0423** [comment]
Related https://github.com/alibaba/spring-cloud-alibaba/issues/699.
