### ISSUE TITLE
用nacos config的LocalConfigInfoProcessor为什么总是会从我本地取配置文件？

### ISSUE THREAD

**Issue by wangzhedong** [alibaba/spring-cloud-alibaba#1033]
LocalConfigInfoProcessor.getFailover()的这个方法，
 File localPath = getFailoverFile(serverName, dataId, group, tenant);
这个localPath的路径是C:\Users\Administrator\nacos\naming\dde45a89-128e-497c-be76-782efd55a9ae
为什么在启动的时候总是会去这个路径拿配置文件？我这个路径里面是没有配置的文件的，所以启动过程中总是报错

**Comment by yuhuangbin** [comment]
```java
LOCAL_SNAPSHOT_PATH = System.getProperty("JM.SNAPSHOT.PATH", System.getProperty("user.home")) + File.separator
            + "nacos" + File.separator + "config";
```
会首先去读系统环境配置 JM.SNAPSHOT.PATH， 没有的话默认user.home。
