### ISSUE TITLE
when the 2.1.1.release publish?

### ISSUE THREAD

**Issue by leoxchang** [alibaba/spring-cloud-alibaba#1042]
I see the 2.1.1.release has past due by 6 days. I want to know when the 2.1.1.release publish.
![image](https://user-images.githubusercontent.com/4852704/68191515-ae1bd300-ffea-11e9-9e54-06c0d8cf91e9.png)

**Comment by fangjian0423** [comment]
Snapshot versions 2.1.1 2.0.1 1.5.1 has been deployed and get it in sonatype snapshot respository by repository setting:

```xml
<repositories>
    <repository>
        <id>sonatype-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

Release version will be release next week!

**Comment by vnobo** [comment]
@fangjian0423 
build error:
Could not resolve all files for configuration ':mspbots-lib-model:compileClasspath'.
   > Could not find com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2.1.1.BUILD-SNAPSHOT.

**Comment by fangjian0423** [comment]
It has been released, cheers. Refer https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.1.RELEASE/pom
