### ISSUE TITLE
2.1.1.BUILD-SNAPSHOT版本的spring-cloud-starter-stream-rocketmq，服务启动报错

### ISSUE THREAD

**Issue by Kimmyzhao** [alibaba/spring-cloud-alibaba#1047]
当把spring-cloud-starter-stream-rocketmq更新到2.1.1.BUILD-SNAPSHOT时，服务启动报错，报错信息如图所示
![6E914923-E16D-4783-A07E-E2657841227F](https://user-images.githubusercontent.com/11455494/68283841-42ec0280-00b7-11ea-8451-f88993046ae0.png)

**Comment by fangjian0423** [comment]
remove regexp check, refer https://github.com/alibaba/spring-cloud-alibaba/commit/695b3749024c318065750f3cef36562daccf625a.
