### ISSUE TITLE
dubbo+nacos bug

### ISSUE THREAD

**Issue by jic138168** [alibaba/spring-cloud-alibaba#1052]
versioin:2.0.0

Problem 1: service provider A is offline, service B is online, and the consumers are still connected to service provider A. Problem 2: service provider is restarted, and the consumers also need to restart

**Comment by fangjian0423** [comment]
please try 2.0.1.BUILD-SNAPSHOT with sonatype snapshot respository by repository setting:

```xml
<repositories>
    <repository>
        <id>sonatype-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by mercyblitz** [comment]
try 2.1.0.RELEASE.

**Comment by laiweijia** [comment]
2.1.1.RELEASE is fixed! trust me!

**Comment by YangXueJun** [comment]
> 2.1.1.RELEASE is fixed! trust me!

I can testify

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
