### ISSUE TITLE
[RocketMQ Binder] Change the class type of nameServer

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#1054]
Now the type of name-server configuration item in `RocketMQBinderConfigurationProperties` is `java.lang.String`, it composed of multiple name servers separated by ";".

change `String` type to `List<String>` is better than regular expression check.

related https://github.com/alibaba/spring-cloud-alibaba/issues/977.

**Comment by yuhuangbin** [comment]
i will fix it
