### ISSUE TITLE
nacos config center cant support Chinese word

### ISSUE THREAD

**Issue by Lyeluo** [alibaba/spring-cloud-alibaba#1055]
i use nacos to be my config center ,but i have some configraction is Chinese word,
then it throw error :  
ERROR com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder [Class = com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder] [File = NacosPropertySourceBuilder.java] [Line = 109] [Method = loadNacosData] [main] {Module : } parse data from Nacos error,dataId:ms-console-dev.yml,data:spring:

someone know how to solve this issue? thanks

**Comment by roninzhang** [comment]
you have some problem, anyone can **save** us?

**Comment by fangjian0423** [comment]
It is supported and works well in my local.

![image](https://user-images.githubusercontent.com/5254035/68639441-8b843f80-053f-11ea-8296-86982effcc57.png)


pls make sure that your IDE is causing this problem.

**Comment by Lyeluo** [comment]
@fangjian0423 i can also user my ide run my project ,but when i package then it throw error ,whatever window and linux

**Comment by Lyeluo** [comment]
我知道了是我的系统编码问题，没有将系统默认编码设置为utf-8

**Comment by 631359746** [comment]
i have this problem too .
run well in IDE , broken when packaged in jar to start . OS : window10
 is there a necessary to provide a config to control the serialize encoding rather then used the system default encoding ? @fangjian0423  , or change `data.getBytes()` to `data.getBytes(StandardCharsets.UTF_8)`
code in `com.alibaba.cloud.nacos.parser.NacosDataYamlParser#doParse` , `data.getBytes()`
```java
public class NacosDataYamlParser extends AbstractNacosDataParser {

	public NacosDataYamlParser() {
		super(",yml,yaml,");
	}

	@Override
	protected Properties doParse(String data) {
		YamlPropertiesFactoryBean yamlFactory = new YamlPropertiesFactoryBean();
		yamlFactory.setResources(new ByteArrayResource(data.getBytes()));
		return yamlFactory.getObject();
	}
}
```

**Comment by 631359746** [comment]
add start paramter like this can avoid the error
`java -Dfile.encoding=UTF-8 -jar xxx.jar`
