### ISSUE TITLE
It‘s a spelling mistake in this page(https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery).

### ISSUE THREAD

**Issue by LuckyLight6** [alibaba/spring-cloud-alibaba#1062]
It‘s a spelling mistake in this page.

![](https://user-images.githubusercontent.com/22209857/68958286-c1a71500-0806-11ea-8524-608b5ee88074.png)

**Comment by fangjian0423** [comment]
could you pls create a pr to fix it?

**Comment by LuckyLight6** [comment]
@fangjian0423 Sorry, I don't know how to create pr to the wiki page.

**Comment by fangjian0423** [comment]
fix it in docs module, we have Chinese and English version: https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-docs/src/main

**Comment by LuckyLight6** [comment]
ok, I get it.
