### ISSUE TITLE
questions about  spring-cloud-alibaba-2.1.1.RELEASE version

### ISSUE THREAD

**Issue by yanglin1501804006** [alibaba/spring-cloud-alibaba#1064]
Which version of the spring cloud version supported by this version [2.1.1] should be? 
If I say that I use the version of spring-cloud-alibaba-2.1.1.RELEASE locally, 
what is the minimum version of my own minimum spring-boot-starter-parent?

这个版本【2.1.1】支持的spring cloud 最低版本应该是哪一个？假如说，
我本地使用spring-cloud-alibaba-2.1.1.RELEASE这个版本，
我自己spring-boot-starter-parent 最低版本应该是多少[应该写多少，随便写吗，还是必须写大于等于2.1.7的spring boot版本呢]

**Comment by yuhuangbin** [comment]
`https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E`
