### ISSUE TITLE
Nacos Config 配置了namespace后，shared-dataids的配置不生效

### ISSUE THREAD

**Issue by zengwenchong** [alibaba/spring-cloud-alibaba#1068]
![% 98)`97ZAIGQ%4LGRI$MYT](https://user-images.githubusercontent.com/9605012/69394180-3ce05d80-0d16-11ea-8720-b78bde431525.png)

请问namespace和shared的配置是互斥的么，namespace配置指向的是dev，dev下的配置可以获取到，但是无法获取common.properties的配置内容
shared-dataids指向的public命名空间下的

![{(_N40K9TINU8G1DNGC_NAD](https://user-images.githubusercontent.com/9605012/69402038-a02bb900-0d31-11ea-999a-f16f571abd02.png)

**Comment by yuhuangbin** [comment]
nacos不同namespace的配置是隔离的，不能跨namespace访问

**Comment by sdaduanbilei** [comment]
其实我觉着 public 里面应该是共享的 这样才符合共享配置的

**Comment by squallliu** [comment]
我也遇到这个问题了，现在共享配置每个 namespace 都要放一个

**Comment by fangjian0423** [comment]
跨 namespace 涉及安全问题，目前不支持也不建议跨 namespace 访问。

**Comment by 1320289235** [comment]
官方建议不同环境用namespace隔离，但是又不支持跨namespace访问，那公共的配置放在哪儿呢？
