### ISSUE TITLE
./mvnw install fail

### ISSUE THREAD

**Issue by superzjcy** [alibaba/spring-cloud-alibaba#1071]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-alibaba

**Describe the bug**
./mvnw install fail

**To Reproduce**
The found version is [2.2.0.BUILD-SNAPSHOT]
Deactivating "milestone" profile for version="2.2.0.BUILD-SNAPSHOT"
Deactivating "central" profile for version="2.2.0.BUILD-SNAPSHOT"
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-sentinel:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-sentinel/pom.xml, line 79, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-netflix-zuul:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-sentinel-gateway:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-sentinel-gateway/pom.xml, line 16, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-nacos-discovery:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-nacos-discovery/pom.xml, line 31, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-config-client:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-nacos-discovery:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-nacos-discovery/pom.xml, line 36, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-config-server:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-nacos-discovery:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-nacos-discovery/pom.xml, line 42, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-seata:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-seata/pom.xml, line 41, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-config-server:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-nacos-config-server:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-nacos-config-server/pom.xml, line 25, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:jar is missing. @ com.alibaba.cloud:spring-cloud-alibaba-dubbo:[unknown-version], /Users/rongen/backend/spring-cloud-alibaba/spring-cloud-alibaba-dubbo/pom.xml, line 94, column 21

**Additional context**
MacOS  、Java8

**Comment by echooymxq** [comment]
The pom problem has resolved. pls check again.
