### ISSUE TITLE
建议将nacos这种持久化操作的实现由官方直接集成进去

### ISSUE THREAD

**Issue by xzknet** [alibaba/spring-cloud-alibaba#1073]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software.

** Which Component **
eg. Nacos Discovery, Sentinel
Sentinel And Nacos

** Is your feature request related to a problem? Please describe. **
项目中希望可以通过nacos数据源的进行规则持久化，但是阅读了很多资料后发现必须下载该项目改了才可以用，这样就不方便了
In the project, I hope that the rules can be persisted through the nacos data source, but after reading a lot of information, I found that I must download the project and change it before it can be used, which is inconvenient.

** Describe the solution you'd like **
建议可以通过sentinel启动参数来控制
It is recommended that it can be controlled by sentinel startup parameters

** Describe alternatives you've considered **
或者通过URL将规则发送到另外一个项目，由专门的存储项目进行规则的存储。
Or send the rule to another item through the URL, and the rule is stored by a special storage item.

** Additional context **

**Comment by echooymxq** [comment]
Sentinel support nacos datasource.

**Comment by felixyin** [comment]
nacos datasource，service restarted，the rule will missing.
