### ISSUE TITLE
Service instances of different groups cannot be found

### ISSUE THREAD

**Issue by yuhuangbin** [alibaba/spring-cloud-alibaba#1075]
**Which Component**
 Nacos Discovery

**Describe the bug**
Service instances of different groups cannot be found

**To Reproduce**
service A register at group `group_a`
service B register at group `group_b`
service A cannot call service B

**Comment by echooymxq** [comment]
The result is normal, similar to tenant.

**Comment by yuhuangbin** [comment]
I think  can be called between different groups, and nacos api is supporting this.  like `List<Instance> getAllInstances(String serviceName, String groupName)`

**Comment by vastliuzxc** [comment]
service A register at group group_a
the same name service A register at group group_b
service C register at group group_c
service C how to call service A of group_b
