### ISSUE TITLE
Add property to disable Sentinel auto-configuration

### ISSUE THREAD

**Issue by echooymxq** [alibaba/spring-cloud-alibaba#1091]
Add `spring.cloud.circuitbreaker.sentinel.enabled` property to disable Sentinel circuitbreaker auto-configuration.
Refer [spring-cloud-circuitbreaker-sentinel](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-circuitbreaker-sentinel).

**Comment by yuhuangbin** [comment]
i will fix it.
