### ISSUE TITLE
ChannelInterceptor cannot Interceptor spring cloud stream rocketmq consumer side 

### ISSUE THREAD

**Issue by glmapper** [alibaba/spring-cloud-alibaba#1093]
Use ChannelInterceptor + GlobalChannelInterceptorWrapper in spring-message,

I expect to be able to intercept Spring Cloud Stream rocketmq messages, but I found that the interceptor can only take effect on the producer side, but not on the consumer side.

PS: I learned from the Internet that kafka is not working, because kafka is not based on MessageChannel, so I would like to ask if rocketmq is not based on MessageChannel.

**Comment by fangjian0423** [comment]
Interceptor not effect in consumer side except we add it in MessageChannel manually in my option.

**Comment by fangjian0423** [comment]
oh, sorry. I found it will do by `MessageConverterConfigurer`, refer https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/MessageConverterConfigurer.java#L139.

**Comment by glmapper** [comment]
> Interceptor not effect in consumer side except we add it in MessageChannel manually in my option.

I have solved the problem，thks

**Comment by xswfantasy** [comment]
> > Interceptor not effect in consumer side except we add it in MessageChannel manually in my option.
> 
> I have solved the problem，thks

how add it in MessageChannel manually in my option?
