### ISSUE TITLE
能不能在seataEnv多环境设置的时候优雅点。Can you be more elegant when setting up seataEnv in multi-environment ？

### ISSUE THREAD

**Issue by Wadeqin** [alibaba/spring-cloud-alibaba#1113]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
SpringCloud-Seata

**Is your feature request related to a problem? Please describe.**

seataEnv只能通过-D设置太不友好了。

It is too unfriendly to set seataEnv via -D.

**Describe the solution you'd like**

能不能在GlobalTransactionAutoConfiguration的globalTransactionScanner里面直接用
System.setProperty("seataEnv", ApplicationContextHolder.getApplicationContext().getEnvironment().getActiveProfiles()[0]);设置算了。直接跟springboot的统一。

Can it be used directly in the globalTransactionScanner of GlobalTransactionAutoConfiguration
”System.setProperty("seataEnv", ApplicationContextHolder.getApplicationContext().getEnvironment().getActiveProfiles()[0]);“
Directly unified with springboot.

**Describe alternatives you've considered**

 恶心的workaround，在logback设置&lt;property scope="system" name="seataEnv" value="dev"/&gt;，主要是这个GlobalTransactionAutoConfiguration加载的太快了，没有好的方式。唉，难受，想哭。

Disgusting workaround, set in logback-dev.xml &lt;property scope="system" name="seataEnv" value="dev"/&gt;
mainly because this GlobalTransactionAutoConfiguration is loaded too fast, there is no good way. 
Alas, uncomfortable, want to cry.

**Additional context**

**Comment by fangjian0423** [comment]
hi, you could refer [seata-spring-boot-starter](https://github.com/seata/seata/tree/develop/seata-spring-boot-starter), we will integrate it in the future.
