### ISSUE TITLE
spring-configuration-metadata.json  add  spring.cloud.stream.rocketmq.bindings.<binding-name>

### ISSUE THREAD

**Issue by yiyan1992** [alibaba/spring-cloud-alibaba#1117]
version   2.1.0.RELEASE   spring-cloud-starter-stream-rocketmq

now  in  spring-configuration-metadata.json  can't find 

spring.cloud.stream.rocketmq.bindings.<binding-name>.consumer
spring.cloud.stream.rocketmq.bindings.<binding-name>.producer  

Cannot resolve configuration property  in application.properties/bootstrap.properties  in IDEA

**Comment by fangjian0423** [comment]
hi, it exists in my local. Are you sure there is no spring-configuration-metadata.json?

**Comment by yiyan1992** [comment]
![微信截图_20191226160707](https://user-images.githubusercontent.com/15227616/71466199-cabdd580-27f9-11ea-9abe-7177399e2231.png)

![微信截图_20191226160914](https://user-images.githubusercontent.com/15227616/71466286-15d7e880-27fa-11ea-9107-ac978e6335af.png)

idea can't show like others

**Comment by fangjian0423** [comment]
The other configurations like `spring.cloud.stream.bindings.*` is defined by project [Spring Cloud Stream](https://github.com/spring-cloud/spring-cloud-stream).

**Comment by yiyan1992** [comment]
ok
