### ISSUE TITLE
k8s环境中消费者一直在消费老的ip，无法建立新的链接

### ISSUE THREAD

**Issue by Abnerring** [alibaba/spring-cloud-alibaba#1118]
您好，我遇到一个问题，就是，我启动消费者，和生产者在K8S pod中，然后每次我重启生产者，POD的ip变化了，消费者还消费老的生产者的IP，不会自动建立链接？nacos不在k8s环境中。

**Comment by fangjian0423** [comment]
duplicate: https://github.com/alibaba/spring-cloud-alibaba/issues/1119
