### ISSUE TITLE
如何使用spring-cloud-stream-binder-rocketmq设置消费者的ComsumeFromWhere

### ISSUE THREAD

**Issue by fengxiang-sc** [alibaba/spring-cloud-alibaba#1121]
如何使用spring-cloud-stream-binder-rocketmq设置消费者的ComsumeFromWhere

**Comment by fangjian0423** [comment]
Not supported now, refer https://github.com/alibaba/spring-cloud-alibaba/issues/488.

**Comment by madGodFucker** [comment]
新版的 没这个属性了。。
