### ISSUE TITLE
长期没动静了呢？

### ISSUE THREAD

**Issue by mostcool** [alibaba/spring-cloud-alibaba#1123]
SCA适配Hoxton进展怎样？有发版计划吗？年前有戏吗？
SCA集成进Spring Initializr说了两个多月了，还没看到动静呢？

**Comment by khiker007** [comment]
活跃度一直很差，有点想弃坑了，怕哪天又突然停止维护了

**Comment by mercyblitz** [comment]
SCA适配Hoxton进展怎样？有发版计划吗？年前有戏吗？
-------------------------------------
正在进行中...

SCA集成进Spring Initializr说了两个多月了，还没看到动静呢？
-------------------------------
这个进程缓慢，完全由 Spring 官方控制

**Comment by shihuaguo** [comment]
别突然停止维护啊，现在好多开源项目用这个呢

**Comment by fangjian0423** [comment]
SCA适配Hoxton进展怎样？有发版计划吗？年前有戏吗？
-------------------------------------

Hoxton 跟之前的 Greenwich 不一样，这个版本加了很多新的东西，需要大家再耐心等等。这也是为什么前段时间先发布 2.1.1.RELEASE, 2.0.1.RELEASE 和 1.5.1.RELEASE 的原因。这样就有更多的精力来发布 2.2.0.RELEASE

SCA集成进Spring Initializr说了两个多月了，还没看到动静呢？
-------------------------------
这个 Spring Cloud Alibaba 团队不能控制，是由 Spring Team 控制的。Spring Cloud Alibaba 团队一直跟进这件事
