### ISSUE TITLE
Will develope a common gateway?

### ISSUE THREAD

**Issue by chenkaijiekidd** [alibaba/spring-cloud-alibaba#1127]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 
Sentinal maybe is not a suitable gatway for micro-service, is there any solution for this? I hope the answer is not springcloud-gateway...

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yuhuangbin** [comment]
sentinel not a gateway role in microservices,  it's a lightweight powerful flow control component enabling reliability and monitoring for microservices

**Comment by chenkaijiekidd** [comment]
thanks, so which componen is the gateway of spring-cloud-alibaba project?

**Comment by yuhuangbin** [comment]
Zuul, Spring Cloud GateWay. Spring Cloud Alibaba doesn't have gateway component
