### ISSUE TITLE
dubbo+dubbo+sentinel设置服务降级，是否会在nacos上标识服务状态，阻止其他服务继续调用降级服务

### ISSUE THREAD

**Issue by khiker007** [alibaba/spring-cloud-alibaba#1128]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel，dubbo

**Describe what problem you have encountered**

dubbo服务的线程数跑满，或其他原因达到服务降级标准，后续的服务会快速失败，这时是否会在nacos注册中心标识服务状态并通知其他服务的调用者，在负载均衡中减去故障节点，达到阻止其他服务继续调用的目的？还是只能在dubbo consumer端对快速失败异常进行处理，进行重试？

**Comment by fangjian0423** [comment]
如果想达到你说的这个要求，可以参考一下这篇文章: https://mp.weixin.qq.com/s/ZdZ65-qjH9xLvGeVomomOw

**Comment by khiker007** [comment]
> 如果想达到你说的这个要求，可以参考一下这篇文章: https://mp.weixin.qq.com/s/ZdZ65-qjH9xLvGeVomomOw

Thanks
