### ISSUE TITLE
Use spring cloud alibaba sentinel.How to set the jvm properties in project app 

### ISSUE THREAD

**Issue by linsongze** [alibaba/spring-cloud-alibaba#1134]
Use spring cloud alibaba sentinel.How to set the jvm properties in project application.yml? 

eg. 

csp.sentinel.metric.file.single.size
csp.sentinel.statistic.max.rt

I found that I can only modify it in jvm -D or propertiesFile .But I want to modify it in application.yml or bootstrap.yml.Can you give me some suggest.
(我想不通过jvm或者properties文件在springcloud的模块中，设置sentinel-core的值.)

**Comment by fangjian0423** [comment]
Refer [Spring Cloud Alibaba Sentinel Wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#%E9%85%8D%E7%BD%AE).
