### ISSUE TITLE
关于Spring Cloud Alibaba推广的小建议

### ISSUE THREAD

**Issue by Xanthuim** [alibaba/spring-cloud-alibaba#1137]
都加都知道之前的Netflix全家桶很多处于维护状态，而阿里巴巴全家桶也开始受到关注，但我发现Spring Initializer中并没有看到Spring Cloud Alibaba相关组件。请问阿里巴巴是否可以跟Spring团队沟通一下，把Spring Cloud Alibaba相关组件加入到Spring Initializer（https://start.spring.io/）中，这样能更好的推广。

We all know that many Netflix family buckets before are in maintenance state, and Alibaba family buckets are also getting attention, but I found that spring cloud Alibaba related components are not seen in spring initializer. May I ask Alibaba to communicate with the spring team and add the relevant components of spring cloud Alibaba to the spring initializer so as to promote it better.

**Comment by fangjian0423** [comment]
hi, we are working on it and please wait patiently for a while.

感谢关注，我们正在处理这件事，请再耐心等待一段时间。

这是后面上线后的效果图:

![image](https://user-images.githubusercontent.com/5254035/71069031-e0584d00-21b2-11ea-89b2-44e7a7f75749.png)

**Comment by Xanthuim** [comment]
好的，期待中。。。
