### ISSUE TITLE
provider端怎么处理dubbo.cloud.subscribed-services？

### ISSUE THREAD

**Issue by mostcool** [alibaba/spring-cloud-alibaba#1141]
@mercyblitz 
应用只做为provider时，不指定dubbo.cloud.subscribed-services，默认会去请订阅注册中心中所有服务。这个怎么处理？
另外，启动时有必要去订阅服务吗？启动完成后再去订阅是否可行？

**Comment by mostcool** [comment]
Spring Cloud Dubbo 在 Dubbo 服务发布的实现不优雅，订阅和发布的每个服务最⻓等待 2.5分钟。默认一共重试五次，分别间隔 10s、20s、30s、40s、50s

**Comment by yuhuangbin** [comment]
try `dubbo.cloud.subscribed-services=“”`

**Comment by 631359746** [comment]
self subscription?
```java
@PostConstruct
	public Stream<String> initSubscribedServices() {
		Set<String> newSubscribedServices = new LinkedHashSet<>();

		// If subscribes all services
		if (ALL_DUBBO_SERVICES.equals(dubboCloudProperties.getSubscribedServices())) {
			List<String> services = discoveryClient.getServices();
			newSubscribedServices.addAll(services);
			if (logger.isWarnEnabled()) {
				logger.warn(
						"Current application will subscribe all services(size:{}) in registry, "
								+ "a lot of memory and CPU cycles may be used, "
								+ "thus it's strongly recommend you using the externalized property '{}' "
								+ "to specify the services",
						newSubscribedServices.size(), "dubbo.cloud.subscribed-services");
			}
		}
		else {
			newSubscribedServices.addAll(dubboCloudProperties.subscribedServices());
		}

		// exclude current application name
		excludeSelf(newSubscribedServices);

		// copy from subscribedServices
		Set<String> oldSubscribedServices = this.subscribedServices;

		// volatile update subscribedServices to be new one
		this.subscribedServices = newSubscribedServices;

		// dispatch SubscribedServicesChangedEvent
		dispatchEvent(new SubscribedServicesChangedEvent(this, oldSubscribedServices,
				newSubscribedServices));

		// clear old one, help GC
		oldSubscribedServices.clear();

		return newSubscribedServices.stream();
	}
```

**Comment by mercyblitz** [comment]
> self subscription?
> 
> ```java
> @PostConstruct
> 	public Stream<String> initSubscribedServices() {
> 		Set<String> newSubscribedServices = new LinkedHashSet<>();
> 
> 		// If subscribes all services
> 		if (ALL_DUBBO_SERVICES.equals(dubboCloudProperties.getSubscribedServices())) {
> 			List<String> services = discoveryClient.getServices();
> 			newSubscribedServices.addAll(services);
> 			if (logger.isWarnEnabled()) {
> 				logger.warn(
> 						"Current application will subscribe all services(size:{}) in registry, "
> 								+ "a lot of memory and CPU cycles may be used, "
> 								+ "thus it's strongly recommend you using the externalized property '{}' "
> 								+ "to specify the services",
> 						newSubscribedServices.size(), "dubbo.cloud.subscribed-services");
> 			}
> 		}
> 		else {
> 			newSubscribedServices.addAll(dubboCloudProperties.subscribedServices());
> 		}
> 
> 		// exclude current application name
> 		excludeSelf(newSubscribedServices);
> 
> 		// copy from subscribedServices
> 		Set<String> oldSubscribedServices = this.subscribedServices;
> 
> 		// volatile update subscribedServices to be new one
> 		this.subscribedServices = newSubscribedServices;
> 
> 		// dispatch SubscribedServicesChangedEvent
> 		dispatchEvent(new SubscribedServicesChangedEvent(this, oldSubscribedServices,
> 				newSubscribedServices));
> 
> 		// clear old one, help GC
> 		oldSubscribedServices.clear();
> 
> 		return newSubscribedServices.stream();
> 	}
> ```

Yes, it may subscribe itself because it's hard to detect the current application is a pure service provider or not.
