### ISSUE TITLE
Why remove NacosConfigManager?

### ISSUE THREAD

**Issue by msgcode** [alibaba/spring-cloud-alibaba#1144]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config

**Describe what problem you have encountered**
Why remove NacosConfigManage? i can see your guys already move NacosConfigManag's code to NacosConfigProperties. Why?

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by fangjian0423** [comment]
We thought it is incompatible with earlier version. So we decide to remove it.

**Comment by msgcode** [comment]
> We thought it is incompatible with earlier version. So we decide to remove it.

after remove it, and add some logic to NacosProperties v1.5.1.RELEASE & SpringCloud E
