### ISSUE TITLE
下线或者关停服务,gateway的负载还是会分到已经关掉的服务里

### ISSUE THREAD

**Issue by jackfruitran** [alibaba/spring-cloud-alibaba#1147]
网上有说是ribbon的定时任务更新可用服务列表导致的,无法及时更新可用服务,
这个是否有解决办法,
现在导致的问题是 无法无缝更新,需要去/actuator/service-registry?status=DOWN 接口先注销掉服务才能优雅关停服务 类似eureka(请求注销+sleep)  无法使用nacos的秒级切换上下线 ,正常关停服务也是,是否nacos支付其他方式 来优雅关停服务

**Comment by fangjian0423** [comment]
1. Ribbon 有个刷新时间，默认是 30s。会调用 `ServerList#getUpdatedListOfServers` 方法获取实例，可以通过 `ribbon.ServerListRefreshInterval=ms` 配置刷新时间
2. 服务下线前调用 /actuator/service-registry?status=DOWN 先下线实例，然后等待下一次服务实例的刷新确保不会拿到下线的实例

参考 [Spring Cloud 应用优雅下线](https://help.aliyun.com/document_detail/132165.html)

**Comment by liaomengge** [comment]
> 2\. service-registry

'/actuator/service-registry?status=DOWN' 这个只针对eureka， nacos是没有状态的，优雅停机应该控制好ribbon.ServerListRefreshInterval的刷新频率

**Comment by liaomengge** [comment]
> 1. Ribbon 有个刷新时间，默认是 30s。会调用 `ServerList#getUpdatedListOfServers` 方法获取实例，可以通过 `ribbon.ServerListRefreshInterval=ms` 配置刷新时间
> 2. 服务下线前调用 /actuator/service-registry?status=DOWN 先下线实例，然后等待下一次服务实例的刷新确保不会拿到下线的实例
> 
> 参考 [Spring Cloud 应用优雅下线](https://help.aliyun.com/document_detail/132165.html)

'/actuator/service-registry?status=DOWN' 这个只针对eureka， nacos是没有状态的，优雅停机应该控制好ribbon.ServerListRefreshInterval的刷新频率

**Comment by liaomengge** [comment]
'/actuator/service-registry?status=DOWN' 这个只针对eureka， nacos是没有状态的，优雅停机应该控制好ribbon.ServerListRefreshInterval的刷新频率

NacosServiceRegistry
![image](https://user-images.githubusercontent.com/12670328/84251269-b4090200-ab3f-11ea-9ec8-8b6a2a76ef96.png)

**Comment by yuhuangbin** [comment]
可以使用`NacosRule` , 在Nacos控制台下线后，会立刻感知。

**Comment by RainElohim** [comment]
> 可以使用`NacosRule` , 在Nacos控制台下线后，会立刻感知。

试验了下，也做不到无缝，我一直调用consumer接口，滚动更新provider，consumer会有报错的时候，

**Comment by RekaDowney** [comment]
> > 可以使用`NacosRule` , 在Nacos控制台下线后，会立刻感知。
> 
> 试验了下，也做不到无缝，我一直调用consumer接口，滚动更新provider，consumer会有报错的时候，

确实是这样，我这边也是用NacosRule，滚动更新都是新实例已经可用了，这时候下线旧实例（通过 K8S 的 preStop 触发服务下线），但还是访问到了旧实例。有什么办法能够解决嘛，始终会有最少1秒不可用。 @yuhuangbin 
nacos 版本：1.4.1
测试方式：死循环不停请求A服务（A服务通过 NacosRule 负载访问 B服务），B服务滚动更新，此时 A 服务依然会访问到 B服务的旧实例。

**Comment by balainit** [comment]
最后是怎么解决的？有朋友分享分享经验？

**Comment by LittleShrimp1987** [comment]
如果是k8s，可以使用preStop优化一下，可以做到无损下线

**Comment by qooke** [comment]
@LittleShrimp1987 方便分享分享你是怎么做的？

**Comment by LittleShrimp1987** [comment]
> @LittleShrimp1987 方便分享分享你是怎么做的？

原理很简单，利用k8s的prestop调用，先反注册，然后等待一定时长。再下线服务。这样这些操作都是自动的了，无需人工干预。可以看我的文章： https://my.oschina.net/u/4022819/blog/5528262

```
@ReadOperation
public String preStop() {
    nacosServiceRegistry.deregister(registration);
    try {
        Thread.sleep(6 * 1000);
    } catch (Exception ex) {
        LOGGER.error("error when prestop sleep", ex);
    }
    LOGGER.info("prestop");
    return "ok";
}
```
