### ISSUE TITLE
why is not inner version of dependencies the same

### ISSUE THREAD

**Issue by sagittar** [alibaba/spring-cloud-alibaba#1148]
为什么内部依赖的版本都不一致

**Comment by fangjian0423** [comment]
Hi, which component version is inconsistency and where is it? Thanks

**Comment by sagittar** [comment]
> Hi, which component version is inconsistency and where is it? Thanks

![image](https://user-images.githubusercontent.com/7836009/71571811-27c9cc00-2b17-11ea-8d0e-3e33ff95df91.png)
![image](https://user-images.githubusercontent.com/7836009/71571885-88590900-2b17-11ea-83b1-72b97044bce4.png)

一种是spring-cloud-alibaba自己的依赖，另一种和spring-cloud-starter-openfeign

**Comment by fangjian0423** [comment]
The dependencies has been optimized via a27d0e2c7101fa35470c21ff96360378f1bb494b. Thanks for your report.
