### ISSUE TITLE
Sentinel 1.7.1版本跟最新的cloud alibaba 2.1.1整合出现控制台提示 失败：invalid type

### ISSUE THREAD

**Issue by a2501521908** [alibaba/spring-cloud-alibaba#1152]
您好，我这边在整合Sentinel的时候，使用的版本是 1.7.1的控制台，我的cloud版本是2.1.1
```java
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>`
```
我的控制台版本是1.7.1

我的code全部都是按照 https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel 来的，才刚刚编写，控制台检测到应用的存在了，点击对其流控的时候，出现了 “失败：invalid type”，是我的版本问题吗?
我看控制台的doc上面说的是版本问题，我这边都是获取的最新的呀？

**Comment by runzexia** [comment]
2.1.1 要用sentinel 1.7.0 
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by a2501521908** [comment]
感谢老哥，解决了。
希望遇见同样问题的小伙伴可以看看上面的版本信息~

**Comment by sczyh30** [comment]
See https://github.com/alibaba/Sentinel/wiki/控制台#62-规则推送

> 注：若通过控制台推送规则时出现 invalid type 或 empty type 的错误，请确保 transport 模块版本与 core 模块版本保持一致；若控制台版本 >= 1.7.1，请将接入端的相关依赖也升级至 1.7.1 及以上版本。

**Comment by a2501521908** [comment]
> See [https://github.com/alibaba/Sentinel/wiki/控制台#62-规则推送](https://github.com/alibaba/Sentinel/wiki/%E6%8E%A7%E5%88%B6%E5%8F%B0#62-%E8%A7%84%E5%88%99%E6%8E%A8%E9%80%81)
> 
> > 注：若通过控制台推送规则时出现 invalid type 或 empty type 的错误，请确保 transport 模块版本与 core 模块版本保持一致；若控制台版本 >= 1.7.1，请将接入端的相关依赖也升级至 1.7.1 及以上版本。

感谢老哥

**Comment by fangjian0423** [comment]
👍
