### ISSUE TITLE
重启服务，不能重启成功，必须删除nacos的服务列表才行

### ISSUE THREAD

**Issue by lixiangfei4** [alibaba/spring-cloud-alibaba#1166]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by fangjian0423** [comment]
Please use the newest version, thanks.
