### ISSUE TITLE
[Sentinel] version update & use SentinelWebInterceptor instead of CommonFilter

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#1168]
**Which Component**

Sentinel

**Is your feature request related to a problem? Please describe.**

1. Version upgrade to 1.7.1
2. Use [SentinelWebInterceptor](https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/SentinelWebInterceptor.java) instead of [CommonFilter](https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-web-servlet/src/main/java/com/alibaba/csp/sentinel/adapter/servlet/CommonFilter.java)

**Comment by yuhuangbin** [comment]
I will fix it.
