### ISSUE TITLE
能否支持外置tomcat？

### ISSUE THREAD

**Issue by livepool1** [alibaba/spring-cloud-alibaba#1169]
我使用spring-cloud-alibaba-nacos-discovery作为服务发现组件，但我注意到示例中使用的是spring boot启动，使用spring boot内置tomcat。如果我想用war包部署到tomcat，可以实现吗？

**Comment by fangjian0423** [comment]
duplicate with https://github.com/alibaba/spring-cloud-alibaba/issues/154
