### ISSUE TITLE
Why there are org.springframework.cloud.spring-cloud-alibaba-dependencies and com.alibaba.cloud.spring-cloud-alibaba-dependencies exists?

### ISSUE THREAD

**Issue by BinWu1989** [alibaba/spring-cloud-alibaba#1180]
**Which Component**
The Dependency Pom

**Describe what problem you have encountered**
Why there are org.springframework.cloud.spring-cloud-alibaba-dependencies and com.alibaba.cloud.spring-cloud-alibaba-dependencies exists? Both seems in maintain,but the org.springframework.cloud version is a little bite old, So which one shall I use?What's the plan for these two version?  

@mercyblitz @spencergibb @lovepoem @spring-buildmaster

**Comment by fangjian0423** [comment]
Spring Cloud Alibaba has been graduated from Spring Cloud incubator organization and groupId changed to `com.alibaba.cloud`, refer [Version specification](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E).

If you have any problems, refer [Spring Cloud Roadmap and Hoxton and Greenwich Maintenance and EOL Announcements](https://spring.io/blog/2019/12/23/spring-cloud-roadmap-and-hoxton-and-greenwich-maintenance-and-eol-announcements) and [Simplifying the Spring Cloud Release Train](https://spring.io/blog/2019/07/24/simplifying-the-spring-cloud-release-train).

**Comment by BinWu1989** [comment]
@fangjian0423 Why not keep the groupId?

**Comment by spencergibb** [comment]
Because Alibaba doesn't have rights to publish to the old group id.
