### ISSUE TITLE
只是增加了nacos-discovery的maven依赖并未在Application类上增加@EnableDiscoveryClient注解，服务注册和发现功能也表现正常，这算bug吗?

### ISSUE THREAD

**Issue by showcup** [alibaba/spring-cloud-alibaba#1182]
只是增加了nacos-discovery的maven依赖并未在Application类上增加@EnableDiscoveryClient注解，服务注册和发现功能也表现正常，@EnableDiscoveryClient等于形同虚设了，这算bug吗?

版本信息：
spring boot:2.1.1.RELEASE
spring cloud:Greenwich.SR4
alibaba cloud:2.1.1.RELEASE

**Comment by fangjian0423** [comment]
It's not a bug, refer https://github.com/alibaba/spring-cloud-alibaba/issues/333.
