### ISSUE TITLE
Spring cloud gateway启用Nacos服务注册中心，如果serviceId配置了listOfServers的话，但还是从nacos取serverList最后导致服务找不到

### ISSUE THREAD

**Issue by showcup** [alibaba/spring-cloud-alibaba#1183]
Spring cloud gateway启用Nacos服务注册中心，如果serviceId配置了listOfServers的话，但还是从nacos取serverList，最后导致服务找不到，配置如下：
上面省略...
    routes:
      - id: website-lb-byContextPath
         uri: lb://boot-website
         predicates:
          - Path=/spring-boot/**
         filters:
          - StripPrefix=0

boot-website:  
  ribbon:
    nacos:
      enabled: false
    listOfServers: localhost:8070, localhost:8071

boot-website并未注册在nacos注册中心的(此时只是想用网关来代理不在服务注册中心注册的服务)，以上配置期望在网关转发选取服务ip时从配置中的listOfServers中获取，现在只要是加入了nacos-discovery依赖则上面的配置则会自动从nacos中获取serverList，而忽略了配置的listOfServers，如果是eureka做服务注册中心可以通过xxserviceId.ribbon.eureka.enabled:false来单个服务关闭，而nacos却不支持类似xxserviceId.ribbon.nacos.enabled:false这个配置，请问这算是一个bug吗？有没有什么解决方案呢？

环境版本：
spring boot:2.1.1.RELEASE
spring cloud:Greenwich.SR4
alibaba cloud:2.1.1.RELEASE

**Comment by fangjian0423** [comment]
Refer https://github.com/alibaba/spring-cloud-alibaba/issues/1056.
