### ISSUE TITLE
nacos客户端支持配置多个地址用逗号分割吗

### ISSUE THREAD

**Issue by showcup** [alibaba/spring-cloud-alibaba#1187]
nacos客户端支持配置多个地址用逗号分割吗？像这样子spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848,127.0.0.1:8849

**Comment by pigxcloud** [comment]
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html
看这个  用NGINX 反代 nacos 集群

**Comment by chuntaojun** [comment]
支持的
