### ISSUE TITLE
2.1.1.RELEASE did not remove spring-cloud://localhost property

### ISSUE THREAD

**Issue by itbeeZh** [alibaba/spring-cloud-alibaba#1188]
根据2.1.0.RELEASE 版本日志，问题 #592  应该得到解决，但是在2.1.1.RELEASE 中发现 spring-cloud 仍然存在

According to the 2.1.0.RELEASE release log, issue #592  should be resolved, but found that spring-cloud still exists in 2.1.1.RELEASE

**Comment by fangjian0423** [comment]
It works well in my local, could you provide a project that reproduces the issue?

**Comment by itbeeZh** [comment]
[zframe.zip](https://github.com/alibaba/spring-cloud-alibaba/files/4143695/zframe.zip)
![深度截图_选择区域_20200202161658](https://user-images.githubusercontent.com/25598861/73605384-8b448f00-45d8-11ea-8c41-80960a82f992.png)

**Comment by itbeeZh** [comment]
![image](https://user-images.githubusercontent.com/25598861/73605397-b16a2f00-45d8-11ea-816d-2ec980ef3766.png)
不好意思，春节期间没即时反馈

**Comment by cygmris** [comment]
same problem. the registry address(localhost:9090 by default) is being used to fetch public ip from interfaces, which makes the error:` java.net.ConnectException: Connection refused (Connection refused)` occur at `org.apache.dubbo.config.ServiceConfig.findConfigedHosts(ServiceConfig.java:698)`

**Comment by cygmris** [comment]
```
  registries:
    new:
      address: spring-cloud://ip138.com:80
``
config syntax above solves your issue

@itbeeZh .

**Comment by itbeeZh** [comment]
> ```
> dubbo:
>   registries:
>     new:
>       address: spring-cloud://ip138.com:80
> ```
> 
> config syntax above solves your issue
> 
> @itbeeZh .


Thanks, I know this configuration method, I am testing the configuration method without using "spring cloud"

**Comment by cygmris** [comment]
```
dubbo:
  registries:
    new:
      address: ip138.com:80
```
without using "spring-cloud"
