### ISSUE TITLE
nacos client printing configuration content it's not secure including sensitive information

### ISSUE THREAD

**Issue by 511098425** [alibaba/spring-cloud-alibaba#1201]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos configuration

**Is your feature request related to a problem? Please describe.**
nacos client printing configuration content in console when application starting. we can find all sensitive information. eg. database configuration 

**Describe the solution you'd like**
provide a switch and desensitize  eg.spring boot actuator

**Describe alternatives you've considered**
desensitize

**Additional context**
printing content class com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder

**Comment by fangjian0423** [comment]
The logs has been removed in 2.2.0.RELEASE. BTW, i don't think it's a problem, we can also visit it by /configprops Endpoint if we remove it in logs.
