### ISSUE TITLE
spring-cloud-alibaba-dubbo not compatible with the latest version of Dubbo

### ISSUE THREAD

**Issue by kcswag** [alibaba/spring-cloud-alibaba#1202]
The current version of spring-cloud-alibaba-dubbo is not compatible with the latest version (2.7.5) of Dubbo. 
Exceptions occurred when application running:  "java.lang.NoClassDefFoundError: org/apache/dubbo/config/spring/util/PropertySourcesUtils at com.alibaba.cloud.dubbo.env.DubboNonWebApplicationEnvironmentPostProcessor.getRestPortFromProtocolsProperties(DubboNonWebApplicationEnvironmentPostProcessor.java:152)"
I checked the Dubbo 2.7.5 code and found that the reference files and classes were removed.

**Comment by fangjian0423** [comment]
we are working on it, related https://github.com/alibaba/spring-cloud-alibaba/issues/1159.
