### ISSUE TITLE
spring-cloud-alibaba下载编译失败

### ISSUE THREAD

**Issue by spiritelf** [alibaba/spring-cloud-alibaba#1208]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-alibaba-nacos-config

**Describe the bug**
build error

**To Reproduce**
1. mvn clear install
2.[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
21.0:test (default-test) on project spring-cloud-alibaba-nacos-config: There are
 test failures.
[ERROR]
[ERROR] Please refer to E:\spring-cloud-latest\spring-cloud-alibaba\spring-cloud
-alibaba-nacos-config\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].
dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying good
bye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""D:\Program Files\Java\jdk1.8.0_22\jre\bin\ja
va" -javaagent:E:\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.3\\org.jacoco.
agent-0.8.3-runtime.jar=destfile=E:\\spring-cloud-latest\\spring-cloud-alibaba\\
spring-cloud-alibaba-nacos-config\\target\\jacoco.exec -jar C:\Users\huang\AppDa
ta\Local\Temp\surefire8771424848866833764\surefirebooter599808855792950095.jar C
:\Users\huang\AppData\Local\Temp\surefire8771424848866833764 2020-02-19T09-19-16
_498-jvmRun1 surefire5225922951523589527tmp surefire_264918646416729470352tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionE
xception The forked VM terminated without properly saying goodbye. VM crash or S
ystem.exit called?
[ERROR] Command was cmd.exe /X /C ""D:\Program Files\Java\jdk1.8.0_22\jre\bin\ja
va" -javaagent:E:\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.3\\org.jacoco.
agent-0.8.3-runtime.jar=destfile=E:\\spring-cloud-latest\\spring-cloud-alibaba\\
spring-cloud-alibaba-nacos-config\\target\\jacoco.exec -jar C:\Users\huang\AppDa
ta\Local\Temp\surefire8771424848866833764\surefirebooter599808855792950095.jar C
:\Users\huang\AppData\Local\Temp\surefire8771424848866833764 2020-02-19T09-19-16
_498-jvmRun1 surefire5225922951523589527tmp surefire_264918646416729470352tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awa
itResultsDone(ForkStarter.java:494)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run
SuitesForkPerTestSet(ForkStarter.java:441)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run
(ForkStarter.java:293)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run
(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute
Provider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute
AfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute

**Additional context**
e.g.  Windows7  、Java8 、latest

**Comment by fangjian0423** [comment]
It works well on circleci and my local, maybe it has some problems in your maven environment.
