### ISSUE TITLE
Make application bootstrap fail when Nacos service register failed.

### ISSUE THREAD

**Issue by anson0370** [alibaba/spring-cloud-alibaba#1212]
**Which Component**
spring-cloud-alibaba-nacos-discovery

**Is your feature request related to a problem? Please describe.**
Application bootstrap do not failed when Nacos service register failed. This is not a problem some times. But when you run the application and the Nacos server in one docker compose file, it will cause problem if the application start before Nacos server. You will get an application running without register to Nacos and need to reboot it manually.

**Describe the solution you'd like**
Give a property like `spring.cloud.nacos.discovery.fast-failed` which it's default value is false, and stop the application bootstrap if the property is set as true.

**Describe alternatives you've considered**
Maybe keep trying register until success or reach a limit?

**Additional context**

**Comment by fangjian0423** [comment]
It will throw exception in 2.2.0.RELEASE, refer https://github.com/alibaba/spring-cloud-alibaba/issues/1132.

**Comment by anson0370** [comment]
Sorry my fault. Using spring boot 2.1.6 and didn't check the newer version. I'll try to upgrade spring boot to 2.2.x. Is it possible to have a 2.1.x version with this issue fixed?

**Comment by fangjian0423** [comment]
2.1.2 will do it.

**Comment by anson0370** [comment]
Great. Should I close this issue or keep it open? Feel free to close it.

**Comment by fangjian0423** [comment]
keep it open and i will close it where 2.1.2 release.
