### ISSUE TITLE
When to support batch consume

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#1219]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zkzlx** [comment]
please try the beta version #2029 to see if it solves your problem, or provide us more information to help find the latent bug.
