### ISSUE TITLE
Nacos文档没有同步更新

### ISSUE THREAD

**Issue by longnamehh** [alibaba/spring-cloud-alibaba#1224]
![image](https://user-images.githubusercontent.com/31299690/75945650-cd156d80-5ed5-11ea-8046-958911ef136d.png)

废弃了，但是文档还是老的，换成了哪一个也没说，还是说不能共享配置了？

**Comment by yuhuangbin** [comment]
```
spring.cloud.nacos.config.shared-configs[0].data-id=yourDataid
spring.cloud.nacos.config.shared-configs[0].group=yourGroup
spring.cloud.nacos.config.shared-configs[0].refresh=true
```
We changed the Nacos configuration at Spring Cloud Alibaba 2.2.0.RELEASE version. At the same time we are compatible with previous configuration methods

**Comment by yuhuangbin** [comment]
Wiki has been updated
