### ISSUE TITLE
【Nacos】How to configure global refresh？

### ISSUE THREAD

**Issue by longnamehh** [alibaba/spring-cloud-alibaba#1225]
How does Nacos configure global refresh instead of adding the @refreshscope annotation？

**Comment by chuntaojun** [comment]
Is it the cloud project

**Comment by longnamehh** [comment]
yes

**Comment by chuntaojun** [comment]
This problem will be transferred to spring-cloud-alibaba

**Comment by echooymxq** [comment]
> What is global refresh? As far as I know, if a bean is ConfigurationPropertiesBean, the bean also will refresh without RefreshScope.

You may be able to define your configuration in a custom configuration properties class.

**Comment by longnamehh** [comment]
> > What is global refresh? As far as I know, if a bean is ConfigurationPropertiesBean, the bean also will refresh without RefreshScope.
> 
> You may be able to define your configuration in a custom configuration properties class.
Nacos only through @ RefreshScope annotations to refresh the configuration to take effect, otherwise unable to automatically refresh the cache, has opened automatically refresh configuration spring. cloud. nacos. config. refresh - enabled = true

**Comment by echooymxq** [comment]
The `refreshEnabled` is default opened. No need to specify it explicitly. I mean that if your bean is not a `ConfigurationPropertiesBean`, you must declare with @RefreshScope.
