### ISSUE TITLE
【Nacos】How to configure global refresh？

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/spring-cloud-alibaba#1226]
https://github.com/alibaba/spring-cloud-alibaba/issues/1225

**Comment by echooymxq** [comment]
What is global refresh? As far as I know, if a bean is `ConfigurationPropertiesBean`, the bean also will refresh without `RefreshScope`.

**Comment by chuntaojun** [comment]
My mistake, the two items were reversed

**Comment by chuntaojun** [comment]
> What is global refresh? As far as I know, if a bean is `ConfigurationPropertiesBean`, the bean also will refresh without `RefreshScope`.

Please go back to the issue of 1225
