### ISSUE TITLE
[Nacos]  Nacos is release 1.2.0 . When does the spring-cloud-alibaba support the new version?

### ISSUE THREAD

**Issue by DerekHQ** [alibaba/spring-cloud-alibaba#1227]
Nacos is release  version 1.2.0, it permission model is changed. But spring-cloud-alibaba current version is not support this.
When does the spring-cloud-alibaba support the new version?
So expect it in a future release!

Thank you!

**Comment by yuhuangbin** [comment]
We will adapt in the next version of Spring Cloud Alibaba.

**Comment by DerekHQ** [comment]
Excellent！

**Comment by yuhuangbin** [comment]
Spring Cloud Alibaba目前还没有正式适配nacos 1.2.0

如果想提前体验的话，可以排除Spring Cloud Alibaba依赖的nacos 1.1.4版本，再依赖最新nacos 1.2.0版本

配置：
spring.cloud.nacos.config.context-path=/nacos
spring.cloud.nacos.config.username=xxx
spring.cloud.nacos.config.password=xxx

注册：
spring.cloud.nacos.discovery.username=xxx
spring.cloud.nacos.discovery.password=xxx


因为非正式适配，所以后续Spring Cloud Alibaba正式适配后，可能对上述用户名密码配置项有调整喔
