### ISSUE TITLE
【Nacos】Not logged in

### ISSUE THREAD

**Issue by longnamehh** [alibaba/spring-cloud-alibaba#1228]
![image](https://user-images.githubusercontent.com/31299690/75963040-c7348200-5eff-11ea-8f7d-176992032be6.png)
![image](https://user-images.githubusercontent.com/31299690/75963242-17134900-5f00-11ea-9cc6-3177f17189b5.png)

Why not go to the home page instead of the login form? 
Does anyone else have this problem？

**Comment by mercyblitz** [comment]
Because of you have to login first
