### ISSUE TITLE
spring-cloud Hoxton.SR3中feign升级接口方法名称改了

### ISSUE THREAD

**Issue by sanliu2015** [alibaba/spring-cloud-alibaba#1235]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

Sentinel

stared error like below:
com.alibaba.cloud.sentinel.feign.SentinelContractHolder does not define or inherit an implementation of the resolved method 'abstract java.util.List parseAndValidateMetadata(java.lang.Class)' of interface feign.Contract

Contract change from parseAndValidatateMetadata to parseAndValidateMetadata

e.g.  win10、Java8 、 spring-cloud-Hoxton.SR3、spring-cloud-alibaba 2.2.0

**Comment by yuhuangbin** [comment]
Spring Cloud Alibaba 2.2.0.RELEASE is based on Spring Cloud Hoxton.RELEASE.

**Comment by fangjian0423** [comment]
@sanliu2015 Thanks for your report. The next Spring Cloud Alibaba version based on Hoxton.SR3
