### ISSUE TITLE
spring.cloud.nacos.discovery.ip or domain-name

### ISSUE THREAD

**Issue by yl-yue** [alibaba/spring-cloud-alibaba#1245]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
是否可以通过域名注册
Whether can register through domain name.
`spring.cloud.nacos.discovery.domain-name=ylyue.cn`

**Describe what information you have read**
![image](https://user-images.githubusercontent.com/39790401/76389481-44e80a00-63a6-11ea-92d6-880227beeead.png)

我想我的某个微服务可以通过域名方式注册到 Nacos 上面，并且以域名的方式进行转发与调用，使用域名注册主要是因为内网穿透的原因，有的同事在外地进行开发，需要注册到公司这里提供的注册中心来，并做相互通信调用。

I think one of my microservices can be registered to Nacos by domain name, and forwarded and invoked by domain name. Domain name registration is mainly for the reason of internal network penetration. Some colleagues are in the field for development, so they need to register with the registry provided by the company here, and communicate with each other.

**Comment by echooymxq** [comment]
try `spring.cloud.nacos.discovery.ip=`?

**Comment by yl-yue** [comment]
> try `spring.cloud.nacos.discovery.ip=`?

这里是可以配置域名，注册到Nacos上面的值是字符串未作检查，但我使用 `spring.cloud.nacos.discovery.ip=ylyue.cn` 配置域名并注册到nacos上面之后，spring-cloud-gateway 并不能做转发，或许不是 nacos 的原因。

Here is you can configure the domain name, registered to Nacos above the value of the string is not checked, but I use `spring.cloud.nacos.discovery.ip=ylyue.cn` configuration domain and registered to Nacos, spring-cloud-gateway and cannot be forwarded, may not be the Nacos reasons.

**Comment by lcg72** [comment]
这里的端口即便是80，也需要显式指定:80,试试改成
spring.cloud.nacos.discovery.domain-name=ylyue.cn:80

Even if the port here is 80, you need to specify it explicitly: 80, try changing it to
spring.cloud.nacos.discovery.domain-name=ylyue.cn:80

**Comment by yl-yue** [comment]
## 使用中文进行问题描述
问题已解决，升级到 Spring Cloud Starter Gateway » 2.1.5.RELEASE 后解决。通过 feign 调用并没有问题，这是springcloudgateway的错误。
被调用的服务配置如下：
```yml
spring:
  cloud:
    nacos:
      server-addr: 192.168.3.51:30100
      discovery:
        ip: ylyue.qicp.vip
        port: 80
```

## Describe the problem in English

The problem has been solved. upgrade to Spring Cloud Starter Gateway » 2.1.5.RELEASE
