### ISSUE TITLE
spring.application.name contains "_" like "cloud_alibaba_sms_service" not correct where use @@LoadBalanced

### ISSUE THREAD

**Issue by huhuamin** [alibaba/spring-cloud-alibaba#1249]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Discovery

**Describe the bug**
name contains "_" like "cloud_alibaba_sms_service" not correct  where use @@LoadBalanced

**To Reproduce**
but name change "_" to "-" like "cloud_alibaba_sms_service" is right where use @@LoadBalanced
#官网 可以正常使用 LoadBalancerClient loadBalancerClient方式
#nacos服务列表 示例代码 用报错@Bean @LoadBalanced
# NACOS1.2.0
#
#<groupId>com.alibaba.cloud</groupId>
#<artifactId>spring-cloud-alibaba-dependencies</artifactId>
#<version>2.2.0.RELEASE</version>

#官网 可以正常使用 LoadBalancerClient loadBalancerClient方式
#nacos服务列表 示例代码 用报错@Bean @LoadBalanced
# NACOS1.2.0
#
#<groupId>com.alibaba.cloud</groupId>
#<artifactId>spring-cloud-alibaba-dependencies</artifactId>
#<version>2.2.0.RELEASE</version>

#先看结果
#LoadBalancerClient 正常 可以理解
request path:http://192.168.31.148:8803/echo/cloud_alibaba_sms_consumer
"Hello Nacos Discovery cloud_alibaba_sms_consumer"
#@LoadBalanced RestTempate 不行 nacos 不是自动依赖netfix ribbion吗
2020-03-12 02:43:14.333 ERROR 52475 --- [nio-8813-exec-3] c.h.s.exception.GlobalExceptionHandler   : Request URI does not contain a valid hostname: http://cloud_alibaba_sms_service/echo/cloud_alibaba_sms_consumer

#代码
@SpringBootApplication
@EnableDiscoveryClient
public class NacosConsumerApp {
     @Bean
    public RestTemplate restTemplate() {
        RestTemplate temp = new RestTemplate();
        return temp;
    }

    @Bean
    @LoadBalanced
    public RestTemplate restTemplateLoad() {
        RestTemplate temp = new RestTemplate();
        return temp;
    }

    @RestController
    public class NacosController{

        @Autowired
        private LoadBalancerClient loadBalancerClient;
        @Autowired
        private Map<String, RestTemplate> restTemplateMap;
        @Autowired
        private LoadBalancerClient loadBalancerClient;

        @Value("${spring.application.name}")
        private String appName;

        @GetMapping("/echo/app-name")
        public String echoAppName(){
            //Access through the combination of LoadBalanceClient and RestTemplate
        ServiceInstance serviceInstance = loadBalancerClient.choose(ServiceName.CLOUD_ALIBABA_SMS_SERVICE);
        String path = String.format("http://%s:%s/echo/%s", serviceInstance.getHost(), serviceInstance.getPort(),appName);
        String path2 = String.format("http://%s/echo/%s", ServiceName.CLOUD_ALIBABA_SMS_SERVICE, appName);
        System.out.println("request path:" + path);
        String result=restTemplateMap.get("restTemplate").getForObject(path, String.class);
        System.out.println(result);
        // @LoadBalanced 通过服务名访问，不行
        return restTemplateMap.get("restTemplateLoad").getForObject(path2, String.class);
        }

    }

    //Instantiate RestTemplate Instance
    public static void main(String[] args) {

        SpringApplication.run(NacosConsumerApp.class,args);
    }
}

**Screenshots**

**Additional context**
MacOS  、Java8 、 spring-cloud-alibaba-nacos-discovery Version 2.2.0.RELEASE

**Comment by huhuamin** [comment]
change "_" to "-" LoadBalancerClient @Bean @LoadBalanced  all right

**Comment by yuhuangbin** [comment]
```java
String url = "http://abc_server/api";
// the host 'abc_server' will be lost
URI uri = URI.create(url);
```

**Comment by huhuamin** [comment]
package com.huhuamin;

import lombok.extern.slf4j.Slf4j;

import java.net.URI;

/**
 * @Auther: Huhuamin
 * @Date: 2020/3/15 15:46
 * @Description:
 */
@Slf4j
public class Testmai {
    public static void main(String[] args) {
        String url = "http://abc_server/api";
// the host 'abc_server' will be lost
        URI uri = URI.create(url);
        log.info(uri.toString());
    }
}

15:48:20.570 [main] INFO com.huhuamin.Testmai - http://abc_server/api

lost what?

**Comment by yuhuangbin** [comment]
```java
String url = "http://abc_server/api";
// the host 'abc_server' will be lost
URI uri = URI.create(url);
System.out.println(uri.getHost());
```

**Comment by lcg72** [comment]
这其实是规范决定域名不能用下划线，你可以尝试申请带下划线的域名，都不会检验通过。
