### ISSUE TITLE
Nacos怎么实现像Ribbon的listOfServers功能

### ISSUE THREAD

**Issue by daigong** [alibaba/spring-cloud-alibaba#1263]
Nacos怎么实现像Eureka一样的listOfServers功能,以便我本地服务可以和DEV环境服务交互，
否则我得本地启动全套微服务注册到Nacos，要么将本地服务注册到DEV，然后调用DEV环境其他服务。非常麻烦~

https://github.com/alibaba/nacos/issues/2363

**Comment by yuhuangbin** [comment]
remove the nacos discovery dependency
```
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
```

**Comment by yuhuangbin** [comment]
ribbon.nacos.enable=false

**Comment by yuhuangbin** [comment]
可以把nacos注册发现功能关闭，就会读取listOfServers

**Comment by yuhuangbin** [comment]
```
spring.cloud.nacos.discovery.enabled=false
service-provider.ribbon.listOfServers=localhost:18082
```

**Comment by daigong** [comment]
调试期想 nacos自动发现和 本地配置共存，很多调试场景还是很方便的

我提了一个pr

**Comment by yuhuangbin** [comment]
使用`spring.cloud.nacos.discovery.enabled=false`来关闭nacos服务发现，能解决你的问题。 @daigong

**Comment by daigong** [comment]
@yuhuangbin 抱歉哈，我可能没有表述清楚：

背景：
case1 ：我们有部分项目是django写的，由于跨数据中心等复杂性我们也不打算使用sidecar的方式注册
case2：其他公司API接口跨IDC访问，我们也想使用相同的feign定义方法，由配置文件解耦
case3：在Debug环境下，我们想让DEBUG代码可以调用UAT、FAT环境，但又不影响UAT、FAT环境调用

这三个场景虽然可以使用mock等方式解决，但是实际上非常麻烦，所以考虑想Eurka一样引入ServerList的方式让 **Nacos注册和ServerList配置**共存，但spring.cloud.nacos.discovery.enabled=false 一旦配置，Nacos就不好用了

我搜了下issue，https://github.com/alibaba/nacos/issues/2363 以前也有类似需求

**Comment by yuhuangbin** [comment]
listOfServers这个配置项是ribbon `ConfigurationBasedServerList`提供的一种本地配置负载策略，跟注册中心应该没有关系，如果你想使用这个本地负载策略，那就把注册中心服务发现能力关闭就行了，你本地调用UAT环境也是可以的。参考使用
`spring.cloud.nacos.discovery.enabled=false`
`ribbon.nacos.enabled=false`

**Comment by daigong** [comment]
是否有种配置是 nacos自动发现 和 ConfigurationBasedServerList 的ServerList 共存呢？

**Comment by yuhuangbin** [comment]
`yourServiceId.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList`

**Comment by daigong** [comment]
> yourServiceId.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList

一开始我也想过这么配置，但是没有生效；甚至胡乱配置一个ClassName上去都没有报错：ClassNotFound

yourServiceId.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerListXXXXSomeThing

我使用的是：
v2.1.1.RELEASE

感谢您的耐心

**Comment by yuhuangbin** [comment]
debug [NacosRibbonClientConfiguration](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.java#L46)

**Comment by yuhuangbin** [comment]
2.1.1.RELEASE版本还没有支持, [NacosRibbonClientConfiguration](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.java#L46)

**Comment by yuhuangbin** [comment]
升级到 Spring Cloud Alibaba 2.2.0.RELEASE， Spring Cloud Hoxton.RELEASE

**Comment by daigong** [comment]
多谢，我找到问题原因了，

v2.1.1.RELEASE 代码没有读取配置等特性
this.propertiesFactory.isSet(ServerList.class, config.getClientName())

以下是 tag v2.1.1.RELEASE 或 branch:greenwich 的 NacosRibbonClientConfiguration 代码

https://github.com/alibaba/spring-cloud-alibaba/blob/3d09d46615b1eead7647fcddc1795a187431e4b9/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.java#L40

最新的master是没问题的，这个分支是否还可以修改？我提个PR也行

**Comment by yuhuangbin** [comment]
> 多谢，我找到问题原因了，
> 
> v2.1.1.RELEASE 代码没有读取配置等特性
> this.propertiesFactory.isSet(ServerList.class, config.getClientName())
> 
> 以下是 tag v2.1.1.RELEASE 或 branch:greenwich 的 NacosRibbonClientConfiguration 代码
> 
> https://github.com/alibaba/spring-cloud-alibaba/blob/3d09d46615b1eead7647fcddc1795a187431e4b9/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.java#L40
> 
> 最新的master是没问题的，这个分支是否还可以修改？我提个PR也行

welcome

**Comment by cooljser** [comment]
2023 版本也同样有这个问题，是否可以支持？
