### ISSUE TITLE
some problems when update nacos from 1.1.4 to 1.2.0

### ISSUE THREAD

**Issue by shihuaguo** [alibaba/spring-cloud-alibaba#1271]
I update springboot,spring cloud and spring cloud alibaba's version from 
`<spring-boot.version>2.1.13.RELEASE</spring-boot.version>
<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
<spring-cloud-alibaba.version>2.1.1.RELEASE</spring-cloud-alibaba.version>`
to
`<spring-boot.version>2.2.5.RELEASE</spring-boot.version>
        <spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>`
then encounter some problems:
1、service can't register to nacos, i have read some related issue, this will resolved in next version;
2、configuration created in version 1.1.4 lost，i queryed in database, the config records in config_info table exists, but they lost in nacos admin console.
3、spring cloud gateway can't startup, it can't distinguish spring.cloud.gateway.routes[0].uri=lb://xxx config, when bingding to GatewayProperties, it's routes property's uri property is null。

**Comment by yuhuangbin** [comment]
Nacos 1.2.0 has been adapted, please wait for the next version of spring cloud Alibaba

**Comment by yuhuangbin** [comment]
You can go to the Nacos community to inquire about the loss of configuration data after upgrading

**Comment by shihuaguo** [comment]
ok,i have import configuration from files that exported before.

**Comment by mercyblitz** [comment]
Please wait for next release.

**Comment by yuhuangbin** [comment]
refer: #1305
