### ISSUE TITLE
condition nacos config HealthIndicator with ConditionalOnEnabledHealthIndicator

### ISSUE THREAD

**Issue by fudali113** [alibaba/spring-cloud-alibaba#1276]
https://github.com/alibaba/spring-cloud-alibaba/blob/3c6a54c8899fd21d15db7c3adbcdc0e121a0b6cc/spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java#L55

healthIndicator common condition annotation is ConditionalOnEnabledHealthIndicator

**Comment by yuhuangbin** [comment]
I think `@ConditionalOnEnabledHealthIndicator` is better, what do you think? @echooymxq

**Comment by yuhuangbin** [comment]
@fudali113 Can you contribute pr to fix it?

**Comment by fudali113** [comment]
> @fudali113 Can you contribute pr to fix it?

ok, but what version delete  the original `@ConditionalOnProperty` implement ?   @yuhuangbin

**Comment by yuhuangbin** [comment]
> ok, but what version delete the original `@ConditionalOnProperty` implement

you can fix it at master branch
