### ISSUE TITLE
nacos注册403无权限

### ISSUE THREAD

**Issue by zhl19911203** [alibaba/spring-cloud-alibaba#1282]
nacos开启用户认证之后，服务注册报403错误，这个bootstrap.yml无法配置用户名和密码

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Mar 24 15:58:39 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

**Comment by yuhuangbin** [comment]
Wait for the next Spring Cloud Alibaba Version.

**Comment by zhl19911203** [comment]
> Wait for the next Spring Cloud Alibaba Version.

那这个预计什么时候更新，目前有临时解决方案吗
我的nacos版本是1.2版本
spring-cloud-alibaba版本2.2.0

**Comment by yuhuangbin** [comment]
> > Wait for the next Spring Cloud Alibaba Version.
> 
> 那这个预计什么时候更新，目前有临时解决方案吗
> 我的nacos版本是1.2版本
> spring-cloud-alibaba版本2.2.0

拉取master分支代码，本地打包构建

**Comment by yuhuangbin** [comment]
hi, refer issue : #1305
