### ISSUE TITLE
RocketMQ Demo from Alibaba Initializer can't run at local

### ISSUE THREAD

**Issue by Gsealy** [alibaba/spring-cloud-alibaba#1287]
**Which Component**
don't find `start.aliyun.com` repo, so open a issue in here.
[start.aliyun.com](https://start.aliyun.com/)

**Describe the bug**
create a rocketmq demo. but has some errors
1. `RocketMQProduceConfiguration.class` import a undefined class `com.alibaba.cloud.sca.demo.rocketmq.Foo` at line 19. `Foo.class` was copy to ` com.example.demo.rocketmq.Foo`, maybe should use this?

2. have same bean name( `customRunner` ) in `RocketMQProduceConfiguration.class` and `RocketMQConsumerConfiguration.class`

3. fix above and configure MQ's address to run it. `ObjectMapper` don't configure.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method rocketMQTemplate in com.alibaba.cloud.stream.binder.rocketmq.config.RocketMQComponent4BinderAutoConfiguration required a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'jacksonObjectMapper' in 'JacksonAutoConfiguration.JacksonObjectMapperConfiguration' not loaded because @ConditionalOnClass did not find required class 'org.springframework.http.converter.json.Jackson2ObjectMapperBuilder'


Action:

Consider revisiting the entries above or defining a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' in your configuration.
```

**To Reproduce**
1. Download demo [link](https://start.aliyun.com/#!type=maven-project&language=java&platformVersion=2.2.5.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=sca-rocketmq)
2. Run it on your computer

**Expected behavior**
demo should can be run, Instead of same use sample class.

**Comment by theonefx** [comment]
thank you for your feedback, and we have fixed it already.
