### ISSUE TITLE
sidecar异构注册nacos时指定group时会额外启动一个default实例

### ISSUE THREAD

**Issue by M1NGc** [alibaba/spring-cloud-alibaba#1292]
![image](https://user-images.githubusercontent.com/26264126/77718134-119bb100-701d-11ea-9aa1-25c3410eb80b.png)
这是nacos注册页面
![image](https://user-images.githubusercontent.com/26264126/77718624-5ecc5280-701e-11ea-9a91-62c6cc7dac1b.png)
这是控制台注册信息 (ps:nacos拼错了)
 跟踪了一下注册流程没找到问题

**Comment by M1NGc** [comment]
![image](https://user-images.githubusercontent.com/26264126/77738864-88e83980-704b-11ea-8de3-c8f705737aee.png)
补充一下这是配置文件

**Comment by yuhuangbin** [comment]
It is no problem to register an additional instance of sidecar with nacos, I will solve the related problems of custom grouping and port.

**Comment by dpwujingchun** [comment]
由于sidecar.ip的地址是内部地址，这样由gateway的LB:服务名，就是成功一次失败一次。同一服务两个实例，一个一次。
