### ISSUE TITLE
2.0.x升级dubbo到2.7.5报错

### ISSUE THREAD

**Issue by chirspan** [alibaba/spring-cloud-alibaba#1310]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Dubbo

**Describe what problem you have encountered**
基础模块都是基于Finchley版本，由于quartz和dubbo冲突，需要升级dubbo版本。出现以下错误
java.lang.ClassNotFoundException: org.apache.dubbo.config.spring.util.PropertySourcesUtils

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by lcg72** [comment]
用这个补丁包试一下，如果没有问题，我就提交修复代码

Try this patch. If there is no problem, I will submit the repair code


[hansbo-patch-spring-cloud-alibaba-2.2.0-RELEASE.jar.zip](https://github.com/alibaba/spring-cloud-alibaba/files/4419218/hansbo-patch-spring-cloud-alibaba-2.2.0-RELEASE.jar.zip)
