### ISSUE TITLE
ClientWorker  一直循环打印日志

### ISSUE THREAD

**Issue by itlidaye** [alibaba/spring-cloud-alibaba#1313]
2020-04-02 15:45:06.070  INFO 7565 --- [bd-aedf53df1e04] c.a.n.client.config.impl.ClientWorker    : [fixed-172.16.72.97_8848-bda7516f-d140-4adf-8cbd-aedf53df1e04] [polling-resp] config changed. dataId=api-comm-result.yaml, group=DEFAULT_GROUP, tenant=bda7516f-d140-4adf-8cbd-aedf53df1e04
2020-04-02 15:45:06.270  INFO 7565 --- [bd-aedf53df1e04] c.a.n.client.config.impl.ClientWorker    : [fixed-172.16.72.97_8848-bda7516f-d140-4adf-8cbd-aedf53df1e04] [polling-resp] config changed. dataId=api-comm-result.yaml, group=DEFAULT_GROUP, tenant=bda7516f-d140-4adf-8cbd-aedf53df1e04
2020-04-02 15:45:06.271  INFO 7565 --- [bd-aedf53df1e04] c.a.n.client.config.impl.ClientWorker    : [fixed-172.16.72.97_8848-bda7516f-d140-4adf-8cbd-aedf53df1e04] [data-received] dataId=api-comm-result.yaml, group=DEFAULT_GROUP, tenant=bda7516f-d140-4adf-8cbd-aedf53df1e04, md5=0a5e535138eb013a700b526f9594e6c9, content=resultmap:

**Comment by magese** [comment]
+1
配置文件没有进行任何修改，但是持续打印 `config changed.`日志

**Comment by MrLin-619** [comment]
+1 

- 我也一样，升级到nacos1.2.1+spring-cloud-alibaba2.2.1就出现了这个问题，升级前（2.2.0）是没问题的

- 代码如下

```
                  Properties properties = new Properties();
			properties.put(PropertyKeyConst.SERVER_ADDR, nacosProperties.getServerAddr());
			properties.put(PropertyKeyConst.USERNAME, nacosProperties.getUsername());
			properties.put(PropertyKeyConst.PASSWORD, nacosProperties.getPassword());
			ConfigService configService = NacosFactory.createConfigService(properties);
			String content = configService.getConfig(DATA_ID, "DEFAULT_GROUP", 5000);
			log.info("初始化网关路由开始");
			updateRoute(content);
			log.info("初始化网关路由完成");

			//开户监听，实现动态
			configService.addListener(DATA_ID, "DEFAULT_GROUP", new Listener() {
				@Override
				public void receiveConfigInfo(String configInfo) {
					log.info("更新网关路由开始");
					updateRoute(configInfo);
					log.info("更新网关路由完成");
				}

				@Override
				public Executor getExecutor() {
					return null;
				}
			});
```

- 日志如下，控制台一直刷新
```
2020-04-16 12:10:52.998  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-base-nacos_8848] [polling-resp] config changed. dataId=dynamic_routes, group=DEFAULT_GROUP
2020-04-16 12:10:52.998  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[dynamic_routes+DEFAULT_GROUP]
2020-04-16 12:10:53.021  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-base-nacos_8848] [data-received] dataId=dynamic_routes, group=DEFAULT_GROUP, tenant=null, md5=07bf53a9f068777b46c7f62b2686fbc8, content=routes:
# auth
...
```
把configService.addListener监听注释掉就不报了

**Comment by baobeidaodao** [comment]
+1

**Comment by MrLin-619** [comment]
> +1
> 
> * 我也一样，升级到nacos1.2.1+spring-cloud-alibaba2.2.1就出现了这个问题，升级前（2.2.0）是没问题的
> * 代码如下
> 
> ```
> Properties properties = new Properties();
> properties.put(PropertyKeyConst.SERVER_ADDR, nacosProperties.getServerAddr());
> properties.put(PropertyKeyConst.USERNAME, nacosProperties.getUsername());
> properties.put(PropertyKeyConst.PASSWORD, nacosProperties.getPassword());
> ConfigService configService = NacosFactory.createConfigService(properties);
> String content = configService.getConfig(DATA_ID, "DEFAULT_GROUP", 5000);
> log.info("初始化网关路由开始");
> updateRoute(content);
> log.info("初始化网关路由完成");
> 
> //开户监听，实现动态
> configService.addListener(DATA_ID, "DEFAULT_GROUP", new Listener() {
> 	@Override
> 	public void receiveConfigInfo(String configInfo) {
> 		log.info("更新网关路由开始");
> 		updateRoute(configInfo);
> 		log.info("更新网关路由完成");
> 	}
> 
> 	@Override
> 	public Executor getExecutor() {
> 		return null;
> 	}
> });
> ```
> 
> * 日志如下，控制台一直循环打印
> 
> ```
> 2020-04-16 12:10:52.998  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-base-nacos_8848] [polling-resp] config changed. dataId=dynamic_routes, group=DEFAULT_GROUP
> 2020-04-16 12:10:52.998  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[dynamic_routes+DEFAULT_GROUP]
> 2020-04-16 12:10:53.021  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-base-nacos_8848] [data-received] dataId=dynamic_routes, group=DEFAULT_GROUP, tenant=null, md5=07bf53a9f068777b46c7f62b2686fbc8, content=routes:
> # auth
> ...
> 2020-04-16 12:10:53.998  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-base-nacos_8848] [polling-resp] config changed. dataId=dynamic_routes, group=DEFAULT_GROUP
> 2020-04-16 12:10:52.998  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[dynamic_routes+DEFAULT_GROUP]
> 2020-04-16 12:10:53.021  INFO 19692 --- [base-nacos_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-base-nacos_8848] [data-received] dataId=dynamic_routes, group=DEFAULT_GROUP, tenant=null, md5=07bf53a9f068777b46c7f62b2686fbc8, content=routes:
> # auth
> ...
> ```
> 
> 把configService.addListener监听的代码注释掉就不报了

在配置文件最后加个空换行就不报了

**Comment by dljunzhuo** [comment]
+1 我也碰到过这个问题

**Comment by cwh1022** [comment]
+1 我这边把那个一直`config changed`那个配置的自动刷新关掉了就好了

**Comment by i402097836** [comment]
遇到了同样的问题，求解决 ，无线循环打印

**Comment by alloevil** [comment]
hi,i get the same problem here is my pom
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.5.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>xxx</groupId>
    <artifactId>xx</artifactId>
    <version>develop/v1.x</version>
    <name>xx</name>
    <description>provide data view</description>
    <packaging>jar</packaging>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    
    
    
    
    
    
    
    
    
    


    
    
    
    
    
    
    
    
    

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>2.2.1.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Hoxton.SR4</version>
            <type>pom</type>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.10</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>29.0-jre</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.4</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.6</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
            <version>1.9.6</version>
        </dependency>

        <dependency>
            <groupId>org.jasig.cas.client</groupId>
            <artifactId>cas-client-core</artifactId>
            <version>3.3.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.4</version>
        </dependency>

        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>3.2.2</version>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.1.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba:fastjson</groupId>
                    <artifactId>1.2.58</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>2.2.1.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <version>2.3.0.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.68</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
`

**Comment by pigxcloud** [comment]
nacos 1.2.1 bug

**Comment by hejinxu** [comment]
确实，配置文件修改一下就不报了（最后加一个空行）

**Comment by majingxuan123** [comment]
修改一下配置文件  加个回车 保存之后就不输出了
应该是bug吧

**Comment by 1239656678** [comment]
真正的原因是，在新建命名空间的时候没有指定命名空间ID
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/55818926/7aea34c5-53c9-454f-8801-a9a6a213e6fa)
而在配置里面配置的确实public导致
正确的应该是配置指定的具体的命名空间id

**Comment by ros275229** [comment]
thanks so much!
