### ISSUE TITLE
关于seata参数disableGlobalTransaction，一直打印警告的问题

### ISSUE THREAD

**Issue by lethwoo** [alibaba/spring-cloud-alibaba#1314]
在使用spring-cloud-starter-alibaba-seata，以自动方式@EnableAutoConfiguration装配时，application.properties文件中，按照seata-example中的配置方式：
`seata.enabled=true`
`spring.cloud.alibaba.seata.tx-service-group=business-service`
`seata.service.vgroup-mapping.business-service=default`
`seata.service.grouplist.default=127.0.0.1:8091`
`seata.service.disable-global-transaction=false`
如果在service某个方法中使用了@GlobalTransactional注解，启动service后，控制台会一直打印一行警告：
`io.seata.config.FileConfiguration        : Could not found property service.disableGlobalTransaction, try to use default value instead.`
如果在application.properties文件中加入以下配置
`service.disableGlobalTransaction=false`
则不会打印警告。请问这是我哪儿没配置好，还是此版本的bug？

**Comment by M1NGc** [comment]
https://github.com/seata/seata/pull/2219 看看这个是不是相同的问题

**Comment by lethwoo** [comment]
> [seata/seata#2219](https://github.com/seata/seata/pull/2219) 看看这个是不是相同的问题

确实是版本问题，我使用的spring-cloud-alibaba-dependencies版本是2.2.0.RELEASE，该版本依赖的是1.0.0的seata-spring-boot-starter，改成1.1.0的就ok了
