### ISSUE TITLE
the register-enabled configuration doesn't work in non-web environment

### ISSUE THREAD

**Issue by hexiangtao** [alibaba/spring-cloud-alibaba#1325]
Type: *bug report* 

### what happend

The register-enabled configuration doesn't work when my project (framework:dubbo+nacos) has only task threads and subscribes only to other services without registering itself. 
If I don't set the port property value of The **NacosDiscoveryProperties** (default is -1), naocs server will throw an exception when calling **namingService.registerInstance**.
The exception was found by debug because the parameter port value was -1, which did not match  the regular expression
(当我的项目(dubbo+nacos)只有task线程，只订阅其它服务不需要注册自己时，register-enabled 配置为false并不起作用.nacos client还是会去注册该实例，然后在调用namingService.registerInstance时传的参数里port值为-1，naocs server端收到请求后会根据serviceId加port的方式验证是否符合表达式**(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):?(\\d{1,5})**?),因为port为-1不符合 **?(\\d{1,5})**?)**,然后会抛一个异常,异常信息如下:

Excetipon message:
> java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:localhost:8848/nacos/v1/ns/instance. code:500 msg: ErrCode:400, ErrMsg:instance format invalid: Your IP address is spelled incorrectly

如果我手动设置一个port值大于-1的整数，就不会有该异常,然后注册成功（可以规避)。但实际情况我的项目并不需要绑定指定端口，无须设置port,也不想注册到nacos上。

### DubboServiceRegistrationNonWebApplicationAutoConfiguration
```java
	@EventListener(ApplicationStartedEvent.class)
	public void onApplicationStarted() {
		setServerPort();
		register();
	}
```
### NacosServiceRegistry
```java
	@Override
	public void register(Registration registration) {
			namingService.registerInstance(serviceId, instance);
	}
```

###  com.alibaba.nacos.naming.core.Instance
```java
private static final Pattern IP_PATTERN
        = Pattern.compile("(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):?(\\d{1,5})?");

    public void validate() throws NacosException {
        if (onlyContainsDigitAndDot()) {
            Matcher matcher = IP_PATTERN.matcher(getIp() + ":" + getPort());
            if (!matcher.matches()) {
                throw new NacosException(NacosException.INVALID_PARAM, "instance format invalid: Your IP address is spelled incorrectly");
            }
        }

        if (getWeight() > MAX_WEIGHT_VALUE || getWeight() < MIN_WEIGHT_VALUE) {
            throw new NacosException(NacosException.INVALID_PARAM, "instance format invalid: The weights range from " +
                MIN_WEIGHT_VALUE + " to " + MAX_WEIGHT_VALUE);
        }

    }

```

### environment
* spring-cloud-alibaba-nacos-discovery:2.1.0
* :nacos-server-1.1.4
* spring-cloud-alibaba-dubbo-2.1.0

**Comment by lcg72** [comment]
discover的端口必须要设置吧，不然到哪里去订阅呢？

**Comment by hexiangtao** [comment]
> discover的端口必须要设置吧，不然到哪里去订阅呢？你这个场景只要设置register-enabled为false就不会注册到nacos，其他配置不变，就可以订阅。

```yml
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
```

```java
	/**
	 * The port your want to register for your service instance, needn't to set it if the
	 * auto detect port works well.
	 */
	private int port = -1;
````

discovery的端口在server-addr里，port应该是用来标识 所要注册的实例的端口吧？ 我的意思是如果不设置port(默认为-1),register-enabled为falsae的话，nacos server端就会报一个异常。

**Comment by lcg72** [comment]
2.2.1下测试了一下，设置spring.main.web-application-type=none,这个时候设置spring.cloud.nacos.discovery.register-enabled=false还是会注册，确实有点问题，报错还是不会。

**Comment by hexiangtao** [comment]
naocs server用的哪个版本?，你可以看  namingService.registerInstance(serviceId, instance)提交的参数里port为-1，过不了 nacos server端的(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):?(\d{1,5})?)验证

**Comment by lcg72** [comment]
不需要到那一步，设置register-enabled=false，不应该走register()方法

**Comment by lcg72** [comment]
你拉下代码https://github.com/lcg72/spring-cloud-alibaba.git本地打包测试一下，看是否符合你需要的场景

**Comment by hexiangtao** [comment]
走register()方法是因为非web环境触发的是的DubboServiceRegistrationNonWebApplicationAutoConfiguration

```java
	@EventListener(ApplicationStartedEvent.class)
	public void onApplicationStarted() {
		setServerPort();
		register();
	}
```
而在web环境下不register是因NacosAutoServiceRegistration类的父类AbstractAutoServiceRegistration.start()方法里调用isEnabled()方法。

```java
	public void start() {
		if (!isEnabled()) {
			if (logger.isDebugEnabled()) {
				logger.debug("Discovery Lifecycle disabled. Not starting");
			}
			return;
		}
````

```java
	@Override
	protected boolean isEnabled() {
		return this.registration.getNacosDiscoveryProperties().isRegisterEnabled();
	}
```
这里给拦截了

**Comment by hexiangtao** [comment]
你拉下代码[https://github.com/lcg72/spring-cloud-alibaba.git本地打包测试一下，看是否符合你需要的场景](https://github.com/lcg72/spring-cloud-alibaba.git%E6%9C%AC%E5%9C%B0%E6%89%93%E5%8C%85%E6%B5%8B%E8%AF%95%E4%B8%80%E4%B8%8B%EF%BC%8C%E7%9C%8B%E6%98%AF%E5%90%A6%E7%AC%A6%E5%90%88%E4%BD%A0%E9%9C%80%E8%A6%81%E7%9A%84%E5%9C%BA%E6%99%AF)

符合

**Comment by yuhuangbin** [comment]
try `spring.cloud.service-registry.auto-registration.enabled=false` ? @hexiangtao

**Comment by lcg72** [comment]
> try `spring.cloud.service-registry.auto-registration.enabled=false` ? @hexiangtao

I tested it, OK. @hexiangtao You can test it again.

**Comment by hexiangtao** [comment]
It works.
