### ISSUE TITLE
2.2.0版本 UrlBlockHandler这个类都没了

### ISSUE THREAD

**Issue by hqxy** [alibaba/spring-cloud-alibaba#1328]
版本
![image](https://user-images.githubusercontent.com/24350787/78423808-9af55800-769b-11ea-9a9b-a96bc802bb7e.png)

我连UrlBlockHandler这个类都找不到了- - 请问是有什么其他的类进行了替代吗 看文档上还是写的这个类去自定义

**Comment by tanaduus** [comment]
BlockExceptionHandle

**Comment by echooymxq** [comment]
Use `BlockExceptionHandler`, v2.2.0 has upgrade to `sentinel` v.1.7.1, and use `sentinel-spring-webmvc-adapter` to replace `sentinel-web-servlet`.
