### ISSUE TITLE
SMS模块的wiki实例代码有问题

### ISSUE THREAD

**Issue by huangyuzhong** [alibaba/spring-cloud-alibaba#1333]
这里的方法声明返回的是SendBatchSmsResponse对象，但是下面return的却用了sendSmsRequest（）返回SendSmsResponse对象，这样容易给初学者造成困扰:
/**
     * 短信发送 Example
     * @param code
     * @return
     */
    @RequestMapping("/batch-sms-send.do")

    public SendBatchSmsResponse batchsendCheckCode(
            @RequestParam(name = "code") String code) {

        // 组装请求对象-具体描述见控制台-文档部分内容
        SendSmsRequest request = new SendSmsRequest();
        // 必填:待发送手机号
        request.setPhoneNumbers("152******");
        // 必填:短信签名-可在短信控制台中找到
        request.setSignName("******");
        // 必填:短信模板-可在短信控制台中找到
        request.setTemplateCode("******");
        // 可选:模板中的变量替换JSON串,如模板内容为"【企业级分布式应用服务】,您的验证码为${code}"时,此处的值为
        request.setTemplateParam("{\"code\":\"" + code + "\"}");
        SendSmsResponse sendSmsResponse ;
        try {
            sendSmsResponse = smsService.sendSmsRequest(request);
        }
        catch (ClientException e) {
            e.printStackTrace();
            sendSmsResponse = new SendSmsResponse();
        }
        return sendSmsResponse ;
    }

**Comment by mercyblitz** [comment]
`sendSmsRequest` is just a method name, is not like a Getter method.
