### ISSUE TITLE
请优化模糊查询功能

### ISSUE THREAD

**Issue by kqkdChen** [alibaba/spring-cloud-alibaba#1341]
例如我想搜索 dataId 以 **kinhoodcloud** 开头的文件
![image](https://user-images.githubusercontent.com/41674301/78855222-eae66d00-7a55-11ea-9069-bc4a06e220c8.png)
可实际上发现搜索结果为空
![image](https://user-images.githubusercontent.com/41674301/78855291-12d5d080-7a56-11ea-8534-0049ce6230ba.png)
不敢相信会出现这种结果，是哪里有问题吗？

**Comment by yuhuangbin** [comment]
try `kinhoodcloud*` ?

**Comment by kqkdChen** [comment]
> try `kinhoodcloud*` ?

是的，这样结果可以出现，但需要带通配符有点莫名其妙。就这样吧
