### ISSUE TITLE
nacos读取配置问题

### ISSUE THREAD

**Issue by zhangchaoyanggit** [alibaba/spring-cloud-alibaba#1356]
nacos 读取配置问题  spring.application.name  以 user开头 读取不到 是关键字问题吗?

**Comment by yuhuangbin** [comment]
Please provide more information.

**Comment by yuhuangbin** [comment]
The [Nacos Config Example](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/java/com/alibaba/cloud/examples/Application.java) is test pass.
