### ISSUE TITLE
[Announce] Spring Cloud Alibaba 2.2.1.RELEASE, 2.1.2.RELEASE and 2.0.2.RELEASE released

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/spring-cloud-alibaba#1357]
Hello Community,

I am glad to announce that Spring Cloud Alibaba 2.2.1.RELEASE, 2.1.2.RELEASE and 2.0.2.RELEASE are released.

You can check detailed release notes here: 
- 2.2.1.RELEASE (Hoxton SR3) : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.1.RELEASE
- 2.1.2.RELEASE (Greenwich SR5 ) : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.1.2.RELEASE
- 2.02.RELEASE (Finchley SR4) : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.0.2.RELEASE

If you have any questions using this version, please report the [issue](https://github.com/alibaba/spring-cloud-alibaba/issues) on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by liaozan** [comment]
spring-cloud-alibaba released the 2.2.1.RELEASE version. I noticed that revision is used instead of project.version, which makes it impossible to find the dependencies of the following related components in the maven central repository, dubbo, seata, acm, ans, oss, schedulerx, sms

**Comment by mercyblitz** [comment]
> spring-cloud-alibaba released the 2.2.1.RELEASE version. I noticed that revision is used instead of project.version, which makes it impossible to find the dependencies of the following related components in the maven central repository, dubbo, seata, acm, ans, oss, schedulerx, sms

Did you build from source or download from Maven repository?

**Comment by liaozan** [comment]
> > spring-cloud-alibaba released the 2.2.1.RELEASE version. I noticed that revision is used instead of project.version, which makes it impossible to find the dependencies of the following related components in the maven central repository, dubbo, seata, acm, ans, oss, schedulerx, sms
> 
> Did you build from source or download from Maven repository?

tried both，[https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dubbo](url),you can see from this link that the latest version is 2.2.0.RELEASE

**Comment by fungoddd** [comment]
There is no 2.0.2.release in Maven warehouse
![image](https://user-images.githubusercontent.com/45350522/79429230-d37d2600-7ff9-11ea-8477-6c7f622dcbea.png)

**Comment by imkiven** [comment]
> There is no 2.0.2.release in Maven warehouse
> ![image](https://user-images.githubusercontent.com/45350522/79429230-d37d2600-7ff9-11ea-8477-6c7f622dcbea.png)

I have the same problem

**Comment by upcwangying** [comment]
@imkiven  I have the same issue

**Comment by mercyblitz** [comment]
Checking...

**Comment by yangbajing** [comment]
Is there a support plan for Spring Cloud 2.3?

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年
http://weibo.ws/zZNbxG

阿里云企业级服务器1折限时特惠
http://weibo.ws/SIyDRE

阿里云建站 速成美站 - 千套模板，价格低至500元
http://weibo.ws/yVQAYW

**Comment by liaozan** [comment]
> 阿里云服务器，限时秒杀价低至102/年
> http://weibo.ws/zZNbxG
> 
> 阿里云企业级服务器1折限时特惠
> http://weibo.ws/SIyDRE
> 
> 阿里云建站 速成美站 - 千套模板，价格低至500元
> http://weibo.ws/yVQAYW

@mercyblitz

**Comment by upcwangying** [comment]
> 阿里云服务器，限时秒杀价低至102/年
> 
> http://weibo.ws/zZNbxG
> 
> 
> 
> 阿里云企业级服务器1折限时特惠
> 
> http://weibo.ws/SIyDRE
> 
> 
> 
> 阿里云建站 速成美站 - 千套模板，价格低至500元
> 
> http://weibo.ws/yVQAYW

打广告打到这里来了，要脸不？
