### ISSUE TITLE
spring cloud alibaba 2.21，sentinel 配置nacos 数据源，nacos 1.2.1 开启权限认证，无法认证

### ISSUE THREAD

**Issue by letian-tang** [alibaba/spring-cloud-alibaba#1362]
spring cloud alibaba 2.21
sentinel 配置nacos 数据源，nacos 1.2.1 开启权限认证。在NacosDataSourceProperties，没有属性设置nacos的username和password

**Comment by yuhuangbin** [comment]
refer: #1350
