### ISSUE TITLE
sidecar fix 1292 but cause another question

### ISSUE THREAD

**Issue by M1NGc** [alibaba/spring-cloud-alibaba#1370]
https://github.com/alibaba/spring-cloud-alibaba/issues/1292
2.2.0.Realease这是之前指定group时 会默认创建default_group的issue
2.2.1.Realease 版本解决了此问题  
但是引起了另一个问题
xxxx.29:10010为python服务
xxxx.1:10011 为java sidecar服务
配置及console信息
![image](https://user-images.githubusercontent.com/26264126/79205246-3d69c400-7e70-11ea-9971-b6f8c5c1614f.png)
nacos dashboard
![image](https://user-images.githubusercontent.com/26264126/79205341-5e321980-7e70-11ea-8294-772b98a2870b.png)

注册时会把这两个都注册上去变成两个实例   
,应该只需要注册xxxx.29:10010实例

**Comment by yuhuangbin** [comment]
`sidecar` instance  will also register.

**Comment by M1NGc** [comment]
异构服务为python xxxx.29:10010  载体为java xxxx.1:10011  
2.2.0.realease 注册服务时自定义group    实例只有python URL 但是会额外注册一个default_group实例
2.2.1.realease 注册服务时自定义group    实例有python URL 和java URL两个实例地址
现在想只想注册python地址 而不注册java URL  可以实现这种需求吗

**Comment by yuhuangbin** [comment]
sidecar 会额外注册一个实例，这是正常的

**Comment by M1NGc** [comment]
可是我其他服务请求的时候不就会轮训请求到java URL吗?可我java没有这个接口  真正接口在python上  引起接口调用超时    或者有配置可以忽略这个实例

**Comment by echooymxq** [comment]
@M1NGc you can set `spring.cloud.nacos.discovery.register-enabled=false`  on sidecar.

**Comment by echooymxq** [comment]
@yuhuangbin Perhaps some improvements can be made.. usually, sidecar only registry the `heterogeneous service` instance.
