### ISSUE TITLE
dubbo服务提供者实例数量变更时不会通知到服务消费者

### ISSUE THREAD

**Issue by lvwd0088** [alibaba/spring-cloud-alibaba#1376]
spring cloud alibaba v2.2.0
注册配置中心：nacos
项目间调用：dubbo
现象：先启动服务提供者A的实例A1，接着启动服务消费者实例B，B启动后会订阅服务提供者A1。然后启动服务提供者A的实例A2，启动后服务消费者实例B不会订阅A2，也就是说B不会更新服务提供者A的实例列表，但将B重启后B即可订阅服务提供者A的实例A1和A2
疑问：当服务提供者拓容时，运行中服务消费者可否感知并更新订阅列表

**Comment by yuhuangbin** [comment]
can you try upgrade Spring Cloud Alibaba version to `2.2.1.RELEASE`, Spring Cloud version to `Hoxton.SR3` and  test again?
