### ISSUE TITLE
为什么我使用了sentinel-spring-cloud-gateway-example  发现限流并未起作用

### ISSUE THREAD

**Issue by lianbitangjin** [alibaba/spring-cloud-alibaba#1378]
Why did I use sentinel spring cloud gateway example to find that current limiting didn't work？
为什么我使用了sentinel-spring-cloud-gateway-example  发现限流并未起作用

I set the stand-alone threshold to 0 and still can access the page
单机阈值 我设置为0了依然可以访问到页面

**Comment by yuhuangbin** [comment]
可以在resources资源目录下新建SPI文件，
文件名：`/META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder`
文件内容：`com.alibaba.csp.sentinel.adapter.gateway.common.slot.GatewaySlotChainBuilder`

**Comment by lianbitangjin** [comment]
有用，解决了我的问题

**Comment by zzfengxia** [comment]
在使用spring-cloud-alibaba-sentinel-gateway，spring-cloud-starter-alibaba-sentinel整合的gateway限流需要添加SPI文件限流才能生效。而使用sentinel-spring-cloud-gateway-adapter实现的不需要添加SPI文件。想请问下这个是BUG还是机制就是这样！
