### ISSUE TITLE
spring-cloud-starter-alibaba:pom:2.2.1.RELEASE   maven pom 版本没有发布

### ISSUE THREAD

**Issue by itlidaye** [alibaba/spring-cloud-alibaba#1380]
spring-cloud-starter-alibaba:pom:2.2.1.RELEASE   maven pom 版本没有发布

**Comment by mercyblitz** [comment]
`spring-cloud-starter-alibaba` has been removed since 2.2.1, please use `spring-cloud-alibaba-starters` instead of it.
