### ISSUE TITLE
how to invoke a remote service on a specified provider?

### ISSUE THREAD

**Issue by Zx55** [alibaba/spring-cloud-alibaba#1381]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Discovery, Dubbo

**Describe what problem you have encountered**
Hi. I' m writing a mirco-service project with spring-cloud-alibaba. In some case, I want to invoke a remote service on a specified provider through Dubbo. Is there a solution?

**Describe what information you have read**
I have read some blogs about Dubbo and tried `RpcContext.getContext().setRemoteAddress(ip, port)`, but it didn' t work. 

Also, `RpcContext.getContext().getRemoteAddress()` always returns null. I am not sure whether the ip and port that I passed to the method are valid in this situation.

**Comment by mercyblitz** [comment]
You could try to use @Reference(url="dubbo://${host}:${port}"), for example : https://github.com/apache/dubbo-spring-boot-project/blob/master/dubbo-spring-boot-samples/auto-configure-samples/consumer-sample/src/main/java/org/apache/dubbo/spring/boot/demo/consumer/bootstrap/DubboAutoConfigurationConsumerBootstrap.java#L38

**Comment by Zx55** [comment]
In my case, I want specify provider during runtime.

**Comment by baozheliu** [comment]
> In my case, I want specify provider during runtime.
> e.g.
> 
> ```java
> @Reference
> DemoService service;
> 
> void foo() {
>     String ip = getIp();
>     int port = getPort();
>     // specify service provided by ip:port
>     service.doSomething();
> }
> ```

Hi, I had the same problem, how did you end up resolving it?
