### ISSUE TITLE
阿里购买的rocketmq 连接不上 

### ISSUE THREAD

**Issue by LYDXY** [alibaba/spring-cloud-alibaba#1390]
spring.cloud.stream.rocketmq.binder.access-key，spring.cloud.stream.rocketmq.binder.secret-key
这两个连不上 阿里购买的 rocketmq ,,,,,,,一样的代码连接 本地的 rocketmq 就没问题，，，，，

**Comment by zhourundong** [comment]
是不是端口没开

**Comment by LYDXY** [comment]
购买的是阿里 的直接产品， 直接 拿 tpc 公网链接 或者 http 公网连接 连不上 ，ecs 部署的才需要端口吧，直购的 mq 我看文档，不需要端口啊

**Comment by LYDXY** [comment]
我用 阿里云 rocketmq 文档的代码测试没问题，就是集成 这个项目的 rocketmq 模块连不上 阿里直购的 rocketmq

**Comment by for2cold** [comment]
@LYDXY 请问您解决了吗，遇到同样的问题……

**Comment by LYDXY** [comment]
我解决了，你去看wiki.再搞不明白加我qq 1542319159------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Kazyle&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月6日(星期五) 下午3:07
收件人:&nbsp;&quot;alibaba/spring-cloud-alibaba&quot;<spring-cloud-alibaba@noreply.github.com&gt;;
抄送:&nbsp;&quot;林尧&quot;<1542319159@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] 阿里购买的rocketmq 连接不上  (#1390)

**Comment by for2cold** [comment]
解决了，要加上阿里云RocketMQ的实例ID，这个“实例ID”有点……

**Comment by xsffsx** [comment]
我也是连接 阿里云购买的 rocketMQ，官方例子可以 publish 消息，但是 spring cloud binder alibaba死活连不上，
请问实例 ID 的配置 配置在哪？

**Comment by xsffsx** [comment]
我也是连接 阿里云购买的 rocketMQ，官方例子可以 publish 消息，但是 spring cloud binder alibaba死活连不上，
请问实例 ID 的配置 配置在哪？

**Comment by for2cold** [comment]
> 我也是连接 阿里云购买的 rocketMQ，官方例子可以 publish 消息，但是 spring cloud binder alibaba死活连不上，
> 请问实例 ID 的配置 配置在哪？

MQ实例ID%topic
![image](https://user-images.githubusercontent.com/2671804/121130381-edfb0a00-c860-11eb-89b8-4b27dfe48208.png)

**Comment by xsffsx** [comment]
> > 我也是连接 阿里云购买的 rocketMQ，官方例子可以 publish 消息，但是 spring cloud binder alibaba死活连不上，
> > 请问实例 ID 的配置 配置在哪？
> 
> MQ实例ID%topic
> ![image](https://user-images.githubusercontent.com/2671804/121130381-edfb0a00-c860-11eb-89b8-4b27dfe48208.png)

yes， you are right,   thanks for save my life.....
spring.cloud.stream.bindings.output.destination=<instanceID>%<topic>
