### ISSUE TITLE
Nacos Discovery add support for hostname

### ISSUE THREAD

**Issue by ClownfishYang** [alibaba/spring-cloud-alibaba#1403]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
I'm not sure if the question is Spring Cloud or Nacos Discovery, but in my judgment, it should be a Nacos Discovery.
我不确定这个问题是Spring Cloud还是Nacos Discovery，但是根据我的判断，它应该属于Nacos Discovery。

**Is your feature request related to a problem? Please describe.**
I now have such clusters A and B, but they are private cloud services, the internal network IP address can not be interacted, can only use the private cloud IP address for communication.
我现在有这样的集群A和B，但它们都是私有云服务，内部网络IP地址不能交互，只能使用私有云IP地址进行通信。

This meant that I had to configure the hostname or domain name for the server to bind to the private cloud IP for communication, but I checked the documentation and found that only Erauke provided this parameter. Although the InetUtils SpringCloud class USES InetUtilsProperties classes to do some configuration Settings, but still can't achieve my goal, in the meantime I use the ignoredInterfaces parameters (value is' [\ s \ s] * '), but findFirstNonLoopbackAddress () calls the InetAddress. Eventually getLocalHost ().
这意味着我必须为服务器配置hostname 或者域名的方式来绑定私有云IP 来进行通信，但是我查阅了文档发现，只有Erauke 提供这种参数。
虽然SpringCloud中的InetUtils类使用了InetUtilsProperties类来进行一些配置化的设置，但依旧不能达到我的目的，在此期间我使用了ignoredInterfaces 参数（值是'[\s\S]*'），但是findFirstNonLoopbackAddress() 最终还是调用了InetAddress.getLocalHost()。

So back to the NacosDiscovery，NacosDiscovery  provides spring.cloud.nacos.discovery.ip parameter (this parameter can fill in the form of a hostname), but I think this parameter should be dynamically acquired rather than specified, because our environment might have dev, test, pro... Although shell scripts in various environments can be specified, this is still tedious work.
再说回NacosDiscovery，NacosDiscovery 提供了spring.cloud.nacos.discovery.ip 参数（这个参数可以填写为hostname 的形式），但是我觉得这个参数应该是动态获取而不是指定，因为我们的环境可能会有dev、test、pro...，尽管在各个环境的shell 脚本能够指定，但这工作依然很繁琐。

综合上面的我更觉得这个问题属于Nacos Discovery，因为InetUtils 提供的HostInfo 信息已经很全了，不是吗？但是Nacos Discovery 却是获取了IP 地址（this.ip = this.inetUtils.findFirstNonLoopbackHostInfo().getIpAddress()）。
Based on the above, I think this problem belongs to Nacos Discovery, because the HostInfo information provided by InetUtils is quite complete, isn't it? But Nacos Discovery gets the IP address(this.inetUtils.findFirstNonLoopbackHostInfo().getIpAddress()).

**Describe the solution you'd like**
1、Nacos Discovery 应该提供一个使用hostname的参数；
1. Nacos Discovery should provide a parameter using hostname;

**Describe alternatives you've considered**
1、比较简单的方法是在Shell 脚本获取hostname 并指定为spring.cloud.nacos.discovery.ip 参数；
2、Nacos Discovery 添加一个使用hostname 的参数；
1, the method is relatively simple for spring. The specified in the Shell script for the hostname and cloud. Nacos. Discovery. IP parameters;
2. Add a parameter using hostname for Nacos Discovery;

**Additional context**

**Comment by yuhuangbin** [comment]
welcome to contribute.
