### ISSUE TITLE
nacos1.2.1longback配置contextName冲突

### ISSUE THREAD

**Issue by kick-pixel** [alibaba/spring-cloud-alibaba#1405]
项目环境如下：
Springboot : 2.1.7.RELEASE
spring-cloud-alibaba-dependencies: 2.1.2.RELEASE
Nacos: 1.2.1

在项目中自定义了logback-spring.xml ，设置contextName为yyc_cms, 启动项目报错如下：
java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [nacos] as [yyc_cms] java.lang.IllegalStateException: Context has been already given a name

这是由于预先加载了nacos的logback配置文件，与自定义的logback的contextName发生了冲突，请问怎么解决

**Comment by yuhuangbin** [comment]
[alibaba/nacos](https://github.com/alibaba/nacos)
