### ISSUE TITLE
规则文件在Jar包内的ClassPath里面，读取失败

### ISSUE THREAD

**Issue by programmer-luxw** [alibaba/spring-cloud-alibaba#1409]
配置了：
spring.cloud.sentinel.datasource.ds1.file.file=classpath: sentinel/flowrule.json
不打成jar可以正常读取到，但是打成jar以后，启动就直接异常了，读取不到jar包里面的classpath文件。
看了源码是：ResourceUtils.getFile不能读取jar包里面的classpath，jar里面的文件只能读取成InputStream.
@Override
	public void preCheck(String dataSourceName) {
		super.preCheck(dataSourceName);
		try {
			this.setFile(
					ResourceUtils.getFile(StringUtils.trimAllWhitespace(this.getFile()))
							.getAbsolutePath());
		}
		catch (IOException e) {
			throw new RuntimeException("[Sentinel Starter] DataSource " + dataSourceName
					+ " handle file [" + this.getFile() + "] error: " + e.getMessage(),
					e);
		}

	}

**Comment by cody1996** [comment]
@programmer-luxw 请问这个问题最后是怎么解决的？我也碰到了相同的问题

**Comment by programmer-luxw** [comment]
配置放redis了，引入他们提供的redis依赖，然后配置一下就行了
spring.cloud.sentinel.datasource.ds1.redis.host=
spring.cloud.sentinel.datasource.ds1.redis.port=
spring.cloud.sentinel.datasource.ds1.redis.password=
spring.cloud.sentinel.datasource.ds1.redis.database=15
spring.cloud.sentinel.datasource.ds1.redis.channel=sentinel-flow-channel
spring.cloud.sentinel.datasource.ds1.redis.rule-key=sentinel-flow-key
spring.cloud.sentinel.datasource.ds1.redis.rule-type=flow
spring.cloud.sentinel.datasource.ds1.redis.timeout=10000ms




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cody1996"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 下午4:07
收件人:&nbsp;"alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com&gt;;
抄送:&nbsp;"卢晓文"<973762159@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] 规则文件在Jar包内的ClassPath里面，读取失败 (#1409)





 
@programmer-luxw 请问这个问题最后是怎么解决的？我也碰到了相同的问题
