### ISSUE TITLE
POM 在打包的时候出现问题

### ISSUE THREAD

**Issue by LyCodingJava** [alibaba/spring-cloud-alibaba#1411]
plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>
                                repackage
                            </goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

如上之前使用 partent 构建 但是现在用这个 为自动加入     <goals>
                            <goal>
                                repackage
                            </goal>
                        </goals>

**Comment by fangjian0423** [comment]
Circleci runs well, i think there is no problem.
