### ISSUE TITLE
spring-cloud-nacos作为注册中心配置文件中enabled和register-enabled属性的关系

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/spring-cloud-alibaba#1413]
使用nacos作为注册中心的话，在配置文件中spring.cloud.nacos.discovery下有enabled和register-enabled属性，但是在NacosDiscoveryProperties类中并没有声明enabled属性，只声明了registerEnabled属性，那么配置文件中enabled这个配置项的作用在哪里体现呢；而且只有当enabled和registerEnabled同时为true时，注册中心才生效；但是源码中只看到了registerEnabled的判断，并没有看到enabled的判断

**Comment by yuhuangbin** [comment]
you can see annotation `@ConditionalOnNacosDiscoveryEnabled` to understand it.

**Comment by HelloHaiNG** [comment]
> you can see annotation `@ConditionalOnNacosDiscoveryEnabled` to understand it.

oh,I see now.ths
