### ISSUE TITLE
 Could not resolve placeholder 'xxx' in value "${xxx}"

### ISSUE THREAD

**Issue by allenhan** [alibaba/spring-cloud-alibaba#1414]
**Which Component**
 Nacos Config

**Describe the bug**
 study from the nacos-config-example.
when i star up the program,it cause Could not resolve placeholder 'xxx' in value "${xxx}" 
it seem not load the property from the nacos.

i do not know why it can not work.

applicatin context:
 <spring.boot.version>2.1.6.RELEASE</spring.boot.version>
        <spring.cloud.verison>Greenwich.SR5</spring.cloud.verison>
        <spring.cloud.alibaba.version>2.1.0.RELEASE</spring.cloud.alibaba.version>

here is config:
=========
bootstrap.yml  
spring:
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        file-extension: properties
  application:
    name: feiting-admin-config
======================
application.yml:
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include: '*'

pom.xml
 <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
    </dependencies>

**Comment by allenhan** [comment]
![image](https://user-images.githubusercontent.com/5449138/80559324-be4bc280-8a0f-11ea-8889-030679068945.png)
add nacos config detail

**Comment by M1NGc** [comment]
Data ID应该是feiting-admin-config.properties
