### ISSUE TITLE
spring-cloud-bus-rocketmq-example could not receive UserRemoteApplicationEvent

### ISSUE THREAD

**Issue by rainsoft** [alibaba/spring-cloud-alibaba#1419]
**Which Component**
spring-cloud-bus-rocketmq-example

**Describe the bug**
When testing the spring-cloud-bus, we found that the example in examples could not receive the UserRemoteApplicationEvent, and the test found that the onEvent (UserRemoteApplicationEvent) did not respond to the event, but the onEvent (RemoteApplicationEvent) could respond and receive the contents of the UserRemoteApplicationEvent event.

```
    @EventListener
    public void onUserEvent(RemoteApplicationEvent event)
        throws JsonProcessingException {
        if (event instanceof UserRemoteApplicationEvent) {
            System.out.printf("Server [port : %d] listeners on %s\n", localServerPort,
                objectMapper.writeValueAsString(event));
        }
    }
```
event instanceof UserRemoteApplicationEvent return false.

**Comment by rainsoft** [comment]
If dependency spring-boot-devtools，will occur this bug。

**Comment by wenlincheng** [comment]
not dependency spring-boot-devtools, will occur this bug too.

**Comment by wenlincheng** [comment]
not dependency spring-boot-devtools, will occur this bug too.
