### ISSUE TITLE
nacos config file-extension 配置失效

### ISSUE THREAD

**Issue by Expried** [alibaba/spring-cloud-alibaba#1422]
![image](https://user-images.githubusercontent.com/10000663/81048542-19d5ee80-8eef-11ea-9f34-819908a78958.png)
![image](https://user-images.githubusercontent.com/10000663/81048603-383bea00-8eef-11ea-8adb-457e046069c0.png)
![image](https://user-images.githubusercontent.com/10000663/81048614-3eca6180-8eef-11ea-9442-6196d67bd231.png)
![image](https://user-images.githubusercontent.com/10000663/81048660-50ac0480-8eef-11ea-992b-b0388b2dcb7c.png)

**Comment by M1NGc** [comment]
试试把 spring.datasource 的key  url 换成jdbc-url

**Comment by yuhuangbin** [comment]
nacos-config相关配置请配置在`bootstrap`
