### ISSUE TITLE
spring.cloud.nacos.config.server-addr 地址为什么默认加上8848端口

### ISSUE THREAD

**Issue by xiaoxiaobanxian** [alibaba/spring-cloud-alibaba#1425]
![image](https://user-images.githubusercontent.com/15420901/81147697-6d0e7680-8fad-11ea-9c8a-3c38eb0c5783.png)
目前我配置的spring.cloud.nacos.discovery.server-addr 的域名就是指向了8848端口的nacos程序，我看源码里面这一段又加上了一个端口，这样我就找不到我的nacos应用了，不知道怎么解决这个问题。

**Comment by M1NGc** [comment]
serverAddrArr.length == 1 进入这个判断 意味着用户没写端口  所以加上默认的
