### ISSUE TITLE
NacosDataPropertiesParser

### ISSUE THREAD

**Issue by myoss** [alibaba/spring-cloud-alibaba#1427]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
 Nacos

**Describe the bug**
1. properties 文件中 " = " 前后有空格，目前不会将 "=" 前后的空格去掉
2. [维基百科中关于.properties文件的定义](https://zh.wikipedia.org/wiki/.properties)

**To Reproduce**
1. 带解析的内容如下：
server.port=8160
#mybatis
spring.server.MaxRequestSize = 500MB
preseLockKey = test-preserLock
2. NacosDataPropertiesParser解析后的结果如下：
<img width="953" alt="Snipaste_2020-05-07_09-09-23" src="https://user-images.githubusercontent.com/6986459/81243483-8e6d7200-9042-11ea-80c2-2f574be04f85.png">
3. java sdk解析结果如下：
<img width="1075" alt="Snipaste_2020-05-07_09-13-17" src="https://user-images.githubusercontent.com/6986459/81243713-2cf9d300-9043-11ea-900b-87867ea87d1d.png">

**Expected behavior**

**Screenshots**

**Additional context**
2.1.2.RELEASE

**Comment by yuhuangbin** [comment]
Refer issue: #987

Combined with the current code, you can use `trim()` to solve. Welcome to contribute pr~

**Comment by myoss** [comment]
现在的key都有空格了，还 trim 呢，这代码写的牛逼，连文件的基本语法格式都没弄明白，也不知道你们怎么审核 pr 的

“spring.server.MaxRequestSize ”

@Value("spring.server.MaxRequestSize") // 没法引用到的
private String key;

**Comment by yuhuangbin** [comment]
> 现在的key都有空格了，还 trim 呢，这代码写的牛逼，连文件的基本语法格式都没弄明白，也不知道你们怎么审核 pr 的
> 
> “spring.server.MaxRequestSize ”
> 
> @value("spring.server.MaxRequestSize") // 没法引用到的
> private String key;

key和value都trim一下，你可以修改你的配置，去掉空格

**Comment by myoss** [comment]
佩服佩服
