### ISSUE TITLE
spring cloud alibaba 版本升级后限流规则失效

### ISSUE THREAD

**Issue by i402097836** [alibaba/spring-cloud-alibaba#1435]
Spirng cloud alibaba version 2.1.1 was used to integrate sentinel and spring cloud gateway, and the current limiting rules were configured through sentinel-dashboard (version 1.7.1). The test found that the current limiting rules were in effect. When upgrading spring cloud alibaba version 2.1.2, all the previously configured current limiting rules did not work.

使用spirng cloud alibaba 2.1.1 版本，sentinel与spring cloud gateway集成，限流规则是通过sentinel-dashboard（1.7.1版）配置的，测试发现限流规则生效，当升级spring cloud alibaba 2.1.2版本后，之前配置的限流规则全部不起作用，需要做什么特殊修改吗？
`@Configuration
public class GatewaySentinelConfiguration {

    private final List<ViewResolver> viewResolvers;
    private final ServerCodecConfigurer serverCodecConfigurer;

    public GatewaySentinelConfiguration(ObjectProvider<List<ViewResolver>> viewResolversProvider,
                                ServerCodecConfigurer serverCodecConfigurer) {
        this.viewResolvers = viewResolversProvider.getIfAvailable(Collections::emptyList);
        this.serverCodecConfigurer = serverCodecConfigurer;
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public SentinelGatewayBlockExceptionHandler sentinelGatewayBlockExceptionHandler() {
        // Register the block exception handler for Spring Cloud Gateway.
        return new SentinelGatewayBlockExceptionHandler(viewResolvers, serverCodecConfigurer);
    }

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public GlobalFilter sentinelGatewayFilter() {
        return new SentinelGatewayFilter();
    }
  
}`

**Comment by yuhuangbin** [comment]
Sentinel 1.7.1-based solution, Refer: #1378 

Spring Cloud Alibaba next version will upgrade sentinel version to 1.7.2 to resolve this issue.
