### ISSUE TITLE
start.aliyun.com 创建OSS项目启动异常

### ISSUE THREAD

**Issue by zhishihuanjue** [alibaba/spring-cloud-alibaba#1437]
异常信息
Failed to instantiate [com.aliyun.oss.OSS]: Factory method 'ossClient' threw exception; nested exception is java.lang.IllegalArgumentException: Oss endpoint can't be empty.
配置文件
# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
spring.cloud.alicloud.access-key=****
spring.cloud.alicloud.secret-key=****

#################################### oss config : ####################################
# oss控制台: https://oss.console.aliyun.com
# oss云存储的EndPoint（地域节点）
# 这里配置的是杭州节点，请根据自己购买的实例进行修改
spring.cloud.alicloud.oss.endpoint=oss-cn-hangzhou.aliyuncs.com

**Comment by theonefx** [comment]
done
the config prefix changed after 2.2.1.RELEASE
