### ISSUE TITLE
sentinel-datasource-spring-cloud-config

### ISSUE THREAD

**Issue by changetest** [alibaba/spring-cloud-alibaba#1439]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 
**Which Component**
eg. Nacos Discovery, Sentinel
----------------sentinel-datasource-spring-cloud-config

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

------------how to use sentinel-datasource-spring-cloud-config
-------------the sentinel-datasource-spring-cloud-config test  can‘t drive
**Describe what information you have read**
eg. I have read the reference doc of Sentinel
------------ I have read the reference doc of Sentinel

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example
