### ISSUE TITLE
sca2.2.1里用dubbo2.7.6 不支持nacos1.2.1注册，但是版本换成2.7.5就可以。

### ISSUE THREAD

**Issue by sundong1982** [alibaba/spring-cloud-alibaba#1444]
sca2.2.1里用dubbo2.7.6 不支持nacos1.2.1注册，但是版本换成2.7.5就可以。目前dubbo那里的example也是2.7.5的。

**Comment by mercyblitz** [comment]
Please add this dependency: https://github.com/apache/dubbo/issues/5956

**Comment by sundong1982** [comment]
我的项目中之前包含了依赖`<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>${dubbo.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>log4j</artifactId>
                    <groupId>log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>`
估计是和nacos1.2.1不兼容
