### ISSUE TITLE
Is there an Exception like HystrixBadRequestException  In Sentinel?

### ISSUE THREAD

**Issue by hanxt** [alibaba/spring-cloud-alibaba#1447]
Is there an Exception like HystrixBadRequestException  In Sentinel?

* In Hystrix ，HystrixBadRequestException  will not trigger fallback which defined on “@FeignClient” interface！so I can turn “remote service error response Body”  into  HystrixBadRequestException  By Feign ErrorDecoder ，and  throw  it out。

* Or put it another way，In sentinel,   there is an exceptionsToIgnore property。How can  I use exceptionsToIgnore   On “@FeignClient”  interface。

**Comment by fangjian0423** [comment]
Try `@FeignClient#fallbackFactory`, refer [ConsumerApplication](https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-demo-beijing-20190526/blob/master/consumer/src/main/java/org/springframework/cloud/alibaba/demo/ConsumerApplication.java#L71).

**Comment by HaojunRen** [comment]
Close this issue with no response for a long time, if any problems, please reopen it

**Comment by 353355756** [comment]
HystrixBadRequestException 异常是不计数的，sentinel会记录到异常数中的。有没有不触发fallback的方案？

**Comment by JimmyQin** [comment]
I also encounter this problem. How to solve it？

**Comment by JimmyQin** [comment]
> I also encounter this problem. How to solve it？

@hanxt

**Comment by zxy1994** [comment]
@hanxt  从你的看云的文档过来的，其实只要让sentinel忽略你抛出的异常（用于流转的业务异常）。可以看看Tracer的api，里面有方法忽略指定的异常，这样不进sentinel的异常计数。还有，如果没指定fallbackFactory，则会自动把异常往上抛。但有个不好的点就是熔断异常，也调用不了fallBackFactory方法。因此需要统一异常处理，处理一下sentienl的相关异常。具体可以参考一下SentinelInvocationHandler的invoke方法。

**Comment by 353355756** [comment]
@zxy1994 您好，有相关示例么？

**Comment by liangenhao** [comment]
目前只能关闭`feign.sentinel`，然后把feign调用包装在一个方法里，方法上添加`@SentinelResource`，指定exceptionsToIgnore来实现了。
