### ISSUE TITLE
nacos开启登录权限后，项目启动时报白名单 403，unknow异常

### ISSUE THREAD

**Issue by MsencSir** [alibaba/spring-cloud-alibaba#1448]
我的项目使用的版本：
spring boot：2.1.14.RELEASE 
spring cloud ： Greenwich.SR5
spring cloud alibaba：0.9.0.RELEASE 
spring-cloud-starter-alibaba-nacos-config：0.9.0.RELEASE 
spring-cloud-starter-alibaba-nacos-discovery：0.9.0.RELEASE

**Comment by MsencSir** [comment]
nacos-server-1.2.1 版本；
开启登录权限后（nacos.core.auth.enabled=true），项目启动时报白名单403，unknow异常！
请问 我应该怎么配置用户名密码？

**Comment by yuhuangbin** [comment]
Hi, please upgrade `Spring Cloud Alibaba ` version to  `2.1.2.RELEASE`.
```properties
spring.cloud.nacos.username=xxx
spring.cloud.nacos.password=xxx
```

Refer: https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by MsencSir** [comment]
我用的依赖groupId 是org.springframework.cloud ；配置用户名和密码没有用；

**Comment by MsencSir** [comment]
![image](https://user-images.githubusercontent.com/46589466/82196500-57456d80-992c-11ea-8dc0-9ef96fa63d76.png)
这是我项目的使用的相关依赖；

**Comment by MsencSir** [comment]
![nacos](https://user-images.githubusercontent.com/46589466/82196666-9378ce00-992c-11ea-9854-3585a44cc002.jpg)
这是我项目使用的相关依赖；

**Comment by sundong1982** [comment]
我也遇到了，目前关掉auth就没问题   - NACOS_AUTH_ENABLE=false
