### ISSUE TITLE
Aliyun Java Initializr Bug or Suggestion Report

### ISSUE THREAD

**Issue by theonefx** [alibaba/spring-cloud-alibaba#1449]
请在这个 issue 中反馈针对 start.aliyun.com 的建议或者意见；
Please submit your suggestions or comments about start.aliyun.com in this issue.
![IMG_8969](https://user-images.githubusercontent.com/13715303/84613286-90eea180-aef5-11ea-8986-676ddba16cc0.JPG)

**Comment by pruidong** [comment]
Spring Boot 在前几天发布了2.3.0,但是start.aliyun.com上面还是旧的版本信息,请问什么时候start.aliyun.com会更新到新版本?

**Comment by theonefx** [comment]
> Spring Boot 在前几天发布了2.3.0,但是start.aliyun.com上面还是旧的版本信息,请问什么时候start.aliyun.com会更新到新版本?

多谢反馈，本周会完成更新

**Comment by pruidong** [comment]
> > Spring Boot 在前几天发布了2.3.0,但是start.aliyun.com上面还是旧的版本信息,请问什么时候start.aliyun.com会更新到新版本?
> 
> 多谢反馈，本周会完成更新

好的.谢谢.

**Comment by 437595587** [comment]
快点更新把

**Comment by pruidong** [comment]
> 快点更新把

刚看了一下，start.aliyun.com已经更新了.

**Comment by yxdwind** [comment]
![image](https://user-images.githubusercontent.com/8383118/84096642-05789a80-aa35-11ea-907b-de6fc417d1c8.png)
引入的路径中没有demo目录

**Comment by yxdwind** [comment]
![QQ截图20200609093935](https://user-images.githubusercontent.com/8383118/84096719-322cb200-aa35-11ea-8772-bb6cc45737c8.png)
引入的路径中没有demo

**Comment by theonefx** [comment]
> ![QQ截图20200609093935](https://user-images.githubusercontent.com/8383118/84096719-322cb200-aa35-11ea-8772-bb6cc45737c8.png)
> 引入的路径中没有demo

Done, it's has been fixed. Actually I remove demo codes about restservice, because of these code not clarity.

**Comment by airclear** [comment]
Aliyun Java Initializr 有开源出来吗？

**Comment by caowenliang** [comment]
gradle 项目 分层架构 里面module还是maven的pom文件
![图片](https://user-images.githubusercontent.com/5080149/86007029-6ea66900-ba49-11ea-885f-809a3cac5249.png)

**Comment by theonefx** [comment]
> gradle 项目 分层架构 里面module还是maven的pom文件
> ![图片](https://user-images.githubusercontent.com/5080149/86007029-6ea66900-ba49-11ea-885f-809a3cac5249.png)

Copy that, I'll handle it.

**Comment by cn-src** [comment]
Could not find artifact com.alibaba.cola:cola-core:pom:2.0.0 in me (https://maven.aliyun.com/repository/central)

**Comment by youngmkl** [comment]
> Could not find artifact com.alibaba.cola:cola-core:pom:2.0.0 in me (https://maven.aliyun.com/repository/central)

me too

**Comment by sunzcdev** [comment]
Could not find artifact com.alibaba.cola:cola-core:pom:2.0.0 in me (https://maven.aliyun.com/repository/central)

**Comment by theonefx** [comment]
> Could not find artifact com.alibaba.cola:cola-core:pom:2.0.0 in me (https://maven.aliyun.com/repository/central)

the COLA template has be updated;

**Comment by theonefx** [comment]
> Could not find artifact com.alibaba.cola:cola-core:pom:2.0.0 in me (https://maven.aliyun.com/repository/central)

the COLA template has be updated;

**Comment by zhugw** [comment]
# 建议 # 

能否自定义分层的module呢  一个应用 对应前台(front) 管理后台(admin) 以及共用(common)
```
foo-parent
    - front # 提供接口给H5
    - common # dao 和 DO
    - admin  # 管理后台接口
```

目前的分层 默认如下 
```
    <modules>
        <module>demo-api</module>
        <module>demo-dao</module>
        <module>demo-manager</module>
        <module>demo-service</module>
        <module>demo-web</module>
        <module>start</module>
    </modules>
```

**Comment by theonefx** [comment]
> # 建议
> 能否自定义分层的module呢 一个应用 对应前台(front) 管理后台(admin) 以及共用(common)
> 
> ```
> foo-parent
>     - front # 提供接口给H5
>     - common # dao 和 DO
>     - admin  # 管理后台接口
> ```
> 
> 目前的分层 默认如下
> 
> ```
>     <modules>
>         <module>demo-api</module>
>         <module>demo-dao</module>
>         <module>demo-manager</module>
>         <module>demo-service</module>
>         <module>demo-web</module>
>         <module>start</module>
>     </modules>
> ```

Good idea, I will consider this suggestion.

**Comment by gundamff** [comment]
gradle, 分层架构 
父项目是build.gradle
生成的子项目里面都是pom.xml

**Comment by oliver-csu** [comment]
能否在生成的时候指定发不到阿里云的私服呢，当然也可以是其他的私服

**Comment by theonefx** [comment]
> 能否在生成的时候指定发不到阿里云的私服呢，当然也可以是其他的私服

Good idea, I will consider this suggestion.

**Comment by xkcoding** [comment]
应用架构选择 `COLA` 下载下来之后，start 模块的 pom 文件存在问题，缺少一级 plugin 节点
```xml
<plugins>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>repackage</id>
            <goals>
                <goal>repackage</goal>
            </goals>
            <configuration>
                <mainClass>com.aliyun.cola.demo.DemoApplication</mainClass>
            </configuration>
        </execution>
    </executions>
</plugins>
```
需要改成
```xml
<plugins>
   <plugin>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-maven-plugin</artifactId>
       <executions>
           <execution>
               <id>repackage</id>
               <goals>
                   <goal>repackage</goal>
               </goals>
               <configuration>
                   <mainClass>com.aliyun.cola.demo.DemoApplication</mainClass>
               </configuration>
           </execution>
       </executions>
   </plugin>
</plugins>
```

**Comment by theonefx** [comment]
> 应用架构选择 `COLA` 下载下来之后，start 模块的 pom 文件存在问题，缺少一级 plugin 节点
> 
> ```
> <plugins>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-maven-plugin</artifactId>
>     <executions>
>         <execution>
>             <id>repackage</id>
>             <goals>
>                 <goal>repackage</goal>
>             </goals>
>             <configuration>
>                 <mainClass>com.aliyun.cola.demo.DemoApplication</mainClass>
>             </configuration>
>         </execution>
>     </executions>
> </plugins>
> ```
> 
> 需要改成
> 
> ```
> <plugins>
>    <plugin>
>        <groupId>org.springframework.boot</groupId>
>        <artifactId>spring-boot-maven-plugin</artifactId>
>        <executions>
>            <execution>
>                <id>repackage</id>
>                <goals>
>                    <goal>repackage</goal>
>                </goals>
>                <configuration>
>                    <mainClass>com.aliyun.cola.demo.DemoApplication</mainClass>
>                </configuration>
>            </execution>
>        </executions>
>    </plugin>
> </plugins>
> ```

done

**Comment by GenshenWang** [comment]
【Bug Report】
Hi, one bug I have found while using Aliyun Java Initializr(https://start.aliyun.com/) to create Spring Boot project, 
here is the bug detail：
![4DC2C2AB-9100-4E1B-B61E-635E05597DD0](https://user-images.githubusercontent.com/24788212/94257316-aeec8900-ff5d-11ea-916e-19bad21f2d60.png)

**Comment by thinwind** [comment]
自动生成的`application.properties`中，`spring.resources.static_locations`应该改成`spring.resources.static-locations`

**Comment by theonefx** [comment]
> 【Bug Report】
> 自动生成的`application.properties`中，`spring.resources.static_locations`应该改成`spring.resources.static-locations`

done

**Comment by nopol** [comment]
根目录能否加一个readme.md简要说明每个模块的作用

**Comment by theonefx** [comment]
> 根目录能否加一个readme.md简要说明每个模块的作用

good idea

**Comment by youngledo** [comment]
高级选项中的项目描述，输入着文字光标就跳转到项目名称上去了！

**Comment by theonefx** [comment]
> 高级选项中的项目描述，输入着文字光标就跳转到项目名称上去了！

already fixed

**Comment by theonefx** [comment]
> 【Bug Report】
> Hi, one bug I have found while using Aliyun Java Initializr(https://start.aliyun.com/) to create Spring Boot project,
> here is the bug detail：
> ![4DC2C2AB-9100-4E1B-B61E-635E05597DD0](https://user-images.githubusercontent.com/24788212/94257316-aeec8900-ff5d-11ea-916e-19bad21f2d60.png)

already fixed

**Comment by mosence** [comment]
maven项目描述会中文乱码

**Comment by nopol** [comment]
> maven项目描述会中文乱码

pom.xml有中文会乱码

**Comment by Ges0ng** [comment]
勾选上了以后创建项目pom文件还是没有加入依赖,是我哪里没设置好么?

**Comment by zhangyq233** [comment]
![image](https://user-images.githubusercontent.com/28673757/100471151-a3137380-3114-11eb-8a59-6cc5a79afc0a.png)
 
创建的dubbo项目报错，折腾一整天了，

第一个错误是启动报错：
![image](https://user-images.githubusercontent.com/28673757/100471421-351b7c00-3115-11eb-9a3d-12b66c1c4bf7.png)
解决方法：移除spring-cloud-openfeign-core依赖

第二个错误是消费端启动报错：
![image](https://user-images.githubusercontent.com/28673757/100471619-9a6f6d00-3115-11eb-9083-efe9de2d1827.png)
折腾好久了，也不知道怎么搞

**Comment by ppzzyy11** [comment]
> maven项目描述会中文乱码

你好能详细复述一下乱码复现过程么？这边需要复现

**Comment by ppzzyy11** [comment]
> > maven项目描述会中文乱码
> 
> pom.xml有中文会乱码

您名描述一下复现过程么？

**Comment by ppzzyy11** [comment]
> ![image](https://user-images.githubusercontent.com/28673757/100471151-a3137380-3114-11eb-8a59-6cc5a79afc0a.png)
> 
> 创建的dubbo项目报错，折腾一整天了，
> 
> 第一个错误是启动报错：
> ![image](https://user-images.githubusercontent.com/28673757/100471421-351b7c00-3115-11eb-9a3d-12b66c1c4bf7.png)
> 解决方法：移除spring-cloud-openfeign-core依赖
> 
> 第二个错误是消费端启动报错：
> ![image](https://user-images.githubusercontent.com/28673757/100471619-9a6f6d00-3115-11eb-9083-efe9de2d1827.png)
> 折腾好久了，也不知道怎么搞

是spring-boot-devtools导致的，去除这个依赖之后，项目都可以跑起来了

**Comment by Ges0ng** [comment]
是的,我也发现了,好像不勾选devtools也不会出现没自动加上依赖的问题

**Comment by zhangyq233** [comment]
> > ![image](https://user-images.githubusercontent.com/28673757/100471151-a3137380-3114-11eb-8a59-6cc5a79afc0a.png)
> > 创建的dubbo项目报错，折腾一整天了，
> > 第一个错误是启动报错：
> > ![image](https://user-images.githubusercontent.com/28673757/100471421-351b7c00-3115-11eb-9a3d-12b66c1c4bf7.png)
> > 解决方法：移除spring-cloud-openfeign-core依赖
> > 第二个错误是消费端启动报错：
> > ![image](https://user-images.githubusercontent.com/28673757/100471619-9a6f6d00-3115-11eb-9083-efe9de2d1827.png)
> > 折腾好久了，也不知道怎么搞
> 
> 是spring-boot-devtools导致的，去除这个依赖之后，项目都可以跑起来了

这个坑折腾了我好几天，哎

**Comment by mosence** [comment]
> > > maven项目描述会中文乱码
> > 
> > 
> > pom.xml有中文会乱码
> 
> 您名描述一下复现过程么？
步骤：
1、使用https://start.aliyun.com/创建maven脚手架
2、项目基本信息.高级选项.项目描述中填写中文
3、应用架构选择COLA，示例代码选择Mybatis+WEB
4、下载/预览代码就会出现乱码了

**Comment by Ges0ng** [comment]
开发工具全勾上,然后接下来哪怕是Spring Web 都没有加上依赖,包括目录结构中的静态资源文件夹等等. 我尝试了下单独勾选lombok就正常了. 
![1](https://user-images.githubusercontent.com/66422493/100706763-7ac19880-33e4-11eb-8658-8532618c0195.png)
![2](https://user-images.githubusercontent.com/66422493/100706768-7c8b5c00-33e4-11eb-83df-f4099e0dbb2c.png)

**Comment by ppzzyy11** [comment]
> > > > maven项目描述会中文乱码
> > > 
> > > 
> > > pom.xml有中文会乱码
> > 
> > 
> > 您名描述一下复现过程么？
> > 步骤：
> > 1、使用 https://start.aliyun.com 创建maven脚手架
> > 2、项目基本信息.高级选项.项目描述中填写中文
> > 3、应用架构选择COLA，示例代码选择Mybatis+WEB
> > 4、下载/预览代码就会出现乱码了
> 
> @ppzzyy11

已经修好了，多谢反馈🙏

**Comment by ppzzyy11** [comment]
> groupId

没有复现成功，亲，您的IDE是啥子

**Comment by Ges0ng** [comment]
> > groupId
> 
> 没有成功复现，您的IDE是啥子IDE

IDEA2020.2.3  可能我的idea有问题吧,有时间重装一下

**Comment by cn-src** [comment]
请及时保持版本是最新的！！！真的，没别的要求了，只希望解决官方的国外网络的问题。
这是最基本的诉求了，至于其他功能，可以慢慢来，都不急。
阿里的，更新实在是太慢了。
:laughing::laughing::laughing::laughing::laughing::laughing::laughing::laughing::laughing::laughing:

**Comment by hduyyg** [comment]
可以指定gradle的版本号嘛？

**Comment by jacovt** [comment]
Hello Everyone.

First of all, awesome job on the work that went into the Initializr! I am interested in seeing how you did the multi-module setup using the initializr (we would like to do something similar for our internal use), so I was wondering if the initializr code is publicly available so that I can have a look? Does anyone know?

Thank you in advance!
---Jaco

**Comment by liuzijianone** [comment]
请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊

**Comment by ppzzyy11** [comment]
> 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊

用IDEA的时候会有这个bug，估计下周开始修

**Comment by liuzijianone** [comment]
> > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> 
> 用IDEA的时候会有这个bug，估计下周开始修

好的，谢谢

**Comment by ppzzyy11** [comment]
> > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > 
> > 
> > 用IDEA的时候会有这个bug，估计下周开始修
> 
> 好的，谢谢

您给下自己创建项目的环境，IDEA版本啥的

**Comment by liuzijianone** [comment]
> > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > 
> > > 
> > > 用IDEA的时候会有这个bug，估计下周开始修
> > 
> > 
> > 好的，谢谢
> 
> 您给下自己创建项目的环境，IDEA版本啥的
jdk1.8，maven3.6.3， idea 2020.1.4

**Comment by ppzzyy11** [comment]
> > > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > > 
> > > > 
> > > > 用IDEA的时候会有这个bug，估计下周开始修
> > > 
> > > 
> > > 好的，谢谢
> > 
> > 
> > 您给下自己创建项目的环境，IDEA版本啥的
> > jdk1.8，maven3.6.3， idea 2020.1.4

您每次都能复现这个bug嘛

**Comment by liuzijianone** [comment]
是的，我刚又试了一下

**Comment by liuzijianone** [comment]
> > > > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > > > 
> > > > > 
> > > > > 用IDEA的时候会有这个bug，估计下周开始修
> > > > 
> > > > 
> > > > 好的，谢谢
> > > 
> > > 
> > > 您给下自己创建项目的环境，IDEA版本啥的
> > > jdk1.8，maven3.6.3， idea 2020.1.4
> 
> 您每次都能复现这个bug嘛
是的，我刚又试了一下

**Comment by liuzijianone** [comment]
> > > > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > > > 
> > > > > 
> > > > > 用IDEA的时候会有这个bug，估计下周开始修
> > > > 
> > > > 
> > > > 好的，谢谢
> > > 
> > > 
> > > 您给下自己创建项目的环境，IDEA版本啥的
> > > jdk1.8，maven3.6.3， idea 2020.1.4
> 
> 您每次都能复现这个bug嘛

是的，我刚又试了一下

**Comment by ppzzyy11** [comment]
> > > > > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > > > > 
> > > > > > 
> > > > > > 用IDEA的时候会有这个bug，估计下周开始修
> > > > > 
> > > > > 
> > > > > 好的，谢谢
> > > > 
> > > > 
> > > > 您给下自己创建项目的环境，IDEA版本啥的
> > > > jdk1.8，maven3.6.3， idea 2020.1.4
> > 
> > 
> > 您每次都能复现这个bug嘛
> 
> 是的，我刚又试了一下

尴尬，这边无法复现您说的这个BUG，但肯定有问题。
请您再把信息给得详尽一点，我们去复现一下

**Comment by sannmizu** [comment]
官方最新的已经是2.4.1了，阿里什么时候升到2.4.0.RELEASE啊

**Comment by liuzijianone** [comment]
> > > > > > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > > > > > 
> > > > > > > 
> > > > > > > 用IDEA的时候会有这个bug，估计下周开始修
> > > > > > 
> > > > > > 
> > > > > > 好的，谢谢
> > > > > 
> > > > > 
> > > > > 您给下自己创建项目的环境，IDEA版本啥的
> > > > > jdk1.8，maven3.6.3， idea 2020.1.4
> > > 
> > > 
> > > 您每次都能复现这个bug嘛
> > 
> > 
> > 是的，我刚又试了一下
> 
> 尴尬，这边无法复现您说的这个BUG，但肯定有问题。
> 请您再把信息给得详尽一点，我们去复现一下

使用spring initializer创建工程，starter service url 写的是start.aliyun.com，然后选择需要的dependency，比如说我选了spring boot 版本为2.2.10，还选了nacos, lombok，spring boot devtools，mybatis，mysql等，然后点finish。project创建完成，打开pom.xml文件，有部分我选择的dependency没有在pom.xml文件中被引用。

**Comment by ppzzyy11** [comment]
> > > > > > > > > 请问在创建项目时选择了需要使用的依赖，但是最终生成的pom.xml文件很多依赖都没有，仍然需要手动导入是什么原因啊
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 用IDEA的时候会有这个bug，估计下周开始修
> > > > > > > 
> > > > > > > 
> > > > > > > 好的，谢谢
> > > > > > 
> > > > > > 
> > > > > > 您给下自己创建项目的环境，IDEA版本啥的
> > > > > > jdk1.8，maven3.6.3， idea 2020.1.4
> > > > 
> > > > 
> > > > 您每次都能复现这个bug嘛
> > > 
> > > 
> > > 是的，我刚又试了一下
> > 
> > 
> > 尴尬，这边无法复现您说的这个BUG，但肯定有问题。
> > 请您再把信息给得详尽一点，我们去复现一下
> 
> 使用spring initializer创建工程，starter service url 写的是start.aliyun.com，然后选择需要的dependency，比如说我选了spring boot 版本为2.2.10，还选了nacos, lombok，spring boot devtools，mybatis，mysql等，然后点finish。project创建完成，打开pom.xml文件，有部分我选择的dependency没有在pom.xml文件中被引用。

多谢提供的信息，已经修好了

**Comment by ppzzyy11** [comment]
> 开发工具全勾上,然后接下来哪怕是Spring Web 都没有加上依赖,包括目录结构中的静态资源文件夹等等. 我尝试了下单独勾选lombok就正常了. 网页端创建手脚架却是没问题,只有idea中创建会这样.没完全加载勾选的东西
> ![1](https://user-images.githubusercontent.com/66422493/100706763-7ac19880-33e4-11eb-8658-8532618c0195.png)
> ![2](https://user-images.githubusercontent.com/66422493/100706768-7c8b5c00-33e4-11eb-83df-f4099e0dbb2c.png)
> 
> `
> 
> 4.0.0
> com.example
> fuxian
> 0.0.1-SNAPSHOT
> fuxian
> Demo project for Spring Boot
> 
> ```
> <properties>
>     <java.version>1.8</java.version>
>     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>     <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
>     <spring-boot.version>2.3.4.RELEASE</spring-boot.version>
> </properties>
> 
> <dependencies>
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
>     </dependency>
> 
>     <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-test</artifactId>
>         <scope>test</scope>
>         <exclusions>
>             <exclusion>
>                 <groupId>org.junit.vintage</groupId>
>                 <artifactId>junit-vintage-engine</artifactId>
>             </exclusion>
>         </exclusions>
>     </dependency>
> </dependencies>
> 
> <dependencyManagement>
>     <dependencies>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-dependencies</artifactId>
>             <version>${spring-boot.version}</version>
>             <type>pom</type>
>             <scope>import</scope>
>         </dependency>
>     </dependencies>
> </dependencyManagement>
> 
> <build>
>     <plugins>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-compiler-plugin</artifactId>
>             <version>3.8.1</version>
>             <configuration>
>                 <source>1.8</source>
>                 <target>1.8</target>
>                 <encoding>UTF-8</encoding>
>             </configuration>
>         </plugin>
>         <plugin>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-maven-plugin</artifactId>
>             <version>2.3.4.RELEASE</version>
>             <configuration>
>                 <mainClass>com.example.fuxian.FuxianApplication</mainClass>
>             </configuration>
>             <executions>
>                 <execution>
>                     <id>repackage</id>
>                     <goals>
>                         <goal>repackage</goal>
>                     </goals>
>                 </execution>
>             </executions>
>         </plugin>
>     </plugins>
> </build>
> ```
> 
> `

多谢提供的信息，已经修好了

**Comment by ppzzyy11** [comment]
> 请及时保持版本是最新的！！！真的，没别的要求了，只希望解决官方的国外网络的问题。
> 这是最基本的诉求了，至于其他功能，可以慢慢来，都不急。
> 阿里的，更新实在是太慢了。
> 😆😆😆😆😆😆😆😆😆😆

已经更新了

**Comment by ppzzyy11** [comment]
> > > groupId
> > 
> > 
> > 没有成功复现，您的IDE是啥子IDE
> 
> IDEA2020.2.3 可能我的idea有问题吧,有时间重装一下

多谢提供的信息，已经修好了，2020.1的参数丢失导致的

**Comment by fantasylion** [comment]
![image](https://user-images.githubusercontent.com/8531944/103070758-22ee0a00-45fd-11eb-8eb0-1ef400fb1c73.png)

以上选择后点击获取代码，项目下载下来后发现只创建了类没有创建包

![image](https://user-images.githubusercontent.com/8531944/103070811-40bb6f00-45fd-11eb-82a4-aec3bdaf80bc.png)

**Comment by zhaoliangzl** [comment]
生成了重复的application.properties配置项
<img width="1209" alt="截屏2020-12-29 下午5 21 55" src="https://user-images.githubusercontent.com/25294531/103273769-0b4ac300-49fb-11eb-8218-af04a4d662b4.png">

**Comment by ppzzyy11** [comment]
> 生成了重复的application.properties配置项
> <img alt="截屏2020-12-29 下午5 21 55" width="1209" src="https://user-images.githubusercontent.com/25294531/103273769-0b4ac300-49fb-11eb-8218-af04a4d662b4.png">

麻烦分享一下配置

**Comment by ppzzyy11** [comment]
> 生成了重复的application.properties配置项
> <img alt="截屏2020-12-29 下午5 21 55" width="1209" src="https://user-images.githubusercontent.com/25294531/103273769-0b4ac300-49fb-11eb-8218-af04a4d662b4.png">

已修复，过几天发布

**Comment by youngledo** [comment]
众所周知Spring已经使用Gradle代替Maven来作为第一选择，然而网络原因Gradle一直无法很好的使用。作为国内的脚手架，阿里云也提供了Gradle的构建方式，但是还是和Spring一样无法正常使用。请问阿里云有提供镜像加速吗，不然Gradle一直没办法使用。

**Comment by iMinusMinus** [comment]
项目能否开源？
已知Spring Initializr/Spring start存在的问题有：
1. 方法参数不支持注解
2. 部分语句不支持，比如“return constant”。
3. 不支持多模块
第1、2点我已经解决，第3点还没开始做。看到阿里云有类似的已实现的效果。

**Comment by wangyushuai** [comment]
![image](https://user-images.githubusercontent.com/8596105/109142284-a7920b80-7799-11eb-9834-14220675d5fe.png)

请问为什么执行 `mvn clean package` 达成的包都特别小，而且是无法运行的。

**Comment by ppzzyy11** [comment]
> ![image](https://user-images.githubusercontent.com/8596105/109142284-a7920b80-7799-11eb-9834-14220675d5fe.png)
> 
> 请问为什么执行 `mvn clean package` 打成的包都特别小，而且是无法运行的。

之前修 BUG 引入的新 BUG，已经修了，后面回发。可以在先手动添加spring boot 的打包插件应急。

**Comment by wangyushuai** [comment]
> > ![image](https://user-images.githubusercontent.com/8596105/109142284-a7920b80-7799-11eb-9834-14220675d5fe.png)
> > 请问为什么执行 `mvn clean package` 打成的包都特别小，而且是无法运行的。
> 
> 之前修 BUG 引入的新 BUG，已经修了，后面回发。可以在先手动添加spring boot 的打包插件应急。

![image](https://user-images.githubusercontent.com/8596105/109636134-2dd99380-7b86-11eb-8d38-795a4f98de91.png)

加了打包插件，变成了8.0k ，还是无法运行的😶

**Comment by jacovt** [comment]
> 加了打包插件，变成了8.0k ，还是无法运行的

You need to to make it executable:
`<plugin>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-maven-plugin</artifactId>
     <configuration>
          <executable>true</executable>
     </configuration>
 </plugin>
`

**Comment by Joettan** [comment]
目前的版本使用gradle进行配置时无法正确导入project和module。idea版本2020.3。

**Comment by ppzzyy11** [comment]
> 目前的版本使用gradle进行配置时无法正确导入project和module。idea版本2020.3。

用IDEA不能指定框架吧？

**Comment by ppzzyy11** [comment]
> gradle, 分层架构
> 父项目是build.gradle
> 生成的子项目里面都是pom.xml

发布了脚手架新版本，这版本的Gradle支持MVC和Layered框架

**Comment by ppzzyy11** [comment]
> 众所周知Spring已经使用Gradle代替Maven来作为第一选择，然而网络原因Gradle一直无法很好的使用。作为国内的脚手架，阿里云也提供了Gradle的构建方式，但是还是和Spring一样无法正常使用。请问阿里云有提供镜像加速吗，不然Gradle一直没办法使用。图片是我使用阿里云脚手架的，Gradle一直无法下载相应的插件。
> <img alt="屏幕截图 2021-01-31 154049" width="809" src="https://user-images.githubusercontent.com/68590897/106377846-d73c3680-63da-11eb-9f2c-43abfb380aad.png">

发布了脚手架新版本，这版本的Gradle支持MVC和Layered框架

**Comment by Ryoui** [comment]
一点不成熟的建议。仔细对比了下官方的脚手架发现，start.aliyun.com脚手架优势在多了一个应用架构和示例代码，但这两块并没有做的很好。只要体现在应用架构对应的示例不够完善，还有改进空间，Lombok组件不添加时生成的demo代码还是用了Lombok，每次都要自己取消。另一个不足之处在于springboot版本上，建议和官方GA版本对齐，比如目前官方learnGA版本有2.4.5、2.3.10.RELEASE、2.2.13.RELEASE、2.1.18.RELEASE这些，start.aliyun.com对应就提供这些就够了；然后就是更新问题，官方发布新版本了，最好能一周之类就更新对应版本。start.aliyun.com有个亮点就是引入了cola应用架构，可惜更新太慢了，不知道是不是要和cola那边配合的原因...希望start.aliyun.com脚手架能越来越好吧

**Comment by allinprogram** [comment]
### 脚手架里为啥不是同步更新发行版本呢？

**Comment by chuxue12** [comment]
我创建的是gradle工程 发现是maven和gradle混用的 
![image](https://user-images.githubusercontent.com/8922853/122166604-722a3e80-ceac-11eb-86dd-66d1fe6d7d5a.png)

**Comment by JanJF** [comment]
![image](https://user-images.githubusercontent.com/14165820/124409209-72667d00-dd7a-11eb-8913-2e917342c0a8.png)

分享的时候一直提示未登录，确定已经登陆过了

**Comment by pashenmebaojinwo** [comment]
二维码分享过期了,能更新一下吗

**Comment by vaughnn** [comment]
是否支持生成代码是yml的配置文件

**Comment by niaoshuai** [comment]
![image](https://user-images.githubusercontent.com/5117373/126949689-604ca035-990f-4e75-b4c1-2a01d0469af0.png)
这个案例里面 有个主键ID 没有配置自增 运行错误

**Comment by lnsane** [comment]
where is Aliyun Java Initializr source code?

**Comment by huiflyy** [comment]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1146104/132112089-e93cafad-828b-4e7c-a8fa-6507f856a68c.png">
示例代码超过9项时，不能上下滑动。

**Comment by dzhiqiang** [comment]
你好，使用https://start.aliyun.com/bootstrap.html时，maven,java,springboot:2.4.1,基本信息：默认，应用架构：分层架构，示例代码：mybatis基础示例，为什么在start和dao子项目中，pom文件都依赖了<artifactId>mybatis-spring-boot-starter</artifactId>

**Comment by meichangsu1** [comment]
二维码失效了，而且构建工具选择的ｇｒａｄｌｅ　但是生成的代码里面仍然是maven的

**Comment by steverao** [comment]
进入start.aliyun.com群请加：32268357

**Comment by steverao** [comment]
> 二维码失效了，而且构建工具选择的ｇｒａｄｌｅ　但是生成的代码里面仍然是maven的

进start.aliyun.com群请加：32268357

**Comment by hesperup** [comment]
应用架构COLA能支持最新4.01吗

**Comment by XM2510136957** [comment]
start.aliyun.com数据什么时候能更新一下最新的

**Comment by mostcool** [comment]
Aliyun Java Initializr 有开源出来吗？求地址

**Comment by pomzhou2011** [comment]
生成的cola工程，怎么mvn install报错啊，弄了好半天搞不好

**Comment by techa03** [comment]
![image](https://user-images.githubusercontent.com/16450027/150733732-ccd87b2c-37f3-4c1b-a7ef-0460793e597c.png)
这里有个错别字

**Comment by zww1990** [comment]
start.aliyun.com啥时候能更新到2.6.x呀？

**Comment by lihulanxx** [comment]
开坑弃坑的节奏

**Comment by Ryoui** [comment]
最看重的springboot版本和应用架构cola版本一年没更新了，钉钉群里反馈了，也没解决。哎

**Comment by RuvikVan** [comment]
这玩意是不是已经被遗弃了？

**Comment by tianfudhe** [comment]
可能收到了裁员的波及

**Comment by HucklyBerryFinn** [comment]
这个项目已经废弃了吗？

**Comment by steverao** [comment]
We have open-sourced [this project](https://github.com/alibaba/cloud-native-app-initializer), and if you have any questions in the future, you can directly submit [issues](https://github.com/alibaba/cloud-native-app-initializer/issues) to related projects.

**Comment by YanhongLiu2000** [comment]
springboot2.3.7RELEASE被移除了，新的2.6.11没有整合mybatis plus，可以继续支持2.3.7吗？
