### ISSUE TITLE
Nacos + Spring-cloud-alibaba off-line dubbo instance

### ISSUE THREAD

**Issue by tone316** [alibaba/spring-cloud-alibaba#1454]
Spring-cloud-alibaba : 2.1.2.RELEASE, Apache-dubbo: 2.7.6, Nacos: 1.2.1

在 Nacos  上面 下线 dubbo provider, dubbo instance 仍然在 nacos 服务列表 里面. 
无法 正常下线dubbo 服务 和isntance.

![image](https://user-images.githubusercontent.com/1491663/82020209-44783200-96bb-11ea-86d8-131738c70588.png)

![image](https://user-images.githubusercontent.com/1491663/82020294-64a7f100-96bb-11ea-8998-6e8192bc8049.png)

下线：
![image](https://user-images.githubusercontent.com/1491663/82020347-82755600-96bb-11ea-83bf-af09fed96cb2.png)

dubbo 服务 仍然在 nacos 列表里面. 
![image](https://user-images.githubusercontent.com/1491663/82020448-aafd5000-96bb-11ea-80bd-6f5937d8d2c7.png)

dubbo provider ,可以看到 remove 的 通知:
![image](https://user-images.githubusercontent.com/1491663/82020570-e861dd80-96bb-11ea-9cd2-c4d2189925ec.png)

**Comment by khiker007** [comment]
你好，请问你的dubbo配置文件是如何配置的，我的dubbo服务注册到nacos的数据跟你的显示的不一样呀

**Comment by khiker007** [comment]
知道了，你这个是配置了metadata了；服务的下线并不是把服务从nacos中删除吧，应该是在客户端获取服务列表的时候，会把下线的服务排除掉

**Comment by mercyblitz** [comment]
It's not an issue, actually, your application uses the traditional registration of dubbo services that are treated as the normal Services(applications) in Nacos, thus, the dubbo services will not be off-line when the application offlines.
