### ISSUE TITLE
How to override the property value in NacosDiscoveryProperties

### ISSUE THREAD

**Issue by Zzzly1106** [alibaba/spring-cloud-alibaba#1460]
springCloud version
` <spring-cloud.version>Hoxton.SR3</spring-cloud.version>`
springCloud-alibaba.version
` <spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>`

How to override the property value in NacosDiscoveryProperties and use the overwritten property value to register during registration

**Comment by yuhuangbin** [comment]
Refer: [SidecarNacosDiscoveryProperties](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryProperties.java). @Zzzly1106
