### ISSUE TITLE
sentinel适配spring-cloud-gateway push模式配置NacosDataSource

### ISSUE THREAD

**Issue by yifan2333** [alibaba/spring-cloud-alibaba#1462]
请问一下sentinel 适配 spring-cloud-gateway时
`sentinel-dashboard:1.7.2` push模式怎么将`ApiDefinition`和`GatewayFlowRule`publish到nacos？
我在试验的时候发现
`com.alibaba.csp.sentinel.dashboard.datasource.entity.gateway.GatewayFlowRuleEntity`和`com.alibaba.csp.sentinel.dashboard.datasource.entity.gateway.ApiDefinitionEntity`的`getRule()`方法返回`null`，`com.alibaba.csp.sentinel.dashboard.rule.nacos.NacosConfigUtil#setRuleStringToNacos`报空指针

**Comment by yuhuangbin** [comment]
Refer: #1440
