### ISSUE TITLE
how sentinel assembly with openfeign1.x.x

### ISSUE THREAD

**Issue by nakerny** [alibaba/spring-cloud-alibaba#1465]
**Which Component**
Sentinel

**Describe what problem you have encountered**
because openfeign 1.x.x used @EnableFeignClients and @FeignClient annotations in the spring-cloud-netflix-core package，not spring-cloud-openfeign-core,I want to know is there an another way for sentinel to integrate with openfeign1.x.x

**Describe what information you have read**
I have read the reference doc of Sentinel

**Comment by whoamigodson** [comment]
Sentinel integrate with openfeign in spring cloud:

1、add dependency:
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>

2、add config in application.properties
feign.sentinel.enabled=true

3、config feignclient,FeignConfiguration class can't add @Configuration

@FeignClient(name = "service-provider", fallback = EchoServiceFallback.class, configuration = FeignConfiguration.class)
public interface EchoService {
    @GetMapping(value = "/echo/{str}")
    String echo(@PathVariable("str") String str);
}

class FeignConfiguration {
    @Bean
    public EchoServiceFallback echoServiceFallback() {
        return new EchoServiceFallback();
    }
}

class EchoServiceFallback implements EchoService {
    @Override
    public String echo(@PathVariable("str") String str) {
        return "echo fallback";
    }
}
