### ISSUE TITLE
Wheather or not we could get File(flow-rule.json) from fat jar in the spring-boot-sentinel project in the current version

### ISSUE THREAD

**Issue by changetest** [alibaba/spring-cloud-alibaba#1467]
Execuse me ,please!

Associate issue 428
I want to confirm wheather the spring-cloud-alibaba can support getting File from fat jar in the current version.That means we can't write our properties like this :
spring.cloud.sentinel.datasource.ds1=jar:D:/sentinel.jar!/BOOT-INF/classes/config/sentinel/FlowRule.json

# class path resource cannot be resolved as enhancement in #91 #428

**Comment by yuhuangbin** [comment]
Refer: [Sentinel Example Project](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties).
