### ISSUE TITLE
How to override the property value in NacosDiscoveryProperties and use the overwritten property value to register during registration

### ISSUE THREAD

**Issue by Zzzly1106** [alibaba/spring-cloud-alibaba#1468]
springCloud version
<spring-cloud.version>Hoxton.SR3</spring-cloud.version>
springCloud-alibaba.version
<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>

How to override the property value in NacosDiscoveryProperties and use the overwritten property value to register during registration

**Comment by yuhuangbin** [comment]
Hi, you can refer [SidecarNacosDiscoveryProperties](https://github.com/alibaba/spring-cloud-alibaba/blob/213bf2a9127fb08e2beba30e7c0f01c2e46459b3/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryProperties.java#L29)

**Comment by Zzzly1106** [comment]
thank you , and I have solved id .  This is my solution  

create spring.factories  under the resources.META-INF and  add 
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.company.demo.sdk.config.nacos.NacosRegistryConfigure,\

create class 

@Configuration
@EnableConfigurationProperties({RegistryProperties.class})
public class NacosRegistryConfigure {

    @Resource
    private RegistryProperties registryProperties;

    private String SERVER_ADDR = "%s:%s";
    @Bean
    NacosDiscoveryProperties nacosProperties() {
        NacosDiscoveryProperties nacosDiscoveryProperties = new NacosDiscoveryProperties();
        nacosDiscoveryProperties.setServerAddr(String.format(SERVER_ADDR, registryProperties.getHost(), registryProperties.getPort()));
        nacosDiscoveryProperties.setRegisterEnabled(RegistryProperties.RegistryEnum.nacos.equals(registryProperties.getType()));
        if (StringUtils.isNotBlank(registryProperties.getIpAddress())) {
            nacosDiscoveryProperties.setIp(registryProperties.getIpAddress());
        }
        if (!CollectionUtils.isEmpty(registryProperties.getTags())) {

            Map<String, String> tags = registryProperties.getTags()
                    .stream()
                    .collect(Collectors.toMap(x -> x.split("=")[0], x -> x.split("=")[1]));
            tags.put("registryTime", String.valueOf(System.currentTimeMillis()));
            nacosDiscoveryProperties.setMetadata(tags);
        } else {
            Map<String, String> tags = Maps.newHashMap();
            tags.put("registryTime", String.valueOf(System.currentTimeMillis()));
            nacosDiscoveryProperties.setMetadata(tags);
        }
        return nacosDiscoveryProperties;
    }

    @Bean
    NacosServiceRegistry nacosServiceRegistry(
            NacosDiscoveryProperties nacosDiscoveryProperties) {
        return new NacosServiceRegistry(nacosDiscoveryProperties);
    }


}
