### ISSUE TITLE
Nacos服务地址更改无效|The modification of Nacos Server Address is invalid

### ISSUE THREAD

**Issue by MephistoLynn** [alibaba/spring-cloud-alibaba#1469]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

My Nacos Server 1.2.1 was running successfully in CentOS of AiliYUN
![image](https://user-images.githubusercontent.com/22832393/82303134-1feac580-99ed-11ea-95f5-7ec0d64cc538.png)

However,after i modified the nacos-discovery address in application.properties and ran the application ,then the console outputed Exception Message  :

![image](https://user-images.githubusercontent.com/22832393/82304523-09de0480-99ef-11ea-9982-2c633b431eff.png)
**[NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused: connect** 

I have already changed the nacos server ip to my remote nacos server ip which in aliyun，but seemingly it is didn't work.
![image](https://user-images.githubusercontent.com/22832393/82303515-a0a9c180-99ed-11ea-8926-ad81753fef4c.png)

The ServerHttpAgent is trying to connecting localhost instead of my own Nacos IP.

### Describe what you expected to happen
Runing  normal.

### How to reproduce it (as minimally and precisely as possible)

1. add property “spring.cloud.nacos.discovery.server-addr= {MyIP:PORT} ”
2. normally running Spring Application

### Tell us your environment
Nacos Server ver: 1.2.1

SpringBoot Ver:2.2.6.RELEASE
spring-cloud-starter-alibaba-nacos-discovery:2.2.1.RELEASE
spring-cloud-starter-alibaba-nacos-config:2.2.1.RELEASE

### Anything else we need to know?

[################CHINESE#################]
1.我在阿里云的Centos上部署了Nacos 并成功运行（单实例）
![image](https://user-images.githubusercontent.com/22832393/82303134-1feac580-99ed-11ea-95f5-7ec0d64cc538.png)

2.然后在application.properties 更改nacos 服务地址为我CentOS的IP
![image](https://user-images.githubusercontent.com/22832393/82303515-a0a9c180-99ed-11ea-8926-ad81753fef4c.png)

3.接着，运行项目就报错了
![image](https://user-images.githubusercontent.com/22832393/82304523-09de0480-99ef-11ea-9982-2c633b431eff.png)

c.a.n.c.config.http.ServerHttpAgent，它一直在尝试连接 http://localhost:8848，但是我的Nacos服务不在本机，所以它持续不断的抛出异常。只有在我本机启动Nacos服务，这个异常才不会出现。

**Comment by Garlichead** [comment]
@chuntaojun ？

**Comment by chuntaojun** [comment]
> @chuntaojun ？

enmmm，Is it wrong that I issue a transfer？

**Comment by MephistoLynn** [comment]
问题已解决。是配置位置的问题。需要改到bootstrap.properties中。感谢。

**Comment by Starbucksstar** [comment]
NacosConfigProperties：
![image](https://user-images.githubusercontent.com/20951983/83019042-de938f00-a058-11ea-914d-97bbaf20d16a.png)

spring cloud context在加载配置的时候，首先加载bootstrap.yml中启动类配置，从中获取配置中心的地址然后会去nacos拉取配置数据，所以如果放在application.yml中会导致配置注入为空，获取默认localhost:8848 nacos的数据
