### ISSUE TITLE
通过Gateway无法访问nacos上注册的服务实例

### ISSUE THREAD

**Issue by chenyi2333** [alibaba/spring-cloud-alibaba#1471]
springcloud 版本为Hoxton.SR4
springcloud-alibaba版本为2.2.1.RELEASE
springboot版本为2.2.7.RELEASE
nacos版本为1.2.1
通过Gateway无法访问nacos上注册的服务

**Comment by NineSwordsMonster** [comment]
+1

**Comment by yang-xiansen** [comment]
+1

**Comment by yang-xiansen** [comment]
> springcloud 版本为Hoxton.SR4
> springcloud-alibaba版本为2.2.1.RELEASE
> springboot版本为2.2.7.RELEASE
> nacos版本为1.2.1
> 通过Gateway无法访问nacos上注册的服务

springcloud 版本为Hoxton.SR1
springcloud-alibaba版本为2.2.0.RELEASE
springboot版本为2.2.4.RELEASE
nacos版本为1.2.1
可以正常访问

**Comment by yuhuangbin** [comment]
请参照版本依赖关系使用，[版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
