### ISSUE TITLE
nacos 权限认证

### ISSUE THREAD

**Issue by 1556837534** [alibaba/spring-cloud-alibaba#1473]
## Issue Description
环境 ： SpringCloud +Spring alibaba
结果信息：
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 20 14:10:12 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos 在application.yaml 文件中配置了 对应的用户与密码 服务可以注册进去，但是提示获取dataId 报403错误 无法获取到对应的 配置文件信息

### Describe what you expected to happen
日志信息
[fixed-127.0.0.1_8848-dev] [check-update] get changed dataId error, code: 403

**Comment by yuhuangbin** [comment]
> > > 我同样也遇到了这个问题，不用Spring Cloud 的版本是可以实现 Nacos 的配置及服务注册，用了 Spring Cloud 的版本后就一直报 403，跟进源码发现是在请求服务配置时 nacos-client 中并没有传入 username 及 password 参数导致？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8255660/80330398-a4777780-8877-11ea-84df-feeed002fda1.png)
> > 现在可以升级到新版本可以配置用户密码，SpringCloud alibaba 组件库升级了
> 
> 能具体告诉到升级到哪个版本么？ 用的springcloud-Finchley，使用的alibaba-nacos-config版本如下：
> com.alibaba.cloud
> spring-cloud-starter-alibaba-nacos-config
> 2.0.2.RELEASE
> 该版本使用的nacos-client为1.2.1 已经是最新版本了，但仍然没有解决这个问题

Spring Cloud Alibaba 2.0.2.RELEASE已经适配Nacos 1.2.1,[Spring Cloud Alibaba版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E).

如果使用 Spring Cloud Alibaba 2.0.2.RELEASE 仍未解决nacos认证问题，请贴出相关配置。

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
