### ISSUE TITLE
2020 Alibaba Summer of Code

### ISSUE THREAD

**Issue by theonefx** [alibaba/spring-cloud-alibaba#1477]
<br />Welcome to the open source world!If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻<br />
<br />Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience the software development in the real world.Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summer time to participate in the open source project and work with the core members of the project.<br />

<a name="68c5daac"></a>
## What you can get?
On this exclusive developer journey, students will have the opportunity to:<br />

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open source project！

<a name="nWt4P"></a>
## Our Mentor
GitHub ID：[Mercy Ma](https://github.com/mercyblitz), Spring Cloud Alibaba PMC
GitHub ID：[theonefx](https://github.com/theonefx), Spring Cloud Alibaba Contributor

<a name="4748b527"></a>
## Apply Now!
Step 1. You can click on this link to apply directly:
[Idea List](https://github.com/alibaba/spring-cloud-alibaba/labels/SoC2020)
Step 2. Full list of Alibaba Summer of Code Projects

- 中文：[https://developer.aliyun.com/topic/summerofcode2020](https://developer.aliyun.com/topic/summerofcode2020)
- English:[https://www.alibabacloud.com/campaign/summerofcode2020](https://www.alibabacloud.com/campaign/summerofcode2020)

（备注：5月25日正式上线）<br />![image.png](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/249972/1589854856011-9366aabf-35f2-4003-a428-ef6b3302c097.png#align=left&display=inline&height=470&margin=%5Bobject%20Object%5D&name=image.png&originHeight=470&originWidth=2508&size=196617&status=done&style=none&width=2508)<br />

<a name="e4990434"></a>
## Timeline⏳

<br />![image.png](https://user-images.githubusercontent.com/5254035/57433282-a8774780-726a-11e9-844c-c4f96a1d64b9.png)<br />

<a name="3fa57f9d"></a>
## Contact us!
Email Address: aliopensource@alibabacloud.com

**Comment by dernDren161** [comment]
Hello @theonefx , do we have a dedicated channel for this project in the IRC?
Thank you!
