### ISSUE TITLE
spring cloud  alibaba nacos中哪些配置修改之后是必须重启应用才可以生效的呢

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/spring-cloud-alibaba#1486]
spring cloud alibaba  nacos中，有许多配置项；比如地址，开关enabled等；
其中哪些配置项修改之后需要应用重启之后才可以生效，哪些配置修改之后是不需要重启应用就可以生效的呢

**Comment by whoamigodson** [comment]
bootstrap.properties中的配置，要重启才能生效，放在nacos配置中心里面的配置无需重启生效。

**Comment by HelloHaiNG** [comment]
> bootstrap.properties中的配置，要重启才能生效，放在nacos配置中心里面的配置无需重启生效。

对；我想要知道的是spring.cloud.nacos自身的配置，比如spring.cloud.nacos.registry.enabled这种的spring.cloud.nacos原生的配置项，我在bootstrap.yml配置了之后，我去修改了的话，哪些原生的配置项是不需要重启应用就可以生效的，哪些是必须要重启应用才可以生效；和nacos配置中心无关

**Comment by fangjian0423** [comment]
This is the default design of Spring Boot & Spring Cloud.
