### ISSUE TITLE
最新版集成 Error creating bean with name 'ribbonServerList' defined in class path resource [com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.class]: Unsatisfied dependency expressed through method 'ribbonServerList' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.client.config.IClientConfig' available

### ISSUE THREAD

**Issue by eshow** [alibaba/spring-cloud-alibaba#1490]
Error creating bean with name 'ribbonServerList' defined in class path resource [com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.class]: Unsatisfied dependency expressed through method 'ribbonServerList' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.client.config.IClientConfig' available
配置信息如下
`spring:
  application:
    name: nacos-discovery-provider
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'`
pom文件引用包如下：
`<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Hoxton.SR3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <version>2.2.1.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>`
springboot 的版本是2.2.5.RELEASE

**Comment by github19938** [comment]
咋解决的

**Comment by muzifeng1008** [comment]
咋解决的
