### ISSUE TITLE
关于版本问题

### ISSUE THREAD

**Issue by huguangjun580** [alibaba/spring-cloud-alibaba#1499]
我看到官网的cloud已经出到 Hoxton SR5 了，spring-cloud-alibaba 项目中Wiki中的关于版本组合文档是否应该即时更新下呀，因为发现在Wiki文档中版本表格中停留在 SR3中，这在spring 官网中算是消逝的迭代品了。

**Comment by yuhuangbin** [comment]
Spring Cloud每个版本之间不一定兼容，比如Hoxton 大版本中的小版本都有不兼容的情况，建议跟着Spring Cloud Alibaba整合的版本走。
