### ISSUE TITLE
ext-config 无法读取到配置的问题

### ISSUE THREAD

**Issue by fengzidk** [alibaba/spring-cloud-alibaba#1500]
nacos服务端版本: 1.2.1
spring-cloud-starter-alibaba-nacos-config 版本: 2.2.1.RELEASE
根据官方文档示例,ext-config配置如下:
```
ext-config[0]:          
   data-id: message-mongo.yml
   group: mongo
```
最终生成的访问配置链接为:http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=message-mongo.yml&group=mongo&tenant=8077e012-a3ce-41b9-85ff-24597ecdef7e

访问此链接: nacos服务端返回 config data not exist

手动去掉.yml 则访问配置链接为:http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=message-mongo&group=mongo&tenant=8077e012-a3ce-41b9-85ff-24597ecdef7e

nacos 服务端返回正确的配置,

但是如果修改配置为
```
ext-config[0]:         
  data-id: message-mongo
  group: mongo
```

启动报错:[message-mongo] must contains file extension with properties|yaml|yml|xml|json

**Comment by fengzidk** [comment]
![image](https://user-images.githubusercontent.com/22466765/83731711-8a526580-a67d-11ea-9340-3a3eee14dc5d.png)
将配置主动加上.yml后 可以正常获取,但是,配置格式只是为了显示优化? 
手动滑稽...

**Comment by zkzlx** [comment]
data-id中添加后缀名是为了告知sca在解析该配置的时候以何种逻辑解析，若需要自动匹配则需要nacos-client的api接口在获取配置的时候也需要一并返回配置格式才可以。等nacos-client的ap接口支持的时候，sca会优化这块逻辑。
