### ISSUE TITLE
这是怎么解决 sleuth +spring alibaba sentinel

### ISSUE THREAD

**Issue by luyanfeng** [alibaba/spring-cloud-alibaba#1505]
Field hystrixAsyncService in com.luyanfeng.zuul.controller.FeignTestController required a single bean, but 2 were found:
	- feignSentinelBuilder: defined by method 'feignSentinelBuilder' in class path resource [com/alibaba/cloud/sentinel/feign/SentinelFeignAutoConfiguration.class]
	- feignHystrixBuilder: defined by method 'feignHystrixBuilder' in class path resource [org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.class]

**Comment by HaojunRen** [comment]
It is conflict problem for sleuth & spring alibaba sentinel. I think sentinel team has known this issue
