### ISSUE TITLE
Tried 3 times of the providers 

### ISSUE THREAD

**Issue by zqzhang84** [alibaba/spring-cloud-alibaba#1508]
我们这边生产环境启动dobbo服务，需要把nacos上面注册的其他服务先下线后才能启动，如果不下线就会报下面的错误，发现application=fd-tms-web和group=cloud-oauth2-server 值不一样，cloud-oauth2-server并不是fd-tms-web的服务提供方，请问大家有没有碰到过？
注：生产环境有这个报错， 测试环境报错，生产环境有防火墙。
org.apache.dubbo.rpc.RpcException: Failed to invoke the method getServiceRestMetadata in the service org.apache.dubbo.rpc.service.GenericService. Tried 3 times of the providers [x.x.x.x:20881] (1/1) from the registry -addr}:9090 on the consumer x.x.x.x using the dubbo version 2.7.3. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://x.x.x.x:20881/org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService?anyhost=true&application=fd-tms-web&bind.ip=x.x.x.x&bind.port=20881&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=cloud-oauth2-server&interface=org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=23&qos.enable=false&register=true&register.ip=x.x.x.x&release=2.7.3&remote.application=cloud-oauth2-server&revision=0.9.0.RELEASE&side=consumer&sticky=false&timestamp=1590170848742&version=1.0.0, cause: message can not send, because channel is closed . url:dubbo://x.x.x.x:20881/org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService?anyhost=true&application=fd-tms-web&bind.ip=x.x.x.x&bind.port=20881&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=cloud-oauth2-server&heartbeat=60000&interface=org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=23&qos.enable=false&register=true&register.ip=x.x.x.x&release=2.7.3&remote.application=cloud-oauth2-server&revision=0.9.0.RELEASE&side=consumer&sticky=false&timestamp=1590170848742&version=1.0.0
        at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:248)
        at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)

**Comment by zqzhang84** [comment]
已解决

**Comment by dododogamila** [comment]
我也遇到了跟你一样的问题，请问你们是怎么解决的？
