### ISSUE TITLE
nacos不断轮询本地nacos连接

### ISSUE THREAD

**Issue by wpt191** [alibaba/spring-cloud-alibaba#1510]
我在application.yml配置了远程服务器的nacos信息，但启动一直在找本地nacos，虽然后续可以连接到远程，但还是一直轮询找本地。
yml配置：
`cloud:
    nacos:
      config:
        server-addr: 192.168.4.28:80
      discovery:
        group: CBI_ENTERPRISE_GROUP
        namespace: 174ba8a5-baf2-4e99-8ba1-f3738fd7ff61
        server-addr: 192.168.4.28:80
        service: ${spring.application.name}
        watch:
          enabled: true`

报错信息：
`currentServerAddr: http://localhost:8848, err : Connection refused: connect`

**Comment by KomachiSion** [comment]
@chuntaojun 麻烦看一下，为什么需要在两边都配置，还是使用方法有问题。

@wpt191 麻烦吧bootstrap.yml和application.yml内容都贴一下，可以省去一些敏感信息，方便定位问题。

**Comment by wpt191** [comment]
`spring:
  cloud:
    nacos:
      config:
        server-addr: 192.168.4.28:80
      discovery:
        group: CBI_ENTERPRISE_GROUP
        namespace: 174ba8a5-baf2-4e99-8ba1-f3738fd7ff61
        server-addr: 192.168.4.28:80
        service: ${spring.application.name}
        watch:
          enabled: true`

问题已经解决：
问题复盘：
1、nacos所有配置信息在application.yml中导致轮询。
2、将nacos，config节点配置在bootstrap中，但discover节点配置在application中导致配置两次。
结论：nacos配置中心与注册中心都需要配置在bootstrap.yml中即可

感谢各位大佬支持，谢谢

**Comment by KomachiSion** [comment]
@wpt191 如果没有问题了就关闭issue吧
