### ISSUE TITLE
无法使用 NacosConfigurationProperties

### ISSUE THREAD

**Issue by NineSwordsMonster** [alibaba/spring-cloud-alibaba#1514]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config

**Describe the bug**
使用 `@NacosConfigurationProperties` 读取不到配置

`@NacosInjected` 也为空

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10054584/84133853-4646d280-aa7a-11ea-9e37-697b88af9aeb.png)

**Additional context**
 MacOS  、Java8 、 Version 2.2.1.RELEASE

**Comment by yuhuangbin** [comment]
这是nacos springboot的特性，spring cloud这边暂时不能使用。

**Comment by NineSwordsMonster** [comment]
> 这是nacos springboot的特性，spring cloud这边暂时不能使用。

如果我想手动读取配置，就没法处理，只能使用 extension config 方法吗？

**Comment by yuhuangbin** [comment]
> > 这是nacos springboot的特性，spring cloud这边暂时不能使用。
> 
> 如果我想手动读取配置，就没法处理，只能使用 extension config 方法吗？

spring cloud有自己的读取配置的方式，参照相关文档

**Comment by inkpark** [comment]
请问如何绑定 List<> 或者 Map<> 类型的配置？

**Comment by yuhuangbin** [comment]
https://spring-cloud-alibaba-group.github.io/github-pages/greenwich/spring-cloud-alibaba.html#_how_to_introduce_nacos_config_for_configuration

**Comment by MentosL** [comment]
> 请问如何绑定 List<> 或者 Map<> 类型的配置？

请问 map类型的结构配置解决了吗

**Comment by griffenliu** [comment]
牛，可以把文档写的更清楚一些吗？翻遍了文档，才看到这个issue,确实是因为spring cloud无法使用的原因吗？那至少在类的注释上声明一下吧。。。

**Comment by xdewx** [comment]
探索了好久，就是因为这个一直搞不懂为什么配置无法加载，不能支持下吗

**Comment by Cola5173** [comment]
现在是不是还没解决，压根无法读取到配置中心的配置文件
