### ISSUE TITLE
allowing clients to select the CP RAFT protocol for service registration.

### ISSUE THREAD

**Issue by guozongkang** [alibaba/spring-cloud-alibaba#1520]
The hope is that the JavaClient of Nacos supports the ephemeral parameter, allowing clients to select the CP RAFT protocol for service registration.
nacos-starter.version
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.0.RELEASE</version>
</dependency>

**Comment by yuhuangbin** [comment]
refer : [pr/1448](https://github.com/alibaba/spring-cloud-alibaba/pull/1488)
