### ISSUE TITLE
【报告BUG】spring-cloud-starter-dubbo消费者订阅服务时No provider available from registry localhost:9090

### ISSUE THREAD

**Issue by hardtolose** [alibaba/spring-cloud-alibaba#1529]
spring-cloud-starter-dubbo版本2.2.1.RELEASE

在 AbstractSpringCloudRegistry.doSubscribe() 中可以看到消费者（协议consumer://开头的URL）会订阅所有的service，对应注册中心 /services/ 节点（以zookeeper为例）下的所有服务

private void doSubscribeDubboServiceURLs(URL url, NotifyListener listener) {

	Set<String> subscribedServices = repository.getSubscribedServices();
	// Sync
	subscribedServices.forEach(service -> subscribeDubboServiceURL(url, listener,
				service, this::getServiceInstances));
}

在subscribeDubboServiceURL中service都会通过getServiceInstances获取服务对应的实例ServiceInstance列表

Collection<ServiceInstance> serviceInstances = serviceInstancesFunction.apply(serviceName);

当service获取不到ServiceInstance时，就会触发

allSubscribedURLs.addAll(emptyURLs(url));
if (logger.isDebugEnabled()) {
	logger.debug("The subscribed URL[{}] will notify all URLs : {}", url, allSubscribedURLs);
}
listener.notify(allSubscribedURLs);

消费者consumer://会被改成冠以empty://协议开头，并通知出去，进而在dubbo的RegistryDirectory中，触发以下代码

if (invokerUrls.size() == 1
             && invokerUrls.get(0) != null
             && EMPTY_PROTOCOL.equals(invokerUrls.get(0).getProtocol())) {
            this.forbidden = true; // Forbid to access
            this.invokers = Collections.emptyList();
            routerChain.setInvokers(this.invokers);
            destroyAllInvokers(); // Close all invokers
}

导致consumer的forbidden=true，然后在调用时获取invoker列表时抛出No provider available异常

public List<Invoker<T>> doList(Invocation invocation) {
        if (forbidden) {
            // 1. No service provider 2. Service providers are disabled
            throw new RpcException(RpcException.FORBIDDEN_EXCEPTION, "No provider available from registry " +
                    getUrl().getAddress() + " for service " + getConsumerUrl().getServiceKey() + " on consumer " +
                    NetUtils.getLocalHost() + " use dubbo version " + Version.getVersion() +
                    ", please check status of providers(disabled, not registered or in blacklist).");
        }
        ......
}

问题的原因，为/services/中的某个service没有启动或者已经不需要启动，而注册中心/services下的service节点并未删除，而产生empty://协议地址导致消费者的invokers被覆盖清空，并且forbidden被设置为true，导致无法访问。

目前我们项目中的解决办法是监听HeartbeatEvent事件，然后到注册中心删除空的service节点

请项目开发人员考虑下如何在框架层面解决这个问题，谢谢！

**Comment by dododogamila** [comment]
我用的注册中心是nacos, ，我也遇到了同样的问题，service 被记住了，不知道是不是可以配置，让停了的服务不要被记住

**Comment by hardtolose** [comment]
> 我用的注册中心是nacos, ，我也遇到了同样的问题，service 被记住了，不知道是不是可以配置，让停了的服务不要被记住

没找到配置，我弄了个清理器来清理
@EventListener(HeartbeatEvent.class)
    public void onHeartbeatEvent(HeartbeatEvent event) {
        emptyServiceCleaner.doClean();
    }

public class EmptyServiceCleaner {

    @Autowired
    private CuratorFramework curator;

    @Autowired
    private ZookeeperDiscoveryProperties properties;

    @Autowired
    private DiscoveryClient discoveryClient; // org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient

    public void doClean() {
        try {
            List<String> services = discoveryClient.getServices();
            for (String service : services) {
                if (discoveryClient.getInstances(service).size() == 0) {
                    String servicePath = properties.getRoot() + "/" + service;
                    curator.delete().forPath(servicePath);
                }
            }
        } catch (Exception e) {
        }
    }

}

**Comment by niuzhiweimr** [comment]
有nacos的示例代码吗？

**Comment by niuzhiweimr** [comment]
2.1.2版本也存在这个问题，能否升级一版本

**Comment by niuzhiweimr** [comment]
加个2.1.3的里程牌

**Comment by dododogamila** [comment]
> 有nacos的示例代码吗？

dubbo spring cloud 里的demo，只是用的version是2.2.1

**Comment by dododogamila** [comment]
> > 我用的注册中心是nacos, ，我也遇到了同样的问题，service 被记住了，不知道是不是可以配置，让停了的服务不要被记住
> 
> 没找到配置，我弄了个清理器来清理
> @eventlistener(HeartbeatEvent.class)
> public void onHeartbeatEvent(HeartbeatEvent event) {
> emptyServiceCleaner.doClean();
> }
> 
> public class EmptyServiceCleaner {
> 
> ```
> @Autowired
> private CuratorFramework curator;
> 
> @Autowired
> private ZookeeperDiscoveryProperties properties;
> 
> @Autowired
> private DiscoveryClient discoveryClient; // org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient
> 
> public void doClean() {
>     try {
>         List<String> services = discoveryClient.getServices();
>         for (String service : services) {
>             if (discoveryClient.getInstances(service).size() == 0) {
>                 String servicePath = properties.getRoot() + "/" + service;
>                 curator.delete().forPath(servicePath);
>             }
>         }
>     } catch (Exception e) {
>     }
> }
> ```
> 
> }

我试了一下，确实不会再报错了，但是我有还是有点疑惑，再触发这个listener之前，它还是拿到了所有services的，包括已经失效的services，但是确不在报错了

**Comment by 1095071913** [comment]
> > > 我用的注册中心是nacos, ，我也遇到了同样的问题，service 被记住了，不知道是不是可以配置，让停了的服务不要被记住
> > 
> > 
> > 没找到配置，我弄了个清理器来清理
> > @eventlistener(HeartbeatEvent.class)
> > public void onHeartbeatEvent(HeartbeatEvent event) {
> > emptyServiceCleaner.doClean();
> > }
> > public class EmptyServiceCleaner {
> > ```
> > @Autowired
> > private CuratorFramework curator;
> > 
> > @Autowired
> > private ZookeeperDiscoveryProperties properties;
> > 
> > @Autowired
> > private DiscoveryClient discoveryClient; // org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient
> > 
> > public void doClean() {
> >     try {
> >         List<String> services = discoveryClient.getServices();
> >         for (String service : services) {
> >             if (discoveryClient.getInstances(service).size() == 0) {
> >                 String servicePath = properties.getRoot() + "/" + service;
> >                 curator.delete().forPath(servicePath);
> >             }
> >         }
> >     } catch (Exception e) {
> >     }
> > }
> > ```
> > 
> > 
> > }
> 
> 我试了一下，确实不会再报错了，但是我有还是有点疑惑，再触发这个listener之前，它还是拿到了所有services的，包括已经失效的services，但是确不在报错了

可以看看你的清理器代码吗 ~     我也是用nacos ~  但没找到nacos操作注册表的config class

**Comment by zhaoziji** [comment]
I still encounter this issue in version 2.2.3.RELEASE

**Comment by zhaoziji** [comment]
> > 我用的注册中心是nacos, ，我也遇到了同样的问题，service 被记住了，不知道是不是可以配置，让停了的服务不要被记住
> 
> 没找到配置，我弄了个清理器来清理
> @eventlistener(HeartbeatEvent.class)
> public void onHeartbeatEvent(HeartbeatEvent event) {
> emptyServiceCleaner.doClean();
> }
> 
> public class EmptyServiceCleaner {
> 
> ```
> @Autowired
> private CuratorFramework curator;
> 
> @Autowired
> private ZookeeperDiscoveryProperties properties;
> 
> @Autowired
> private DiscoveryClient discoveryClient; // org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient
> 
> public void doClean() {
>     try {
>         List<String> services = discoveryClient.getServices();
>         for (String service : services) {
>             if (discoveryClient.getInstances(service).size() == 0) {
>                 String servicePath = properties.getRoot() + "/" + service;
>                 curator.delete().forPath(servicePath);
>             }
>         }
>     } catch (Exception e) {
>     }
> }
> ```
> 
> }

这个问题依旧存在，个人觉得无需删除注册中心的信息，仅需“消费端”删除本地无效的“dubbo服务端缓存”即可。

**Comment by Ruling95** [comment]
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-dubbo</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>


<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>

以上为POM配置信息。同样会出现。服务提供者重启之后，消费方无法找到提供者的問題。 希望官方能提供相应的解决方案。
