### ISSUE TITLE
【报告BUG】spring-cloud-starter-cloud非WEB无服务提供者的微服务消费端在DubboServiceRegistrationNonWebApplicationAutoConfiguration中取不到serverPort

### ISSUE THREAD

**Issue by hardtolose** [alibaba/spring-cloud-alibaba#1532]
spring-cloud-starter-dubbo版本2.2.1.RELEASE

在非WEB的微服务中会使用DubboServiceRegistrationNonWebApplicationAutoConfiguration进行配置

其中有个serverPort会在程序启动后进行初始化

private volatile Integer serverPort = null;

@EventListener(ApplicationStartedEvent.class)
public void onApplicationStarted() {
	setServerPort();
	register();
}

setServerPort() 中是从暴露的服务地址中进行获取

private void setServerPort() {
	if (serverPort == null) {
		for (List<URL> urls : repository.getAllExportedUrls().values()) {
			urls.stream()
					.filter(url -> REST_PROTOCOL.equalsIgnoreCase(url.getProtocol()))
					.findFirst().ifPresent(url -> {
						serverPort = url.getPort();
					});

			// If REST protocol is not present, use any applied port.
			if (serverPort == null) {
				urls.stream().findAny().ifPresent(url -> {
					serverPort = url.getPort();
				});
			}
		}
	}
}

如果微服务只消费，没有暴露服务，那么serverPort就会为null，从而导致程序启动失败。

**Comment by zkzlx** [comment]
I have tested 2.2.1 RELEASE version many times and the problem you mentioned has not been found.
Please check you configuration or dependencies.

**Comment by hardtolose** [comment]
> I have tested 2.2.1 RELEASE version many times and the problem you mentioned has not been found.
> Please check you configuration or dependencies.

英语不好直接中文了

这个问题在满足两个条件下是必现的，
1、非WEB环境（配置走DubboServiceRegistrationNonWebApplicationAutoConfiguration）
new SpringApplicationBuilder(XXXStarter.class).web(WebApplicationType.NONE).run(args);
2、程序只消费，没有暴露服务


SpringApplication               :[826] Application run failed

java.lang.NullPointerException: null
	at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceRegistrationNonWebApplicationAutoConfiguration$ZookeeperConfiguration.onServiceInstancePreRegistered(DubboServiceRegistrationNonWebApplicationAutoConfiguration.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
......

**Comment by zkzlx** [comment]
方便的话，能否把demo压缩下发送至我的邮箱 kiss_maple@163.com, @hardtolose

**Comment by hardtolose** [comment]
> 方便的话，能否把demo压缩下发送至我的邮箱 [kiss_maple@163.com](mailto:kiss_maple@163.com), @hardtolose

已发送

**Comment by mercyblitz** [comment]
NO issue

**Comment by DamonK** [comment]
我本地也出现了，这个最后是怎么处理的

**Comment by hardtolose** [comment]
@DamonK 没改源码，直接打破两个条件中的一个。做成web或者加个服务上去
