### ISSUE TITLE
2.2.2 when can it be release ?

### ISSUE THREAD

**Issue by rcfeng** [alibaba/spring-cloud-alibaba#1541]
**Which Component**
eg. Nacos Config, Sentinel

**Describe what problem you have encountered**
sentinel使用nacos作为数据源，但是不支持输入nacos的账号密码，已有贡献者修复于里程碑2.2.2，原定5月31号发布的2.2.2已经延迟很久了
Sentinel uses Nacos as the data source, but does not support entering the account password of Nacos. Some contributors have fixed the milestone 2.2.2. The 2.2.2 originally scheduled to be released on May 31 has been delayed for a long time

**Comment by mercyblitz** [comment]
Will soon

**Comment by ZhangDi-d** [comment]
will it be released this month ？
