### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel:2.2.1会影响controller的数据返回格式

### ISSUE THREAD

**Issue by wangzhedong** [alibaba/spring-cloud-alibaba#1542]
spring-cloud-starter-alibaba-sentinel升级到2.2.1之后，在controller写注解@RestControllerestController返回的数据格式是application/xml而不是json,排查了很久，发现就是spring-cloud-starter-alibaba-sentinel引起的，请问这个问题是怎么引起的？

**Comment by wangzhedong** [comment]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
剔除这个jackson-dataformat-xml就好了

**Comment by SanjiFlip** [comment]
或者加上这个注解
@RequestMapping(value = "/order5/prod/{pid}" ,produces = MediaType.APPLICATION_JSON_UTF8_VALUE)

**Comment by lltx** [comment]
https://juejin.im/post/5e93f6b6e51d4546f27ff50a
