### ISSUE TITLE
Spring Cloud Alibaba 2.2.1.RELEASE 和spring-security-oauth2.0 使用 feign 获取authorities权限数据集合仅获取数组最后一条

### ISSUE THREAD

**Issue by 1653865905** [alibaba/spring-cloud-alibaba#1543]
版本：<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>2.2.1.RELEASE</version>

<dependency>
				<groupId>org.springframework.security.oauth</groupId>
				<artifactId>spring-security-oauth2</artifactId>
				<version>2.3.6.RELEASE</version>
			</dependency>
springboot版本 2.2.6   cloud版本Hoxton.SR3
使用Spring Cloud Alibaba 2.2.0.RELEASE 没有发现此问题 
![image](https://user-images.githubusercontent.com/37290718/85380571-a9069680-b56f-11ea-88de-2f894de30bb9.png)

**Comment by 1653865905** [comment]
获取的权限集合我原来有51条 改了版本后就变成50条了

**Comment by 1653865905** [comment]
获取的权限集合我原来有51条 改了版本后就变成只有最后1条了

**Comment by 1653865905** [comment]
![image](https://user-images.githubusercontent.com/37290718/85381517-a0fb2680-b570-11ea-9b8a-a8d6d7ce8ad5.png)
最后断电跟出来是这个方法返回只剩一条数据

**Comment by 1653865905** [comment]
最后断点跟出来是 public class RestTemplate extends InterceptingHttpAccessor implements RestOperations  这个类的
public <T> T execute(String url, HttpMethod method, @Nullable RequestCallback requestCallback,
			@Nullable ResponseExtractor<T> responseExtractor, Object... uriVariables) throws RestClientException  方法返回数据出的问题

**Comment by lltx** [comment]
问题同  #1544 #1542 

https://github.com/lltx/pig/blob/0f086a4a6146d1cb442f735d993e3a99a830061f/pig-common/pig-common-security/src/main/java/com/pig4cloud/pig/common/security/component/PigResourceServerAutoConfiguration.java#L51-L54
			return execution.execute(request, body);
		}));
