### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel 2.2.1.RELEASE 版本无法自定义异常界面，黑白名单无法生效

### ISSUE THREAD

**Issue by SanjiFlip** [alibaba/spring-cloud-alibaba#1545]
父工程版本
<spring-cloud.version>Hoxton.SR4</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>

自定义的限流异常无法生效

package com.xmaven.config;

import com.alibaba.csp.sentinel.adapter.servlet.callback.UrlBlockHandler;
import com.alibaba.csp.sentinel.slots.block.BlockException;
import com.alibaba.csp.sentinel.slots.block.authority.AuthorityException;
import com.alibaba.csp.sentinel.slots.block.degrade.DegradeException;
import com.alibaba.csp.sentinel.slots.block.flow.FlowException;
import com.alibaba.csp.sentinel.slots.block.flow.param.ParamFlowException;
import com.alibaba.csp.sentinel.slots.system.SystemBlockException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

//自定义返回异常界面
@Component
public class ExceptionHandlerPage implements UrlBlockHandler {

    //BlockException 异常接口,包含Sentinel的五个异常
    // FlowException 限流异常
    // DegradeException 降级异常
    // ParamFlowException 参数限流异常
    // AuthorityException 授权异常
    // SystemBlockException 系统负载异常

    private ResponseData data = null;
    @Override
    public void blocked(HttpServletRequest request, HttpServletResponse response, BlockException e) throws IOException {

        response.setContentType("application/json;charset=utf-8");

        if (e instanceof FlowException) {
            data = ResponseData.builder().code(-1).message("接口被限流了...").build();
        } else if (e instanceof DegradeException) {
            data = ResponseData.builder().code(-2).message("接口被降级了...").build();
        } else if (e instanceof ParamFlowException){
            data = ResponseData.builder().code(-3).message("接口参数限流异常...").build();
        } else if (e instanceof AuthorityException){
            data = ResponseData.builder().code(-4).message("接口授权异常...").build();
        } else if (e instanceof SystemBlockException){
            data = ResponseData.builder().code(-5).message("接口系统负载异常...").build();
        }
        // http状态码
        response.setStatus(500);
        response.setCharacterEncoding("utf-8");
        response.setHeader("Content-Type","application/json;charset=utf-8");
        // Spring MVC自带的json操作工具jackson
        new ObjectMapper().writeValue(response.getWriter(),data);
    }

    @Data
    @Builder
    @AllArgsConstructor//全参构造
    @NoArgsConstructor//无参构造
    static class ResponseData {
        private int code;
        private String message;
    }

}

**Comment by yuhuangbin** [comment]
`UrlBlockHandler` has been deprecated, please use `BlockExceptionHandler` instead.
