### ISSUE TITLE
请问dubbo 序列化的漏洞, spring cloud alibaba 对应的升级版本是什么呢

### ISSUE THREAD

**Issue by YOUHAPPYJlUOK** [alibaba/spring-cloud-alibaba#1547]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by wujincheng2333** [comment]
依赖dubbo 2.7.7版本的，不过目前没看到有dubbo2.7.7版本的更新，并且dubbo2.7.7也不能完全修复漏洞，只是能过安全检查而已

**Comment by fangjian0423** [comment]
可以关注 [版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E) 页面。

每次版本发布都会更新内容。
