### ISSUE TITLE
spring cloud nacos监听到配置文件改变但是没有更新本地配置

### ISSUE THREAD

**Issue by wenshao1121567443** [alibaba/spring-cloud-alibaba#1549]
<dependency>
 				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
				<version>0.9.0.RELEASE</version>
			</dependency>
nacos修改了配置文件，服务监听到了配置修改，我追了一下代码，本地是确实拿到了nacos修改后的配置，但是没有刷新到本地配置，现在不知道是新版本改好了还是一直没有改了

**Comment by zkzlx** [comment]
本地配置刷新，请问这配置是如何使用的呢？对应的类有添加 `@RefreshScope` 或 `@ConfigurationProperties ` 注解么

**Comment by wenshao1121567443** [comment]
找到原因了，@RefreshScope注解是要加在需要刷新数据的变量的类上，我加在了启动类上了，所以导致没有刷新
