### ISSUE TITLE
无法使用 SpringBoot /shutdown 优雅关闭服务

### ISSUE THREAD

**Issue by EyoungShieh1992** [alibaba/spring-cloud-alibaba#1555]
不论是使用自己搭建的项目，还是使用SpringCloudAlibaba提供的示例，开启shutdown端点时，都无法正常关闭项目

![image](https://user-images.githubusercontent.com/31103392/86090382-92ff5580-badc-11ea-9a1f-77bff2bddaa4.png)
![image](https://user-images.githubusercontent.com/31103392/86090474-b7f3c880-badc-11ea-876c-3550d996284b.png)
![image](https://user-images.githubusercontent.com/31103392/86090510-c641e480-badc-11ea-87bb-37c2d85e15ad.png)

**Comment by fangjian0423** [comment]
Similar with https://github.com/alibaba/spring-cloud-alibaba/issues/222.
