### ISSUE TITLE
这么久没活跃了。还发布新版本吗

### ISSUE THREAD

**Issue by lilaizhencn** [alibaba/spring-cloud-alibaba#1556]
这么久没活跃了。还发布新版本吗？

acm 模块不太好用啊。能不能有详细的文档啊。

**Comment by mercyblitz** [comment]
Please use Nacos config~

**Comment by mercyblitz** [comment]
Please view the milestone 2.2.2.RELEASE : https://github.com/alibaba/spring-cloud-alibaba/milestone/7
