### ISSUE TITLE
启动nacos后，启动提供者，为什么按F5刷新nacos web ui时的service list中有时有东西有时没有呢？

### ISSUE THREAD

**Issue by startjava** [alibaba/spring-cloud-alibaba#1563]
是什么情况呢？？

按F5有时候有，有时候没有，出现“没有数据”的提示，但再按F5有可能就出现服务条目 了，

**Comment by startjava** [comment]
难道nacos web ui有限流功能？

**Comment by yuhuangbin** [comment]
可以到[Nacos](https://github.com/alibaba/nacos)社区提issue。
