### ISSUE TITLE
dubbo有计划支持类似feign的调用方式吗？

### ISSUE THREAD

**Issue by startjava** [alibaba/spring-cloud-alibaba#1567]
feign直接调用controller真的挺方便的，，因为有的代码是写在controller中的，功能更容易被复用

**Comment by startjava** [comment]
看了一些资料，，dubbo的proxy是基于JDK的，依赖interface，那么也就意味着必须要通过接口进行远程调用了？即使dubbo能把@Controller对外暴露，那么Controller也要implements 接口，这样Controller就紧耦interface，

**Comment by mercyblitz** [comment]
Please reference to https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample/src/main/java/com/alibaba/cloud/dubbo/bootstrap/DubboSpringCloudConsumerBootstrap.java
