### ISSUE TITLE
在官方的dubbo的demo中，这两者写法有什么区别呢？

### ISSUE THREAD

**Issue by startjava** [alibaba/spring-cloud-alibaba#1568]
@FeignClient("${provider.application.name}")
	public interface FeignRestService {

--------------------------------------------------------------
	@FeignClient("${provider.application.name}")
	@DubboTransported(protocol = "dubbo")
	public interface DubboFeignRestService {

--------------------------------------------------------
一个走的是http协议？，一个走的是dubbo协议？

**Comment by mercyblitz** [comment]
Yes, you got it.
