### ISSUE TITLE
新增流控规则后，为什么没有显示在流控规则列表，配置无法生效!

### ISSUE THREAD

**Issue by zq0757** [alibaba/spring-cloud-alibaba#1570]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by zq0757** [comment]
新增流控规则后，为什么没有显示在流控规则列表，配置无法生效

**Comment by zq0757** [comment]
新增流控规则后，为什么没有显示在流控规则列表，配置无法生效

**Comment by fangjian0423** [comment]
Refer https://github.com/alibaba/Sentinel/wiki/%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Sentinel.
