### ISSUE TITLE
Nacos 1.3.0 and Dubbo 2.7.7 are supported

### ISSUE THREAD

**Issue by metaphysical-road** [alibaba/spring-cloud-alibaba#1571]
**When will Nacos 1.3.0 and Dubbo 2.7.7 be supported**

we use the  latest version of spring cloud alibaba, but it not support Nacos 1.3.0 and Dubbo 2.7.7,  Dubbo 2.7.6 and the low version have serialization security issues.

**Comment by yuhuangbin** [comment]
We are working on it.
