### ISSUE TITLE
spring cloud stream rocketmq The problem of catching exceptions when a producer sends a message exception (当生产者发送消息异常时捕捉异常的问题)

### ISSUE THREAD

**Issue by dsadsaad** [alibaba/spring-cloud-alibaba#1573]
用spring-cloud-starter-stream-rocketmq 方式使用Rocketmq(ONS)
项目已在阿里云上线两周,这两周mq是全部正常推送和接收的.
但是昨天晚上9:01 发生了消息**部分**推送失败异常
异常信息是

RocketMQMessageHandler         ERROR  RocketMQ Message hasn't been sent. Caused by No route info of this topic, MQ_INST_1349000000083961_Bc0CmRiE%prod-detail-topic

在推送此条消息的前一条是正常推送成功的,报了此异常后,程序 **没有重启或重新连**,但后续的消息是正常推送的.

提交工单给阿里云 工作人员经过后台以及日志查询反馈该问题是由于nameserver 短时抖动引起的.建议对消息发送段的代码进行全面的try-catch，做好重试.

但是我的业务场景send是需要异步进行的(默认异步),无法直接对send部分代码进行try catch异常捕捉.

通过阅读issues  https://github.com/alibaba/spring-cloud-alibaba/issues/577 得知通过设置errorChannelEnabled=true 方式可通过xxxtopic.errors 方式订阅到MessagingException从而达到自定义处理异常.
但是该处理方式有**两个**明显的问题

1.参考了 https://github.com/alibaba/spring-cloud-alibaba/issues/577 改造了项目发现不能正常接收所有订阅的异常
每次推送异常 第一次会被我的@ServiceActivator(inputChannel = "xxxxxx.errors")方式捕捉,接着进行第二次异常的推送
我的@ServiceActivator(inputChannel = "xxxxxx.errors")无法正常捕获,异常信息被LoggingHandler输出到控制台.经过测试发现
当LoggingHandler捕捉到异常时,我的@ServiceActivator就无法捕获.我的@ServiceActivator正常捕捉时,控制台就不会输出LoggingHandler信息.
订阅的errors是平均分摊到我的@ServiceActivator(inputChannel = "xxxxxx.errors")与LoggingHandler
导致我不能正常处理所有的发送异常

2无法避免硬编码
@ServiceActivator(inputChannel = "xxxxxx.errors")
直接填入字符串inputChannel = "xxxxxx.errors"方式可以正常订阅

@ServiceActivator(inputChannel = "${xxxx.xxx}")
SPEL表达式方式无法正常接收errors

@ServiceActivator(inputChannel = MyChannelInterface.out+".errors")
参考官方文档的方式也无法接收errors

**Comment by dsadsaad** [comment]
如有需要我可以提供全套环境的demo

**Comment by dsadsaad** [comment]
环境信息:
Spring Cloud alibaba版本 2.1.0.RELEASE

**Comment by dsadsaad** [comment]
问题demo 请看
https://github.com/dsadsaad/rocketmq-demo

**Comment by fangjian0423** [comment]
>> 1.参考了 #577 改造了项目发现不能正常接收所有订阅的异常
每次推送异常 第一次会被我的@serviceactivator(inputChannel = "xxxxxx.errors")方式捕捉,接着进行第二次异常的推送
我的@serviceactivator(inputChannel = "xxxxxx.errors")无法正常捕获,异常信息被LoggingHandler输出到控制台.经过测试发现
当LoggingHandler捕捉到异常时,我的@serviceactivator就无法捕获.我的@serviceactivator正常捕捉时,控制台就不会输出LoggingHandler信息.
订阅的errors是平均分摊到我的@serviceactivator(inputChannel = "xxxxxx.errors")与LoggingHandler
导致我不能正常处理所有的发送异常

这个问题是 [Spring Cloud Stream 的 bug](https://github.com/spring-cloud/spring-cloud-stream/issues/1510)，尝试升级到 2.1.1.RELEASE

**Comment by dsadsaad** [comment]
> > > 1.参考了 #577 改造了项目发现不能正常接收所有订阅的异常
> > > 每次推送异常 第一次会被我的@serviceactivator(inputChannel = "xxxxxx.errors")方式捕捉,接着进行第二次异常的推送
> > > 我的@serviceactivator(inputChannel = "xxxxxx.errors")无法正常捕获,异常信息被LoggingHandler输出到控制台.经过测试发现
> > > 当LoggingHandler捕捉到异常时,我的@serviceactivator就无法捕获.我的@serviceactivator正常捕捉时,控制台就不会输出LoggingHandler信息.
> > > 订阅的errors是平均分摊到我的@serviceactivator(inputChannel = "xxxxxx.errors")与LoggingHandler
> > > 导致我不能正常处理所有的发送异常
> 
> 这个问题是 [Spring Cloud Stream 的 bug](https://github.com/spring-cloud/spring-cloud-stream/issues/1510)，尝试升级到 2.1.1.RELEASE

好的,我试试在回馈

**Comment by dsadsaad** [comment]
> > > 1.参考了[＃577](https://github.com/alibaba/spring-cloud-alibaba/issues/577)改造了项目发现不能正常接收所有
> > > 订阅的异常时发生异常异常第一次会被我的@serviceactivator（inputChannel =“ xxxxxx.errors”）方式，然后进行第二次异常的推送
> > > 我的@serviceactivator（inputChannel = “xxxxxx.errors”）无法正常捕获，异常信息被LoggingHandler输出到控制台。测试经过发现
> > > 当LoggingHandler捕捉到异常时，我的@serviceactivator就无法捕获。我的@serviceactivator正常捕捉时，控制台就不会输出LoggingHandler信息。订阅
> > > 的错误是平均分摊到我的@serviceactivator（inputChannel =“ xxxxxx.errors”）与LoggingHandler 
> > > 导致我不能正常处理所有的发送异常
> 
> 这个问题是[Spring Cloud Stream的bug](https://github.com/spring-cloud/spring-cloud-stream/issues/1510)，尝试升级到2.1.1.RELEASE

通过运行我的demo 修改版本放此BUG仍然存在.无法捕捉所有的异常.

**Comment by fangjian0423** [comment]
确定这个问题已经被修复 😄  可以提供一个最小的复现 demo

**Comment by dsadsaad** [comment]
> 确定这个问题已经被修复 😄 可以提供一个最小的复现 demo

你好,Demo请看https://github.com/dsadsaad/rocketmq-demo
运行后,访问127.0.0.1:8080/testsend触发发送异常
