### ISSUE TITLE
bootstrap.yml配置nacos地址问题（Bootstrap.yml configuration nacos address problem）

### ISSUE THREAD

**Issue by skykis** [alibaba/spring-cloud-alibaba#1575]
日志可以见https://github.com/alibaba/spring-cloud-alibaba/issues/1574#issue-651642281

触发似乎是因为没有配置spring.cloud.nacos.server-addr项，只配了spring.cloud.nacos.discovery.server-addr项，所以spring.cloud.nacos.discovery.server-addr被覆盖成了默认值localhost:8848（默认值？）。当2个值都配置的时候spring.cloud.nacos.discovery.server-addr反而不会被spring.cloud.nacos.server-addr覆盖

The log can be seen at https://github.com/alibaba/spring-cloud-alibaba/issues/1574#issue-651642281

The trigger seems to be because the spring.cloud.nacos.server-addr item is not configured, and only the spring.cloud.nacos.discovery.server-addr item is configured, so spring.cloud.nacos.discovery.server-addr is overwritten as the default The value localhost:8848 (default?). When both values are configured, spring.cloud.nacos.discovery.server-addr will not be overwritten by spring.cloud.nacos.server-addr

**Comment by yuhuangbin** [comment]
If you only need to use nacos for registration and discovery without dynamic configuration service, you only need to add dependencies
```xml
<dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
 </dependency>
```
However, if you use the nacos dynamic configuration service, you need to add dependencies and add related configuration items in `bootstrap.properties`.

```xml
<dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
 </dependency>
```
