### ISSUE TITLE
虚拟机部署nacos,本机微服务配置虚拟机ip，但是启动访问localhost

### ISSUE THREAD

**Issue by tczml** [alibaba/spring-cloud-alibaba#1576]
虚拟机部署nacos,本机微服务配置虚拟机ip，但是启动访问localhost

**Comment by yuhuangbin** [comment]
是nacos config模块吗？麻烦提供日志出来

**Comment by tczml** [comment]
非常感谢您的回复，之前一直解决不了问题，我就恢复了本地nacos，因为是集成seata,所以调整了nacos的配置位置，从application.yml,改到了bootstrap.yml；刚才看到你的邮件，我就把nacos的ip换成虚拟机的ip，重新启动后发现不报错了，也不知道什么原理？然后我又改回之前在application里配置方式，试了一下还是报之前错误，它自动访问的是localhost：8848 ，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "余黄彬"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 下午5:01
收件人: "alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com&gt;; 
抄送: "浴火流星"<724765659@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/spring-cloud-alibaba] 虚拟机部署nacos,本机微服务配置虚拟机ip，但是启动访问localhost (#1576)





 
是nacos config模块吗？麻烦提供日志出来

**Comment by yuhuangbin** [comment]
nacos config模块相关的配置需要配置在`bootstrap.yml`里。

**Comment by tczml** [comment]
&nbsp; &nbsp; &nbsp; 哦，因为是视频学习的nacos简单本地配置，没说要用bootstrap配置，所以一直找不到配置不生效原因，开始还以为nacos还有什么默认配置需要修改呢。
感谢您百忙之中还帮忙解决我的疑惑，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "余黄彬"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 上午8:57
收件人: "alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com&gt;; 
抄送: "浴火流星"<724765659@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/spring-cloud-alibaba] 虚拟机部署nacos,本机微服务配置虚拟机ip，但是启动访问localhost (#1576)





 
nacos config模块相关的配置需要配置在bootstrap.yml里。

**Comment by Liu1796997299** [comment]
> nacos config模块相关的配置需要配置在`bootstrap.yml`里。
我用的2.2.1，在bootstrap.yml中指定配置中心依然无效，降版本也不行。改用springcloud的config了，没办法
