### ISSUE TITLE
更新到spring-cloud-alibaba-dependencies  2.2.1.RELEASE 出现原先的配置读取错误

### ISSUE THREAD

**Issue by ljwps** [alibaba/spring-cloud-alibaba#1578]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-alibaba-dependencies  version: 2.2.1.RELEASE
spring-cloud-starter-alibaba-nacos-config   version: 2.2.1.RELEASE
nacos服务版本：version: 1.1.3
spring boot 2.2.5  2.2.6  
spring cloud Hoxton.SR3  Hoxton.SR4

**Describe the bug**
更新到spring-cloud-alibaba-dependencies  2.2.1.RELEASE 出现配置读取错误，原来用2.1.1是好的
spring boot 2.2.5  2.2.6  
spring cloud Hoxton.SR3  Hoxton.SR4
都试过一样的错误

**To Reproduce**
我的nacos中application配置文件样例如下：
>server:
&nbsp;&nbsp;servlet:
&nbsp;&nbsp;&nbsp;&nbsp;context-path:&nbsp;/yourproject-server
&nbsp;&nbsp;port:&nbsp;8082
ibcc:
&nbsp;&nbsp;db:&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;conns:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url:&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sharding-tables:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;column-name:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;table-name:

我的应用中bootstrap配置文件样例如下：
> spring:
&nbsp;&nbsp;application:
&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;yourproject-server
&nbsp;&nbsp;cloud:
&nbsp;&nbsp;&nbsp;&nbsp;nacos:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;config:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;server-addr:&nbsp;127.0.0.1:8848
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enabled:&nbsp;true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;group:&nbsp;YOURPROJECT-SERVER
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file-extension:&nbsp;yml

我的配置类如下：
> package&nbsp;com.ibcc.test;
import&nbsp;org.springframework.boot.context.properties.ConfigurationProperties;
import&nbsp;org.springframework.context.annotation.Configuration;
import&nbsp;java.util.List;
import&nbsp;java.util.Map;
/**
&nbsp;*&nbsp;数据源配置
&nbsp;*/
@Configuration
@ConfigurationProperties(prefix&nbsp;=&nbsp;"ibcc.db")
public&nbsp;class&nbsp;DbProperties&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;private&nbsp;Map&lt;String,&nbsp;DbConnConfig&gt;&nbsp;conns;
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;Map&lt;String,&nbsp;DbConnConfig&gt;&nbsp;getConns()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;conns;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;void&nbsp;setConns(Map&lt;String,&nbsp;DbConnConfig&gt;&nbsp;conns)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.conns&nbsp;=&nbsp;conns;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;/**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;数据源的conn属性
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*/
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;static&nbsp;class&nbsp;DbConnConfig&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;private&nbsp;String&nbsp;url;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;private&nbsp;List&lt;ShardingTable&gt;&nbsp;shardingTables;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;void&nbsp;setUrl(String&nbsp;url)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.url&nbsp;=&nbsp;url;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;String&nbsp;getUrl()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;url;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;List&lt;ShardingTable&gt;&nbsp;getShardingTables()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;shardingTables;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;void&nbsp;setShardingTables(List&lt;ShardingTable&gt;&nbsp;shardingTables)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.shardingTables&nbsp;=&nbsp;shardingTables;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;/**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;分表
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*/
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;static&nbsp;class&nbsp;ShardingTable&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;private&nbsp;String&nbsp;columnName;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;private&nbsp;String&nbsp;tableName;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;String&nbsp;getColumnName()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;columnName;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;void&nbsp;setColumnName(String&nbsp;columnName)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.columnName&nbsp;=&nbsp;columnName;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;String&nbsp;getTableName()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tableName;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;void&nbsp;setTableName(String&nbsp;tableName)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.tableName&nbsp;=&nbsp;tableName;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
}

**Expected behavior**
启动的时候遇到这种配置写法就报错。报错如下：
>org.springframework.boot.context.properties.bind.BindException:&nbsp;Failed&nbsp;to&nbsp;bind&nbsp;properties&nbsp;under&nbsp;'ibcc.db.conns.default.sharding-tables'&nbsp;to&nbsp;java.util.List<com.ibcc.test.DbProperties$ShardingTable>
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:364)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:324)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:448)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:90)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:79)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:56)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:452)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:572)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:558)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:513)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:450)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:391)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:320)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$null$1(Binder.java:412)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withSource(Binder.java:543)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.access$900(Binder.java:513)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:413)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.AggregateElementBinder.bind(AggregateElementBinder.java:39)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.lambda$bindEntries$0(MapBinder.java:157)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.HashMap.computeIfAbsent(HashMap.java:1126)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.bindEntries(MapBinder.java:157)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:68)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:415)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:572)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.access$100(Binder.java:513)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:415)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:376)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:320)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:448)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:90)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:79)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:56)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:452)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:572)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:558)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:513)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:450)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:391)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:320)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:308)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:238)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:225)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:89)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:96)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.ibcc.test.IbccComplatServerApplication.main(IbccComplatServerApplication.java:16)
Caused&nbsp;by:&nbsp;java.lang.NullPointerException:&nbsp;null
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.TreeMap.compare(TreeMap.java:1294)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.TreeMap.put(TreeMap.java:538)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.TreeSet.add(TreeSet.java:255)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.Iterator.forEachRemaining(Iterator.java:116)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.IndexedElementsBinder.assertNoUnboundChildren(IndexedElementsBinder.java:136)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:113)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:86)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:71)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.CollectionBinder.bindAggregate(CollectionBinder.java:49)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:415)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:572)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder$Context.access$100(Binder.java:513)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:415)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:376)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:320)
&nbsp;&nbsp;&nbsp;&nbsp;...&nbsp;62&nbsp;common&nbsp;frames&nbsp;omitted
2020-07-12&nbsp;00:20:14.580&nbsp;[yourproject-server]&nbsp;[]&nbsp;ERROR&nbsp;LoggingFailureAnalysisReporter:40&nbsp;-&nbsp;
>***************************
>APPLICATION&nbsp;FAILED&nbsp;TO&nbsp;START
>***************************
>Description:
Failed&nbsp;to&nbsp;bind&nbsp;properties&nbsp;under&nbsp;'ibcc.db.conns.default.sharding-tables'&nbsp;to&nbsp;java.util.List<com.ibcc.test.DbProperties$ShardingTable>:
&nbsp;&nbsp;&nbsp;&nbsp;Reason:&nbsp;Failed&nbsp;to&nbsp;bind&nbsp;properties&nbsp;under&nbsp;'ibcc.db.conns.default.sharding-tables'&nbsp;to&nbsp;java.util.List<com.ibcc.test.DbProperties$ShardingTable>

**Screenshots**
无

**Additional context**
windows10、jdk8

**Comment by guerlab** [comment]
有空指针的发生，你可以先看下是什么对象产生了空指针

**Comment by ljwps** [comment]
> 有空指针的发生，你可以先看下是什么对象产生了空指针

分析过异常堆栈，感觉是从读取配置到spring那条线出现的，但并没能发现确切的问题，我把我的配置的类的对应属性的set方法加了断点，还没有走到里面就报错了。奇怪的是我用低版本的 spring-cloud-alibaba-dependencies 2.1.1 就没问题

**Comment by M1NGc** [comment]
100%复现吗

**Comment by ljwps** [comment]
> 100%复现吗

是的 100% 复现，上面的代码  大佬可以直接用下看看。

**Comment by zkzlx** [comment]
是因为不支持yaml文件部分语法导致的，该问题已在 #1531 中修复

**Comment by ljwps** [comment]
> 是因为不支持yaml文件部分语法导致的，该问题已在 #1531 中修复

能透露下什么是否发修复版本么

**Comment by ljwps** [comment]
@zkzlx 请问一下，这个问题在哪个版本修复并发布了？

**Comment by zkzlx** [comment]
> @zkzlx 请问一下，这个问题在哪个版本修复并发布了？

应该是下个版本吧， @yuhuangbin @mercyblitz @fangjian0423  具体的发布计划安排，各位看下
