### ISSUE TITLE
POM文件Java版本生成错误

### ISSUE THREAD

**Issue by jf11480** [alibaba/spring-cloud-alibaba#1579]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
https://start.aliyun.com/

**Describe the bug**
生成的POM.xml当中
  properties-> java.version是1.8 应该是所选版本

**To Reproduce**
1.进入https://start.aliyun.com/
2.选择 MavenProject
3.应用架构选 NONE
4 .Spring Boot版本  2.3.0
5.项目基本信息

项目名称 默认
项目描述 默认
基础包 默认
导包方式 Jar
Java 版本 14
依赖 Spring Boot Starter Web

java版本错误,应该是14,而不是 1.8

POM文件当中的
```java
<properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.3.0.RELEASE</spring-boot.version>
    </properties>
```

以及
```java
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25859453/87246919-14fb6100-c483-11ea-847d-96e587c3a5da.png)

**Additional context**

**Comment by theonefx** [comment]
fixed
