### ISSUE TITLE
找不到nacos注册中心客户端配置nacos服务的服务名

### ISSUE THREAD

**Issue by axiang9945** [alibaba/spring-cloud-alibaba#1582]
nacos的注册中心
Nacos Discovery

我修改了nacos服务的服务名称，但我在配置注册中心配置时，只找到了配置地址，但没有找到配置服务名称（contextPath，默认nocas）的配置项，我在源码中发现，这个api调用地址是常用变量写死在代码中
I modified the service name of the Nacos service, but when I configured the registry configuration, I only found the configuration address, but I did not find the configuration item of the configuration service name (contextpath, default nocas). In the source code, I found that the API call address is a common variable written in the code

想知道如何覆盖配置默认的nacos配置，谢谢
Would like to know how to override the default Nacos configuration, thank you
![TIM截图20200714160316](https://user-images.githubusercontent.com/34832545/87400689-b6052b80-c5eb-11ea-813f-4518f0a6375c.png)

**Comment by yuhuangbin** [comment]
Sorry, I don’t know what the configuration you want is, but you can find it at `NacosDiscoveryProperties` or `NacosConfigProperties`.
