### ISSUE TITLE
springCloudAlibaba does not support sentinel config with username and password

### ISSUE THREAD

**Issue by apple987** [alibaba/spring-cloud-alibaba#1585]
The latest version of the code does not support configuring the user name and password to read the rules in Nacos. If Nacos is configured with permissions, it will be troublesome here. In order to save resources, it is recommended to add the permission data that can read the corresponding account according to the user name and password！
the current version:
 <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-circuitbreaker-sentinel</artifactId>
      <version>2.2.1.RELEASE</version>
    </dependency>
my config like this:
spring:
  cloud:
    sentinel: #sentinel限流器
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
      eager: true #懒加载关闭
        #规则看这里 org.springframework.cloud.alibaba.sentinel.datasource.RuleType
        #因为spring-cloud-starter-alibaba-sentinel目前2.2.1版本不支持username,password,
        #如果使用可以单独配置一个不开启验证的限流服务器的nacos
        #限流规则请参考这里NacosDataSourceProperties,折中的办法就是暂时配置一个不验证权限的限流nacos
#        datasource:
#        flow:
#          nacos:
#            server-addr: ${spring.nacos-host}:${spring.nacos-port}
#            username: ${spring.nacos-username}
#            password: ${spring.nacos-password}
#            dataId: ${spring.application.name}-sentinel-flow
#            groupId: SENTINEL_GROUP
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: ${spring.nacos-host}:${spring.nacos-port}
#            username: ${spring.nacos-username}
#            password: ${spring.nacos-password}
#            dataId: ${spring.application.name}-sentinel-degrade
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#        system:
#          nacos:
#            server-addr: ${spring.nacos-host}:${spring.nacos-port}
#            username: ${spring.nacos-username}
#            password: ${spring.nacos-password}
#            dataId: ${spring.application.name}-sentinel-system
#            groupId: SENTINEL_GROUP
#            rule-type: system
#        authority:
#          nacos:
#            server-addr: ${spring.nacos-host}:${spring.nacos-port}
#            username: ${spring.nacos-username}
#            password: ${spring.nacos-password}
#            dataId: ${spring.application.name}-sentinel-authority
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#        param-flow:
#          nacos:
#            server-addr: ${spring.nacos-host}:${spring.nacos-port}
#            username: ${spring.nacos-username}
#            password: ${spring.nacos-password}
#            dataId: ${spring.application.name}-sentinel-param-flow
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow
but when i start up my project,this config is unable to read,look this class: NacosDataSourceProperties,
it does not support config with username and password,need to fixed，thanks！

**Comment by yuhuangbin** [comment]
Spring Cloud Alibaba 2.2.1.RELEASE already supported.  you can see it at `NacosDataSourceProperties.java` .

**Comment by yuhuangbin** [comment]
[Sentinel Example](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example)
