### ISSUE TITLE
Nacos Discovery 默认使用 Ribbon, 怎么切换到使用 spring-cloud-loadbalancer

### ISSUE THREAD

**Issue by R-anybbo** [alibaba/spring-cloud-alibaba#1592]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Discovery 

**Describe what problem you have encountered**
Nacos Discovery uses Ribbon by default, how to switch to spring-cloud-loadbalancer ? 

**Describe what information you have read**

**Comment by yuhuangbin** [comment]
`spring.cloud.loadbalancer.ribbon.enabled=false` 
```xml
<dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-loadbalancer</artifactId>
 </dependency>
```

**Comment by R-anybbo** [comment]
> `spring.cloud.loadbalancer.ribbon.enabled=false`
> 
> ```
> <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-starter-loadbalancer</artifactId>
>  </dependency>
> ```

这样切换成 spring-cloud-starter-loadbalancer 时, Nacos 的负载均衡能力是不是就没有了

**Comment by yuhuangbin** [comment]
Nacos本身没有负载均衡的能力，可以提供详细的配置，使用情况及错误信息出来。

**Comment by R-anybbo** [comment]
找到问题了, 是我配置的不对,  提前初始化了 `FeignAutoConfiguration` 导致没有注册上 feign 的 `Client`. 谢谢 @yuhuangbin

**Comment by JohnNiang** [comment]
引入 `org.springframework.cloud:spring-cloud-starter-loadbalancer` 后应排除 `spring-cloud-starter-netflix-ribbon` 依赖：

```yml
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

这样才能够使用 `org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient`，而不是 `org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient`。
