### ISSUE TITLE
项目维护进度太慢

### ISSUE THREAD

**Issue by brucewuu520** [alibaba/spring-cloud-alibaba#1597]
项目进展太缓慢了，290个issue没解决；也没有版本发布计划；我公司的项目都已经上生产阿里云了；恳求尽快解决issue；适配新版本的Spring boot和cloud

**Comment by petrel1024** [comment]
同求

**Comment by lizhian** [comment]
不会挖了个坑然后不管吧

**Comment by khiker007** [comment]
建议做好最坏打算吧，准备springcloud原生版本或自己维护一套SCA

**Comment by 15605912544** [comment]
项目进展太缓慢了，291个issue没解决；希望能尽快解决issue；

**Comment by m1ngyuan** [comment]
哎，我已经用回原生版本了，可能是祖传的KPI项目吧！

**Comment by khiker007** [comment]
蚂蚁金服要上市，估计都没心思维护了吧，毕竟都要财富自由了

**Comment by khiker007** [comment]
希望停止维护，也能发个通知，不要直接扔着不管了

**Comment by M1NGc** [comment]
有些issue可能并不是问题且没有关闭

**Comment by MingIXu** [comment]
官方应该出来说明下吧，几个月没动静

**Comment by fevenor** [comment]
2.2.2.RELEASE 还有 8 open，逾期9天

**Comment by yuhuangbin** [comment]
We are working for it. welcome to participate in the community.
