### ISSUE TITLE
关于远程nacos的问题

### ISSUE THREAD

**Issue by xpp666** [alibaba/spring-cloud-alibaba#1600]
我在本地环境开发，配置云服务器启动的nacos，nacos控制台服务列表能看到注册服务成功，并且使用也不会有什么问题。但是本地日志一直报错 "[NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err: Connection refused: connect " ,这是什么情况啊？

**Comment by yuhuangbin** [comment]
`Nacos-Config` 相关的配置，需要配置在`bootstrap.properties`, 具体参考文档 [Nacos-Config Wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config)
