### ISSUE TITLE
使用sidecar组件整合异构服务时，nacos注册中心会显示2个实例

### ISSUE THREAD

**Issue by Codding-Huntsman** [alibaba/spring-cloud-alibaba#1602]
### 问题描述

使用`spring-cloud-starter-alibaba-sidecar`代理异构服务时，注册中心会负载2个实例问题，导致部分请求无效

### 版本号

- `Nacos`：1.2.1和1.3.1
- `spring-cloud-starter-alibaba-sidecar`：2.2.1

### 问题截图

使用官方提供的example启动时发生的问题

![](https://user-images.githubusercontent.com/25610769/88473820-d91ccd00-cf53-11ea-9a0f-88c562725a77.png)

**Comment by yuhuangbin** [comment]
该问题已修复，请等待新版本发布。
