### ISSUE TITLE
关于spring-cloud-alibaba 2.2.1.RELEASE版本无法添加spring-cloud-starter-alicloud-oss组件问题

### ISSUE THREAD

**Issue by AvengerEug** [alibaba/spring-cloud-alibaba#1603]
* 背景：由[spring-cloud-alibaba毕业版本依赖关系(推荐使用)](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E#%E6%AF%95%E4%B8%9A%E7%89%88%E6%9C%AC%E4%BE%9D%E8%B5%96%E5%85%B3%E7%B3%BB%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8)可知，在spring-cloud【**`Hoxton.SR3`**】版本中应该依赖spring-cloud-alibaba【**`2.2.1.RELEASE`**】版本，但却无法依赖**spring-cloud-starter-alicloud-oss**组件。
* 疑问：在[`2.2.1.RELEASE`分支的starter包](https://github.com/alibaba/spring-cloud-alibaba/tree/2.2.1.RELEASE/spring-cloud-alibaba-starters)下并未看到关于**spring-cloud-starter-alicloud-oss**组件的starter，请问是因为spring-cloud-alibaba【**`2.2.1.RELEASE`**】版本未集成**spring-cloud-starter-alicloud-oss**组件么？

* 问题重现：
1. 父模块maven依赖:
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

2. 子模块依赖spring-cloud-starter-alicloud-oss
```xml
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alicloud-oss</artifactId>
        </dependency>
```

3. 版本依赖一览
![result](https://avenger-mall.oss-cn-hangzhou.aliyuncs.com/spring-cloud-alibaba-oss-quesion.png)

**Comment by yuhuangbin** [comment]
Spring Cloud Alibaba 商业化组件已经迁移到 [aliyun-spring-boot](https://github.com/alibaba/aliyun-spring-boot) 仓库。

**Comment by AvengerEug** [comment]
感谢回复，已完美解决~

**Comment by AvengerEug** [comment]
> Spring Cloud Alibaba 商业化组件已经迁移到 [aliyun-spring-boot](https://github.com/alibaba/aliyun-spring-boot) 仓库。

感谢回复，已完美解决~
