### ISSUE TITLE
引入spring-cloud-starter-alibaba-sentinel 2.2.0.RELEASE,怎么设置全局的自定义限流处理逻辑

### ISSUE THREAD

**Issue by cssherlock** [alibaba/spring-cloud-alibaba#1605]
在项目中引入spring-cloud-starter-alibaba-sentinel，版本2.2.0.RELEASE之后，发现没有WebCallbackManager，然后又引入了sentinel-web-servlet

添加了如下代码
`@Component
public class SentinelConfig {
    public SentinelConfig() {
        WebCallbackManager.setUrlBlockHandler(new UrlBlockHandler() {
            @Override
            public void blocked(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, BlockException e) throws IOException {
                HashMap<String, String> map = new HashMap<>();
                map.put("code","1002");
                map.put("msg","请求流量过大");

                httpServletResponse.setCharacterEncoding("utf-8");
                httpServletResponse.setContentType("application/json");
                httpServletResponse.getWriter().write(JSON.toJSONString(map));
            }
        });
    }
}`

发现没有生效，最终请求限流之后，还是显示的默认信息 Blocked by Sentinel (flow limiting)

请问一下， 这个是需要怎么配置

**Comment by yuhuangbin** [comment]
Custom a bean, implement `BlockExceptionHandler`

**Comment by cssherlock** [comment]
yes,thank you
