### ISSUE TITLE
[NACOS CONFIG] Recommended add ServerHttpAgent  retry interval parameter

### ISSUE THREAD

**Issue by coolbeevip** [alibaba/spring-cloud-alibaba#1607]
Component:  Nacos Config

I cannot use the `spring.cloud.nacos.config.maxRetry` and `spring.cloud.nacos.config.timeout` parameters to precisely control the duration of the retry.

E.g.: I want to retry for 30 seconds, using the following parameters may be closer to my expectations

```
spring.cloud.nacos.config.maxRetry=30
spring.cloud.nacos.config.RetryInterval=1000  (ms)
spring.cloud.nacos.config.timeout=30000
```

**Comment by yuhuangbin** [comment]
`spring.cloud.nacos.config.maxRetry`  means nacos maximum number of tolerable server reconnection errors.

the `spring.cloud.nacos.config.configLongPollTimeout` used to control the time-consuming retry.

**Comment by yuhuangbin** [comment]
you can refer : https://nacos.io/zh-cn/docs/system-configurations.html
and `ServerHttpAgent.java`
