### ISSUE TITLE
[feature]  应用外配置应用所需的各配置文件

### ISSUE THREAD

**Issue by fudali113** [alibaba/spring-cloud-alibaba#161]
应该有一些差别，我不希望通过范匹配来进行一个数据的拉取，我希望所有的配置拉取都是明确的，这也是我不太认可第一种方案的原因之一；

我的意思大概是这个样子的：
比如我的应用配置是这个样子的：
```
spring.cloud.nacos.shared.dataids=global.yaml,app-common.yaml,app-local-common.yaml
```

然后我的`app-common.yaml` 配置是这个样子的：
```yaml
include-dataids:
- xxx.yaml
```

那么最终 `xxx.yaml` 也会加载成为我应用的配置，`xxx.yaml`的优先级比 include 他的配置文件(`app-common.yaml`) 优先级略低，但是优先级高于基础配置中比 `app-common.yaml` 优先级更低的配置 `global.yaml` ;

所有的 dataId 都是必须手动制定的，虽然范匹配和基于一定规则匹配会带来一定的遍历性，但是也可能在某些时候带来一定的不确定性(比如配置的人还不太熟悉该规则？或者是一时忘记了某种规则？)

# 更简洁一些的方案

同时，以上只是基于第二种方案提出的，在于优先级的处理上可能会有些复杂，那是不是也可以简单点的定义为在应用基础配置中只能配置一个 `dataId: app-local-common.yaml`，然后在 `app-local-common.yaml` 中去做 `include` 的操作？

# 想法的来源

我的方案大致来自于我的两个对于配置中的诉求：
* 所有配置的加载必须明确指定；(范匹配带来便利，但是需要对规则高度熟悉；对人的要求比较高，但是并不是所有人都优秀)
*  我们应该尽可能的把配置交给配置中心处理；(这也是我们需要配置中心的理由，使用配置中心就是为了把配置独立出去；除了应用与配置的关联，我觉得其他的配置都应该交给配置中心)

**Comment by pbting** [comment]
非常感谢您提供的场景。我们仔细讨论了关于您的这个场景，发现如果将可配置的文件暴露在一个比较容易修改的白屏化操作的界面，这样某种程度上会带来系统配置的风险度，同时也带来了另外一个比较迫切的要求:那就是 Nacos 需要对配置权限的管理支持非常的完善。所以综合考虑暂时不考虑进去，Nacos 团队正在做权限管理模块的功能，等他们成熟了，届时会考虑实现进来。
再次感谢您提供的场景。

**Comment by fudali113** [comment]
那如果不是一配置中加载配置的方式呢？ 如果我们可以在外部建立一个应用名跟配置文件的映射这种方式呢？

即我们在 nacos config 的服务端维护一个 应用名 与 dataId 的映射关系；

你觉得这种方式怎么样呢？ @pbting

**Comment by fudali113** [comment]
或者是我们可以更近一部，在 nacos config 服务端抽象一个 app 的概念，然后我们在应用的匹配里面只需要配置 app 的相关信息，然后在服务端去处理应用于配置文件之间的关联？

在服务端与客服端的大体的交互我们都可以保持不变，只是之前客服端从应用配置拿去映射关系变为从服务端获取映射关系。

@pbting
