### ISSUE TITLE
字符串判断有误

### ISSUE THREAD

**Issue by ChixianGen** [alibaba/spring-cloud-alibaba#1619]
如下代码：
https://github.com/alibaba/spring-cloud-alibaba/blob/899b7b4fe07603ec8ffa8a5207739c2585e6afa7/spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/RedisDataSourceProperties.java#L96-L99

**Comment by yuhuangbin** [comment]
Thanks for your report. Contributions are welcome~
