### ISSUE TITLE
Nacos 非容器化部署，修改默认端口后，可以成功登陆 Nacos 主页，但是应用程序无法注册上去，拉取的还是 8848 的配置

### ISSUE THREAD

**Issue by Rambo1203** [alibaba/spring-cloud-alibaba#1627]
#### 环境描述  

WIndows 10 + JDK 8 + Nacos-server-1.2.1（Nacos-server-1.3.2） 非容器部署

#### 操作步骤

1. 修改 Nacos 默认端口为 8858  

2. startup.bat 启动 Nacos  

3. 访问 http://127.0.0.1:8858/nacos 成功  

4. 修改应用程序配置文件 ，启动失败（还是去查找 8848 的资源，具体如下图） 

[配置信息](https://img-blog.csdnimg.cn/20200811113625932.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L1JhbWJvX1lhbmc=,size_16,color_FFFFFF,t_70)

[更详细的描述](https://blog.csdn.net/Rambo_Yang/article/details/107920052)

此处 ISSUE 未能解决该问题，或许是我理解错误，请详细指导一下，感谢~！：https://github.com/alibaba/nacos/issues/3361

**Comment by yuhuangbin** [comment]
nacos config 相关的配置项，放在`bootstrap.yaml`中

**Comment by Rambo1203** [comment]
> nacos config 相关的配置项，放在`bootstrap.yaml`中

经过测试，必须放在 bootstrap 文件中才能生效。是否有点不够友好，期待新版本改进，辛苦！
