### ISSUE TITLE
spring-cloud-alibaba dubbo对nacos支持问题

### ISSUE THREAD

**Issue by skyding1212** [alibaba/spring-cloud-alibaba#1629]
目前nacos实现了dubbo注册元数据中心，
dubbo.registry.address 协议 scheme nacos://换成 springcloud://则无法获取元数据，取而代之的是变成配置项。

**Comment by mercyblitz** [comment]
It's unnecessary to change the protocol that was configured by the property `dubbo.registry.address `, Dubbo Spring Boot will be adaptive on the Spring Cloud Registry automatically.
