### ISSUE TITLE
Consumer rebalance problem when using docker container

### ISSUE THREAD

**Issue by casparcao** [alibaba/spring-cloud-alibaba#1633]
**Which Component**
RocketMQ

**Describe the bug**
There are duplicated clientId in different consumer instance in k8s docker container. which result in messages consumed repeatedly in all instance.
I found the components of the clientid is appkey+appsecret+topic+pid，and cannot extend of customize.

**Additional context**
spring-cloud-stream-binder-rocketmq 2.2.0
Aliyun RocketMQ

**Comment by zkzlx** [comment]
you can use the beta version #2029
