### ISSUE TITLE
怎么配置zookeeper集群?

### ISSUE THREAD

**Issue by wuzhihao7** [alibaba/spring-cloud-alibaba#1634]
我用start.aliyun.com生成的spring-cloud-alibaba-dubbo项目，配置中心默认配置如下：
# 挂载到 Spring Cloud 注册中心
dubbo.registry.address=spring-cloud://localhost
有两个问题请教：
1、生产环境的zk集群在这里要怎么配置，dubbo-admin能看到注册的服务吗？
2、挂载到 Spring Cloud 注册中心是什么意思，和原来的只用dubbo的注册中心有什么区别？

**Comment by yuhuangbin** [comment]
使用请参照[相关文档](https://github.com/alibaba/spring-cloud-alibaba/wiki/Dubbo-Spring-Cloud) ，issue用于反馈问题

**Comment by wuzhihao7** [comment]
> 使用请参照[相关文档](https://github.com/alibaba/spring-cloud-alibaba/wiki/Dubbo-Spring-Cloud) ，issue用于反馈问题



> 使用请参照[相关文档](https://github.com/alibaba/spring-cloud-alibaba/wiki/Dubbo-Spring-Cloud) ，issue用于反馈问题

就是官方没看到才能问的呀，求帮忙解答

**Comment by wuzhihao7** [comment]
> 使用请参照[相关文档](https://github.com/alibaba/spring-cloud-alibaba/wiki/Dubbo-Spring-Cloud) ，issue用于反馈问题

就是官方没找到相关说明才来问的呀，求帮忙解答
