### ISSUE TITLE
rocketmq 2.2.0    

### ISSUE THREAD

**Issue by lvITStudy** [alibaba/spring-cloud-alibaba#1636]
**Which Component**
 spring-cloud-stream-binder-rocketmq      2.2.0.RELEASE

**Describe what problem you have encountered**
The application is deployed in a docker environment with the same instance name, causing multiple instances of a service to repeatedly consume messages

**Describe what information you have read**
I see com.alibaba.cloud.stream.binder.rocketmq.consuming.RocketMQListenerBindingContainer
	consumer.setInstanceName(RocketMQUtil.getInstanceName(rpcHook,
					topic + "|" + UtilAll.getPid()));

Our application is deployed in the docker environment, the pid is the same

**Comment by liuhailin** [comment]
so，when can this problem be solved? We are waiting for the release of 2.2.2 @lvITStudy

**Comment by zkzlx** [comment]
you can use the beta version #2029
