### ISSUE TITLE
求更新spring-cloud-alibaba Maven版本

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/spring-cloud-alibaba#1637]
<dependency>
        <groupId>com.alibaba.cloud</groupId>
         <artifactId>spring-cloud-starter-alibaba-*（所有系列，为什么maven包从4月份就不同步了？）</artifactId>
         <version>${spring-cloud-alibaba.version}</version>
</dependency> 
请问下这个依赖包什么时候会同步唉，4月份现在都8月份了。很多组件都迭代了好几次了。希望官方辛苦一下跟进一下版本。这每次都要去排除，然后引入新的组件依赖看的有点难受

**Comment by yuhuangbin** [comment]
8月份会Spring Cloud Alibaba会发布新版本。
