### ISSUE TITLE
nacos config downgrade to 0.8.0

### ISSUE THREAD

**Issue by zhangbin1010** [alibaba/spring-cloud-alibaba#1640]
`<nacos.config.version>0.8.0</nacos.config.version>`
why nacos config downgrade to 0.8.0 in 2.2.2.RELEASE milestone ?

**Comment by yuhuangbin** [comment]
The jar version of nacos adapted to spring cloud config server has always been 0.8.0.
refer https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-config.
