### ISSUE TITLE
Nacos enables authentication, but sentinel uses Nacos as a dynamic data source. How to configure the user and password

### ISSUE THREAD

**Issue by fightingaman** [alibaba/spring-cloud-alibaba#1648]
ENV：
  nacos：1.2.1
  ali cloud：2.1.2
  sentinel：1.7.1
QUESTION：
  Nacos enables authentication, but sentinel uses Nacos as a dynamic data source. How to configure the user and password。
 
![image](https://user-images.githubusercontent.com/19791332/90617156-ecfcdb80-e240-11ea-8722-94a64086b036.png)

使用的版本如上，现在遇到的问题是nacos开启了认证，但是在sentinel配置了nacos的动态数据源时（如上配置），会出现
nacos changed dataId error, code: 403。但是在NacosDataSourceProperties中也只有accessKey，secretKey的属性类似，我该怎么配置nacos的认证账号密码信息。
datasource:
        ds1:
          nacos:
            server-addr: 
            group-id: DEFAULT_GROUP
            data-id: flow_rule
            data-type: json
            rule-type: flow
        ds2:
          nacos:
            server-addr: 
            group-id: DEFAULT_GROUP
            data-id: degrade_rule
            data-type: json
            rule-type: degrade

**Comment by yuhuangbin** [comment]
refer #1585

**Comment by fightingaman** [comment]
i can not find it  in   2.2.1.RELEASE。
![image](https://user-images.githubusercontent.com/19791332/90748991-74ac1e00-e305-11ea-843c-90a69be8e9be.png)
But I found the configuration in the source code version 2.2.2-snapshot

**Comment by yuhuangbin** [comment]
Confirm which version of `spring-cloud-sentinel-datasource` jar the file you opened is located in? I found it in `spring-cloud-aibaba-sentinel-datasource-2.2.1.RELEASE`.
![image](https://user-images.githubusercontent.com/26948026/90770770-db8cff80-e324-11ea-9eef-d9ec7276c996.png)
