### ISSUE TITLE
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([pig-register:8848]) tried: java.net.UnknownHostException: pig-register

### ISSUE THREAD

**Issue by guoxuxiong** [alibaba/spring-cloud-alibaba#1655]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by yuhuangbin** [comment]
确保`pig-register:8848` 网络能通吗？

**Comment by lltx** [comment]
看起来就是没有配置 hosts 的问题   配置一个  ip pig-register 的映射
