### ISSUE TITLE
spring cloud nacos  -- config data not exist

### ISSUE THREAD

**Issue by oliverliye** [alibaba/spring-cloud-alibaba#1659]
nacos-server-1.3.2
spring-cloud-starter-alibaba-nacos-config:2.1.0RELEASE

![image](https://user-images.githubusercontent.com/1321939/90997301-c7325680-e5f3-11ea-9305-493c0f287156.png)
![image](https://user-images.githubusercontent.com/1321939/90997322-d5807280-e5f3-11ea-9ea8-32d3e0512a14.png)
![image](https://user-images.githubusercontent.com/1321939/90997341-e16c3480-e5f3-11ea-886e-ded066132e76.png)

**Comment by yuhuangbin** [comment]
Provide detailed information to the nacos community. Use spring cloud alibaba please refer to [wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config) and [example](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example)
