### ISSUE TITLE
[How get SendResult.messageId?]send消息如何获取SendResult里的messageId?

### ISSUE THREAD

**Issue by LH-gulongfei** [alibaba/spring-cloud-alibaba#1663]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

package org.springframework.messaging;

default boolean send(Message<?> message) {
        return this.send(message, -1L);
    }

MessageChannel.send() only return boolean?

How get SendResult.messageId?

spring cloud rocketMq的messaging下的send方法只返回boolean类型么? 有办法返回SendResult获取到发送消息的messageId么?

**Comment by yuhuangbin** [comment]
MessageChannel 设计如此

**Comment by LH-gulongfei** [comment]
> MessageChannel 设计如此

spring cloud 是推荐使用MessageChannel来send么?

**Comment by yuhuangbin** [comment]
`MessageChannel` 是SpringCloud 提供的统一封装。
