### ISSUE TITLE
一个spring boot应用多注册中心依赖情况下的spring.autoconfigure.exclude配置问题 

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/spring-cloud-alibaba#1664]
场景： 一个应用引入了nacos和zookeeper的注册中心依赖；这个时候如果应用只用zookeeper作为注册中心。那么spring.autoconfigure.exclude配置排除掉nacos自动装配类的时候，源码spring.factories中的所有自动装配的类都要排除吗还是说只需要排除某个特定的类就行。
![image](https://user-images.githubusercontent.com/33769220/91114928-a03f5780-e6bb-11ea-8135-97cd6554e78f.png)

**Comment by yuhuangbin** [comment]
try `spring.cloud.nacos.discovery.enabled=false` ?

**Comment by HelloHaiNG** [comment]
> try `spring.cloud.nacos.discovery.enabled=false` ?
这种方式可以，但是如果要做到动态切换的话就不太灵活了，spring boot有个自动装配的过滤器接口，可以动态的排除符合条件的自动装配类，这种方式可能更加符合实际的情况

**Comment by yuhuangbin** [comment]
动态切换注册中心组件？ 这种需求应该不是大众需求吧

**Comment by HelloHaiNG** [comment]
> 动态切换注册中心组件？ 这种需求应该不是大众需求吧
确实，一般的业务方向的项目可能只会在更换注册中心的时候有这个需求；
但是如果作为一个技术平台来说的话，这种需求就不得不考虑了，每个用户选择的注册中心完全有可能是不一样的

**Comment by yuhuangbin** [comment]
> > 动态切换注册中心组件？ 这种需求应该不是大众需求吧
> > 确实，一般的业务方向的项目可能只会在更换注册中心的时候有这个需求；
> > 但是如果作为一个技术平台来说的话，这种需求就不得不考虑了，每个用户选择的注册中心完全有可能是不一样的

Spring Cloud Alibaba 提供了Nacos 注册中心的实现，多注册中心组件的切换并不是社区的关注点。
