### ISSUE TITLE
config is invalid.

### ISSUE THREAD

**Issue by QQ794763733** [alibaba/spring-cloud-alibaba#1675]
I create a config in nacos on remote server.
But config is invalid in local bootstrap.yml
See following imags:

![QQ截图20200828153913](https://user-images.githubusercontent.com/30444727/91534999-0db1e900-e945-11ea-931d-70ffe3f4162d.png)
![1](https://user-images.githubusercontent.com/30444727/91535022-1aced800-e945-11ea-898a-9fc3489f22b2.png)
![QQ截图20200828153933](https://user-images.githubusercontent.com/30444727/91535027-1e625f00-e945-11ea-8436-c12412e335b1.png)
![QQ截图20200828153950](https://user-images.githubusercontent.com/30444727/91535031-202c2280-e945-11ea-983d-b8395370dfbb.png)

**Comment by yuhuangbin** [comment]
Which version? Please provide more information.

**Comment by yuhuangbin** [comment]
If the `namespace` is `public` , you can remove the `spring.cloud.nacos.config.namespace=Public`.

**Comment by QQ794763733** [comment]
Verison is 2.2.1.RELEASE,I add dependency of discovery, It's work right now, Looks it can't standalone use.

**Comment by yuhuangbin** [comment]
`Nacos-Config` and `Nacos-Discovery` can be used independently, you can refer to [Nacos-Config-Example](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example). Of course, you can also provide a simple project to reproduce your problem, and I will assist you in troubleshooting.

**Comment by QQ794763733** [comment]
Thank for your answer, But it's enough for me.
