### ISSUE TITLE
Nacos-client中的application.properties有问题

### ISSUE THREAD

**Issue by bigbenfather** [alibaba/spring-cloud-alibaba#1678]
我只看了nacos-client.jar的1.1.4和1.3.2，其中有个application.properties，其主要内容为：
`version=${project.version}`
我的springboot项目中没有自定义application.properties，导致读取了nacos的application.properties文件，抛出如下异常
IllegalArgumentException: Could not resolve placeholder 'project.version' in value "${project.version}"

当我创建一个空的application.properties文件时，问题解决。

**Comment by yuhuangbin** [comment]
请按照issue模板来提交问题
