### ISSUE TITLE
sentinel1.8.0引用spring-cloud-starter-alibaba-sentinel报错

### ISSUE THREAD

**Issue by matevip** [alibaba/spring-cloud-alibaba#1680]
**Which Component**
Sentinel1.8.0

**Describe the bug**
程序异常：org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.alibaba.csp.sentinel.transport.config.TransportConfig.getConsoleServer()Ljava/lang/String;

**To Reproduce**
1. 查看'SentinelHealthIndicator'代码第47行
2. 查看sentinel1.8.0版本的TransportConfig的66行
3. Method由getConsoleServe()->getConsoleServerList()
4. 导致报上述BUG

**Expected behavior**
期待下一个版本迭代，修复此bug

**Screenshots**

<img width="944" alt="WechatIMG2" src="https://user-images.githubusercontent.com/57164338/91852723-d0768f80-ec93-11ea-8eed-e797f045c6ad.png">
<img width="1252" alt="WechatIMG3" src="https://user-images.githubusercontent.com/57164338/91852731-d40a1680-ec93-11ea-8dbb-99e9669d2aa0.png">
<img width="830" alt="WechatIMG4" src="https://user-images.githubusercontent.com/57164338/91852749-d79d9d80-ec93-11ea-85f0-ae4f4a1e5272.png">

**Comment by yuhuangbin** [comment]
sentinel 1.8.0 在即将发布的版本中会适配，目前已发布的版本中还没有集成sentinel 1.8.0

**Comment by matevip** [comment]
谢谢回复，2.2.1.Release已经好久没有更新，期待新版本
