### ISSUE TITLE
@Bean 方法签名是否需要统一命名规范

### ISSUE THREAD

**Issue by PeineLiang** [alibaba/spring-cloud-alibaba#1681]
**Which Component**

**Describe what problem you have encountered**

spring-cloud-alibaba中一些@Bean方法的方法签名中有些是方法名与要导入的类名一致，有些是方法名与类名不一致的(风格不同的地方较多)，这个是否需要统一一下，举例如下:

In the method signature of @Bean method in spring-cloud-alibaba, some of the method names are consistent with the class names, and some are inconsistent with the class names.  Here are some examples:

`	@Bean
	public RocketMQTopicProvisioner provisioningProvider() {
		return new RocketMQTopicProvisioner();
	}

	@Bean
	public RocketMQMessageChannelBinder rocketMessageChannelBinder(
			RocketMQTopicProvisioner provisioningProvider,
			InstrumentationManager instrumentationManager) {
		RocketMQMessageChannelBinder binder = new RocketMQMessageChannelBinder(
				provisioningProvider, extendedBindingProperties,
				rocketBinderConfigurationProperties, rocketMQProperties,
				instrumentationManager);
		binder.setExtendedBindingProperties(extendedBindingProperties);
		return binder;
	}
`
**Describe what information you have read**

**Comment by yuhuangbin** [comment]
Refer [RocketMQBinderAutoConfiguration](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/config/RocketMQBinderAutoConfiguration.java). Welcome to controbute~

**Comment by AprogrammingEnthusiast** [comment]
这里的命名风格需要统一吗？是用什么风格为准呢？

**Comment by zkzlx** [comment]
The new version is being refactored, and the issue will be resolved uniformly. Please join us
