### ISSUE TITLE
converter can not convert rules because source is empty

### ISSUE THREAD

**Issue by ankeway** [alibaba/spring-cloud-alibaba#1705]
console continuous printing WARN log "converter can not convert rules because source is empty"
if no configuration rules

com.alibaba.cloud.sentinel.datasource.converter.SentinelConverter.convert(String)
if (StringUtils.isEmpty(source)) {
log.warn("converter can not convert rules because source is empty");
return ruleCollection;
}

com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(S)
public T loadConfig(S conf) throws Exception {
T value = parser.convert(conf);
return value;
}

com.alibaba.cloud.sentinel.endpoint.SentinelHealthIndicator.doHealthCheck(Builder)
try {
dataSource.loadConfig();
........
}

https://github.com/alibaba/Sentinel/issues/1716

**Comment by yuhuangbin** [comment]
no rules cnofigurated, remove the dependecy?
