### ISSUE TITLE
The configuration format is yaml. A date string is included in the configuration. When you obtain the configuration, the date string is converted to a date object.

### ISSUE THREAD

**Issue by lidaoyang** [alibaba/spring-cloud-alibaba#1709]
**Which Component**
jdk :1.8
spring-cloud-starter-alibaba-nacos-config :2.2.1

**Describe the bug**
The configuration format is yaml. A date string is included in the configuration. When you obtain the configuration, the date string is converted to a date object.
配置格式是yaml 配置内容中有日期字符串在获取配置时会把日期字符串转换成日期对象
转换之前是日期字符串
![image](https://user-images.githubusercontent.com/26211950/92891215-58a22500-f44a-11ea-9062-173ac365a00a.png)

转换之后变成了Date对象
![image](https://user-images.githubusercontent.com/26211950/92891542-999a3980-f44a-11ea-92f7-aa14b5a415e6.png)

**Comment by yuhuangbin** [comment]
user.version='2020-09-10'

**Comment by lidaoyang** [comment]
> user.version='2020-09-10'

ok
