### ISSUE TITLE
dubbo cannot find the correct port

### ISSUE THREAD

**Issue by cqyisbug** [alibaba/spring-cloud-alibaba#1718]
**Which Component**
Dubbo ，Nacos

**Describe the bug**

Server A and B. Client C.
The dubbo port of A is 30000 and the dubbo port of B is 30010. After restarting A and B, the port of A is 30010 and the port of B is 30000. At this time, an error will be reported when calling the client C interface, and when C calls the service provided by A , Will also find the port 30000

**To Reproduce**
1. The dubbo port of A is 30000 and the dubbo port of B is 30010
2. restarting A and B,the port of A is 30010 and the port of B is 30000
3. call the client C interface

**Additional context**
CentOs 8  
OpenJDK 1.8
Sring cloud alibaba Version 2.2.2.RELEASE
spring cloud version Hoxton.SR8
spring boot version 2.3.3-RELEASE

**Comment by dlmu-lq** [comment]
Hello, I'm facing the same problem, so how did you fix it?

**Comment by dlmu-lq** [comment]
大佬求教
