### ISSUE TITLE
DubboCloudRegistry and NacosServiceRegistry registration conflict

### ISSUE THREAD

**Issue by cqyisbug** [alibaba/spring-cloud-alibaba#1719]
**Which Component**
Nacos Registry, Dubbo

**Describe the bug**
 the registration address of dubbo is defined as `spring-cloud://` format. At this time, if the `ApplicationEventMulticaster` bean is defined, the registration of spring cloud will be completed before the registration of dubbo. , Causing the dubbo server to fail to register.

**Additional context**
centos 8
open jdk 1.8
spring boot version 2.3.3-RELEASE
spring cloud version Hoxton.SR8
spring cloud alibaba version 2.2.1-RELEASE

**Comment by yuhuangbin** [comment]
不需要配置 spring-cloud://

**Comment by cqyisbug** [comment]
```
dubbo:
  registry:
    address: spring-cloud://${spring.cloud.nacos.discovery.server-addr}
```
spring-cloud 协议下的话就会有注册先后的问题，2.2.2-RELEASE 和 2.2.1-RELEASE 都有这个问题。

```
dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
```
nacos协议下刚刚试了没有问题。

**Comment by cqyisbug** [comment]
> 不需要配置 spring-cloud://

**Comment by cqyisbug** [comment]
我还是上个截图吧
<img width="944" alt="截屏2020-09-14 16 33 12" src="https://user-images.githubusercontent.com/25382172/93063099-576e3380-f6a8-11ea-9567-3778b4d8bb64.png">
<img width="1032" alt="截屏2020-09-14 16 33 25" src="https://user-images.githubusercontent.com/25382172/93063112-5b01ba80-f6a8-11ea-8ed7-577c0c57b904.png">
<img width="1236" alt="截屏2020-09-14 16 33 35" src="https://user-images.githubusercontent.com/25382172/93063116-5dfcab00-f6a8-11ea-98a0-ef596b7c4648.png">

**Comment by cqyisbug** [comment]
@yuhuangbin 

使用的dubbo 配置
`dubbo:
  registry:
    address: spring-cloud://${spring.cloud.nacos.discovery.server-addr}`

冲突的bean
`    @Bean(name = "applicationEventMulticaster")
    public ApplicationEventMulticaster simpleApplicationEventMulticaster() {
        SimpleApplicationEventMulticaster eventMulticaster
                = new SimpleApplicationEventMulticaster();
        eventMulticaster.setTaskExecutor(new SimpleAsyncTaskExecutor());
        return eventMulticaster;
    }
`
