### ISSUE TITLE
NacosContextRefresher类中如果修改了nacos会发送RefeshEvent，建议把dataId和group送出来，方便应用捕获事件做一些配置变更的后续处理。

### ISSUE THREAD

**Issue by rainsoft** [alibaba/spring-cloud-alibaba#1730]
NacosContextRefresher类中如果修改了nacos会发送RefeshEvent，建议把dataId和group送出来，方便应用捕获事件做一些配置变更的后续处理。

private void registerNacosListener(final String groupKey, final String dataKey) {
		String key = NacosPropertySourceRepository.getMapKey(dataKey, groupKey);
		Listener listener = listenerMap.computeIfAbsent(key,
				lst -> new AbstractSharedListener() {
					@Override
					public void innerReceive(String dataId, String group,
							String configInfo) {
						refreshCountIncrement();
						nacosRefreshHistory.addRefreshRecord(dataId, group, configInfo);
						// todo feature: support single refresh for listening
						applicationContext.publishEvent(
								new RefreshEvent(this, null, "Refresh Nacos config"));
						if (log.isDebugEnabled()) {
							log.debug(String.format(
									"Refresh Nacos config group=%s,dataId=%s,configInfo=%s",
									group, dataId, configInfo));
						}
					}
				});
		try {
			configService.addListener(dataKey, groupKey, listener);
		}
		catch (NacosException e) {
			log.warn(String.format(
					"register fail for nacos listener ,dataId=[%s],group=[%s]", dataKey,
					groupKey), e);
		}
	}

**Comment by yuhuangbin** [comment]
`RefreshEvent` 是spring cloud common定义的事件，建议你可以自己添加nacos config监听,  

`configService.addListener(dataId, group, listener);`

**Comment by rainsoft** [comment]
谢谢回复，我觉得RefreshEvent的第一个参数返回NacosContextRefresher没什么用处，返回configService和dataId、group，用处更大。

**Comment by yuhuangbin** [comment]
第一个参数是事件源，一般事件源是发送方，你的需求只要自己加一个nacos的配置变化监听就行
