### ISSUE TITLE
org.springframework.boot.loader.jar.JarFile memory leak

### ISSUE THREAD

**Issue by racooncry** [alibaba/spring-cloud-alibaba#1734]
**Which Component**
Spring cloud gateway

**Describe the bug**
I use "jmap -histo <pid> | more" ,  too much  “org.springframework.boot.loader.jar.JarFile” instances.
Here is the image.
I suspect it caused a memory leak。

![image](https://user-images.githubusercontent.com/25974372/93339311-0011c400-f85e-11ea-8f0b-55ec7fd04c6e.png)

 `
$ jmap -histo:live <pid> | more 
`
![image](https://user-images.githubusercontent.com/25974372/93339605-5c74e380-f85e-11ea-9a20-2c5f800de62f.png)

pom.xml
`    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Hoxton.SR6</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
`

gateway filter
`
/**
 * @Author 
 * @Date 4/8/2020 下午4:36
 * @Description
 * @Version 1.0
 */
@Component
@Slf4j
public class AuthFilter implements GlobalFilter, Ordered {
    @Autowired
    AuthenticationService authenticationService;
    @Autowired
    private ServerCodecConfigurer codecConfigurer;
    private static final String KEY= "id";

`
`
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        /**
         * save request path and serviceId into gateway context
         */
        ServerHttpRequest request = exchange.getRequest();
        print(request);

        ServerHttpResponse serverHttpResponse = exchange.getResponse();

        Map<String, String> params = parseRequest(exchange);
        Result checkSignatureRes = checkSignature(params, request);
        Integer id= 1;

   
        HttpHeaders headers = request.getHeaders();
        MediaType contentType = headers.getContentType();
        log.info("contentType:{}", contentType);
        long contentLength = headers.getContentLength();
        if (contentLength > 0) {
            if (MediaType.APPLICATION_JSON.equals(contentType) || MediaType.APPLICATION_JSON_UTF8.equals(contentType)) {
                log.info("read json");
                return readBodyAndModify(exchange, chain, bussinessId);
            }
            if (contentType.toString().startsWith(MediaType.MULTIPART_FORM_DATA_VALUE)) {
                log.info("read form");
                return readFormData(exchange, chain, bussinessId);
            }
        }
        return chain.filter(exchange);

    }

`

    /**
     * ReadFormData
     *
     * @param exchange
     * @param chain
     * @return
     */
    private Mono<Void> readFormData(ServerWebExchange exchange, GatewayFilterChain chain, Integer id) {
        log.info("form data");
        ServerHttpRequest httpRequest = exchange.getRequest();
        URI uri = httpRequest.getURI();
        StringBuilder query = new StringBuilder();
        String originalQuery = uri.getRawQuery();
        // originalQuery
        // log.info("originalQuery:{}", originalQuery);
      
        if (org.springframework.util.StringUtils.hasText(originalQuery)) {
            query.append(originalQuery);
            if (originalQuery.charAt(originalQuery.length() - 1) != '&') {
                query.append('&');
            }
        }

        // 添加查询参数
        query.append(key+ "=" + id);

        // 替换查询参数
        URI newUri = UriComponentsBuilder.fromUri(uri)
                .replaceQuery(query.toString())
                .build(true)
                .toUri();
        log.info("newUri:{}", query.toString());
        ServerHttpRequest request = exchange.getRequest().mutate().uri(newUri).build();
        return chain.filter(exchange.mutate().request(request).build());
    }

  
    /**
     * ReadJsonBody and modify
     *
     * @param exchange
     * @param chain
     * @return
     */
    private Mono<Void> readBodyAndModify(ServerWebExchange exchange, GatewayFilterChain chain, Integer id) {
        ServerRequest serverRequest = ServerRequest.create(exchange, codecConfigurer.getReaders());
        Mono modifiedBody = serverRequest.bodyToMono(String.class).flatMap(body -> {
            JSONObject jsonObject;
            // body为string
            if (StringUtils.isEmpty(body)) {
                jsonObject = new JSONObject();
            } else {
                jsonObject = JSONObject.parseObject(body);
            }
            jsonObject.put("key", id);
            return Mono.just(jsonObject.toJSONString());
        });
       // codecConfigurer.getReaders().clear();
        BodyInserter bodyInserter = BodyInserters.fromPublisher(modifiedBody, String.class);

        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.putAll(exchange.getRequest().getHeaders());
        // 先删除 content length
        httpHeaders.remove(HttpHeaders.CONTENT_LENGTH);
        CachedBodyOutputMessage outputMessage = new CachedBodyOutputMessage(exchange, httpHeaders);

        return bodyInserter.insert(outputMessage, new BodyInserterContext()).then(Mono.defer(() -> {

            ServerHttpRequest decorator = this.decorate(exchange, httpHeaders, outputMessage);

            return chain.filter(exchange.mutate().request(decorator).build());
        }));
    }

    @Override
    public int getOrder() {
        return -1;
    }

    ServerHttpRequestDecorator decorate(ServerWebExchange exchange, HttpHeaders headers, CachedBodyOutputMessage outputMessage) {
        return new ServerHttpRequestDecorator(exchange.getRequest()) {
            @Override
            public HttpHeaders getHeaders() {
                long contentLength = headers.getContentLength();
                HttpHeaders httpHeaders = new HttpHeaders();
                httpHeaders.putAll(super.getHeaders());
                if (contentLength > 0L) {
                    // 重新写 content length
                    httpHeaders.setContentLength(contentLength);
                } else {
                    httpHeaders.set(HttpHeaders.TRANSFER_ENCODING, "chunked");
                }
                return httpHeaders;
            }

            @Override
            public Flux<DataBuffer> getBody() {

                return outputMessage.getBody();
            }
        };
    }

}
`

**To Reproduce**
Before, I used Spring Cloud Netflix, but later I switched to Spring Cloud Alibaba. However, when Switching, I found that the gateway memory was rising rapidly, and I found the problems in the above pictures with JMAP.

MAT:
![image](https://user-images.githubusercontent.com/25974372/93410004-bb704200-f8ca-11ea-9e46-037fe8b27bc0.png)

![image](https://user-images.githubusercontent.com/25974372/93409954-a1cefa80-f8ca-11ea-9c2c-ae899011b65e.png)

**Comment by mercyblitz** [comment]
Please feedback to Spring Cloud
