### ISSUE TITLE
[Announce] Spring Cloud Alibaba 2.2.4.RELEASE released

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/spring-cloud-alibaba#1748]
Hello Community,

I am glad to announce that Spring Cloud Alibaba 2.2.4.RELEASE is released.

You can check detailed release notes here:

2.2.4.RELEASE (Hoxton SR8) : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.4.RELEASE

If you have any questions using this version, please report the issue on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by xxxing007** [comment]
![image](https://user-images.githubusercontent.com/49646113/93553449-94d30980-f9a5-11ea-9f69-42d7f70c49be.png)
文档有误

**Comment by mercyblitz** [comment]
> ![image](https://user-images.githubusercontent.com/49646113/93553449-94d30980-f9a5-11ea-9f69-42d7f70c49be.png)
> 文档有误

Could you please pull a request to fix it?

**Comment by Guan-MengYuan** [comment]
请更新示例文档
