### ISSUE TITLE
动态刷新不生效

### ISSUE THREAD

**Issue by 18835572909** [alibaba/spring-cloud-alibaba#1751]
配置：
nacos1.3.1 
<spring.boot.version>2.3.2.RELEASE</spring.boot.version>
<spring.cloud.version>Hoxton.SR8</spring.cloud.version>
<spring.cloud.alibaba.version>2.1.2.RELEASE</spring.cloud.alibaba.version>

spring.cloud.nacos.server-addr=x.x.x.x:8848,x.x.x.x:8849,x.x.x.x:8850
spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.discovery.heart-beat-interval=5000
spring.cloud.nacos.discovery.namespace=07f50f35-fcaa-4bf0-b748-32816f856583
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.encode=UTF-8
spring.cloud.nacos.config.timeout=30000
spring.cloud.nacos.config.namespace=07f50f35-fcaa-4bf0-b748-32816f856583
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.shared-configs=test.properties
spring.cloud.nacos.config.refreshable-dataids=test.properties

启动类：
@RefreshScope
@EnableFeignClients
@EnableDiscoveryClient
@SpringBootApplication

Controller类：
@RefreshScope
@RestController
@RequestMapping("/t")
public class TemplateController {
    @Value(value="${ping}")
    private String ping;

问题描述：启动后，后台日志，有时可以刷新，有时不刷新。经过多次重启测试，检测大约3分钟左右，重启生效，再次重启后，动态刷新不生效，再等3分钟，再次重启，再次生效，期间重启不生效（没有找到相关配置这个设置间隔）。spring.cloud.alibaba.version使用2.2.2和2.1.2都有尝试，nacos-server也用1.3.2和1.3.1尝试，都有同样的问题。

**Comment by zhouxufu** [comment]
@RefreshScope注解加需要动态刷新的类上，并不是启动类

**Comment by 18835572909** [comment]
> @RefreshScope注解加需要动态刷新的类上，并不是启动类

都有加的
@RefreshScope
@RestController
@RequestMapping("/t")
public class TemplateController {

**Comment by zhouxufu** [comment]
你服务的spring.application.name是test?

**Comment by 18835572909** [comment]
> 你服务的spring.application.name是test?

不是的，spring.application.name=dy-nacos-template

**Comment by 18835572909** [comment]
经你这么提醒，我把spring.cloud.nacos.config.shared-configs改成spring.cloud.nacos.config.shared-dataids，可以了，不过这两个shared-dataids、refreshable-dataids、都已经标识是@Deprecated

**Comment by littlechaser** [comment]
试试
https://gitee.com/the-best-riven/spring-value-auto-refresh-spring-cloud-starter

**Comment by dang90324** [comment]
spring-cloud-alibaba.version版本：2021.1，nacos服务端版本：2.0.1或1.2.1，这样写是可以的。优先级、动态刷新都没问题
        shared-configs[0]:
          data-id: nacos-config-client-dev.yml # 配置文件名-Data Id
          refresh: true   # 是否动态刷新，默认为false
          group: SH
        extension-configs[0]:
          data-id: nacos-config-client-test.yml # 配置文件名-Data Id
          refresh: true   # 是否动态刷新，默认为false
