### ISSUE TITLE
v.2.1.3.RELEASE的版本依赖写的有问题吧

### ISSUE THREAD

**Issue by hanzhen1989** [alibaba/spring-cloud-alibaba#1756]
![image](https://user-images.githubusercontent.com/11624934/93730369-e1635280-fbfa-11ea-9d83-2547cbaf7dad.png)

![image](https://user-images.githubusercontent.com/11624934/93730317-b2e57780-fbfa-11ea-99a0-49c9ecb6c5c1.png)

**Comment by hanzhen1989** [comment]
另外，如何才能出现在贡献者列表中呢？
V.2.1.3.RELEASE版本中的这个优化，是我提的issue，但是没有出现在贡献者列表中
![image](https://user-images.githubusercontent.com/11624934/93866514-55d0eb00-fcfa-11ea-8554-05f5317112be.png)
![image](https://user-images.githubusercontent.com/11624934/93866546-64b79d80-fcfa-11ea-9277-9b279f3a6fe9.png)

**Comment by yuhuangbin** [comment]
> 另外，如何才能出现在贡献者列表中呢？
> V.2.1.3.RELEASE版本中的这个优化，是我提的issue，但是没有出现在贡献者列表中
> ![image](https://user-images.githubusercontent.com/11624934/93866514-55d0eb00-fcfa-11ea-8554-05f5317112be.png)
> ![image](https://user-images.githubusercontent.com/11624934/93866546-64b79d80-fcfa-11ea-9277-9b279f3a6fe9.png)

提交pr，并且pr被审核通过合并，就可以~
label 为 `enhancement`  的issue都是可以参与解决的。

**Comment by hanzhen1989** [comment]
哦，好的，明白了，谢谢。
