### ISSUE TITLE
Dubbo: How to use  spring-cloud-dubbo-servlet-gateway-sample; 如何使用 dubbo-servlet-gateway

### ISSUE THREAD

**Issue by powerttt** [alibaba/spring-cloud-alibaba#1763]
Spring Cloud Alibaba Version 2.2.2.RELEASE
Spring Boot Version 2.3.2.RELEASE
Dubbo Version 2.7.8
Spring Cloud Starter Dubbo Version 2.2.3.RELEASE

**Which Component**
Dubbo
****
Run the spring-cloud-dubbo-servlet-gateway-sample in the spring-cloud-alibaba-examples>nacos-example module, but I don’t know how to call and access the service, please ask
将spring-cloud-alibaba-examples>nacos-example 模块中的 spring-cloud-dubbo-servlet-gateway-sample  跑起来，但不知道如何调用访问到服务，请教
**Describe what information you have read**
Sorry, I did not find the relevant document

**Comment by yuhuangbin** [comment]
尚未发布，敬请期待~
