### ISSUE TITLE
can't run with attribute "management.endpoints.web.exposure.include "  with value "*"

### ISSUE THREAD

**Issue by jbzong** [alibaba/spring-cloud-alibaba#1765]
can't run with attribute "management.endpoints.web.exposure.include "  with value "*"。
we should use management.endpoints.web.exposure.include=["*"] or ["health"]。 because setInclude method accept only set sets.

   public void setInclude(Set<String> include) {
            this.include = include;
        }

**Comment by yuhuangbin** [comment]
`management.endpoints.web.exposure.include=*`

**Comment by jbzong** [comment]
在版本为2.1.2.REALEASE中：`management.endpoints.web.exposure.include=["*"]`，不能直接 = *，启动会报：`Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning an alias
 in 'reader', line 15, column 18:
            include: *
                     ^
expected alphabetic or numeric character, but found 
`。
