### ISSUE TITLE
打卡

### ISSUE THREAD

**Issue by HunDeMingMingBaiBai** [alibaba/spring-cloud-alibaba#1766]
* 组织：个人
* 地点：中国北京
* 联系方式：18404983786@163.com
* 组件：Nacos、Sentinel
* 场景：服务发现、配置管理、限流降级

**Comment by ivanjin2017** [comment]
组织：个人
地点：中国杭州
联系方式：49145323
组件：Nacos，Sentinel
场景：服务发现，学习

**Comment by yuhuangbin** [comment]
Hi~ please migrate user registration information to #301
