### ISSUE TITLE
The bean 'nacosDiscoveryClient', defined in class path resource [com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientAutoConfiguration.class] and overriding is disabled.

### ISSUE THREAD

**Issue by wangjia2016** [alibaba/spring-cloud-alibaba#1768]
Describe the bug
The bean 'nacosDiscoveryClient', defined in class path resource [com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientAutoConfiguration.class] and overriding is disabled.
Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Expected behavior
normal

Acutally behavior

How to Reproduce
SpringBootWebApplication：
SpringBoot version 2.3.3.RELEASE
spring-cloud-dependencies Hoxton.SR8
spring-cloud-alibaba-dependencies 2.2.3.RELEASE

Desktop (please complete the following information):

OS: windows idea
Version NACOS1.1.4

**Comment by yuhuangbin** [comment]
As the description says, did you define a bean named nacosDiscoveryClient?

**Comment by yinzhuo1998** [comment]
cause：startup class'Application.java' under the 'com' package
