### ISSUE TITLE
使用spring-cloud-starter-alibaba-nacos-discovery之后，即使启动之后什么都不做，JVM内存一直增加

### ISSUE THREAD

**Issue by 290713469** [alibaba/spring-cloud-alibaba#1773]
项目中使用Nacos作为注册中心，在添加了spring-cloud-starter-alibaba-nacos-discovery之后，即使启动之后什么都不做，JVM内存一直增加

**Comment by yuhuangbin** [comment]
你可以查看内存占用情况，确定是否为`nacos discovery`相关的占用比较高？
