### ISSUE TITLE
spring-cloud-alibaba-nacos-discovery服务调用之间的集群隔离性问题

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/spring-cloud-alibaba#1778]
看源码，nacos sdk已经默认支持了ribbon，根据权重来进行负载均衡
场景：
服务A和服务B注册到nacos上，服务B有多个集群，
那么服务A如果想要调用服务B中的集群1中的实例，nacos是怎么保证服务A不会去调用到服务B其他集群中的实例

**Comment by yuhuangbin** [comment]
Spring Cloud Alibaba暂时还没支持Nacos多集群服务发现。

**Comment by HelloHaiNG** [comment]
> Spring Cloud Alibaba暂时还没支持Nacos多集群服务发现。

请问有这个需求的排期吗？
还是就是nacos虽然支持了ribbon，看代码是根据实例的权重大小来分配流量的，但是我测试了一下，服务A调用服务B的两个实例好像是轮询去调用的（两个实例的权重设置的不一样），是我使用方式上有地方漏了什么细节吗？

**Comment by yuhuangbin** [comment]
> > Spring Cloud Alibaba暂时还没支持Nacos多集群服务发现。
> 
> 请问有这个需求的排期吗？
> 还是就是nacos虽然支持了ribbon，看代码是根据实例的权重大小来分配流量的，但是我测试了一下，服务A调用服务B的两个实例好像是轮询去调用的（两个实例的权重设置的不一样），是我使用方式上有地方漏了什么细节吗？

可通过配置`ribbon.NFLoadBalancerRuleClassName=com.alibaba.cloud.nacos.ribbon.NacosRule` 实现权重

**Comment by xiaonaoshu** [comment]
同时请求多次，第一个服务阻塞，第二个服务非阻塞的时候，为什么整个服务处于阻塞状态，有没有可以修改和设置的地方啊。
