### ISSUE TITLE
Can't run "./mvnw install" properly.

### ISSUE THREAD

**Issue by Bruce-Stark** [alibaba/spring-cloud-alibaba#1779]
When run "./mvnw install", it will automaticly download "Apache Maven 3.5.2", and it will report error as follow:
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.alibaba.cloud:spring-cloud-alibaba-dependencies:pom:2.2.3-SNAPSHOT @ com.alibaba.cloud:spring-cloud-alibaba:${revision}, E:\Cloud\spring-cloud-alibaba\pom.xml, line 135, column 25
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.alibaba.cloud:spring-cloud-alibaba-dependencies:pom:2.2.3-SNAPSHOT @ com.alibaba.cloud:spring-cloud-alibaba:${revision}, E:\Cloud\spring-cloud-alibaba\pom.xml, line 135, column 25

**Comment by yuhuangbin** [comment]
`mvn -Drevision=2.2.3-SNAPSHOT clean install`

**Comment by wanisily** [comment]
mvn -Drevision=2.2.1.RELEASE -DskipTests=true -Dcheckstyle.skip=true clean install  **过滤掉TEST**

**Comment by wanisily** [comment]
不过滤TEST，简直要等半小时的节奏
