### ISSUE TITLE
What is the highest supported version now?

### ISSUE THREAD

**Issue by 65725738** [alibaba/spring-cloud-alibaba#1790]
spring boot 2.2.X   2.3.X is corresponding spring cloud Hoxton.SR8 。

springcloud alibaba
 master branch: Corresponds to Spring Cloud Greenwich & Spring Boot 2.x. JDK 1.8 or later versions are supported.

Is Hoxton.sr8 not supported？

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
