### ISSUE TITLE
springcloud alibaba+nacos集成websocket启动报错

### ISSUE THREAD

**Issue by zhangran2616** [alibaba/spring-cloud-alibaba#1796]
![image](https://user-images.githubusercontent.com/6472032/97656333-3324b580-1aa2-11eb-9c9f-d3a7a05e6ce4.png)

**Comment by ID-Ethan** [comment]
I also encountered this problem.

**Comment by yuhuangbin** [comment]
提供你项目的 `pom` 文件，是否依赖了多个版本 `spring-cloud-starter-alibaba-nacos-discovery` ?

**Comment by zhangran2616** [comment]
> 提供你项目的 `pom` 文件，是否依赖了多个版本 `spring-cloud-starter-alibaba-nacos-discovery` ?

![image](https://user-images.githubusercontent.com/6472032/98211921-c451cb80-1f7d-11eb-898a-a7a52bdbed3c.png)


我排查过依赖 没有发现其他版本的spring-cloud-starter-alibaba-nacos-discovery 依赖。

**Comment by zhangran2616** [comment]
> I also encountered this problem.

问题最后解决了吗？

**Comment by ID-Ethan** [comment]
> > I also encountered this problem.
> 
> 问题最后解决了吗？

![image](https://user-images.githubusercontent.com/39491128/98212649-de3fde00-1f7e-11eb-94b2-c50933f0b4af.png)


> > I also encountered this problem.
> 
> 问题最后解决了吗？

暂时解决了，但是还是有一些瑕疵。覆盖了框架中NacosWatch实例的创建过程，因为考虑到日常开发，在测试环境和生产环境如果需要使用NacosWatch需要显示配置：spring.cloud.nacos.discovery.watch.enabled=true
<img width="1092" alt="WechatIMG58" src="https://user-images.githubusercontent.com/39491128/98212890-3971d080-1f7f-11eb-80a3-4c7dfabcacbc.png">

**Comment by zhangran2616** [comment]
> > > I also encountered this problem.
> > 
> > 
> > 问题最后解决了吗？
> 
> 暂时解决了，但是还是有一些瑕疵。覆盖了框架中NacosWatch实例的创建过程，因为考虑到日常开发，在测试环境和生产环境如果需要使用NacosWatch需要显示配置：spring.cloud.nacos.discovery.watch.enabled=true
> <img alt="WechatIMG58" width="1092" src="https://user-images.githubusercontent.com/39491128/98212890-3971d080-1f7f-11eb-80a3-4c7dfabcacbc.png">

好的，试试！

**Comment by luckywur** [comment]
同样的问题
spring-cloud-starter-alibaba-nacos-discovery: 2.1.3.RELEASE
spring cloud: Greenwich.SR6
spring-boot-starter-websocket: 2.1.13.RELEASE
没有重复引用包

**Comment by xiao-ma-nong** [comment]
解决了吗

**Comment by dsadsaad** [comment]
> > > I also encountered this problem.
> > 
> > 
> > 问题最后解决了吗？
> 
> 暂时解决了，但是还是有一些瑕疵。覆盖了框架中NacosWatch实例的创建过程，因为考虑到日常开发，在测试环境和生产环境如果需要使用NacosWatch需要显示配置：spring.cloud.nacos.discovery.watch.enabled=true
> <img alt="WechatIMG58" width="1092" src="https://user-images.githubusercontent.com/39491128/98212890-3971d080-1f7f-11eb-80a3-4c7dfabcacbc.png">

感谢,完美解决
