### ISSUE TITLE
如何在代码里面写自定义starter扩展替代bootstrap里面写extension-configs

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/spring-cloud-alibaba#1798]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel
Nacos Config

**Describe what problem you have encountered**
A clear and concise description of what you want to do.
希望在自定义starter里面可以自由扩展NacosConfig的extension-configs
但是NacosPropertySourceRepository中NacosPropertySource没有public构造方法
NacosPropertySourceBuilder的build也不是public访问

**Describe what information you have read**
eg. I have read the reference doc of Sentinel
I have read the reference doc of Nacos

**Comment by hsoftxl** [comment]
NacosPropertySourceBuilder 看看这个类

**Comment by MagakiReimu** [comment]
Declare a CustomConfiguration
autowired NacosConfigProperties
use PostContruct
NacosConfigProperties.getExtensionConfigs().add(new NacosConfigProperties.Config())

spring.factories  add this
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
CustomConfiguration
