### ISSUE TITLE
Debug spring-cloud-dubbo-consumer-sample Demo happend ClassCastException

### ISSUE THREAD

**Issue by Jimi0018** [alibaba/spring-cloud-alibaba#1802]
When debug the demo for spring-cloud-dubbo-consumer-sample, system happend ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.alibaba.cloud.dubbo.service.SpringRestService.requestBodyMap(SpringRestService.java:92)
    It like appear in 
com.alibaba.cloud.dubbo.service.SpringRestService#requestBodyMap(@RequestBody Map<String, Object> data) 
, when a consumer use restTemplate.postForObject request this method will make param's value happend  ClassCastException.
    Thanks for your reply !

        在调试 spring-cloud-dubbo-consumer-sample项目时，在SpringRestService.requestBodyMap方法上发生类型转换异常，异常大概是由于使用restTemplate.postForObject 请求该方法时Map参数的value对象被全部转换成String类型导致。
       感谢你的答复!!!
![spring-cloud-dubbo-consumer1](https://user-images.githubusercontent.com/17883137/97986008-06f79480-1e14-11eb-9db0-abaf96f65872.png)

**Comment by daimingbao** [comment]
I try is ok,
