### ISSUE TITLE
ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: ErrCode:503, ErrMsg:server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by wangfuxu** [alibaba/spring-cloud-alibaba#1814]
nacos1.4+springboot2.3.2+springcloudalibaba2.2.3
nacos单机启动成功，第二天上班再运行就报错500
springcloud 客户端启动报错ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: ErrCode:503, ErrMsg:server is DOWN now, please try again later!

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/nacos/issues
