### ISSUE TITLE
org.apache.dubbo.remoting.http.tomcat.TomcatHttpServer cant resolve method

### ISSUE THREAD

**Issue by wucfu** [alibaba/spring-cloud-alibaba#1816]
![image](https://user-images.githubusercontent.com/38030542/98906443-ffad4680-24f7-11eb-94db-d64b83421ddf.png)

version:
- spring-cloud-starter-dubbo version is 2.2.1.RELEASE
- dubbo version is 2.7.6
- springboot version is 2.3.2.RELEASE

**Comment by yuhuangbin** [comment]
report https://github.com/apache/dubbo
