### ISSUE TITLE
shared-dataids not effect in proper group

### ISSUE THREAD

**Issue by xiangtianyu** [alibaba/spring-cloud-alibaba#1817]
My nacos server version is 1.4.0
Springcloud : Greenwich

I created a shared config common.yml in group (dev),but when it try to connect the server ,it tried to fetch the group[DEFAULT_GROUP]

![1](https://user-images.githubusercontent.com/10825900/98906415-f7eda200-24f7-11eb-92ae-1baba706690b.PNG)
![2](https://user-images.githubusercontent.com/10825900/98906437-fe7c1980-24f7-11eb-9c68-2f470e81ecb5.PNG)
![3](https://user-images.githubusercontent.com/10825900/98906445-00de7380-24f8-11eb-9188-3ffe0e978f45.PNG)

**Comment by yuhuangbin** [comment]
Which version of Spring Cloud Alibaba？

**Comment by xiangtianyu** [comment]
> Which version of Spring Cloud Alibaba？

2.1.1.RELEASE

**Comment by yuhuangbin** [comment]
> > Which version of Spring Cloud Alibaba？
> 
> 2.1.1.RELEASE

Can you upgrede Spring Cloud Alibaba Version to 2.1.3.RELEASE? then retry it.

**Comment by xiangtianyu** [comment]
> > > Which version of Spring Cloud Alibaba？
> > 
> > 
> > 2.1.1.RELEASE
> 
> Can you upgrede Spring Cloud Alibaba Version to 2.1.3.RELEASE? then retry it.

I tried, and it didn't work

**Comment by yuhuangbin** [comment]
This function is no problem, please provide your code to reproduce.

**Comment by xiangtianyu** [comment]
> This function is no problem, please provide your code to reproduce.

i create a demo https://github.com/xiangtianyu/nacos-demo
and my server version is 1.4.0

**Comment by yuhuangbin** [comment]
> > This function is no problem, please provide your code to reproduce.
> 
> i create a demo https://github.com/xiangtianyu/nacos-demo
> and my server version is 1.4.0

I have explained, upgrade Spring Cloud Alibaba Version to 2.1.3.RELEASE, refer https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E.

And If you have some usage issues to discuss, please go to the relevant community group like DingTalk, thank you.
