### ISSUE TITLE
sentinel的限流统计指标不对，1次点击算成2次

### ISSUE THREAD

**Issue by yx657990706** [alibaba/spring-cloud-alibaba#1819]
**Which Component**
Sentinel

**Describe the bug**
The Gateway gateway USES Sentinel to limit the flow, setting the rules QPS every 2 seconds and reporting custom 429 (too many requests) errors all the time.
If you look at the metrics and find a request, there will be two counts. The statistics work properly after the JAR is switched.

> gateway网关使用sentinel限流，设置规则 ：同一个IP，QPS --2秒1次，一直报自定义的429（太多请求）错误。查看相关指标发现一次请求，会有2次统计，导致限流不正确.将jar包切换后能正常工作。

### before：
```
       <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
           <version>2.3.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.3.3.RELEASE</version>
        </dependency>
```
### after (normal)
```
  <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-transport-simple-http</artifactId>
            <version>1.8.0</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
            <version>1.8.0</version>
        </dependency>

```

**To Reproduce**

**Expected behavior**
click one and no block

**Screenshots**
curl http://localhost:8719/cnode?id=single@comsumer_hello
![image](https://user-images.githubusercontent.com/13072869/99146024-1ba71880-26af-11eb-8ff0-e0482e9b518a.png)

**Additional context**

**Comment by sczyh30** [comment]
看下是否有重复注册 SentinelGatewayFilter

**Comment by yx657990706** [comment]
本地就启动一个实例，也没有添加其他filter。目前是换了包好使（啥也没改，jar替换就正常了）。
