### ISSUE TITLE
spring.cloud.nacos.discovery.server-addr 配置无效

### ISSUE THREAD

**Issue by luke4j** [alibaba/spring-cloud-alibaba#1821]
bootstrap.yaml
dubbo:
  scan:
    base-packages: com.luke.eyeglass
  protocols:
    dubbo:
      port: -1

feign:
  hystrix:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata

spring:
  application:
    name: lk-eyeglass-surm
  main:
    allow-bean-definition-overriding: true
  profiles: nacos
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848

package com.alibaba.cloud.nacos;

@ConfigurationProperties("spring.cloud.nacos.discovery")
public class NacosDiscoveryProperties 

  public void overrideFromEnv(Environment env) {
        if (StringUtils.isEmpty(this.getServerAddr())) {
            String serverAddr = env.resolvePlaceholders("${spring.cloud.nacos.discovery.server-addr:}");
            if (StringUtils.isEmpty(serverAddr)) {
                serverAddr = env.resolvePlaceholders("${spring.cloud.nacos.server-addr:localhost:8848}");
            }

            this.setServerAddr(serverAddr);
        }

这一句取不到配置的属性,
String serverAddr = env.resolvePlaceholders("${spring.cloud.nacos.discovery.server-addr:}");
serverAddr 的值总是 localhost:8848

**Comment by GuoDapeng** [comment]
`bootstrap.yaml` 丢失了格式，不是很清楚你这个配置的层次。另外看上去，`spring.cloud.nacos.discovery.serverAddr` 在 `bootstrap.yaml ` 里，配置的端口就是 8848。没了解你遇到的困难。
