### ISSUE TITLE
spring cloud config client 整合nacos注册中心

### ISSUE THREAD

**Issue by shipengzhen** [alibaba/spring-cloud-alibaba#1824]
spring cloud config client 整合nacos注册中心
![1605861429(1)](https://user-images.githubusercontent.com/33373790/99778537-c8b9df00-2b4e-11eb-9135-ce3d76d0bb0b.png)
Error creating bean with name 'nacosProperties': Unsatisfied dependency expressed through field 'nacosServiceManager';   无法启动

**Comment by shipengzhen** [comment]
> spring cloud config client 整合nacos注册中心
> ![1605861429(1)](https://user-images.githubusercontent.com/33373790/99778537-c8b9df00-2b4e-11eb-9135-ce3d76d0bb0b.png)
> Error creating bean with name 'nacosProperties': Unsatisfied dependency expressed through field 'nacosServiceManager'; 无法启动

**Comment by YzsCmy** [comment]
怎么解决的?
