### ISSUE TITLE
Spring Cloud Stream + RocketMQ 报错 ObjectMapper Not Found

### ISSUE THREAD

**Issue by phpisfuture** [alibaba/spring-cloud-alibaba#1827]
环境版本：
<spring-boot.version>2.3.2.RELEASE</spring-boot.version>
<spring-cloud-alibaba.version>2.2.3.RELEASE</spring-cloud-alibaba.version>

依赖：

> <dependency>
         <groupId>com.alibaba.cloud</groupId>
         <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
</dependency>

报错：
Description:

Parameter 1 of method rocketMQTemplate in com.alibaba.cloud.stream.binder.rocketmq.config.RocketMQComponent4BinderAutoConfiguration required a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'jacksonObjectMapper' in 'JacksonAutoConfiguration.JacksonObjectMapperConfiguration' not loaded because @ConditionalOnClass did not find required class 'org.springframework.http.converter.json.Jackson2ObjectMapperBuilder'

Action:

Consider revisiting the entries above or defining a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' in your configuration.

问题：
ObjectMapper是否忘记了自动装配呢？ObjectMapper为啥要已注入的形式引入呢？

**Comment by zkzlx** [comment]
The new version is being refactored and will be addressed by `MessageConverter`. Welcome to join us

**Comment by hzjc** [comment]
本人环境版本：
<spring-boot.version>2.3.7.RELEASE</spring-boot.version>
<spring-cloud-alibaba.version>2.2.4.RELEASE</spring-cloud-alibaba.version>

依赖：
     <groupId>com.alibaba.cloud</groupId>
     <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
       <version>2.2.4.RELEASE</version>
报以上同样的错误
![image](https://user-images.githubusercontent.com/18162393/105135286-c2ce8300-5b2a-11eb-9773-3d632f5a77d4.png)

**Comment by hzjc** [comment]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method rocketMQTemplate in com.alibaba.cloud.stream.binder.rocketmq.config.RocketMQComponent4BinderAutoConfiguration required a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'jacksonObjectMapper' in 'JacksonAutoConfiguration.JacksonObjectMapperConfiguration' not loaded because @ConditionalOnClass did not find required class 'org.springframework.http.converter.json.Jackson2ObjectMapperBuilder'


Action:

Consider revisiting the entries above or defining a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' in your configuration.

**Comment by candyYu** [comment]
> APPLICATION FAILED TO START
> 
> Description:
> 
> Parameter 1 of method rocketMQTemplate in com.alibaba.cloud.stream.binder.rocketmq.config.RocketMQComponent4BinderAutoConfiguration required a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' that could not be found.
> 
> The following candidates were found but could not be injected:
> - Bean method 'jacksonObjectMapper' in 'JacksonAutoConfiguration.JacksonObjectMapperConfiguration' not loaded because @ConditionalOnClass did not find required class 'org.springframework.http.converter.json.Jackson2ObjectMapperBuilder'
> 
> Action:
> 
> Consider revisiting the entries above or defining a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' in your configuration.

how to solve this problem ?

**Comment by YeautyYE** [comment]
spring-cloud-alibaba.version = 2021.1 
there are same exception
