### ISSUE TITLE
master和2.2.3的tags项目版本号有问题,源码无法构建

### ISSUE THREAD

**Issue by CrazyLionL** [alibaba/spring-cloud-alibaba#1830]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by xuande** [comment]
master版本将2.2.3-SNAPSHOT版本改为2.2.3.RELEASE可以正常编译
```
<properties>
        <!-- Project revision -->
        <revision>2.2.3-SNAPSHOT</revision>
        ....
```
更改为 
```
<properties>
        <!-- Project revision -->
        <revision>2.2.3.RELEASE</revision>
        ....
```
