### ISSUE TITLE
nacos-client与nacos-server版本对应问题

### ISSUE THREAD

**Issue by jsxiao** [alibaba/spring-cloud-alibaba#1832]
**Which Component**
`Nacos Discovery`

**Describe what problem you have encountered**
我们使用的Spring cloud版本是 `Greenwich.SR5`, alibaba-dependencies是`2.1.2.RELEASE`, 其中依赖了 `nacos-client:1.2.1`版本。nacos-server已经升级到1.4.0，但nacos-client直接从`1.2.1`升级到`1.4.0`是否有问题？如果不升级的话那`nacos-client:1.2.1`对应`nacos-server:1.4.0` 是否可以呢？

**Describe what information you have read**

**Comment by yuhuangbin** [comment]
use Spring Cloud Aliababa  2.1.3.RELEASE.
