### ISSUE TITLE
properties配制支持去除空格

### ISSUE THREAD

**Issue by KeRan213539** [alibaba/spring-cloud-alibaba#1837]
[alibaba/nacos#4278 当配置文件有空格时，将无法匹配参数。](https://github.com/alibaba/nacos/issues/4278)

**Comment by alonelaval** [comment]
能指派给我吗？谢谢！

**Comment by KeRan213539** [comment]
> 能指派给我吗？谢谢！

我没这个仓库的权限额.  你直接在这个issue下回复你来弄,然后弄好了提PR的时候关联这个issue应该就可以了

**Comment by KeRan213539** [comment]
> 能指派给我吗？谢谢！
可以参考这个
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81

**Comment by alonelaval** [comment]
好的。

**Comment by KeRan213539** [comment]
> 好的。

我测试的spring的处理是对 key 做了 trim, 但是value没有做trim. spring对value的处理只是去除了前面的空格,后面的空格没有去除.
我建议你也测试下或者参考spring的代码里的处理方式. 按照spring的方式来搞

**Comment by alonelaval** [comment]
可以关闭了。我看到：https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataPropertiesParser.java 已修复该问题。2.2.1版本存在该问题：https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.1.RELEASE/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataPropertiesParser.java。
谢谢！

**Comment by KeRan213539** [comment]
ok
