### ISSUE TITLE
com.alibaba.cloud:spring-cloud-starter-dubbo 很多方法标记为 Deprecated

### ISSUE THREAD

**Issue by GuoDapeng** [alibaba/spring-cloud-alibaba#1839]
**Which Component**
`com.alibaba.cloud:spring-cloud-starter-dubbo`

**Describe what problem you have encountered**
Many methods are marked as Deprecated. eg. com.alibaba.dubbo.config.annotation.Service, org.apache.dubbo.config.annotation.Reference.
很多方法被标记为Deprecated。例如：com.alibaba.dubbo.config.annotation.Service，org.apache.dubbo.config.annotation.Reference。

**Describe what information you have read**
Should I just wait for a while?
我是不是等待一段时就好了？

**Comment by yuhuangbin** [comment]
标记 @Deprecated  标识即将被废弃的
