### ISSUE TITLE
小马哥离职后是不是就没人维护了？

### ISSUE THREAD

**Issue by IcebergXTY** [alibaba/spring-cloud-alibaba#1842]
#1791，提的这个issue一个多月了都没人理一下😓是写的不够清楚吗？

**Comment by zhizhi555555** [comment]
是的

**Comment by KamSss** [comment]
很难不承认

**Comment by yuhuangbin** [comment]
小马哥也会在这个社区的，社区里也有阿里其他负责人在跟的，也欢迎大家一起参与贡献~

**Comment by yuhuangbin** [comment]
> #1791，提的这个issue一个多月了都没人理一下😓是写的不够清楚吗？

问题已经解决了喔，会在下个版本更新，你可以用master分支代码打包测试下~
