### ISSUE TITLE
使用的nacos账号的密码带有"#"，请求登录server接口失败

### ISSUE THREAD

**Issue by liuyunlong1229** [alibaba/spring-cloud-alibaba#1843]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
nacos-client  1.3.3 通过如下dependency引入。
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.3.REALEASE</version>
 </dependency>

**Nacos Server 1.3.2**

**Describe the bug**

**To Reproduce**

1. 配置文件中设置nacos的密码是ecommerce#pateo2020
2.启动服务中，请求nacos server 登录api出现错误码 100

**Expected behavior**
希望请求登录成功
 
**Screenshots**
日志中提示如下内容：
[SecurityProxy] login http request failed url: http://xxxxxx/nacos/v1/auth/users/login, params: {username=nacos}, bodyMap: {password=ecommerce%23pateo2020}, errorMsg: errCode: 100, errMsg: Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed.  

**Additional context**
Java8 ，Windows7

**Comment by yuhuangbin** [comment]
How about this?
```yaml
spring:
  cloud:
    nacos:
      username: nacos
      password: 'ecommerce#pateo2020'
```

**Comment by GithubG-666** [comment]
你咋解决的，加引号吗
