### ISSUE TITLE
nacos-config set group is invalid

### ISSUE THREAD

**Issue by simon-sou** [alibaba/spring-cloud-alibaba#1844]
I have set spring.cloud.nacos.config.group=simon and spring.cloud.nacos.config.file-extension=yaml  on application.properties; it's 
invalid; it tried to fetch the group[DEFAULT_GROUP];

![image](https://user-images.githubusercontent.com/48339364/100715888-d8f57800-33f2-11eb-8741-c0ee11e3e38d.png)

my server config:

server.port=8000
server.servlet.context-path=/
spring.application.name=hello
spring.profiles.active=nacos
spring.cloud.nacos.config.file-extension=yaml
spring.cloud.nacos.config.server-addr=localhost:8848
spring.cloud.nacos.config.group=simon
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
spring.cloud.nacos.discovery.enabled=false

my server version:
ailbabaVersion : 2.1.3.RELEASE
springCloudVersion: Hoxton.SR8
springBootVersion:  2.3.5.RELEASE

i create a demo  https://github.com/simon-sou/spring-cloud-demo/tree/master/spring-hello-app

**Comment by simon-sou** [comment]
I have solve it by rename application.properties to bootstrap.properties . I can't understand; 
discovery group is useful in application.properties

**Comment by yuhuangbin** [comment]
Nacos Config related configuration items must be in bootstrap.
