### ISSUE TITLE
nacos 

### ISSUE THREAD

**Issue by mxz668** [alibaba/spring-cloud-alibaba#1848]
能否提供下 spring-cloud-starter-alibaba-nacos-discovery 和 spring-cloud-starter-alibaba-nacos-config的说明文档

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/spring-cloud-alibaba/wiki

**Comment by mxz668** [comment]
你好：
&nbsp; &nbsp; 有关于&nbsp;spring-cloud-starter-alibaba-nacos-discovery&nbsp;源码的文档吗，比如我项目引入了该jar包，启动项目后服务注册和发现的机制怎么实现的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 上午8:57
收件人:&nbsp;"alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com&gt;;
抄送:&nbsp;"风落"<402416390@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] nacos  (#1848)





 
https://github.com/alibaba/spring-cloud-alibaba/wiki
