### ISSUE TITLE
sentinel使用nacos作为规则的持久化问题

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/spring-cloud-alibaba#1849]
通过sentinel使用nacos作为规则持久化问题中，有个配置项：
spring.cloud.sentinel.datasource.ds.nacos.rule-type
这个配置项只能配置一种规则类型，但是如果想我枚举类里面的规则全部持久化到nacos，这个时候应该怎么配置呢

**Comment by yuhuangbin** [comment]
refer: https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties

**Comment by HelloHaiNG** [comment]
> refer: https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties

好哒，感谢
