### ISSUE TITLE
nacos config save snapshot error

### ISSUE THREAD

**Issue by realhm** [alibaba/spring-cloud-alibaba#1854]
Nacos Config

When config spring.cloud.nacos.config.server-addr as below

spring.cloud.nacos.config.server-addr=\
nacos-cluster-0.nacos-cluster-hs.1249604763418169345.svc.cluster.local.:8848,\
nacos-cluster-1.nacos-cluster-hs.1249604763418169345.svc.cluster.local.:8848,\
nacos-cluster-2.nacos-cluster-hs.1249604763418169345.svc.cluster.local.:8848

then saveing snapshot error occured because of snapshot path is too long(file name too long ，the name_max of linux is 255).

The snapshot path is /home/app/nacos/config/fixed-nacos-cluster-0.nacos-cluster-hs.1249604763418169345.svc.cluster.local._8848-nacos-cluster-1.nacos-cluster-hs.1249604763418169345.svc.cluster.local._8848-nacos-cluster-2.nacos-cluster-hs.1249604763418169345.svc.cluster.local._8848-c5f7f011-3e6d-40fe-8d0a-ce6499435496_nacos/snapshot-tenant/c5f7f011-3e6d-40fe-8d0a-ce6499436696/xxx/xxx.properties.

So how to resolve？ Thank you!

**Comment by yuhuangbin** [comment]
plase submit issue to [Nacos](https://github.com/alibaba/nacos).
