### ISSUE TITLE
集成seata,使用nacos做配置中心、注册中心，启动报403  unkonw

### ISSUE THREAD

**Issue by xueshuailing820** [alibaba/spring-cloud-alibaba#1858]
版本，
naocs clinet v1.3.3
nacos api   v1.3.3
seate   v1.3
操作系统：mac
![WechatIMG71593](https://user-images.githubusercontent.com/75656196/101439931-a3034700-3950-11eb-992c-fc97b88976c2.png)
 <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
        <spring-cloud-alibaba.version>2.1.3.RELEASE</spring-cloud-alibaba.version>
        <druid.version>1.1.10</druid.version>
    </properties>

    
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

使用starter方式引入，seate、naocs;按照官方配置，信息如下：
#nacos
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#seata 注册到nacos配置中心
seata.config.type=nacos
seata.config.nacos.group=SEATA_GROUP
seata.config.nacos.server-addr=127.0.0.1:8848
seata.config.nacos.password=nacos
seata.config.nacos.username=nacos
seata.registry.type=nacos
seata.registry.nacos.application=seata-server
seata.registry.nacos.group=SEATA_GROUP
#seata.registry.nacos.namespace=public
seata.registry.nacos.username=naocs
seata.registry.nacos.password=nacos
seata.registry.nacos.server-addr=127.0.0.1:8848

spring.cloud.nacos.config.group=SEATA_GROUP
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.password=nacos
spring.cloud.nacos.config.name=nacos
spring.cloud.alibaba.seata.tx-service-group=service-product

**Comment by yuhuangbin** [comment]
submit issue to [Seata](https://github.com/seata/seata)
