### ISSUE TITLE
根据线程数限流BUG

### ISSUE THREAD

**Issue by zjwat303** [alibaba/spring-cloud-alibaba#1861]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.1.1.RELEASE</version>
</dependency>

限流规则：
private static void initFlowRules(){
        List<FlowRule> rules = new ArrayList<>();
        FlowRule rule = new FlowRule();
        rule.setResource("HelloWorld");
        rule.setGrade(RuleConstant.FLOW_GRADE_THREAD);
        rule.setCount(2);
        rules.add(rule);
        FlowRuleManager.loadRules(rules);
}
如上配置通过线程数限流，限流线程数为2.
当前10个线程T1-T0，T1和T10同时走到StatisticsSlot的fireEntry方法里面，线程同时触发StatisticsSlot的fireEntry，在FlowSlot中的DefaultController的canPass方法限流逻辑if (curCount + acquireCount > count)会认为当前curCount只有0，无法触发限流。导致10个线程同时进入entry块。

**Comment by yuhuangbin** [comment]
please submit issue to [Sentinel](https://github.com/alibaba/Sentinel).
