### ISSUE TITLE
如何读取nacos config自定义文件？配置的是extension-configs

### ISSUE THREAD

**Issue by wjce** [alibaba/spring-cloud-alibaba#1862]
问题：可以根据spring.profiles.active读取不同配置文件，但是无法读取extension-configs配置下的test.yml中的值
test.yml配置如下
`mytest: sdfkljaslkfjsl`

读取test.yml方式如下
`@Value("${mytest.test}")
    private String test;`

bootstrap.yml配置如下
`spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        refresh-enabled: true
        file-extension: yml
        name: nacos-config
        extension-configs:
          - dataId: test.yml
            refresh: true
        username: nacos
        password: nacos`

**Comment by wjce** [comment]
如何读取test.yml中的值?

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config

**Comment by dkgee** [comment]
应该是可以读的，特别是要注意nacos中创建配置文件时，dataId中最好都带上后缀域，不然会加载不了。例如nacos中创建了配置文件dataId为test.yml，应用中配置
extension-configs:
           - data-id: test.yaml
             group: xxx
             refresh: true

**Comment by q894944272** [comment]
> 应该是可以读的，特别是要注意nacos中创建配置文件时，dataId中最好都带上后缀域，不然会加载不了。例如nacos中创建了配置文件dataId为test.yml，应用中配置
> extension-配置：
> -数据ID：test.yaml
> 组：xxx
> 刷新：t​​rue

+1

**Comment by zhutie8111** [comment]
Nacos可以重写本地的配置文件吗

**Comment by zhutie8111** [comment]
你的看一下其他配置，我测试完全不依赖这个文件，就算文件不存在都行
