### ISSUE TITLE
升级新版本报错

### ISSUE THREAD

**Issue by xiao-ma-nong** [alibaba/spring-cloud-alibaba#1865]
从Hoxton.SR4升级到8，
spring-cloud-alibaba.version 2.2.1.RELEASE升级到 2.2.3.RELEASE
springboot 2.2.6.RELEASE升级到 2.3.4.RELEASE

启动项目报以下错误

***************************
APPLICATION FAILED TO START
***************************

Description:

The Bean Validation API is on the classpath but no implementation could be found

Action:

Add an implementation, such as Hibernate Validator, to the classpath

Disconnected from the target VM, address: '127.0.0.1:55717', transport: 'socket'

**Comment by yuhuangbin** [comment]
这个跟Spring Cloud Alibaba应该没啥联系吧？

**Comment by xiao-ma-nong** [comment]
我使用是这个版本而已

不过已经解决了
