### ISSUE TITLE
need set the param maxReconsumeTimes,but the cloud stream don't surport the rmq param config

### ISSUE THREAD

**Issue by iorilchen** [alibaba/spring-cloud-alibaba#1866]
rocket mq can set the maxReconsumeTimes param,when use the stream cloud rocketmq, there is no config for this, would it surport ont the future?

**Comment by yuhuangbin** [comment]
contribute are welcome~

**Comment by zkzlx** [comment]
The new version is being refactored, and the issue will be resolved uniformly. Welcome to join us.

**Comment by huangdx0726** [comment]
I'll try

**Comment by zkzlx** [comment]
you can use the beta version #2029
