### ISSUE TITLE
在nacos做注册中心时，不同group下的服务之间无法相互调用

### ISSUE THREAD

**Issue by syapollo** [alibaba/spring-cloud-alibaba#1870]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
在nacos做注册中心时，不同group下的服务之间无法相互调用，因此也无法用spring cloud gateway自动路由

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuhuangbin** [comment]
设计如此
