### ISSUE TITLE
集成的netty，该怎么访问呢？

### ISSUE THREAD

**Issue by xiao-ma-nong** [alibaba/spring-cloud-alibaba#1871]
因为之前都是用demo测试是可以的使用的，但是集成到springcloudalibaba之后就无法连接了？？

或者有谁集成过netty？？

**Comment by theonefx** [comment]
Please provide more details

**Comment by xiao-ma-nong** [comment]
集成的netty没有启动，但是模块正常启动

**Comment by yuhuangbin** [comment]
不要吝啬你的日志，这样的描述谁能确定问题在哪呢？请按照issue模板来提供相关信息

**Comment by xiao-ma-nong** [comment]
> 不要吝啬你的日志，这样的描述谁能确定问题在哪呢？请按照issue模板来提供相关信息

非常感谢你的回复，我这边已经搞定了

**Comment by xiao-ma-nong** [comment]
不过我还是想问一个问题，请教一下老大哥

多台Netty服务的情况，假设我发布了三台netty服务

首先是通过负载均衡进行转发

进行三次转发

第一次请求->A服务器，这时候channel是在A服务器上面
第二次请求->B服务器，这时候channel是在B服务器上面
第三次请求->C服务器，这时候channel是在C服务器上面

这是基本的流程

假设第四次请求->A服务器上面，这时候channel通到是找不到的，也就是无法推送消息给用户

假设第四次是请求在C服务器上面，是可以正常推送消息

为了保证全局的channel网络通道，这个时候就需要寄托在第三方上面，想这种的就有点类似于那个springcloud 服务注册到eruka或者nacos、zk第三方中间件上面

当然啦，这些好高级

所以我使用redis中存储这个chnnel因为是网络通讯的东西，我是无法反序列化到redis中去，想问一下你这有什么更好的建议吗
