### ISSUE TITLE
Wiki 文档“配置的优先级”存在容易混淆的表述

### ISSUE THREAD

**Issue by yelijing18** [alibaba/spring-cloud-alibaba#1874]
Wiki 文档

[配置的优先级](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config#%E9%85%8D%E7%BD%AE%E7%9A%84%E4%BC%98%E5%85%88%E7%BA%A7) 
文档中写到“优先级关系是:A < B < C”，存在歧义容易造成混淆，建议修改。
应使用更为确切的说法，优先级的定语是“高和低”而不是“大和小”，并不一定所有读者都有“优先级数值小即优先级高”的认知
同时，例子中使用 A、B 和 C 亦没有体现出数值的概念，进一步加深了读者的疑惑。
如：“优先级大”、“优先级数值小”和“优先级高”，是否应选择“优先级高”才是最清晰的表达方式？

**Comment by yuhuangbin** [comment]
contribute are welcome~

**Comment by Dercharles** [comment]
正在尝试修正这个问题
