### ISSUE TITLE
Upgrade nacos-client version to 1.4.0

### ISSUE THREAD

**Issue by horizonzy** [alibaba/spring-cloud-alibaba#1875]
**Which Component**
Nacos Discovery

**Describe the bug**
Now the nacos-client version is 1.3.3. In the application.properties,  
```
version=${project.version}
```
It will cause some problem.  etc: https://github.com/alibaba/nacos/issues/3528 https://github.com/alibaba/nacos/issues/3867
The problem fixed by https://github.com/alibaba/nacos/pull/3872

Upgrade nacos-client to 1.4.0, it's compatible with 1.3.3.

**Comment by theonefx** [comment]
done
