### ISSUE TITLE
Nacos discovery param about heart beat unit second didn't match nacos unit millisecond

### ISSUE THREAD

**Issue by horizonzy** [alibaba/spring-cloud-alibaba#1877]
**Which Component**
Nacos Discovery

**Describe the bug**
Nacos discovery some param about heart beat, such as:
```
spring.cloud.nacos.discovery.heart-beat-interval=3
spring.cloud.nacos.discovery.heart-beat-timeout=6
spring.cloud.nacos.discovery.ip-delete-timeout=9
```
where unit are second, but in nacos, the unit is millisecond. 
It will lead to send heart beat frequently, and nacos server cpu load high.

**Comment by horizonzy** [comment]
Should append doc infol et user know the older version unit is milliseconds. If want change the default heart beat param, the old version unit is millisecond, the new version unit is second.

**Comment by yuhuangbin** [comment]
> Should append doc infol et user know the older version unit is milliseconds. If want change the default heart beat param, the old version unit is millisecond, the new version unit is second.

Maybe you only need to change the comment of the field, the unit of second is changed to millisecond.

**Comment by horizonzy** [comment]
It's also work, as long as user know the unit has changed since @`2.2.4.RELEASE`

**Comment by horizonzy** [comment]
It's also work, just let user know the unit is millisecond before `2.2.4.RELEASE`

**Comment by yuhuangbin** [comment]
> It's also work, just let user know the unit is millisecond before `2.2.4.RELEASE`

I think we just need to modify the comments, and the time unit needs to be consistent with Nacos, otherwise it will increase the cost of user understanding.

**Comment by horizonzy** [comment]
The old version comment can't modify. Should apply a way let user know old version comment unit is not right, use millisecond value to set



发自我的iPhone


------------------ Original ------------------
