### ISSUE TITLE
When will It be possible to support Spring-boot 2.4 and Spring-Cloud 2020?

### ISSUE THREAD

**Issue by FreeSaltedFish** [alibaba/spring-cloud-alibaba#1879]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lilaizhencn** [comment]
+1

**Comment by maoxiaoxiong** [comment]
+1

**Comment by Taogang00** [comment]
+1

**Comment by yuansongming** [comment]
来自：Spring Cloud Alibaba 开源讨论

林克（陈军进） 12月17日 11:27
有2.3的发布计划吗  是否支持spring cloud 2020.0.0 @涂南 Amber 

涂南 Amber 12月17日 11:33
@林克（陈军进）  这个月会发

**Comment by kennyliao1982** [comment]
just found an article about making spring cloud alibaba support spring cloud 2020. will give it a try later

https://juejin.cn/post/6911980096177995789

**Comment by HaojunRen** [comment]
Yeah, we tend to start the plan to support Spring Cloud 2020 and Spring Boot 2.4.1, please wait...
