### ISSUE TITLE
start.spring.io 已经不能帮忙创建带有 Nacos Service Discovery 依赖的项目了

### ISSUE THREAD

**Issue by GuoDapeng** [alibaba/spring-cloud-alibaba#1880]
![截屏2020-12-25 下午9 14 54](https://user-images.githubusercontent.com/7477750/103135885-bce5ad80-46f6-11eb-9520-879e655d26ba.png)

https://start.spring.io/

目前提供的最低版本是 2.3.7。现在已经不能正常的用它创建项目了。

我看 [版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E) 目前毕业版本是 2.3.2.RELEASE。
请问后续会修复这个吗？

**Comment by GuoDapeng** [comment]
https://github.com/alibaba/spring-cloud-alibaba/issues/1879#issue-773531980

**Comment by GuoDapeng** [comment]
#1879

**Comment by yuhuangbin** [comment]
https://start.aliyun.com/
