### ISSUE TITLE
generate properties bug

### ISSUE THREAD

**Issue by zhaoliangzl** [alibaba/spring-cloud-alibaba#1885]
you have duplicate config in application.properties 
有重复的配置在生成application.properties文件中
<img width="1209" alt="截屏2020-12-29 下午5 21 55" src="https://user-images.githubusercontent.com/25294531/103273565-91b2d500-49fa-11eb-8fed-2de4528d12f9.png">

**Comment by ppzzyy11** [comment]
已修复已发布
