### ISSUE TITLE
Nacos config  can't use application.properties or application.yml 

### ISSUE THREAD

**Issue by haoyann** [alibaba/spring-cloud-alibaba#1887]
**Which Component**
 Nacos Config

**Describe the bug**
Nacos config use application.properties or application.yml invalid configuration

**To Reproduce**
 Configure nacos with application.properties config 
  ```
server.port=18084
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


spring.application.name=nacos-config-example
spring.cloud.nacos.config.server-addr=10.0.0.1:8848

#nacos certification information
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos

  ```

I configure `spring.cloud.nacos.config.server-addr=10.0.0.1:8848`, but get serverAddr is `localhost:8848`
![image](https://user-images.githubusercontent.com/43994656/103330795-fa06c280-4a9d-11eb-878e-0f5641dba39b.png)

------

After checking the code, I found in `com.alibaba.cloud.nacos.NacosConfigBootstrapConfiguration#nacosConfigManager`, 
I did not configure the bootstrap , so it is the default value nacosConfigProperties. It create `NacosConfigManager`
![image](https://user-images.githubusercontent.com/43994656/103330922-9630c980-4a9e-11eb-98dc-dccbbd0e458a.png)

But`NacosConfigManager`  use  singleton create ConfigService. Even after getting the correct configuration `com.alibaba.cloud.nacos.NacosConfigAutoConfiguration`,  configService still wrong.
```
	static ConfigService createConfigService(
			NacosConfigProperties nacosConfigProperties) {
		if (Objects.isNull(service)) {
			synchronized (NacosConfigManager.class) {
				try {
					if (Objects.isNull(service)) {
						service = NacosFactory.createConfigService(
								nacosConfigProperties.assembleConfigServiceProperties());
					}
				}
				catch (NacosException e) {
					log.error(e.getMessage());
					throw new NacosConnectionFailureException(
							nacosConfigProperties.getServerAddr(), e.getMessage(), e);
				}
			}
		}
		return service;
	}
```

![image](https://user-images.githubusercontent.com/43994656/103331096-46063700-4a9f-11eb-9695-a63724300660.png)

**Additional context**
  MacOS  、Java8 、 Version 2.2.3.RELEASE

**Comment by yuhuangbin** [comment]
refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config
