### ISSUE TITLE
spring cloud dubbo 是否支持直连提供者

### ISSUE THREAD

**Issue by ProgramV** [alibaba/spring-cloud-alibaba#1888]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by theonefx** [comment]
能否明确描述一下需求细节和使用场景？

**Comment by JoeBiBi** [comment]
> 能否明确描述一下需求细节和使用场景？

您好
有一个场景我向您描述一下，不知能否实现

服务①启动并注册在nacos A
消费者②启动并注册在nacos A
消费者③启动并注册在nacos B
因为服务①只能做单台部署，并且希望消费者②，消费者③都能正常使用服务①

目前使用的是dubbo文档中提供的“直连提供者”，但是目前有个问题就是使用了“直连提供者”后，服务端的timeout属性会失效
“直连提供者”文档地址：https://dubbo.apache.org/zh/docs/v2.7/user/examples/explicit-target/

或者是否支持dubbo的“多注册中心”呢？
“多注册中心”文档地址：https://dubbo.apache.org/zh/docs/v2.7/user/examples/multi-registry/
