### ISSUE TITLE
nacos use yaml snake to parse date string(2019-02-20) but return date（WEB FED xxxxxx)

### ISSUE THREAD

**Issue by teneous** [alibaba/spring-cloud-alibaba#1889]
**Which Component**
spring cloud nacos config starter 2.2.3.RELEASE

**Describe the bug**
when I define params like this.
当我像下面这样定义参数时
![image](https://user-images.githubusercontent.com/21994254/103342115-a7400180-4ac3-11eb-9bb3-8e8e0ba5268e.png)
这里是我的代码
here is my code
![image](https://user-images.githubusercontent.com/21994254/103342168-c8085700-4ac3-11eb-89bc-e3c6314a76d8.png)

nacos use snakeyaml to parse these params, it returns  (YamlProcessor#process)
nacos使用nakeyaml进行参数解析，解析出来却自动变为了时间类型
![image](https://user-images.githubusercontent.com/21994254/103342351-41a04500-4ac4-11eb-8090-ee0c6322c178.png)

Although, I can use double quotation marks to avoid this issue.is that a bug of YAML?
虽然我可以使用双引号来避免，但是这个算是一个yaml的bug么

![image](https://user-images.githubusercontent.com/21994254/103343489-23881400-4ac7-11eb-9f06-8b53fc740230.png)

it successful return
![image](https://user-images.githubusercontent.com/21994254/103343527-3f8bb580-4ac7-11eb-83a4-6db5cd79cab1.png)

**Additional context**
MacOS 11.1 、Java8

**Comment by theonefx** [comment]
这个，我理解不是个问题，符合设计预期。
不使用引号，就代表这需要做特殊类型的转换，包括数字类型也是一样的情况。
如果需要使用字符串类型，就用双引号包起来，明确指定。
