### ISSUE TITLE
Spring cloud alibaba 2.2.3版本使用端点/actuator/service-registry注销服务注册问题

### ISSUE THREAD

**Issue by itunic** [alibaba/spring-cloud-alibaba#1893]
问题：通过spring提供的端点/actuator/service-registry 进行注销服务注册时，发生 ErrCode:500, ErrMsg:ErrCode:400, ErrMsg:instance not exist: 192.168.2.14:9091:unknown:DEFAULT_1.0_true_false_DEFAULT。

排查过程。

通过查看源码
 com.alibaba.cloud.nacos.registry.NacosServiceRegistry.setStatus(Registration registration, String status)方法。调用了
com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(String serviceName, Instance instance)，发现里面为硬编码this.updateInstance(serviceName, "DEFAULT_GROUP", instance);
在服务注册时指定group时会发生此问题。

bug版本：Spring cloud alibaba 2.2.1~ 2.2.3

**Comment by brothelul** [comment]
I want to solve it. please assgin to me.
