### ISSUE TITLE
How to switch call from remotelly to locally 

### ISSUE THREAD

**Issue by a22349** [alibaba/spring-cloud-alibaba#1899]
i have an interface and have an implementation , 
when use nacos , i want to switch from local call to remote call and backforth easily 
is there some property to control the remote call ? 
i saw spring.cloud.discovery.enable property but when i set it false , there is startup exception
in summary i just want to debug easily in local mode  and deploy later distributel later
ps i dont want to write two interface one is feign one is service i just want to use one service interface
thanks

**Comment by HaojunRen** [comment]
That is Spring Cloud mechanism, I think it is maybe difficult to resolve for Feign. But to RestTemplate, my personal opinion to use FF4J - 功能开关

**Comment by HaojunRen** [comment]
由于Spring Cloud Alibaba是基于Spring Cloud规范标准做进一步实现，所以您的需求可能满足满足。是否可以关闭该isseu？
