### ISSUE TITLE
springcloud2020中已弃用hystrix，而sentinel中对于fegin的的集成问题

### ISSUE THREAD

**Issue by 1837740965** [alibaba/spring-cloud-alibaba#1908]
springcloud
In the latest version of spring cloud in 20201, hystrix has been abandoned. However, in sentinel, hystrix is mainly used to implement sentinelfegin, resulting in a lack of dependency and error reporting. We can only reduce the version processing problem of openfegin. We hope the team can update the version to be compatible with the latest version of spring cloud

**Comment by HaojunRen** [comment]
We have a plan to remove hystrix in Sentinel in Spring Cloud 2020,please wait...
