### ISSUE TITLE
sentinel1.8控制台不显示限流的配置信息

### ISSUE THREAD

**Issue by zgz757183190** [alibaba/spring-cloud-alibaba#1917]
现状：
       springcloud gateway + nacos + sentinel ，实现网关动态限流。测试有达到限流的效果，但sentinel的控制不显示限流的配置参数。

版本说明：
1、SpringCloud Alibaba 2.2.3.RELEASE
2、SpringCloud Hoxton.SR8
3、springboot 2.3.2.RELEASE
4、nacos 1.4
5、sentinel 1.8

**Comment by HaojunRen** [comment]
Please forward to Sentinel github toreport issues?
