### ISSUE TITLE
nacos config directly by prefix

### ISSUE THREAD

**Issue by christophe-liwei** [alibaba/spring-cloud-alibaba#1927]
- Component
   nacos config
- Version
   2.0.x
- Description
  
![image](https://user-images.githubusercontent.com/20626345/104979887-495a6600-5a40-11eb-8d1c-1ee0643a2915.png)

This is a bug because the content is retrieved directly from the prefix

**Comment by yuhuangbin** [comment]
dataIdPrefix + fileExtension,  There's nothing wrong here.

**Comment by christophe-liwei** [comment]
你们经过测试了吗？这里明显使用的dataIdPrefix 作为dataId，没有拼接。

![image](https://user-images.githubusercontent.com/20626345/104987045-ae698800-5a4f-11eb-9ac0-5236b4f70566.png)

![image](https://user-images.githubusercontent.com/20626345/104987064-bde8d100-5a4f-11eb-8c86-2852ea553bfb.png)

**Comment by christophe-liwei** [comment]
![image](https://user-images.githubusercontent.com/20626345/104987139-e670cb00-5a4f-11eb-9027-100164871320.png)

这里明显直接使用了dataPrefix
