### ISSUE TITLE
nacos 配置中心不能刷新

### ISSUE THREAD

**Issue by lucian521** [alibaba/spring-cloud-alibaba#1929]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel
nacos 作为配置中心  springcloud 方式
nacos 客户端 : spring-cloud-alibaba-nacos-config-2.0.0.RELEASE.jar
nacos 服务端:  nacos-1.1.4

**Describe the bug**

应用端 bootstrap.yml  中配置

spring:
  application:
    name: hsa-cep-ips
  cloud:
    nacos:
      config:
        file-extension: yaml
        enabled: true
        #server-addr: 10.255.40.12:8848,10.255.40.13:8848,10.255.40.14:8848,10.255.40.25:8848,10.255.40.26:8848
        server-addr: 127.0.0.1:8803
        refreshable-dataids: hsa-cep-ips.yaml

2. 应用中配置
@ConfigurationProperties(prefix="httpconfig")
@Component
@Data
@RefreshScope
public class HttpConfig {

    /**
     *  xxx
     */
    private String elecertUrl;
}

3. nacos 中 配置 
httpconfig:
  #http 超时时间
  timeOut: 5
  #xxxxx
  elecertUrl: http://xxxx

4. 修改 nacos 中elecertUrl , 发布后, 应用中 elecertUrl 没有更新

环境配置:

JDK1.8 
nacos SDK : 2.0.0.RELEASE.jar
nacos  服务端: 1.1.4

**Comment by yuhuangbin** [comment]
refer #1926

**Comment by lucian521** [comment]
问题已经解决 jasypt-spring-boot-starter  2.1.1 jar 冲突, 将 jasypt-spring-boot-starter jar pom 引用去掉,  nacos 自动刷新功能 生效
