### ISSUE TITLE
Vote for version solution of next generation Spring Cloud Alibaba matching Spring Cloud 2020

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/spring-cloud-alibaba#1938]
Here is 3 solutions
- 3.x.x        [just like 2.x.x]，例如：3.0.1
- 202y.x.x  [first x is for month, second x is for version number]，例如：2021.0.0，表示2021年1月份的第一个版本；2021.1.2，表示2021年2月份的第三个版本
- 202y.x     [x is just for version number]，例如：2021.0，表示2021年的第一个版本；2021.2，表示2021年的第三个版本

如果是202y开头的大版本号，那么跟随Spring Cloud的大版本号

Please vote for those version solution by emotion  :+1:. If you have more solutions, you can reply this issue

**Comment by theonefx** [comment]
I think 2020.x is better, simpler and easier to remember

**Comment by HaojunRen** [comment]
3.x.x

**Comment by HaojunRen** [comment]
202y.x

**Comment by cckmit** [comment]
202y.x.x [first x is for month, second x is for version number]

**Comment by eonezhang** [comment]
202y. x. x is clear

**Comment by HaojunRen** [comment]
please use emotion

**Comment by yiqinghui** [comment]
202y.x.x

**Comment by alishangtian** [comment]
3.x.x

**Comment by 1308404897** [comment]
202y.xx [第一个x代表月份，第二个x代表版本号] 这个比较好点吧，详细点

**Comment by HaojunRen** [comment]
请点击:+1:三个选项中的一个进行投票

**Comment by caorenpeng-kaer** [comment]
202y.x

**Comment by 510mt** [comment]
202y.x.x

**Comment by zengjianfei** [comment]
跟springcloud版本保持

**Comment by Beannery** [comment]
0代表第一个,没必要这么刻意吧,接地气一些不行嘛, 1就是1,2就是2不行么 ?看到版本号后,大家还得想想,六爷到底吃了几碗粉?

版本号不仅是规则,更要便于理解,虽然我是程序员,但我如果提前不知道这个版本命名规则的话,我的理解,1就是第一个版本号,行业大佬的规则,也要辩证看待,除非是这样规定有其它原因,如果只是程序员的世界里0就是1的话,不是很赞同,带来不必要的理解障碍.

cloud原本以地铁站式命名为什么后来又使用日历化版本命名?不还是普遍感觉不好用，所以还是以实用性为主，行业大佬的方案未必都是好的，别被牵着鼻子走，一个版本而已，本来就是服务于人，如果第一眼看到的版本信息还要结合规则去算一下实际的版本，就感觉菊花隐隐作痛。

**Comment by yonxao** [comment]
适配 spring cloud 的最高版本

**Comment by lilaizhencn** [comment]
还是别在这上面下功夫了。 紧随springcloud的版本发布和适配节奏和版本名称定义不好吗。

**Comment by lihuimingxs** [comment]
更新的频繁，选项2比较好；如果不太频繁，选项3比较好。

**Comment by tyronego** [comment]
202y.x

**Comment by tyronego** [comment]
紧随springcloud的版本，一眼就能看出适配哪个版本

**Comment by HaojunRen** [comment]
最终方式采用年份+数字，例如2021年发布第一版，那么版本号为2021.1
