### ISSUE TITLE
config nacosrule but does not work!

### ISSUE THREAD

**Issue by apple987** [alibaba/spring-cloud-alibaba#1944]
my version,nacos1.4.0+springCloudAlibaba2.2.3.RELEASE+sentinel1.8.0,here is my config

@Configuration
public class RibbonConfig {

    @Bean
    @Scope(value="prototype")
    public IRule loadBalanceRule(){
      
        return new NacosRule();
    }
}

server:
  port: 8088
# 使用阿里 sentinel监控
feign:
  sentinel: #开启sentinel熔断
    enabled: true
  hystrix:  #关闭hystrix熔断
    enabled: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true #开启okhttp
  compression: #开启压缩
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000
#actuator健康检查配置
management:
  health:
    sentinel:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'heapdump' #内存转储存在泄漏风险，关掉内存转储
  endpoint:
    health:
      show-details: always
# actuator系统信息
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring-boot.version@'
  spring-cloud-version: '@spring-cloud.version@'
  spring-cloud-alibaba-version: '@spring-cloud-alibaba.version@'
###########启用环境##################
spring:
  nacos-host: @service.nacos.host@
  nacos-port: @service.nacos.port@
  nacos-username: @service.nacos.username@
  nacos-password: @service.nacos.password@
  nacos-namespace: @service.nacos.namespace@
  nacos-group: @service.group@
  profiles:
    active: @profile.active@
  application:
    name: business
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr:  ${spring.nacos-host}:${spring.nacos-port}
        username: ${spring.nacos-username}
        password: ${spring.nacos-password}
        namespace: ${spring.nacos-namespace}
        group: ${spring.nacos-group}
      config:
        server-addr:  ${spring.nacos-host}:${spring.nacos-port}
        username: ${spring.nacos-username}
        password: ${spring.nacos-password}
        namespace: ${spring.nacos-namespace}
        group: ${spring.nacos-group}
        file-extension: properties
    loadbalancer:
      retry:
        enabled: false
#日志配置
logging:
  config: classpath:log4j2-${spring.profiles.active}.yml

when i start the project with debug mode,the code return new NacosRule() does not stop,after two client started,the nacos rule does not work!need help thanks!

**Comment by theonefx** [comment]
I can't understand what the specific problem is, can you provide more problem description?

**Comment by apple987** [comment]
when the proiect starting,the bean NacosRule sholud be loaded,but it does not happen, search the ribbon document,find the answer,thanks!
