### ISSUE TITLE
How to use the latest version of Sentinel-Core 1.8.0 by spring-cloud-starter-alibaba-sentinel

### ISSUE THREAD

**Issue by pengtenghui** [alibaba/spring-cloud-alibaba#1948]
目前spring-cloud-starter-alibaba-sentinel整合的sentinel-core是1.7.1
请问下
spring-cloud-starter-alibaba-sentinel何时会整合最新版本的sentinel-core:1.8.0
![image](https://user-images.githubusercontent.com/28785423/106095504-def7a300-616e-11eb-8d99-5ca16c0804bc.png)

**Comment by HaojunRen** [comment]
目前Spring Cloud Alibaba 2.2.5.RC2已经集成Sentinel 1.8.0，请试用，同时敬请等待2.2.5正式版发布
