### ISSUE TITLE
nacos-discovery和websocket依赖不兼容，导致NacosWatch获取错误的TaskScheduler

### ISSUE THREAD

**Issue by HSPCode** [alibaba/spring-cloud-alibaba#1952]
您好，
一、问题描述：nacos作为注册中心，项目引入nacos-discovery依赖，NacosWatch获取错误的taskScheduler（websocket的NoOpScheduler）导致项目无法启动。
![image](https://user-images.githubusercontent.com/47849395/105978391-71476a80-60cd-11eb-8143-79db8a6399b3.png)
二、项目版本依赖：
（1）springboot版本2.0.3.RELEASE
（2）spring-boot-starter-websocket版本2.0.3.RELEASE
（3）spring-cloud-starter-alibaba-nacos-discovery版本2.0.3.RELEASE
三、问题原因：NacosWatch的taskScheduler实现类获取的是org.springframework.web.socket.config.annotation.WebSocketConfigurationSupport的内部类NoOpScheduler，这个类的scheduleWithFixedDelay(Runnable task, long delay)方法是抛出异常，导致项目启动不了。
![image](https://user-images.githubusercontent.com/47849395/105978867-f92d7480-60cd-11eb-8b51-d1d45bcd6127.png)
![image](https://user-images.githubusercontent.com/47849395/105977884-dea6cb80-60cc-11eb-8f40-6de47ac5ac86.png)
具体获取：
org.springframework.beans.factory.support.DefaultListableBeanFactory类通过classType获取
![image](https://user-images.githubusercontent.com/47849395/105980225-8e7d3880-60cf-11eb-8e88-32d862663a0a.png)

四、效果对比：
（1）项目去掉spring-boot-starter-websocket依赖，启动成功
（2）通过@Primary指定，启动成功
![image](https://user-images.githubusercontent.com/47849395/105980795-41e62d00-60d0-11eb-9210-281019a6a638.png)
（3）其他项目，未引入spring-boot-starter-websocket依赖，启动成功
五、咨询目的：这个冲突算是nacos-discovery兼容问题；还是说是个人的使用不当导致的，正确用法就是四.(2)？

_Originally posted by @HSPCode in https://github.com/alibaba/nacos/issues/4096#issuecomment-768202136_

**Comment by yuhuangbin** [comment]
请使用新版本以解决此问题

**Comment by HSPCode** [comment]
> 请使用新版本以解决此问题



> 请使用新版本以解决此问题
好的大佬。但是有个疑问：
![image](https://user-images.githubusercontent.com/47849395/106352775-c3cc9500-6320-11eb-8dfa-6336a3d3e22d.png)
根据官方文档说明，nacos-discovery和springboot的依赖版本需要尽量保持一致，nacos-discovery的2.2.4.RELEASE和springboot的2.0.3不会有问题嘛？这是项目启动后新的问题：
![image](https://user-images.githubusercontent.com/47849395/106353040-a4366c00-6322-11eb-8e69-d38dd4c18a74.png)
![image](https://user-images.githubusercontent.com/47849395/106353063-d47e0a80-6322-11eb-874b-b2736552ac3e.png)
![image](https://user-images.githubusercontent.com/47849395/106353067-dcd64580-6322-11eb-8580-af95267c9938.png)
![image](https://user-images.githubusercontent.com/47849395/106353076-e8297100-6322-11eb-999f-8d5393a2ea9c.png)
是哪些依赖也要跟着升级吗？
