### ISSUE TITLE
wiki文档描述错误

### ISSUE THREAD

**Issue by zard-sakai** [alibaba/spring-cloud-alibaba#1953]
**问题截图：**
问题1：
![image](https://user-images.githubusercontent.com/47819674/106280437-e1deba80-6278-11eb-97a0-3f351ea12d9d.png)
问题2：
![image](https://user-images.githubusercontent.com/47819674/106279919-2ae23f00-6278-11eb-8630-7548b59a2be0.png)

**问题链接：**
问题1、2链接：https://github.com/alibaba/spring-cloud-alibaba/wiki/Spring-Cloud-Alibaba-Meetup-%E5%9F%8E%E5%B8%82%E7%AB%99%E5%85%A8%E5%B9%B4%E8%A7%84%E5%88%92

**Comment by theonefx** [comment]
非常感谢反馈，问题已经修复
