### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by jacksonrick** [alibaba/spring-cloud-alibaba#1957]
spring-cloud-starter-alibaba-nacos-discovery:2.2.1.RELEASE

com.alibaba.cloud.nacos.discovery.NacosWatch.getTaskScheduler() 77行
```
taskScheduler.setBeanName("Nacso-Watch-Task-Scheduler");
```

`Nacso`拼写错误，应该为`Nacos`

**Comment by yuhuangbin** [comment]
Has been resolved. Refer to the latest code.
