### ISSUE TITLE
Aliyun Java Initializr  引入nacos discovery  但是在生成的start子模块中找到@EnableDiscoveryClient的jar

### ISSUE THREAD

**Issue by wxz0107** [alibaba/spring-cloud-alibaba#1961]
maven
java  
springboot：2.3.7.RELEASE
应用框架：MVC
组件：nacos discovery

生成项目  看到springcloudalibaba的版本是2.2.2.RELEASE 
在start模块中 有一个NacosDiscoveryConfiguration的配置类 但是类注解 @EnableDiscoveryClient 找不到

这个难道要直接手动在start模块下添加nacos discovery的依赖嘛

**Comment by wxz0107** [comment]
经过尝试在start子模块的pom.xml中手动添加了依赖
  <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
就可以了

**Comment by ppzzyy11** [comment]
谢谢反馈，已修

**Comment by ppzzyy11** [comment]
> 谢谢反馈，已修

下次发版会更新
