### ISSUE TITLE
nacos config with version in metadata,but it does not work!

### ISSUE THREAD

**Issue by apple987** [alibaba/spring-cloud-alibaba#1962]
my current version is:
 <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.build.timestamp.format>yyyy-MM-dd HH</maven.build.timestamp.format>
        <spring-cloud.version>Hoxton.SR8</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
        <spring-boot.version>2.3.8.RELEASE</spring-boot.version>
        <seata-spring-boot-starter.version>1.4.0</seata-spring-boot-starter.version>
        <sentinel.version>1.8.0</sentinel.version>
        <mybatis-plus.version>3.3.2</mybatis-plus.version>
        <maven-javadoc-plugin.version>3.0.1</maven-javadoc-plugin.version>
        <maven-source-plugin.version>3.0.1</maven-source-plugin.version>
        <skywalking.version>8.1.0</skywalking.version>
        <xxljob.version>2.2.0</xxljob.version>
    </properties>

the project bean setting is here!

@MapperScan("com.mcy.**.mapper")
@EnableFeignClients
@EnableDiscoveryClient
@SpringBootApplication(scanBasePackages = "com.mcy.business")
@RibbonClient(name = "${spring.application.name}", configuration = RibbonConfig.class)
@Slf4j
public class BusinessApplication {

    public static void main(String[] args) throws UnknownHostException {
        ConfigurableApplicationContext application = SpringApplication.run(BusinessApplication.class, args);
        Environment env = application.getEnvironment();
        String activeProfiles= StringUtils.arrayToCommaDelimitedString(env.getActiveProfiles());
        activeProfiles=StringUtils.isEmpty(activeProfiles)?"default":activeProfiles;
        log.info("<===========[{}]启动完成！"+"运行环境:[{}] IP:[{}] PORT:[{}]===========>", env.getProperty("spring.application.name"),activeProfiles,InetAddress.getLocalHost().getHostAddress(),env.getProperty("server.port"));
    }

}

@Configuration
@Slf4j
public class RibbonConfig {

    @Bean
    @Scope("prototype")
    public IRule initRibbonRule() {
        log.info("Initializing Ribbon With Nacos Rule=========================================>>>>");
        return new NacosFinalRule();
    }
}

public class NacosFinalRule extends AbstractLoadBalancerRule {
    private static final Logger LOGGER = LoggerFactory.getLogger(NacosFinalRule.class);
    @Autowired
    private NacosDiscoveryProperties nacosDiscoveryProperties;
    @Autowired
    private NacosServiceManager nacosServiceManager;

    public NacosFinalRule() {
    }

    @Override
    public Server choose(Object key) {
        try {
            String clusterName = this.nacosDiscoveryProperties.getClusterName();
            String group = this.nacosDiscoveryProperties.getGroup();
            //服务元数据版本
            String version = this.nacosDiscoveryProperties.getMetadata().get("version");
            LOGGER.info("NacosFinalRule get current service version:{}",version);
            DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer)this.getLoadBalancer();
            String name = loadBalancer.getName();
            NamingService namingService = this.nacosServiceManager.getNamingService(this.nacosDiscoveryProperties.getNacosProperties());
            List<Instance> instances = namingService.selectInstances(name, group, true);
            if (org.springframework.util.CollectionUtils.isEmpty(instances)) {
                LOGGER.warn("no instance in service {}", name);
                return null;
            } else {
                List<Instance> instancesToChoose = instances;
                //相同版本实例
                if (StringUtils.isNotBlank(version)) {
                    instancesToChoose = instances.stream()
                            .filter(instance -> Objects.equals(version, instance.getMetadata().get("version")))
                            .collect(Collectors.toList());
                    if (CollectionUtils.isEmpty(instancesToChoose)) {
                        LOGGER.warn("No metadata matching target instance found, Please check the configuration ! version = {}, instance = {}", version, instances);
                        return null;
                    }
                }
                //相同集群实例
                if (StringUtils.isNotBlank(clusterName)) {
                    List<Instance> sameClusterInstances = (List)instances.stream().filter((instancex) -> {
                        return Objects.equals(clusterName, instancex.getClusterName());
                    }).collect(Collectors.toList());
                    if (!CollectionUtils.isEmpty(sameClusterInstances)) {
                        instancesToChoose = sameClusterInstances;
                    } else {
                        LOGGER.warn("A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}", new Object[]{name, clusterName, instances});
                    }
                }
                Instance instance = ExtendBalancer.getHostByRandomWeight2(instancesToChoose);
                return new NacosServer(instance);
            }
        } catch (Exception var10) {
            LOGGER.warn("NacosFinalRule error", var10);
            return null;
        }
    }

    @Override
    public void initWithNiwsConfig(IClientConfig iClientConfig) {
    }
}

the bootstrap.yaml is this!

server:
  port: 8089
# 使用阿里 sentinel监控
feign:
  sentinel: #开启sentinel熔断
    enabled: true
  hystrix:  #关闭hystrix熔断
    enabled: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true #开启okhttp
  compression: #开启压缩
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
ribbon:
  nacos:
    enabled: true
  ConnectTimeout: 30000
  ReadTimeout: 30000
  eager-load:
    enabled: true
    clients: ${spring.application.name}

#actuator健康检查配置
management:
  health:
    sentinel:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'heapdump' #内存转储存在泄漏风险，关掉内存转储
  endpoint:
    health:
      show-details: always
# actuator系统信息
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring-boot.version@'
  spring-cloud-version: '@spring-cloud.version@'
  spring-cloud-alibaba-version: '@spring-cloud-alibaba.version@'
###########启用环境##################
spring:
  nacos-host: @service.nacos.host@
  nacos-port: @service.nacos.port@
  nacos-username: @service.nacos.username@
  nacos-password: @service.nacos.password@
  nacos-namespace: @service.nacos.namespace@
  nacos-group: @service.group@
  profiles:
    active: @profile.active@
  application:
    name: business
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr:  ${spring.nacos-host}:${spring.nacos-port}
        username: ${spring.nacos-username}
        password: ${spring.nacos-password}
        namespace: ${spring.nacos-namespace}
        group: ${spring.nacos-group}
        metadata:
          version: 1.0.0.RELEASE
        enabled: true
      config:
        server-addr:  ${spring.nacos-host}:${spring.nacos-port}
        username: ${spring.nacos-username}
        password: ${spring.nacos-password}
        namespace: ${spring.nacos-namespace}
        group: ${spring.nacos-group}
        file-extension: properties
        enabled: true
    loadbalancer:
      retry:
        enabled: false
#日志配置
logging:
  config: classpath:log4j2-${spring.profiles.active}.yml

when i start the project,config with the metadata,but it does not work!need help thanks!

**Comment by apple987** [comment]
spring:
  nacos-host: @service.nacos.host@
  nacos-port: @service.nacos.port@
  nacos-username: @service.nacos.username@
  nacos-password: @service.nacos.password@
  nacos-namespace: @service.nacos.namespace@
  nacos-group: @service.group@
  profiles:
    active: @profile.active@
  application:
    name: business
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr:  ${spring.nacos-host}:${spring.nacos-port}
        username: ${spring.nacos-username}
        password: ${spring.nacos-password}
        namespace: ${spring.nacos-namespace}
        group: ${spring.nacos-group}
        metadata:
          version: 1.0.0.RELEASE
        enabled: true
      config:
        server-addr:  ${spring.nacos-host}:${spring.nacos-port}
        username: ${spring.nacos-username}
        password: ${spring.nacos-password}
        namespace: ${spring.nacos-namespace}
        group: ${spring.nacos-group}
        file-extension: properties
        enabled: true
    loadbalancer:
      retry:
        enabled: false


feign:
  sentinel: #开启sentinel熔断
    enabled: true
  hystrix:  #关闭hystrix熔断
    enabled: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true #开启okhttp
  compression: #开启压缩
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
ribbon:
  nacos:
    enabled: true
  ConnectTimeout: 30000
  ReadTimeout: 30000
  eager-load:
    enabled: true
    clients: ${spring.application.name}

**Comment by apple987** [comment]
when check this class NacosRule,i think the metadata should contain the key version,that mean the same version client can be called!
so the nacos rule choose method should such as this:

public Server choose(Object key) {
        try {
            String clusterName = this.nacosDiscoveryProperties.getClusterName();
            String group = this.nacosDiscoveryProperties.getGroup();
            //服务元数据版本
            String version = this.nacosDiscoveryProperties.getMetadata().get("version");
            System.err.println("NacosFinalRule get current service version:{}"+version);
            LOGGER.info("NacosFinalRule get current service version:{}",version);
            DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer)this.getLoadBalancer();
            String name = loadBalancer.getName();
            NamingService namingService = this.nacosServiceManager.getNamingService(this.nacosDiscoveryProperties.getNacosProperties());
            List<Instance> instances = namingService.selectInstances(name, group, true);
            if (org.springframework.util.CollectionUtils.isEmpty(instances)) {
                LOGGER.warn("no instance in service {}", name);
                return null;
            } else {
                List<Instance> instancesToChoose = instances;
                //相同版本实例
                if (StringUtils.isNotBlank(version)) {
                    instancesToChoose = instances.stream()
                            .filter(instance -> Objects.equals(version, instance.getMetadata().get("version")))
                            .collect(Collectors.toList());
                    if (CollectionUtils.isEmpty(instancesToChoose)) {
                        LOGGER.warn("No metadata matching target instance found, Please check the configuration ! version = {}, instance = {}", version, instances);
                        return null;
                    }
                }
                //相同集群实例
                if (StringUtils.isNotBlank(clusterName)) {
                    List<Instance> sameClusterInstances = (List)instances.stream().filter((instancex) -> {
                        return Objects.equals(clusterName, instancex.getClusterName());
                    }).collect(Collectors.toList());
                    if (!CollectionUtils.isEmpty(sameClusterInstances)) {
                        instancesToChoose = sameClusterInstances;
                    } else {
                        LOGGER.warn("A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}", new Object[]{name, clusterName, instances});
                    }
                }
                Instance instance = ExtendBalancer.getHostByRandomWeight2(instancesToChoose);
                return new NacosServer(instance);
            }
        } catch (Exception var10) {
            LOGGER.warn("NacosFinalRule error", var10);
            return null;
        }
    }


not only the same  cluster client but also the same version ! This is a suggestion. You need to add clients of the same cluster and the same version. When both are satisfied, the instance found by the load is allowed to be called. At present, only clients of the same cluster feel that there is a problem that different client versions can be called ！thanks！

**Comment by HaojunRen** [comment]
duplicated with https://github.com/alibaba/spring-cloud-alibaba/issues/1965
