### ISSUE TITLE
Metadata version number does not work, fatal bug!

### ISSUE THREAD

**Issue by apple987** [alibaba/spring-cloud-alibaba#1965]
After the version number of metadata is configured, only the server and client with the same version number can be called during load balancing. Different version numbers are not allowed to be called. However, the current code only uses the version of the same cluster, and there is no service processing with the same version number of metadata. There are services with different version numbers that can be called each other, which is wrong！
1. Here's the bug code：
public class NacosRule extends AbstractLoadBalancerRule {
@Override
	public Server choose(Object key) {
		try {
			String clusterName = this.nacosDiscoveryProperties.getClusterName();
			String group = this.nacosDiscoveryProperties.getGroup();
			DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer) getLoadBalancer();
			String name = loadBalancer.getName();

			NamingService namingService = nacosServiceManager
					.getNamingService(nacosDiscoveryProperties.getNacosProperties());
			List<Instance> instances = namingService.selectInstances(name, group, true);
			if (CollectionUtils.isEmpty(instances)) {
				LOGGER.warn("no instance in service {}", name);
				return null;
			}

			List<Instance> instancesToChoose = instances;
                       /////这里只是做了相同集群，并没有处理元数据相同版本，存在不同版本号服务可以互相调用的bug///////
			if (StringUtils.isNotBlank(clusterName)) {
				List<Instance> sameClusterInstances = instances.stream()
						.filter(instance -> Objects.equals(clusterName,
								instance.getClusterName()))
						.collect(Collectors.toList());
				if (!CollectionUtils.isEmpty(sameClusterInstances)) {
					instancesToChoose = sameClusterInstances;
				}
				else {
					LOGGER.warn(
							"A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}",
							name, clusterName, instances);
				}
			}

			Instance instance = ExtendBalancer.getHostByRandomWeight2(instancesToChoose);

			return new NacosServer(instance);
		}
		catch (Exception e) {
			LOGGER.warn("NacosRule error", e);
			return null;
		}
	}
}
2 .the correct code:
public class NacosRule extends AbstractLoadBalancerRule {
@Override
	public Server choose(Object key) {
		try {
			String clusterName = this.nacosDiscoveryProperties.getClusterName();
			String group = this.nacosDiscoveryProperties.getGroup();
			DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer) getLoadBalancer();
			String name = loadBalancer.getName();
                       //服务元数据版本，元数据的map这里使用version作为key，其他字段也可以
                       String version = this.nacosDiscoveryProperties.getMetadata().get("version");
			NamingService namingService = nacosServiceManager
					.getNamingService(nacosDiscoveryProperties.getNacosProperties());
			List<Instance> instances = namingService.selectInstances(name, group, true);
			if (CollectionUtils.isEmpty(instances)) {
				LOGGER.warn("no instance in service {}", name);
				return null;
			}

			List<Instance> instancesToChoose = instances;
                  //相同版本实例，负载均衡选择实例时，必须是相同的版本号，才存在互相调用的可能性
                if (StringUtils.isNotBlank(version)) {
                    instancesToChoose = instances.stream()
                            .filter(instance -> Objects.equals(version, instance.getMetadata().get("version")))
                            .collect(Collectors.toList());
                    if (CollectionUtils.isEmpty(instancesToChoose)) {
                        LOGGER.warn("No metadata matching target instance found, Please check the configuration ! version = {}, i 
                         nstance = {}", version, instances);
                        return null;
                    }
                }
                       //这里才是处理相同集群的实例，提供负载均衡规则调用
			if (StringUtils.isNotBlank(clusterName)) {
				List<Instance> sameClusterInstances = instances.stream()
						.filter(instance -> Objects.equals(clusterName,
								instance.getClusterName()))
						.collect(Collectors.toList());
				if (!CollectionUtils.isEmpty(sameClusterInstances)) {
					instancesToChoose = sameClusterInstances;
				}
				else {
					LOGGER.warn(
							"A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}",
							name, clusterName, instances);
				}
			}

			Instance instance = ExtendBalancer.getHostByRandomWeight2(instancesToChoose);
			return new NacosServer(instance);
		}
		catch (Exception e) {
			LOGGER.warn("NacosRule error", e);
			return null;
		}
	}
}

3.there is room for optimization with server list ,suggestion code!
public class NacosServerList extends AbstractServerList<NacosServer> {
       
        //这里实例化nacos的负载实例时，加上只筛选元数据相同版本号的服务实例
	private List<NacosServer> instancesToServerList(List<Instance> instances) {
		List<NacosServer> result = new ArrayList<>();
		if (CollectionUtils.isEmpty(instances)) {
			return result;
		}
		for (Instance instance : instances) {
                        //TODO 筛选出相同版本的服务实例，加入NacosServer列表
			result.add(new NacosServer(instance));
		}
		return result;
	}
}

**Comment by HaojunRen** [comment]
按照我的理解，根据自定义元数据(例如∶version)去实现类似灰度发布的功能，这并不属于Nacos和Spring Cloud Alibaba的技术范畴。Spring Cloud Alibaba也不大可能内置一个version的元数据进行逻辑处理，如果是，那么用户则会提出是否可以支持region，zone等更多的元数据自定义功能

**Comment by apple987** [comment]
nacos是支持灰度发布的，灰度发布会存储在单独的config-beta表，正常配置存储在config表。我这里提出的是，在做负载均衡的时候，相同服务order，如果发布时存在3个实例，实例1：1.0版本，实例2：2.0版本，实例3：2.0版本。客户端如果已经升级到2.0版本，那么这里服务器可用实例，就不能出现1.0版本。系统的多版本控制这是常用的，至于灰度发布那是另外一个问题，跟我提出的没有关系！灰度发布只是说配置项针对具体那几台实例生效，但是整个服务对应的版本号还是一致的，只是存在beta版本配置不同！！！！

**Comment by HaojunRen** [comment]
你的版本号version，在Spring Cloud Alibaba侧看看，其范畴是业务数据，你提到“/////这里只是做了相同集群，并没有处理元数据相同版本，存在不同版本号服务可以互相调用的bug///////”，是希望基础框架帮你去处理你定义的业务性质的数据么？

**Comment by apple987** [comment]
这不是业务系统的bug啊，做APP的应用很正常的存在系统多版本的场景！既然服务端都使用了nacos来作为负载均衡，那么在源头这里可以加上这个version来控制，多系统版本实例时，存在的业务缺陷！这里加了version对于框架也没有什么影响吧？正常使用不配置version，使用没有问题，这里提出的是针对相同系统多版本共存如何来高效结局的的方案！

**Comment by HaojunRen** [comment]
理解你的需求，但个人认为这不是Spring Cloud Alibaba的技术范畴，例如像阿里云edas等才具备这种业务商业级功能，这也并不是bug

**Comment by apple987** [comment]
源码我可以自己改，只是这里把代码贴出来，希望官方在系统能加上这个，而且这个对于现有框架没有任何影响，同时对于现有框架业务支持是一种扩充，目的是帮助社区越做越好。你是害怕加了这个元数据版本处理，会引申出其他更多的个性化需求吗？大可不必，有些非共性的场景，完全可以项目自己解决。但是目前这种场景是很常见的，这个框架既然是提供解决方案，多提供一种解决方案，对于使用者来说不是更具优势吗？

**Comment by HaojunRen** [comment]
其实，源码上不做任何修改，也可以实现你要的功能，可以参考https://github.com/Nepxion/Discovery

**Comment by apple987** [comment]
这是灰度发布增强组件吗？跟我的需求不符吧?

**Comment by HaojunRen** [comment]
你的需求不是如下场景么：
A服务->B服务->C服务，若干个服务的版本要对齐或者指定，例如，A 1.0 -> B 1.0 -> C 1.0或者A 2.0 -> B 2.0 -> C 2.0

**Comment by apple987** [comment]
差不多是这样，上面那个组件可以实现吗？

**Comment by HaojunRen** [comment]
对的，版本对齐也可以交由用户来编排，例如，也可以是A 1.0 -> B 2.0 -> C 3.0，不仅有版本，也有区域，环境等更多维度

**Comment by apple987** [comment]
好的，非常感谢！我学习一下，这个框架，有问题在咨询您！

**Comment by HaojunRen** [comment]
Close this issue first, if any problems or suggestions, please reopen it. thanks
