### ISSUE TITLE
NacosDiscoveryProperties service value cannot resolve properly 

### ISSUE THREAD

**Issue by wangzhenxyz1** [alibaba/spring-cloud-alibaba#1966]
**Nacos Discovery**

**Describe the bug**
when set spring.cloud.nacos.discovery.service= embed string(#{'${spring.application.name}'.toUpperCase()}),
@Value can resolve the value propertly, but will be override by setService finally, the service value is still embed string.

**To Reproduce**
spring:
  application:
    name: spring-cloud-alibaba-dubbo-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
        service: "#{'${spring.application.name}'.toUpperCase()}"
        
        
**Expected behavior**
should not override by the method of setService, can set the resolved embed value.
 

**Additional context**
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2.2.3.RELEASE</version>
</dependency>

**Comment by HaojunRen** [comment]
In my mind, service name in Nacos only supports lower case. What proposal to convert to upper case?

**Comment by wangzhenxyz1** [comment]
> In my mind, service name in Nacos only supports lower case. What proposal to convert to upper case?

Current situation is eureka and nacos combination registy,  default eureka registry registers service name is upper-case transparntly ,when sync service infos to nacos via nacos-sync, using the same service name cannot find services in nacos properly vice-versa.

**Comment by HaojunRen** [comment]
yeah, we also do this kind of workaround, and we changed all service name in Eureka one-by-one to lower case. we can not find any more better solutions.

**Comment by wangzhenxyz1** [comment]
anyway this is a bug

**Comment by HaojunRen** [comment]
i have contacted with Nacos Team, hope they can do an enhancement for it

**Comment by KomachiSion** [comment]
Nacos will not do any operation from users' input, so if you register upper, nacos stores it with upper.

I think it's a eureka's problem, which modified the original input is not great.

So if you need use nacos-sync and using the same service in nacos and eureka at the same time. you need to know the Eureka has a bad way to ignore word cases by uppering them. So you need to register service all upper name.

**Comment by HaojunRen** [comment]
Close this issue first. If any problems, please reopen it
