### ISSUE TITLE
nacos修改远程配置本地不刷新

### ISSUE THREAD

**Issue by RuoBingCoder** [alibaba/spring-cloud-alibaba#1970]
### 1、Nacos 单机版作为配置中心
spring boot  version 2.2.6.RELEASE
nacos-config-spring-boot-starter verison 0.2.7

- 具体原因是线程池执行事件回掉，本地nacosValueTarget map发现为空，造成无法注入新值请作者复现一下问题！谢谢！

**Comment by yuhuangbin** [comment]
提交issue至 https://github.com/nacos-group/nacos-spring-boot-project
