### ISSUE TITLE
NacosServiceRegistry Close NPE

### ISSUE THREAD

**Issue by liaomengge** [alibaba/spring-cloud-alibaba#1981]
when use graceful shutdown service, the NacosServiceRegistry#close not judge namingService isn't NULL, so then throw NPE. for below:
```
public void nacosServiceShutDown() throws NacosException {
    this.namingService.shutDown(); --- need judge namingService not null
    namingService = null;
    namingMaintainService = null;
}
```

**Comment by HaojunRen** [comment]
Would you please submit a PR for nacosServiceShutDown?

**Comment by steverao** [comment]
We solved this problem in in Spring Cloud Alibaba 2.2.7.RELEASE!
