### ISSUE TITLE
enable-remote-sync-config 设置无效

### ISSUE THREAD

**Issue by ljwps** [alibaba/spring-cloud-alibaba#1982]
**Which Component**
discovery-common-nacos-6.0.1.jar
**Describe the bug**
因为单元测试原因，需要将enable-remote-sync-config 设置为false。
将此属性设置为false，但依旧为true，跟踪代码后发现NacosAutoConfiguration这个类中
@Bean
    @ConditionalOnMissingBean
    public ConfigService nacosConfigService() throws NacosException {
        Properties properties = createNacosProperties(environment, true);

        return NacosFactory.createConfigService(properties);
    }
createNacosProperties(environment, true);这行第二个参数强制给了true，并没有用yml配置中的false

**Comment by yuhuangbin** [comment]
这个不属于Spring Cloud Alibaba项目范畴，请提交issue至正确仓库。
