### ISSUE TITLE
spring-cloud-starter-stream-rocketmq:2.2.5.RELEASE not support rocketmq-spring-boot-starter:2.0.2

### ISSUE THREAD

**Issue by sundong1982** [alibaba/spring-cloud-alibaba#1984]
spring-cloud-starter-stream-rocketmq:2.2.5.RELEASE not support rocketmq-spring-boot-starter:2.0.2

java.lang.NoClassDefFoundError: org/apache/rocketmq/spring/config/TransactionHandlerRegistry
java.lang.ClassNotFoundException: org.apache.rocketmq.spring.config.TransactionHandlerRegistry

use rocketmq-spring-boot-starter:2.0.2 is ok.

**Comment by theonefx** [comment]
please try 2.2.5-RocketMQ-RC1
https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.5-RocketMQ-RC1

**Comment by sundong1982** [comment]
@theonefx thx:)
