### ISSUE TITLE
使用-Dcsp.sentinel.app.type=1无法标识gateway

### ISSUE THREAD

**Issue by LoranMEI** [alibaba/spring-cloud-alibaba#1985]
spring-boot：2.3.2.RELEASE
spring-cloud：Hoxton.SR8
spring-cloud-alibaba：2.2.5.RELEASE
使用-Dcsp.sentinel.app.type=1无法标识gateway

**Comment by MingIXu** [comment]
标识后重启 sentinel-dashboard 或 先标识-Dcsp.sentinel.app.type=1的应用再启动 sentinel-dashboard

**Comment by MingIXu** [comment]
> spring-boot：2.3.2.RELEASE
> spring-cloud：Hoxton.SR8
> spring-cloud-alibaba：2.2.5.RELEASE
> 使用-Dcsp.sentinel.app.type=1无法标识gateway

先标记再启动 sentinel-dashboard 才能生效
