### ISSUE TITLE
is spring-cloud-starter-alibaba-sentinel(2.1.3.RELEASE) compatible with sentinel-core(1.8.1)?

### ISSUE THREAD

**Issue by yazong** [alibaba/spring-cloud-alibaba#1987]
**Which Component**

Sentinel

**Describe what problem you have encountered**

The default value used by spring-cloud-starter-alibaba-sentinel(2.1.3.RELEASE) with sentinel-core(1.8.0).
Can i replace sentinel-core(1.8.0) with sentinel-core(1.8.1) in pom.xml?

**Describe what information you have read**

**Comment by yazong** [comment]
spring-cloud-starter-alibaba-sentinel(2.1.4.RELEASE) is in maven-repo,but spring-cloud-starter-alibaba-sentinel(2.1.4.RELEASE) is not it github?

**Comment by yazong** [comment]
> spring-cloud-starter-alibaba-sentinel(2.1.4.RELEASE) is in maven-repo,but spring-cloud-starter-alibaba-sentinel(2.1.4.RELEASE) is not it github?

that's the second question.

**Comment by yuhuangbin** [comment]
refer #1971

**Comment by yazong** [comment]
> refer #1971

i'm talking about version 2.1.3.RELEASE.  the version you mentioned is  2.2.6-SNAPSHOT.  
can sentinel-core(1.8.1) be used in both verions?

**Comment by yazong** [comment]
> > spring-cloud-starter-alibaba-sentinel(2.1.4.RELEASE) is in maven-repo,but spring-cloud-starter-alibaba-sentinel(2.1.4.RELEASE) is not it github?
> 
> that's the second question.

@yuhuangbin
