### ISSUE TITLE
升级到spring cloud 2020.0.1之后，sentinel与openfeign启动报异常 Requested bean is currently in creation: Is there an unresolvable circular reference?

### ISSUE THREAD

**Issue by dpengjianjun** [alibaba/spring-cloud-alibaba#1990]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by HashZhang** [comment]
I found there were some incompatible parts between `Spring-Cloud-Alibaba 2.2.5-RELEASE` and `spring cloud 2020.0.1`. So I suggest you waiting for next version of `Spring-Cloud-Alibaba`

**Comment by HashZhang** [comment]
Related pull request: https://github.com/alibaba/spring-cloud-alibaba/pull/1978

**Comment by fevenor** [comment]
> I found there were some incompatible parts between `Spring-Cloud-Alibaba 2.2.5-RELEASE` and `spring cloud 2020.0.1`. So I suggest you waiting for next version of `Spring-Cloud-Alibaba`

Is there any release plan for next version?

**Comment by theonefx** [comment]
We released the 2020.0.RC1 version, welcome to try.
