### ISSUE TITLE
生成错误的基础包

### ISSUE THREAD

**Issue by hesixian123** [alibaba/spring-cloud-alibaba#1998]
生成的脚手架，基础包都是 com/example/demo

**Comment by ppzzyy11** [comment]
![image](https://user-images.githubusercontent.com/20295482/112129836-c94caa00-8c02-11eb-829b-af0384ea5e33.png)
https://start.aliyun.com/bootstrap.html/#!type=maven-project&language=java&architecture=mvc&platformVersion=2.3.7.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example123&artifactId=demo123123123123123123&name=demo123123123123123123&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example123.demo123123123123123123&dependencies=web,thymeleaf,h2,mybatis,commons-io&demos=web,jackson,mybatis

没有复线，可以在下图地方gai改
![image](https://user-images.githubusercontent.com/20295482/112129953-e2555b00-8c02-11eb-8751-ce4209ce0657.png)

**Comment by hesixian123** [comment]
对于有关键字的包名，会出现那个问题（包名为默认的com.example.demo），个人认为给个提示比较好。^v^








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月23日(星期二) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] 生成错误的基础包 (#1998)





 

 https://start.aliyun.com/bootstrap.html/#!type=maven-project&amp;language=java&amp;architecture=mvc&amp;platformVersion=2.3.7.RELEASE&amp;packaging=jar&amp;jvmVersion=1.8&amp;groupId=com.example123&amp;artifactId=demo123123123123123123&amp;name=demo123123123123123123&amp;description=Demo%20project%20for%20Spring%20Boot&amp;packageName=com.example123.demo123123123123123123&amp;dependencies=web,thymeleaf,h2,mybatis,commons-io&amp;demos=web,jackson,mybatis
 
没有复线，可以在下图地方gai改
