### ISSUE TITLE
Can we distinguish Dubbo and spingcloud services by metadata in Nacos?

### ISSUE THREAD

**Issue by novayoung** [alibaba/spring-cloud-alibaba#2000]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
Can we distinguish Dubbo and spingcloud services by metadata in Nacos?

**Describe what information you have read**

**Comment by theonefx** [comment]
I don't quite understand your needs, can you describe it in more detail

**Comment by novayoung** [comment]
> I don't quite understand your needs, can you describe it in more detail
If I want to synchronize Nacos service data to other registries (such as zookeeper), I need to know whether the data is Dubbo or Spring Cloud.

**Comment by theonefx** [comment]
which “Nacos service data” you want to synchronize？Could you please provide some samples？

**Comment by novayoung** [comment]
I already have a solution, thanks
