### ISSUE TITLE
希望能增加对MyBatisPlus的支持

### ISSUE THREAD

**Issue by ZoolYe** [alibaba/spring-cloud-alibaba#2002]
#### 希望能增加对`MyBatisPlus`的支持，希望脚手架生成项目代码时候，能允许选择`MyBatisPlus`替换`MyBatis`
***I hope to add support for `mybatis plus`. I hope that when scaffolding generates project code, `mybatis plus` can be selected to replace `mybatis`***

**Comment by ppzzyy11** [comment]
已添加
