### ISSUE TITLE
No provider available from registry http::9090 for service xxx/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0 on consumer 192.168.50.205 use dubbo version 2.7.6, please check status of providers(disabled, not registered or in blacklist).

### ISSUE THREAD

**Issue by zzwangxin** [alibaba/spring-cloud-alibaba#2007]
Which Component
Eureka 或者Nacos Discovery, Dubbo

Describe the bug

nacos或者eureka作为服务注册中心，服务A订阅了B服务，服务B订阅了C、D服务，当D服务Down机，会导致A调用B，B调用C服务出现“No provider available”，反之C服务Down机也会有这种问题

Nacos or Eureka is the service registry. Service a subscribes to service B, and service B subscribes to services C and D. when service d is down, a calls B, and B calls C, and "no provider available" occurs. Otherwise, service C is down

服务提供方配置B：
Service provider configuration B:

dubbo:
  cloud:
    subscribed-services: 'C,D'
  consumer:
    check: false
    client: netty
    retries: 0
    threadpool: fixed
    threads: 200
    queues: 0
    loadbalance: 'roundrobin'
    init: true

  scan:
    base-packages: cn.retail.product
  protocol:
    name: dubbo
    port: 20900
    client: netty
    server: netty
    serialization: hessian2
    charset: utf-8
    threadpool: fixed
    threads: 200
    queues: 0
    iothreads: 9
    buffer: 8192
    accepts: 1000
    payload: 8388608
    dispatcher: all

  registry:
    check: false
    file: './dubbo/dubbo-registry-product-service.cache'
    address: 'spring-cloud://192.168.30.221'
    port: 32505

  provider:
    filter: '-exception'
    loadbalance: 'roundrobin'
    cluster: 'failover'

服务消费者A：
Service consumer A:

dubbo:
  cloud:
    subscribed-services: 'B'
  consumer:
    check: false
    client: netty
    retries: 0
    threadpool: fixed
    threads: 200
    queues: 0
    loadbalance: 'roundrobin'

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    enabled: true
    registry-fetch-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 5
    service-url:
      defaultZone:'http://192.168.30.221:32505/eureka/,http://192.168.30.221:32506/eureka/,http://192.168.30.221:32507/eureka/'

不清楚，是否为springcloud alibaba duboo  bug导致

I don't know if it is caused by the springcloud Alibaba dubbo bug

**Comment by theonefx** [comment]
能否通过一下，你所使用的  Spring Cloud Alibaba 的版本号？
nacos 和 eureka 作为注册中心，都有这个问题吗？

**Comment by zzwangxin** [comment]
springcloud   Greenwich.RELEASE
spring boot 2.1.8.RELEASE
springcloud alibaba 2.1.2.RELEASE

**Comment by zzwangxin** [comment]
> 能否通过一下，你所使用的 Spring Cloud Alibaba 的版本号？
> nacos 和 eureka 作为注册中心，都有这个问题吗？


springcloud Greenwich.RELEASE
spring boot 2.1.8.RELEASE
springcloud alibaba 2.1.2.RELEASE

nacos 和 eureka 都有这个问题，而且升级至最新springcloud alibaba dubbo也有同样问题

**Comment by theonefx** [comment]
按照你的描述，如果D下线了，那么B调用D出现 No Provider 是正常的，然后这个异常顺着调用返回到了最前端的 A 也是正常的呀

**Comment by zzwangxin** [comment]
> 按照你的描述，如果D下线了，那么B调用D出现 No Provider 是正常的，然后这个异常顺着调用返回到了最前端的 A 也是正常的呀

按我的描述，B访问C应该正常，因为C没有Down，但是现在没有

**Comment by theonefx** [comment]
B->C 和 B->D 在一个调用链路上吗？

**Comment by zzwangxin** [comment]
> B->C 和 B->D 在一个调用链路上吗？

什么意思？

**Comment by theonefx** [comment]
一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？

**Comment by zzwangxin** [comment]
> 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？

独立，互相不影响。

**Comment by theonefx** [comment]
> > 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？
> 
> 独立，互相不影响。

那，看来这是个问题，我们会尽快处理一下

**Comment by zzwangxin** [comment]
请问是什么问题，需要怎么修复呢，因为我们现在的版本是
springcloud Greenwich.RELEASE
spring boot 2.1.8.RELEASE
springcloud alibaba 2.1.2.RELEASE
现有版本不想做升级，是否可以提供一个补丁（Java文件）进行修复

**Comment by zzwangxin** [comment]
> > > 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？
> > 
> > 
> > 独立，互相不影响。
> 
> 那，看来这是个问题，我们会尽快处理一下

请问是什么问题，需要怎么修复呢，因为我们现在的版本是
springcloud Greenwich.RELEASE
spring boot 2.1.8.RELEASE
springcloud alibaba 2.1.2.RELEASE
现有版本不想做升级，是否可以提供一个补丁（Java文件）进行修复

**Comment by zzwangxin** [comment]
> > > 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？
> > 
> > 
> > 独立，互相不影响。
> 
> 那，看来这是个问题，我们会尽快处理一下

**Comment by zzwangxin** [comment]
> > > 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？
> > 
> > 
> > 独立，互相不影响。
> 
> 那，看来这是个问题，我们会尽快处理一下

可以提供修复给我们现在使用版本吗？

**Comment by theonefx** [comment]
> > > > 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？
> > > 
> > > 
> > > 独立，互相不影响。
> > 
> > 
> > 那，看来这是个问题，我们会尽快处理一下
> 
> 可以提供修复给我们现在使用版本吗？

我们会尽快修复这个问题，你可以期待下一个版本

**Comment by wghdir** [comment]
这个No Privoder一直存在，有时在k8s上伸缩服务的时候，突然就有的consumer就会提示这个，不管等多久都不能调用成功，只有把consumer重启一下，再调就正常。

**Comment by BuYi-Feng** [comment]
> > > > > 一次调用，是先经过了 B->C 然后再经过 B->D ？还是说 B->C 与 B->D 是独立的？
> > > > 
> > > > 
> > > > 独立，互相不影响。
> > > 
> > > 
> > > 那，看来这是个问题，我们会尽快处理一下
> > 
> > 
> > 可以提供修复给我们现在使用版本吗？
> 
> 我们会尽快修复这个问题，你可以期待下一个版本

这个问题什么时候解决呢，现在我们服务端一重启，其他的项目也必须跟着重启，很影响发布流程啊~~

**Comment by ms20hj** [comment]
我也是突然遇到这个问题，把注册中心从nacos切换成zk，早上正常的，下午又不正常了。后面把该提交的代码提交一下，然后把本地代码删掉，从Git上从新拉取下来又正常了。
        <spring-boot.version>2.1.18.RELEASE</spring-boot.version>
        <spring-cloud.version>Greenwich.SR6</spring-cloud.version>
        <spring-cloud-alibaba.version>2.1.2.RELEASE</spring-cloud-alibaba.version>
        <dubbo.version>2.7.8</dubbo.version>

**Comment by theonefx** [comment]
https://github.com/alibaba/spring-cloud-alibaba/pull/2101
这个PR，优化了服务发现的逻辑，使用revision来避免很多重复的调用

**Comment by cai-ti** [comment]
> #2101
> 这个PR，优化了服务发现的逻辑，使用revision来避免很多重复的调用
springcloud Hoxton.SR10
spring boot 2.3.3.RELEASE
springcloud alibaba 2.2.5.RELEASE
这个在不升级的情况下怎么使用?我把你pr的那些文件都赋值到我本地了，消费端启动的时候就直接报No provider available from registry了

**Comment by cai-ti** [comment]
springcloud Hoxton.SR10
spring boot 2.3.3.RELEASE
springcloud alibaba 2.2.5.RELEASE

我本地下载master分支代码下来打包引入消费端也是启动不了

**Comment by theonefx** [comment]
> springcloud Hoxton.SR10
> spring boot 2.3.3.RELEASE
> springcloud alibaba 2.2.5.RELEASE
> 
> 我本地下载master分支代码下来打包引入消费端也是启动不了

你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了

**Comment by cai-ti** [comment]
> > springcloud Hoxton.SR10
> > spring boot 2.3.3.RELEASE
> > springcloud alibaba 2.2.5.RELEASE
> > 我本地下载master分支代码下来打包引入消费端也是启动不了
> 
> 你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了

我这按你说的引入 2.2.6-bugfix4-SNAPSHOT ，消费端启动直接就报Failed to check the status of the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService. No provider available for the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=base-gateway了
服务提供端是正常启动的

**Comment by cai-ti** [comment]
> > springcloud Hoxton.SR10
> > spring boot 2.3.3.RELEASE
> > springcloud alibaba 2.2.5.RELEASE
> > 我本地下载master分支代码下来打包引入消费端也是启动不了
> 
> 你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了

我这按你说的引入 2.2.6-bugfix4-SNAPSHOT ，消费端启动直接就报Failed to check the status of the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService. No provider available for the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=base-gateway了
服务提供端是正常启动的

**Comment by theonefx** [comment]
> > > springcloud Hoxton.SR10
> > > spring boot 2.3.3.RELEASE
> > > springcloud alibaba 2.2.5.RELEASE
> > > 我本地下载master分支代码下来打包引入消费端也是启动不了
> > 
> > 
> > 你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了
> 
> 我这按你说的引入 2.2.6-bugfix4-SNAPSHOT ，消费端启动直接就报Failed to check the status of the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService. No provider available for the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=base-gateway了
> 服务提供端是正常启动的

能否提供一下你的配置方式？如果内容多单独发我邮箱也可以

**Comment by cai-ti** [comment]
> > > > springcloud Hoxton.SR10
> > > > spring boot 2.3.3.RELEASE
> > > > springcloud alibaba 2.2.5.RELEASE
> > > > 我本地下载master分支代码下来打包引入消费端也是启动不了
> > > 
> > > 
> > > 你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了
> > 
> > 
> > 我这按你说的引入 2.2.6-bugfix4-SNAPSHOT ，消费端启动直接就报Failed to check the status of the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService. No provider available for the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=base-gateway了
> > 服务提供端是正常启动的
> 
> 能否提供一下你的配置方式？如果内容多单独发我邮箱也可以

提供者配置
dubbo:
  scan:
    base-packages: com.syiti.dev.base.**.provider
  cloud:
    subscribed-services: ''
  application:
    name: ${spring.application.name}
  protocols:
    dubbo:
      name: dubbo
      port: -1
      threads: 2000
  provider:
    retries: 0
    timeout: 2000
    version: 1.0.0
  consumer:
    retries: 0
    timeout: 2000

消费者配置
dubbo:
  cloud:
    subscribed-services: 'base-app'
  application:
    name: ${spring.application.name}
  protocols:
    dubbo:
      name: dubbo
      port: -1
      threads: 1000
  provider:
    retries: 0
    timeout: 2000
    version: 1.0.0
  consumer:
    retries: 0
    timeout: 2000

这个配置在2.2.5.RELEASE版本是能使用的，换2.2.6-bugfix4-SNAPSHOT 消费者者启动久报错了

**Comment by cai-ti** [comment]
> > > > springcloud Hoxton.SR10
> > > > spring boot 2.3.3.RELEASE
> > > > springcloud alibaba 2.2.5.RELEASE
> > > > 我本地下载master分支代码下来打包引入消费端也是启动不了
> > > 
> > > 
> > > 你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了
> > 
> > 
> > 我这按你说的引入 2.2.6-bugfix4-SNAPSHOT ，消费端启动直接就报Failed to check the status of the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService. No provider available for the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=base-gateway了
> > 服务提供端是正常启动的
> 
> 能否提供一下你的配置方式？如果内容多单独发我邮箱也可以

sca dubbo已经用了很久了，还一直用的dubbo的注册的方式
dubbo:
  application:
    name: ${spring.application.name}
  registries:
    nacos:
      address: nacos://${nacos.host}:${nacos.port}?username=${nacos.username}&password=${nacos.password}&namespace=${nacos.rpc-namespace}

这个方式接口多启动会比dubbo-cloud://注册的慢很多

**Comment by cai-ti** [comment]
> > > > springcloud Hoxton.SR10
> > > > spring boot 2.3.3.RELEASE
> > > > springcloud alibaba 2.2.5.RELEASE
> > > > 我本地下载master分支代码下来打包引入消费端也是启动不了
> > > 
> > > 
> > > 你可以直接用 2.2.6-bugfix4-SNAPSHOT 试一下，这个是包含了 #2101 的版本，已经给一些小伙伴测试并确认能解决问题了
> > 
> > 
> > 我这按你说的引入 2.2.6-bugfix4-SNAPSHOT ，消费端启动直接就报Failed to check the status of the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService. No provider available for the service com.syiti.dev.base.system.rpc.api.api.BaseApiRpcService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=base-gateway了
> > 服务提供端是正常启动的
> 
> 能否提供一下你的配置方式？如果内容多单独发我邮箱也可以

sca dubbo已经用了很久了，还一直用的dubbo的注册的方式
dubbo:
  application:
    name: ${spring.application.name}
  registries:
    nacos:
      address: nacos://${nacos.host}:${nacos.port}?username=${nacos.username}&password=${nacos.password}&namespace=${nacos.rpc-namespace}

这个方式接口多启动会比dubbo-cloud://注册的慢很多

**Comment by theonefx** [comment]
@cai-ti 我参照你的配置在我的demo工程中，并不能重现你的问题，我的配置贴在后面。
可能的区别是 dubbo.consumer.check=false 我打开了，不过这个配置无论是否打开，都不影响结果。
所以，能否辛苦提供一个可以复现这个的样例工程？
非常期待你的回复

```yaml
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    health:
      show-details: always

dubbo:
  cloud:
    subscribed-services: provider1,provider2
  scan:
    base-packages: com.example.consumer
  application:
    name: ${spring.application.name}
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  provider:
    retries: 0
    timeout: 2000
    version: 1.0.0
  consumer:
    retries: 0
    timeout: 2000
    check: false
```

**Comment by cai-ti** [comment]
> @cai-ti 我参照你的配置在我的demo工程中，并不能重现你的问题，我的配置贴在后面。
> 可能的区别是 dubbo.consumer.check=false 我打开了，不过这个配置无论是否打开，都不影响结果。
> 
> 另外，你后来说是用 dubbo 直接连接 nacos 而不是使用 sca 的注册中心，如果是这样配置的话，等于整个注册逻辑全部在 dubbo 内部，这个跟 sca 应该没什么关系了。由于 dubbo 使用的是接口维度的注册，所以速度上会比 sca 应用维度的注册慢一些，这个现象是正常的。
> 
> 所以，能否辛苦提供一个可以复现这个的样例工程？
> 非常期待你的回复
> 
> ```yaml
> spring:
>   application:
>     name: consumer
>   cloud:
>     nacos:
>       discovery:
>         username: nacos
>         password: nacos
>         server-addr: 127.0.0.1:8848
>         namespace: public
> 
> server:
>   port: 8080
> 
> management:
>   server:
>     port: 8081
>   endpoints:
>     jmx:
>       exposure:
>         include: "*"
>     web:
>       exposure:
>         include: "*"
>     health:
>       show-details: always
> 
> dubbo:
>   cloud:
>     subscribed-services: provider1,provider2
>   scan:
>     base-packages: com.example.consumer
>   application:
>     name: ${spring.application.name}
>   protocol:
>     id: dubbo
>     name: dubbo
>     port: -1
>   provider:
>     retries: 0
>     timeout: 2000
>     version: 1.0.0
>   consumer:
>     retries: 0
>     timeout: 2000
>     check: false
> ```

好的，我抽个时间写一个最简的样例工程

**Comment by cai-ti** [comment]
> @cai-ti 我参照你的配置在我的demo工程中，并不能重现你的问题，我的配置贴在后面。
> 可能的区别是 dubbo.consumer.check=false 我打开了，不过这个配置无论是否打开，都不影响结果。
> 
> 另外，你后来说是用 dubbo 直接连接 nacos 而不是使用 sca 的注册中心，如果是这样配置的话，等于整个注册逻辑全部在 dubbo 内部，这个跟 sca 应该没什么关系了。由于 dubbo 使用的是接口维度的注册，所以速度上会比 sca 应用维度的注册慢一些，这个现象是正常的。
> 
> 所以，能否辛苦提供一个可以复现这个的样例工程？
> 非常期待你的回复
> 
> ```yaml
> spring:
>   application:
>     name: consumer
>   cloud:
>     nacos:
>       discovery:
>         username: nacos
>         password: nacos
>         server-addr: 127.0.0.1:8848
>         namespace: public
> 
> server:
>   port: 8080
> 
> management:
>   server:
>     port: 8081
>   endpoints:
>     jmx:
>       exposure:
>         include: "*"
>     web:
>       exposure:
>         include: "*"
>     health:
>       show-details: always
> 
> dubbo:
>   cloud:
>     subscribed-services: provider1,provider2
>   scan:
>     base-packages: com.example.consumer
>   application:
>     name: ${spring.application.name}
>   protocol:
>     id: dubbo
>     name: dubbo
>     port: -1
>   provider:
>     retries: 0
>     timeout: 2000
>     version: 1.0.0
>   consumer:
>     retries: 0
>     timeout: 2000
>     check: false
> ```

这是我去掉大部分依赖之后写的一个示例，是可以复现问题的，同样的配置2.2.5是可以正常启动访问的https://gitee.com/vip_caiti/sca-dubbo-bug-example

**Comment by cai-ti** [comment]
这是复现示例工程https://gitee.com/vip_caiti/sca-dubbo-bug-example------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月22日(星期二) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] No provider available from registry http::9090 for service xxx/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0 on consumer 192.168.50.205 use dubbo version 2.7.6, please check status of providers(disabled, not registered or in blacklist). (#2007)

**Comment by theonefx** [comment]
感谢，我好像找到问题了，跟 DubboCloudRegistry 的初始化顺序有关系，稍等一下，我处理一下，非常感谢

**Comment by theonefx** [comment]
@cai-ti 刚才发布了一个新的 2.2.6-bugfix5-SNAPSHOT，解决了这个问题，你可以试一下，相关的 PR 是 https://github.com/alibaba/spring-cloud-alibaba/pull/2120

**Comment by theonefx** [comment]
2.2.6.RC1 应发布了，欢迎大家试用，该问题已经在这个版本中得到修复了

**Comment by ufwq** [comment]
2.2.6.RC1还是存在问题

**Comment by tan-zhuo** [comment]
你们是不是在调试时几个相互订阅服务同时启动？

**Comment by tan-zhuo** [comment]
根据我调试结果得出、几个服务在同时启动时、先启动好的服务注册入nacos之后、nacos并不会通知正在**注册中**的服务、服务变更事件、从而导致后注册上的服务没有获取到最新的订阅服务信息。

**Comment by tan-zhuo** [comment]
为了避免在注册中途有订阅服务注册上nacos却没有通知到本服务、故此我在服务启动之后会主动去发起一次订阅服务更新事件、经过测试之后已经解决此问题。

@Slf4j
@Component
public class CustomDubboActiveProbeSubscriptionService implements ApplicationListener<ApplicationReadyEvent> {

    @Override
    public void onApplicationEvent(ApplicationReadyEvent event) {
        DubboServiceMetadataRepository dubboServiceMetadataRepository = event.getApplicationContext().getBean(DubboServiceMetadataRepository.class);
        Set<String> subscribedServices = dubboServiceMetadataRepository.getSubscribedServices();
        if (!ObjectUtils.isEmpty(subscribedServices)) {
            DiscoveryClient DiscoveryClient = event.getApplicationContext().getBean(DiscoveryClient.class);
            for (String subscribedService : subscribedServices) {
                log.info("主动探测订阅服务:" + subscribedService);
                ServiceInstancesChangedEvent changedEvent = new ServiceInstancesChangedEvent(subscribedService, DiscoveryClient.getInstances(subscribedService));
                event.getApplicationContext().publishEvent(changedEvent);
            }
        }
    }

}
