### ISSUE TITLE
Parameter 0 of method ribbonServerList in com.alibaba.cloud.nacos.ribbon.NacosRibbonClientConfiguration required a bean of type 'com.netflix.client.config.IClientConfig' that could not be found.

### ISSUE THREAD

**Issue by hupanfeng** [alibaba/spring-cloud-alibaba#2008]
**Which Component**
 Nacos Discovery,

**Describe the bug**

Parameter 0 of method ribbonServerList in com.alibaba.cloud.nacos.ribbon.NacosRibbonClientConfiguration required a bean of type 'com.netflix.client.config.IClientConfig' that could not be found.
--按照官方手册改成以下版本后，有些模块可以了，但依然有些模块报上面的做错误
spring-boot:2.3.5
spring-cloud:Hoxton.SR8
spring-cloud-starter-alibaba-nacos-config:2.2.5.RELEASE
spring-cloud-starter-alibaba-nacos-discovery:2.2.5.RELEASE

@ComponentScan(basePackages = "com.inspur")
--我对比了下，不行的模块（微服务）报错的地方是NacosRibbonClientConfiguration的ribbonServerList方法，而不报错的模块根本不会进这个方法，这就奇怪了，为什么有些模块会进这个方法而有些模块不进？
@Bean
	@ConditionalOnMissingBean
	public ServerList<?> ribbonServerList(IClientConfig config,
			NacosDiscoveryProperties nacosDiscoveryProperties) {
		if (this.propertiesFactory.isSet(ServerList.class, config.getClientName())) {
			ServerList serverList = this.propertiesFactory.get(ServerList.class, config,
					config.getClientName());
			return serverList;
		}
		NacosServerList serverList = new NacosServerList(nacosDiscoveryProperties);
		serverList.initWithNiwsConfig(config);
		return serverList;
	}

**Comment by theonefx** [comment]
Can you upgrade to 2.1.4.RELEASE and try again if there are still problems?

**Comment by hupanfeng** [comment]
No ok

**Comment by hupanfeng** [comment]
找到原因了，竟然是阿里云的sdk跟nacos冲突。引这几个包后就不行了：
<dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-dysmsapi</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-dyvmsapi</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-core</artifactId>
        </dependency>

**Comment by hupanfeng** [comment]
解决的办法是：不要直接使用aliyun-java-sdk-dysmsapi,使用下面的依赖才行 
 <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alicloud-sms</artifactId>
                <version>2.2.0.RELEASE</version>
            </dependency>

**Comment by HaojunRen** [comment]
Close this issue first. If any problems, please reopen it
