### ISSUE TITLE
在nacos的服务列表中sidecar的服务会有2个实例

### ISSUE THREAD

**Issue by sishidadao-aft** [alibaba/spring-cloud-alibaba#2009]
<img width="809" alt="服务列表" src="https://user-images.githubusercontent.com/81454172/112708125-2b4f2d00-8eeb-11eb-847d-6fec87a85e9b.PNG">

<img width="785" alt="集群" src="https://user-images.githubusercontent.com/81454172/112708160-710bf580-8eeb-11eb-9d36-aa1816ac0896.PNG">

**Comment by theonefx** [comment]
能否提供一下复现的步骤？

**Comment by lltx** [comment]
说明一下你的版本 ，这个已经修复了 

你可以尝试使用 新版本 复测一下
