### ISSUE TITLE
想要关闭某个input不让他接收消息。或者让这个input只接受某个tag的消息要怎么配置

### ISSUE THREAD

**Issue by wrj15034011352** [alibaba/spring-cloud-alibaba#2010]
spring.cloud.stream.rocketmq.bindings.iutput1.consumer.enabled=false

spring.cloud.stream.rocketmq.bindings.iutput1.consumer.tags=ttt

我使用这两个配置 都进行了测试 均不生效
想问要怎么设置才可以
使用的是2.2.0.RELEASE版本

**Comment by zkzlx** [comment]
https://github.com/alibaba/spring-cloud-alibaba/pull/2013
已在上面的PR解决，由于此次修改较多，故会先拉取一个新分支，后续会有rocketmq单独对应的RC包出来

**Comment by zkzlx** [comment]
please use the new version #2029
