### ISSUE TITLE
SentinelFeign 报错

### ISSUE THREAD

**Issue by leshalv** [alibaba/spring-cloud-alibaba#2019]
FeignClientFactoryBean feignClientFactoryBean = (FeignClientFactoryBean) def.getAttribute("feignClientsRegistrarFactoryBean");

获取 FeignClientFactoryBean  null 
版本 spring cloud 2020.0.0
spring cloud alibaba  2020.0.RC1 
spring boot 2.2.4

**Comment by theonefx** [comment]
能否描述一下你的使用场景？

**Comment by theonefx** [comment]
我在2020.0 分支上测试了一下，sentinel 的案例都是ok 的
我先把这个 issue 关闭了，如果有更多的信息，辛苦待上更多明细场景再发一个 issue
