### ISSUE TITLE
NacosConfigProperties bean properties init error

### ISSUE THREAD

**Issue by litairan1995** [alibaba/spring-cloud-alibaba#2023]
NacosConfigProperties  bean 在第一次初始化的时候没有成功注入 serverAddr 。从environment中没有获取到${spring.cloud.nacos.config.server-addr:} 这个的值。导致在ServerHttpAgent.serverListMgr中获取到的只有默认的localhost:8848这个地址。

NacosConfigProperties  bean  the injection was not successful on the first initialization serverAddr , 
Did not get from the environment to ${spring.cloud.nacos.config.server-addr:}  this value.Result in ServerHttpAgent. serverListMgr access to only the default in localhost: 8848 this address.

![图片](https://user-images.githubusercontent.com/50817193/113655441-6102cb80-96cc-11eb-8bd1-19781e27b2a9.png)

![图片](https://user-images.githubusercontent.com/50817193/113655195-f2257280-96cb-11eb-841c-269c02d2e46d.png)

导致 ClientWorker在启动线程LongPollingRunnable请求的地址错误

nacos-version 2.2.5.RELEASE

**Comment by guerlab** [comment]
配置文件的名称是否正确？

**Comment by litairan1995** [comment]
文件的名称我贴了截图，我也检查了和他从环境中获取的名称是一致的。

**Comment by guerlab** [comment]
bootstrap.yml或者bootstrap.properties？？？

spring cloud使用的哪个版本？

**Comment by litairan1995** [comment]
我用的是application.yml。springcloud的版本是2.2.2.RELEASE。

**Comment by guerlab** [comment]
spring cloud里边是优先加载bootstrap.yml   推荐nacos的配置写到bootstrap.yml里边去

**Comment by litairan1995** [comment]
好的我改下。但是我只配置了一个application.yml文件，在没有其他的配置文件了
