### ISSUE TITLE
[Announce] Spring Cloud Alibaba 2021.1 released

### ISSUE THREAD

**Issue by theonefx** [alibaba/spring-cloud-alibaba#2027]
Hello Community,

I am glad to announce that Spring Cloud Alibaba 2021.1 is released.

You can check detailed release notes here:

2021.1 : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2021.1

This release builds on 2.2.5.Release and completes the Spring Cloud 2020.0 adaptation.
And this is the first version that supports the 2020 version of spring cloud.

Also, you may be confused about the version number.
2021.1 means this is our first official release in 2021.

If you have any questions using this version, please report the issue on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by FreeSaltedFish** [comment]
nacos的依赖没有升级到2.0

**Comment by jinshengyong** [comment]
> nacos的依赖没有升级到2.0吗

## 可以自行升级，不影响，我实践过的

**Comment by techa03** [comment]
请问新版nacos配置中心如何使用，升级后拉取不到配置

**Comment by zhangran2616** [comment]
update wiki version dependency

**Comment by lltx** [comment]
> > nacos的依赖没有升级到2.0吗
> 
> ## 可以自行升级，不影响，我实践过的

或许会遇到这个问题 https://github.com/alibaba/nacos/issues/5327

**Comment by theonefx** [comment]
> nacos的依赖没有升级到2.0吗

我们会在下一个版本，将相关组件的版本做一次全面的升级。包括 nacos、dubbo 等等

**Comment by theonefx** [comment]
> update wiki version dependency

We will update it as soon as possible

**Comment by gmymengyuan** [comment]
### please update wiki version dependency

**Comment by theonefx** [comment]
> ### please update wiki version dependency

done

**Comment by theonefx** [comment]
> update wiki version dependency

done

**Comment by zhangran2616** [comment]
> > update wiki version dependency
> 
> done

thx

**Comment by FreeSaltedFish** [comment]
> > nacos的依赖没有升级到2.0吗
> 
> 我们会在下一个版本，将相关组件的版本做一次全面的升级。包括nacos，dubbo等等

大概要多久那，太久了我就先自行升级了

**Comment by theonefx** [comment]
> > > nacos的依赖没有升级到2.0吗
> > 
> > 
> > 我们会在下一个版本，将相关组件的版本做一次全面的升级。包括nacos，dubbo等等
> 
> 大概要多久那，太久了我就先自行升级了

预计要到5月份，因为除了单纯升级版本号，还会有一波优化

**Comment by winterallen** [comment]
> > > > nacos的依赖没有升级到2.0吗
> > > 
> > > 
> > > 我们会在下一个版本，将相关组件的版本做一次全面的升级。包括nacos，dubbo等等
> > 
> > 
> > 大概要多久那，太久了我就先自我升级了
> 
> 预计要到5月份，因为除了单纯升级版本号，然后还要波优化

springcloud alibaba dubbo 服务端重启，消费端报：No provider available from registry localhost:9090 for service这个问题也会解决掉吗，现在使用的是2.7.8版本，SCA是2.2.5.RELEASE

**Comment by Burutiaowuhh** [comment]
@theonefx 官方能看看这个问题么https://github.com/alibaba/spring-cloud-alibaba/issues/2047#issue-864609552

**Comment by shihuaguo** [comment]
> > > > nacos的依赖没有升级到2.0吗
> > > 
> > > 
> > > 我们会在下一个版本，将相关组件的版本做一次全面的升级。包括nacos，dubbo等等
> > 
> > 
> > 大概要多久那，太久了我就先自行升级了
> 
> 预计要到5月份，因为除了单纯升级版本号，还会有一波优化

大概会有哪些组件升级？因为5月份应该是springboot例行发布新版本（2.5）的时间，到时候会包含这个升级吗？

**Comment by spinachomes** [comment]
依赖缺少bootstrap，使用spring cloud 2020.x得加上

**Comment by mostcool** [comment]
> > update wiki version dependency
> 
> We will update it as soon as possible

还没有计划安排吗？

**Comment by mostcool** [comment]
> > > > nacos的依赖没有升级到2.0吗
> > > 
> > > 
> > > 我们会在下一个版本，将相关组件的版本做一次全面的升级。包括nacos，dubbo等等
> > 
> > 
> > 大概要多久那，太久了我就先自行升级了
> 
> 预计要到5月份，因为除了单纯升级版本号，还会有一波优化

这都7月份了呢，还没计划安排吗？
