### ISSUE TITLE
【2021.1】不访问Nacos配置问题   NacosConfigAutoConfiguration   context.getParent()==null 

### ISSUE THREAD

**Issue by letian-tang** [alibaba/spring-cloud-alibaba#2032]
**spring-cloud-alibaba  2021.1  spring-boot2.4.2**

NacosConfigAutoConfiguration.java  line 38  
context.getParent()==null    is  true 
Leading to direct return   new NacosConfigProperties()

NacosConfigAutoConfiguration 38行，context.getParent()==null   导致直接返回 new NacosConfigProperties()，而不去访问远程nacos配置中心

**Comment by oSunnyo** [comment]
同样的问题，没有访问远端的配置中心。

**Comment by letian-tang** [comment]
原因找到了，需要引入
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>

**Comment by theonefx** [comment]
因为springboot 2.4 版本去掉了默认的 bootstrap 功能，这部分功能现在需要单独引入。后续的版本，我们会把这个依赖加回框架的依赖里。
