### ISSUE TITLE
@SentinelRestTemplate fallback doesn't work and NullPointerException throws

### ISSUE THREAD

**Issue by topsoft-support** [alibaba/spring-cloud-alibaba#2044]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Sentinel
**Describe the bug**
The RestTempte configuration:
```kotlin
@Bean
@LoadBalanced
@SentinelRestTemplate(blockHandler = "handleBlock", blockHandlerClass = RestTemplateBlock::class, fallback = "handleFallback", fallbackClass = RestTemplateFallback::class)
open fun restTemplate(clientHttpRequestFactory: ClientHttpRequestFactory): RestTemplate {
	val restTemplate = RestTemplate(clientHttpRequestFactory)
	restTemplate.messageConverters.add(MappingJackson2HttpMessageConverterImpl())
	return restTemplate
}
```
fallbackClass Configuration:
```kotlin
class RestTemplateFallback {
    companion object {
        @JvmStatic
        fun handleFallback(request: HttpRequest, body: ByteArray, execution: ClientHttpRequestExecution, exception: BlockException): ClientHttpResponse {
            println(">>> RestTemplateFallback.handleFallback")
            return SentinelClientHttpResponse()
        }
    }
}
```
The service `service-res` doesn't exist or already offline .
```kotlin
 val resp = restTemplate.getForEntity("http://service-res/res/api/ms/app", Result::class.java)
```

The `NullPointerException`  occured:
```
java.lang.NullPointerException: null
	at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:64) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:807) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.5.jar:5.3.5]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361) ~[spring-web-5.3.5.jar:5.3.5]
```
I trace the class `SentinelProtectInterceptor.intercept`
found that the exception has be catched and the `IllegalStateException` is not BlockException, so it do nothing.
`java.lang.IllegalStateException: No instances available for service-res`
![image](https://user-images.githubusercontent.com/53323942/115369581-dad1a380-a1fa-11eb-9853-3f9b17e54703.png)

I think that `sentinel` with `openfeign` work fine, why `RestTemplate` not,and I saw the `SentinelInvocationHandler`'s process:

![image](https://user-images.githubusercontent.com/53323942/115369807-0eacc900-a1fb-11eb-9b0f-30f90e6003bb.png)

I am confused !!!

I configed the `SentinelRestTemplate` `fallbackClass`, if can't access the service ,it shouldn't run the method `handleFallback`?

```
<org.springframework.boot.version>2.4.4</org.springframework.boot.version>
<org.springframework.data.version>2.4.4</org.springframework.data.version>
<org.springframework.cloud.version>2020.0.2</org.springframework.cloud.version>
<com.alibaba.cloud.version>2021.1</com.alibaba.cloud.version>
```

**Comment by ankeway** [comment]
See 
https://github.com/alibaba/spring-cloud-alibaba/issues/1346
https://github.com/alibaba/spring-cloud-alibaba/pull/1374/commits/4c5bf778632153bfbaf5dc092533f4c7303eb9d7

**Comment by theonefx** [comment]
My solution is to simply throw the exception when it can't be handled.

https://github.com/alibaba/spring-cloud-alibaba/pull/2146
