### ISSUE TITLE
No provider available from registry localhost:9090 for service com.xxx.xxxService on consumer 192.168.1.100 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).

### ISSUE THREAD

**Issue by winterallen** [alibaba/spring-cloud-alibaba#2047]
> 问题描述：

第一次启动服务端和消费端，消费端能正常调用服务端的方法，此时重启服务端，消费端报No provider available from registry localhost:9090 for service...

> 版本:

spring-boot :2.3.2.RELEASE
spring-cloud:Hoxton.SR8
sca:2.2.5.RELEASE
nacos-client/ser :1.4.1
dubbo:2.7.8

> 异常：

org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:9090 for service com.xxx.xxxService on consumer 192.168.1.100 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).

**Comment by Burutiaowuhh** [comment]
我也遇到这样的问题  第一次先启动消费者，再启动提供者，这样是可以正常访问到。但是把提供者下线在上线之后，消费者就报No provider available from registry异常。希望官方能给解决下。

**Comment by Burutiaowuhh** [comment]
我的版本是springcloud alibaba: 2.2.5.RELEASE
dubbo:2.7.8
nacos-client:1.4.1

**Comment by winterallen** [comment]
更改注册中心地址协议方式可暂时解决No provider available from registry localhost:9090 for service的问题
dubbo:
  registry:
    ~~address: spring-cloud://localhost~~
    address: nacos://127.0.0.1:8848
但是又有新的问题，配置中心会侵入一些dubbo的配置信息
![image](https://user-images.githubusercontent.com/17891799/116365098-80a69300-a837-11eb-8488-bb76d1072beb.png)

**Comment by Burutiaowuhh** [comment]
> 更改注册中心地址协议方式可暂时解决No provider available from registry localhost:9090 for service的问题
> dubbo:
> registry:
> ~address: spring-cloud://localhost~
> address: nacos://127.0.0.1:8848
> 但是又有新的问题，配置中心会侵入一些dubbo的配置信息
> ![image](https://user-images.githubusercontent.com/17891799/116365098-80a69300-a837-11eb-8488-bb76d1072beb.png)

这样操作的话有个问题 ：
假设现在有A、B两个命名空间 ，访问A空间里的消费者服务的时候，A空间里的消费者有概率会调用到B空间里的服务提供者，A、B两个空间的服务就没办法做到隔离

**Comment by theonefx** [comment]
@winterallen 请问一下，你的dubbo的注册中心地址是如何配置的？

**Comment by winterallen** [comment]
> @winterallen请问一下，你的dubbo的注册中心地址是如何配置的？

![image](https://user-images.githubusercontent.com/17891799/116496692-39241380-a8d8-11eb-8972-c9b42b7930c1.png)

**Comment by BuYi-Feng** [comment]
一样的配置 等待结果，我现在是在K8S上配置的，现在每次重启服务端，其他的消费端也必须重启，会导致STW。

**Comment by candyYu** [comment]
等待处理结果

**Comment by lizhuquan0769** [comment]
同样等待，消费者得重启才能找到提供者

**Comment by cyf0477** [comment]
不是注册协议的问题 
address: spring-cloud://localhost
address: nacos://127.0.0.1:8848

这个改了也没用   
dubbo: 2.7.4.1
cloud: 2.2.0

**Comment by tinet-shenjg** [comment]
我这也是  所以每次启动都是全量重启，太费劲了

**Comment by theonefx** [comment]
这个问题，应该在https://github.com/alibaba/spring-cloud-alibaba/pull/2101这个PR中修复了。目前已经在2.2.6.RC1中发布了，欢迎大家一起验证

**Comment by xiaojinrong** [comment]
> 我这也是所以每次启动全量重启，太费劲了

哥，这个问题解决了吗？太痛苦了。
