### ISSUE TITLE
Spring Cloud Alibaba 2021.1  @Value 无法绑定配置

### ISSUE THREAD

**Issue by linyongfu2013** [alibaba/spring-cloud-alibaba#2048]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Config

**Describe what problem you have encountered**
```
Spring Boot : 2.4.2
Spring Cloud Alibaba: 2021.1
Nacos server: 2.0.0
Nacos client: 1.4.1
```

使用以上版本启动应用报错：Could not resolve placeholder 'avatar' in value "${avatar}"

同样的代码和配置，使用以下版本组合则正常可用：
```
Spring Boot : 2.3.7.RELEASE
Spring Cloud Alibaba: 2.2.5.RELEASE
Nacos server: 2.0.0
Nacos client: 1.4.1
```

**Describe what information you have read**
eg. I have read the reference doc of Nacos

![image](https://user-images.githubusercontent.com/4011963/115818123-a9411e00-a42e-11eb-9a3c-ceb39834988a.png)

**Comment by linyongfu2013** [comment]
还有一个问题，我的项目使用了 [jasypt](https://github.com/ulisesbocchio/jasypt-spring-boot) 对配置进行加解密，应用在收到nacos 配置更新触发事件时，可能是没调用 `jasypt` 的解密，导致了部分属性配置因类型不对而报错

```
spring.redis.port: ENC(qRT6kXO4GycbQgu9B5H+6w==)

org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.redis.port' to int
```

**Comment by mj19910923** [comment]
你的各个组件版本对应好像有问题
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by linyongfu2013** [comment]
@mj19910923 为什么我收到邮件有你的回复，但进来 issue 里却看不到你的回复

![image](https://user-images.githubusercontent.com/4011963/115979521-f0f3b100-a5b8-11eb-801a-5e836160b516.png)

![image](https://user-images.githubusercontent.com/4011963/115979543-1b456e80-a5b9-11eb-921d-86e0db1857f7.png)

**Comment by warthur1214** [comment]
我也遇到这个问题了

**Comment by Surrin1999** [comment]
> 我也遇到这个问题了。 是spring cloud 2020以上版本移除boostrap组件的问题。 添加一下配置就可以了：
> 
> ```
>     <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-starter-bootstrap</artifactId>
>         <version>3.0.2</version>
>     </dependency>
> ```

感谢！的确是这个原因，Spring Cloud报的错误太具迷惑性了。。
