### ISSUE TITLE
版本依赖应该是不正确的

### ISSUE THREAD

**Issue by wpengsen** [alibaba/spring-cloud-alibaba#2059]
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

springboot2.4.x版本好像后边没有RELEASE后缀了，请及时更新文档

还有cloud的版本是2020.0，用不用确定下小版本号，现在好像是2020.0.2

**Comment by HaojunRen** [comment]
Correct it in https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
