### ISSUE TITLE
How to disable Hystrix while using Sentinel

### ISSUE THREAD

**Issue by hooverhe** [alibaba/spring-cloud-alibaba#2062]
More than one implementation of @EnableCircuitBreaker (now relying on @conditionals to pick one): [com.alibaba.cloud.sentinel.custom.SentinelCircuitBreakerConfiguration, org.springframework.cloud.netflix.hystrix.HystrixCircuitBreakerConfiguration]

The version of spring boot and cloud:

```
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.3.8.RELEASE</version>

<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-dependencies</artifactId>
<version>Hoxton.SR10</version>
```

If I exclude those Hystrix dependencies, the application will throw exception. How to disable Hystrix while using Sentinel?

**Comment by conditionals** [comment]
i pick the first option

**Comment by HaojunRen** [comment]
Removal Hystrix dependency does any helps?

**Comment by HaojunRen** [comment]
I think you do not have the annotation with @EnableCircuitBreaker under Sentinel
