### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discovery 2021.1 version issue

### ISSUE THREAD

**Issue by w13518019987** [alibaba/spring-cloud-alibaba#2069]
I introduce dependencies
<dependency>
              <groupId>com.alibaba.cloud</groupId>
              <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
              <version>2021.1</version>
</dependency>
Does he not support ribbon by default？
Should the ribbon dependency be introduced separately?
RestTemplate load balancing failed！！

**Comment by HaojunRen** [comment]
Spring Cloud 2020 and Spring Cloud Alibaba 2021 does not support Ribbon yet, it has been replace with Spring Cloud Loadbalancer with based on WebFlux. Any Ribbon related components will impact functions of 2020
