### ISSUE TITLE
Can sentinel implement IP based current limiting rules?

### ISSUE THREAD

**Issue by LingCai2001** [alibaba/spring-cloud-alibaba#2076]
Can sentinel implement IP based current limiting rules? Can I adjust the concurrency of each IP?

**Comment by HaojunRen** [comment]
Do you mean that sentinel limitation via IP dimension? It makes sense, you can extend 'limit-app' mechanism. Please refer to http://nepxion.com/discovery/, jump to  Chapters '基于Sentinel-LimitApp扩展的防护' -> '基于IP地址和端口的防护'
