### ISSUE TITLE
BOM should not import spring-boot-dependencies and spring-cloud-dependencies

### ISSUE THREAD

**Issue by JasonMing** [alibaba/spring-cloud-alibaba#2081]
Currently the BOM (spring-cloud-alibaba-dependencies) import spring-boot-dependencies and spring-cloud-dependencies.
It is really a bad idea to do that! 
These imports make spring-cloud-alibaba-dependencies and strongly bound to specified version spring-boot/spring-cloud.
The good practice likes spring-cloud-dependenies, it never imports the spring-boot-dependencies, leave the final decision to the users instead of making decision for them.

**Comment by HaojunRen** [comment]
You can replace version of spring-boot-dependencies and spring-cloud-dependencies in your BOM. For example
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring.cloud.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
    </dependencyManagement>
```
refer to https://gitee.com/nepxion/DiscoveryGuide/blob/6.x.x-simple/pom.xml

That means if you define the verison of them, spring cloud alibaba will use your defination, otherwise it will use its defination
