### ISSUE TITLE
which version can support nacos2.0.1?

### ISSUE THREAD

**Issue by maozuoyun** [alibaba/spring-cloud-alibaba#2083]
hello,alibaba spring cloud team：
I found the newest version of spring cloud alibaba is 2021.1,the best fit version of nacos is 1.4.1。now the newst nacos server version is 2.0.1,this version is better than the older version. I want to know whether spring cloud alibaba can support nacos the newest version，and if support，how can i to integrate  in my project?

**Comment by theonefx** [comment]
the api of 2.0.1 is same as 1.4.x，so you can upgrade it as you need

**Comment by maozuoyun** [comment]
i think you have  misunderstand me! Becauser in offical release notes,spring-cloud-alibaba recommend nacos version is 1.4.2,but the newest version is 2.0.x.
