### ISSUE TITLE
项目a，消费项目b和c, b,c项目实现的是同一接口，如何指定？

### ISSUE THREAD

**Issue by HuShao96** [alibaba/spring-cloud-alibaba#2085]
项目a，消费项目b和c； b和c项目实现的是同一接口，如何指定？
本来想根据应用名称指定，但是好像没有这样的方法，ProvidedBy属性好像也没用。求解

**Comment by jnx2280303225** [comment]
> 项目a，消费项目b和c； b和c项目实现的是同一接口，如何指定？
> 本来想根据应用名称指定，但是好像没有这样的方法，ProvidedBy属性好像也没用。求解

可以尝试一下根据url来指定
@FeignClient(url = "http://b/xxx")

**Comment by HuShao96** [comment]
> > 项目a，消费项目b和c； b和c项目实现的是同一接口，如何指定？
> > 本来想根据应用名称指定，但是好像没有这样的方法，ProvidedBy属性好像也没用。求解
> 
> 可以尝试一下根据url来指定
> @FeignClient(url = "http://b/xxx")

谢谢，我想这个肯定行，也是最终但不想使用的解决办法
