### ISSUE TITLE
The nacos interface reported an error

### ISSUE THREAD

**Issue by wangzai9999** [alibaba/spring-cloud-alibaba#2086]
Nacos 2.0.1 and 2.0.0 version interface modification configuration cannot be saved, interface error: DiffEditorDialog.js?306b:66 Uncaught TypeError: Cannot read property 'MergeView' of undefined
at DiffEditorDialog.createDiffCodeMirror (DiffEditorDialog.js?306b:66)
at eval (DiffEditorDialog.js?306b:53)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by theonefx** [comment]
Please check if there is a version conflict
