### ISSUE TITLE
Sentinel对Feign限制粒度以及扩展问题

### ISSUE THREAD

**Issue by A11enHuang** [alibaba/spring-cloud-alibaba#2094]
**Which Component**
 Sentinel

**Is your feature request related to a problem? Please describe.**
Sentinel对Feign的支持中，每一个rest接口都会当作一个资源进行限流处理，可是Sentinel对资源的数量会有限制。目前的版本(1.8)中未提供对此资源限制的调整。如果项目中本身要限制的资源太多，那么就会造成直接忽略对某些资源的限制。并且SentinelFeign是final类，SentinelInvocationHandler的构造方法也仅限于本包中。因此如果我想要进行扩展，是没法做到的。

In Sentinel's support for Feign, each rest interface will be treated as a resource for current limiting, but Sentinel will limit the number of resources. The current version (1.8) does not provide adjustments to this resource limit. If there are too many resources to be restricted in the project itself, it will cause the direct ignorance of the restrictions on certain resources. And SentinelFeign is a final class, the construction method of SentinelInvocationHandler is also limited to this package. So if I want to expand, I can't do it.

**Describe the solution you'd like**
能不能开放对资源限制粒度的配置。例如我针对某一个service进行限制，或者同一个service中的某一个domain进行限制，最小的粒度才是针对rest接口的限制。
在SentinelFeign中提供重载方法，让我能对构建过程进行扩展，或者能够提供装饰器，让我对构建进行扩展。

Can you open up the configuration of resource restriction granularity. For example, if I restrict a certain service, or restrict a certain domain in the same service, the smallest granularity is the restriction for the rest interface.
Provide overloaded methods in SentinelFeign, so that I can extend the build process, or can provide a decorator, let me extend the build.

**Comment by yuhuangbin** [comment]
欢迎贡献 PR

**Comment by Cuihongsen** [comment]
我这边需要一个能自定义资源名的方式，这个Feature 似乎有用

**Comment by DanielLiu1123** [comment]
see #2342
