### ISSUE TITLE
Sentinel dashboard can't show spring cloud gateway current group

### ISSUE THREAD

**Issue by jgzl** [alibaba/spring-cloud-alibaba#2114]
**Which Component**
当使用sentinel 和 spring cloud alibaba 2020.1时

**Describe the bug**
SpringCloud Alibaba sentinel往网关注册时，提交的type是 11，而Sentinel官方要求是1
System.setProperty(SentinelConfig.APP_TYPE_PROP_KEY,
				ConfigConstants.APP_TYPE_SCG_GATEWAY);

public final class ConfigConstants {

	/**
	 * Spring Cloud Gateway type.
	 */
	public static final String APP_TYPE_SCG_GATEWAY = "11";              这个是SpringCloudAlibaba封装的

public final class SentinelGatewayConstants {

    public static final int APP_TYPE_GATEWAY = 1;                 这个是Sentinel定义的

请问这可以提交PR修复不

**Comment by jgzl** [comment]
在 API Gateway 端，用户只需要在原有启动参数的基础上添加如下启动参数即可标记应用为 API Gateway 类型：

# 注：通过 Spring Cloud Alibaba Sentinel 自动接入的 API Gateway 整合则无需此参数
-Dcsp.sentinel.app.type=1

**Comment by oawang** [comment]
@jgzl  https://github.com/alibaba/spring-cloud-alibaba/pull/2112
