### ISSUE TITLE
请问事务型消息的@RocketMQTransactionListener中的txProducerGroup应该如何配置？

### ISSUE THREAD

**Issue by snfdf** [alibaba/spring-cloud-alibaba#2115]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
rocketmq

**Describe what problem you have encountered**
我目前使用的阿里云的rocketmq，根据这篇文档中最后一部分描述
https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ
我在配置topic和group的时候需要在前面加上instance-id%。那么我在使用事务型消息的时候需要在一个类上使用@RocketMQTransactionListener注解，同时要设置txProducerGroup，那么此时这个txProducerGroup我应该如何设置呢？因为一般项目都会有多套环境，那按照文档说明这个txProducerGroup我应该配置成 instance-id%group-name，但这样就把instance-id写死了。还请各位指点，谢谢。

**Comment by pomeloHu** [comment]
注解上的参数值也可以使用配置

**Comment by snfdf** [comment]
> 注解上的参数值也可以使用配置
还请大侠给写一下是如何使用配置的。我之前写的是：
@RocketMQTransactionListener(txProducerGroup = "${instance-id}%group")
但是项目启动时报错，提示 the specified group[${instance-id}%group] contains illegal characters, allowing only ^[%|a-zA-Z0-9_-]+$

**Comment by snfdf** [comment]
> 注解上的参数值也可以使用配置

还请大侠给写一下是如何使用配置的。我之前写的是：
@RocketMQTransactionListener(txProducerGroup = "${instance-id}%group")
但是项目启动时报错，提示 the specified group[${instance-id}%group] contains illegal characters, allowing only ^[%|a-zA-Z0-9_-]+$

**Comment by zkzlx** [comment]
你使用的是哪个版本的mq呢？新版本的mq更新了很多特性，配置方式也改变了很多，wiki上的文档目前还不是最新的

**Comment by snfdf** [comment]
> 你使用的是哪个版本的mq呢？新版本的mq更新了很多特性，配置方式也改变了很多，wiki上的文档目前还不是最新的

我用的是spring-cloud-starter-stream-rocketmq，版本是2.2.5.RELEASE。请问最新的配置要在哪里查看？

**Comment by zkzlx** [comment]
新文档正在更新中，这两天就能在wiki上弄好。或者可以先在分支上查看说明
[rocketMq新说明](https://github.com/alibaba/spring-cloud-alibaba/blob/rocketmq/spring-cloud-alibaba-docs/src/main/asciidoc-zh/rocketmq-new.adoc)

**Comment by snfdf** [comment]
> 新文档正在更新中，这两天就能在wiki上弄好。或者可以先在分支上查看说明
> [rocketMq新说明](https://github.com/alibaba/spring-cloud-alibaba/blob/rocketmq/spring-cloud-alibaba-docs/src/main/asciidoc-zh/rocketmq-new.adoc)

好的，谢谢。
