### ISSUE TITLE
分层能否按着阿里巴巴的官方手册来？

### ISSUE THREAD

**Issue by pashenmebaojinwo** [alibaba/spring-cloud-alibaba#2118]
![image](https://user-images.githubusercontent.com/43331024/122644072-d0258300-d145-11eb-9d03-2f7c0ee22bde.png)
![image](https://user-images.githubusercontent.com/43331024/122644093-f5b28c80-d145-11eb-84cd-f9315f0db8b2.png)
我还看到有controller直接调用dao层，什么鬼！分层领域规约,model官方手册也没有啊！

**Comment by theonefx** [comment]
抱歉，这部分代码模板处理的有些问题，多谢反馈，我们会尽快处理的
