### ISSUE TITLE
NacosDiscoveryProperties required a bean of type 'com.alibaba.cloud.nacos.NacosServiceManager'

### ISSUE THREAD

**Issue by wu-xin** [alibaba/spring-cloud-alibaba#2123]
In spring-cloud-starter-alibaba-nacos-discovery-2.1.4.release, an error is reported when `spring.cloud.nacos.discovery.enabled=false` is configured, because NacosDiscoveryProperties is injected with NacosServiceManager, and NacosServiceManager is initialized in NacosServiceAutoConfiguration, which is When false, NacosServiceAutoConfiguration is not loaded.

**Comment by davids-dot** [comment]
@wu-xin  大佬，怎么解决的？
