### ISSUE TITLE
dubbo3.0什么时候支持

### ISSUE THREAD

**Issue by ytsunlei** [alibaba/spring-cloud-alibaba#2124]
您好，dubbo3.0，已经发布10多天了，spring cloud alibaba什么时候支持？希望使用dubbo3.0的应用级注册

**Comment by theonefx** [comment]
目前同 dubbo3 的集成工作正在进行中，会分成两批发布：

- 采用之前的方式适配 dubbo3 ，使用方法和集成方法上和 2.x 保持一致；
- 实现 dubbo3 与 sca + dubbo 的双向互调；

其中第一部分，预期7月份能搞定，第二部分，要看参与的同学的精力，以及实现方案上有多少坑。
