### ISSUE TITLE
NacosConfigProperties#Config 内的 group 为什么不默认使用 NacosConfigProperties  的 group

### ISSUE THREAD

**Issue by glmapper** [alibaba/spring-cloud-alibaba#2125]
```
spring.cloud.nacos.config.group=xxx
```
&
```
spring.cloud.nacos.config.extension-configs[n].group=xxx
```

**Comment by yuhuangbin** [comment]
extension-configs可加载不同分组的配置信息，`spring.cloud.nacos.config.group` 默认加载当前应用分组，可以参考：[NacosPropertySourceLocator](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java#L102)
