### ISSUE TITLE
springboot引入spring-cloud-starter-alibaba-nacos-config 时，nacos配置更新时，应用好像被重启了。

### ISSUE THREAD

**Issue by Canicanliu** [alibaba/spring-cloud-alibaba#2126]
![image](https://user-images.githubusercontent.com/1527623/123365709-64aa3e00-d5a9-11eb-9696-22058ba17e67.png)
这种重启是否会对业务造成影响呢？

**Comment by Canicanliu** [comment]
还有@RefreshScope 需要在每个获取配置的java文件中添加，能否只在启动的类上添加呢？这样改造工作就会更少。

**Comment by yuhuangbin** [comment]
动态配置刷新是Spring Cloud官方团队开发，参考 `ContextRefresher`，使用此功能，建议把配置放在 `@ConfigurationProperties`标注的配置类中。

**Comment by Canicanliu** [comment]
> 动态配置刷新是Spring Cloud官方团队开发，参考 `ContextRefresher`，使用此功能，建议把配置放在 `@ConfigurationProperties`标注的配置类中。

这个主要是解答我的问题2吧，问题2其实主要是，改造配置中心的工作量的问题。

**Comment by Canicanliu** [comment]
重启的问题有人看吗？这个才是我最关心的问题，如果配置更新，服务被自动重启了，担心影响到业务

**Comment by Canicanliu** [comment]
应该其他人也有遇到类似的问题，都有重启的日志吧

**Comment by yuhuangbin** [comment]
你的应用服务不会重启的，配置刷新原理你可以查看 `ContextRefresher` 这个类源码，其实是创建了一个新的容器去启动，完成相关配置的刷新动作，随后close掉，不是你应用服务本身的容器，建议你还是去查阅相关`Spring Cloud` 动态配置刷新相关的原理，配置的刷新会导致bean的销毁再重新装载，所以建立动态刷新的配置都归类到 `@ConfigurationProperties`标注的配置类中，避免业务bean生命周期有影响

**Comment by yuhuangbin** [comment]
对于`@ConfigurationProperties`的配置类属性动态刷新，是不需要再标注`@RefreshScope`注解的

**Comment by Canicanliu** [comment]
> 你的应用服务不会重启的，配置刷新原理你可以查看 `ContextRefresher` 这个类源码，其实是创建了一个新的容器去启动，完成相关配置的刷新动作，随后close掉，不是你应用服务本身的容器，建议你还是去查阅相关`Spring Cloud` 动态配置刷新相关的原理，配置的刷新会导致bean的销毁再重新装载，所以建立动态刷新的配置都归类到 `@ConfigurationProperties`标注的配置类中，避免业务bean生命周期有影响

所以，我上面截图的那些日志是正常的，ContextRefresher并没有重启服务，而只是把相差的bean销毁再重新装载？

**Comment by Canicanliu** [comment]
> 对于`@ConfigurationProperties`的配置类属性动态刷新，是不需要再标注`@RefreshScope`注解的

![配置问题](https://user-images.githubusercontent.com/1527623/123923706-d0cade80-d9bb-11eb-9631-e8bad70dfb57.png)
我建了一个配置类，加了@ConfigurationProperties，并不会自动刷新

**Comment by yuhuangbin** [comment]
相关案例请参考，example工程吧
