### ISSUE TITLE
ConsumerProperties 并没有 consume-from-where属性，这个该如何设置

### ISSUE THREAD

**Issue by madGodFucker** [alibaba/spring-cloud-alibaba#2127]
![image](https://user-images.githubusercontent.com/52117498/123394290-90411e80-d5d1-11eb-8d6a-1a529ac2c5f5.png)
![image](https://user-images.githubusercontent.com/52117498/123394471-c1b9ea00-d5d1-11eb-88ce-380950e137a9.png)

**Comment by zkzlx** [comment]
you can use this version .
`<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
    <version>2.2.6.RC1</version>
</dependency>`
