### ISSUE TITLE
spring-cloud-alibaba 2021.1版本，如果启用SentinelFeign 后FeignClientBuilder forType方法 动态创建FeignClient不成功

### ISSUE THREAD

**Issue by heyin123** [alibaba/spring-cloud-alibaba#2137]
启用SentinelFeign 后FeignClientBuilder forType方法 动态创建FeignClient不成功。debug调试发现，SentinelFeign中build方法中去从GenericApplicationContext中去获取。gctx.getBeanDefinition 时候会抛出NoSuchBeanDefinitionException异常，本来FeignClient需要动态创建的不知道为啥这里需要去从ApplicationContext中获取，而hystixFeign不会出现这种异常。
，SentinelFeign代码片段如下。
public Feign build() {
            super.invocationHandlerFactory(new InvocationHandlerFactory() {
                public InvocationHandler create(Target target, Map<Method, MethodHandler> dispatch) {
                    GenericApplicationContext gctx = (GenericApplicationContext)Builder.this.applicationContext;
                    BeanDefinition def = gctx.getBeanDefinition(target.type().getName());
                    FeignClientFactoryBean feignClientFactoryBean = (FeignClientFactoryBean)def.getAttribute("feignClientsRegistrarFactoryBean");
                    Class fallback = feignClientFactoryBean.getFallback();
                    Class fallbackFactory = feignClientFactoryBean.getFallbackFactory();
                    String beanName = feignClientFactoryBean.getContextId();

**Which Component**
SentinelFeign

**Describe the bug**

**To Reproduce**
动态创建FeignClient代码如下：
        FeignClientBuilder clientBuilder = new FeignClientBuilder(applicationContext);
        FeignClientBuilder.Builder<BizUserClient> builder = clientBuilder.forType(BizUserClient.class, serviceName);
        BizUserClient userClient = builder.build();

注意：BizPermsClient是接口类
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import java.util.List;

public interface BizUserClient {

    @RequestMapping(value = "/user/resources", method = RequestMethod.POST)
    public BaseResult<List<String>> userResources(@RequestParam(value = "userId") String userId);

}

**Expected behavior**
通过FeignClientBuilder 可以动态创建FeignClient。

**Screenshots**

**Additional context**
spring-cloud-alibaba 2021.1版本

**Comment by HaojunRen** [comment]
本来FeignClient需要动态创建的不知道为啥这里需要去从ApplicationContext中获取
----------------------------------------------------
原因是因为Hoxton.SR10改了fallback机制，不这么做，会引起类似循环依赖错误
```
Requested bean is currently in creation: Is there an unresolvable circular reference?
```
我们在考虑新的可行性解决方案

**Comment by HaojunRen** [comment]
本来FeignClient需要动态创建的不知道为啥这里需要去从ApplicationContext中获取
----------------------------------------------------
原因是因为Hoxton.SR10改了fallback机制，不这么做，会引起类似循环依赖错误
```
Requested bean is currently in creation: Is there an unresolvable circular reference?
```
我们在考虑新的可行性解决方案

**Comment by HaojunRen** [comment]
我根据你提供的相关用法，测试了一下，并没有发现你说的问题。是否可以提供一个可以单独运行，可以重新该问题的简单示例给我们？
![图片](https://user-images.githubusercontent.com/42354711/124477345-83dd7280-ddd6-11eb-8965-0b4f9ae73563.png)
![图片](https://user-images.githubusercontent.com/42354711/124477417-948de880-ddd6-11eb-9a02-8af0abda926a.png)
![图片](https://user-images.githubusercontent.com/42354711/124477468-a40d3180-ddd6-11eb-99b9-b4d3d9229437.png)
![图片](https://user-images.githubusercontent.com/42354711/124477503-acfe0300-ddd6-11eb-86da-3061630d6c54.png)
