### ISSUE TITLE
NacosWatch 影响zipkin链路追踪

### ISSUE THREAD

**Issue by suqinghzhou2019** [alibaba/spring-cloud-alibaba#2140]
NacosWatch 注入的参数taskScheduler为LazyTraceThreadPoolTaskScheduler,将会导致每半分钟向zipkin-server发送无用信息，
`[{"traceId":"2de22ad748eac957","id":"2de22ad748eac957","name":"async","timestamp":1625464726537000,"duration":311,"localEndpoint":{"serviceName":"organization","ipv4":"192.168.180.1"}}]`
**Desktop (please complete the following information):**
 - Version

> Spring Cloud Alibaba  2.1.4.RELEASE 

> Spring Cloud Greenwich.SR6

**Comment by yuhuangbin** [comment]
`NacosWatch`仅仅周期性 发布 `HeartbeatEvent`事件， 你提到的向`zipkin-server`发送无用信息， 确定是由于注入了`LazyTraceThreadPoolTaskScheduler` 导致吗？或者可以提供其他详细信息

**Comment by suqinghzhou2019** [comment]
> `NacosWatch`仅仅周期性 发布 `HeartbeatEvent`事件， 你提到的向`zipkin-server`发送无用信息， 确定是由于注入了`LazyTraceThreadPoolTaskScheduler` 导致吗？或者可以提供其他详细信息

基本确定，我自行注入NacosWatch，创建了个返回空的ObjectProvider<ThreadPoolTaskScheduler>，就没有这种情况了。

**Comment by HaojunRen** [comment]
一般来说，调用链中间件会自动采集http调用请求，发到服务器上去。不知道在Zipkin里是否可以把NacosWatch的HeartbeatEvent的请求排除在Zipkin发送触发机制之外？

**Comment by guerlab** [comment]
2.0+的nacos client采用了tcp链接，应该就不会有这个问题了吧
