### ISSUE TITLE
nacos配置中心(spring.cloud.nacos.discovery) 实例meta信息，热更新不到注册中心服务实例列表元数据里面

### ISSUE THREAD

**Issue by caofei88** [alibaba/spring-cloud-alibaba#2148]
一、测试版本背景：nacos server版本2.0.1  ,springcloud alibaba2.2.5
二、测试步骤如下：
     1、在nacos配置中心配置实例，示例如下：
       
![image](https://user-images.githubusercontent.com/64238311/124849513-80faa180-dfd1-11eb-959f-b3441fd9ab91.png)

     2、启动服务，去注册中心观察实例，服务实例元数据正常

     3、修改配置中心服务实例元数据配置，去注册中心实例列表观察，元数据未推送更新
            
![image](https://user-images.githubusercontent.com/64238311/124849704-d5058600-dfd1-11eb-8720-9b12b66b6917.png)
![image](https://user-images.githubusercontent.com/64238311/124849723-dd5dc100-dfd1-11eb-997a-ed7089a84576.png)
![image](https://user-images.githubusercontent.com/64238311/124849780-f6667200-dfd1-11eb-975c-b65a54e7ef30.png)

**Comment by yuhuangbin** [comment]
直接在Nacos控制台，修改实例元数据就行

**Comment by HaojunRen** [comment]
Nacos界面上更新元数据，只是发生在配置层面，就算收到了更新后的元数据配置，也不会去更新注册实例上的元数据，所以在Nacos控制台上，自行去修改实例元数据即可。至于是否在配置中心修改了元数据后，推送到注册中心上，这个需要讨论一下

**Comment by Cczzzz** [comment]
nacos服务注册他只有启动时才读那些东西，启动后有更新也不会管了

**Comment by HaojunRen** [comment]
> 
> 
> nacos服务注册他只有启动时才读那些东西，启动后有更新也不会管了

在Nacos Web界面的元数据那里可以修改的，会动态更新权重数据，以及用户自定义的元数据，但如果一个服务有多个实例，需要手工逐个更新

**Comment by caofei88** [comment]
> > nacos服务注册他只有启动时才读那些东西，启动后有更新也不会管了
> 
> 在Nacos Web界面的元数据那里可以修改的，会动态更新权重数据，以及用户自定义的元数据，但如果一个服务有多个实例，需要手工逐个更新

在注册中心页面上手动编辑实例元数据更新就很鸡肋了，这个本质上就是spring-cloud-starter-alibaba-nacos-discovery,重新注册逻辑没生效或者去处理配置中心热更新

**Comment by caofei88** [comment]
> 直接在Nacos控制台，修改实例元数据就行
假设有100个实例，你自己一个个手动改  那要配置现在搞锤子

**Comment by yuhuangbin** [comment]
> > 直接在Nacos控制台，修改实例元数据就行
> > 假设有100个实例，你自己一个个手动改  那要配置中心搞锤子

Nacos 提供了运维Open Api，你可以通过Open Api批量更新，通过配置中心管理元数据，这个方案还需要讨论

**Comment by HaojunRen** [comment]
> > 直接在Nacos控制台，修改实例元数据就行
> > 假设有100个实例，你自己一个个手动改  那要配置中心搞锤子

你的需求从这个维度讲是对的，但是从另外一个维度，例如，有个服务A有4个实例，有2个实例是旧版本，2个是新版本，通过MetaData动态修改版本，如果打通配置中心和注册中心，那么在配置中心修改版本号，这4个实例全部同一个版本号了。但我个人认为通过配置中心来修改元数据，的确是有必要的。但这里会牵涉到很多的问题，例如：
元数据可能来自三部分
- Nacos config配置中心
- 静态文件打包到jar里的application.properties或者yml
- 通过运维侧启动参数-D方式进来的

问题在哪里呢？
比如：我一开始把元数据配置在静态文件里，然后遇到需求，需要通过Nacos config增加一个元数据，这可能没问题。那么假如在Nacos config里删除一个元数据，又应该怎么处理呢，假如删除的元数据是和-D方式同名，是否直接把它干掉？因为大多数情况，元数据配置和业务配置可能是混在一起的，业务配置改动频率比较大。从技术上来讲，Nacos监听任何配置的改动，都会触发一个事件，如果通过比较配置中心推过的元数据和服务内存中的元数据，从而去决定要不要推送到注册中心，这种做法可能会有漏洞。举个例子，我通过-D方式注册了一个元数据，配置中心没配元数据，然后配置中心修改了一个业务配置，推到nacos client，这个时候，client有一个元数据(即-D方式进来的)，配置中心没有元数据，那么，从client层面，会认为没有配置元数据，它会把-D那个也删除，这就有逻辑问题。原因在于，
client无法区分，这个元数据是来自最上面罗列的三种方式的哪一种？

所以，元数据来源不是一个地方，如何很好的处理好数据一致性问题，有较大的难度。至于打通注册中心和配置中心，在技术层面难度不会太大

欢迎讨论

**Comment by theonefx** [comment]
> > > 直接在Nacos控制台，修改实例元数据就行
> > > 假设有100个实例，你自己一个个手动改  那要配置中心搞锤子
> 
> 你的需求从这个维度讲是对的，但是从另外一个维度，例如，有个服务A有4个实例，有2个实例是旧版本，2个是新版本，通过MetaData动态修改版本，如果打通配置中心和注册中心，那么在配置中心修改版本号，这4个实例全部同一个版本号了。但我个人认为通过配置中心来修改元数据，的确是有必要的。但这里会牵涉到很多的问题，例如：
> 元数据可能来自三部分
> 
> * Nacos config配置中心
> * 静态文件打包到jar里的application.properties或者yml
> * 通过运维侧启动参数-D方式进来的
> 
> 问题在哪里呢？
> 比如：我一开始把元数据配置在静态文件里，然后遇到需求，需要通过Nacos config增加一个元数据，这可能没问题。那么假如在Nacos config里删除一个元数据，又应该怎么处理呢，假如删除的元数据是和-D方式同名，是否直接把它干掉？因为大多数情况，元数据配置和业务配置可能是混在一起的，业务配置改动频率比较大。从技术上来讲，Nacos监听任何配置的改动，都会触发一个事件，如果通过比较配置中心推过的元数据和服务内存中的元数据，从而去决定要不要推送到注册中心，这种做法可能会有漏洞。举个例子，我通过-D方式注册了一个元数据，配置中心没配元数据，然后配置中心修改了一个业务配置，推到nacos client，这个时候，client有一个元数据(即-D方式进来的)，配置中心没有元数据，那么，从client层面，会认为没有配置元数据，它会把-D那个也删除，这就有逻辑问题。原因在于，
> client无法区分，这个元数据是来自最上面罗列的三种方式的哪一种？
> 
> 所以，元数据来源不是一个地方，如何很好的处理好数据一致性问题，有较大的难度。至于打通注册中心和配置中心，在技术层面难度不会太大
> 
> 欢迎讨论

那么，是否存在这样一种逻辑，将数据来源隔离？例如通过一个：先读取-D、在读取application.properties、最后读取nacos config，这样的规则来实现数据的读取工作。于是从数据的关注者角度，只需要关注配置的key，而不用关心数据的来源，因为配置最终都是聚合的。

**Comment by HaojunRen** [comment]
问题不在这里而是，比如
运维人员设置了metadata.a，通过-DMetadata.a=x，输入进去，运维人员在配置中心设置MetaData.b=y，那么a应该怎么处理？因为a既可以-D进来，也可以通过配置中心来设置。

举个场景，一开始在配置中心有a和b两个值，后面删除了a，那么在client需要同步删除a。由于client端无法区分a来自-D，还是配置中心，所以按照上述场景，client很难决定a要不要删除。

**Comment by caofei88** [comment]
> 问题不在这里而是，比如
> 运维人员设置了metadata.a，通过-DMetadata.a=x，输入进去，运维人员在配置中心设置MetaData.b=y，那么a应该怎么处理？因为a既可以-D进来，也可以通过配置中心来设置。
> 
> 举个场景，一开始在配置中心有a和b两个值，后面删除了a，那么在client需要同步删除a。由于client端无法区分a来自-D，还是配置中心，所以按照上述场景，client很难决定a要不要删除。

那其实就是说配置metadata来源方式有多种，默认那种优先级最高，然后就覆盖了

**Comment by caofei88** [comment]
> 问题不在这里而是，比如
> 运维人员设置了metadata.a，通过-DMetadata.a=x，输入进去，运维人员在配置中心设置MetaData.b=y，那么a应该怎么处理？因为a既可以-D进来，也可以通过配置中心来设置。
> 
> 举个场景，一开始在配置中心有a和b两个值，后面删除了a，那么在client需要同步删除a。由于client端无法区分a来自-D，还是配置中心，所以按照上述场景，client很难决定a要不要删除。

**Comment by caofei88** [comment]
> 问题不在这里而是，比如
> 运维人员设置了metadata.a，通过-DMetadata.a=x，输入进去，运维人员在配置中心设置MetaData.b=y，那么a应该怎么处理？因为a既可以-D进来，也可以通过配置中心来设置。
> 
> 举个场景，一开始在配置中心有a和b两个值，后面删除了a，那么在client需要同步删除a。由于client端无法区分a来自-D，还是配置中心，所以按照上述场景，client很难决定a要不要删除。

我觉得这个问题可以参考dubbo 现在设计思路，dubbo元数据在注册中心引入一个版本号，确定优先级
![image](https://user-images.githubusercontent.com/64238311/125391242-b7239100-e3d6-11eb-87f4-5dcf1ad48c48.png)

**Comment by yuhuangbin** [comment]
如果此功能是用于做灰度，配置中心更新元数据，是否能做到更新服务的部分实例元数据而不是更新所有实例 ？如果实现不了，或者复杂度比较高，那么有点事倍功半。

**Comment by HaojunRen** [comment]
> 
> 
> 如果此功能是用于做灰度，配置中心更新元数据，是否能做到更新服务的部分实例元数据而不是更新所有实例 ？如果实现不了，或者复杂度比较高，那么有点事倍功半。

这的确是个大问题，因为元数据是实例级的，而配置是服务级的，就是说同一个服务下每个服务实例都有自己专属的元数据，而Nacos配置中心的某个配置是对该服务下所有实例都通用的，配置中心改了一个元数据，所有的服务实例都会被更新到，这就会影响到元数据实例的独特性

其实，这个issue讨论下来，我们可以转换一下思路
> Nacos控制台上专门开辟一个界面，来批量更新元数据，入口让用户选择，如果用户选择了一个服务名，那么所有的实例都会被更新到。如果用户选择了该服务下若干个实例，那么就只更新这若干个实例的元数据

不知道Nacos团队是否能接受这个需求
