### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discover 服务发现没有使用sdk的订阅功能

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/spring-cloud-alibaba#2153]
为什么会这样，为什么不用订阅来获得更低的延迟

**Comment by HaojunRen** [comment]
走的是Nacos两个不同的路
注册中心走com.alibaba.nacos.api.naming.NamingService
配置中心走com.alibaba.nacos.api.config.ConfigService

Spring Cloud的负载均衡，用的是Ribbon或者Spring Cloud Loadbalancer，Spring Cloud Alibaba需要去适合和符合Spring Cloud相关的规范，比如通过Ribbon更新机制，去更新服务列表，如果绕开这些机制，可能行，但也可能不行，应该需要大量代码的修改

我的个人观点，仅供参考

**Comment by Cczzzz** [comment]
> 走的是Nacos两个不同的路
> 注册中心走com.alibaba.nacos.api.naming.NamingService
> 配置中心走com.alibaba.nacos.api.config.ConfigService
> 
> Spring Cloud的负载均衡，用的是Ribbon或者Spring Cloud Loadbalancer，Spring Cloud Alibaba需要去适合和符合Spring Cloud相关的规范，比如通过Ribbon更新机制，去更新服务列表，如果绕开这些机制，可能行，但也可能不行，应该需要大量代码的修改
> 
> 我的个人观点，仅供参考

是的，我看了下 spring cloud那边好像并没考虑 推送与负载均衡这边的交互

**Comment by HaojunRen** [comment]
阐述一下，我个人理解的一些背后逻辑
如果Sping Cloud更加开放，负载均衡机制更Open，比如，更新负载均衡缓存可以由用户去实现，而不是定时更新，那么我们可以采用长连接的方式，去做服务注册发现。你的想法应该也可以实现。
或者Spring Cloud推一套负载均衡和服务注册发现的强势性规范，所有象Nacos, Consul, Eureka, Zookeeper那种都必须遵循，不仅仅局限在某种固定的协议（例如，Http协议），那么你的问题迎刃而解。但是Spring Cloud是中间件，不站在最底层，所以只能它去适配注册中心，而不是注册中心反过来适配它。
所以目前的设计，对于现有Spring Cloud负载均衡机制的定时更新机制，有个很致命的缺陷，当某个服务实例下线后，不能马上通知给其它服务，从而造成流量有损，尤其是Ribbon，而Spring Cloud LoadBalancer会好一些
