### ISSUE TITLE
[Question] For the stater stream rocket in the use of Instrumentation.

### ISSUE THREAD

**Issue by yourkiwifruit** [alibaba/spring-cloud-alibaba#2154]
**Which Component**
starter-stream-rocketmq

**Describe what problem you have encountered**

For the stater stream rocket in the use of  `Instrumentation`, 
```
rocketMQTemplate.afterPropertiesSet();
instrumentationManager.getHealthInstrumentation(destination).markStartedSuccessfully();	
```
```
rocketMQListenerContainer.start();
instrumentationManager.getHealthInstrumentation(rocketMQListenerContainer.getTopic()+ rocketMQListenerContainer.getConsumerGroup()).markStartedSuccessfully();
```

I can understand that for when `rocketMQTemplate` or `ocketMQListenerContainer` complete initialization or start success, just as the UP state?

**Describe what information you have read**
No.

**Comment by zkzlx** [comment]
Yes, that's all for now. If you have any good ideas, you are welcome to join us

**Comment by yourkiwifruit** [comment]
thanks
