### ISSUE TITLE
nacos-client 2.0.1 configure discovery.server-addr to domain(slb) in cluster mode is NacosWatch throw exception

### ISSUE THREAD

**Issue by it-noob** [alibaba/spring-cloud-alibaba#2155]
**Which Component**
Nacos Discovery,

**Describe what problem you have encountered**
2.0.1 的集群模式下，在 master 分支直接修改 spring-cloud-alibaba-dependencies 中的 nacos-client 版本为 2.0.1，然后启动 nacos-discovery-provider-example，就提示如下错误：

但是，如果是 1.4.2 不会报错，spring.cloud.nacos.discovery.server-addr 如果是其中一个节点的 IP+端口也不会报错

In 2.0.1 cluster mode, I modify the nacos-client version to 2.0.1 in the master branch directly, and then start nacos-discovery-provider-example, it prompts the following error.
![image](https://user-images.githubusercontent.com/12043442/124929064-c602f000-e032-11eb-94ea-2b03be323181.png)

![image](https://user-images.githubusercontent.com/12043442/124929155-d87d2980-e032-11eb-93a3-59b8877b2e84.png)

However, if it is 1.4.2 it will not report an error and spring.cloud.nacos.discovery.server-addr will not report an error if it is the IP+port of one of the nodes

**Describe what information you have read**

官网文档提示集群模式使用 vip 或者 slb 进行使用

The official documentation suggests using vip or slb for cluster mode

![image](https://user-images.githubusercontent.com/12043442/124929120-d024ee80-e032-11eb-990f-3d4c86fa6a1e.png)

**Comment by yuhuangbin** [comment]
Please refer to [Nacos 2.x Upgrade document](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html), Then check SLB configuration.

**Comment by it-noob** [comment]
> Please refer to [Nacos 2.x Upgrade document](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html), Then check SLB configuration.

Ok, thanks, sorry for not reading the documentation in detail.
