### ISSUE TITLE
更灵活的服务注册 

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/spring-cloud-alibaba#2156]
我希望能增加以下功能：

- 控制开始注册的时间。在项目启动时不进行注册，在运行时可以动态的上线，由应用自己控制
例子：
某些启动后需要预热的应用。
会发生角色切换的应用，例如需要选举并且只有leader才需要注册，如果leader宕机其他节点成为leader时他才能注册自己

- 运行时修改实例的元数据

这些功能现版本可以做吗，或者有人在开发吗

**Comment by yuhuangbin** [comment]
case1： 暂时没有该计划

case2:  直接通过Nacos Server Open Api修改实例，或者Nacos 控制台编辑修改服务实例元数据

**Comment by Cczzzz** [comment]
我想贡献这个case1：
通过一个配置项选择是否启用
然后利用
       @EventListener
	public void onNacosDiscoveryInfoChangedEvent(NacosDiscoveryInfoChangedEvent event) {
		restart();
	}
中的NacosDiscoveryInfoChangedEvent进行控制。
NacosDiscoveryInfoChangedEvent 这个现在是啥情况并未用到
为其提供几种事件类型
- 开始注册
- 注销自己
- 重新注册（先修改NacosRegistration 然后根据NacosRegistration的信息重新注册）

**Comment by HaojunRen** [comment]
> 
> 
> 我希望能增加以下功能：
> 
>     * 控制开始注册的时间。在项目启动时不进行注册，在运行时可以动态的上线，由应用自己控制
>       例子：
>       某些启动后需要预热的应用。
>       会发生角色切换的应用，例如需要选举并且只有leader才需要注册，如果leader宕机其他节点成为leader时他才能注册自己
> 
>     * 运行时修改实例的元数据
> 
> 
> 这些功能现版本可以做吗，或者有人在开发吗

控制开始注册的时间。在项目启动时不进行注册，在运行时可以动态的上线，由应用自己控制
--------------------
Nacos元数据里有个enabled开关，你注册上去的时候，enabled=false为初始值，含义是虽然注册了，但不对外暴露，其它服务不能发现它，等你预热结束后，DevOps平台通过Open Api把enabled置成true，就可以被其它服务发现了

case 2如同@yuhuangbin所提到的，其实case1和case2都是相同的操作模式
