### ISSUE TITLE
failed to register metadata to consul  (Spring Cloud Alibaba 2021.1)

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#2157]
Version:  Spring Cloud Alibaba 2021.1

Use Consul as register center. Some Exception Information was found. as bellow:

> Invalid Service Meta: Couldn't load metadata pair ('dubbo.metadata-service.urls', '[ "dubbo://192.168.0.141:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bind.ip=192.168.0.141&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=spring-cloud-alibaba-dubbo-provider&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=38572&qos.enable=false&release=2.7.8&revision=1.0.0&side=provider&timestamp=1625815894436&version=1.0.0" ]'): Key contains invalid characters

It means that the key named "dubbo.metadata-service.urls" is not supported.

original message put to consul by http method is:
`
{"ID":"spring-cloud-alibaba-dubbo-provider-9384","Name":"spring-cloud-alibaba-dubbo-provider","Tags":[],"Address":"host.docker.internal","Meta":{"secure":"false","dubbo.metadata-service.urls":"[ \"dubbo://192.168.0.141:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost\u003dtrue\u0026application\u003dspring-cloud-alibaba-dubbo-provider\u0026bind.ip\u003d192.168.0.141\u0026bind.port\u003d20880\u0026deprecated\u003dfalse\u0026dubbo\u003d2.0.2\u0026dynamic\u003dtrue\u0026generic\u003dfalse\u0026group\u003dspring-cloud-alibaba-dubbo-provider\u0026interface\u003dcom.alibaba.cloud.dubbo.service.DubboMetadataService\u0026methods\u003dgetAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs\u0026pid\u003d38572\u0026qos.enable\u003dfalse\u0026release\u003d2.7.8\u0026revision\u003d1.0.0\u0026side\u003dprovider\u0026timestamp\u003d1625815894436\u0026version\u003d1.0.0\" ]","dubbo.protocols.dubbo.port":"20880","dubbo.protocols.rest.port":"9090"},"Port":9090}`

**Comment by theonefx** [comment]
Could you please provide your configuration so that we can reproduce the problem locally

**Comment by imgoby** [comment]
I run the program In Spring Cloud Aibaba(**version 2021.1)** original source,the project name is "spring-cloud-dubbo-provider-sample"
![image](https://user-images.githubusercontent.com/27885492/125047222-5728a400-e0d1-11eb-837d-e327a2beb834.png)

the config is as follow:
![image](https://user-images.githubusercontent.com/27885492/125047503-9fe05d00-e0d1-11eb-9f3e-c06a2496058a.png)

![image](https://user-images.githubusercontent.com/27885492/125047545-ad95e280-e0d1-11eb-84bd-15531499cfc7.png)
