### ISSUE TITLE
Nacos doesn't support Route Definition Locator?

### ISSUE THREAD

**Issue by WeLinkOn** [alibaba/spring-cloud-alibaba#2161]
**Which Component**
Nacos Discovery, Spring Cloud Gateway

**Describe what problem you have encountered**
I want to create routes  based on service discovery, so I set spring.cloud.gateway.discovery.locator.enabled=true and of course lower-case-service-id=true. My gateway address is **_localhost:8080_**, the target service is **ruyi-user-service** and the path is _**localhost:8010/auth/sendSmsCode**_. Having the service discovery enabled, when I visit **_localhost:8080/ruyi-user-service/auth/sendSmsCode_**, the response should be the same as the request of the target route, but it doesn't work and the status is always 404. Here is the log:

>2021-07-12 02:41:17.830  INFO 16228 --- [ctor-http-nio-3] c.netflix.config.ChainedDynamicProperty  : Flipping property: ruyi-user-service.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2021-07-12 02:41:17.881  INFO 16228 --- [ctor-http-nio-3] c.netflix.loadbalancer.BaseLoadBalancer  : Client: ruyi-user-service instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=ruyi-user-service,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2021-07-12 02:41:17.901  INFO 16228 --- [ctor-http-nio-3] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2021-07-12 02:41:17.948  INFO 16228 --- [ctor-http-nio-3] c.netflix.config.ChainedDynamicProperty  : Flipping property: ruyi-user-service.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2021-07-12 02:41:17.993  INFO 16228 --- [ctor-http-nio-3] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client ruyi-user-service initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=ruyi-user-service,current list of Servers=[192.168.124.3:8011],Load balancer stats=Zone stats: {unknown=[Zone:unknown;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:192.168.124.3:8011;	Zone:UNKNOWN;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 08:00:00 CST 1970;	First connection made: Thu Jan 01 08:00:00 CST 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:com.alibaba.cloud.nacos.ribbon.NacosServerList@62b0f8ea
2021-07-12 02:41:18.915  INFO 16228 --- [erListUpdater-0] c.netflix.config.ChainedDynamicProperty  : Flipping property: ruyi-user-service.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647

**Describe what information you have read**
I have read the reference doc of Spring Cloud Gateway : https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-discoveryclient-route-definition-locator

**Comment by HaojunRen** [comment]
Do you mean to change Spring Cloud Gateway route via dynamic config in Nacos Config? If so, whatever Spring Cloud or Spring Cloud Alibaba, whatever Nacos or Consul, are `ALL` does not support the feature, you should integrate them by yourself. You can refer to https://nepxion.com/discovery/, find the chapter for 'Spring-Cloud-Gateway网关动态路由'

**Comment by WeLinkOn** [comment]
Thanks for your answer.
Uh, What I want is not dynamic config in Nacos, but using its service discovery ability.
We have known that Spring Cloud Gateway has an ability to locate service route via service registry and service name([Spring Cloud Gatey Doc here](https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-discoveryclient-route-definition-locator)), so there is no need to configure each of them. For example, My gateway host is localhost:8080 and, I have an api **_localhost:8010/auth/sendSmsCode_** used to send sms code in user-service, when I set spring.cloud.gateway.discovery.locator.enabled=true in gateway configuration, I can call the api by combining gateway domain and the service name, like this: localhost:8080/user-service/auth/sendSmsCode, but I failed, the response status is 404.
The Spring Cloud Gateway reference doc said a DiscoveryClient implementation can do like that, does Nacos support that too?

**Comment by HaojunRen** [comment]
If you use `spring.cloud.gateway.discovery.locator.enabled=true`, i think it should use `serviceName` as the predicate in url, just as follows
```
http://[gateway ip]:[gateway port]/[service name]/[service url]
```
Just like your url
```
http://localhost:8080/user-service/auth/sendSmsCode
```

I am sure Gateway with the component of Spring Cloud Alibaba can work fine, because I tested that yesterday. May some other configs impacted that for you?

**Comment by WeLinkOn** [comment]
Yes, my url is the same as yours, it is correct.

---
Good news!
I've found a new case just now at your suggestion. I use `dubbo` to expose my rest api in user-service. I doubt it may influence. So I created a new test api with springMVC, you know what, it worked. So, the question becomes

* Does dubbo rest support the service discovery based route location? If yes, how to make that?

**Comment by HaojunRen** [comment]
Dubbo exposes restful api, make Dubbo service and Spring Cloud Gateway in the same service discovery center. Try it

I am not so sure that it can work

**Comment by WeLinkOn** [comment]
![image](https://user-images.githubusercontent.com/26466555/125273472-89d7d400-e33f-11eb-9c49-651ad2782da1.png)
I've searched [dubbo reference doc about the rest support](https://dubbo.apache.org/zh/docs/v2.7/user/rest/#dubbo-rest%E7%9A%84%E6%9C%8D%E5%8A%A1%E8%83%BD%E5%92%8Cdubbo%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%BF%83%E7%9B%91%E6%8E%A7%E4%B8%AD%E5%BF%83%E9%9B%86%E6%88%90%E5%90%97) and found the above info, which I think is the reasonable explanation. I directly call the rest api exposed by dubbo in Postman, which is not a dubbo managed consumer, so it doesn't work. It looks that I should choose another way to expose the restful api to web invokers.
Thanks.

**Comment by HaojunRen** [comment]
Spring Cloud Gateway is a just route component, since Dubbo exposed Rest API can be invoked in Postman, why not invoke via Gateway? Would you do an advanced search for integration Dubbo & Spring Cloud Gateway?If really not supported, welcome to PR

**Comment by WeLinkOn** [comment]
> Spring Cloud Gateway is a just route component, since Dubbo exposed Rest API can be invoked in Postman, why not invoke via Gateway? Would you do an advanced search for integration Dubbo & Spring Cloud Gateway?If really not supported, welcome to PR

OK，I would make more efforts to test the truth. Just give me some days : )

**Comment by WeLinkOn** [comment]
> Spring Cloud Gateway is a just route component, since Dubbo exposed Rest API can be invoked in Postman, why not invoke via Gateway? Would you do an advanced search for integration Dubbo & Spring Cloud Gateway?If really not supported, welcome to PR

OK，I would make more efforts to test the truth. Just give me some days : )
