### ISSUE TITLE
nacos开启认证以后，自定义dataid获取失败。Error opening logging config file

### ISSUE THREAD

**Issue by jiangjun0130** [alibaba/spring-cloud-alibaba#2164]
nacos server启动开启认证（NACOS_AUTH_ENABLE=true  ），设置了spring.cloud.nacos.username/password后，springboot默认配置能够读取。但是自定的dataid获取失败。
如logback自定义配置文件
logging:
  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-custom.xml

获取失败日志：
Error opening logging config file http://ip:port/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

Server returned HTTP response code: 403 for URL: http://ip:port/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

配置内容上如何设置accessToken？

**Comment by yuhuangbin** [comment]
你是通过Nacos Open Api操作的？

**Comment by jiangjun0130** [comment]
spring:
  cloud:
    nacos:
      username: xxx
      password: xxx
      discovery:
        server-addr: nacos.nacos:8848
        namespace: xxx
      config:
        server-addr: nacos.nacos:8848
        namespace: lin-an-town
        file-extension: yml
        shared-configs[0]:
          data-id: xxx.yml
          group: DEFAULT_GROUP
          refresh: true

logging:
  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-custom.xml

如上配置，springboot启动过程中，日志输出：
Error opening logging config file http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

Server returned HTTP response code: 403 for URL: http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

想把各微服务自定义的logback配置统一通过配置中心获取，但是当nacos启用了认证以后，拉取不到logback配置文件，看日志是没有对应权限。这块要怎么配置呢？

**Comment by yuhuangbin** [comment]
配置项是不是在 `bootstrap.yaml` 里面配置的?

**Comment by jiangjun0130** [comment]
移到bootstrap也是一样的。日志输出：
Error opening logging config file http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

Server returned HTTP response code: 403 for URL: http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

nacos server默认不开启认证是没问题的，开启了认证（NACOS_AUTH_ENABLE=true）就读取不到

**Comment by jiangjun0130** [comment]
移到bootstrap也是一样的。日志输出：
Error opening logging config file http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

Server returned HTTP response code: 403 for URL: http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

nacos server默认不开启认证是没问题的，开启了认证（NACOS_AUTH_ENABLE=true）就读取不到

**Comment by yuhuangbin** [comment]
namespace 应该是Nacos 控制台上的 uuid吧？建议你先阅读相关文档，或者参考Spring Cloud Alibaba Example示例项目

**Comment by jiangjun0130** [comment]
除了自定义logback-custom.xml读取不到，application-name.yml是可以读取到的，不是UUID的问题，创建namespace，id和name是可以一样的

**Comment by yuhuangbin** [comment]
你是否加入了SCA社区钉钉群？ 可以去群里讨论这个问题

**Comment by taoguoliang** [comment]
@jiangjun0130 请问有没有解决这个问题
