### ISSUE TITLE
钉钉群的二维码全部过期了

### ISSUE THREAD

**Issue by lin-mt** [alibaba/spring-cloud-alibaba#2165]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lin-mt** [comment]
https://github.com/alibaba/spring-cloud-alibaba/blob/master/README-zh.md

**Comment by yuhuangbin** [comment]
群5 Spring Cloud Alibaba ：34930571
