### ISSUE TITLE
How to route based on metadata by use spring cloud dubbo  and nacos

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/spring-cloud-alibaba#2166]
If I want route by nacos metadata。In AbstractLoadBalance and AbstractRouter ，I can not get metadata from （List<Invoker> invokers, URL url, Invocation invocation）
what should I do？

**Comment by yuhuangbin** [comment]
refer `NacosRule`

**Comment by HaojunRen** [comment]
```java
    @Autowired
    private Registration registration;
    
   Map<String, String> metadata = registration.getMetadata();
```

**Comment by Cczzzz** [comment]
> NacosRule



> ```java
>     import org.springframework.cloud.client.serviceregistry.Registration;
> 
>     @Autowired
>     private Registration registration;
>     
>    Map<String, String> metadata = registration.getMetadata();
> ```

自己用dubbo 接口url 里的信息和nacos元数据进行关联吗，没有更合适的方式吗

**Comment by Cczzzz** [comment]
> refer `NacosRule`

NacosRule 在哪里

**Comment by Cczzzz** [comment]
我怎样做才能在dubbo 进行路由和负载均衡时 拿到注册到nacos的元数据呢。我需要根据元数据进行路由，并且元数据是可以发生变化的
