### ISSUE TITLE
SentinelFeign 中获取FeignClientFactoryBean为null

### ISSUE THREAD

**Issue by yangxiufeng666** [alibaba/spring-cloud-alibaba#2169]
spring-boot.version ： 2.4.2
spring-cloud.version：2020.0.0
spring-cloud-alibaba：2021.1

不能实例化FeignClient，报FeignClientFactoryBean为null。

![image](https://user-images.githubusercontent.com/6647574/125881095-410e7a46-8597-473a-8ba5-10d34bffbe90.png)

**Comment by theonefx** [comment]
这个问题已经在2.2.6.RELEASE里修复了，很快会合并到新的2020版本里去

**Comment by theonefx** [comment]
https://github.com/alibaba/spring-cloud-alibaba/issues/2107

**Comment by kim709394** [comment]
> 这个问题已经在2.2.6.RELEASE里修复了，很快会合并到新的2020版本里去
```xml
     <spring.cloud.alibaba.version>2021.1</spring.cloud.alibaba.version>
        <spring.boot.version>2.4.9</spring.boot.version>
        <spring.cloud-version>2020.0.0</spring.cloud-version>
```
dependence versions were up to date, but this bug remain exists

**Comment by YSRE** [comment]
2022.0.0.0-RC1 又出现这个问题了
