### ISSUE TITLE
允许dubbo在路由时访问nacos元数据

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/spring-cloud-alibaba#2170]
使用nacos作为注册中心进行服务治理时，我们会根据nacos的中的元数据来进行路由和治理。为方便进行服务治理所有的路由和负载都应该是基于一套数据。比如有dubbo 和 cloud 配置路由元数据的应该都是一个地方，不应该为dubbo单独配置。
但在使用dubbo时dubbo spi 提供的负载均衡和路由时并不能获取到注册到nacos的元数据。
修改DubboNacosServiceMetadataRepository 将nacos Registration 中的元数据 添加到接口url 的 parameters中。
这样保证服务消费者做负载时也能获取到注册的nacos的 元数据。这样是否可行？

**Comment by theonefx** [comment]
初步看来，是个不错的想法。但是还是需要继续展开讨论一下。

目前在2.2.6中，是支持江dubbo的一些元数据写入注册中心的metadata中。例如tag，或者是其他的自定义标识。

但是不是很确定你需要写入的数据具体有哪些，以及这些数据在哪里维护，能否举个例子呢？
