### ISSUE TITLE
Nacos discovery client get service do not have right behavior

### ISSUE THREAD

**Issue by tian-jeff** [alibaba/spring-cloud-alibaba#2172]
**Which Component**
Nacos Discovery

**Describe the bug**
Nacos discovery client get service do not have right behavior

**To Reproduce**
1. application bootstrap normal.
2. core DNS in k8s cluster exception occurred, can not resolve Nacos service host.
3. k8s liveness probe triggered the action of Nacos get service 
4. ip util checked the ipv4 address is incorrect, and throw exception.
5. NacosDiscoveryClient eat up this exception, and return empty list, health check is ok.
6. core DNS back to normal, but in application container the Nacos hostname can not resolve.
7.  health check always ok, k8s will not restart container.

**Expected behavior**
when Nacos ip check failed, throw exception to health check.

**Screenshots**
detail exception
![image](https://user-images.githubusercontent.com/1702836/125962374-ae453d6c-fb68-4ee5-8df4-23e1ae23e126.png)
Eat the exception code
![image](https://user-images.githubusercontent.com/1702836/125962573-a1ccc407-6387-4673-8068-7cf7469d2cea.png)

**Comment by theonefx** [comment]
it's a bug in nacos-client 1.4.1. please upgrade to version 1.4.2.

**Comment by tian-jeff** [comment]
double confirm this, i don't think this code in nacos client.
i upgrade to version com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.2.6.RELEASE, and in 
 com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient 
![image](https://user-images.githubusercontent.com/1702836/126732679-fc08b92d-d120-4344-8f3a-d1e9bb2c0e91.png)
get service name from nacos server fail, but health checker thought it was success.

**Comment by tian-jeff** [comment]
> it's a bug in nacos-client 1.4.1. please upgrade to version 1.4.2.

the point is spring cloud discovery health checker can not perceive exception from com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient
