### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar不再支持Ribbon?

### ISSUE THREAD

**Issue by onlymate918** [alibaba/spring-cloud-alibaba#2177]
Zuul集成Nacos时，spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar因为没有NacosRibbonClientConfiguration类，导致没有实例化com.netflix.loadbalancer.ServerList<T extends Server>，从而网关无法拉取服务列表，导致路由分发失败
![image](https://user-images.githubusercontent.com/53428286/126252157-de7a2c04-536f-4c92-83a3-3c7dd58ce42b.png)
![image](https://user-images.githubusercontent.com/53428286/126252078-bf355121-aa0a-46d1-b9c9-f1d0555eb21e.png)
修改版本为spring-cloud-starter-alibaba-nacos-discovery-2.2.6.RELEASE后，正常了
![image](https://user-images.githubusercontent.com/53428286/126253727-ba358cd3-7a9b-421e-87d7-016e0e2019a9.png)
请问，2021.1版本不在对Ribbon支持了吗？

**Comment by guerlab** [comment]
spring cloud alibaba 2021.1是基于spring cloud 2020的

spring cloud 2020里边已经逐渐的弃用了netflix的组件了

zuul使用了spring cloud gateway进行替代

可以考虑更换zuul来使用新版本，或者将spring  cloud alibaba/spring cloud进行降级
