### ISSUE TITLE
FeignClient错误

### ISSUE THREAD

**Issue by lfift** [alibaba/spring-cloud-alibaba#2188]
FeignClient指定Fallback后启动报错，报错信息如下：
Caused by: java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory$Default
	at com.alibaba.cloud.sentinel.feign.SentinelFeign$Builder$1.create(SentinelFeign.java:104)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:64)
	at feign.Feign$Builder.target(Feign.java:269)
![image](https://user-images.githubusercontent.com/31279478/127113383-d6aef0cd-02bc-44d1-8dad-64c8d6259044.png)
根本就没有这个类呀，SpringCloudOpenFeign不是提供了一个FallbackFactory吗，为啥还是使用的Hystrix的，难道是我的版本有问题吗，依赖版本如下：
<spring-cloud.version>2020.0.0</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.6.RELEASE</spring-cloud-alibaba.version>

代码如下：
@FeignClient(value = "test", fallback = TestFeignFallback.class)
public interface TestFeign {

    @GetMapping("/test")
    Result<String> test();
}

@Component
public class TestFeignFallback implements TestFeign {
    @Override
    public Result<String> test() {
        return Result.isFailure("调用服务失败！");
    }
}

**Comment by yuhuangbin** [comment]
请严格参照版本说明  https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
<spring-cloud-alibaba.version>2.2.6.RELEASE</spring-cloud-alibaba.version>
对应
<spring-cloud.version>Hoxton.SR9</spring-cloud.version>

**Comment by hefangqiang** [comment]
请问你解决了吗  我的集成sentinel降级, feign配置fallbackFactory时报错: `Incompatible fallbackFactory instance. Fallback/fallbackFactory of type class com.micro.system.api.factory.RemotePayFallbackFactory is not assignable to interface feign.hystrix.FallbackFactory for feign client `remotePayService.`         版本：2.2.7.RELEASE   Hoxton.SR12  2.3.12.RELEASE  sentinel1.8.1
