### ISSUE TITLE
sentinel 搭配nacos 提示错误

### ISSUE THREAD

**Issue by yu5056561661** [alibaba/spring-cloud-alibaba#2194]
spring:
  profiles: dev
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.192.24:19999
        port: 8719
      datasource:
        flow:
          nacos:
            serverAddr: 192.168.192.24:20200 #nacos服务器地址
            username:  123
            password:  123
            dataId: JClientConsumer-sentinel.json
            groupId: DEFAULT_GROUP
            namespace: dev #命名空间
    nacos:
      config:
        server-addr: 192.168.192.24:20200 
        file-extension: yaml
        namespace: dev
        username:  123
        password:  123
        extension-configs:
          - data-id: All-service-dev.yaml
            group: DEFAULT_GROUP
            refresh: true 
我现在想把sentinel 规则文件放在配置中心， 然后就按照文档配置。会提示
Description:

Failed to bind properties under 'spring.cloud.sentinel.datasource.flow.nacos' to com.alibaba.cloud.sentinel.datasource.config.NacosDataSourceProperties:

    Reason: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotEmpty' validating type 'java.lang.String'. Check configuration for 'dataId'
想请问下是什么问题？

**Comment by suirenshiyu** [comment]
同问啊 用javax.validation.constraints.NotEmpty来校验String的原因，用org.hibernate.validator.constraints.NotEmpty也行啊官方啥时候改改？

**Comment by suirenshiyu** [comment]
https://www.136.la/java/show-95876.html
