### ISSUE TITLE
啥时候可以发布新版本，可不可以把里面的依赖都升级一下呀

### ISSUE THREAD

**Issue by jinshengyong** [alibaba/spring-cloud-alibaba#2197]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by spinachomes** [comment]
连续20天没动静了

**Comment by yuhuangbin** [comment]
暂定这个月会有新版本发布，主要内容为升级各个组件版本，稍安勿躁

**Comment by jinshengyong** [comment]
> 暂定这个月会有新版本发布，主要内容为升级各个组件版本，稍安勿躁

好的，谢谢呀，一直都是如饥似渴地在等呀

**Comment by shihuaguo** [comment]
感觉升级很频繁啊，你们都是一有新版本就把原有项目全部升级到最新版吗？

**Comment by jinshengyong** [comment]
是的，每次升级都是升级到最新版

**Comment by jinshengyong** [comment]
> 感觉升级很频繁啊，你们都是一有新版本就把原有项目全部升级到最新版吗？

是的，每次升级都是升级到最新版
