### ISSUE TITLE
LoadBalancerClient is not injected into spring context.

### ISSUE THREAD

**Issue by kim709394** [alibaba/spring-cloud-alibaba#2198]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
 Nacos Discovery,

**Describe the bug**
versions:
  <spring.cloud.alibaba.version>2021.1</spring.cloud.alibaba.version>
        <spring.boot.version>2.4.9</spring.boot.version>
        <spring.cloud-version>2020.0.0</spring.cloud-version>
The class org.springframework.cloud.client.loadbalancer.LoadBalancerClient is not injected into spring context.
there are error messages when run a nacos discovery app from wiki examples:
No qualifying bean of type 'org.springframework.cloud.client.loadbalancer.LoadBalancerClient'

**To Reproduce**

**Expected behavior**
 
**Screenshots**

**Additional context**
 Windows、Java8 、
  <spring.cloud.alibaba.version>2021.1</spring.cloud.alibaba.version>
        <spring.boot.version>2.4.9</spring.boot.version>
        <spring.cloud-version>2020.0.0</spring.cloud-version>

**Comment by kim709394** [comment]
nacos-discovery-comsumer  demo, I tried to run the following code , which can be runed success
@RestController
@RequestMapping("/nacos/comsumer")
public class ComsumerController {

    @Autowired
    private NacosServiceManager nacosServiceManager;

    @Autowired
    private NacosDiscoveryProperties nacosDiscoveryProperties;

    @Autowired
    private RestTemplate restTemplate;


    @GetMapping("/test")
    public String test() throws NacosException {
        //从注册中心nacos获取服务名为nacos-discovery-provider的实例
        NamingService namingService = nacosServiceManager.getNamingService(nacosDiscoveryProperties.getNacosProperties());
        Instance instance = namingService.selectOneHealthyInstance("nacos-discovery-provider");
        String url = String.format("http://%s:%s/nacos/discovery/provider",instance.getIp(),instance.getPort());
        String response = restTemplate.getForObject(url, String.class);
        return "provider service return :"+response;

    }
}

**Comment by yuhuangbin** [comment]
try add dependency ?
```xml
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
 </dependency>
```
