### ISSUE TITLE
kill -15 java服务报错NullPointerException

### ISSUE THREAD

**Issue by KingSirLee** [alibaba/spring-cloud-alibaba#2200]
如题，kill -15 的时候，报错：
o.s.beans.factory.support.DisposableBeanAdapter - Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException

spring-cloud-starter-alibaba-nacos-discovery
2.1.3.RELEASE

**Comment by yuhuangbin** [comment]
麻烦提供详细日志

**Comment by yuhuangbin** [comment]
pr : #2201 增强了NPE判断

**Comment by KingSirLee** [comment]
snapshot版本有deploy到仓库麽，
https://oss.sonatype.org/content/repositories/snapshots/com/alibaba/cloud/spring-cloud-alibaba-nacos-discovery/
这里看不到修复版本
