### ISSUE TITLE
Wiki 里面 ”版本说明“未及时更新

### ISSUE THREAD

**Issue by HardyDou** [alibaba/spring-cloud-alibaba#2202]
毕业版本依赖关系(推荐使用)
目前是：
|Spring Cloud Version | Spring Cloud Alibaba Version | Spring Boot Version|
-- | -- | --
|Spring Cloud 2020.0.0 | 2021.1 | 2.4.2|

应该是：

|Spring Cloud Version | Spring Cloud Alibaba Version | Spring Boot Version|
-- | -- | --
|Spring Cloud 2020.0.1 | 2021.1 | 2.4.2|

**Comment by yuhuangbin** [comment]
thanks, fixed.
