### ISSUE TITLE
logback-spring.xml can't use <springProperty> when using nacos config

### ISSUE THREAD

**Issue by ooooo-youwillsee** [alibaba/spring-cloud-alibaba#2205]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos config 

**Is your feature request related to a problem? Please describe.**

nacos config :
```
a.b = 1
```

logback-spring.xml :
```
<springProperty scope="context" name="x" source="a.b" defaultValue="2"/>
```

but I get value of 'x' is 2

**Describe the solution you'd like**

see apollo implementation , [ApolloApplicationContextInitializer](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java)

**Comment by IT-GoldFish** [comment]
Hello, have you solved your problem? I'm in the same situation

**Comment by ooooo-youwillsee** [comment]
SpringBoot 2.4+ using configData, nacos implements it using  `NacosConfigDataLoader`, it had solved the problem
