### ISSUE TITLE
nacos1.4 使用openfeign调用第三方www.baidu.com无法访问，提示：com.netflix.client.ClientException: Load balancer does not have available server for client: www.hao123.com

### ISSUE THREAD

**Issue by 495291493** [alibaba/spring-cloud-alibaba#2209]
# springcloud alibaba 、 springboot版本
![AV%OYWU0@PQ%FB`H$_JV8UD](https://user-images.githubusercontent.com/10412649/128810359-a5e6dea2-c44b-4dda-a903-dbf5a801a332.png)

# feign声明式调用编写
![image](https://user-images.githubusercontent.com/10412649/128810405-9db95ae3-871d-4411-b2af-74fa7cda31ab.png)

# 报错信息如下
![image](https://user-images.githubusercontent.com/10412649/128810437-be66fc17-938d-4736-afba-3282db08d67a.png)

# 自查问题处理，无效情况如下
![image](https://user-images.githubusercontent.com/10412649/128810560-870c29b0-97c7-4e9a-9a62-213c1da373f7.png)

希望官网能帮忙看看问题！谢谢！

**Comment by yuhuangbin** [comment]
```java
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
@Controller
public class App{

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    
    @Autowired
    private BaiduFeignClient baiduFeignClient;

    @RequestMapping(value = "/test")
    public String test() {
        return baiduFeignClient.get();
    }
    
    
    @FeignClient(name = "baidu", url = "https://www.baidu.com")
    public interface BaiduFeignClient {

        @GetMapping("/")
        public String get();
   }
    
    
}
```

**Comment by liuzhimin1996** [comment]
@495291493 
这个问题解决了吗？issue为什么关了
