### ISSUE TITLE
An exception(java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory) occurred while using openfeign + sentinel

### ISSUE THREAD

**Issue by wanglianghczyq** [alibaba/spring-cloud-alibaba#2220]
**Which Component**
spring-cloud-starter-alibaba-sentinel-2.2.6.RELEASE.jar

**Describe the bug**
使用OpenFeign+Sentinel时,发生异常
An exception occurred while using openfeign + sentinel

Caused by: java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory
	at com.alibaba.cloud.sentinel.feign.SentinelFeign$Builder.build(SentinelFeign.java:76) ~[spring-cloud-starter-alibaba-sentinel-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at feign.Feign$Builder.target(Feign.java:269) ~[feign-core-10.12.jar:na]
	at org.springframework.cloud.openfeign.DefaultTargeter.target(DefaultTargeter.java:30) ~[spring-cloud-openfeign-core-3.0.3.jar:3.0.3]
----
查看SentinelFeign代码,发现头部引入了hystrix 的类
Check the sentinelfeign code and find that the header references the hystrix class

package com.alibaba.cloud.sentinel.feign;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.util.Map;

import feign.Contract;
import feign.Feign;
import feign.InvocationHandlerFactory;
import feign.Target;
**import feign.hystrix.FallbackFactory;
import feign.hystrix.HystrixFeign;**

import org.springframework.beans.BeansException;
import org.springframework.cloud.openfeign.FeignContext;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.util.ReflectionUtils;
import org.springframework.util.StringUtils;

/**
 * {@link Feign.Builder} like {@link HystrixFeign.Builder}.
 *
 * @author <a href="mailto:fangjian0423@gmail.com">Jim</a>
 */
public final class SentinelFeign {

**Screenshots**
![hystrixfeign](https://user-images.githubusercontent.com/14726884/130308324-1929e81d-f899-4d23-8e9b-3b845bc3cbe9.png)

**Additional context**
windows 、Java8 、 Version 2.2.6.RELEASE

**Comment by yuhuangbin** [comment]
你Spring Cloud 什么版本？

**Comment by wanglianghczyq** [comment]
spring cloud 是2.2.6RELEASE版本的,我感觉和spring cloud没有关系吧
是SentinelFeign类中引入了feign.hystrix中的类,加载类的时候就异常了




----- 原始邮件 -----
发件人：余黄彬 ***@***.***>
收件人：alibaba/spring-cloud-alibaba ***@***.***>
抄送人：wanglianghczyq ***@***.***>,  Author ***@***.***>
主题：Re: [alibaba/spring-cloud-alibaba] An exception(java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory) occurred while using openfeign + sentinel (#2220)
日期：2021年08月23日 09点15分



你Spring Cloud 什么版本？



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuhuangbin** [comment]
> spring cloud 是2.2.6RELEASE版本的,我感觉和spring cloud没有关系吧 是SentinelFeign类中引入了feign.hystrix中的类,加载类的时候就异常了
> […](#)
> ----- 原始邮件 ----- 发件人：余黄彬 ***@***.***> 收件人：alibaba/spring-cloud-alibaba ***@***.***> 抄送人：wanglianghczyq ***@***.***>, Author ***@***.***> 主题：Re: [alibaba/spring-cloud-alibaba] An exception(java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory) occurred while using openfeign + sentinel (#2220) 日期：2021年08月23日 09点15分 你Spring Cloud 什么版本？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你说的2.2.6.RELEASE是spring cloud alibaba的版本，我问的是Spring Cloud是什么版本

**Comment by wanglianghczyq** [comment]
<spring-cloud.version>2020.0.3</spring-cloud.version>

<dependencyManagement>       <dependency>				<groupId>org.springframework.cloud</groupId>				<artifactId>spring-cloud-dependencies</artifactId>				<version>${spring-cloud.version}</version>				<type>pom</type>				<scope>import</scope>      </dependency></dependencyManagement>
--------------------------------------spring-cloud-dependencies配置的版本如下:
<properties>    <spring-cloud-kubernetes.version>2.0.3</spring-cloud-kubernetes.version>    <spring-cloud-config.version>3.0.4</spring-cloud-config.version>    <spring-cloud-contract.version>3.0.3</spring-cloud-contract.version>    <spring-cloud-netflix.version>3.0.3</spring-cloud-netflix.version>    <spring-cloud-vault.version>3.0.3</spring-cloud-vault.version>    <spring-cloud-openfeign.version>3.0.3</spring-cloud-openfeign.version>    <spring-cloud-task.version>2.3.2</spring-cloud-task.version>    <spring-cloud-stream.version>3.1.3</spring-cloud-stream.version>    <spring-cloud-commons.version>3.0.3</spring-cloud-commons.version>    <spring-cloud-build.version>3.0.3</spring-cloud-build.version>    <spring-cloud-zookeeper.version>3.0.3</spring-cloud-zookeeper.version>    <spring-cloud-consul.version>3.0.3</spring-cloud-consul.version>    <spring-cloud-bus.version>3.0.3</spring-cloud-bus.version>    <spring-cloud-function.version>3.1.3</spring-cloud-function.version>    <spring-cloud-sleuth.version>3.0.3</spring-cloud-sleuth.version>    <spring-cloud-gateway.version>3.0.3</spring-cloud-gateway.version>    <spring-cloud-cloudfoundry.version>3.0.2</spring-cloud-cloudfoundry.version>    <main.basedir>${basedir}/../..</main.basedir>    <spring-cloud-circuitbreaker.version>2.0.2</spring-cloud-circuitbreaker.version>    <spring-cloud-cli.version>3.0.3</spring-cloud-cli.version>  </properties>


----- 原始邮件 -----
发件人：余黄彬 ***@***.***>
收件人：alibaba/spring-cloud-alibaba ***@***.***>
抄送人：wanglianghczyq ***@***.***>,  Author ***@***.***>
主题：Re: [alibaba/spring-cloud-alibaba] An exception(java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory) occurred while using openfeign + sentinel (#2220)
日期：2021年08月23日 14点32分





spring cloud 是2.2.6RELEASE版本的,我感觉和spring cloud没有关系吧 是SentinelFeign类中引入了feign.hystrix中的类,加载类的时候就异常了


…


----- 原始邮件 ----- 发件人：余黄彬 @.> 收件人：alibaba/spring-cloud-alibaba @.> 抄送人：wanglianghczyq @.>, Author @.> 主题：Re: [alibaba/spring-cloud-alibaba] An exception(java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory) occurred while using openfeign + sentinel (#2220) 日期：2021年08月23日 09点15分 你Spring Cloud 什么版本？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



你说的2.2.6.RELEASE是spring cloud alibaba的版本，我问的是Spring Cloud是什么版本



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuhuangbin** [comment]
Spring Cloud Alibaba 2.2.6.RELESE 对应 Spring Cloud H版本，你使用Spring Cloud 2020.0.3 当然会有问题，看版本关系文档吧
