### ISSUE TITLE
mq设置多个的时候,按照分组设置 tags 不起作用

### ISSUE THREAD

**Issue by SilenceRainly** [alibaba/spring-cloud-alibaba#2222]
按照这种方式 
![5708% 3A{Y8QGEH6AEHGUZF](https://user-images.githubusercontent.com/37230683/130401937-67c54717-82f5-4940-a1e5-a76e0fbcf4d0.jpg)
tags是能注册进去
但是下面这种
![XGZ S~V4AE(E6(5_}(3N3%F](https://user-images.githubusercontent.com/37230683/130402050-ef016ae9-8e53-4544-9035-46e57fc5c122.jpg)
不能被注入进去

**Comment by SilenceRainly** [comment]
希望官方大大 早点回复,版本 
        <spring-boot.version>2.3.4.RELEASE</spring-boot.version>
        <spring-cloud.version>Hoxton.SR3</spring-cloud.version>
        <alibaba-cloud.version>2.2.4.RELEASE</alibaba-cloud.version>

**Comment by zkzlx** [comment]
please try the beta version #2029 to see if it solves your problem, or provide us more information to help find the latent bug.
