### ISSUE TITLE
关于调用链路过程中，出现多种RPC调用时，如何获取链路中的上下文问题?

### ISSUE THREAD

**Issue by manonba** [alibaba/spring-cloud-alibaba#2224]
假设以下是一个客户端请求的完整的调用链路:

**客户端A**  一一http调用一一> **ServerB** 一一feign调用一一> **ServerC** 一一dubbo调用一一> **ServerD**

**问题:**

`ServerD`如何获取`客户端A`的真实`IP`地址？

**Comment by ChinaJeckXu** [comment]
ThreadLocal or MDC

**Comment by AbelSara** [comment]
Add some context fields to the entrance and exit to transmit this part of the content, and pass it locally through the thread in the internal service
