### ISSUE TITLE
SpringCloud Stream 如何设置多个rocketMQ，不同集群

### ISSUE THREAD

**Issue by windlisten** [alibaba/spring-cloud-alibaba#2225]
我的设置如下，但并不起效，正确的配置是什么？望解答
# RocketMQ1
spring.cloud.stream.binders.mq1.type = rocketmq
spring.cloud.stream.binders.mq1.environment.spring.cloud.stream.rocketmq.binder.name-server = name-server1:9876
spring.cloud.stream.bindings.someInput.binder=m1
spring.cloud.stream.bindings.someInput.destination=someTopic
spring.cloud.stream.bindings.someInput.content-type=application/json
spring.cloud.stream.bindings.someInput.group=someInput_group
spring.cloud.stream.bindings.someInput.consumer.concurrency=1

# RocketMQ2
spring.cloud.stream.binders.m2.type = rocketmq
spring.cloud.stream.binders.mq2.environment.spring.cloud.stream.rocketmq.binder.name-server = name-server2:9876
spring.cloud.stream.bindings.someInput2.binder=m2
spring.cloud.stream.bindings.someInput2.destination=someTopic
spring.cloud.stream.bindings.someInput2.content-type=application/json
spring.cloud.stream.bindings.someInput2.group=someInput2_group
spring.cloud.stream.bindings.someInput2.consumer.concurrency=1

**Comment by zkzlx** [comment]
Currenty, the rocketmq-stream not support this feature, we will consider it.
