### ISSUE TITLE
SpringBoot2.4.6 Cloud 2020.0.3 Using NACOS issues  

### ISSUE THREAD

**Issue by wanghwtaiji** [alibaba/spring-cloud-alibaba#2226]
SpringBoot2.4.6 Cloud 2020.0.3 Problem with using any version of NACOS。

2.2.1-No message output from the console, some projects failed to start

2.2.5 or later Unable to read the NACOS configuration center

How can it be used normally!!!

**Comment by wanghwtaiji** [comment]
我提问题之前  咱们的版本我都挨个试了，2021.1(boot 2.4.6  cloud 2020.0.3)的时候控制台能够正常打出，但是无法获取到nacos配置中心的内容。

**Comment by wanghwtaiji** [comment]
是不是版本兼容性的问题？ 我看Spring Cloud官网中 spring-cloud-alibaba 最新版本是2.2.1.RELEASE

**Comment by DouShaoxun** [comment]
Spring Boot 2.5.X 版本还不支持？

**Comment by wanghwtaiji** [comment]
我应该知道2021.1这个版本不行的原因了。可能关于共享配置这块的问题。我试了以下几种方式，在2021.1中，无法读取到。
#        sharedConfigs: application.yaml,application-dev.yaml  # 通过`shared-dataids`属性来指定要读取共享配置文件的`DataID`,多个文件用`,`分隔
#        shared-dataids: application.yaml,application-dev.yaml  # 通过`shared-dataids`属性来指定要读取共享配置文件的`DataID`,多个文件用`,`分隔
#        shared-configs: application.yaml,application-dev.yaml  # 通过`shared-dataids`属性来指定要读取共享配置文件的`DataID`,多个文件用`,`分隔
#        refreshable-dataids: application.yaml,application-dev.yaml # 使用`refreshable-dataids`指定共享配置文件支持自动刷新

**Comment by wanghwtaiji** [comment]
我应该知道2021.1这个版本不行的原因了。可能关于共享配置这块的问题。我试了以下几种方式，在2021.1中，无法读取到。
sharedConfigs: application.yaml,application-dev.yaml # 通过shared-dataids属性来指定要读取共享配置文件的DataID,多个文件用,分隔
shared-dataids: application.yaml,application-dev.yaml # 通过shared-dataids属性来指定要读取共享配置文件的DataID,多个文件用,分隔
shared-configs: application.yaml,application-dev.yaml # 通过shared-dataids属性来指定要读取共享配置文件的DataID,多个文件用,分隔
refreshable-dataids: application.yaml,application-dev.yaml # 使用refreshable-dataids指定共享配置文件支持自动刷新

**Comment by wanghwtaiji** [comment]
这块您能给个例子么？

**Comment by wanghwtaiji** [comment]
我再试试

**Comment by zqr95518** [comment]
我碰到了相同问题
Spring Cloud 2020.0.3
spring.cloud.alibaba 2021.1
spring-boot 2.4.10

**Comment by zqr95518** [comment]
> 我再试试

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
破案了，加个依赖就解决了

**Comment by lanbai1993** [comment]
> > 我再试试
> 
> ```
>     <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-starter-bootstrap</artifactId>
>     </dependency>
> ```
> 
> 破案了，加个依赖就解决了

boot- 2.5.4
cloud- 2020.0.3
cloud.alibaba- 2021.1
加上这个搞定了，真的无语，玩ali版本要搞半天。。。服

**Comment by yuhuangbin** [comment]
> > 我再试试
> 
> ```
>     <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-starter-bootstrap</artifactId>
>     </dependency>
> ```
> 
> 破案了，加个依赖就解决了

动态配置需要添加这个依赖是Spring Cloud 2020.x版本的新变化，升级版本最好关注下新版本的变化内容

**Comment by zqr95518** [comment]
@yuhuangbin 但是不要这个依赖把bootstrap里的内容移到application里，nacos discovery没有问题，config也不提示错误，直接不生效，这个肯定是个bug吧。
