### ISSUE TITLE
为什么配置自动刷新功能，client端会请求两次server端获取content

### ISSUE THREAD

**Issue by kangarooking** [alibaba/spring-cloud-alibaba#2230]
springCloudAlibaba2.2.6 版本 nacos-client2.0.2 nacos-server 2.0.2  
问题描述：
nacos配置中心，自动刷新配置的功能，在nacos管理界面修改相关应用配置，nacos-clinet最终会请求两次server获取具体的修改细节。确实不是nacos-client的原生逻辑，发送事件给spring的逻辑在nacos-config starter里面的NacosContextRefresher类。最后spring那边处理的过程中会重新生成上下文，在这个过程中就调用到了nacosConfigService的getConfig方法，又请求了一次server（也就是第二次请求server）
意见：因为第一次请求之后就已经将修改配置的细节存放到CacheData的content里面了，这里spring调用getConfig方法的时候是否可以直接拿CacheData 里面的content，我是觉得这里需要优化一下吧，因为本来就只需要请求一次server的。
下面是从第一次请求server到第二次请求server 代码的一个执行顺序：
第一次请求server
![第一次请求server](https://user-images.githubusercontent.com/52196004/131062232-907eb1d6-b982-406e-a0de-5e2b7e40fd75.jpg)
![获取configinfo](https://user-images.githubusercontent.com/52196004/131062260-1317a3fb-8f43-49c6-8228-15b8940cc627.jpg)

发布refresh事件
![发布refresh事件](https://user-images.githubusercontent.com/52196004/131062272-82235702-7150-4ef6-b236-12ebb09a66c8.jpg)
![刷新配置动态](https://user-images.githubusercontent.com/52196004/131062308-6ef491fe-3362-4194-a55f-0516cdce73f1.jpg)

第二次请求server
![第二次请求server](https://user-images.githubusercontent.com/52196004/131062285-7e44bc52-8659-42df-92f1-ce533a4d377c.jpg)

**Comment by kangarooking** [comment]
你们 这个 额  我在nacos发出来 他们说是来这边提 ，我现在在这边提 你们又说 提到nacos那边、。。。。。

**Comment by yuhuangbin** [comment]
你提到的这个CacheData  是属于Nacos client包中的，Spring Cloud Alibaba框架去拉取信息是通过namingService\configService去操作，具体Nacos client是走本地缓存，还是直接去Nacos Server拉取，这取决于Nacos Client的实现啊，Spring Cloud Alibaba只是使用。

**Comment by chickenlj** [comment]
related to https://github.com/alibaba/spring-cloud-alibaba/issues/3322
