### ISSUE TITLE
spring-cloud-starter-dubbo  

### ISSUE THREAD

**Issue by lexang** [alibaba/spring-cloud-alibaba#2231]
dobbo is 2.7.8   always  No provider available from registry

After restarting the service

**Comment by yuhuangbin** [comment]
try `2.2.6.RELEASE` ？

**Comment by lexang** [comment]
> try `2.2.6.RELEASE` ？

不行 试了

**Comment by lexang** [comment]
> > try `2.2.6.RELEASE` ？
> 
> 不行 试了

No, I tried that
