### ISSUE TITLE
啥时候可以release一个版本呀

### ISSUE THREAD

**Issue by jinshengyong** [alibaba/spring-cloud-alibaba#2232]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuhuangbin** [comment]
你这边是在等什么功能急用吗? 如果仅仅是相关组件版本升级的话，可以先排除原有依赖，引入你需要的版本，应该是兼容的

**Comment by jinshengyong** [comment]
> 你这边是在等什么功能急用吗? 如果仅仅是相关组件版本升级的话，可以先排除原有依赖，引入你需要的版本，应该是兼容的

就想升级一下里面组件的版本而已
