### ISSUE TITLE
spring cloud aliaba 2.2.6 RELEASE  always No provider available from registry

### ISSUE THREAD

**Issue by zzwangxin** [alibaba/spring-cloud-alibaba#2234]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

各配置版本
spring cloud alibaba.version= 2.2.6.RELEASE，
spring boot.version=2.2.13.RELEASE,
spring-cloud.version=Hoxton.SR12；
nacos:2.0.1
k8s:1.18

容器启动后

服务均注册到nacos，通过nacos管理台也可以查看到注册服务，但是访问时，提示No provider available from registry。

现像1：service服务先启动，api服务后启动，在api服务还没有启动成功并注册到nacos，这时有请求过来，提示No provider available。

现像2：service服务先启动，api服务后启动并完成注册到nacos，正常请求接口，也提示No provider available，这时候需要重启api服务或service服务。

以上问题，很困扰，而且在经常重启时，问题发生会比较频繁，还麻烦作者尽快解决这个问题，给广大it民工们一个稳定的版本，解决燃眉之急。

After container startup

All services are registered with Nacos. You can also view the registered services through the Nacos management console, but when we accessing server, you will be find question no provider available from registry.

q1: the service starts first and the API service starts later. Before the API service is started successfully and registered with Nacos, a request is sent to the server, and you will find problem no provider available.

q2: the service service starts first, then the API service starts and registers with Nacos,  a request is sent to the server, and you will find problem no provider available. At this time, you need to restart the API service or service.

The above problems are very troublesome, and the problems will occur more frequently when they are restarted frequently. It is also troublesome for the author to solve this problem as soon as possible and give the majority of it migrant workers a stable version to solve the urgent problem.

**Comment by lexang** [comment]
我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了

**Comment by jinshengyong** [comment]
> 我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了

我没遇到这问题啊，我的版本
# Sprnig Boot 2.5.4
# Spring Cloud 2020.0.3
# Spring Cloud Alibaba 2021.1
# Apache Dubbo 2.7.13
# nacos 2.0.3

**Comment by jinshengyong** [comment]
> > 我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了
> 
> 我没遇到这问题啊，我的版本
> 
> # Sprnig Boot 2.5.4
> # Spring Cloud 2020.0.3
> # Spring Cloud Alibaba 2021.1
> # Apache Dubbo 2.7.13
> # nacos 2.0.3

一直很稳定，应该是你配置问题

**Comment by zzwangxin** [comment]
配置没有问题，如果有问题，启动后，服务间接口也会调用不通。但是接口是没问题的

**Comment by lexang** [comment]
> > > 我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了
> > 
> > 
> > 我没遇到这问题啊，我的版本
> > # Sprnig Boot 2.5.4
> > # Spring Cloud 2020.0.3
> > # Spring Cloud Alibaba 2021.1
> > # Apache Dubbo 2.7.13
> > # nacos 2.0.3
> 
> 一直很稳定，应该是你配置问题

我觉得是dubbo版本的问题 你的Dubbo  版本怎么替换的

**Comment by lexang** [comment]
> > > > 我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了
> > > 
> > > 
> > > 我没遇到这问题啊，我的版本
> > > # Sprnig Boot 2.5.4
> > > # Spring Cloud 2020.0.3
> > > # Spring Cloud Alibaba 2021.1
> > > # Apache Dubbo 2.7.13
> > > # nacos 2.0.3
> > 
> > 
> > 一直很稳定，应该是你配置问题
> 
> 我觉得是dubbo版本的问题 你的Dubbo 版本怎么替换的

dubbo版本 nacos版本

**Comment by paoyingshidai** [comment]
解决方案：加上这个类
`
@Component
public class DubboRegistryAdapter implements ApplicationListener<ServiceInstancesChangedEvent> {

    @Override
    public void onApplicationEvent(ServiceInstancesChangedEvent event) {
        Collection<Registry> registries = SpringCloudRegistryFactory.getRegistries();

        for (Registry registry : registries) {
            DubboCloudRegistry dubboCloudRegistry = (DubboCloudRegistry) registry;

            dubboCloudRegistry.onApplicationEvent(event);
        }
    }
}
`

**Comment by guanweiyi** [comment]
> > > > > 我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了
> > > > 
> > > > 
> > > > 我没遇到这问题啊，我的版本
> > > > # Sprnig Boot 2.5.4
> > > > # Spring Cloud 2020.0.3
> > > > # Spring Cloud Alibaba 2021.1
> > > > # Apache Dubbo 2.7.13
> > > > # nacos 2.0.3
> > > 
> > > 
> > > 一直很稳定，应该是你配置问题
> > 
> > 
> > 我觉得是dubbo版本的问题 你的Dubbo 版本怎么替换的
> 
> dubbo版本 nacos版本

我也想知道怎么单独升dubbo，我升级后引入了其他问题，nacos的元数据变成preserved.register.source=SPRING_CLOUD了

**Comment by AndroidMilk** [comment]
> > > 我也遇到这个问题 很是影响工作效率 一度想放弃不用dubbo了
> > 
> > 
> > 我没遇到这问题啊，我的版本
> > # Sprnig Boot 2.5.4
> > # Spring Cloud 2020.0.3
> > # Spring Cloud Alibaba 2021.1
> > # Apache Dubbo 2.7.13
> > # nacos 2.0.3
> 
> 一直很稳定，应该是你配置问题

请问dubbo版本是用的哪个依赖

**Comment by AndroidMilk** [comment]
> > 解决方案：加上这个类
> > @component public class DubboRegistryAdapter implements ApplicationListener {
> > ```
> > @Override
> > public void onApplicationEvent(ServiceInstancesChangedEvent event) {
> >     Collection<Registry> registries = SpringCloudRegistryFactory.getRegistries();
> > 
> >     for (Registry registry : registries) {
> >         DubboCloudRegistry dubboCloudRegistry = (DubboCloudRegistry) registry;
> > 
> >         dubboCloudRegistry.onApplicationEvent(event);
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> 试了不起作用

`public class CustomDubboActiveProbeSubscriptionService implements ApplicationListener<ApplicationReadyEvent> {

    @Override
    public void onApplicationEvent(ApplicationReadyEvent event) {
        DubboServiceMetadataRepository dubboServiceMetadataRepository = event.getApplicationContext().getBean(DubboServiceMetadataRepository.class);
        Set<String> subscribedServices = dubboServiceMetadataRepository.getSubscribedServices();
        if (!ObjectUtils.isEmpty(subscribedServices)) {
            DiscoveryClient discoveryClient = event.getApplicationContext().getBean(DiscoveryClient.class);
            for (String subscribedService : subscribedServices) {
                log.info("主动探测订阅服务:" + subscribedService);
                ServiceInstancesChangedEvent changedEvent = new ServiceInstancesChangedEvent(subscribedService, discoveryClient.getInstances(subscribedService));
                event.getApplicationContext().publishEvent(changedEvent);
            }
        }
    }

}`

**Comment by AndroidMilk** [comment]
> > > 解决方案：加上这个类
> > > @component public class DubboRegistryAdapter implements ApplicationListener {
> > > ```
> > > @Override
> > > public void onApplicationEvent(ServiceInstancesChangedEvent event) {
> > >     Collection<Registry> registries = SpringCloudRegistryFactory.getRegistries();
> > > 
> > >     for (Registry registry : registries) {
> > >         DubboCloudRegistry dubboCloudRegistry = (DubboCloudRegistry) registry;
> > > 
> > >         dubboCloudRegistry.onApplicationEvent(event);
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > 
> > 
> > 试了不起作用
> 
> `public class CustomDubboActiveProbeSubscriptionService implements ApplicationListener {
> 
> ```
> @Override
> public void onApplicationEvent(ApplicationReadyEvent event) {
>     DubboServiceMetadataRepository dubboServiceMetadataRepository = event.getApplicationContext().getBean(DubboServiceMetadataRepository.class);
>     Set<String> subscribedServices = dubboServiceMetadataRepository.getSubscribedServices();
>     if (!ObjectUtils.isEmpty(subscribedServices)) {
>         DiscoveryClient discoveryClient = event.getApplicationContext().getBean(DiscoveryClient.class);
>         for (String subscribedService : subscribedServices) {
>             log.info("主动探测订阅服务:" + subscribedService);
>             ServiceInstancesChangedEvent changedEvent = new ServiceInstancesChangedEvent(subscribedService, discoveryClient.getInstances(subscribedService));
>             event.getApplicationContext().publishEvent(changedEvent);
>         }
>     }
> }
> ```
> 
> }`

试试这个用SPI加载

**Comment by action2013** [comment]
> 还是想知道dubbo怎么单独升级的，我这边单独升级一直报错

```
<properties>
      <spring-boot.version>2.5.5</spring-boot.version>
      <spring-cloud.version>2020.0.4</spring-cloud.version>
      <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>

      <dubbo.version>2.7.14</dubbo.version>
      <nacos.client.version>2.0.3</nacos.client.version>
  </properties>

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- dubbo 依赖，内部仅声明所有依赖，不包括starter和autoconfigure -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--
                解决
                AbstractAnnotationBeanPostProcessor中setClassValuesAsString和setNestedAnnotationsAsMap找不到 #2210:
                https://github.com/alibaba/spring-cloud-alibaba/issues/2210
            -->
            <dependency>
                <groupId>com.alibaba.spring</groupId>
                <artifactId>spring-context-support</artifactId>
                <version>1.0.11</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-autoconfigure-compatible</artifactId>
                <version>${dubbo.version}</version>
            </dependency>

            <!--Nacos-->
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>${nacos.client.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.zookeeper</groupId>
                <artifactId>zookeeper</artifactId>
                <version>3.4.12</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-log4j12</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
  </dependencies>
</dependencyManagement>
```

**Comment by haihaiya** [comment]
> 还是没有解决问题啊，作者不能解决一下@theonefx

原来不止我一个人这样，搞了两天还是找不到问题所在。难道生产者和消费者启动时间要隔一段时间么

**Comment by haihaiya** [comment]
我nacos版本为2.0.3正常依赖却无法启动，必须添加
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.4.2</version>
</dependency>
才可以正常运行
