### ISSUE TITLE
端口冲突后没有调用NacosWatch.stop方法

### ISSUE THREAD

**Issue by wangYX657211334** [alibaba/spring-cloud-alibaba#2238]
**Which Component**
Nacos Discovery

**Describe the bug**
端口冲突后没有调用`NacosWatch.stop`方法, Naocs中的user-thread仍然在运行, 导致进程不退出

**To Reproduce**
1. 开启 Nacos Discovery
2. 指定一个已存在的端口, 并启动应用程序

**Expected behavior**
进程因端口冲突而退出

**Screenshots**
![image](https://user-images.githubusercontent.com/17154662/131813692-e19db042-8416-43d9-92ea-8d3a86e48ee9.png)
blocking...

**Additional context**
Windows, Java8, Version 2.2.6.RELEASE

**Some advice**
`NacosWatch` 实现`DisposableBean`接口, 实现`destroy` 方法, 方法体如下:
``` java
public void destroy(){
        this.stop();
}
```
或者
`NacosWatch` 删除 `SmartLifecycle`实现, 改为 `InitializingBean`和`DisposableBean`

**Comment by wangYX657211334** [comment]
请问这个问题打算如何解决呢?

**Comment by netfreeperson** [comment]
> 请问这个问题打算如何解决呢?

请问这个问题怎么解决，我也遇到了
