### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by zhangOranges** [alibaba/spring-cloud-alibaba#2239]
Spring Cloud Version       Spring Cloud Alibaba Version     Spring Boot Version
Spring Cloud 2020.0.1      2021.1                                         2.4.2 
当前我使用的是这些版本
但是我项目中使用spring-cloud-starter-dubbo启动后会出现NoClassDefFoundError javax/ws/rs/Path
查看后发现feign.jaxrs2:9.7.0的scope为provided，这是为什么要这样做呢

I am currently using these versions

However, the NoClassDefFoundError javax / WS / RS / path will appear after using spring cloud starter Dubbo to start my project

After checking, I found that the scope of feign. Jaxrs2: 9.7.0 is provided. Why

**Comment by liukeshao** [comment]
使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud

**Comment by zhangOranges** [comment]
> 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud

是有什么问题么，可以详细说下么

**Comment by liukeshao** [comment]
> > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> 
> 是有什么问题么，可以详细说下么

- dubbo服务注册机制和spring cloud的不一样
- 单独重启服务，会报 no provider 异常，2021分支
- 这个项目更新非常慢，尤其对dubbo支持
- 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持

**Comment by zhangOranges** [comment]
> > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > 
> > 
> > 是有什么问题么，可以详细说下么
> 
> * dubbo服务注册机制和spring cloud的不一样
> * 单独重启服务，会报 no provider 异常，2021分支
> * 这个项目更新非常慢，尤其对dubbo支持
> * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持

好的，感谢

**Comment by shihuaguo** [comment]
> > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > 
> > 
> > 是有什么问题么，可以详细说下么
> 
> * dubbo服务注册机制和spring cloud的不一样
> * 单独重启服务，会报 no provider 异常，2021分支
> * 这个项目更新非常慢，尤其对dubbo支持
> * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持

jdk17应该是9.14发布吧？

**Comment by liukeshao** [comment]
> > > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > > 
> > > 
> > > 是有什么问题么，可以详细说下么
> > 
> > 
> > 
> > * dubbo服务注册机制和spring cloud的不一样
> > * 单独重启服务，会报 no provider 异常，2021分支
> > * 这个项目更新非常慢，尤其对dubbo支持
> > * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持
> 
> jdk17应该是9.14发布吧？

是的 https://openjdk.java.net/projects/jdk/17/
因为以下jep，dubbo不支持jdk17
[jep 396](https://openjdk.java.net/jeps/396)
[jep 403](https://openjdk.java.net/jeps/403)

**Comment by shihuaguo** [comment]
> > > > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > > > 
> > > > 
> > > > 是有什么问题么，可以详细说下么
> > > 
> > > 
> > > 
> > > * dubbo服务注册机制和spring cloud的不一样
> > > * 单独重启服务，会报 no provider 异常，2021分支
> > > * 这个项目更新非常慢，尤其对dubbo支持
> > > * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持
> > 
> > 
> > jdk17应该是9.14发布吧？
> 
> 是的 https://openjdk.java.net/projects/jdk/17/
> 因为以下jep，dubbo不支持jdk17
> [jep 396](https://openjdk.java.net/jeps/396)
> [jep 403](https://openjdk.java.net/jeps/403)

我大致看了下这两个jep，在jep403，虽然不能再使用--illegal-access，但是还是可以使用--add-opens来访问特定的package。而且对于”critical internal APIs“，这些仍然是可以继续用反射访问的。为啥dubbo不能支持呢？

**Comment by liukeshao** [comment]
> > > > > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > > > > 
> > > > > 
> > > > > 是有什么问题么，可以详细说下么
> > > > 
> > > > 
> > > > 
> > > > * dubbo服务注册机制和spring cloud的不一样
> > > > * 单独重启服务，会报 no provider 异常，2021分支
> > > > * 这个项目更新非常慢，尤其对dubbo支持
> > > > * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持
> > > 
> > > 
> > > jdk17应该是9.14发布吧？
> > 
> > 
> > 是的 https://openjdk.java.net/projects/jdk/17/
> > 因为以下jep，dubbo不支持jdk17
> > [jep 396](https://openjdk.java.net/jeps/396)
> > [jep 403](https://openjdk.java.net/jeps/403)
> 
> 我大致看了下这两个jep，在jep403，虽然不能再使用--illegal-access，但是还是可以使用--add-opens来访问特定的package。而且对于”critical internal APIs“，这些仍然是可以继续用反射访问的。为啥dubbo不能支持呢？

可以看一下这个issue [dubbo#7593l](https://github.com/apache/dubbo/issues/7593l)
dubbo使用了不合适的api [jboss-javassist/javassist#369](https://github.com/jboss-javassist/javassist/issues/369)

**Comment by liukeshao** [comment]
> > > > > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > > > > 
> > > > > 
> > > > > 是有什么问题么，可以详细说下么
> > > > 
> > > > 
> > > > 
> > > > * dubbo服务注册机制和spring cloud的不一样
> > > > * 单独重启服务，会报 no provider 异常，2021分支
> > > > * 这个项目更新非常慢，尤其对dubbo支持
> > > > * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持
> > > 
> > > 
> > > jdk17应该是9.14发布吧？
> > 
> > 
> > 是的 https://openjdk.java.net/projects/jdk/17/
> > 因为以下jep，dubbo不支持jdk17
> > [jep 396](https://openjdk.java.net/jeps/396)
> > [jep 403](https://openjdk.java.net/jeps/403)
> 
> 我大致看了下这两个jep，在jep403，虽然不能再使用--illegal-access，但是还是可以使用--add-opens来访问特定的package。而且对于”critical internal APIs“，这些仍然是可以继续用反射访问的。为啥dubbo不能支持呢？

可以看一下这个issue apache/dubbo#7593
dubbo使用了不合适的api jboss-javassist/javassist#369

**Comment by shihuaguo** [comment]
> * dubbo服务注册机制和spring cloud的不一样

好的，谢谢。公司内部项目已经从spring cloud alibaba改为单体应用了。小公司使用这种架构真的是没啥必要。

**Comment by shihuaguo** [comment]
> > > > > > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > > > > > 
> > > > > > 
> > > > > > 是有什么问题么，可以详细说下么
> > > > > 
> > > > > 
> > > > > 
> > > > > * dubbo服务注册机制和spring cloud的不一样
> > > > > * 单独重启服务，会报 no provider 异常，2021分支
> > > > > * 这个项目更新非常慢，尤其对dubbo支持
> > > > > * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持
> > > > 
> > > > 
> > > > jdk17应该是9.14发布吧？
> > > 
> > > 
> > > 是的 https://openjdk.java.net/projects/jdk/17/
> > > 因为以下jep，dubbo不支持jdk17
> > > [jep 396](https://openjdk.java.net/jeps/396)
> > > [jep 403](https://openjdk.java.net/jeps/403)
> > 
> > 
> > 我大致看了下这两个jep，在jep403，虽然不能再使用--illegal-access，但是还是可以使用--add-opens来访问特定的package。而且对于”critical internal APIs“，这些仍然是可以继续用反射访问的。为啥dubbo不能支持呢？
> 
> 可以看一下这个issue [apache/dubbo#7593](https://github.com/apache/dubbo/issues/7593)
> dubbo使用了不合适的api [jboss-javassist/javassist#369](https://github.com/jboss-javassist/javassist/issues/369)

JEP401、402、417等大概在哪个版本能集成进去？

**Comment by liukeshao** [comment]
> > > > > > > > 使用经验：用spring cloud就别用dubbo，用dubbo就别用spring cloud
> > > > > > > 
> > > > > > > 
> > > > > > > 是有什么问题么，可以详细说下么
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > * dubbo服务注册机制和spring cloud的不一样
> > > > > > * 单独重启服务，会报 no provider 异常，2021分支
> > > > > > * 这个项目更新非常慢，尤其对dubbo支持
> > > > > > * 如果你计划使用jdk 17，就不要使用dubbo，dubbo不支持
> > > > > 
> > > > > 
> > > > > jdk17应该是9.14发布吧？
> > > > 
> > > > 
> > > > 是的 https://openjdk.java.net/projects/jdk/17/
> > > > 因为以下jep，dubbo不支持jdk17
> > > > [jep 396](https://openjdk.java.net/jeps/396)
> > > > [jep 403](https://openjdk.java.net/jeps/403)
> > > 
> > > 
> > > 我大致看了下这两个jep，在jep403，虽然不能再使用--illegal-access，但是还是可以使用--add-opens来访问特定的package。而且对于”critical internal APIs“，这些仍然是可以继续用反射访问的。为啥dubbo不能支持呢？
> > 
> > 
> > 可以看一下这个issue [apache/dubbo#7593](https://github.com/apache/dubbo/issues/7593)
> > dubbo使用了不合适的api [jboss-javassist/javassist#369](https://github.com/jboss-javassist/javassist/issues/369)
> 
> JEP401、402、417等大概在哪个版本能集成进去？

不知道，我一个吃瓜群众
