### ISSUE TITLE
Configration Item 'spring.cloud.sentinel.datasource.ds4.apollo.default-flow-rule-value' Not Work

### ISSUE THREAD

**Issue by Hans-Kl** [alibaba/spring-cloud-alibaba#2244]
用apollo作为动态数据源时，有一个`spring.cloud.sentinel.datasource.ds4.apollo.default-flow-rule-value`配置，但我不知道如何正确的使用它。
这个配置在`com.alibaba.cloud.sentinel.datasource.config.ApolloDataSourceProperties`定义的数据类型是String，所以我配置数组类型value，类似`[{resource: TestResource,controlBehavior: 0,count: 100,grade: 1,limitApp: default,strategy: 0}]`这样的value时，SpringBoot无法帮我解析，导致解析后的值是null，和没有配置一个效果。
我可以用String来表达限流规则？还是说这是一个bug？

**Comment by yuhuangbin** [comment]
问题描述不够清楚，`spring.cloud.sentinel.datasource.ds4.apollo.default-flow-rule-value` 配置项是一个默认的兜底配置，
`spring.cloud.sentinel.datasource.ds4.apollo.default-flow-rule-value=[{"resource": "/hello","grade": 1}]` 
如上配置能正常解析
