### ISSUE TITLE
引入nacos的依赖导致thymeleaf找不到视图

### ISSUE THREAD

**Issue by lionel-coderm** [alibaba/spring-cloud-alibaba#2246]
springCloud 2.x版本 引入nacos的依赖之后，会导致thymeleaf 视图解析不到
具体依赖版本如下
        <spring.cloud-version>Hoxton.SR11</spring.cloud-version>
        <alibaba.cloud.version>2.2.5.RELEASE</alibaba.cloud.version>
        <boot.version>2.2.13.RELEASE</boot.version>

**Comment by yuhuangbin** [comment]
请安装版本说明修改Spring Boot/Spring Cloud/Spring Cloud Alibaba三者的对应版本，然后再试试
<spring.cloud-version>Hoxton.SR9</spring.cloud-version>
<alibaba.cloud.version>2.2.6.RELEASE</alibaba.cloud.version>
<boot.version>2.3.2.RELEASE</boot.version>

https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by lionelkali** [comment]
修改之后还是这样报错信息如下：

`org.thymeleaf.exceptions.TemplateInputException: Error resolving template [test], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]`

去除掉 一下两个依赖就不会报错，视图正常渲染
`        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>`
