### ISSUE TITLE
关于NacosServiceDiscovery类中getInstances方法的问题

### ISSUE THREAD

**Issue by wushengju** [alibaba/spring-cloud-alibaba#2247]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos服务发现通过serviceId获取ServiceInstance列表时，代码如下所示:
public List<ServiceInstance> getInstances(String serviceId) throws NacosException {
		String group = discoveryProperties.getGroup();
		List<Instance> instances = namingService().selectInstances(serviceId, group,
				true);
		return hostToServiceInstanceList(instances, serviceId);
	}
我的问题是这里为啥不需要传入clusters参数，在注册使用如下代码及clusterName=DEFAULT
private Instance getNacosInstanceFromRegistration(Registration registration) {
		Instance instance = new Instance();
		instance.setIp(registration.getHost());
		instance.setPort(registration.getPort());
		instance.setWeight(nacosDiscoveryProperties.getWeight());
//设置了clusterName
		instance.setClusterName(nacosDiscoveryProperties.getClusterName());
		instance.setEnabled(nacosDiscoveryProperties.isInstanceEnabled());
		instance.setMetadata(registration.getMetadata());
		instance.setEphemeral(nacosDiscoveryProperties.isEphemeral());
		return instance;
	}

如果未设置，会生成多一份实例数据在内存中

**Comment by yuhuangbin** [comment]
一个是服务发现，一个服务注册，你说的多一份数据具体是什么意思？能详细描述吗？
