### ISSUE TITLE
Nacos: support 'spring.config.import'

### ISSUE THREAD

**Issue by mailingfeng** [alibaba/spring-cloud-alibaba#2266]
Nacos

Spring Boot 2.4 introduced a new way to import configuration data via the `spring.config.import` property, and Spring Cloud 2020.0.x (consul) already support.

i see the Spring-Cloud-Alibaba `2021.1` is the first version that supports the 2020 version of spring cloud, but can not found about `spring.config.import`.

What time Spring-Cloud-Alibaba (nacos) will follow up and support it?

thanks

**Comment by mailingfeng** [comment]
keep attention

**Comment by steverao** [comment]
> keep attention

If you have time, you can do it together：）

**Comment by DanielLiu1123** [comment]
see #2349
