### ISSUE TITLE
SpringCloudDubbo注册到Nacos中，无法看到Dubbo接口。

### ISSUE THREAD

**Issue by yun19830206** [alibaba/spring-cloud-alibaba#2267]
**Which Component**
Nacos Register, Dubbo

**Describe the bug**
SpringCloudDubbo注册到Nacos中，无法看到Dubbo接口。

**To Reproduce**
我有一个应用，使用Nacos作为注册中心，Dubbo提供服务接口，服务提供者启动完成之后，在Nacos控制台中，能够看到注册的服务，但是无法在Nacos配置列表中看到 服务提供者注册的dubbo接口。
我试了nacos版本1.1.4与1.4.2都不可以。
注册服务的依赖如下：
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-dubbo</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
</dependency>
配置文件信息
dubbo.registry.address=spring-cloud://localhost
spring.cloud.nacos.discovery.server-addr=localhost:8848

**Expected behavior**
期待在Nacos控制台的配置列表中 能够看到注册成功的dubbo服务提供者的所有接口列表

**Additional context**
Java8
spring-cloud-alibaba-dependencies<version>2.2.5.RELEASE</version>
spring-cloud-dependencies<version>Hoxton.SR8</version>
spring-boot-dependencies<version>2.3.2.RELEASE</version>

**Comment by yuhuangbin** [comment]
服务注册跟配置没有关系，服务注册成功在服务列表查看就行
