### ISSUE TITLE
NacosServiceRegistry类里引用NacosServiceManager的方式问题

### ISSUE THREAD

**Issue by wf2311** [alibaba/spring-cloud-alibaba#2271]
版本：2.2.6
https://github.com/alibaba/spring-cloud-alibaba/blob/387dd46fa4d037dad3d7091fca2274d4cc1d5034/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java#L40-L60

在NacosServiceRegistry里引用NacosServiceManager是采用直接注入的方式，当在我想在项目中实现注册多个Nacos注册中心时，就没办法复用此类，建议引用NacosServiceManager的方式和引用NacosDiscoveryProperties保持一致，都通过构造函数引入:

From Google Translate:
NacosServiceManager is referenced in NacosServiceRegistry by direct injection. When I want to register multiple Nacos registries in the project, there is no way to reuse this type. It is recommended that the method of referencing NacosServiceManager and referencing NacosDiscoveryProperties are consistent, both through construction Function introduction:

```java
    private final NacosDiscoveryProperties nacosDiscoveryProperties;

    private final NacosServiceManager nacosServiceManager;

    public NacosServiceRegistry(NacosServiceManager nacosServiceManager, NacosDiscoveryProperties nacosDiscoveryProperties) {
        this.nacosServiceManager = nacosServiceManager;
        this.nacosDiscoveryProperties = nacosDiscoveryProperties;
    }
```

**Comment by yuhuangbin** [comment]
欢迎贡献pr

**Comment by Jack9610** [comment]
> 欢迎贡献pr

你说话怎么那么高冷🙄
