### ISSUE TITLE
Sidecar无法注册服务

### ISSUE THREAD

**Issue by oSunnyo** [alibaba/spring-cloud-alibaba#2273]
![image](https://user-images.githubusercontent.com/8553780/134891451-bc3671e5-c203-4d8d-8dd5-bb40d96c74af.png)
此处逻辑是否有问题？导致异构的服务无法注册到服务中心。
方法位置：com.alibaba.cloud.sidecar.SidecarHealthChecker#check

**Comment by yuhuangbin** [comment]
这里是服务健康检查的逻辑，有什么问题？ 方便具体说明一下吗?

**Comment by oSunnyo** [comment]
不知道服务注册的入口就是这里，如果是那么在第一次注册服务的时候方框里的代码是创建缓存并保存到MAP，然后是如果状态为UP就先检查一下是否需要注册，但检查是否需要注册的逻辑是对比缓存，此方法永远返回false，导致服务永远不会被注册。

**Comment by yuhuangbin** [comment]
> 注册的逻辑是对比缓存，此方法永远返回false，

上面已经说了，这里是服务健康检查的处理，第一次注册服务并不是在这里处理

**Comment by yuhuangbin** [comment]
你的问题仅仅是通过自己看代码觉得有问题吗? 你可以动手实践一下
