### ISSUE TITLE
No provider available from registry localhost:9090 for service xxx/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0 on consumer 172.26.160.1 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).

### ISSUE THREAD

**Issue by coder-michaelwu** [alibaba/spring-cloud-alibaba#2274]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**

**zookeeper** Discovery, dubbo

**Describe the bug**

服务消费者在服务提供方之前启动就出现这个错，而且是必现，非偶发。
This error occurs when the service consumer starts up before service provider, and it is inevitable, not accidental.

**Additional context**
Windows10  、Java8 、zookeeper 单点
```
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR9</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.3.12.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.6.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by coder-michaelwu** [comment]
我发现加上这个参数` dubbo.consumer.check=false ` 可以避免这个问题产生。 
I found this problem could be avoided by adding the argument `dubo.consumer.check =false` .

**Comment by coder-michaelwu** [comment]
另外当服务提供方的`dubbo.application.name` 和 `spring.application.name` 配置不一样时，也会出现这个问题。
This problem also occurs when the value of the service provider's parameters ,`dubo.application.name`and `spring.application.name`, are configured differently.

**Comment by chenqincheng** [comment]
2.2.6.RELEASE 版本。这个问题还存在！！！

**Comment by KabourWu** [comment]
> 2.2.6.RELEASE 版本。这个问题还存在！！！

我也碰到了...

**Comment by winterallen** [comment]
SpringBoot：

**Comment by winterallen** [comment]
spring.boot.version=2.3.2.RELEASE
spring.cloud.version=Hoxton.SR8
spring.cloud.alibaba.version=2.2.6.RELEASE
同样的问题

**Comment by CHN-djt** [comment]
使用版本：
spring.boot.version=2.3.2.RELEASE
spring.cloud.version=Hoxton.SR8
spring.cloud.alibaba.version=2.2.6.RELEASE
注册中心使用为nacos

被这个问题困扰半年之久，也一直在关注这个问题的处理情况，然而。。。
经过几天的爬资料，也重新研究了一下官方的Samples，实验发现将
dubbo.registry.address=spring-cloud://localhost
改为dubbo.registry.address=nacos://localhost:8848
（有另一个isseue中有个评论也有提到这么改）
不会出现上述no provider的问题了！
但是由此又引发两个问题：
1.启动报错提示Class Not Found: org.apache.commons.lang3.StringUtils，这个通过导入依赖可解决；
2.将dubbo注册地址改成nacos之后，所有的dubbo服务都会出现在服务列表。当使用了spring-boot-admin，其仍然去检测每个服务的在线状态，但又无法正常检测dubbo服务（出现检测异常），故它又将dubbo服务标记下线。那这个时候spring-boot-admin又没法正常使用了。。当dubbo服务注册中心为spring-cloud时，spring-boot-admin是可以正常工作和正常显示

**Comment by lcx0603** [comment]
spring.boot.version=2.3.2.RELEASE
spring.cloud.version=Hoxton.SR9
spring.cloud.alibaba.version=2.2.6.RELEASE
同样的问题

**Comment by haihaiya** [comment]
spring.boot.version=2.3.12.RELEASE
spring.cloud.version=Hoxton.SR12
spring.cloud.alibaba.version=2.2.7.RELEASE
一样出现了这个问题各种方案都试了无法解决

**Comment by abelyang** [comment]
> 我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。 We recommend using English. If you are non-native English speaker, you can use the translation software.
> 
> **Which Component**
> 
> **zookeeper** Discovery, dubbo
> 
> **Describe the bug**
> 
> 服务消费者在服务提供方之前启动就出现这个错，而且是必现，非偶发。 This error occurs when the service consumer starts up before service provider, and it is inevitable, not accidental.
> 
> **Additional context** Add any other context about the problem here. Windows10 、Java8 、zookeeper 单点
> 
> ```
>             <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-dependencies</artifactId>
>                 <version>Hoxton.SR9</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>             <dependency>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-dependencies</artifactId>
>                 <version>2.3.12.RELEASE</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>             <dependency>
>                 <groupId>com.alibaba.cloud</groupId>
>                 <artifactId>spring-cloud-alibaba-dependencies</artifactId>
>                 <version>2.2.6.RELEASE</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> ```

This problem is mostly caused by the fact that the producer registered on Nacos does not safely remove the producer's node from the registry Nacos in advance (including closing traffic and deleting instances) when it exits (for example, during redeployment), and the Nacos client owned by other consumers registered on Nacos (including gateway and other provider consumers) because the Nacos client has a default self discovery mechanism with a maximum length of 30s, if it happens to be in the empty window period within 30s, the problem described by you will appear;

Recommendations:

1. When redeploying, ensure that the producer has other available nodes

2. You can reasonably adjust the default 30s of Nacos client self discovery



这个问题大部分都是因为注册在 nacos 上的生产者退出时（例如重新部署时）没有提前把这个生产者的节点从注册中心nacos上安全移出（包括关闭流量、删除实例）而造成的，而注册在nacos上的其他消费者所拥有的的nacos-client（包括gateway和其他provider消费者） 因为是nacos-client有个默认最长30s的自发现机制，如果刚好在这30s内的空窗期，就会出现你描述的问题；
建议：
1.重新部署时，保证该producer有其他的可用节点
2.可以合理向下调整nacos-client自己自发现默认的30s

**Comment by coder-michaelwu** [comment]
@abelyang 我使用的注册中心是zookeeper，而非nacos，另外我的前提条件是服务消费者在服务提供方之前启动。也就是说在注册中心中是没有服务实例的。
The registry I used is ZooKeeper, not Nacos, and my prerequisite is that the service consumer starts up before the service provider. That means there are no instances of the service provider in the registry.

**Comment by qinyinglun** [comment]
spring.boot.version=2.3.2.RELEASE
spring.cloud.version=Hoxton.SR8
spring.cloud.alibaba.version=2.2.6.RELEASE
同样的问题

**Comment by Zhaowenhor** [comment]
> 

我跟你版本一样，同样的问题。

**Comment by Zhaowenhor** [comment]
spring.boot.version=2.3.2.RELEASE
spring.cloud.version=Hoxton.SR9
spring.cloud.alibaba.version=2.2.6.RELEASE
同样的问题
