### ISSUE TITLE
Spring Cloud Alibaba 2020 分支的什么时候可以发布一个版本呀，能不能升级一下里面的依赖哦

### ISSUE THREAD

**Issue by jinshengyong** [alibaba/spring-cloud-alibaba#2279]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by steverao** [comment]
> 怕是要被放弃了，项目经常20+天没有任何动静

前段时间因为内部人员调整，所以项目维护进展较慢，后续会继续维护更新的，也欢迎一起参与进来！

**Comment by LiuXiaoJie** [comment]
确实是很久没更新了 @steverao

**Comment by steverao** [comment]
We will release relevant version next week!
