### ISSUE TITLE
Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by luosm** [alibaba/spring-cloud-alibaba#2283]
when use  `SpringApplication.exit` to stop the application
class     com.alibaba.cloud.nacos.NacosServiceManager 
method nacosServiceShutDown() will run twice , and the second time  there is a `this.namingService.shutDown();`   NPE

![image](https://user-images.githubusercontent.com/21169802/138418241-cd513309-cbef-4ba5-9f36-e62e154a76dc.png)

**The first run stack**

`
nacosServiceShutDown:116, NacosServiceManager (com.alibaba.cloud.nacos)
close:120, NacosServiceRegistry (com.alibaba.cloud.nacos.registry)
stop:268, AbstractAutoServiceRegistration (org.springframework.cloud.client.serviceregistry)
destroy:201, AbstractAutoServiceRegistration (org.springframework.cloud.client.serviceregistry)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
invoke:389, InitDestroyAnnotationBeanPostProcessor$LifecycleElement (org.springframework.beans.factory.annotation)
invokeDestroyMethods:347, InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata (org.springframework.beans.factory.annotation)
postProcessBeforeDestruction:177, InitDestroyAnnotationBeanPostProcessor (org.springframework.beans.factory.annotation)
destroy:184, DisposableBeanAdapter (org.springframework.beans.factory.support)
destroyBean:587, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
destroySingleton:559, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
destroySingleton:1152, DefaultListableBeanFactory (org.springframework.beans.factory.support)
destroySingletons:520, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
destroySingletons:1145, DefaultListableBeanFactory (org.springframework.beans.factory.support)
destroyBeans:1106, AbstractApplicationContext (org.springframework.context.support)
doClose:1075, AbstractApplicationContext (org.springframework.context.support)
doClose:172, ServletWebServerApplicationContext (org.springframework.boot.web.servlet.context)
close:1021, AbstractApplicationContext (org.springframework.context.support)
close:1401, SpringApplication (org.springframework.boot)
exit:1388, SpringApplication (org.springframework.boot)
lambda$main$0:34, QueryApiApplication (com.totok.lottery.query.api.web)
run:-1, 1606954469 (com.totok.lottery.query.api.web.QueryApiApplication$$Lambda$1236)
run:748, Thread (java.lang)
`
![image](https://user-images.githubusercontent.com/21169802/138415365-dab71e3f-0813-459d-99e6-0d78a73252cf.png)

**The second run stack**

`
nacosServiceShutDown:115, NacosServiceManager (com.alibaba.cloud.nacos)
close:120, NacosServiceRegistry (com.alibaba.cloud.nacos.registry)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
invokeCustomDestroyMethod:281, DisposableBeanAdapter (org.springframework.beans.factory.support)
destroy:215, DisposableBeanAdapter (org.springframework.beans.factory.support)
destroyBean:587, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
destroySingleton:559, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
destroySingleton:1152, DefaultListableBeanFactory (org.springframework.beans.factory.support)
destroySingletons:520, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
destroySingletons:1145, DefaultListableBeanFactory (org.springframework.beans.factory.support)
destroyBeans:1106, AbstractApplicationContext (org.springframework.context.support)
doClose:1075, AbstractApplicationContext (org.springframework.context.support)
doClose:172, ServletWebServerApplicationContext (org.springframework.boot.web.servlet.context)
close:1021, AbstractApplicationContext (org.springframework.context.support)
close:1401, SpringApplication (org.springframework.boot)
exit:1388, SpringApplication (org.springframework.boot)
lambda$main$0:34, QueryApiApplication (com.totok.lottery.query.api.web)
run:-1, 1606954469 (com.totok.lottery.query.api.web.QueryApiApplication$$Lambda$1236)
run:748, Thread (java.lang)
`
![image](https://user-images.githubusercontent.com/21169802/138415483-76e358e9-bc17-4a91-b10c-132fd3dd91c7.png)

 MacOS  、Java8  
com.alibaba.cloud         2.2.6.RELEASE
alibaba.nacos.version   2.0.3
dubbo.version 2.7.14 
spring.data.version 2.5.3
spring.boot.version 2.5.3
spring.cloud.dependencies.version 2020.0.3

I am looking forward to your answer

**Comment by shijiebei2009** [comment]
@steverao does 2021.0.5.0 verion not fix this problem?

**Comment by steverao** [comment]
> @steverao does 2021.0.5.0 verion not fix this problem?

You encountered the problem again in 2021.0.5.0?

**Comment by xinger321** [comment]
我升级到2.2.8.RELEASE仍然遇到这个问题了。

**Comment by xinger321** [comment]
springboot版本 2.3.12.RELEASE
spring-alibaba版本2.2.8.RELEASE

**Comment by xinger321** [comment]
springboot版本 2.3.12.RELEASE
spring-alibaba版本2.2.8.RELEASE 仍然遇到这个问题了。
