### ISSUE TITLE
循环依赖时，偶现消费者有时候会出现找不到服务

### ISSUE THREAD

**Issue by xshiyu** [alibaba/spring-cloud-alibaba#2285]
版本：spring-cloud-starter-dubbo-2.2.6.RELEASE
过程：A服务通过subscribed-services配置订阅B服务，B服务通过subscribed-services订阅A服务
结果：偶发的会出现一方消费者，订阅不到服务，通过 http://actuator/dubboRegistryDirectory 查看，信息基本为空
暂时的解决办法：
查看源码：
@EventListener(HeartbeatEvent.class)
public void onHeartbeatEvent(HeartbeatEvent event) {
/**
	* Try to re-initialize the subscribed services, in order to sense the change of
	* services if {@link DubboCloudProperties#getSubscribedServices()} is wildcard
	* that indicates all services should be subscribed.
	*/
Stream<String> subscribedServices = dubboServiceMetadataRepository
		.initSubscribedServices();

heartbeatEventChangedPredicate.ifAvailable(predicate -> {
	if (predicate.test(event)) {
		// Dispatch ServiceInstancesChangedEvent for each service
		subscribedServices.forEach(serviceName -> {
			List<ServiceInstance> serviceInstances = getInstances(serviceName);
			dispatchServiceInstancesChangedEvent(serviceName, serviceInstances);
		});
	}
});
}
在心跳时，会主动调用dispatchServiceInstancesChangedEvent方法，但是predicate.test(event)始终返回false，我并不清楚这里为什么一定要始终返回false，谁能帮助解答一下
@Bean
public Predicate<HeartbeatEvent> heartbeatEventChangedPredicate() {
    return event -> false;
}
目前的解决办法是，在自己的项目中覆盖heartbeatEventChangedPredicate这个bean，修改它的返回值为true，让它在心跳的时候，主动调用dispatchServiceInstancesChangedEvent方法
@Bean
public Predicate<HeartbeatEvent> heartbeatEventChangedPredicate() {
    return event -> true;
}

**Comment by pe1221** [comment]
这个问题什么时候能解决呀
