### ISSUE TITLE
快速失败为什么主进程还在运行

### ISSUE THREAD

**Issue by lualeslie** [alibaba/spring-cloud-alibaba#2288]
升级后的客户端依赖版本：spring-cloud-starter-alibaba-nacos-discovery2.2.6.RELEASE+nacos-client1.4.2
升级前的客户端依赖版本：spring-cloud-starter-alibaba-nacos-discovery2.2.5.RELEASE+nacos-client1.4.1

spring-cloud-starter-alibaba-nacos-discovery2.2.6.RELEASE新增了一个快速失败的配置spring.cloud.nacos.discovery.failFast，spring-cloud-starter-alibaba-nacos-discovery2.2.5.RELEASE代码中是默认快速失败的，新版本增加了一个配置项，但是设置了spring.cloud.nacos.discovery.failFast=true之后的表现与旧版本不太一样。

问题描述：
升级前，客户端应用解析nacos服务端地址失败，会直接抛出异常UndeclaredThrowableException，然后应用注册失败，最后主进程会停止。但是升级后，客户端应用解析nacos服务端地址失败，也会直接抛出异常UndeclaredThrowableException，然后应用注册失败，但是主进程仍在运行中，并没有停止，想问下具体的原因是什么？代码层面改动了什么？

**Comment by yuhuangbin** [comment]
refer : #2104

**Comment by steverao** [comment]
确实存在这个问题，在2.2.6版本中，spring.cloud.nacos.discovery.failFast这个开关无论开启还是关闭应用进程都还是一直处于运行状态！

**Comment by lualeslie** [comment]
我这边昨天排查发现，nacosWatch这个修改了构造方法，原来是传入ObjectProvider<ThreadPoolTaskScheduler>，现在新版本是new一个ThreadPoolTaskScheduler，然后调试的时候发现回调stop方法没有被触发，导致任务线程池没有shutdown，所以进程一直没有被关闭，想问下你们有检查过这个问题嘛？比较好奇为什么SmartLifeCycle类的stop没有执行？

**Comment by steverao** [comment]
是的，你说的是对的，在2.2.7中我们已经修复了这个问题，具体可以看一下代码！
