### ISSUE TITLE
nacos-config升级到2021.1版本以后，启动时获取的配置不会打印到控制台

### ISSUE THREAD

**Issue by zqr95518** [alibaba/spring-cloud-alibaba#2293]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-alibaba-nacos-config

**Describe the bug**
nacos-config升级到2021.1版本以后，启动时获取的配置不会打印到控制台
After nacos-config is upgraded to version 2021.1, the configuration obtained at startup will not be printed to the console.

**To Reproduce**
1. 配置好nacos 
2. 正常启动服务

1. Configure nacos
2. Start the service normally

**Expected behavior**
启动时打印获取到的配置到控制台
Print the acquired configuration to the console at startup

**Additional context**
spring-boot 2.4.12
spring-cloud-alibaba-nacos-discovery 2021.1
spring-cloud-alibaba-nacos-config 2021.1
nacos server 2.0.3

**Comment by steverao** [comment]
配置信息吗？之前的版本好像也是不行的吧？另外问一下你为什么要打印在控制台呀？

**Comment by zqr95518** [comment]
> 配置信息吗？之前的版本好像也是不行的吧？另外问一下你为什么要打印在控制台呀？

2.1.1.RELEASE的时候还是有的，启动的时候打印配置比较方便观察配置有没有生效。

**Comment by steverao** [comment]
> > 配置信息吗？之前的版本好像也是不行的吧？另外问一下你为什么要打印在控制台呀？
> 
> 2.1.1.RELEASE的时候还是有的，启动的时候打印配置比较方便观察配置有没有生效。 可不可以把这个做成配置，默认关闭。

打印到控制台一般需求还是比较少的吧，生产环境一般也主要是看日志了

**Comment by steverao** [comment]
不过有兴趣的话，也可以尝试一下贡献到社区来哈：）

**Comment by zqr95518** [comment]
主要是以前有过这个功能，升级框架了以后没有了现场部署的时候不能直接检查配置有没有问题了

**Comment by zkzlx** [comment]
我记得这个是某个版本中是默认关闭的，有个配置可以开启的，可以翻下源码，在nacos-client中

**Comment by zqr95518** [comment]
> 貌似从某个版本中开始就是默认关闭的，有个配置可以开启的，可以翻下源码，在nacos-client中

对nacos的源码不熟，能不能指点一下_(:з」∠)_

**Comment by steverao** [comment]
> > 貌似从某个版本中开始就是默认关闭的，有个配置可以开启的，可以翻下源码，在nacos-client中
> 
> 对nacos的源码不熟，能不能指点一下_(:з」∠)_

刚看了一下源代码，确实现在是加了一个开关，你把应用的日志级别设置为debug，例如：logging.level.root=debug，就可以打印日志到控制台中

**Comment by steverao** [comment]
通过开关关闭日志的背景可见#1131

**Comment by zqr95518** [comment]
懂了，level开到debug就看到了，虽然并不是用配置开关的，至少能看到了。
```
logging:
  level:
    com.alibaba.cloud.nacos.client: debug
```
