### ISSUE TITLE
The generated code is incorrect

### ISSUE THREAD

**Issue by 10nbj** [alibaba/spring-cloud-alibaba#2295]
https://start.aliyun.com/bootstrap.html The generated code of "cola" architecture cannot be run directly, and even an error is reported

**Comment by steverao** [comment]
There are some problems with this website now, we will fix it as soon as possible.

**Comment by steverao** [comment]
> https://start.aliyun.com/bootstrap.html The generated code of "cola" architecture cannot be run directly, and even an error is reported

There are some problems with this website now, we will fix it as soon as possible.
