### ISSUE TITLE
dubbo 升级到 springcloudAlibaba

### ISSUE THREAD

**Issue by rottenmu** [alibaba/spring-cloud-alibaba#2296]
目前使用dubbo2.7.10，如果将dubbo升级到springloucdAlibaba需要注意哪些呢

**Comment by rottenmu** [comment]
目前使用dubbo2.7.10，如果将dubbo升级到springloucdAlibaba需要注意哪些

**Comment by steverao** [comment]
是准备使用Spring Cloud Alibaba替换原来的Dubbo框架吗？

**Comment by steverao** [comment]
如果是Spring Cloud Alibaba使用上的相关问题可以在项目中文文档中找到交流钉钉群加入进行交流

**Comment by rottenmu** [comment]
> 是准备使用Spring Cloud Alibaba替换原来的Dubbo框架吗？
是的，但是扔使用Dubbo作为通讯协议

**Comment by rottenmu** [comment]
> > 是准备使用Spring Cloud Alibaba替换原来的Dubbo框架吗？
> > 是的，但是扔使用Dubbo作为通讯协议

因为之前主要使用springcloudAlibaba，对dubbo有些生疏，有升级到springcloudAlibaba的意愿

**Comment by tnessn** [comment]
> > > 是准备使用Spring Cloud Alibaba替换原来的Dubbo框架吗？
> > > 是的，但是扔使用Dubbo作为通讯协议
> 
> 因为之前主要使用springcloudAlibaba，对dubbo有些生疏，有升级到springcloudAlibaba的意愿

建议你别这么做，我们却跟你相反，准备把spring cloud alibaba改为单纯的dubbo

**Comment by steverao** [comment]
> > > 是准备使用Spring Cloud Alibaba替换原来的Dubbo框架吗？
> > > 是的，但是扔使用Dubbo作为通讯协议
> 
> 因为之前主要使用springcloudAlibaba，对dubbo有些生疏，有升级到springcloudAlibaba的意愿

你是企业生产环境使用吗？还是不建议根据是否对技术本身是否生疏作为升级替换框架的原因

**Comment by rottenmu** [comment]
> 企业

现在的业务架构非常有必要升级到SpringCloudAlibaba

**Comment by steverao** [comment]
> > 企业
> 
> 现在的业务架构非常有必要升级到SpringCloudAlibaba

方便解释一下具体原因吗？社区也想了解一下

**Comment by rottenmu** [comment]
> > > 企业
> > 
> > 
> > 现在的业务架构非常有必要升级到SpringCloudAlibaba
> 
> 方便解释一下具体原因吗？社区也想了解一下

目前公司使用dubbo，当前架构没有合适网关适合我们的架构，想优化架构去做一些事情也方便后续接入其他中间件，这些属于历史遗留问题

**Comment by rottenmu** [comment]
> 建议你别这么做，我们却跟你相反，准备把spring cloud alibaba改为单纯的dubbo

为什么呢，同学能不能分享一下

**Comment by tnessn** [comment]
> > 建议你别这么做，我们却跟你相反，准备把spring cloud alibaba改为单纯的dubbo
> 
> 为什么呢，同学能不能分享一下

现在还有不少bug，我看你说网关的问题，其实单纯用dubbo加spring cloud其实也可以做到

**Comment by steverao** [comment]
> > > > 企业
> > > 
> > > 
> > > 现在的业务架构非常有必要升级到SpringCloudAlibaba
> > 
> > 
> > 方便解释一下具体原因吗？社区也想了解一下
> 
> 目前公司使用dubbo，当前架构没有合适网关适合我们的架构，想优化架构去做一些事情也方便后续接入其他中间件，这些属于历史遗留问题
如果是因为Dubbo不太好支持网关的话，可以使用dubbo-spring-boot-starter去提供一个RESTful API给外部网关调用，然后内容还是走Dubbo调用这样可能会比较合适

**Comment by steverao** [comment]
> > > 建议你别这么做，我们却跟你相反，准备把spring cloud alibaba改为单纯的dubbo
> > 
> > 
> > 为什么呢，同学能不能分享一下
> 
> 现在还有不少bug，我看你说网关的问题，其实单纯用dubbo加spring cloud其实也可以做到

这一块确实还不够成熟，也欢迎大家一起参与到社区建设中来，完善Spring Cloud Alibaba：）

**Comment by rottenmu** [comment]
> 现在还有不少bug，我看你说网关的问题，其实单纯用dubbo加spring cloud其实也可以做到

dubbo+springcloud需要改造吗？

**Comment by tnessn** [comment]
> > 现在还有不少bug，我看你说网关的问题，其实单纯用dubbo加spring cloud其实也可以做到
> 
> dubbo+springcloud需要改造吗？

你现在已经有dubbo了，把spring cloud加进来就可以了，网关对外用spring cloud,服务间的调用还是用dubbo

**Comment by rottenmu** [comment]
> 
> 
> > > 现在还有不少bug，我看你说网关的问题，其实单纯用dubbo加spring cloud其实也可以做到
> > 
> > 
> > dubbo+springcloud需要改造吗？
> 
> 你现在已经有dubbo了，把spring cloud加进来就可以了，网关对外用spring cloud,服务间的调用还是用dubbo
秒懂

**Comment by Fox2210** [comment]
springCloudAlibaba整合dubbo后不乐观，从去年发现到现在为止，一直跟踪服务丢失问题一直都在，中间自己试了一些方法还是一样的结果，要么升级alibaba不使用自身的dubbo版本单独引入apache版dubbo（本地demo测试发现没有服务丢失情况，没有经过环境测试暂时不知道是否没问题），要么升级alibaba后不使用dubbo直接使用open-feign问题可以解决（但是大部分人应该还是喜欢dubbo，写起来方便而且传输协议和http区别）。

**Comment by EyoungShieh1992** [comment]
> springCloudAlibaba整合dubbo后不乐观，从去年发现到现在为止，一直跟踪服务丢失问题一直都在，中间自己试了一些方法还是一样的结果，要么升级alibaba不使用自身的dubbo版本单独引入apache版dubbo（本地demo测试发现没有服务丢失情况，没有经过环境测试暂时不知道是否没问题），要么升级alibaba后不使用dubbo直接使用open-feign问题可以解决（但是大部分人应该还是喜欢dubbo，写起来方便而且传输协议和http区别）。

这个目前只能修改源码来解决了，我是自己修改了框架的源码，加了一个定时器去比对Nacos和本地缓存的差异解决了，不知道其他大佬有没有好的解决办法

**Comment by QKM-0203** [comment]
> 我想问问是不是 你是不是遇到这个问题No provider available for the service com.xiyoulinux.auth.service.IAuthService from the url spring-cloud://127.0.0.1:9090/呀

**Comment by QKM-0203** [comment]
> > springCloudAlibaba整合dubbo后不乐观，从去年发现到现在为止，一直跟踪服务丢失问题一直都在，中间自己试了一些方法还是一样的结果，要么升级alibaba不使用自身的dubbo版本单独引入apache版dubbo（本地demo测试发现没有服务丢失情况，没有经过环境测试暂时不知道是否没问题），要么升级alibaba后不使用dubbo直接使用open-feign问题可以解决（但是大部分人应该还是喜欢dubbo，写起来方便而且传输协议和http区别）。
> 
> 这个目前只能修改源码来解决了，我是自己修改了框架的源码，加了一个定时器去比对Nacos和本地缓存的差异解决了，不知道其他大佬有没有好的解决办法

 我想问问是不是遇到这个问题呀No provider available for the service com.xiyoulinux.auth.service.IAuthService from the url spring-cloud://127.0.0.1:9090

**Comment by EyoungShieh1992** [comment]
> > > springCloudAlibaba整合dubbo后不乐观，从去年发现到现在为止，一直跟踪服务丢失问题一直都在，中间自己试了一些方法还是一样的结果，要么升级alibaba不使用自身的dubbo版本单独引入apache版dubbo（本地demo测试发现没有服务丢失情况，没有经过环境测试暂时不知道是否没问题），要么升级alibaba后不使用dubbo直接使用open-feign问题可以解决（但是大部分人应该还是喜欢dubbo，写起来方便而且传输协议和http区别）。
> > 
> > 
> > 这个目前只能修改源码来解决了，我是自己修改了框架的源码，加了一个定时器去比对Nacos和本地缓存的差异解决了，不知道其他大佬有没有好的解决办法
> 
> 我想问问是不是遇到这个问题呀No provider available for the service com.xiyoulinux.auth.service.IAuthService from the url spring-cloud://127.0.0.1:9090

是的，消费者找不到服务的问题

**Comment by mengxuan37** [comment]
别入坑，都在讨论放弃 移除Spring Cloud Dubbo模块了
