### ISSUE TITLE
How feign uses sentinel

### ISSUE THREAD

**Issue by jmilktea** [alibaba/spring-cloud-alibaba#2297]
**Which Component**
Sentinel

**Describe what problem you have encountered**
在hystrix和resilience4j中，我们可以配置default，对所有的feign client生效，例如熔断规则，隔离策略。在sentinel中我找不到类似的配置，似乎需要单个url去配置，这非常麻烦，请问怎么做。

In hystrix and resilience4j, we can configure "default", which will take effect for all feign clients, such as circuit breaker rules and isolation strategies. I can't find a similar configuration in sentinel. It seems that each URL needs to be configured, which is very troublesome. , May I ask how to do it.

**Describe what information you have read**
I have read the reference doc of Sentinel

**Comment by steverao** [comment]
It doesn't support this feature, you need to set rules for each Feign Client now.

**Comment by steverao** [comment]
But others had some ideas to acheve this feature, Someone who is interested in can try!(https://juejin.cn/post/6933072764395847693)

**Comment by jmilktea** [comment]
This is a very common feature and I look forward to supporting it in the future. The correct way is to provide a default option similar to hystrix. If there are special requirements, it can be configured separately, otherwise there are many URLs, and the configuration of each URL seems messy.

这是个很常见的功能，期待以后能支持。正确的方式应该像hystrix类似提供一个default选项，如果有特殊的需求可以单独配置，否则url很多，每个url都配置显得很乱。

**Comment by drgnchan** [comment]
@steverao please assign it to me.

**Comment by steverao** [comment]
> @steverao please assign it to me.

Do you want to achieve the feature? If alright, you just do it and create a PR.

**Comment by drgnchan** [comment]
> > @steverao please assign it to me.
> 
> Do you want to achieve the feature? If alright, you just do it and create a PR.

ok,i'm in progress.
