### ISSUE TITLE
在阿里云服务器上的docker环境中运行的容器中服务的@LoadBalanced会偶尔不生效？

### ISSUE THREAD

**Issue by zqr95518** [alibaba/spring-cloud-alibaba#2308]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-starter-alibaba-nacos-discovery

**Describe what problem you have encountered**
在阿里云服务器上的docker环境中运行的容器中服务的@LoadBalanced会偶尔不生效？
Will the @LoadBalanced service in the container running in the docker environment on the Alibaba Cloud server occasionally fail to take effect?

使用的是完全相同的镜像，有的能生效，有的不能。
nacos-discovery 2021.1 使用更低版本的nacos-discovery没有发现这个问题。
推测和替换了ribbon有关？因为是偶发的所以没法重现，不知道有没有人遇到和我一样的问题。

**Comment by steverao** [comment]
不能生效的现象是什么？或者说你怎么发现是@LoadBalanced没生效？

**Comment by zqr95518** [comment]
有Loadbalance用服务名访问如果不存在是报找不到服务，而有问题的时候是提示找不到host

**Comment by zqr95518** [comment]
jdk1.8.0_181

**Comment by zqr95518** [comment]
docker standalone 20.10.12
镜像:
CentOS 基础镜像版本不明
jdk1.8.0_181
spring boot 2.4.13
spring-cloud 2020.0.4
spring.cloud.alibaba 2021.1
最近在不同服务器上发现了相同现象，@LoadBalanced不走nacos获取ip，而是走的本地host。
@steverao 其他环境的正常代码，放到了有问题的环境里都会报错，镜像代码都是相同的，还需要提供什么信息么

**Comment by steverao** [comment]
It's environmental problem, you need to contact with environmental provider.
