### ISSUE TITLE
[Announce] Spring Cloud Alibaba 2.2.7.RELEASE released

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2309]
Hello Community,

We are very glad to announce that Spring Cloud Alibaba 2.2.7.RELEASE is released.

You can check detailed release notes here:

2.2.7.RELEASE : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.7.RELEASE

If there are no notable bugs, the RELEASE version will come within a week.

If you have any questions using this version, please report the issue on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by xfxf521** [comment]
use 2.2.7 ,report error
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.<init>(ReferenceAnnotationBeanPostProcessor.java:106)

The following method did not exist:

    org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.setClassValuesAsString(Z)V

The method's class, org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor, is available from the following locations:

    jar:file:/D:/apache-maven-3.6.2/res/org/apache/dubbo/dubbo/2.7.13/dubbo-2.7.13.jar!/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.class

The class hierarchy was loaded from the following locations:

    org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor: file:/D:/apache-maven-3.6.2/res/org/apache/dubbo/dubbo/2.7.13/dubbo-2.7.13.jar
    com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor: file:/D:/apache-maven-3.6.2/res/com/alibaba/spring/spring-context-support/1.0.10/spring-context-support-1.0.10.jar
    org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter: file:/D:/apache-maven-3.6.2/res/org/springframework/spring-beans/5.2.15.RELEASE/spring-beans-5.2.15.RELEASE.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor

**Comment by steverao** [comment]
Please update "spring-context-support" from 1.0.10 to 1.0.11.

**Comment by jinshengyong** [comment]
> 

请问一下，新版发布的2.2.7支持spring boot 2.6.x 以上版本吗

**Comment by haihaiya** [comment]
> 如果你在 Spring Cloud Alibaba 2.2.7.RELEASE 中使用 Dubbo 2.7.13，请从 1.0.10 到 1.0.11 更新到“spring-context-support”，否则将无法启动！
麻烦请问一下我更新spring-context-support依然无法正常启动，在添加了nacos-client-1.4.2才能正常启动。我的nacos服务是2.0.3版本的。但是正常启动后无法完成远程调用，找不到服务。为什么会出现这种情况。

**Comment by haihaiya** [comment]
> 使用2.2.7，报错 说明：
> 
> 试图调用不存在的方法。尝试是从以下位置进行的：
> 
> ```
> org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.<init>(ReferenceAnnotationBeanPostProcessor.java:106)
> ```
> 
> 以下方法不存在：
> 
> ```
> org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.setClassValuesAsString(Z)V
> ```
> 
> 该方法的类 org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor 可从以下位置获得：
> 
> ```
> jar:file:/D:/apache-maven-3.6.2/res/org/apache/dubbo/dubbo/2.7.13/dubbo-2.7.13.jar!/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.class
> ```
> 
> 类层次结构是从以下位置加载的：
> 
> ```
> org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor: file:/D:/apache-maven-3.6.2/res/org/apache/dubbo/dubbo/2.7.13/dubbo-2.7.13.jar
> com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor: file:/D:/apache-maven-3.6.2/res/com/alibaba/spring/spring-context-support/1.0.10/spring-context-support-1.0.10.jar
> org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter: file:/D:/apache-maven-3.6.2/res/org/springframework/spring-beans/5.2.15.RELEASE/spring-beans-5.2.15.RELEASE.jar
> ```
> 
> 行动：
> 
> 更正应用程序的类路径，使其包含 org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor 的单个兼容版本

你问题解决了么，是否可以正常调用注册的服务

**Comment by xfxf521** [comment]
我升级1.0.11就解决了，可以正常调用。

**Comment by haihaiya** [comment]
您好，能给我看一下你的pom依赖和配置么。我这块来来回回改好几天了依然无法正常调用，不胜感激。


| |
池海
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/15/2021 ***@***.***> wrote：

我升级1.0.11就解决了，可以正常调用。

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhifuchen** [comment]
升级后配置的nacos config报错
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles zflocal are currently active).

**Comment by zhujy5** [comment]
升级以下配置后，出现：
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.6.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.6.RELEASE</version>
        </dependency>
出现应用无法启动问题
***************************
APPLICATION FAILED TO START
***************************
 
Description:
 
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
 
Reason: Failed to determine a suitable driver class

奇怪的是：
本地启动时OK的，但是容器却又问题！
