### ISSUE TITLE
升级 2.2.7 报错

### ISSUE THREAD

**Issue by mj19910923** [alibaba/spring-cloud-alibaba#2310]
依赖版本：
spring-boot：2.3.12.RELEASE
spring-cloud-alibaba：2.2.7.RELEASE
spring-cloud：Hoxton.SR12
nacos：2.0.3

报错信息：
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.<init>(ReferenceAnnotationBeanPostProcessor.java:106)

The following method did not exist:

    org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.setClassValuesAsString(Z)V

The method's class, org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor, is available from the following locations:

    jar:file:/Users/hudongshan/.m2/repository/org/apache/dubbo/dubbo/2.7.13/dubbo-2.7.13.jar!/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.class

The class hierarchy was loaded from the following locations:

    org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor: file:/Users/hudongshan/.m2/repository/org/apache/dubbo/dubbo/2.7.13/dubbo-2.7.13.jar
    com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor: file:/Users/hudongshan/.m2/repository/com/alibaba/spring/spring-context-support/1.0.10/spring-context-support-1.0.10.jar
    org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter: file:/Users/hudongshan/.m2/repository/org/springframework/spring-beans/5.2.15.RELEASE/spring-beans-5.2.15.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor

**Comment by steverao** [comment]
Please update "spring-context-support" from 1.0.10 to 1.0.11.

**Comment by mj19910923** [comment]
> Please update "spring-context-support" from 1.0.10 to 1.0.11.

感谢，已解决！

解决方案：
          <dependency>
              <groupId>com.alibaba.spring</groupId>
              <artifactId>spring-context-support</artifactId>
              <version>1.0.11</version>
          </dependency>

**Comment by ladixiu** [comment]
666

**Comment by frozentearz** [comment]
666

**Comment by CQWSBUY** [comment]
666，老弟呀，给你留灯

**Comment by GragonWu** [comment]
999

**Comment by kouke0305** [comment]
太坑了呀
