### ISSUE TITLE
nacos 服务权重没效果

### ISSUE THREAD

**Issue by ibingdian** [alibaba/spring-cloud-alibaba#2312]
使用原生的spring.cloud.gateway的方式搭建简易的网关。
分别调用不同端口，权重分别为1和6的weight服务，结果是两个端口调用比例是1：1。

Spring Cloud Version ：2020.0.1
Spring Cloud Alibaba Version：2021.1
Spring Boot Version：2.4.2

请问，这个问题应该怎么解决？

 以下是依赖

       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

**Comment by yuhuangbin** [comment]
refer pr: #2152
