### ISSUE TITLE
增强nacosRule结合loadBalance缓存

### ISSUE THREAD

**Issue by haorq** [alibaba/spring-cloud-alibaba#2313]
String clusterName = this.nacosDiscoveryProperties.getClusterName();
            String group = this.nacosDiscoveryProperties.getGroup();
            DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer) getLoadBalancer();
            String name = loadBalancer.getName();

      
           List<Server> allServers = loadBalancer.getAllServers();
            List<Instance> collect = null;
            List<Instance> instances = null;
            if(CollectionUtils.isEmpty(allServers)){
                collect = allServers.stream().map(t -> {
                    NacosServer nacosServer = (NacosServer) t;
                    Instance instance = nacosServer.getInstance();
                    return instance;
                }).collect(Collectors.toList());
            }

            if(CollectionUtils.isEmpty(collect)){
                NamingService namingService = nacosServiceManager
                        .getNamingService(nacosDiscoveryProperties.getNacosProperties());
                instances = namingService.selectInstances(name, group, true);
            }else{
                instances = collect;
            }

            if (CollectionUtils.isEmpty(instances)) {
                LOGGER.warn("no instance in service {}", name);
                return null;
            }

            List<Instance> instancesToChoose = instances;
            if (StringUtils.isNotBlank(clusterName)) {
                List<Instance> sameClusterInstances = instances.stream()
                        .filter(instance -> Objects.equals(clusterName,
                                instance.getClusterName()))
                        .collect(Collectors.toList());
                if (!CollectionUtils.isEmpty(sameClusterInstances)) {
                    instancesToChoose = sameClusterInstances;
                }
                else {
                    LOGGER.warn(
                            "A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}",
                            name, clusterName, instances);
                }
            }

            Instance instance = ExtendBalancer.getHostByRandomWeight2(instancesToChoose);

            return new NacosServer(instance);
        }

**Comment by steverao** [comment]
你这是要提PR吗？

**Comment by haorq** [comment]
在原有NacosRule的基础上增加几行代码。













在 2021-12-06 19:30:03，"Steve Rao" ***@***.***> 写道：

你这是要提PR吗？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuhuangbin** [comment]
`NacosRule` 不适合使用 `loadBalance` 缓存，Nacos Client本身就有服务实例数据缓存，服务实例变更后，直接从Nacos Client中能拿到最新的服务实例数据，如果加了一层 `loadBalance` 缓存，那么将无法快速感知服务实例数据变化。
