### ISSUE TITLE
适配spring cloud 2021.0.0提上日程了吗

### ISSUE THREAD

**Issue by laohuihui178** [alibaba/spring-cloud-alibaba#2314]
想问下适配spring cloud 2021.0.0提上日程了吗

**Comment by steverao** [comment]
还没有这么块哈，当前主要精力还是集中在支持和完善主流的Spring Cloud、Spring Boot以及阿里内部中间件的可靠性与稳定性上！

**Comment by yuhuangbin** [comment]
不建议大家使用Spring Cloud的版本太激进，据我了解，大部分企业用户生产环境都是Spring Cloud 2020.0 (code name: ilford)之前的版本

**Comment by Max-Qiu** [comment]
我已经升级到 SpringBoot 2.6.1 与 SpringCloud 2021.0.0 ，目前来看没啥问题（PS：我只用了nacos的注册中心和配置中心）

**Comment by kabunx** [comment]
┌──->──┐
|  com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration (field private java.util.Optional com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration.sentinelWebInterceptorOptional)
└──<-──┘

**Comment by herodotus-cloud** [comment]
> 我已经升级到 SpringBoot 2.6.1 与 SpringCloud 2021.0.0 ，目前来看没啥问题（PS：我只用了nacos的注册中心和配置中心）

目前看主要是Sentinel有问题，依赖循环

**Comment by lin-mt** [comment]
> > 我已经升级到 SpringBoot 2.6.1 与 SpringCloud 2021.0.0 ，目前来看没啥问题（PS：我只用了nacos的注册中心和配置中心）
> 
> 目前看主要是Sentinel有问题，依赖循环

这个可以手动关闭，你试试

**Comment by laohuihui178** [comment]
> > > 我已经升级到 SpringBoot 2.6.1 与 SpringCloud 2021.0.0 ，目前来看没啥问题（PS：我只用了nacos的注册中心和配置中心）
> > 
> > 
> > 目前看主要是Sentinel有问题，依赖循环
> 
> 这个可以手动关闭，你试试

我试过，没有效果

**Comment by chenmaochang** [comment]
springboot-data-redis 2.4.2对redis zadd都没做实现,直接stackoverflow ,手动exclude掉引个2.6.1的进来真的很难看,求求了赶紧提上议程啊

**Comment by rainwolf01** [comment]
跟不上spring cloud的发布节奏啊。

**Comment by cnlinjie** [comment]
> 目前看主要是Sentinel有问题，依赖循环

同一个问题

**Comment by laohuihui178** [comment]
> > 目前看主要是Sentinel有问题，依赖循环
> 
> 同一个问题

可以试下在springboot启动类里面手动设置允许循环依赖
```java
System.setProperty("spring.main.allow-circular-references", "true");
```

**Comment by galaxy-sea** [comment]
感觉要走dubbo的老路了

**Comment by mynzdbx** [comment]
> 不建议大家使用Spring Cloud的版本太激进，据我了解，大部分企业用户生产环境都是Spring Cloud 2020.0 (code name: ilford)之前的版本

不支持springboot2.5+的话，java17没法用吧？新项目想用java17，因为ali只支持到springboot2.3，被迫先用的java15

**Comment by shanzhaozhen** [comment]
spring boot 2.6+ 的变化有点大，而且用spring security 也有巨大的变化，强绑定版本有点影响了开发，目前想用spring security 5.6+又得对boot做升级，希望spring cloud alibaba也可以快点更新，跟上进度，期待变得更加强大

**Comment by mynzdbx** [comment]
> > 我已经升级到 SpringBoot 2.6.1 与 SpringCloud 2021.0.0 ，目前来看没啥问题（PS：我只用了nacos的注册中心和配置中心）
> 
> 目前看主要是Sentinel有问题，依赖循环

我使用原生的spring cloud，也是你这个版本，不引入spring cloud alibaba，nacos似乎用不了啊。能贴下你的pom文件吗？

**Comment by HaojunRen** [comment]
Spring Cloud Alibaba 2021.0.1.0 has been released. It supported SpringCloud 2021.0.1
