### ISSUE TITLE
Memory overflow after upgrade to nacos-client-2.0.3

### ISSUE THREAD

**Issue by Comven** [alibaba/spring-cloud-alibaba#2316]
nacos-server-2.0.3
SpringCloudAlibaba 2021.1
nacos-client-2.0.3

Memory overflow occurred when the client program was running for several hours.The hprof file analysis results are shown in the figure below:
![image](https://user-images.githubusercontent.com/8464801/145135197-c51b1e55-1b08-44e1-bb38-c12b7f1791cf.png)

Among them, the largest object java.lang.object [] data reaches 100000, and the main contents are as follows:
![image](https://user-images.githubusercontent.com/8464801/145135587-9ccd1247-742d-402c-9e85-76fb5e100851.png)

and main data are as follows:
![image](https://user-images.githubusercontent.com/8464801/145135287-ad61cc1f-5dc7-491d-9337-62a35ac645b0.png)

This program will not actively call other programs, but passively receive requests and respond. when downgrade to nacos-client-1.4.2 and everything is normal.

Does anyone know the reason for this, or the solution?

**Comment by yuhuangbin** [comment]
refer : https://github.com/alibaba/nacos/issues/7397

Spring Cloud Alibaba对于 NamingService 和 ConfigService的使用，都是单例模式，不存在交互一次创建一个新的实例。建议[Nacos](https://github.com/alibaba/nacos) 社区自查Nacos Client

**Comment by Comven** [comment]
> refer : [alibaba/nacos#7022](https://github.com/alibaba/nacos/issues/7022) , [alibaba/nacos#7377](https://github.com/alibaba/nacos/issues/7377)
> 
> Spring Cloud Alibaba对于 NamingService 和 ConfigService的使用，都是单例模式，不存在交互一次创建一个新的实例。建议[Nacos](https://github.com/alibaba/nacos) 社区反馈详细信息，或者排查自己业务代码有没有自行初始化NamingService 和 ConfigService

1、出现内存溢出的程序是被动接收请求，没有自行初始化NamingService 和ConfigService的地方。
2、调用该程序的app采用RestTemplate调用的，也没有自行初始化NamingService 和 ConfigService一说。除了对RestTemplate的首次申明，其他地方都是SpringBoot自动注入的。1.4.2版本完全没有问题，升级2.0.3就始终会这样。
3、nacos社区反馈了包括其他反馈，基本石沉大海，杳无音讯了。所以才到这边来问问，看有没有人遇到过同类型问题。
