### ISSUE TITLE
集成sentinel 循环依赖错误

### ISSUE THREAD

**Issue by SSDespair** [alibaba/spring-cloud-alibaba#2319]
![image](https://user-images.githubusercontent.com/26852131/145519332-aeabcd55-661a-4b7a-a66b-17de2cee0a52.png)
使用版本
![image](https://user-images.githubusercontent.com/26852131/145519391-f19e15a9-6f3a-49eb-84c3-9a6e37c5c0bb.png)

**Comment by yuhuangbin** [comment]
有没有自己做任何扩展实现操作? 或者提供一个复现demo

**Comment by SSDespair** [comment]
重写了 com.alibaba.cloud.sentinel.feign.SentinelFeign，demo 暂时无法提供

**Comment by yuhuangbin** [comment]
可以试下使用默认的SentinelFeign，是否存在这个问题？

**Comment by SSDespair** [comment]
可以 ，我等会尝试下看看，是否会存在这个问题

**Comment by fglfglfgl** [comment]
这个是啥呀？怎么我也能收到呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月14日(周二) 下午2:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [alibaba/spring-cloud-alibaba] 集成sentinel 循环依赖错误 (Issue #2319)




 
重写了 com.alibaba.cloud.sentinel.feign.SentinelFeign，demo 暂时无法提供

**Comment by SSDespair** [comment]
经过测试，单独使用也是会出现这个问题，并且只要引入mvc 的包都会出现这个问题
![image](https://user-images.githubusercontent.com/26852131/145957498-41adaf9b-7f71-49a9-8d0a-3213e4d111cd.png)

**Comment by SSDespair** [comment]
![image](https://user-images.githubusercontent.com/26852131/145957573-0d2b1c6c-0cc1-4323-b6f5-7f40b43884e1.png)
上面的截图不全

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example

这个示例项目是没问题的，可能是你这个springfox包有影响

**Comment by SSDespair** [comment]
![image](https://user-images.githubusercontent.com/26852131/145960877-2d9a70ea-aedc-413b-ab4e-6c00f0b9a40c.png)这三个版本是否和我使用的一致呢

**Comment by yuhuangbin** [comment]
> ![image](https://user-images.githubusercontent.com/26852131/145960877-2d9a70ea-aedc-413b-ab4e-6c00f0b9a40c.png)这三个版本是否和我使用的一致呢

版本之间对应关系请参照  https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by SSDespair** [comment]
我还是等适配吧

**Comment by yuhuangbin** [comment]
> 我还是等适配吧

你参考下wiki版本说明文档，你目前使用的版本也对不上，Spring Boot/Spring Cloud/Spring Cloud Alibaba三者的版本对应关系，文档中有说明的

**Comment by edifangyi** [comment]
> > 我还是等适配吧
> 
> 你参考下维基版本说明文档，你现在使用的版本也对不上，Spring Boot/Spring Cloud/Spring Cloud Alibaba 三者的版本对应，文档中的说明的

最新一栏，试了不得行。
这个matecloud开源项目是按照楼主的版本号适配的，不知道怎么他们怎么做的

**Comment by SSDespair** [comment]
那我抽时间看看 matecloud  项目

**Comment by herodotus-cloud** [comment]
#2322 

> @LingCai2001 对我没用哈~

我是临时通过以下方式解决的。

1. 新建一个com.alibaba.cloud.sentinel包（是在依赖了spring-cloud-starter-alibaba-sentinel的工程中创建，以确保可以覆盖该包中的SentinelWebAutoConfiguration）
2.在该包中新建类 SentinelWebAutoConfiguration，代码修改为以下内容，就可以解决
```
@Configuration(proxyBeanMethods = false)
@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.SERVLET)
@ConditionalOnClass(SentinelConfiguration.SentinelWebConfiguration.class)
public class SentinelWebAutoConfiguration extends WebMvcConfigurationSupport {

    private static final Logger log = LoggerFactory
            .getLogger(SentinelWebAutoConfiguration.class);

    @Autowired
    private SentinelProperties properties;

    @Autowired
    private Optional<SentinelWebInterceptor> sentinelWebInterceptorOptional;

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        if (!sentinelWebInterceptorOptional.isPresent()) {
            return;
        }
        SentinelProperties.Filter filterConfig = properties.getFilter();
        registry.addInterceptor(sentinelWebInterceptorOptional.get())
                .order(filterConfig.getOrder())
                .addPathPatterns(filterConfig.getUrlPatterns());
        log.info(
                "[Sentinel Starter] register SentinelWebInterceptor with urlPatterns: {}.",
                filterConfig.getUrlPatterns());
    }
}
```

3. 代码参考连接，[https://gitee.com/herodotus/eurynome-cloud/blob/master/packages/eurynome-cloud-kernel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java](https://gitee.com/herodotus/eurynome-cloud/blob/master/packages/eurynome-cloud-kernel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java)

**Comment by kscMaster** [comment]
为啥关了，到底是什么原因，我把sentinel关了就不存在这个问题，并且这个问题大概率不是版本号引起的
