### ISSUE TITLE
SpringBoot2.6.X循环依问题

### ISSUE THREAD

**Issue by LingCai2001** [alibaba/spring-cloud-alibaba#2322]
报错：
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   webSecurityConfiguration
      ↓
   org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration
┌─────┐
|  com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration (field private java.util.Optional com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration.sentinelWebInterceptorOptional)
└─────┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

SpringBootVersion: 2.6.1
SpringCloudVersion: 2021.0.0
SpringCloudAlibabaVersion: 2.2.7.RELEASE
SentinelVersion: 2.2.7.RELEASE

**Comment by yuhuangbin** [comment]
将Spring Boot 版本调整至 `2.3.12.RELEASE` 看一下

**Comment by yuhuangbin** [comment]
![image](https://user-images.githubusercontent.com/26948026/146524197-ef2391fb-5f00-4e69-b657-7e2c1ed2d5e7.png)

**Comment by herodotus-cloud** [comment]
> @LingCai2001 对我没用哈~

我是临时通过以下方式解决的。

1. 新建一个com.alibaba.cloud.sentinel包（是在依赖了spring-cloud-starter-alibaba-sentinel的工程中创建，以确保可以覆盖该包中的SentinelWebAutoConfiguration）
2.在该包中新建类 SentinelWebAutoConfiguration，代码修改为以下内容，就可以解决
```
@Configuration(proxyBeanMethods = false)
@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.SERVLET)
@ConditionalOnClass(SentinelConfiguration.SentinelWebConfiguration.class)
public class SentinelWebAutoConfiguration extends WebMvcConfigurationSupport {

    private static final Logger log = LoggerFactory
            .getLogger(SentinelWebAutoConfiguration.class);

    @Autowired
    private SentinelProperties properties;

    @Autowired
    private Optional<SentinelWebInterceptor> sentinelWebInterceptorOptional;

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        if (!sentinelWebInterceptorOptional.isPresent()) {
            return;
        }
        SentinelProperties.Filter filterConfig = properties.getFilter();
        registry.addInterceptor(sentinelWebInterceptorOptional.get())
                .order(filterConfig.getOrder())
                .addPathPatterns(filterConfig.getUrlPatterns());
        log.info(
                "[Sentinel Starter] register SentinelWebInterceptor with urlPatterns: {}.",
                filterConfig.getUrlPatterns());
    }
}
```

3. 代码参考连接，[https://gitee.com/herodotus/eurynome-cloud/blob/master/packages/eurynome-cloud-kernel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java](https://gitee.com/herodotus/eurynome-cloud/blob/master/packages/eurynome-cloud-kernel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java)

**Comment by LingCai2001** [comment]
> 将Spring Boot版本调整到`2.4.2.RELEASE`一下，关于Spring Boot/Spring Cloud/Spring Cloud阿里巴巴三者的关系，大家请参照[版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)，不要自己的自由版本任意组合，不同版本的组合会出现不同情况

好的，谢谢，没在意看这个

**Comment by LingCai2001** [comment]
> 将Spring Boot版本调整到`2.4.2.RELEASE`一下，关于Spring Boot/Spring Cloud/Spring Cloud 阿里巴巴三者的关系，大家请参照[版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)，不要自己的自由版本组合，不同版本的组合会出现不同的情况

什么时候能够解决这个问题？

**Comment by westboy** [comment]
spring.main.allow-circular-references=true 这个不可以吗？

**Comment by JabinHao** [comment]
> 
that works, thanks

**Comment by guruilin** [comment]
> > 
> 
> 那有效，谢谢

解决了吗
