### ISSUE TITLE
nacos中的yml配置文件不支持yml分隔符 ---

### ISSUE THREAD

**Issue by helloichen** [alibaba/spring-cloud-alibaba#2328]
使用nacos作为配置中心，配置文件使用yaml格式。
如果配置文件中使用了 `---` 来对yaml进行分隔，会导致配置解析不出来，getProperty(String name) 返回值将会是null。
[NacosPropertySource#getSourceMap(String group, String dataId, List<PropertySource<?>> propertySources)](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySource.java)
```java
	private static Map<String, Object> getSourceMap(String group, String dataId,
			List<PropertySource<?>> propertySources) {
		if (CollectionUtils.isEmpty(propertySources)) {
			return Collections.emptyMap();
		}
		// If only one, return the internal element, otherwise wrap it.
		if (propertySources.size() == 1) {
			PropertySource propertySource = propertySources.get(0);
			if (propertySource != null && propertySource.getSource() instanceof Map) {
				return (Map<String, Object>) propertySource.getSource();
			}
		}
		// If it is multiple, it will be returned as it is, and the internal elements
		// cannot be directly retrieved, so the user needs to implement the retrieval
		// logic by himself
                // (*) yml中使用了 --- 将会执行到这里，导致属性的key取不到值
		return Collections.singletonMap(
				String.join(NacosConfigProperties.COMMAS, dataId, group),
				propertySources);
	}
```
`com.alibaba.cloud.nacos.parser.NacosDataParserHandler#parseNacosData`方法中使用`org.springframework.boot.env.YamlPropertySourceLoader#load`来加载`nacosData`
springboot在解析Yaml的时候,于`org.springframework.boot.env.YamlPropertySourceLoader#load`方法中已经将yml解析成map了
![image](https://user-images.githubusercontent.com/52805835/147173153-0fd3b284-1d22-4d44-acd1-8d88fe719a9b.png)
我认为在`NacosPropertySource#getSourceMap(String group, String dataId, List<PropertySource<?>> propertySources)`中无需再将propertySources转成singletonMap，可对 `List<PropertySource<?>> propertySources`遍历进行类型判断，如果是`MapPropertySource`类型，可直接getSource,再合并

**Comment by helloichen** [comment]
使用场景：
使用nacos作为配置中心，采取yaml的格式来配置配置文件，在yam中使用---分隔符对yaml配置的内容进行分隔，springboot对就会出现上述bug，导致propertyName获取不到对应的配置值。

**Comment by zkzlx** [comment]
感谢反馈，可否修复下这个问题呢？谢谢

**Comment by helloichen** [comment]
> 感谢反馈，可否修复下这个问题呢？谢谢

已提交Pull request,请审核。

**Comment by helloichen** [comment]
Pull reqeust has bean merged by yuhuangbin.
