### ISSUE TITLE
springboot2.6.x循环依赖com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration.sentinelWebInterceptorOptional

### ISSUE THREAD

**Issue by 203579397** [alibaba/spring-cloud-alibaba#2330]
The dependencies of some of the beans in the application context form a cycle:

   sysLoginService (field private com.dfe.dfzh.smk.system.api.feign.LogFeignClient com.dfe.dfzh.smk.auth.service.SysLoginService.logFeignClient)
      ↓
   org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration
┌─────┐
|  com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration (field private java.util.Optional com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration.sentinelWebInterceptorOptional)
└─────┘

**Comment by yuhuangbin** [comment]
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

参考版本说明引用对应正确的版本，Spring Boot 2.6.x还没有对应的版本适配，可能会引发不兼容问题
