### ISSUE TITLE
nacos配置中心问题

### ISSUE THREAD

**Issue by zengzhi520** [alibaba/spring-cloud-alibaba#2332]
spring boot版本2.3.12.RELEASE spring cloud版本Hoxton.SR12 spring cloud alibaba版本 2.2.7.RELEASE
启动工程时，错误如下：
Description:
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class
Action:
Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles test are currently active).
这几个不是官网上的稳定版本吗？怎么也会有问题呢？
然后我将上述版本都降低后又没有问题
比如降低的版本为 spring boot版本 2.3.2.RELEASE  spring cloud版本Hoxton.SR9 spring cloud alibaba版本 2.2.6.RELEASE
感觉有点坑

**Comment by yuhuangbin** [comment]
如何确定是Nacos的问题呢？ 看这个日志你应该检查一下你项目的数据源配置，升级任何项目版本都要评估的，不是改改版本号那么简单

**Comment by zengzhi520** [comment]
数据源配置是没问题的，感觉就是 Spring Cloud Alibaba 2.2.7.RELEASE 版本对nacos配置中心有问题，我将其降到 Spring Cloud Alibaba 2.2.6.RELEASE 或其他版本，都没有问题，能够正常使用。
我这边在降版本测试时，参考的是Spring Cloud、Spring Boot、Spring Cloud Alibaba这三者适配版本操作的，应该是没问题的。
并且我也自由搭配了几个版本，就只有Spring Cloud Alibaba 2.2.7.RELEASE有问题..


备注：升级任何项目版本都是根据官网给出的来调整的



根据官网上的适配后，我自己也随意搭配了三者版本，结果如下：





有可能是我哪里有配置错误的，但就只有Spring Cloud Alibaba 2.2.7.RELEASE有问题，见谅见谅






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] nacos配置中心问题 (Issue #2332)





 
如何确定是Nacos的问题呢？ 看这个日志你应该检查一下你项目的数据源配置，升级任何项目版本都要评估的，不是改改版本号那么简单
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by steverao** [comment]
2.2.7.RELEASE 中的 Nacos 使用的是2.0版本，使用上要注意一下 Nacos Server 是不是2.0

**Comment by steverao** [comment]
看报错好像并不是Nacos问题，你拿着报错先用搜索引擎搜搜看吧，SCA 2.2.7.RELEASE很多组件都升级了，有的组件升级后不一定支持你原来的编码方式，你可能也需要相应做一些修改的

**Comment by zengzhi520** [comment]
Nacos Server 用的是 2.0.3 




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] nacos配置中心问题 (Issue #2332)





 
2.2.7.RELEASE 中的 Nacos 使用的是2.0版本，使用上要注意一下 Nacos Server 是不是2.0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zsyubo** [comment]
> spring boot版本2.3.12.RELEASE spring cloud版本Hoxton.SR12 spring cloud alibaba版本 2.2.7.RELEASE 启动工程时，错误如下： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (the profiles test are currently active). 这几个不是官网上的稳定版本吗？怎么也会有问题呢？ 然后我将上述版本都降低后又没有问题 比如降低的版本为 spring boot版本 2.3.2.RELEASE spring cloud版本Hoxton.SR9 spring cloud alibaba版本 2.2.6.RELEASE 感觉有点坑

换成bootstrap.properties试试

**Comment by zhifuchen** [comment]
> 

不行啊

**Comment by zhifuchen** [comment]
> 换成bootstrap.properties试试
不行啊

**Comment by zhifuchen** [comment]
> > spring boot版本2.3.12.RELEASE spring cloud版本Hoxton.SR12 spring cloud alibaba版本 2.2.7.RELEASE 启动工程时，错误如下： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (the profiles test are currently active). 这几个不是官网上的稳定版本吗？怎么也会有问题呢？ 然后我将上述版本都降低后又没有问题 比如降低的版本为 spring boot版本 2.3.2.RELEASE spring cloud版本Hoxton.SR9 spring cloud alibaba版本 2.2.6.RELEASE 感觉有点坑
> 
> 换成bootstrap.properties试试

不行啊

**Comment by zhifuchen** [comment]
> 数据源配置是没问题的，感觉就是 Spring Cloud Alibaba 2.2.7.RELEASE 版本对nacos配置中心有问题，我将其降到 Spring Cloud Alibaba 2.2.6.RELEASE 或其他版本，都没有问题，能够正常使用。 我这边在降版本测试时，参考的是Spring Cloud、Spring Boot、Spring Cloud Alibaba这三者适配版本操作的，应该是没问题的。 并且我也自由搭配了几个版本，就只有Spring Cloud Alibaba 2.2.7.RELEASE有问题.. 备注：升级任何项目版本都是根据官网给出的来调整的 根据官网上的适配后，我自己也随意搭配了三者版本，结果如下： 有可能是我哪里有配置错误的，但就只有Spring Cloud Alibaba 2.2.7.RELEASE有问题，见谅见谅
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/spring-cloud-alibaba" ***@***.***&gt;; 发送时间:&nbsp;2021年12月24日(星期五) 下午4:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] nacos配置中心问题 (Issue #2332) 如何确定是Nacos的问题呢？ 看这个日志你应该检查一下你项目的数据源配置，升级任何项目版本都要评估的，不是改改版本号那么简单 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我改成2.2.6.RELEASE 也不行

**Comment by leyung** [comment]
> > 数据源配置是没问题的，感觉就是 Spring Cloud Alibaba 2.2.7.RELEASE 版本对nacos配置中心有问题，我将其降到 Spring Cloud Alibaba 2.2.6.RELEASE 或其他版本，都没有问题，能够正常使用。 我这边在降版本测试时，参考的是Spring Cloud、Spring Boot、Spring Cloud Alibaba这三者适配版本操作的，应该是没问题的。 并且我也自由搭配了几个版本，就只有Spring Cloud Alibaba 2.2.7.RELEASE有问题.. 备注：升级任何项目版本都是根据官网给出的来调整的 根据官网上的适配后，我自己也随意搭配了三者版本，结果如下： 有可能是我哪里有配置错误的，但就只有Spring Cloud Alibaba 2.2.7.RELEASE有问题，见谅见谅
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "alibaba/spring-cloud-alibaba" _**@**_._**>; 发送时间: 2021年12月24日(星期五) 下午4:14 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [alibaba/spring-cloud-alibaba] nacos配置中心问题 (Issue #2332) 如何确定是Nacos的问题呢？ 看这个日志你应该检查一下你项目的数据源配置，升级任何项目版本都要评估的，不是改改版本号那么简单 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 我改成2.2.6.RELEASE 也不行

找到解决方法了！
我是部署在服务器上的nacos docker镜像在2.0.3版本需要额外使用两个gRPC的端口9848/9849，参照官方文档[Nacos 2.0.0 兼容性文档](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html)，于是我在` -p 8848:8848 `的基础上添加了
```
-p 9848:9848 \
-p 9849:9849 \
```
同时在服务器厂商控制台添加安全组，又加上了 9848,9849 端口放行（如果防火墙没关还有放行防火墙），重新部署运行即可

**Comment by yhb890430** [comment]
我这边也出现了一样的问题，现在也卡在这里了

**Comment by pkaq** [comment]
我也遇到了一样的问题 我用的nacos和alibaba都是最新版本


Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

**Comment by pkaq** [comment]
兄弟们 加这个注解可以 让程序启动起来 蛋没什么卵用
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})

经过试验 数据库 redis等一些配置 放到        shared-config 里去加载就会出现这类问题 放到项目所属的配置里是不会有问题的

**Comment by pkaq** [comment]
#2616 方式可以解决此类问题

**Comment by song0403** [comment]
我也报这个错，我的解决方法是配置文件下的config.group分组必须要加上
