### ISSUE TITLE
存在单机启动生产者消费者时找不到生产者的问题

### ISSUE THREAD

**Issue by js20166098** [alibaba/spring-cloud-alibaba#2336]
2.2.7.RELEASE 版本在对应的生产者消费者同时启动时存在消费者找不到对应的dubbo生产者,我自己测试采用的单机同时启动生产者和消费者。采用的idea 的服务管理同时启动，可能生产者和消费者启动的间隔时间很短。我这里必现
https://github.com/spring-cloud-alibaba-study/NacosGradle/tree/spring-cloud-dubbo%E7%89%88%E6%9C%AC2.3.12.RELEASE
这里有我对应的所有组件的版本号

**Comment by yuhuangbin** [comment]
Spring Cloud Dubbo 组件目前不是很成熟，不建议生产使用哈~
