### ISSUE TITLE
spring cloud alibaba 2021.1版本更新计划

### ISSUE THREAD

**Issue by huxin889** [alibaba/spring-cloud-alibaba#2339]
你们好，spring cloud alibaba 2021.1 版 本在2021年4月发布之后一直没有更新，请问有没有计划更新呢，2.2.X.Release的版本wiki里写的是需要spring boot 2.3.12.RELEASE, 该版本社区已经不会再维护了，spring cloud alibaba计划什么时候迁到较新的版本上去呢？

**Comment by Comven** [comment]
的确是很久没有动静了

**Comment by lin-mt** [comment]
> 的确是很久没有动静了

有打算放弃了～

**Comment by huxin889** [comment]
> > 的确是很久没有动静了
> 
> 有打算放弃了～

当年dubbo我等了三年，唉~

**Comment by steverao** [comment]
最近社区计划适配Spring Cloud 2021.x，大家有兴趣的也可以一起参与进来哈：）

**Comment by lin-mt** [comment]
> 最近社区计划适配Spring Cloud 2021.x，大家有兴趣的也可以一起参与进来哈：）

如何参与呢
