### ISSUE TITLE
配置管理中每个配置条目添加fileExtension项

### ISSUE THREAD

**Issue by tomalloc** [alibaba/spring-cloud-alibaba#2341]
## 背景
nacos配置中可以对每一条配置记录指定对于的数据格式(properties、json、yml等)
## 现状
nacos client是不区分具体格式操作的。现有的spring cloud 配置类 `NacosConfigProperties` 中  `fileExtension` 对整个应用来说是全局的。一旦设置了全局的 `fileExtension`，那么应用中的配置条目只能是一种类型。目前可以将fileExtension设置为 **空** ,对应的dataId带上具体的文件格式(如:redis.yml) ,这样就会获得到对应的文件扩展名，进而就能匹配到对应的  PropertySourceLoader 来解析配置。
## 期望
在 `NacosConfigProperties.Config` 添加 `fileExtension` 字段。按以下优先级获取

1. 优先用 `NacosConfigProperties.Config` 中的
2. 1中不存在，用现有`NacosConfigProperties`类中的 `fileExtension`
3. 2 也不配置的时候才根据 dataId的名称解析获取

**Comment by yuhuangbin** [comment]
目前是支持按 dataId 后缀来做相应格式的解析的，在 `NacosConfigProperties.Config` 添加 `fileExtension` 独立字段来支持对应格式解析，感觉意义不大。 欢迎讨论~
