### ISSUE TITLE
NacosReactiveDiscoveryClient#getServices()  empty will be returned when Error

### ISSUE THREAD

**Issue by qq843700497** [alibaba/spring-cloud-alibaba#2343]
**Which Component**
spring-cloud-starter-alibaba-nacos-discovery-2.2.6.RELEASE

**Describe the bug**
现象：spring cloud gateway集成spring-cloud-starter-alibaba-nacos-discovery-2.2.6.RELEASE后，当nacos服务端不可用时，或者gateway到nacos网络不可达时。访问gateway,会返回404。
问题过程：gateway会以nacos客户端发出的心跳事件为节奏，通过NacosReactiveDiscoveryClient.java中的getServices()方法获取服务列表，以此列表更新路由转发规则。当nacos服务端不可用或者网络不可达时，getServices方法会返回空列表。网关以此空列表更新路由规则，导致通过网关转发服务时，因无对应路由转发规则，向请求方返回404。

期望： 当nacos服务端不可用或者网络不可达时，nacos客户端可以返回缓存的服务列表。

建议：请作者重点关注NacosReactiveDiscoveryClient.java中的getServices()中的异常处理是否需要优化。目前的实现是当出现连接异常时，返回空列表。调用方无法分辨是连接异常还是nacos上的服务列表真的为空。 eureka的作法是，当连接异常时，返回本地缓存的服务列表。期望nacos的客户端和eureka行为一致，应用才能不需要修改代码，无缝在eureka和nacos之间做切换。当nacos客户端使用缓存时，应用可增加对网络波动和nacos短期故障的容错。

java: 1.8
spring-cloud-starter-alibaba-nacos-discovery: 2.2.6.RELEASE
spring cloud gateway:2.2.6.RELEASE

**Comment by DanielLiu1123** [comment]
1. `NacosReactiveDiscoveryClient#getServices` 方法应该是和 gateway 更新路由规则没有关系, gateway 如何路由可以先看一下 `ReactiveLoadBalancerClientFilter`, 这个方法暂时貌似只用在了健康检查, 但是这里确实有一点问题, 每次都需要去请求服务端拉取服务列表 (测试了一下耗时均在 100ms 以上), 确实可以缓存到本地, 减少健康检查开销
2. gateway 更新服务对应的实例列表, 是由 `ServiceInstanceListSupplier` 所决定的, 如果你是用的是默认配置, 那么默认会使用缓存服务实例的形式, 并且隔一定时间刷新缓存, 按理说只要 缓存失效 和 gateway到nacos网络不可达 没有同时发生, 都不会出现 404, 当然前提是你没有做特殊配置, 你可以更加详细的说明一下你的使用情况
3. 可能说的不是很对, 不要骂我 QAQ

**Comment by yuhuangbin** [comment]
正常情况下Nacos Server不可用，是有客户端本地缓存的，应该不会出现Nacos Server不可用，客户端本地路由信息清空，可以说下具体使用方式

**Comment by qq843700497** [comment]
> 1. `NacosReactiveDiscoveryClient#getServices` 方法应该是和 gateway 更新路由规则没有关系, gateway 如何路由可以先看一下 `ReactiveLoadBalancerClientFilter`, 这个方法暂时貌似只用在了健康检查, 但是这里确实有一点问题, 每次都需要去请求服务端拉取服务列表 (测试了一下耗时均在 100ms 以上), 确实可以缓存到本地, 减少健康检查开销
> 2. gateway 更新服务对应的实例列表, 是由 `ServiceInstanceListSupplier` 所决定的, 如果你是用的是默认配置, 那么默认会使用缓存服务实例的形式, 并且隔一定时间刷新缓存, 按理说只要 缓存失效 和 gateway到nacos网络不可达 没有同时发生, 都不会出现 404, 当然前提是你没有做特殊配置, 你可以更加详细的说明一下你的使用情况

1，我改用开源网关和nacos配合，最小配置，仅配置了NacosReactiveDiscoveryClient#getServices=true（和注册中心配合动态配置路由规则，必须配置此项为true）。仍然是我描述的现象。 不需要网络和缓存失效同时发生，只要网络不可达，就会404。
2，很容易复现和发现问题，请打断点对比。NacosReactiveDiscoveryClient#getServices和getInstances（转到了loadInstancesFromNacos方法），结构类似。都是在try中获取服务或实例列表，在catche中返回空列表。可以在正常获取和catch中打断点对比，正常情况下都是只执行try中逻辑。将网络断开后（nacos服务端不要在同一机器），这两个方法再被调用时，表现不同。getInstances不会进入cache，没有返回空实例列表。 而相反的，getServices会进入到catch中，返回空列表。 网关会周期性（30s）的调用这两个方法，因为getServices导致网关更新路由规则为空，无法转发。 对于这个问题没有被发现，应该是一般应用调用getInstances比较频繁，较少调用getServices方法。
3，我自己复写了getServices方法，在try可正常处理时，缓存结果。当进入到catch后，不再使用原逻辑，反回空列表，而是返回最后一次缓存的结果。经过以上改造，可解决nacos服务端故障或网络不可达时，网关也跟着不可用的问题。 请作者帮看下这样临时改造是否可行。是否需要在源码中对此处进行优化。

**Comment by qq843700497** [comment]
> 1，我改用开源网关和nacos配合，最小配置，仅配置了NacosReactiveDiscoveryClient#getServices=true（和注册中心配合动态配置路由规则，必须配置此项为true）。仍然是我描述的现象。 不需要网络和缓存失效同时发生，只要网络不可达，就会404。
> 2，很容易复现和发现问题，请打断点对比。NacosReactiveDiscoveryClient#getServices和getInstances（转到了loadInstancesFromNacos方法），结构类似。都是在try中获取服务或实例列表，在catche中返回空列表。可以在正常获取和catch中打断点对比，正常情况下都是只执行try中逻辑。将网络断开后（nacos服务端不要在同一机器），这两个方法再被调用时，表现不同。getInstances不会进入cache，没有返回空实例列表。 而相反的，getServices会进入到catch中，返回空列表。 网关会周期性（30s）的调用这两个方法，因为getServices导致网关更新路由规则为空，无法转发。 对于这个问题没有被发现，应该是一般应用调用getInstances比较频繁，较少调用getServices方法。
> 3，我自己复写了getServices方法，在try可正常处理时，缓存结果。当进入到catch后，不再使用原逻辑，反回空列表，而是返回最后一次缓存的结果。经过以上改造，可解决nacos服务端故障或网络不可达时，网关也跟着不可用的问题。 请作者帮看下这样临时改造是否可行。是否需要在源码中对此处进行优化。

1，我改用开源网关和nacos配合，最小配置，仅配置了NacosReactiveDiscoveryClient#getServices=true（和注册中心配合动态配置路由规则，必须配置此项为true）。仍然是我描述的现象。 不需要网络和缓存失效同时发生，只要网络不可达，就会404。
2，很容易复现和发现问题，请打断点对比。NacosReactiveDiscoveryClient#getServices和getInstances（转到了loadInstancesFromNacos方法），结构类似。都是在try中获取服务或实例列表，在catche中返回空列表。可以在正常获取和catch中打断点对比，正常情况下都是只执行try中逻辑。将网络断开后（nacos服务端不要在同一机器），这两个方法再被调用时，表现不同。getInstances不会进入cache，没有返回空实例列表。 而相反的，getServices会进入到catch中，返回空列表。 网关会周期性（30s）的调用这两个方法，因为getServices导致网关更新路由规则为空，无法转发。 对于这个问题没有被发现，应该是一般应用调用getInstances比较频繁，较少调用getServices方法。
3，我自己复写了getServices方法，在try可正常处理时，缓存结果。当进入到catch后，不再使用原逻辑，反回空列表，而是返回最后一次缓存的结果。经过以上改造，可解决nacos服务端故障或网络不可达时，网关也跟着不可用的问题。 请作者帮看下这样临时改造是否可行。是否需要在源码中对此处进行优化。

**Comment by yuhuangbin** [comment]
`spring.cloud.gateway.discovery.locator.enabled=true`
你是开启了这个配置项么？这个配置项会周期去注册中心拉取服务列表作为route，目前如果是注册中心不可用，就是返回empty（Nacos、Consul、Zk都是这么实现）

如果你开启这个功能是为了做动态路由，我觉得这不是一个好的方案，动态路由建议通过配置中心来下发路由配置，然后结合
`InMemoryRouteDefinitionRepository`来实现。

**Comment by qq843700497** [comment]
> 

注册中心不可用时，eureka不是返回的empty。spring.cloud.gateway.discovery.locator.enabled=true 开启这个特性后，网关和注册中心配合使用，就可以实现动态路由了。可以不必再新引入一个配置中心来下发路由配置了。配置中心下发的路由配置还需要人工手动操作配置。和注册中心配合使用，可以全自动的实现动态路由。显然前者是更好的方案。

**Comment by qq843700497** [comment]
> `spring.cloud.gateway.discovery.locator.enabled=true` 你是开启了这个配置项么？这个配置项会周期去注册中心拉取服务列表作为route，目前如果是注册中心不可用，就是返回empty（Nacos、Consul、Zk都是这么实现）
> 
> 如果你开启这个功能是为了做动态路由，我觉得这不是一个好的方案，动态路由建议通过配置中心来下发路由配置，然后结合 `InMemoryRouteDefinitionRepository`来实现。

注册中心不可用时，eureka不是返回的empty。spring.cloud.gateway.discovery.locator.enabled=true 开启这个特性后，网关和注册中心配合使用，就可以实现动态路由了。可以不必再新引入一个配置中心来下发路由配置了。配置中心下发的路由配置还需要人工手动操作配置。和注册中心配合使用，可以全自动的实现动态路由。显然前者是更好的方案。 @yuhuangbin

**Comment by yuhuangbin** [comment]
你这个做法仅仅是收集注册中心中的服务作为`Spring Cloud Gateway` 的`Route`，通常我们配置route还有很多其他的属性，所以用路由动态配置文件来做动态路由是常见方式，当然你提到的这个情况也是需要优化的点，欢迎一起参与社区~
