### ISSUE TITLE
请问一下seata是不是不支持3.1.0版本的openfeign，提示java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactor，请问有没有什么适配的方法

### ISSUE THREAD

**Issue by WalkFly** [alibaba/spring-cloud-alibaba#2348]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuhuangbin** [comment]
你可能是使用了剔除了ribbon实现的Spring Cloud 版本？

**Comment by WalkFly** [comment]
> 你可能是使用了剔除了ribbon实现的Spring Cloud 版本？

是的，openfeign 3.1.0版本已经剔除了ribbon，CachingSpringLoadBalancerFactor这个类在openfeign-core 2.1.0中有找到，但是3.1.0版本的openfeign的openfeign-core依赖是找不到的。请问一下有没有适配的方法？

**Comment by yuhuangbin** [comment]
试试 spring-cloud-loadbalancer

**Comment by WalkFly** [comment]
加入spring-cloud-loadbalancer还是提示java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactory

**Comment by WalkFly** [comment]
> 试试 spring-cloud-loadbalancer

加入spring-cloud-loadbalancer还是提示java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactory

**Comment by WithWindLuo** [comment]
我是`spring-cloud-starter-alibaba-seata`版本写错了，删掉指定版本用默认的`<version>2021.1</version>`就正常了
