### ISSUE TITLE
[Feature] Update Nacos to 1.4.2 in Spring Cloud Alibaba 2022.0

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2357]
1.Update Nacos to 1.4.2 in Spring Cloud Alibaba 2022.0

**Comment by a96219** [comment]
Why not 2.0.4?

**Comment by steverao** [comment]
> Why not 2.0.4?

Taking into account elements such as stability, this version supports 1.4.2 first.

**Comment by steverao** [comment]
solved
