### ISSUE TITLE
> 试试 spring-cloud-loadbalancer

### ISSUE THREAD

**Issue by WalkFly** [alibaba/spring-cloud-alibaba#2358]
> 试试 spring-cloud-loadbalancer

加入spring-cloud-loadbalancer还是提示java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactory

_Originally posted by @WalkFly in https://github.com/alibaba/spring-cloud-alibaba/issues/2348#issuecomment-1018094756_

**Comment by JacoBlunt** [comment]
大佬  怎么解决的呀？
