### ISSUE TITLE
Dubbo spring cloud 预计什么时候可以上生产环境

### ISSUE THREAD

**Issue by wangxuguang578** [alibaba/spring-cloud-alibaba#2359]
目前项目想用springcloud 但是服务调用想用dubbo，看wiki说Dubbo spring cloud目前还是preview版本，不适合上生产环境。请问这个升级有后续计划吗

**Comment by steverao** [comment]
社区短期内没有相关升级计划，如果希望实现 Spring Cloud 应用调用 Dubbo 服务，建议先直接通过 Spring Boot 将 Dubbo 服务暴露为 RESTful API 的方式以供对外调用。

**Comment by wangxuguang578** [comment]
> 社区短期内没有相关升级计划，如果希望实现 Spring Cloud 应用调用 Dubbo 服务，建议先直接通过 Spring Boot 将 Dubbo 服务暴露为 RESTful API 的方式以供对外调用。

好的
