### ISSUE TITLE
[Feature] 在2022.x版本中支持服务契约能力

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2362]
1.服务契约指，用户可以通过应用的某个接口去查询应用的所有服务元数据信息（类信息、服务名、参数列表、返回值类型）。
2.需要设计相关的数据接口来存储服务的元数据信息，第一期可以直接存储在内存中。
3.相关效果图可参见：https://help.aliyun.com/document_detail/181965.html

**Comment by galaxy-sea** [comment]
这个功能开发好像涉及到nacos的web页面吧

**Comment by kaori-seasons** [comment]
@steverao 
Hi everyone, I'm interested in this Can you assign this task to me?

**Comment by cevencheng** [comment]
Does this still need to be implemented ?  @steverao

**Comment by steverao** [comment]
We don't plan to do it recently and close first.
