### ISSUE TITLE
是否有生成 sts 授权信息的 api 操作？

### ISSUE THREAD

**Issue by steventong** [alibaba/spring-cloud-alibaba#238]
有需要生成 sts 授权给客户端单独访问oss的需求，oss-starter 里面没找到相关的api。

目前我这边还是根据java sdk实现的。

或者这块是独立的吗？有没有类似的 alibaba-sts-starter ？

**Comment by steventong** [comment]
有需要生成sts授权给客户端单独访问oss的需求，oss-starter里面没找到相关的api。

**Comment by fangjian0423** [comment]
Maybe we need a spring-cloud-alibaba-sts-starter module or we can do it in `spring-cloud-alicloud-context` module. 

Are you interested in doing it?

**Comment by steventong** [comment]
恩 过年放假的时候 有空我就试试
