### ISSUE TITLE
请问:  异构微服务调用Spring Cloud微服务时,需要在sidecar的配置文件里面配置网关的路由跳转吗?  

### ISSUE THREAD

**Issue by hongjiahao6** [alibaba/spring-cloud-alibaba#2385]
您好! 我分别用一个java应用,php应用模拟了异构微服务应用.  然后从微服务那边使用feign调取这两个应用是正常的,  但是不明白该如何从这两个应用往回调.  我看了文档, 使用了http工具类模拟发送了文档上的请求,但是一直是404.  所以想问一下是否还应配置相应的路由跳转, 和其正确的往回调用的方式. (尝试过配置路由跳转, 但是仍然是404).   十分感谢您的不吝赐教. 
![image](https://user-images.githubusercontent.com/99403704/153406814-30babdd8-206c-4b1f-b45a-0d9e6ad7a300.png)

**Comment by yuhuangbin** [comment]
使用问题请查阅资料及相关文档，example工程

**Comment by hongjiahao6** [comment]
> 使用问题请查阅资料及相关文档，example工程

我看了example以及相关文档,并没有异构服务往回调用的示例以及详细说明,只是说构建一个请求,但是我以http工具去构建相同结构的请求是失败的.

**Comment by qiuzhangming** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件。我将尽快给您回复。

**Comment by yuhuangbin** [comment]
> 是说构建一个请求,但是我以http工具去

异构服务调用其他应用，需要自己封装调用代码的

**Comment by cevencheng** [comment]
你异构服务既然已经通过Sidecar接入了微服务体系，那么你异构去调 SpringCloud 微服务时，直接通过本地的 Sidecar 走服务发现的调用方式，直接通过服务名调用即可。
例如：http://127.0.0.1:8088/order-demo/xxx

**Comment by steverao** [comment]
Long time without response and close first.
