### ISSUE TITLE
关于dubbo3.0适配

### ISSUE THREAD

**Issue by dujie-js** [alibaba/spring-cloud-alibaba#2386]
建议spring cloud alibaba 在下一个大的版本可以支持dubbo3.0挂载到spring cloud下

**Comment by steverao** [comment]
如果希望实现 Spring Cloud 应用调用 Dubbo 服务，建议先直接通过 Spring Boot 将 Dubbo 服务暴露为 RESTful API 的方式以供对外调用。这样两个组件互相都是独立的，比较推荐。
