### ISSUE TITLE
Scaffolding is vulnerable to xss vulnerability

### ISSUE THREAD

**Issue by xiaomingX1** [alibaba/spring-cloud-alibaba#2387]
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-web-sample/src/main/java/com/alibaba/cloud/dubbo/service/SpringRestService.java

the argument param ，and String b  is vulnerable to xss vulnerability

Advice：
 - Comment and alert users to the risks here

`

@GetMapping("/param")
	public String param(@RequestParam String param) {
		log("/param", param);
		return param;
	}

`

**Comment by steverao** [comment]
Do you want to alert the users to care about that? If yes, please create a PR！
