### ISSUE TITLE
The bean 'com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository' could not be injected as a 'com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository' because it is a JDK dynamic proxy that implements:

### ISSUE THREAD

**Issue by keylihai** [alibaba/spring-cloud-alibaba#2388]
**Which Component**
spring-cloud-starter-dubbo:2.2.5.RELEASE

**Describe what problem you have encountered**
16:44:34.623 [main] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'targeterBeanPostProcessor' defined in class path resource [com/alibaba/cloud/dubbo/autoconfigure/DubboOpenFeignAutoConfiguration.class]: Unsatisfied dependency expressed through method 'targeterBeanPostProcessor' parameter 1; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository' is expected to be of type 'com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository' but was actually of type 'com.sun.proxy.$Proxy86'
16:44:34.624 [main] INFO  c.a.c.d.s.DubboGenericServiceFactory - The Dubbo GenericService ReferenceBeans are destroying...
16:44:34.631 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
16:44:34.634 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository' could not be injected as a 'com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository' because it is a JDK dynamic proxy that implements:
	org.springframework.beans.factory.SmartInitializingSingleton
	org.springframework.context.ApplicationEventPublisherAware

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.

**Comment by steverao** [comment]
如果希望实现 Spring Cloud 应用调用 Dubbo 服务，建议先直接通过 Spring Boot 将 Dubbo 服务暴露为 RESTful API 的方式以供对外调用。

**Comment by kevinw66** [comment]
@keylihai 能否麻烦提供一个可复现的DEMO工程呢？
