### ISSUE TITLE
java.lang.RuntimeException: group must be configured for channel

### ISSUE THREAD

**Issue by frlzk** [alibaba/spring-cloud-alibaba#2391]
**Which Component**
spring-cloud-starter-stream-rocketmq

**Describe the bug**
In https://docs.spring.io/spring-cloud-stream/docs/3.2.1/reference/html/spring-cloud-stream.html#_configuration_options has following description:
```
group
    The consumer group of the binding. Applies only to inbound bindings. See Consumer Groups.
    Default: null (indicating an anonymous consumer).
```
But rocketmq binder required 'group' , it is in conflict with norms.

**To Reproduce**
1. Not config spring.cloud.stream.bindings.mytopic-in-0.group

**Expected behavior**
Excpect 'group' not required , and when not provider 'group' auto set messageModel=BROADCASTING .

**Screenshots**
```
Caused by: java.lang.RuntimeException: 'group must be configured for channel mytopic'
	at com.alibaba.cloud.stream.binder.rocketmq.RocketMQMessageChannelBinder.createConsumerEndpoint(RocketMQMessageChannelBinder.java:119)
	at com.alibaba.cloud.stream.binder.rocketmq.RocketMQMessageChannelBinder.createConsumerEndpoint(RocketMQMessageChannelBinder.java:57)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:408)
	... 27 common frames omitted
```

**Additional context**
e.g.  MacOS  、Java8 、 spring-cloud-starter-stream-rocketmq:2.2.7.RELEASE、spring-cloud-stream:3.1.2

**Comment by DanielLiu1123** [comment]
RocketMQ has a concept of consumer group, if you use RocketMQ as Broker, you need to configure group.

**Comment by frlzk** [comment]
If I use RocketMQ directly, I should follow the rules and concepts of RocketMQ. However, as the implementation of Binder, I think we should follow binder's rules. The purpose of using spring cloud stream is to shield the differences of the underlying MQ and facilitate MQ switching. The requirement that groups must be configured will lead to inconsistent behaviors of different Binder.

**Comment by DanielLiu1123** [comment]
> If I use RocketMQ directly, I should follow the rules and concepts of RocketMQ. However, as the implementation of Binder, I think we should follow binder's rules. The purpose of using spring cloud stream is to shield the differences of the underlying MQ and facilitate MQ switching. The requirement that groups must be configured will lead to inconsistent behaviors of different Binder.

Great point. Considering to fix it.
You can also submit PR to help improve this work.

**Comment by Sorieee** [comment]
I think I can solve this issue, will finish it this week or next week(maybe).

**Comment by Sorieee** [comment]
Do I need to write integration tests in this pull request?
Or write intergration test in my next pull request?

**Comment by Sorieee** [comment]
Will write some unit tests to verify.

**Comment by Sorieee** [comment]
This pr should be rollback, if set group null, will generate diff SubscriptionGroup when each restart，consumption progress will be recalculated.

**Comment by Sorieee** [comment]
Pls reopen this issue,needs to be discussed
