### ISSUE TITLE
The discovery chapter of wiki have some errors

### ISSUE THREAD

**Issue by onewe** [alibaba/spring-cloud-alibaba#2397]
https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery

1. example code 
![未命名](https://user-images.githubusercontent.com/38708836/154628362-92524271-ee3a-4158-8036-72e8dd60f4ef.png)

2. EndPoint
It's `http://ip:port/actuator/nacosdiscovery`, it's not `http://ip:port/actuator/nacos-discovery`

**Comment by yuhuangbin** [comment]
Thanks for your feedback, can you submit a pr to fix it?

**Comment by onewe** [comment]
Can I submit a pr for wiki page? is the page source in the `spring-cloud-alibaba-docs`? if it's over there i will submit a pr to fix this issue.
