### ISSUE TITLE
【nacos config】I use springboot 2.6.3 and springcloud 2021.0.1, then I want to use nacos config as config center, I want to know which nacos version should I can use.

### ISSUE THREAD

**Issue by luonaibin** [alibaba/spring-cloud-alibaba#2409]
I use springboot 2.6.3 and springcloud 2021.0.1, then I want to use nacos config as config center, I want to know which nacos version should I can use.
<spring.boot.version>2.6.3</spring.boot.version>
<spring.cloud.version>2021.0.1</spring.cloud.version>

<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
	<version>${nacos.version}</version>
</dependency>

who can tell me nacos.version?

**Comment by DanielLiu1123** [comment]
The latest version will support Springboot 2.6.3 and SpringCloud 2021.0.1, you can wait for the release, and nacos version is 1.4.2.

**Comment by mynzdbx** [comment]
我也有相同的问题。是使用spring-cloud-starter-alibaba-nacos-config和spring-cloud-starter-alibaba-nacos-discovery就必须引入spring cloud alibaba吗？原生spring cloud似乎无法使用nacos。spring cloud alibaba又无法使用java17

**Comment by DanielLiu1123** [comment]
> 我也有相同的问题。是使用spring-cloud-starter-alibaba-nacos-config和spring-cloud-starter-alibaba-nacos-discovery就必须引入spring cloud alibaba吗？原生spring cloud似乎无法使用nacos。spring cloud alibaba又无法使用java17

It is not necessary to use `spring cloud alibaba`, but it is recommended to use it, avoiding the version conflicts.

**Comment by luonaibin** [comment]
I use nacos-server 2.0.3, and my own SpringBoot micoservice program user nacos.version=2021.1, 
my pom.xml should import this
```xml
<dependency>
  <groupId>com.alibaba.cloud</groupId>
  <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
  <version>${nacos.version}</version>
  <exclusions>
    <exclusion>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-context</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bootstrap</artifactId>
  <version>3.0.0</version>
</dependency>
```

**Comment by DanielLiu1123** [comment]
> I use nacos-server 2.0.3, and my own SpringBoot micoservice program user nacos.version=2021.1, my pom.xml should import this
> 
> ```
> <dependency>
>   <groupId>com.alibaba.cloud</groupId>
>   <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>   <version>${nacos.version}</version>
>   <exclusions>
>     <exclusion>
>       <groupId>org.springframework.cloud</groupId>
>       <artifactId>spring-cloud-context</artifactId>
>     </exclusion>
>   </exclusions>
> </dependency>
> <dependency>
>   <groupId>org.springframework.cloud</groupId>
>   <artifactId>spring-cloud-starter-bootstrap</artifactId>
>   <version>3.0.0</version>
> </dependency>
> ```

If you want to use nacos 2.0.3 in spring cloud alibaba 2021.1
```xml
<dependency>
  <groupId>com.alibaba.cloud</groupId>
  <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
  <version>2021.1</version>
  <exclusions>
    <exclusion>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>com.alibaba.nacos</groupId>
  <artifactId>nacos-client</artifactId>
  <version>2.0.3</version>
</dependency>
```
