### ISSUE TITLE
在2.2.7版本@ConfigurationProperties 不能获取配置文件，2.2.6却可以

### ISSUE THREAD

**Issue by Tig3rkin** [alibaba/spring-cloud-alibaba#2410]
![image](https://user-images.githubusercontent.com/30619272/155272573-3d5b38f4-463c-4453-8448-d85ed66dc53f.png)

**Comment by DanielLiu1123** [comment]
If this is a mistake, you should consult the [Spring Boot](https://github.com/spring-projects/spring-boot) community.

BTW, this is not a very standard usage for `@ConfigurationProperties`.

You should make ConfigurationProperties simple.

```java
@ConfigurationProperties("your.prefix")
public class xxxProperties {
    private String one;
    // getters and setters....
}
```
then through `@EnableConfigurationProperties(xxxProperties.class)` to put it in Spring IOC.
