### ISSUE TITLE
Dubbo did not notify Nacos to log out of the service when the service was closed

### ISSUE THREAD

**Issue by tan-zhuo** [alibaba/spring-cloud-alibaba#2412]
**Which Component**
【spring-cloud-starter-dubbo】DubboServiceRegistrationNonWebApplicationAutoConfiguration.java

**Describe the bug**
dubbo服务优雅停机时，并没有通知 nacos service 进行服务正常下线。
导致nacos仍然进行心跳节拍检查，直到状态从健康变为不健康再到删除服务，在这期间，存在请求异常问题，gateway没有在第一时间获取到下线通知，导致部分流量流入已下线ip中。k8s中滚动更新时发现有异常流量排查出此问题（已设置容器最小就绪数据保证服务完全能够注册上nacos并检测直到健康状态）。

When the Dubbo service went down gracefully, nacos Service was not notified to take the service offline properly.
As a result, NACOS still checks heartbeat beats until the status changes from healthy to unhealthy and then deletes the service. During this period, abnormal requests exist, and the Gateway does not get offline notification in the first time, resulting in part of traffic flowing into offline IP addresses. Abnormal traffic was found during the rolling update in K8S to troubleshoot this problem (minimum container ready data has been set to ensure that the service can fully register with NACOS and detect until health status).

**To Reproduce**
1.启动dubbo service
2.正常关闭dubbo service
3.dubbo 没有通知nacos 下线服务
4.nacos 继续进行心跳检测

1.Start the Dubbo service
2.Shut down the Dubbo Service
3.Dubbo did not notify Nacos of the offline service
4.Nacos continued heartbeat detection

**Expected behavior**
nacos 优雅下线服务，而不是按照宕机处理。

Nacos gracefully takes the service offline, rather than treating it as an outage.

**Screenshots**
目前处理方式：
Current treatment:
![image](https://user-images.githubusercontent.com/32378959/155464379-43157e56-ca06-4d27-99f7-5f5eeb45f261.png)

**Additional context**
spring-cloud-alibaba 2.2.6.RELEASE

**Comment by DanielLiu1123** [comment]
We are considering whether to continue to support Dubbo module.

You override `DubboServiceRegistrationNonWebApplicationAutoConfiguration` ? Cause I do not this code in `2.2.6.RELEASE`.

And you have already given a good solution, if you change your implementation, it will be better, not through overriding the class.

**Comment by tan-zhuo** [comment]
> We are considering whether to continue to support Dubbo module.
> 
> You override ? Cause I do not this code in .`DubboServiceRegistrationNonWebApplicationAutoConfiguration``2.2.6.RELEASE`
> 
> And you have already given a good solution, if you change your implementation, it will be better, not through overriding the class.

![image](https://user-images.githubusercontent.com/32378959/155475144-fe57b656-3af0-49ec-86f3-a6d4dcb190a0.png)
Yes, I have solved this problem in a more sensible way, but why not continue to support the Dubbo module?

**Comment by DanielLiu1123** [comment]
see #2398
