### ISSUE TITLE
Spring Cloud Alibaba 2021.0.1.1 升级指南 中使用2021.0.1.1版本找不到相关的依赖

### ISSUE THREAD

**Issue by yaoysyao** [alibaba/spring-cloud-alibaba#2416]
根据链接 https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc  进行升级
如题
 `<spring-boot.version>2.6.3</spring-boot.version>
 <spring-cloud.version>2021.0.1</spring-cloud.version>
  <spring-cloud-alibaba.version>2021.0.1.1</spring-cloud-alibaba.version>
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    `</dependencyManagement>``
maven会提示找不到依赖项 'com.alibaba.cloud:spring-cloud-alibaba-dependencies:2021.0.1.1'

**Comment by Comven** [comment]
2021的版本只有2021.1吧，哪里有发布2021.0.1.1?

**Comment by steverao** [comment]
还没发布哈，只是提前准备了相关材料
