### ISSUE TITLE
Wiki修改：Nacos config无法获取配置，添加pom依赖修复

### ISSUE THREAD

**Issue by stone-monster** [alibaba/spring-cloud-alibaba#2419]
问题：参照[Nacos config](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config)示例构建，获取始终为本机用户名与null。
解决方案：从Spring Boot 2.4版本开始，配置文件加载方式进行了重构，添加spring-cloud-starter-bootstrap依赖即可。
参考：[①](https://www.jianshu.com/p/491db5791bf7?ivk_sa=1024320u)、[②](https://blog.csdn.net/weixin_43272781/article/details/116718747)

**Comment by DanielLiu1123** [comment]
Please give a minimum sample project to reproduce this problem if feasible, it will solve your problem more efficiently.

**Comment by steverao** [comment]
> 问题：参照[Nacos config](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config)示例构建，获取始终为本机用户名与null。 解决方案：从Spring Boot 2.4版本开始，配置文件加载方式进行了重构，添加spring-cloud-starter-bootstrap依赖即可。 参考：[①](https://www.jianshu.com/p/491db5791bf7?ivk_sa=1024320u)、[②](https://blog.csdn.net/weixin_43272781/article/details/116718747)

We very much welcome you to contribute relevant PR to the community to solve this problem.

**Comment by kaori-seasons** [comment]
Please assign to me
