### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config 2.2.7.RELEASE的ConfigService#getConfig获取不到配置

### ISSUE THREAD

**Issue by patience00** [alibaba/spring-cloud-alibaba#2422]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel
nacos
pom:
![image](https://user-images.githubusercontent.com/35128024/155871979-15dfd436-e9cc-431d-883a-0740962022d7.png)

springboot version:2.3.12.RELEASE

**Describe the bug**
com.alibaba.nacos.api.config.ConfigService#getConfig获取不到配置
com.alibaba.nacos.api.config.ConfigService#getConfig() cannot get config data

log:
2022-02-27 13:52:38.983  WARN 34772 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-gateway] & group[DEFAULT_GROUP]
2022-02-27 13:52:39.493  WARN 34772 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-gateway.json] & group[DEFAULT_GROUP]
2022-02-27 13:52:39.987  WARN 34772 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-gateway-dev.json] & group[DEFAULT_GROUP]

bootstrap.yml:
`spring:
  profiles:
    active: dev
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: blog
          uri: lb://blog
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}:8848
        username: ${NACOS_USER}
        password: ${NACOS_PASSWORD}
        namespace: public
      config:
        server-addr: ${NACOS_SERVER}:8848
        username: ${NACOS_USER}
        password: ${NACOS_PASSWORD}
        name: service-gateway
        namespace: public
        group: DEFAULT_GROUP

`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35128024/155871118-fcd0ff4c-ac10-4c05-a18a-929341e88f7f.png)

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

最后我配置文件,代码都没动,切换到
    <spring-cloud.version>Hoxton.SR9</spring-cloud.version>
        <alibaba-cloud.version>2.2.6.RELEASE</alibaba-cloud.version>
问题消失了;

**Comment by DanielLiu1123** [comment]
Please give a minimum sample project to reproduce this problem if feasible, it will solve your problem more efficiently.

BTW, 2021.0.1.0 has been released, you can try it. 2.2.x version has been outdated.

**Comment by HaojunRen** [comment]
从你的问题反馈来看，也许不是Nacos Config没拉到更新后的配置，而是这个配置在Gateway路由上不生效。有一个推测：Hoxton.SR9和Hoxton.SR12在Gateway路由配置上可能存在区别。以前我们曾经测试过G版的网关路由配置，在H版上不生效，至于Hoxton.SR9的路由配置在Hoxton.SR12上生效与否，并不确定，建议你debug一下

**Comment by DanielLiu1123** [comment]
2.2.7使用的nacos为版本为2.x，如果你的nacos-server为1.x版本，那会那出现问题，2.x客户端不支持1.x服务端

**Comment by patience00** [comment]
> 

我服务端用的是最新版,然后本地启动的standalone模式,cloud和nacos版本都参照的https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by patience00** [comment]
问题应该是出在<alibaba-cloud.version>2.2.7.RELEASE</alibaba-cloud.version>和<spring-cloud.version>Hoxton.SR12</spring-cloud.version>这两个版本之间

**Comment by DanielLiu1123** [comment]
可以给一个最小示例复现这个问题吗

**Comment by lcxw** [comment]
换单机版的NACOS就没问题
