### ISSUE TITLE
[Announce] Spring Cloud Alibaba 2021.0.1.0 released

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2424]
Hello Community,

We are very glad to announce that Spring Cloud Alibaba 2021.0.1.0 is released.

You can check detailed release notes here:

2021.0.1.0 : https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2021.0.1.0

Upgrade related reference materials can be found：https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc

If you have any questions using this version, please report the issue on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by EdwardVanWow** [comment]
为什么nacos的版本是1.x？

**Comment by steverao** [comment]
> 为什么nacos的版本是1.x？

这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持

**Comment by EdwardVanWow** [comment]
> > 为什么nacos的版本是1.x？
> 
> 这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持

可以换成2.x的版本吗？因为2.x性能提升比较高

**Comment by steverao** [comment]
> > > 为什么nacos的版本是1.x？
> > 
> > 
> > 这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持
> 
> 可以换成2.x的版本吗？因为2.x性能提升比较高

可以自己替换依赖去使用，但是社区不保证是否存在依赖冲突和稳定性方面问题

**Comment by wudaoshengu** [comment]
about dubbo spring cloud ：
所有的demo 没有在 provider端的单元测试

**Comment by colddew** [comment]
> > 为什么nacos的版本是1.x？
> 
> 这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持

这只是结果吧，并没有解释为什么Nacos和Dubbo还是用的比较低的版本，只是稳定性考虑？支持Nacos2.x和Dubbo3.x在规划中么？

**Comment by steverao** [comment]
> > > 为什么nacos的版本是1.x？
> > 
> > 
> > 这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持
> 
> 这只是结果吧，并没有解释为什么Nacos和Dubbo还是用的比较低的版本，只是稳定性考虑？支持Nacos2.x和Dubbo3.x在规划中么？

这个就是原因，一个大版本的spring cloud 对应的nacos版本要支持全面，否则很多使用nacos 1.x的客户(1.x还是很多企业一直在用的版本)发现nacos 1.4.2以下版本有问题，而1.4.2版本又没有对应的sca版本支持，只能升级nacos 2.0对其影响面也很大

**Comment by steverao** [comment]
> > > 为什么nacos的版本是1.x？
> > 
> > 
> > 这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持
> 
> 这只是结果吧，并没有解释为什么Nacos和Dubbo还是用的比较低的版本，只是稳定性考虑？支持Nacos2.x和Dubbo3.x在规划中么？

Nacos 2.x在规划中了，了解一下Spring Cloud Dubbo你是有使用吗？具体场景可以介绍一下吗？这个我们目前决定不在主分支上维护Spring Cloud Dubbo组件了，相关讨论见 #2398

**Comment by colddew** [comment]
> > > > 为什么nacos的版本是1.x？
> > > 
> > > 
> > > 这一块是考虑到支持Nacos版本的连续性，因为spring cloud 近一年出的新版本没有对nacos 1.4.2的支持
> > 
> > 
> > 这只是结果吧，并没有解释为什么Nacos和Dubbo还是用的比较低的版本，只是稳定性考虑？支持Nacos2.x和Dubbo3.x在规划中么？
> 
> Nacos 2.x在规划中了，了解一下Spring Cloud Dubbo你是有使用吗？具体场景可以介绍一下吗？这个我们目前决定不在主分支上维护Spring Cloud Dubbo组件了，相关讨论见 #2398

我们目前在尝试使用SCA，考虑到后期会上k8s和Service Mesh，同时还可能会用到Dubbo，那么Duboo3.x会有更好的兼容性。引入更高版本的Dubbo，目前需要exclude掉SCA对应的依赖，重新引入dubbo-spring-boot-starter等，前段时间调研时遇到过一些依赖问题没解决掉暂时放弃了。如果决定放弃SCD组件，也希望社区能给出一个SpringCloud开发引入Dubbo3.x的最佳实践方式

**Comment by Liesport758** [comment]
https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc，不能打开 了

**Comment by DanielLiu1123** [comment]
moved to https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc

**Comment by ilaotan** [comment]
dubbo用户,本想偷懒直接用cloud相关nacos组件,结果还停留在1.4.x阶段.
