### ISSUE TITLE
[nacos config]when I use properties as my default file-extension, properties can not resolve as follows data

### ISSUE THREAD

**Issue by luonaibin** [alibaba/spring-cloud-alibaba#2425]
nacos version 2021.1
nacos server 2.0.3
springboot 2.5.9
springcloud 2020.0.5

redis.password=k_=.p04jTp-=d.0opFddj.hjh1hh_=.mNo0

then, nacos config can not resolve the redis.password parameter, When I use yaml file, It can run usually.

**Comment by DanielLiu1123** [comment]
If possible, please give a minimum sample project to reproduce this problem, it will solve your problem more efficiently.

See [release notes](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E).

**Comment by luonaibin** [comment]
when the value "k_=.p04jTp-=d.0opFddj.hjh1hh_=.mNo0 " as common parameter, like  nacos.redis=k_=.p04jTp-=d.0opFddj.hjh1hh_=.mNo0 , program resolve the value nacos.redis usually, 
`@Value("${nacos.redis}")
    private String nacosRedis;`

`@GetMapping("/test/nacosredis")
    public String getNacosRedis(){
        return "Nacos.redis=" + nacosRedis;
    }`

it returns `Nacos.redis=k_=.p04jTp-=d.0opFddj.hjh1hh_=.mNo0`

but, when redis.password=k_=.p04jTp-=d.0opFddj.hjh1hh_=.mNo0 as redis password, then , cannot visit the redis and do some read & write operations, 
`@GetMapping("/test/redis")
    public String redisTest(){
        boolean ifAbsent = redisCacheRepository.setIfAbsent("testRedis", "OK", 20, TimeUnit.SECONDS);
        return "redis test:" + ifAbsent;
    }`

it returns '{"code":500,"message":"Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to *.*.*:6379","data":{}}'

**Comment by yuhuangbin** [comment]
Your configuration information includes the special character `=`，maybe you can use `"..."` to reference them?

**Comment by luonaibin** [comment]
I use the yaml file instead of properties, that can solve the problem, redis password which other teams is using, so I have no rights to modify password.
