### ISSUE TITLE
loadBalancer use NacosRule  Random string of microservice calls

### ISSUE THREAD

**Issue by roneywei** [alibaba/spring-cloud-alibaba#2430]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

NacosRule Random string of microservice calls

ALL microservice LoadBalancer use  NacosRule 

    /**
     * 指定所有服务负载均衡策略使用nacos策略
     *
     * @return
     */
    @Bean
    public IRule ribbonRule() {
        return new NacosRule();
    }

gateway one   call  service-A   then call service-B

when again call service-A ，the loadBalancer is use service-B

spring-cloud-starter-alibaba-nacos-discovery version 2.2.6.RELEASE
![nacosRule 服务乱窜 drawio](https://user-images.githubusercontent.com/5858867/156491922-e07889f8-c4b5-4888-ab0b-f4534c541b3d.png)

![调用服务A](https://user-images.githubusercontent.com/5858867/156492980-4ff20cf0-caeb-45c2-b05c-d03b07817ad1.png)

![调用服务B](https://user-images.githubusercontent.com/5858867/156493038-42b43c79-6e29-4903-9b74-1d98ceb41874.png)

![再次调用服务A](https://user-images.githubusercontent.com/5858867/156493055-49f47abe-e4e6-4f93-af9d-12a4e763c699.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by yuhuangbin** [comment]
```java
@Bean
@Scope("prototype")
public IRule ribbonRule() {
    return new NacosRule();
}
```

**Comment by steverao** [comment]
Long time without response and close.
