### ISSUE TITLE
使用2021.0.1.0版本去除掉bootstrap.yml文件后使用spring.config.import获取不到nacos上的配置文件

### ISSUE THREAD

**Issue by yaoysyao** [alibaba/spring-cloud-alibaba#2432]
如题，按照 https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc 所说明的配置方式，对现有项目升级，发现去除掉
`        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>`
之后，使用application.yml获取nacos上的配置，发现无法获取配置，nacos版本1.4.2
application.yml
`
server:
  port: 8081
  servlet:
    context-path: /auth
spring:
  application:
    name: manager-auth
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        file-extension: ${nacos.file-extension}
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
  config:
    import:
      - optional:nacos:manager-auth-dev.yml?group=${nacos.group} # 覆盖默认 group，监听 group_01:test01.yml
> `

**Comment by jianhao2010303** [comment]
file-extension: ${nacos.file-extension} 删除下试一试。

**Comment by DanielLiu1123** [comment]
有报错吗？

**Comment by yaoysyao** [comment]
> 有报错吗？

启动的时候有报错，错误就是找不到配置的信息，比如数据库密码错误等，现在已经回退到原来使用bootstrap.yml的方式了，这种方式是可以正常访问nacos上的配置文件的

**Comment by jianhao2010303** [comment]
1。查看下 boot的版本，是不是2.6.*。
2。查看下bootstrap是否还有引用。

**Comment by yaoysyao** [comment]
> 1。查看下 boot的版本，是不是2.6.*。 2。查看下bootstrap是否还有引用。

已解决，谢谢啦

**Comment by yaoysyao** [comment]
> 有报错吗？

已解决，谢谢啦

**Comment by MnameHZJ** [comment]
> group=

什么原因呢

**Comment by MnameHZJ** [comment]
> > 有报错吗？
> 
> 已解决，谢谢啦

什么原因导致的呢
