### ISSUE TITLE
What is the plan for branch management? 

### ISSUE THREAD

**Issue by code-ferry** [alibaba/spring-cloud-alibaba#2435]
**Which Component**
spring cloud alibaba

**Describe what problem you have encountered**
A few days ago we saw the 2022.x branch, today we only see 2021.x.  What is the plan for branch management? 

**Describe what information you have read**

**Comment by steverao** [comment]
There are two main branches now, 2021.x and 2.2.x, 2.2.x branch corresponds to some old versions of spring cloud alibaba, 2021.x corresponds to spring cloud alibaba 2021.x. The 2022.x branch appeared because the version number was not determined at the beginning
