### ISSUE TITLE
2021.0.1.0版本可以把nacos升级到2.x版本吗，现在1.4.2有BUG

### ISSUE THREAD

**Issue by startjava** [alibaba/spring-cloud-alibaba#2438]
https://github.com/alibaba/nacos/issues/7698

这个bug在1.4.2中存在，导致nacos集群启动时出现问题。

现在的spring cloud alibaba最新版用的还是旧的nacos版本，建议升级。

**Comment by DanielLiu1123** [comment]
Considering to support Nacos 2.x in next version.

**Comment by C20171008S** [comment]
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${cloud.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions>
                    <exclusion>
                        <groupId>com.alibaba.nacos</groupId>
                        <artifactId>nacos-client</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>${nacos.version}</version>
            </dependency>

**Comment by shuangpai** [comment]
> [alibaba/nacos#7698](https://github.com/alibaba/nacos/issues/7698)
> 
> 这个bug在1.4.2中存在，导致nacos集群启动时出现问题。
> 
> 现在的spring cloud alibaba最新版用的还是旧的nacos版本，建议升级。

<img width="822" alt="QQ20220308-094103@2x" src="https://user-images.githubusercontent.com/12716056/157149033-0f4a7b63-e6a0-4a98-8501-913782e2ddd5.png">

**Comment by startjava** [comment]
从1.4.2升级到2版本，兼容性是否能得到保障 ？

**Comment by DanielLiu1123** [comment]
2021.0.1.0 版本使用 2.x 会出现问题，下版本应该会支持 2.x

**Comment by startjava** [comment]
发现版本更新周期需要2，3个月，有些慢了哟，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] 2021.0.1.0版本可以把nacos升级到2.x版本吗，现在1.4.2有BUG (Issue #2438)





 
2021.0.1.0 版本使用 2.x 会出现问题，下版本应该会支持 2.x
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DanielLiu1123** [comment]
可以手动升级 nacos-client 到2.x，但是需要在 2.0.3 以下

**Comment by colddew** [comment]
同样的问题，最新版spring-cloud-alibaba 2021.0.1.0对Nacos和Dubbo支持的版本还比较低，希望可以尽快升级，手动调整依赖遇到各种问题，希望官方可以尽快升级解决Nacos2.x和Dubbo3.x的依赖问题

**Comment by DanielLiu1123** [comment]
下版本应该会支持 Nacos 2.x，Dubbo 问题请看 #2398

**Comment by Comven** [comment]
> 可以手动升级 nacos-client 到2.x，但是需要在 2.0.3 以下

2.0.4都不行？

**Comment by startjava** [comment]
我的想法啊，别手动升级，对付用1.4.2吧，至少我用起来没有大的功能性错误，环境能出来，，等官方新版本升级依赖到2.x版本吧，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] 2021.0.1.0版本可以把nacos升级到2.x版本吗，现在1.4.2有BUG (Issue #2438)





  
可以手动升级 nacos-client 到2.x，但是需要在 2.0.3 以下
  
2.0.4都不行？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaojunRen** [comment]
我解释一下，原因是Nacos 2.0.4做了很小的优化重构，很不幸的是恰巧会导致不兼容问题，那么，SCA需要同步变更，而2.0.3没有该优化，所以是兼容的，这并不是什么功能性的问题。目前SCA最新未发布版本的代码上已经兼容了2.0.4，用户可以有两个选择
- 换成2.0.3
- 等待下个SCA版本发布

**Comment by DanielLiu1123** [comment]
> 2.0.4都不行？

如果使用老方式（bootstrap）启动应用，那么 2.0.4 是 OK 的；如果想使用 import 方式启动应用，那么需要 nacos-client 版本小于或者等于 2.0.2

**Comment by startjava** [comment]
我等下一个版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neptune ***@***.***&gt;
发送时间: 2022年3月11日 10:30
收件人: alibaba/spring-cloud-alibaba ***@***.***&gt;
抄送: startjava ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/spring-cloud-alibaba] 2021.0.1.0版本可以把nacos升级到2.x版本吗，现在1.4.2有BUG (Issue #2438)





 
我解释一下，原因是Nacos 2.0.4做了很小的优化重构，很不幸的是恰巧会导致出现不兼容问题，那么，SCA需要同步变更，而2.0.3没有该优化，所以是兼容的，这并不是什么功能性的问题。目前SCA最新未发布版本的代码上已经兼容了2.0.4，用户可以有两个选择
  
换成2.0.3 

等待下个SCA版本发布 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
