### ISSUE TITLE
SpringCloudAlibaba2021.0.1.0使用nacos-client2.0.3出现  Couldn't load full implementation for TraceComponent, now trying to load lite implementation

### ISSUE THREAD

**Issue by rottenmu** [alibaba/spring-cloud-alibaba#2454]
**Which Component**
Nacos Discovery 2.0.3

**Describe what problem you have encountered**
Couldn't load full implementation for TraceComponent, now trying to load lite implementation

**Describe what information you have read**
Couldn't load full implementation for TraceComponent, now trying to load lite implementation

**Comment by steverao** [comment]
Please add some more detailed error message
