### ISSUE TITLE
服务提供方启动成功注册到Nacos上，但是消费者却拉不到服务

### ISSUE THREAD

**Issue by 631876058** [alibaba/spring-cloud-alibaba#2458]
clone 下来的项目，2.2.8-SNAPSHOT。

先启动了 spring-cloud-alibaba-dubbo-server 可以在 Nacos Server 2.0.3 上看到服务的注册信息，
然后启动了 spring-cloud-alibaba-dubbo-client ，报错 No provider available for the service com.alibaba.cloud.dubbo.service.EchoService

请问，这是怎么回事呢？

**Comment by steverao** [comment]
Spring Cloud Dubbo模块在项目主分支暂不进行维护，#2398
