### ISSUE TITLE
spring.cloud.alibaba2021.0.1.0,nacos1.4.2无法自动刷新配置

### ISSUE THREAD

**Issue by liuyiyo** [alibaba/spring-cloud-alibaba#2461]
参考的官方提供的Spring boot >= 2.4.0 版本,import示例:
![image](https://user-images.githubusercontent.com/52642305/158408843-03a40a6a-49f0-4a9e-9db3-c6e739468933.png)
![image](https://user-images.githubusercontent.com/52642305/158408937-e7731fb4-aa91-473a-8805-0d689911f2fd.png)
![image](https://user-images.githubusercontent.com/52642305/158408990-ca7027d3-ce11-4982-aabc-6e4c4668b3b0.png)
控制台可以看到刷新的日志,但是获取的值还是旧的
![image](https://user-images.githubusercontent.com/52642305/158409111-f2a31563-7fa7-4e9b-9727-d8ab1b68b0ba.png)

**Comment by imyxiao** [comment]
Try adding @RefreshScope?

**Comment by liuyiyo** [comment]
@[imyxiao](https://github.com/imyxiao)
感谢大佬及时解答,加了@RefreshScope确实可以了,但是官方的Example里面没加这个注解也.
![image](https://user-images.githubusercontent.com/52642305/158414029-d4979d52-4326-4aef-980c-34aade4beaef.png)

**Comment by imyxiao** [comment]
@liuyiyo 

看这里的文档：

https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html

**Comment by liuyiyo** [comment]
@imyxiao 
好的,谢谢
