### ISSUE TITLE
关于import方式引入配置文件的疑问

### ISSUE THREAD

**Issue by liuyiyo** [alibaba/spring-cloud-alibaba#2465]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Config

**Describe what problem you have encountered**
![image](https://user-images.githubusercontent.com/52642305/158624101-e7efe186-b81a-431a-be14-003c80874aaa.png)
如果我采用了spring.config.import的方式引入配置文件,那是不是根据dataId的格式自动引入就没什么意义了?
![image](https://user-images.githubusercontent.com/52642305/158623998-93c41c8d-3ee8-4117-9a01-51c7c98c4907.png)

我目前基于import的用法如下,麻烦大佬看下是否合理?
![image](https://user-images.githubusercontent.com/52642305/158624657-3aa27cc8-91a6-42bb-ba2e-421a61cb9f36.png)
![image](https://user-images.githubusercontent.com/52642305/158624690-06992c19-9557-4d9d-80b7-922d4a2058f0.png)
![image](https://user-images.githubusercontent.com/52642305/158624719-261e9e99-a043-44f8-8711-c251a4c00483.png)
一个开发环境,一个测试环境.通过namespace区分

**Comment by ysuwei** [comment]
我感觉也是这样

**Comment by DanielLiu1123** [comment]
这是推荐的方式
