### ISSUE TITLE
【求助】spring-cloud-gateway使用nacos启动不成功

### ISSUE THREAD

**Issue by cxzucc** [alibaba/spring-cloud-alibaba#2467]
前几天把项目的spring-cloud-gateway版本升级到了3.1.1，nacos的版本升级到2021.0.1.0，发现启动不了。
debug看了下，是阻塞在了WeightCalculatorWebFilter类locator.getRoutes().blockLast()这个地方。
邮件问了下鬼佬，他说不知道为什么，就不鸟我了。
后来在配置文件里加了下spring.cloud.gateway.predicate.weight.enabled=false，可以启动起来了。
不知道各位大佬，有没有谁知道这是什么原因导致的？

	public void onApplicationEvent(ApplicationEvent event) {
		if (event instanceof PredicateArgsEvent) {
			handle((PredicateArgsEvent) event);
		}
		else if (event instanceof WeightDefinedEvent) {
			addWeightConfig(((WeightDefinedEvent) event).getWeightConfig());
		}
		else if (event instanceof RefreshRoutesEvent && routeLocator != null) {
			// forces initialization
			if (routeLocatorInitialized.compareAndSet(false, true)) {
				// on first time, block so that app fails to start if there are errors in
				// routes
				// see gh-1574
				routeLocator.ifAvailable(locator -> locator.getRoutes().blockLast());
			}
			else {
				// this preserves previous behaviour on refresh, this could likely go away
				routeLocator.ifAvailable(locator -> locator.getRoutes().subscribe());
			}
		}

	}

**Comment by DanielLiu1123** [comment]
测试并没有出现这种情况，如果是直接启动失败那么应该是路由配置有问题

**Comment by cxzucc** [comment]
> 测试并没有出现这种情况，如果是直接启动失败那么应该是路由配置有问题

我gateway本地的配置文件里，没有配路由规则

**Comment by DanielLiu1123** [comment]
能给一个最小示例复现这个问题吗

**Comment by cxzucc** [comment]
新搞了个项目，复现不出来，可能还是原项目哪里的配置有问题，我先自己排查下，谢谢。

**Comment by cxzucc** [comment]
> 能给一个最小示例复现这个问题吗

是因为在SCG里注入了feign导致的问题，原先2.x的版本里确实是不能用，后来SCG升级到3.0.1又可以用了，我还以为这个问题解决了。

**Comment by cxzucc** [comment]
不过还没搞明白为什么注入feign会导致WeightCalculatorWebFilter类locator.getRoutes().blockLast()这个地方卡在那不动了。

**Comment by zhangliang198722** [comment]
出现了类型的问题，根据第一个提问者的描述，尝试设置
`spring.cloud.gateway.predicate.weight.enabled=false `
设置后服务正常运行，nacos 的负载断言其应该存在问题，请作者修复

**Comment by zhangliang198722** [comment]
> 不过还没搞明白为什么注入feign会导致WeightCalculatorWebFilter类locator.getRoutes().blockLast()这个地方卡在那不动了。

我猜你和我偶一样子gateway 里调用了其它服务，这时候loadbalancer开始运行所以执行内容被挂起了，代码无法向下运行

**Comment by DanielLiu1123** [comment]
> > 不过还没搞明白为什么注入feign会导致WeightCalculatorWebFilter类locator.getRoutes().blockLast()这个地方卡在那不动了。
> 
> 我猜你和我偶一样子gateway 里调用了其它服务，这时候loadbalancer开始运行所以执行内容被挂起了，代码无法向下运行

能给个demo复现问题吗

**Comment by HaojunRen** [comment]
2021版的Spring Cloud Gateway不能通过Feign阻塞式调用其它服务，而H版可以。不仅仅Feign，任何对WebFlux起阻塞的代码都不可以

**Comment by cxzucc** [comment]
> 2021版的Spring Cloud Gateway不能通过Feign阻塞式调用其它服务，而H版可以。不仅仅Feign，任何对WebFlux起阻塞的代码都不可以

这个我是知道的，在SCG的filter里也是用非阻塞方式调用feign的，只是会去注入feign的实例。
现在的问题是，SCG在某个版本里，修改了WeightCalculatorWebFilter类的代码，在onApplicationEvent方法中加了一行代码（具体见我的问题），导致网关启动卡在那里。我觉得应该不是nacos的问题，可能是跟spring-cloud-openfeign有关，debug看的时候，这个代码是被spring-cloud-openfeign初始化的时候触发的。

**Comment by HaojunRen** [comment]
参考:
https://github.com/spring-cloud/spring-cloud-gateway/issues/2126

https://github.com/spring-cloud/spring-cloud-gateway/issues/1090

**Comment by HaojunRen** [comment]
你确定在202x版的scg有Feign调用的影子？官方明确给出答案，需要用WebClient来代替FeignClient

**Comment by cxzucc** [comment]
> 你确定在202x版的scg有Feign调用的影子？官方明确给出答案，需要用WebClient来代替FeignClient

SCG的3.0.1版本的时候，我就是注入了FeignClient，然后通过CompleteFuture 方式去调用的

**Comment by HaojunRen** [comment]
WebFlux下再套个线程，线程里再实施FeignClient，过程是异步>异步>同步，这方案并不太好。建议你按照官方提供的WebClient去试一下，也很简单。scg下面的底层SpringBoot机制在不同版本并不一样，在某个版本没问题，并不代表在其他版本也一定是好的

**Comment by zhangliang198722** [comment]
> > > 不过还没搞明白为什么注入feign会导致WeightCalculatorWebFilter类locator.getRoutes().blockLast()这个地方卡在那不动了。
> > 
> > 
> > 我猜你和我偶一样子gateway 里调用了其它服务，这时候loadbalancer开始运行所以执行内容被挂起了，代码无法向下运行
> 
> 能给个demo复现问题吗

`
import io.netty.channel.ChannelOption;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cloud.client.loadbalancer.reactive.LoadBalancedExchangeFilterFunction;
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;
import reactor.netty.http.client.HttpClient;

import javax.annotation.PostConstruct;

@Service
public class LoadDemoInitService {

    Logger log = LoggerFactory.getLogger(LoadDemoInitService.class);

    private WebClient webClient;

    public LoadDemoInitService(LoadBalancedExchangeFilterFunction lbFunction) {
        HttpClient httpClient = HttpClient.create()
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 500);
        webClient = WebClient
            .builder()
            .clientConnector(new ReactorClientHttpConnector(httpClient))
            .filter(lbFunction)
            .baseUrl("http://gateway-admin")
            .build();
    }


    @PostConstruct
    public void init(){
        getVersion("firstGateWay")
            .doOnNext(n -> log.info("request is {}",n))
            .subscribe();
    }

    public Mono<Long> getVersion(String tag){
        return  webClient
            .get()
            .uri(uriBuilder ->
                uriBuilder
                    .path("/version/lastVersion")
                    .queryParam("tag",tag)
                    .build()
            )
            .retrieve()
            .bodyToMono(Long.class)
            .onErrorReturn(0L);
    }
}
`

您可以建立一个最基本的gateway项目 然后使用这个 service类， 配置了
`spring.cloud.gateway.predicate.weight.enabled=false`
日志可以正常输出，未配置的情况是会被阻塞的。
如果需要更多配置信息，可以随时联系我

**Comment by zhangliang198722** [comment]
> 你确定在202x版的scg有Feign调用的影子？官方明确给出答案，需要用WebClient来代替FeignClient

这个bug 在使用webClient的时候也会复现，我已经提供了demo代码

**Comment by HaojunRen** [comment]
可否把异常信息贴上来？

**Comment by zhangliang198722** [comment]
> 日志可以正常输出，未配置的情况是会被阻塞的。

非常你提供的配置，这个问题我已经找了好多天。 因为我的gateway业务有些多，一直怀疑是fegin的问题。但是没有找到根源，今天换用webclient 实现

> 可否把异常信息贴上来？

代码只是被阻塞，控制台不会有异常体现。您可以自己建一个基本的gateway的demo ，然后使用这个service的demo， 当然你还要有个nacos 和 一个demo的微服务。 这个问题是完全可以复现的
正式因为没有异常，这个问题我排查了好久。

您要关注
`.doOnNext(n -> log.info("request is {}",n))`
这一步是否执行到

**Comment by cxzucc** [comment]
> > 你确定在202x版的scg有Feign调用的影子？官方明确给出答案，需要用WebClient来代替FeignClient
> 
> 这个bug 在使用webClient的时候也会复现，我已经提供了demo代码

你使用WebClient的时候，是否有把pom里的spring-cloud-openfeign依赖去掉？没有的话，去掉再试试。

**Comment by HaojunRen** [comment]
LoadDemoInitService是放在scg里的一个类？如果是，我直觉这么写不太好，因为我的理解WebClient一般是放在scg的Filter(本身它是WebFlux的)里，你放在构造方法以及@PostConstruct里似乎有点怪。你这个问题，我看到好久了，我还不理解你的需求是什么？是否存在简单问题复杂化了？

**Comment by zhangliang198722** [comment]
> > > 你确定在202x版的scg有Feign调用的影子？官方明确给出答案，需要用WebClient来代替FeignClient
> > 
> > 
> > 这个bug 在使用webClient的时候也会复现，我已经提供了demo代码
> 
> 你使用WebClient的时候，是否有把pom里的spring-cloud-openfeign依赖去掉？没有的话，去掉再试试。

我重新确认类一下，排除openFegin 后问题依然复现

**Comment by zhangliang198722** [comment]
> LoadDemoInitService是放在scg里的一个类？如果是，我直觉这么写不太好，因为我的理解WebClient一般是放在scg的Filter(本身它是WebFlux的)里，你放在构造方法以及@PostConstruct里似乎有点怪。你这个问题，我看到好久了，我还不理解你的需求是什么？是否存在简单问题复杂化了？

我写的需求是在gateway启动的时候初始化动态bean的配置。具体要做什么不方便多透露，我们只关心现象即可
只要我配置了
`spring.cloud.gateway.predicate.weight.enabled=false`
就可以按照我的设想运行。

**Comment by zhangliang198722** [comment]
@HaojunRen H @cxzucc  感谢两位陪我讨论这么久，目前对与我来说已经找到了暂时解决问题的方案。 如果有其它需要github留言即可。 今晚我就提供信息到这里了，如果你们需要我其它的协助，我看到消息后会尽量第一时间提供线索的。

**Comment by HaojunRen** [comment]
我分析下来，个人觉得，你的问题涉及到的是Spring Cloud原生技术层面的问题，似乎没涉及到Spring Cloud Alibaba层面的东西。同时，WebFlux方面的东西尽量谨慎使用，不能姑且认为问题解决了，不吃透也许后续问题还是会出现。

**Comment by zengxianming01** [comment]
try to add  "spring-cloud-loadbalancer " in pom.xml

**Comment by cxzucc** [comment]
> try to add "spring-cloud-loadbalancer " in pom.xml

是因为启动的时候有死锁导致的。
初始化Bean的时候，主线程执行到DefaultSingletonBeanRegistry.getSingleton方法，会持有一个锁。
然后我项目里用了openfeign，在openfeign初始化的时候，会发布一个RefreshRoutesEvent事件，刚好被WeightCalculatorWebFilter捕获到了，执行了routeLocator.ifAvailable(locator -> locator.getRoutes().blockLast());这句代码，blockLast的时候，主线程就挂起了，锁没释放。
然后有其他线程执行到DefaultSingletonBeanRegistry.getSingleton方法的时候（比如上面的locator.getRoutes，实际是异步执行的，线程会调用到DefaultSingletonBeanRegistry.getSingleton方法）， 就死锁启不起来了。

**Comment by diyewu** [comment]
我也遇到了同样的问题，不过稍微有点不同。我的情况是这样的，在nacos没有注册服务之前启动gateway能正常注册的，也就是要保证gateway是第一个注册成功的服务。如果有其他服务已经注册，gateway就会卡在locator.getRoutes().blockLast()。暂时配置spring.cloud.gateway.predicate.weight.enabled=false解决。
springboot版本：2.6.11，spring-cloud版本：2021.0.4

**Comment by MrLiu2001** [comment]
> > try to add "spring-cloud-loadbalancer " in pom.xml
> 
> 是因为启动的时候有死锁导致的。 初始化Bean的时候，主线程执行到DefaultSingletonBeanRegistry.getSingleton方法，会持有一个锁。 然后我项目里用了openfeign，在openfeign初始化的时候，会发布一个RefreshRoutesEvent事件，刚好被WeightCalculatorWebFilter捕获到了，执行了routeLocator.ifAvailable(locator -> locator.getRoutes().blockLast());这句代码，blockLast的时候，主线程就挂起了，锁没释放。 然后有其他线程执行到DefaultSingletonBeanRegistry.getSingleton方法的时候（比如上面的locator.getRoutes，实际是异步执行的，线程会调用到DefaultSingletonBeanRegistry.getSingleton方法）， 就死锁启不起来了。
你好，我目前在使用动态路由时也遇到了这个问题，项目启动时会发布RefreshRoutesEvent事件时会导致无法死锁启动，请问你是如何解决的，谢谢

**Comment by fulizhe** [comment]
如果只是启动阻塞的问题，可以参考这种方案： https://docs.spring.io/spring-cloud-openfeign/docs/3.1.9/reference/html/#early-initialization-errors

**Comment by suzhelan** [comment]
我也于两年后遇到同样的问题(nacos+gateway+openfeign) 解决方法
1.配置spring.cloud.gateway.predicate.weight.enabled=false
2.保证网关是第一个启动的服务（用了方法一就不用这个 推荐方法一）
3.请求时出现 `block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-3` 不支持阻塞执行 我是这样解决的
先写个配置类
```java
@Configuration
public class HttpMsgConverConfig {

    @Bean
    @ConditionalOnMissingBean
    public HttpMessageConverters messageConverters(ObjectProvider<HttpMessageConverter<?>> converters) {
        return new HttpMessageConverters(converters.orderedStream().collect(Collectors.toList()));
    }
}
```
然后UserloginService是使用openfeign的类
```java
    @Autowired
    public  UserLoginService userLoginService;

    @RequestMapping("doLogin")
    public Object doLogin() throws ExecutionException, InterruptedException, TimeoutException {
        CompletableFuture<Object> completableFuture = CompletableFuture.supplyAsync(userLoginService::doLogin);
        return completableFuture.get(5, TimeUnit.SECONDS);

    }
```

通过CompletableFuture异步阻塞调用 好像帮openfeign配置连接池更换连接方式也能解决 我还没试

**Comment by roycefan** [comment]
今天遇到这个问题

     <spring-boot.version>2.4.6</spring-boot.version>
        <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
        <spring-cloud.version>2020.0.5</spring-cloud.version>

 
org.springframework.cloud.gateway.support.ConfigurationService

	@Override
		protected T doBind() {
			Bindable<T> bindable = Bindable.of(this.configurable.getConfigClass());
			T bound = bindOrCreate(bindable, this.normalizedProperties, this.configurable.shortcutFieldPrefix(),
					/* this.name, */this.service.validator.get(), this.service.conversionService.get());
			return bound;
		}

会卡在  this.service.validator.get(), this.service.conversionService.get() 上面，

换成
        <spring-boot.version>2.6.11</spring-boot.version>
        <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
        <spring-cloud.version>2021.0.4</spring-cloud.version>
配置 spring.cloud.gateway.predicate.weight.enabled=false 虽然没报错，但是我的filter 又有问题了，还在看。
