### ISSUE TITLE
2021.0 stream-rocketmq document invalid

### ISSUE THREAD

**Issue by zhangliang198722** [alibaba/spring-cloud-alibaba#2479]
您好，我子最近尝试升级到 spring cloud alibaba 2021.0 版本时遇到了困难，经过我几天的时间才发现，2021.0 升级内容非常丰富，因此就的使用文档已经不能够指导我开发了。 
例如：
`spring.cloud.stream.rocketmq.bindings.input.consumer.broadcasting=true`
需要替换为
`spring.cloud.stream.rocketmq.bindings.input.consumer.messageModel=BROADCASTING`

这样的变更破坏性非常大，如果我仅通过文档获取信息那我的服务将会出现极严重的错误希望你们能够尽快更新文档，不要让更多开发者处理这些不必要的问题

We encourage the use of English. If you can't use it directly, you can use translation software, and you can still keep the original Chinese text.

Hello, my son recently encountered difficulties when trying to upgrade to spring cloud Alibaba 2021.0. After a few days, I found that the 2021.0 upgrade content is very rich, so the user documentation can no longer guide me to develop.

For example:

`spring. cloud. stream. rocketmq. bindings. input. consumer. broadcasting=true`

Need to replace with

`spring. cloud. stream. rocketmq. bindings. input. consumer. messageModel=BROADCASTING`

Such changes are very destructive. If I only obtain information through documents, there will be very serious errors in my service. I hope you can update the documents as soon as possible and don't let more developers deal with these unnecessary problems

**Comment by steverao** [comment]
We got it and welcome to finish it together! see #2481

**Comment by steverao** [comment]
We updated it now.
