### ISSUE TITLE
[RocketMQ] Add some examples about new features

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2481]
1.Add some examples about new features in RocketMQ.
2.Add relevant using documents.

**Comment by Sorieee** [comment]
Which version's new feature?

**Comment by Sorieee** [comment]
I want to have a try, but I want to know Which version new features do you mean. 2021.0?

**Comment by steverao** [comment]
> I want to have a try, but I want to know Which version new features do you mean. 2021.0?

RocketMQ 4.9.2

**Comment by Sorieee** [comment]
> > I want to have a try, but I want to know Which version new features do you mean. 2021.0?
> 
> RocketMQ 4.9.2

Oook, I will learn RocketMQ 4.9.2, and finish this issue on April 10th(maybe).

**Comment by Sorieee** [comment]
Only 1 feature[RIP-7](https://github.com/apache/rocketmq/wiki/RIP-7-Multiple-Directories-Storage-Support)
refer to 
https://rocketmq.apache.org/release_notes/release-notes-4.7.0/
https://rocketmq.apache.org/release_notes/release-notes-4.7.1/
https://rocketmq.apache.org/release_notes/release-notes-4.8.0/
https://rocketmq.apache.org/release_notes/release-notes-4.9.0/
https://rocketmq.apache.org/release_notes/release-notes-4.9.1/
https://rocketmq.apache.org/release_notes/release-notes-4.9.2/

**Comment by Sorieee** [comment]
- [x] Broadcasting
- [x] Order
- [x] Delay
- [x] Sql filter

Todo:
- [x] Transaction

Don't know how to do:
- [ ] Batch (May be impossible)
Will improve docs after coding jobs finisihed.
