### ISSUE TITLE
[Sidecar] Add example document of sidecar module

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2485]
Add example document of sidecar module in https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples

**Comment by cevencheng** [comment]
We already use sidecar in production, so if i want to write a document which branch to commit.

**Comment by sollhui** [comment]
Welcome to contribute, you can commit to 2021.x firstly.
