### ISSUE TITLE
nacos刷新配置后线程数高速增加最终导致oom

### ISSUE THREAD

**Issue by jackli0909** [alibaba/spring-cloud-alibaba#2488]
![image](https://user-images.githubusercontent.com/86995835/160312429-6c4a29bf-18a2-4d9b-84af-140558510337.png)
 
spring cloud alibaba 2.2.7版本，服务启动后，修改nacos中的配置信息，线程数高速增长，能达到3K，最终oom。

**Comment by yuhuangbin** [comment]
请说明使用方式、Nacos Client & Nacos Server 版本，最好可以提供一个能够复现的demo，此issue没暴露足够多的信息，将被关闭
