### ISSUE TITLE
Nacos Discovery couldn't deregister a permanent instance when application shutdown gracefully

### ISSUE THREAD

**Issue by Troy-2015** [alibaba/spring-cloud-alibaba#2489]
**Which Component**
Nacos Discovery

**Describe the bug**
When I run my application and register my service instance with the config `spring.cloud.nacos.discovery.ephemeral=false`, by which indicates that it's a permanent service. But when I shutdown the application gracefully, the console shows that it deregisters the instance:
2022-03-28 14:22:04.197  INFO 19248 --- [ionShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registering from Nacos Server now...
2022-03-28 14:22:04.216  INFO 19248 --- [ionShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registration finished.

Yet it turns out **doesn't deregister the instance**.

I've checked the deregister code:
```
com.alibaba.cloud.nacos.registry.NacosServiceRegistry#deregister(Registration registration)
	@Override
	public void deregister(Registration registration) {

		...

		NamingService namingService = namingService();
		String serviceId = registration.getServiceId();
		String group = nacosDiscoveryProperties.getGroup();

		try {
			namingService.deregisterInstance(serviceId, group, registration.getHost(),
					registration.getPort(), nacosDiscoveryProperties.getClusterName());
		}
		catch (Exception e) {
			...
		}

		...
	}
```
```
com.alibaba.nacos.client.naming.NacosNamingService#deregisterInstance(String serviceName, String groupName, String ip, int port, String clusterName)
    @Override
    public void deregisterInstance(String serviceName, String groupName, String ip, int port, String clusterName)
            throws NacosException {
        Instance instance = new Instance();
        instance.setIp(ip);
        instance.setPort(port);
        instance.setClusterName(clusterName);
        
        deregisterInstance(serviceName, groupName, instance);
    }
```
and the `ephemeral` field in `com.alibaba.nacos.api.naming.pojo.Instance` defaults as `true`, which causes the bug.

**Comment by yuhuangbin** [comment]
Please provide relevant version information.

**Comment by yuhuangbin** [comment]
`spring.cloud.nacos.discovery.ephemeral=true` not a persistent instance. Instead, it represents a temporary instance.

**Comment by Troy-2015** [comment]
> `spring.cloud.nacos.discovery.ephemeral=true` not a persistent instance. Instead, it represents a temporary instance.

typo, sry, corrected already

**Comment by Troy-2015** [comment]
> Please provide relevant version information.

<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
	<version>2021.0.1.0</version>
</dependency>
