### ISSUE TITLE
Spring cloud Alibaba and swagger compatibility

### ISSUE THREAD

**Issue by l42111996** [alibaba/spring-cloud-alibaba#2496]
version：
   <spring.cloud.alibaba.version>2021.0.1.0</spring.cloud.alibaba.version>
    <spring.cloud.version>2021.0.1</spring.cloud.version>
    <springboot.version>2.6.3</springboot.version>
 <swagger.version>2.9.2</swagger.version>

The Nacos service discovery and configuration center is used, but it cannot be started and an abnormal error occurs

2022-04-01 11:16:37.289 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext [AbstractApplicationContext.java:591] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException

Thank you. What may be the problem?

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by HaojunRen** [comment]
Spring Boot 2.6.x NOT compatible with Swagger

**Comment by HaojunRen** [comment]
Here a solution maybe do a help for you


    @Bean
    public static BeanPostProcessor springfoxHandlerProviderBeanPostProcessor() {
        return new BeanPostProcessor() {
            @Override
            public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
                if (bean instanceof WebMvcRequestHandlerProvider /*|| bean instanceof WebFluxRequestHandlerProvider*/) {
                    customizeSpringfoxHandlerMappings(getHandlerMappings(bean));
                }

                return bean;
            }

            private <T extends RequestMappingInfoHandlerMapping> void customizeSpringfoxHandlerMappings(List<T> mappings) {
                List<T> copy = mappings.stream()
                        .filter(mapping -> mapping.getPatternParser() == null)
                        .collect(Collectors.toList());
                mappings.clear();
                mappings.addAll(copy);
            }

            @SuppressWarnings("unchecked")
            private List<RequestMappingInfoHandlerMapping> getHandlerMappings(Object bean) {
                try {
                    Field field = ReflectionUtils.findField(bean.getClass(), "handlerMappings");
                    field.setAccessible(true);

                    return (List<RequestMappingInfoHandlerMapping>) field.get(bean);
                } catch (IllegalArgumentException | IllegalAccessException e) {
                    throw new IllegalStateException(e);
                }
            }
        };
    }


If you use WebFlux，recovery


bean instanceof WebFluxRequestHandlerProvider


then add a config

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

**Comment by l42111996** [comment]
> Here a solution maybe do a help for you
> 
> ```
> @Bean
> public static BeanPostProcessor springfoxHandlerProviderBeanPostProcessor() {
>     return new BeanPostProcessor() {
>         @Override
>         public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
>             if (bean instanceof WebMvcRequestHandlerProvider /*|| bean instanceof WebFluxRequestHandlerProvider*/) {
>                 customizeSpringfoxHandlerMappings(getHandlerMappings(bean));
>             }
> 
>             return bean;
>         }
> 
>         private <T extends RequestMappingInfoHandlerMapping> void customizeSpringfoxHandlerMappings(List<T> mappings) {
>             List<T> copy = mappings.stream()
>                     .filter(mapping -> mapping.getPatternParser() == null)
>                     .collect(Collectors.toList());
>             mappings.clear();
>             mappings.addAll(copy);
>         }
> 
>         @SuppressWarnings("unchecked")
>         private List<RequestMappingInfoHandlerMapping> getHandlerMappings(Object bean) {
>             try {
>                 Field field = ReflectionUtils.findField(bean.getClass(), "handlerMappings");
>                 field.setAccessible(true);
> 
>                 return (List<RequestMappingInfoHandlerMapping>) field.get(bean);
>             } catch (IllegalArgumentException | IllegalAccessException e) {
>                 throw new IllegalStateException(e);
>             }
>         }
>     };
> }
> ```
> 
> If you use WebFlux，recovery
> 
> bean instanceof WebFluxRequestHandlerProvider
> 
> then add a config
> 
> spring.mvc.pathmatch.matching-strategy=ant-path-matcher

it works,Thanks
