### ISSUE TITLE
How to configure spring.cloud.nacos.discovery properties to allow http health check?

### ISSUE THREAD

**Issue by chenweiyj** [alibaba/spring-cloud-alibaba#2497]
In using nacos service discovery, when I need http health check, is it a must that we could only configure it on the web ui manually? How could we configure the http health check path in spring.cloud.nacos.discovery properties or any approaches else in spring cloud program?

**Comment by HaojunRen** [comment]
Http Health Check of Nacos Service discovery? Do you mean to 'Heart Beat'?

**Comment by steverao** [comment]
No reply for a long time, close first

**Comment by zdpbj2014** [comment]
> Http Health Check of Nacos Service discovery? Do you mean to 'Heart Beat'?

Due to encountering OOM and normal heartbeat, the service is still being registered. I would like to add HTTP method to detect the health status of the instance。But I couldn't find the configuration item. Do you have any plans to add new ones in the future
