### ISSUE TITLE
Nacos service connection refused behind spring cloud gateway under high concurrency scenario 

### ISSUE THREAD

**Issue by chenweiyj** [alibaba/spring-cloud-alibaba#2499]
I have two micro services registered in the nacos, namely serviceA and gateway, where gateway use spring cloud gateway. The gateway uses spring cloud load balancer to access serviceA, eg. lb://serviceA. When serviceA is under high concurrency, it will return connection refused when it is republished through k8s. So how can we fix it?

我在nacos服务前挂了一个spring cloud gateway，gateway也是注册到nacos，通过spring cloud loadbalancer访问其他服务，假设网关后的服务为serviceA, serviceA的并发量很高，在serviceA通过k8s重新发布的那几秒里，gateway无法访问到serviceA，报connection refused, 然后过了十来秒又好了，但是外部请求丢了很多

**Comment by steverao** [comment]
This is a problem that the Spring Cloud framework itself has always existed in the application offline and the related problems can only be solved by the cloud products of cloud manufacturers now.

**Comment by HaojunRen** [comment]
这个问题一般通过服务治理（灰度发布）层面来解决，可以通过“预热”措施 - 当一辆汽车发动到开足马力，需要一段时间给发动机预热。文中提到的问题，在网关后某个实例刚启动后，给它10-20秒时间预热，流量不要一下子打到新启动的服务实例上

顺便说一句，这个“问题”不仅仅在Nacos上，在Consul，Eureka，Zookeeper上都存在，尤其在Eureka上最严重

**Comment by steverao** [comment]
> 这个问题一般通过服务治理（灰度发布）层面来解决，可以通过“预热”措施 - 当一辆汽车发动到开足马力，需要一段时间给发动机预热。文中提到的问题，在网关后某个实例刚启动后，给它10-20秒时间预热，流量不要一下子打到新启动的服务实例上
> 
> 顺便说一句，这个“问题”不仅仅在Nacos上，在Consul，Eureka，Zookeeper上都存在，尤其在Eureka上最严重

嗯嗯，是Spring Cloud框架本身没有实现无损下线问题导致的，客户端无法实时感受到提供端的下线状态，出现调用已下线实例从而出现connection refused，Eureka客户端因为有几级缓存客户端感知服务端状态比较慢所以特别严重

**Comment by lay-g** [comment]
这个我目前的解决方案是重写了 Spring 的 DefaultLifecycleProcessor#onClose()，在原本的 onClose 前加入了执行自己的关闭执行器（自定接口，可自己实现自定的关闭逻辑，比如：关闭 Web 容器前在注册中心下线应用、应对节点信息缓存的延迟关闭等逻辑），这样可以做到一个简单的无损下线。当然，也可以做一个通知功能，主动通知所有自己的 consumer 剔除自己。
