### ISSUE TITLE
你对Spring Cloud Alibaba有什么期待？

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2500]
### What do you expect from Spring Cloud Alibaba
The Spring Cloud Alibaba community is making plans for 2022. You are welcome to leave a message to us about your thoughts.

### 你对Spring Cloud Alibaba有什么期待？
Spring Cloud Alibaba社区正在做2022年度规划，欢迎大家将自己的相关想法留言告诉我们：）

**Comment by steverao** [comment]
比如说大家对Spring Cloud Function这块有在生产场景使用过的吗？对社区后续做一些相关尝试有什么建议的吗？

**Comment by abelzhyb** [comment]
期待就是文档写得认真点，过期的文档及时更改，不同的版本不同的文档内容，不然照着文档各种排错

**Comment by steverao** [comment]
> 期待就是文档写得认真点，过期的文档及时更改，不同的版本不同的文档内容，不然照着文档各种排错

具体哪里有问题可以指出来，也可以通过issues或者提交PR一起修改，这块因为社区维护同学一直都是在动态变化的，所以可能确实有你说的问题而当前主要维护的同学并没有发现，开源项目本来也是依赖社区内外同学一起建设的，单纯依靠个人或者一小部分人也很难建设好，希望理解~

**Comment by jaimyjie** [comment]
更新及时

**Comment by steverao** [comment]
> 更新及时

收到，我们当前会尽量保持2~3个月更新一个新版本的频率进行社区维护，也欢迎有兴趣的同学一起参与到社区共建中来：）

**Comment by dengyumin** [comment]
Spring Cloud Dubbo 组件移除是一大遗憾。期待接下来其他的组件能够好好维护：使用的稳定，文档的详尽说明等。别再中途放弃了。将来有能力了我也会尽力贡献自己一份力量，共同参与建设。

**Comment by steverao** [comment]
> Spring Cloud Dubbo 组件移除是一大遗憾。期待接下来其他的组件能够好好维护：使用的稳定，文档的详尽说明等。别再中途放弃了。将来有能力了我也会尽力贡献自己一份力量，共同参与建设。

收到，其实spring cloud dubbo移除也是经过了慎重的讨论的，觉得不太适合放到社区来继续维护。另外欢迎参与进来，可以从issues里面的welcome-contribution标签的issues选一些简单的开始加入到社区中来:）

**Comment by DearYangs** [comment]
Spring Cloud Nacos为啥不提供和Spring Nacos的一样的功能，好多注解没法使用，比如：@NacosConfigListener、@NacosConfigurationProperties...

**Comment by HeyChiang** [comment]
> > 期待就是文档写得认真点，过期的文档及时更改，不同的版本不同的文档内容，不然照着文档各种排错
> 
> 具体哪里有问题可以指出来，也可以通过issues或者提交PR一起修改，这块因为社区维护同学一直都是在动态变化的，所以可能确实有你说的问题而当前主要维护的同学并没有发现，开源项目本来也是依赖社区内外同学一起建设的，单纯依靠个人或者一小部分人也很难建设好，希望理解~

期望完善框架融合的相关文档吧，比如Nacos+Sentinel+gateway这种的，虽然gateway不属于alibaba，但是有这样的文档更有利于框架推广。

文档需要按照版本去区分，这个可以参考ElasticSearch的文档规范，有修复版可以在官方文档及时提现，例如：[这个bug](https://github.com/alibaba/spring-cloud-alibaba/issues/2310)不来github查是不知道发生了什么事情的。

**Comment by steverao** [comment]
> 

你说的这两个注解都是Nacos原生提供的，Spring Cloud应用中你应该是可以正常使用的。

**Comment by steverao** [comment]
> Spring Cloud Nacos为啥不提供和Spring Nacos的一样的功能，好多注解没法使用，比如：@NacosConfigListener、@NacosConfigurationProperties...

你说的这两个注解都是Nacos原生提供的，Spring Cloud应用中你应该是可以正常使用的。

**Comment by steverao** [comment]
> > > 期待就是文档写得认真点，过期的文档及时更改，不同的版本不同的文档内容，不然照着文档各种排错
> > 
> > 
> > 具体哪里有问题可以指出来，也可以通过issues或者提交PR一起修改，这块因为社区维护同学一直都是在动态变化的，所以可能确实有你说的问题而当前主要维护的同学并没有发现，开源项目本来也是依赖社区内外同学一起建设的，单纯依靠个人或者一小部分人也很难建设好，希望理解~
> 
> 期望完善框架融合的相关文档吧，比如Nacos+Sentinel+gateway这种的，虽然gateway不属于alibaba，但是有这样的文档更有利于框架推广。
> 
> 文档需要按照版本去区分，这个可以参考ElasticSearch的文档规范，有修复版可以在官方文档及时提现，例如：[这个bug](https://github.com/alibaba/spring-cloud-alibaba/issues/2310)不来github查是不知道发生了什么事情的。

很同意你的第一条建议，其实我们也计划做一套Spring Cloud Alibaba在云原生微服务领域应用的实践案例，这块有兴趣欢迎一起参与进来哈~

**Comment by DearYangs** [comment]
> > Spring Cloud Nacos 啥不提供和 Spring Nacos 的一样的功能，很多为注解无法使用，比如：@NacosConfigListener、@NacosConfigurationProperties...
> 
> 你说的这两个注解都是 Nacos 提供的，春云应用中你应该是可以正常使用的。

版本：
```
api(platform("org.springframework.cloud:spring-cloud-dependencies:2021.0.1"))
api(platform("org.springframework.boot:spring-boot-dependencies:2.6.3"))
api(platform("com.alibaba.cloud:spring-cloud-alibaba-dependencies:2021.0.1.0"))


implementation("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery")
implementation("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config")
```

代码：
```
@Configuration
public class NacosDynamicRouteService {

    @NacosConfigListener(dataId = "gate.yml", groupId = "GATEWAY")
    public void routeConfig(String configInfo) {
        System.out.println(configInfo);
    }

}
```
问题：修改配置，无法进入监听方法内部

**Comment by misselvexu** [comment]
#### There are the following points.
- Hope the official of `Spring Cloud Alibaba Framework` can provide a full scenario based on the full component samples .
- Whether to provide a complete middleware runtime environment based on Docker .
- Whether we can provide a test package similar to TCK (Technology Compatibility Kit).

**Comment by SkyWalkerKKKK** [comment]
> Spring Cloud Nacos为啥不提供和Spring Nacos的一样的功能，好多注解没法使用，比如：@NacosConfigListener、@NacosConfigurationProperties...

我也遇到了这个问题，我只验证了`@NacosConfigurationProperties`在`Spring Cloud Nacos`中无法使用，与Spring Boot集成是可以使用的。
与Spring Boot集成的依赖：
```xml
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.10</version>
</dependency>
```

---

基于`Frameless-Nacos`，我们可以进行进行定制化的更新配置项；

基于`Spring-Nacos`，我们可以将配置项与Spring容器结合起来；

而`Spring Boot Nacos`或者是`Spring Cloud Nacos`，则是由`AutoConfiguration`帮助我们将代码转为了配置项。

我在这个集成框架递进的时候，发现`Spring Cloud Nacos`的`extension-configs`配置中，移除了`namespace`的配置选项（`Spring Boot Nacos`中具有此配置项）。

官网关于`namespace`的定义我也有看，但在生产实践中，如果有很多条产品线，每个产品线使用一个命名空间，多条产品线都有一些共用的配置，这种情况下，我需要在一个项目中，访问不同命名空间的配置，在`Spring Cloud Nacos`中就不是那么的方便了，不知后续对此的设计方向是什么样子的，是否会还原`namespace`配置项？

**Comment by SkyWalkerKKKK** [comment]
> Spring Cloud Nacos为啥不提供和Spring Nacos的一样的功能，好多注解没法使用，比如：@NacosConfigListener、@NacosConfigurationProperties...

我也遇到了这个问题，我只验证了`@NacosConfigurationProperties`在`Spring Cloud Nacos`中无法使用，与Spring Boot集成是可以使用的。
与Spring Boot集成的依赖：
```xml
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.10</version>
</dependency>
```

---

基于`Frameless-Nacos`，我们可以进行定制化的更新配置项；
基于`Spring-Nacos`，我们可以将配置项与Spring容器结合起来；
而`Spring Boot Nacos`或者是`Spring Cloud Nacos`，则是由`AutoConfiguration`帮助我们将代码转为了配置项。

我在这个集成框架递进的时候，发现`Spring Cloud Nacos`的`extension-configs`配置中，移除了`namespace`的配置选项（`Spring Boot Nacos`中具有此配置项）。

官网关于`namespace`的定义我也有看，但在生产实践中，如果有很多条产品线，每个产品线使用一个命名空间，多条产品线都有一些共用的配置，这种情况下，我需要在一个项目中，访问不同命名空间的配置，在`Spring Cloud Nacos`中就不是那么的方便了，不知后续对此的设计方向是什么样子的，是否会还原`namespace`配置项？

**Comment by lazeyliu** [comment]
有个正经的  版本对照表 cloud alibaba ~ spring cloud ~ springboot

**Comment by lazeyliu** [comment]
> 

找个版本对应关系 全世界找,csdn有的已经过时,跟破案似的猜解

**Comment by SkyWalkerKKKK** [comment]
> 

有的，https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by SkyWalkerKKKK** [comment]
> 有个正经的 版本对照表 cloud alibaba ~ spring cloud ~ springboot

有的，https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by lazeyliu** [comment]
> > 
> 
> 有的，https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

多谢,这个连接我收藏了,就是不太显眼,有点难找

**Comment by lazeyliu** [comment]
上面有版本对照没找到也是我翻阅文档不够勤奋,但如spring cloud 这样标注 看着会更好,有个大前提
![springcloud0](https://user-images.githubusercontent.com/5097837/167532398-4dd40a12-4012-4e5a-bfcf-4f2499db3224.png)
![springcloud1](https://user-images.githubusercontent.com/5097837/167532410-f6507a4f-131b-4ec8-b897-033b344b3e41.png)

**Comment by senluowx** [comment]
期待spring-native稳定了以后能支持spring-native

**Comment by steverao** [comment]
> 期待spring-native稳定了以后能支持spring-native

收到，有兴趣也可以一起来探索和参与这块内容建设：）

**Comment by JavaLionLi** [comment]
期待可以加快对组件新版本的兼容

**Comment by liqi19950722** [comment]
> > > Spring Cloud Nacos 啥不提供和 Spring Nacos 的一样的功能，很多为注解无法使用，比如：@NacosConfigListener、@NacosConfigurationProperties...
> > 
> > 
> > 你说的这两个注解都是 Nacos 提供的，春云应用中你应该是可以正常使用的。
> 
> 版本：
> 
> ```
> api(platform("org.springframework.cloud:spring-cloud-dependencies:2021.0.1"))
> api(platform("org.springframework.boot:spring-boot-dependencies:2.6.3"))
> api(platform("com.alibaba.cloud:spring-cloud-alibaba-dependencies:2021.0.1.0"))
> 
> 
> implementation("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery")
> implementation("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config")
> ```
> 
> 代码：
> 
> ```
> @Configuration
> public class NacosDynamicRouteService {
> 
>     @NacosConfigListener(dataId = "gate.yml", groupId = "GATEWAY")
>     public void routeConfig(String configInfo) {
>         System.out.println(configInfo);
>     }
> 
> }
> ```
> 
> 问题：修改配置，无法进入监听方法内部

不生效是因为处理类没有引入
处理类在这儿
[nacos-spring-project](https://github.com/nacos-group/nacos-spring-project)
```
<dependency>
  <groupId>com.alibaba.nacos</groupId>
  <artifactId>nacos-spring-context</artifactId>
  <version>1.1.1</version>
</dependency>
```

**Comment by tnessn** [comment]
把sentinel做好一点 ，现在就跟鸡肋一样，还不支持持久化

**Comment by cnlinjie** [comment]
有点不明白，2021.1 的版本，能够用更高的springboot版本，但alibaba组件能用的版本，反而更低；
比如：
2021.0.1.0 版本，能用 SrpingBoot 2.6.3 版本，但只能用 Nacos 1.4.2版本。
而 
2.2.8.RELEASE 版本的 ，只能用 Spring Boot 2.3.12.RELEASE 版本，但却可以用 Nacos 2.1.0 版本。

给我整糊涂了。。

<img width="727" alt="image" src="https://user-images.githubusercontent.com/3601638/176857586-e682f83c-563c-4350-b8dc-f3f3558c0390.png">

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/3601638/176857671-4d7e4501-adb0-4b08-8d54-7bcabfd5a456.png">

**Comment by cnlinjie** [comment]
> 把sentinel做好一点 ，现在就跟鸡肋一样，还不支持持久化

这个可以自己实现，很简单的。。

**Comment by quicksandznzn** [comment]
> * scenario

等个回答 ~ 我也遇到这个问题

**Comment by tnessn** [comment]
> > 把sentinel做好一点 ，现在就跟鸡肋一样，还不支持持久化
> 
> 这个可以自己实现，很简单的。。

我知道简单 简单为什么就不能给完善下呢

**Comment by 201206030** [comment]
2022.x 版本有计划吗？

**Comment by steverao** [comment]
> 2022.x 版本有计划吗？

Got it, we will discuss it later.

**Comment by 1027nuan** [comment]
根据这个文档，https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by 1027nuan** [comment]
根据这个文档 https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E 
 Spring cloud已经升级到2021.0.3，对应的Spring Cloud Alibaba版本应该是2021.0.3，但是目前没有这个版本，那实际上兼容的版本是？是2021.0.1.0吗？

**Comment by steverao** [comment]
> 把sentinel做好一点 ，现在就跟鸡肋一样，还不支持持久化

Sentinel是支持支持就化的，你可以更清楚的说明一下你的诉求吗？我们理解之后才好评估，另外哪块觉得有问题也可以提PR去帮助完善！

**Comment by steverao** [comment]
> 根据这个文档 https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E Spring cloud已经升级到2021.0.3，对应的Spring Cloud Alibaba版本应该是2021.0.3，但是目前没有这个版本，那实际上兼容的版本是？是2021.0.1.0吗？

暂时没有出对应的适配版本，我们这边并不是Spring Cloud的每个版本都进行适配的，我们主要是适配一些比较典型的，有代表性的版本。

**Comment by 342963711** [comment]
中国语言博大精深，分两个版本，2.x 一个是2.4之前（后面我觉得可以停掉，因为版本是一直更新的，保证新版本可以快速使用就OK）。2021.x 是支持2.4之后版本的，2021.0.0.x 是 最新的，已经到了2.6。 我说的OK 吧

**Comment by 342963711** [comment]
使用经验总结，和期待
1. 在使用版本上的问题,  真的是全靠猜，文档开始只是告诉依赖spring-cloud-dependencies。 之后基本全篇没有版本对照
2. dubbo 已经从cloud中生态中移除，我没明白为啥还要添加dubbo的依赖。(看错了，老版本存在，2021.x新版本确实没有了)
期待：
1. https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E  版本对照表 可以规划下放到更加合理的地方。
2. 明星产品希望文档说明更加通过copy文档可以快速接入。大家评论大部分都觉得文档不够，版本文档+明星产品

**Comment by steverao** [comment]
> 中国语言博大精深，分两个版本，2.x 一个是2.4之前（后面我觉得可以停掉，因为版本是一直更新的，保证新版本可以快速使用就OK）。2021.x 是支持2.4之后版本的，2021.0.0.x 是 最新的，已经到了2.6。 我说的OK 吧

企业用户主要还是使用的Spring Boot 2.4以下的版本，这块覆盖了大量用户，在未来一段时间还是需要维护的。

**Comment by steverao** [comment]
> 3\. https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

收到

**Comment by icodening** [comment]
服务路由能力欠缺，希望未来有服务路由的能力

**Comment by sollhui** [comment]
> 服务路由能力欠缺，希望未来有服务路由的能力

we plan to do it recently,you can read issue https://github.com/alibaba/spring-cloud-alibaba/issues/2700

**Comment by xllove-moon** [comment]
> > 根据这个文档 https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E Spring cloud已经升级到2021.0.3，对应的Spring Cloud Alibaba版本应该是2021.0.3，但是目前没有这个版本，那实际上兼容的版本是？是2021.0.1.0吗？
> 
> 暂时没有出对应的适配版本，我们这边并不是Spring Cloud的每个版本都进行适配的，我们主要是适配一些比较典型的，有代表性的版本。

2.4后下一个典型的有代表性的版本是哪个系列呢,或者说SCA会持续支持的主要版本,我们新服务做版本选择的时候也好有个参考,最好和SCA的规划方向一致

**Comment by Cilong** [comment]
请问SCA2021.0.1.x版本 支持nacos2.10 和ipv6具体发布版本日期？

**Comment by Cilong** [comment]
请问SCA2021.x版本 具体什么时候支持nacos2.10 和ipv6

**Comment by spidersq** [comment]
> 

是的，感觉有点乱套，好久了也没更新版本，跟不上springboot，springcloud的发布。

**Comment by spidersq** [comment]
> 

是的，感觉有点乱套，好久了也没更新版本，跟不上springboot，springcloud的发布

**Comment by JHB-Client** [comment]
啥也不说,赶紧把版本文档认真搞好,不要有腾讯那样的臭毛病!

**Comment by JHB-Client** [comment]
1.4.2的nacos,搭配这个
<img width="812" alt="image" src="https://user-images.githubusercontent.com/15072068/189064175-cc421505-1a91-426e-9ec9-3505d5ad7feb.png">
然后,client注册不到.
报错:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/15072068/189064380-e1f791ff-1928-4f5a-ae00-aa8c52005ecf.png">
代码:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/15072068/189064681-f7a96cc6-ca25-4a5f-8776-67bf97eba73a.png">
结果:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/15072068/189064797-a0f5a599-1310-44ed-a0e7-c35cb6bf7940.png">

**Comment by cevencheng** [comment]
> 1.4.2的nacos,搭配这个 <img alt="image" width="812" src="https://user-images.githubusercontent.com/15072068/189064175-cc421505-1a91-426e-9ec9-3505d5ad7feb.png"> 然后,client注册不到. 报错: <img alt="image" width="1141" src="https://user-images.githubusercontent.com/15072068/189064380-e1f791ff-1928-4f5a-ae00-aa8c52005ecf.png"> 代码: <img alt="image" width="577" src="https://user-images.githubusercontent.com/15072068/189064681-f7a96cc6-ca25-4a5f-8776-67bf97eba73a.png"> 结果: <img alt="image" width="1091" src="https://user-images.githubusercontent.com/15072068/189064797-a0f5a599-1310-44ed-a0e7-c35cb6bf7940.png">

client 的版本和server端的不兼容，你可以跑个 2.x 版本的 nacos server 试下。

**Comment by sollhui** [comment]
> 1.4.2的nacos,搭配这个 <img alt="image" width="812" src="https://user-images.githubusercontent.com/15072068/189064175-cc421505-1a91-426e-9ec9-3505d5ad7feb.png"> 然后,client注册不到. 报错: <img alt="image" width="1141" src="https://user-images.githubusercontent.com/15072068/189064380-e1f791ff-1928-4f5a-ae00-aa8c52005ecf.png"> 代码: <img alt="image" width="577" src="https://user-images.githubusercontent.com/15072068/189064681-f7a96cc6-ca25-4a5f-8776-67bf97eba73a.png"> 结果: <img alt="image" width="1091" src="https://user-images.githubusercontent.com/15072068/189064797-a0f5a599-1310-44ed-a0e7-c35cb6bf7940.png">

可以参考社区的版本文档进行搭配： https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by herodotus-ecosystem** [comment]
有两点期待：
1. Nacos 支持 Postgresql
2. Spring Cloud Alibaba 开始着手适配 Spring Boot 3.X （还有两个多月 Spring Boot 3 就发布了）

**Comment by steverao** [comment]
> 有两点期待：
> 
> 1. Nacos 支持 Postgresql
> 2. Spring Cloud Alibaba 开始着手适配 Spring Boot 3.X （还有两个多月 Spring Boot 3 就发布了）

I got it, but Nacos supports Postgresql that you need to create a issue and discuss with Nacos community.

**Comment by ovenfrank** [comment]
官方就不能加入持久化吗，为什么要用户自己去实现

**Comment by zhaoyunxing92** [comment]
> 有点不明白，2021.1 的版本，能够用更高的springboot版本，但alibaba组件能用的版本，反而更低； 比如： 2021.0.1.0 版本，能用 SrpingBoot 2.6.3 版本，但只能用 Nacos 1.4.2版本。 而 2.2.8.RELEASE 版本的 ，只能用 Spring Boot 2.3.12.RELEASE 版本，但却可以用 Nacos 2.1.0 版本。
> 
> 给我整糊涂了。。
> 
> <img alt="image" width="727" src="https://user-images.githubusercontent.com/3601638/176857586-e682f83c-563c-4350-b8dc-f3f3558c0390.png">
> 
> <img alt="image" width="1083" src="https://user-images.githubusercontent.com/3601638/176857671-4d7e4501-adb0-4b08-8d54-7bcabfd5a456.png">

我也看不懂现在的版本，使用低版本的nacos提示有安全漏洞，要用高版本的nacos只能降低sca的版本

**Comment by steverao** [comment]
> > 有点不明白，2021.1 的版本，能够用更高的springboot版本，但alibaba组件能用的版本，反而更低； 比如： 2021.0.1.0 版本，能用 SrpingBoot 2.6.3 版本，但只能用 Nacos 1.4.2版本。 而 2.2.8.RELEASE 版本的 ，只能用 Spring Boot 2.3.12.RELEASE 版本，但却可以用 Nacos 2.1.0 版本。
> > 给我整糊涂了。。
> > <img alt="image" width="727" src="https://user-images.githubusercontent.com/3601638/176857586-e682f83c-563c-4350-b8dc-f3f3558c0390.png">
> > <img alt="image" width="1083" src="https://user-images.githubusercontent.com/3601638/176857671-4d7e4501-adb0-4b08-8d54-7bcabfd5a456.png">
> 
> 我也看不懂现在的版本，使用低版本的nacos提示有安全漏洞，要用高版本的nacos只能降低sca的版本

2021.0.1.0和2.2.8.RELEASE之间没有高低之分，它们是两个分支分别发布的版本。另外，2021.1其实相对2021.0.1.0先发布，这里有一些历史原因，对版本号进行了调整。

**Comment by bestwxc** [comment]
> > Spring Cloud Dubbo 组件移除是一大遗憾。期待接下来其他的组件能够好好维护：使用的稳定，文档的详尽说明等。别再中途放弃了。将来有能力了我也会尽力贡献自己一份力量，共同参与建设。
> 
> 收到，其实spring cloud dubbo移除也是经过了慎重的讨论的，觉得不太适合放到社区来继续维护。另外欢迎参与进来，可以从issues里面的welcome-contribution标签的issues选一些简单的开始加入到社区中来:）


由于某些原因， 我们团队用在spring cloud 里面混用了dubbo. 属于那一小部分了吧。 

今天在升级的时候， 才知道最新的版本已经移除了对dubbo的直接依赖了。找来找去发现， 除了关于去留的讨论issue， 未找到明显的其他材料， 就连release中， 也没有找到相关的说明。 一个特性的移除， 都不够在发布说明中提一嘴的么？？？

希望团队能够稍稍用心在项目维护上， 而不仅仅是为了自己的kpi,  做好项目， 写好文档。

不然， 项目快点死了吧， 少祸害点人。

**Comment by NiuXiangQian** [comment]
希望各种组件尽快兼容spring boot 3.x 、spring cloud、java17

**Comment by LuoHong1993** [comment]
啥时候支持spring6、spring boot 3、spring cloud 2022？
隔壁spring-cloud-tencent都开始支持了。

**Comment by Cilong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by herodotus-ecosystem** [comment]
> 啥时候支持spring6、spring boot 3、spring cloud 2022？ 隔壁spring-cloud-tencent都开始支持了。

隔壁是要弯道超车了

**Comment by DearYangs** [comment]
> 

spring cloud alibaba争点气

**Comment by Deathef** [comment]
Spring Boot 3已经GA了，支持Spring Boot 3可以提上日程了。

**Comment by w3n9** [comment]
> 

请问这个案例现在有链接了吗

**Comment by imyxiao** [comment]
希望紧更spring cloud的更新步伐，适配快一点。
