### ISSUE TITLE
2021.0.1 use rockentMq 4.9.2 logger bug

### ISSUE THREAD

**Issue by weixiao5** [alibaba/spring-cloud-alibaba#2503]
**Which Component**
spring-cloud-stream 3.1.6，spring cloud alibaba 2021.0.1

**Describe the bug**
1、class RocketMQProducerMessageHandler The log is printed every time a message is sent

`package com.alibaba.cloud.stream.binder.rocketmq.integration.outbound;`

`log.info("the message has sent,message={},sendResult={}", mqMessage,sendResult);`

The info level modifies the debug level 
`log.debug("the message has sent,message={},sendResult={}", mqMessage,sendResult);`

2、class DirectWithAttributesChannel print 
`2022-04-07 00:17:02.062  INFO 10844 --- [   scheduling-1] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'unknown.channel.name' has 1 subscriber(s).`

**Comment by pandaapo** [comment]
`o.s.c.s.m.DirectWithAttributesChannel` is the class of spring cloud, not spring cloud alibaba.

**Comment by weixiao5** [comment]
您好，您的邮件我已经收到，我会尽快回复的。谢谢您的支持！

**Comment by steverao** [comment]
we solved it.

**Comment by weixiao5** [comment]
您好，您的邮件我已经收到，我会尽快回复的。谢谢您的支持！
