### ISSUE TITLE
2021.0.1.0 版本 nacos 默认不会读取 服务名对应的配置文件了么

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#2507]
2021.0.1.0 版本 nacos 2.0.2 默认不会读取 服务名对应的配置文件了么

**Comment by JavaLionLi** [comment]
现在的现象是 原先不需要配置 可以自动读取 服务名对应的配置文件
升级之后 不会进行读取了 需要在配置文件引入

**Comment by steverao** [comment]
> 2021.0.1.0 版本 nacos 2.0.2 默认不会读取 服务名对应的配置文件了么

2021.0.1.0 我们支持的是 nacos 1.4.2 版本

**Comment by JavaLionLi** [comment]
> > 2021.0.1.0 版本 nacos 2.0.2 默认不会读取 服务名对应的配置文件了么
> 
> 2021.0.1.0 我们支持的是 nacos 1.4.2 版本

你能把问题看明白嘛 我想问的是 原先可以默认读取服务名对应的配置文件 现在读取不了 是不是没有这个功能了

**Comment by steverao** [comment]
> > > 2021.0.1.0 版本 nacos 2.0.2 默认不会读取 服务名对应的配置文件了么
> > 
> > 
> > 2021.0.1.0 我们支持的是 nacos 1.4.2 版本
> 
> 你能把问题看明白嘛 我想问的是 原先可以默认读取服务名对应的配置文件 现在读取不了 是不是没有这个功能了

这么回复你的意思是尽量使用官方推荐的nacos版本，如果有问题优先排除其他问题，控制变量来看吧

**Comment by DanielLiu1123** [comment]
使用 import 方式导入配置的话，不会默认拉取，需要手动配置；使用 bootstrap 方式会自动默认拉取。

具体使用可以参考一下升级文档或者 example

**Comment by JavaLionLi** [comment]
> > > > 2021.0.1.0 版本 nacos 2.0.2 默认不会读取 服务名对应的配置文件了么
> > > 
> > > 
> > > 2021.0.1.0 我们支持的是 nacos 1.4.2 版本
> > 
> > 
> > 你能把问题看明白嘛 我想问的是 原先可以默认读取服务名对应的配置文件 现在读取不了 是不是没有这个功能了
> 
> 这么回复你的意思是尽量使用官方推荐的nacos版本，如果有问题优先排除其他问题，控制变量来看吧

看看人家看看你 差距

**Comment by JavaLionLi** [comment]
> 使用 import 方式导入配置的话，不会默认拉取，需要手动配置；使用 bootstrap 方式会自动默认拉取。
> 
> 具体使用可以参考一下升级文档或者 example

好的谢谢
