### ISSUE TITLE
nacos 跨group调用问题 讨论

### ISSUE THREAD

**Issue by galaxy-sea** [alibaba/spring-cloud-alibaba#2509]
**Which Component**
Nacos Discovery

**Describe the bug**

nacos discovery 跨 group的问题我跟踪了一下，看了一下代码实现, 现在的设计是Namespace和group是同一个概念了.

看了nacos的官网文档，nacos的group和Spring Cloud的clusterName才是同一个概念

**Expected behavior**

**Screenshots**

**Comment by li-xiao-shuang** [comment]
> **Which Component** Nacos Discovery
> 
> **Describe the bug**
> 
> nacos discovery 跨 group的问题我跟踪了一下，看了一下代码实现, 现在的设计是Namespace和group是同一个概念了.
> 
> 看了nacos的官网文档，nacos的group和Spring Cloud的clusterName才是同一个概念
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.

The group of Nacos discovery is used for weak isolation scenarios. For example, the same service has grpc protocol and http protocol. You can choose to use or not use it according to the actual business situation.

**Comment by galaxy-sea** [comment]
我觉得nacos-discovery不应该默认group, 应该把group的选择权交给rpc框架, 由rpc框架选择要不要进行group
