### ISSUE TITLE
版本说明为什么没有包含Apache Dubbo

### ISSUE THREAD

**Issue by HeyChiang** [alibaba/spring-cloud-alibaba#2512]
在引用SpringCloud Alibaba整套框架时，不知道怎么选择Apache Dubbo的版本，是否有地方可以参考？

**Comment by steverao** [comment]
这是两个独立的开源框架，现在最新版本2021.0.1.0已经跟Dubbo没有关联了，不需要考虑之间版本问题。另外，不建议业务中两种框架混用，这对于你们后续维护是比较大的代价。

**Comment by HeyChiang** [comment]
Alibaba的[Github官网](https://github.com/alibaba/spring-cloud-alibaba)仍然引用了Apache Dubbo框架。如果完全独立，后期是否会考虑有单独的Alibaba Dubbo文档？

**Comment by steverao** [comment]
我们已经在最新的分支里面把Spring Cloud Dubbo相关的内容代码给删除了，你说的链接问题，这块应该是上次删除代码的时候没有及时删除（如果方便可以提PR帮助社区删除掉相关内容）。apache dubbo本身是有文档的：https://dubbo.apache.org/zh/index.html，不知道这个是不是你需要的？

**Comment by HeyChiang** [comment]
我大概理解了，SpringCloud Alibaba把Dubbo剔除掉了，都交给Apache Dubbo去维护了。 

我今天会提交一个PR 删除掉所有关于dubbo的内容，并说明原因。

**Comment by HeyChiang** [comment]
我觉得wiki 里面也要说明下，没找到改的地方
