### ISSUE TITLE
Nacos服务器不可访问，要不要抛异常？

### ISSUE THREAD

**Issue by johnyannj** [alibaba/spring-cloud-alibaba#2514]
目前NacosDiscoveryClient 是抛异常的。
```
@Override
	public List<ServiceInstance> getInstances(String serviceId) {
		try {
			return Optional.of(serviceDiscovery.getInstances(serviceId)).map(instances -> {
						ServiceCache.setInstances(serviceId, instances);
						return instances;
					}).get();
		}
		catch (Exception e) {
			if (failureToleranceEnabled) {
				return ServiceCache.getInstances(serviceId);
			}
			throw new RuntimeException(
					"Can not get hosts from nacos server. serviceId: " + serviceId, e);
		}
	}
```
但是nacos的client会被CompositeDiscoveryClient调用。

如果是多注册中心，nacos不可用，会导致spring cloud 不去别的注册中心查询
```
@Override
	public List<ServiceInstance> getInstances(String serviceId) {
		if (this.discoveryClients != null) {
			for (DiscoveryClient discoveryClient : this.discoveryClients) {
				List<ServiceInstance> instances = discoveryClient.getInstances(serviceId);
				if (instances != null && !instances.isEmpty()) {
					return instances;
				}
			}
		}
		return Collections.emptyList();
	}

````

**Comment by misselvexu** [comment]
Spring Cloud only support  `single registry` by default, but we can be extended to enable registry switching.

**Comment by DanielLiu1123** [comment]
可以通过自行实现 `DiscoveryClient` 来达到预期行为。

**Comment by johnyannj** [comment]
@DanielLiu1123 @misselvexu  不是能不能实现的问题， 我的疑问是，这个地方该不该抛异常，是不是返回EmptyList就可以？

**Comment by misselvexu** [comment]
The handling mechanism is inconsistent, returning an empty set means there are no available instances, throwing an exception means there's an error somewhere, but sca framework does handle this one a bit roughly.

**Comment by steverao** [comment]
> @DanielLiu1123 @misselvexu 不是能不能实现的问题， 我的疑问是，这个地方该不该抛异常，是不是返回EmptyList就可以？

现在已经提供了spring.cloud.nacos.discovery.failure-tolerance-enabled去让用户自己去选择是否抛出异常，返回空列表也容易跟真正为null的场景造成混淆。另外，其实多注册场景暂时不考虑的，Spring Cloud默认只提供单注册，多注册的场景一般适合于注册中心迁移等问题，长时间维护多个注册中心其实会把应用架构搞得比较复杂，维护成本也高，不建议使用。
