### ISSUE TITLE
Java heap space

### ISSUE THREAD

**Issue by swhr0903** [alibaba/spring-cloud-alibaba#2516]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
[com.alibaba.nacos.client.config.impl.ClientWorker] [] - longPolling error :  java.lang.OutOfMemoryError: Java heap space

**Comment by steverao** [comment]
Please provider more information, such as more logs about the exception, your Spring Cloud Alibaba and Nacos version, etc.

**Comment by swhr0903** [comment]
spring-cloud-alibaba: 2.2.5.RELEASE
nacos: 1.4.1

**Comment by steverao** [comment]
Can you give a minimum example to reproduce this problem? This will resolve your problem faster.

**Comment by swhr0903** [comment]
I can't, it doesn't happen often, occasionally

**Comment by G0die** [comment]
这个是使用问题？还是nacos问题，升级nacos能解决这个问题吗
