### ISSUE TITLE
About Sentinel + Feign‘s fallbackFactory

### ISSUE THREAD

**Issue by Alleninggx** [alibaba/spring-cloud-alibaba#2518]
BOM：
Spring Cloud Alibaba：2.2.7.RELEASE
Spring Cloud：Spring Cloud Hoxton.SR12
Spring Boot：2.3.12.RELEASE
---

我使用Sentinel + Feign，在编写一个`FeignClient`的时候，指定了对应的`fallbackFactory`属性，因为我用Spring Cloud，理所当然使用了`spring-cloud-openfeign-core`下的`FallbackFactory`接口。接下来运行的时候，报出了错误：类似`Incompatible fallbackFactory instance. Fallback/fallbackFactory of type MyFallbackFactory is not assignable to EchoService for feign client service-provider`。

I use Sentinel + Feign, when writing a 'FeignClient', specified the corresponding `fallbackFactory` attribute. I use the `FallbackFactory` interface under `spring-cloud-openfeign-core` because I feel like I'm using Spring Cloud. But an error is reported at run time, same `Incompatible fallbackFactory instance. Fallback/fallbackFactory of type MyFallbackFactory is not assignable to EchoService for feign client service-provider`.

![image](https://user-images.githubusercontent.com/40049392/164951255-7c4419fe-da00-4ea5-8375-8f1ef8d661de.png)

---

我翻看源代码注释，也有标明去查看此类`org.springframework.cloud.openfeign.FallbackFactory`。

I looked at the source code comments and also marked to view such `org.springframework.cloud.openfeign.FallbackFactory`.

![image](https://user-images.githubusercontent.com/40049392/164951054-ee9f0203-a5ad-4100-b3e4-fe53833caf10.png)

---

于是我DEBUG了异常跑出的代码。发现它做类型判断的时候，只支持`feign.hystrix.FallbackFactory`，而`org.springframework.cloud.openfeign.FallbackFactory`就抛出异常。

So I DEBUG the code that ran out of the exception. When it is found to make type judgment, only `feign.hystrix.FallbackFactory` is supported, and an exception is thrown by `org.springframework.cloud.openfeign.FallbackFactory`.

Source Code: `com/alibaba/cloud/spring-cloud-starter-alibaba-sentinel/2.2.7.RELEASE/spring-cloud-starter-alibaba-sentinel-2.2.7.RELEASE-sources.jar!/com/alibaba/cloud/sentinel/feign/SentinelFeign.java:118`
![image](https://user-images.githubusercontent.com/40049392/164951406-7738f1a6-57d9-4e1f-b626-0d6f19c48e6c.png)

--- 

我的疑问，是因为什么原因不能用`org.springframework.cloud.openfeign.FallbackFactory`，还是我使用方法有问题吗？

My question is, is there any reason why I can't use `org.springframework.cloud.openfeign.FallbackFactory`, or is there something wrong with my method?

---

**Which Component**
Nacos Discovery, Sentinel

**Describe what problem you have encountered**
Sentinel + Fiegn Not Support `org.springframework.cloud.openfeign.FallbackFactory`

**Describe what information you have read**
I have read the reference doc of Sentinel

**Comment by DanielLiu1123** [comment]
Can you give a minimum example to reproduce this problem? This will resolve your problem faster.

**Comment by Alleninggx** [comment]
邮件已收到！

**Comment by Alleninggx** [comment]
> Can you give a minimum example to reproduce this problem? This will resolve your problem faster.

I'm afraid I won't be able to provide examples any time soon.

**Comment by Alleninggx** [comment]
邮件已收到！
