### ISSUE TITLE
nacos服务器修改节点状态，注册节点自身如何同步？

### ISSUE THREAD

**Issue by johnyannj** [alibaba/spring-cloud-alibaba#2519]
spring cloud nacos插件，注册到nacos的节点状态默认是health=true
如果nacos服务器把节点改成health=false.

如果节点和nacos之间网络失效一会，heartbeat失败，再重新注册上来，health不又变成了true了吗？

**Comment by steverao** [comment]
This is nacos problem, you need to ask for helps from nacos community.

**Comment by johnyannj** [comment]
@steverao if spring cloud  sync the status from the server periodically, It's also a solution。
