### ISSUE TITLE
非java异构服务访问java微服务怎样通过sidecar实现呢

### ISSUE THREAD

**Issue by windrainroad** [alibaba/spring-cloud-alibaba#2527]
非java异构服务访问java微服务，spring cloud netflix sidecar可以通过如下格式实现，但alibaba sidecarq却访问不了？
http://{sidecar-host}:{sidecar-port}/{目的服务的服务名}/{目的服务的path}

**Comment by galaxy-sea** [comment]
你好， 你是通过gateway访问你的异构服务的嘛

http://{gateway-host}:{gateway-port}/{目的服务的服务名}/{目的服务的path}

**Comment by steverao** [comment]
Long time without response, close first!
