### ISSUE TITLE
can't recognized BlockException when use restTemplate with SentinelRestTemplate

### ISSUE THREAD

**Issue by caps-xia** [alibaba/spring-cloud-alibaba#2536]
SentinelProtectInterceptor
try {
            try {
                hostEntry = SphU.entry(hostResource, EntryType.OUT);
                if (entryWithPath) {
                    hostWithPathEntry = SphU.entry(hostWithPathResource, EntryType.OUT);
                }

                response = execution.execute(request, body);
                if (this.restTemplate.getErrorHandler().hasError(response)) {
                    Tracer.trace(new IllegalStateException("RestTemplate ErrorHandler has error"));
                }

                ClientHttpResponse var12 = response;
                return var12;
            } catch (Throwable var17) {
                if (!BlockException.isBlockException(var17)) {
                    Tracer.traceEntry(var17, hostEntry);
                    if (var17 instanceof IOException) {
                        throw (IOException)var17;
                    }

                    if (var17 instanceof RuntimeException) {
                        throw (RuntimeException)var17;
                    }

                    throw new IOException(var17);
                }
            }

            var13 = this.handleBlockException(request, body, execution, (BlockException)var17);
        } finally {
            if (hostWithPathEntry != null) {
                hostWithPathEntry.exit();
            }

            if (hostEntry != null) {
                hostEntry.exit();
            }

        }

when i use SentinelRestTemplate,kill provider,why !BlockException.isBlockException(var17) is true in SentinelProtectInterceptor

**Comment by DanielLiu1123** [comment]
You killed provider, it should be network err ?

Please provide more info about your case.

**Comment by caps-xia** [comment]
> You killed provider, it should be network err ?
> 
> Please provide more info about your case.

exception is java.net.ConnectException: Connection refused，can‘t trigger  circuit breaker？ why can trigger  circuit breaker when use feign in this case

**Comment by DanielLiu1123** [comment]
Annotation `@SentinelRestTemplate` is not very mature, will refactor this feature in the future,  try not to use it.

**Comment by caps-xia** [comment]
> will

its not the same with feign?if @SentinelRestTemplate cant trigger fallback when provider is killed，what scene will trigger fallback

**Comment by steverao** [comment]
Long time without response
