### ISSUE TITLE
Support without file extensions in nacos-config

### ISSUE THREAD

**Issue by onewe** [alibaba/spring-cloud-alibaba#2537]
Hey, I found a little problem. if I configure a `data-id` without file extensions in `extension-configs` , but config content type is `yaml`. then there is a proble, configuration is invalid. because the configuration is parsed by properties. so I want to add `fileExtension` field in `NacosConfigProperties.Config`.

我发现一个小问题, 如果在`extension-configs`里的`data-id`没有带文件后缀,并且配置内容格式是`yaml`或者其他类型,那么这个配置就会无效,因为会按照`properties`的格式进行解析. 所以我想添加一个`fileExtension`属性到`NacosConfigProperties.Config`里,用于支持这种场景.

about issues: https://github.com/alibaba/nacos/issues/8289
相关问题: https://github.com/alibaba/nacos/issues/8289

**Comment by DanielLiu1123** [comment]
Welcome to contribute this feature.

**Comment by onewe** [comment]
Ok, I will finish it.
