### ISSUE TITLE
spring boot集成阿里云Rocket MQ发送消息失败

### ISSUE THREAD

**Issue by zhangwenbi** [alibaba/spring-cloud-alibaba#2541]
报错信息：com.aliyun.openservices.ons.shaded.org.apache.rocketmq.client.exception.ClientException: error code: FETCH_TOPIC_ROUTE_FAILURE

服务器报错：(Slf4jLoggerFactory.java:95)- closeChannel: close the connection to remote address[] result: true

**Comment by steverao** [comment]
Do you use the method of using RocketMQ provided by Spring Cloud Alibaba?

**Comment by zhangwenbi** [comment]
I am using the official Demo of Ali Cloud Rocket MQ
chained address:https://code.aliyun.com/aliware_rocketmq/rocketmq-demo/tree/master/springboot/java-springboot-demo?spm=a2c4g.11186623.0.0.30f328074isTIH

**Comment by zhangwenbi** [comment]
> 你用的是Spring Cloud Alibaba提供的RocketMQ的使用方法吗？

I am using the official Demo of Ali Cloud Rocket MQ
chained address:https://code.aliyun.com/aliware_rocketmq/rocketmq-demo/tree/master/springboot/java-springboot-demo?spm=a2c4g.11186623.0.0.30f328074isTIH

**Comment by steverao** [comment]
Recommend to add dingtalk group 21982288 and ask for helps in it.
