### ISSUE TITLE
NacosConfigManger ConfigService need reload

### ISSUE THREAD

**Issue by SKYhuangjing** [alibaba/spring-cloud-alibaba#2547]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config Starter

**Describe the bug**
when NacosConfigProperties has been changed, bug NacosConfigManager configservice can't reload it.

**To Reproduce**
1. set bootstrap.yml namespace is xx_${spring.profiles.active}
2. use nacosConfigManager serivce in biz code.
3. when get or publish config to nacos server, it will be throw warn invalid tenant

**Expected behavior**
get or publish success

**Comment by steverao** [comment]
Please provider your version information of Spring Cloud Alibaba and give us a simplified demo to reproduce it.

**Comment by DanielLiu1123** [comment]
Can you give a demo to reproduce it ?

**Comment by SKYhuangjing** [comment]
update demo later..

**Comment by SKYhuangjing** [comment]
Spring Cloud Alibaba version 2021.0.1.0
Spring Boot Version 2.6.7

demo url : https://github.com/SKYhuangjing/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example

run the demo and 
```bash
curl http://localhost:8080/config/getConfigNamespace
```
Actual result : business_group_${spring.profiles.active}%
Expect result : business_group_local

ps : so I can't use configService in NacosConfigManager, need regenerate ConfigService from NacosFactory.createConfigService.

**Comment by DanielLiu1123** [comment]
1. I remember `namespace` should be the namespace id ?
2. `bootstrap.yml` was loaded before `application.yml`, so you can't get `spring.profiles.active` when `bootstrap.yml` was loading.

**Comment by SKYhuangjing** [comment]
> 1. I remember `namespace` should be the namespace id ?
> 2. `bootstrap.yml` was loaded before `application.yml`, so you can't get `spring.profiles.active` when `bootstrap.yml` was loading.

Question 1 : I have set the namesapce id and  name is same
Question 2 : Yes, I know it, in this senario,  I debug the init source code, nacosConfigProperties will be set many times, so namespace value will be fine, but configservice will init in first time, if we need use nacosconfigManager.configService, It can't work, so I want know the nacos offical site have plan to fix it ?

**Comment by steverao** [comment]
For an general application, it just need an object of Config Service, we intentionally make it load only once, can you describe in detail why you need to use NacosConfigManager.configService directly?

**Comment by SKYhuangjing** [comment]
> For an general application, it just need an object of Config Service, we intentionally make it load only once, can you describe in detail why you need to use NacosConfigManager.configService directly?

I have provide my demo, in my senario, I need use dynamic namespace config, but the Config Service will not init correct in daynamic config, i just want know, offical site will fix it?
