### ISSUE TITLE
Can we set specific clientIP in RocketMQCommonProperties rather than auto configuration?

### ISSUE THREAD

**Issue by jjyyjjyy** [alibaba/spring-cloud-alibaba#2548]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-starter-stream-rocketmq

**Describe the bug**
Currently, RocketMQ set clientIP with first local ipv4 address automatically, but we neet to set specific ip manually, and RocketMQ starter doesn't provide any way about this.

**To Reproduce**

**Expected behavior**
There should be a "clientIP" field in RocketMQCommonProperties.

**Screenshots**

**Additional context**
latest version

**Comment by Sorieee** [comment]
What does "clientIP" mean?

**Comment by Sorieee** [comment]
Do you mean this property?
![image](https://user-images.githubusercontent.com/8654292/168284776-b5ba8f2b-a698-4f3b-90db-d9c27863cee6.png)

**Comment by Sorieee** [comment]
And Why do you need to modify it?

**Comment by DanielLiu1123** [comment]
You can set `clientIP` through producer or consumer `setClientIP(String)` method.

**Comment by jjyyjjyy** [comment]
> Do you mean this property? ![image](https://user-images.githubusercontent.com/8654292/168284776-b5ba8f2b-a698-4f3b-90db-d9c27863cee6.png)

**Comment by jjyyjjyy** [comment]
> Do you mean this property? ![image](https://user-images.githubusercontent.com/8654292/168284776-b5ba8f2b-a698-4f3b-90db-d9c27863cee6.png)

Yes, it is

**Comment by jjyyjjyy** [comment]
We need to set clientIP as elastic ip in cloud environment.

**Comment by jjyyjjyy** [comment]
We are using rocketmq-spring-boot-starter and spring-cloud-starter-stream-rocketmq module, its better to provide configuration properties, not call method manually.

**Comment by DanielLiu1123** [comment]
> We are using rocketmq-spring-boot-starter and spring-cloud-starter-stream-rocketmq module, its better to provide configuration properties, not call method manually.

The open source version provides a universal solution. I think you can implement the demand in your projects, but it is not suitable for placing in the open source version.
