### ISSUE TITLE
rocketmq在有链路透传的情况下会抛异常并导致消息无法发出

### ISSUE THREAD

**Issue by liaoshijung** [alibaba/spring-cloud-alibaba#2552]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-starter-stream-rocketmq 2021.0.1.0

**Describe the bug**
在使用sleuth 进行链路透传的情况下，spring message会把sleuth 的baggage放到messageheader里面，但这里面的value有可能为空，此时rocketmq会把这部分header放到UserProperty里面，rocketmq就会抛出异常

**To Reproduce**
1. 添加spring-cloud-starter-sleuth 依赖
2. 配置文件中增加baggage  spring.sleuth.baggage.remote-fields=username
3. 声明BaggageField并往其注入值
4. 在切面或者异步方法中发送消息有概率header的值为空

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7908044/168761979-a90e2f91-f330-4a85-a218-790323de73da.png)

**Additional context**
Java8

**Comment by Sorieee** [comment]
Ok, will fix it later.

**Comment by Sorieee** [comment]
Plz tell me which property will cause exception?

**Comment by Sorieee** [comment]
Ok, I know, blank header.

**Comment by Sorieee** [comment]
Blank String header is not support by rocketmq, you can consult the rocketmq community.

**Comment by Sorieee** [comment]
Plz close this issue @steverao.

**Comment by Sorieee** [comment]
.. Maybe rocketmq-binder can remove all blank header before rocketmq support blank value header, I will imporve it, plz reopen it.

**Comment by chen-junl** [comment]
> 我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。 We recommend using English. If you are non-native English speaker, you can use the translation software.
> 
> **哪个组件** spring-cloud-starter-stream-rocketmq 2021.0.1.0
> 
> **Describe the bug** 在使用sleuth 进行链路透传的情况下，spring message会把sleuth 的baggage放到messageheader里面，但这里面的value有可能为空，此时rocketmq会把这部分header放到UserProperty里面，rocketmq就会抛出异常
> 
> **重现** 重现行为的步骤：
> 
> 1. 添加spring-cloud-starter-sleuth 依赖
> 2. 配置文件中增加baggage  spring.sleuth.baggage.remote-fields=username
> 3. 声明BaggageField并往其注入值
> 4. 在切面或者异步方法中发送消息有概率header的值为空
> 
> **预期行为** 对您预期发生的事情的清晰简洁的描述。
> 
> **截图** ![图片](https://user-images.githubusercontent.com/7908044/168761979-a90e2f91-f330-4a85-a218-790323de73da.png)
> 
> **附加上下文** 在此处添加有关该问题的任何其他上下文。 Java8


使用sleuth跟踪链路 发送消息的时候怎么带上header的? 我全局设置为什么没有效果呢?
