### ISSUE TITLE
[ASoC]Spring Cloud Stream支持RocketMQ能力重构并适配支持RocketMQ 5.0有关新特性

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2564]
### 题目描述
目前 RocketMQ 和 Spring Cloud Stream 整合度不够，没有充分利用到各自的特性，比如 Stream 相关 binding 配置项和 header 的处理，RocketMQ 资源开销优化和 pop 模式的支持。并调研 RocketMQ 5.0 新特性，尝试在 Spring Cloud Alibaba 中提前做一些新功能适配。

### 产出要求

1. 优化原生binding配置和header处理，实现更多的订阅关系(P一对多，C多对一)，支持更多的 RocketMQ 原生特性以及pop消费模式，增强 RocketMQ 部分能力，如可通过调整配置即可实现线程动态调整，负载策略变更等。
2. 调研 RocketMQ 5.0 新特性，尝试在 Spring Cloud Alibaba 中提前做一些新功能适配。
3. 针对设计方案与目标功能，开发插件，并贡献到社区

### 选题要求

- 熟悉 RocketMQ 原理，至少掌握 consumer、producer 各实现机制，熟悉 Spring Cloud Stream 核心机制；
- 参加身份必须为未毕业在校生；
- 暑期7~8月期间保证每周有至少有40个小时参与项目；
- 良好的沟通和协作能力，不畏难，能在导师指导下克服困难完成题目和答辩。

### 题目难度
基础

### 导师信息
Zhang Kaizhao (@zkzlx), ASoC Mentor, Spring Cloud Alibaba Committer
kiss_maple@163.com（联系导师请附上个人简历）

**Comment by BillLthree** [comment]
Mr zhang，My name is Li Yuanhui，I am very interested in this project.I want to try to do this project.

**Comment by steverao** [comment]
> Mr zhang，My name is Li Yuanhui，I am very interested in this project.I want to try to do this project.

Please contact with mentor of the problem and submit your information by the website: https://open-source.alibaba.com/blog/detail/71
