### ISSUE TITLE
[ASoC]Spring Cloud Alibaba实现智能化全自动化测试

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2566]
### 题目描述
Spring Cloud Alibaba项目当前的测试方案效率比较低，存在很多手动替换依赖进行的操作，现在需要为项目设计一套集成测试方案，能够较好地测试项目中Nacos、RocketMQ、Seata、Sentinel等组件功能是否服务预期，结合Github CI实现智能自动化一键测试，提高项目集成测试的效率。

### 产出要求

1. 需要为项目设计一套集成测试方案，能够较好地测试项目中Nacos、RocketMQ、Seata、Sentinel等组件功能是否服务预期，提高项目集成测试的效率，并通过Github CI实现智能化自动测试；
2. 针对设计方案与目标功能，开发插件，并贡献到社区。

### 选题要求

- 了解Spring Cloud Alibaba项目，对其中的支持的Nacos、RocketMQ、Seata、Sentinel等分布式组件有了解；
- 了解一些集成测试相关的技术，比如testContainers、junit以及持续集成持续部署技术；
- 参加身份必须为未毕业在校生；
- 暑期7~8月期间保证每周有至少有40个小时参与项目；
- 良好的沟通和协作能力，不畏难，能在导师指导下克服困难完成题目和答辩。

### 题目难度
基础

### 导师信息
Cheng Xingyuan (@complone), ASoC Mentor, dubbo-go-pixiu member, dubbo contributor
1817802738@qq.com（联系导师请附上个人简历）

**Comment by kaori-seasons** [comment]
Current PR: https://github.com/alibaba/spring-cloud-alibaba/pull/2524
