### ISSUE TITLE
在 application.properties 下spring.cloud.nacos.config.prefix 与 spring.application.name 优先级问题

### ISSUE THREAD

**Issue by jiang4yu** [alibaba/spring-cloud-alibaba#2575]
**Which Component**
eg. Nacos Config

**Describe the bug**
在 **application.properties** 作为配置文件的情况下 当 **spring.application.name**  **spring.cloud.nacos.config.prefix** 不生效

**To Reproduce**
1. 在nacos服务端 分别建立 **dataId** 为 **demo** 与 **example** 配置文件，配置项 useLocalCache 的值分别 为 demo 和 example；
2. 程序使用 application.properties 作为配置文件，其内容如下：
  ```
spring.application.name=example
spring.cloud.nacos.config.prefix=demo
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
  ```
4. 通过访问 http://localhost:8080/config/get 获取结果，则复现 spring.cloud.nacos.config.prefix 不生效的问题

**Expected behavior**
通过上述步骤后，能清晰的看出 获取到的配置内容为  example 而非 demo 所对应的 demo

**Screenshots**
bug 复现程序 [demo](https://github.com/jiang4yu/nacosDemo.git)

**Comment by yuhuangbin** [comment]
使用 bootstrap 进行配置

**Comment by Klayt11** [comment]
对于bootstrap作为公用的配置，怎么保证spring.application.name优先级在application能一直被读取到

**Comment by steverao** [comment]
> 对于bootstrap作为公用的配置，怎么保证spring.application.name优先级在application能一直被读取到

你可以详细描述一下你的需求吗？”怎么保证spring.application.name优先级在application能一直被读取到“没太明白意思。你如果希望spring.application.name配置内容优先级高，直接定义在bootstrap中就好了。

**Comment by Klayt11** [comment]
就是我想把bootstrap抽离做一个可公用的配置文件，不需要每个服务都写一个bootstrap然后去配置nacos注册或者sentinel那些啥的。但是这里spring.application.name写在服务内application.yml之后，在刷新配置后，我看源码是没有去加载application.yml的。将服务内的的application改成bootstrap.yml时，外面的bootstrap又会被覆盖掉。貌似不会合并配置，而是直接替换bootstrap文件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Steve ***@***.***&gt;; 
发送时间: 2022年10月6日(星期四) 晚上11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/spring-cloud-alibaba] 在 application.properties 下spring.cloud.nacos.config.prefix 与 spring.application.name 优先级问题 (Issue #2575)





  
对于bootstrap作为公用的配置，怎么保证spring.application.name优先级在application能一直被读取到
  
你可以详细描述一下你的需求吗？”怎么保证spring.application.name优先级在application能一直被读取到“没太明白意思。你如果希望spring.application.name配置内容优先级高，直接定义在bootstrap中就好了。

**Comment by steverao** [comment]
> 

还是不太理解你的意思，如果需要一份配置被集群内的一部分应用共同使用并且支持动态修改被相关应用都感知到的话，最好就是把它定义在Nacos中，然后在bootstrap配置文件配置相关订阅信息。如果你希望定义几组配置，不是用bootstrap来做（建议了解一下bootstrap和application的区别，这两种配置不是一回事，不能直接替换使用），一般是定义多个`application-{profile}.yml`文件，然后基础的内容定义在application.yml中，特殊的配置定义在`application-{profile}.yml`中，application-xxx.yml中的优先级会更高，优先级顺序：`nacos上的配置 > 本地application-{profile}.yml > 本地application.yml`

**Comment by FangPengbo** [comment]
> > 
> 
> 还是不太理解你的意思，如果需要一份配置被集群内的一部分应用共同使用并且支持动态修改被相关应用都感知到的话，最好就是把它定义在Nacos中，然后在bootstrap配置文件配置相关订阅信息。如果你希望定义几组配置，不是用bootstrap来做（建议了解一下bootstrap和application的区别，这两种配置不是一回事，不能直接替换使用），一般是定义多个`application-{profile}.yml`文件，然后基础的内容定义在application.yml中，特殊的配置定义在`application-{profile}.yml`中，application-xxx.yml中的优先级会更高，优先级顺序：`nacos上的配置 > 本地application-{profile}.yml > 本地application.yml`

如何使本地的配置文件优先级大于nacos上边的呢？
