### ISSUE TITLE
Register service to a non-existent namespace, why the response is SUCCESS?

### ISSUE THREAD

**Issue by gMan1990** [alibaba/spring-cloud-alibaba#2576]
# spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar

https://github.com/alibaba/spring-cloud-alibaba/blob/9c542de53ea83d6adaa86ee08eefb60d6c0bef8b/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java#L74

# nacos-client-2.0.4.jar

com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy#requestToServer

`Response{resultCode=200, errorCode=0, message='null', requestId='null'}`

**Comment by yuhuangbin** [comment]
Can be reported to the Nacos community.
