### ISSUE TITLE
sentinel 规则未生效

### ISSUE THREAD

**Issue by yujunchengg** [alibaba/spring-cloud-alibaba#2578]
sentinel使用nacos管理流控规则，但是springcloud中某个微服务的controller方法添加流控规则后不生效，资源名称和接口路由保持一致

**Comment by steverao** [comment]
请提供详细的信息，比如使用的组件版本号，可复现的最小的demo，上面这样没法查问题！

**Comment by yujunchengg** [comment]
用到的组件版本如下
springboot 2.3.12.RELEASE
springcloud Hoxton.SR12
alibaba.cloud 2.2.7.RELEASE
sentinel 1.8.1
![image](https://user-images.githubusercontent.com/36986915/171339967-5ff27ed7-b963-4645-a84e-483780acdc52.png)

sentinel中流控规则配置如下
![image](https://user-images.githubusercontent.com/36986915/171340451-9dec5437-7ba9-4d7c-92ad-cf5ab7aaad33.png)

然后我客户端pom文件引入的依赖也是跟example文件中的保持一致的，但是死活就是没执行限流

**Comment by steverao** [comment]
> 

官方example内容是可以通过Nacos修改限流熔断配置进行动态限流操作的，你通过Nacos动态修改修改配置，sentinel控制台可以看到规则变化吗？

**Comment by ruansheng8** [comment]
是直接手动在Nacos配置限流规则还是通过Sentinel-Dashboard进行配置的呢
如果是通过Sentinel-Dashboard持久化到Nacos的话, 可以查看一下Nacos的配置列表中是否存在对应的限流规则

**Comment by steverao** [comment]
Long time no response, close first!
