### ISSUE TITLE
'org.springframework.cloud.stream.annotation.Input' 已被弃用

### ISSUE THREAD

**Issue by yl-yue** [alibaba/spring-cloud-alibaba#2585]
**spring-cloud-starter-stream-rocketmq**

`org.springframework.cloud.stream.annotation.Input` 已被弃用，但新的Spring CloudFunction方式也不受支持。

> just use `java.util.function.Consumer` can define a Consumer, it is Spring Cloud Stream v3 recommended way, while `@StreamListener` is outdated
> ```java
> @Bean
> public Consumer<String> sink() {
>     return System.out::println;
> }
> ```

[👉详情见spring_cloud_function文档](https://docs.spring.io/spring-cloud-stream/docs/3.2.4/reference/html/spring-cloud-stream.html#spring_cloud_function)

**Comment by steverao** [comment]
相关使用文档我们已经更新了在2021.x分支，尽快会合并进来的

**Comment by yl-yue** [comment]
已测试spring-cloud-function方式是支持的，但相关文档未更新，倒是在2021.x分支看到了相关示例，谢谢！
