### ISSUE TITLE
Spring cloud has released 2021.0.3. Will the community follow up

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#2586]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。

Spring cloud has released 2021.0.3. Will the community follow up?
When will the next version of the 2021.x branch be released?

spring cloud 已经发布 2021.0.3 了 社区是否会跟进 
2021.X 分支的下一个版本大概什么时候发布呢

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by steverao** [comment]
最近不会发布支持2021.x.x的spring cloud 版本，近期会发布2.2.8版本对所支持的组件进行一下升级。

**Comment by Cilong** [comment]
> 最近不会发布支持2021.x.x的spring cloud 版本，近期会发布2.2.8版本对所支持的组件进行一下升级。

请问最近会发布2021.x.xspring cloud版本吗，支持nacos 2.x和ipv6.

**Comment by steverao** [comment]
> > 最近不会发布支持2021.x.x的spring cloud 版本，近期会发布2.2.8版本对所支持的组件进行一下升级。
> 
> 请问最近会发布2021.x.xspring cloud版本吗，支持nacos 2.x和ipv6.

是的，近期会发布相关新版本。

**Comment by Cilong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
