### ISSUE TITLE
建议把 2021.X 分支的 nacos 使用文档改改 新用法最好在nacos文档里说明一下

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#2588]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by steverao** [comment]
其实是有说明的，在nacos-config-2.4.x-exampel的readme.md中，这块可以将nacos-config-2.4.x-examples跟nacos-config-example合并一下，只保留一个，欢迎有兴趣的同学来做一下：）

**Comment by JavaLionLi** [comment]
我想说的是docs模块内的 看examples代码的还是少数 主要还是看docs

**Comment by steverao** [comment]
文档相关的问题，欢迎社区内外同学一起参与进来：）
