### ISSUE TITLE
undertow 与 nacos 一起用 服务停止的时候 异常报错(nacos社区让我来这提bug)

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#2589]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

https://github.com/alibaba/nacos/issues/8550

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by JavaLionLi** [comment]
spring cloud alibaba nacos 2021.0.1.0
springboot 2.6.8

**Comment by liqi19950722** [comment]
A quick conclusion
Does not affect use, just a line of error log.

Reason:
`NacosWatch` Bean invoke `stop()` method after `WebServerStartStopLifecycle` invokestop().
At that time servlet container is closed, then throw `NullPointExcpetion` or throw `IllegalStateException` after undertow version 2.3.0.Alpha1.

[undertow link](https://github.com/undertow-io/undertow/commit/8749be0a19b565565d38e646be412ef2a80b2fe1)

The solution in my opinion:
1. change the log level NacosWatch.
 ```
 log.error("namingService unsubscribe failed, properties:{}", properties, e); ->

 log.warn("namingService unsubscribe failed, properties:{}", properties, e);
```

2. let NacosWatch invoke stop() before WebServerStartStopLifecycle
    WebServerStartStopLifecycle = Integer.MAX_VALUE - 1
    NacosWatch getPhase value is bigger than WebServerStartStopLifecycle's is ok.

```
@Override
public int getPhase() {
	return 0;
}
@Override
public int getPhase() {
	return Integer.MAX_VALUE;
}
```
The processing method of [DefaultLifecycleProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java)

结论： 不影响使用。

问题原因： 
NacosWatch 执行 `stop()` 方法在 `WebServerStartStopLifecycle` 之后， `com.alibaba.spring.util.PropertySourcesUtils#getPropertyNames`执行时undertow 已经被关闭。抛出空指针异常。

我的解决方式：

1. 改变NacosWatch的日志等级， 参考 [InitDestroyAnnotationBeanPostProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/factory/annotation/InitDestroyAnnotationBeanPostProcessor.java) postProcessBeforeDestruction这个方法
2. 让NacosWatch在WebServerStartStopLifecycle之前执行 stop()方法。
[DefaultLifecycleProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java)的处理方式 根据phase倒序，大的先执行

**Comment by JavaLionLi** [comment]
> A quick conclusion Does not affect use, just a line of error log.
> 
> Reason: `NacosWatch` Bean invoke `stop()` method after `WebServerStartStopLifecycle` invokestop(). At that time servlet container is closed, then throw `NullPointExcpetion` or throw `IllegalStateException` after undertow version 2.3.0.Alpha1.
> 
> [undertow link](https://github.com/undertow-io/undertow/commit/8749be0a19b565565d38e646be412ef2a80b2fe1)
> 
> The solution in my opinion:
> 
> 1. change the log level NacosWatch.
> 
> ```
> log.error("namingService unsubscribe failed, properties:{}", properties, e); ->
> 
> log.warn("namingService unsubscribe failed, properties:{}", properties, e);
> ```
> 
> 2. let NacosWatch invoke stop() before WebServerStartStopLifecycle
>    WebServerStartStopLifecycle = Integer.MAX_VALUE - 1
>    NacosWatch getPhase value is bigger than WebServerStartStopLifecycle's is ok.
> 
> ```
> @Override
> public int getPhase() {
> 	return 0;
> }
> @Override
> public int getPhase() {
> 	return Integer.MAX_VALUE;
> }
> ```
> 
> The processing method of [DefaultLifecycleProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java)
> 
> 结论： 不影响使用。
> 
> 问题原因： NacosWatch 执行 `stop()` 方法在 `WebServerStartStopLifecycle` 之后， `com.alibaba.spring.util.PropertySourcesUtils#getPropertyNames`执行时undertow 已经被关闭。抛出空指针异常。
> 
> 我的解决方式：
> 
> 1. 改变NacosWatch的日志等级， 参考 [InitDestroyAnnotationBeanPostProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/factory/annotation/InitDestroyAnnotationBeanPostProcessor.java) postProcessBeforeDestruction这个方法
> 2. 让NacosWatch在WebServerStartStopLifecycle之前执行 stop()方法。
>    [DefaultLifecycleProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/support/DefaultLifecycleProcessor.java)的处理方式 根据phase倒序，大的先执行

![image](https://user-images.githubusercontent.com/31852897/173731456-5d465e41-ebe6-4b01-9242-ad772235e55c.png)
![image](https://user-images.githubusercontent.com/31852897/173731474-2eecbede-ffd7-47b7-a34e-89cb5a419b05.png)
继承重写修改 `getPhase` 等级后 不报错了 感谢回复

**Comment by jsczrangel** [comment]
![image](https://user-images.githubusercontent.com/35262775/177081403-3ed5db68-c83f-472d-be38-e8bf2e53c0cd.png)
2021.1版本的nacosWatch构造方法多了一个参数，请教下这个怎么初始化 @JavaLionLi
