### ISSUE TITLE
[Sentinel] Refacter the examples of Sentinel

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2590]
1. The example of Sentinel is in chaos, don't provider all features about Sentinel.
2. You can use the website (https://httpbin.org) to write the examples, such as this is a delay request (https://httpbin.org/delay/3), this is a exception request (https://httpbin.org/status/404)

**Comment by zhangqian9158** [comment]
I will finish it！

**Comment by steverao** [comment]
Please leave a deadline, otherwise other people will pick it up.
