### ISSUE TITLE
why spring-cloud-alibaba nacos not use spring.application.name, but use project.name?

### ISSUE THREAD

**Issue by wushuaiping** [alibaba/spring-cloud-alibaba#2591]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

Is your feature request related to a problem? Please describe.
1. why use project.name? I think developers related to the Java ecosystem should all use spring.application.name as application name, can not project.name.
2. Or what is the reason for not supporting spring.application.name in spring-cloud-alibaba nacos?
3. i want to know the answer.

Describe the solution you'd like
i hope supporting spring.application.name in spring-cloud-alibaba nacos

Describe alternatives you've considered
if project.name exist, use project.name, if spring.application.name exist, use spring.application.name

**Comment by yuhuangbin** [comment]
Can you describe exactly what the function is? As far as I know, the service registration is used `spring.application.name`.
