### ISSUE TITLE
How to let the nacos-discovery-client refresh its cache quickly when instances up/down?

### ISSUE THREAD

**Issue by boholder** [alibaba/spring-cloud-alibaba#2594]
**Which Component**

We use the `spring-cloud-starter-alibaba-nacos-discovery:2.2.1RELEASE` as SD dependence in Java spring boot applications. And of course we have set up a Nacos cluster.

**Describe what problem you have encountered**

In brief, the java consumer application can't quickly react on providers' up/down events, with default configurations I guess.
After a provider downed, we can't see it on the Nacos cluster's web console, which is good. But the consumer still sending queries to downed instance (ip address) and causing "no response" errors.

I'm sure there must be some configurations for client or server that can deal with this problem, but I just be confused by the google search results and the official documents, not mentioning there is another project called "Nacos Config" which makes searching more difficult.

**Describe what information you have read**

I struggled to find [this document](https://spring-cloud-alibaba-group.github.io/github-pages/hoxton/zh-cn/index.html#_%E5%85%B3%E4%BA%8E_nacos_discovery_starter_%E6%9B%B4%E5%A4%9A%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E4%BF%A1%E6%81%AF) but configurations inside it can't achieve what I want.

**Comment by boholder** [comment]
Must we use the SDK to manually processing these event?
https://nacos.io/zh-cn/docs/sdk.html

**Comment by yuhuangbin** [comment]
refer `NacosRule.java`
