### ISSUE TITLE
Spring Cloud Bootstrap is no longer supported.

### ISSUE THREAD

**Issue by zhangpan-soft** [alibaba/spring-cloud-alibaba#2595]
Recently, I was studying spring native, but I found a problem Spring native has abandoned its support for bootstrap However, it seems that cloud Alibaba has not been processed properly, resulting in an error loading the configuration center when the project is started Can I add a native plug-in of Alibaba so that I can connect to native, just like the native support provided by Google? I hope to provide such native support. Thank you!
version info:

spring native: 0.11.x,0.12.0
spring cloud: >=2021.0.1)
spring boot: >=2.6.3)
spring cloud alibaba: 2021.0.1.0

**Comment by sunsilong-pacvue** [comment]
卧槽 楼上的大佬 我刚在研究spring native 正愁找不到人 你就出来了

**Comment by sunsilong-pacvue** [comment]
> 卧楼的大佬 我刚在研究春天的人 正愁找不到人 你就出来了

给个邮箱联系下啊 交流交流

**Comment by zhangpan-soft** [comment]
> 

zhangpan_soft@163.com

**Comment by DanielLiu1123** [comment]
Since 2021.0.1.0, you can use `import` instead of `bootstrap`.

Currently, SCA has not done compatibility testing with Spring Native, so don't use Spring Native for the current project !

This need a lot work ......

**Comment by zhangpan-soft** [comment]
> Since 2021.0.1.0, you can use `import` instead of `bootstrap`.
> 
> Currently, SCA has not done compatibility testing with Spring Native, so don't use Spring Native for the current project !
> 
> This need a lot work ......

I know that Alibaba has no support for native products However, I think the Alibaba technical team can start to study it, just like the native support provided by Google Alibaba has always been the leader of the Internet in China. I think 80% of the projects in the Chinese market use springcloud alibaba So I want to get help from native support so that I can keep up with the mainstream of technology.
Spring native has been tried by big manufacturers abroad, such as Google, Facebook and twitter Therefore, I think we can also keep up with the top technology and produce one. There are many like-minded people who can work together and take the lead

**Comment by steverao** [comment]
> > Since 2021.0.1.0, you can use `import` instead of `bootstrap`.
> > Currently, SCA has not done compatibility testing with Spring Native, so don't use Spring Native for the current project !
> > This need a lot work ......
> 
> I know that Alibaba has no support for native products However, I think the Alibaba technical team can start to study it, just like the native support provided by Google Alibaba has always been the leader of the Internet in China. I think 80% of the projects in the Chinese market use springcloud alibaba So I want to get help from native support so that I can keep up with the mainstream of technology. Spring native has been tried by big manufacturers abroad, such as Google, Facebook and twitter Therefore, I think we can also keep up with the top technology and produce one. There are many like-minded people who can work together and take the lead

I agree with you, please add my dingtalk account: steverao2021, so that we can talk about this topic.
