### ISSUE TITLE
Spring-cloud-alibaba 2.2.6.RELEASE,nacos2.0.4 ,dubbo注册地址使用spring-cloud://localhost配置。在k8s环境启动时，消费者先启动，生产者后启动。

### ISSUE THREAD

**Issue by RedA1ert** [alibaba/spring-cloud-alibaba#2599]
alibaba-cloud 2.2.6.RELEASE
dubbo: 2.7.8

dubbo.registry.address=spring-cloud://localhost
dubbo.registry.check=false
dubbo.consumer.check=false
dubbo.consumer.timeout=120000
dubbo.protocol.id=dubbo
dubbo.protocol.name=dubbo

**Comment by RedA1ert** [comment]
调用时 no provider avaliable xxxx localhost,按照官方说法2.2.6.RELEASE已经解决了这个问题，但是在实际使用中，这个问题依然存在

**Comment by steverao** [comment]
dubbo注册中心是指的什么？

**Comment by RedA1ert** [comment]
> 注册

说错了 注册地址

**Comment by RedA1ert** [comment]
> dubbo注册中心是指的什么？

上面的图里面我写的有配置

**Comment by steverao** [comment]
没太理解你的问题，你是使用spring cloud alibaba中哪一个组件遇到问题了？

**Comment by RedA1ert** [comment]
> 没太理解你的问题，你是使用spring cloud alibaba中哪一个组件遇到问题了？

使用spring-cloud-alibaba 的dubbo组件。dubbo的注册地址配置为spring-cloud://localhost的时候，服务生产者和消费者可以正常启动(消费者先启动，生产者后启动)。消费者调用生产者服务的时候会报错：no provider avilable  xxx  locahost:9090.

**Comment by RedA1ert** [comment]
issue #2101 ,里面也提到这个问题。

**Comment by steverao** [comment]
> issue #2101 ,里面也提到这个问题。

确定注册中心中服务提供者的实例信息是有的是吗？

**Comment by RedA1ert** [comment]
> 
是的 ，确认过。服务提供者的实例是存在的

**Comment by steverao** [comment]
> > 
> 
> 是的 ，确认过。服务提供者的实例是存在的

这个地方可能还是有些问题，我们也在后续2021.0.1.0版本中移除了相关组件并不建议在生产场景继续使用Spring Cloud Dubbo组件了，详细讨论可见#2398

**Comment by steverao** [comment]
具体no provider原因可以通过下面链接排查一下: https://mp.weixin.qq.com/s/cktptv62chtkmscZQCNCfQ
