### ISSUE TITLE
Can you register a service in more than one namespace？

### ISSUE THREAD

**Issue by mdh304045885** [alibaba/spring-cloud-alibaba#2602]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by misselvexu** [comment]
Multiple namespace registration is not currently supported and is not expected to be supported in the future .

**Comment by steverao** [comment]
We don't support now, but you can describe your demand more and we evaluate the feasibility.
By the way, please write more specific description about your problem when you create an issue, it can be more effective, otherwise we will close your issue directly next time.

**Comment by Triagen** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已收到，谢谢您的来信！
