### ISSUE TITLE
[Seata]Add Seata relevant docs 

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2610]
1.Add Seata relevant docs to spring-cloud-alibaba-docs module, we will update it in Spring Cloud Alibaba [official docs](https://spring-cloud-alibaba-group.github.io/github-pages/2021/en-us/index.html).
2.You can refer to [Seata readme.md](https://github.com/alibaba/spring-cloud-alibaba/tree/2.2.x/spring-cloud-alibaba-examples/seata-example) content to make it.
3.Please complete Chinese and English version together.

**Comment by kaori-seasons** [comment]
I want to try it, I will need to investigate the seata module recently

**Comment by mahi072** [comment]
Hi @steverao, I would like to work on this.
I started exploring the seata module recently.
Please guide me through this.

**Comment by steverao** [comment]
Now we just modified in branch of 2.2.x, and we should create a same PR to branch of 2021.x.

**Comment by fszhang1998** [comment]
I want to have a try, and I am starting to expore it.

**Comment by fszhang1998** [comment]
I want to have a try, and I am starting to expore it.

**Comment by steverao** [comment]
It's solved.
