### ISSUE TITLE
extension-configs 无法正确读取yaml共享配置问题 

### ISSUE THREAD

**Issue by pkaq** [alibaba/spring-cloud-alibaba#2616]
使用extension-configs配置读取共享yaml文件
由于需要使用condition接口进行判断  在match方法中使用context.getEnvironment().getProperty（“ a.b.c ”）
断点发现propertysources会把配置逐行拆解为a,b,c三个 从而导致无法用的方式读取 而使用properties格式没有问题

已经可以确认是
1.配置肯定没问题 只要nacos中格式改成properties立马可以
2.file-extension: yaml 已经配置为 yaml
3.已经添加snakeyaml依赖

使用的spring boot ， cloud， nacos版本均为最新版 ，JDK11

```yaml
a:
    b:
         c: xxx
```

NacosDataParserHandler.getInstance().parseNacosData(dataId, data,fileExtension) 之后 yaml内容就成了逐行解析的内容了
另外看来file-extension并未生效

![1](https://user-images.githubusercontent.com/4537450/174806150-04184953-243b-4c33-b1ed-ac3a6f5950c5.png)
![2](https://user-images.githubusercontent.com/4537450/174806153-d720ce68-9574-423a-8325-1a194c9eb44a.png)
![3](https://user-images.githubusercontent.com/4537450/174806133-863c1738-89b2-4e43-98e0-d2cc9b98e364.png)

**Comment by pkaq** [comment]
问题已经解决 但是不妨碍这个bug的奇葩性质

解决方式为 克隆一份dataid为 a  的配置 重命名为 a.yaml， 然后 extension-config 中配置 a.yaml 后可以正常读取

我裂开了

**Comment by yuhuangbin** [comment]
请提供更多详细信息，如详细版本，配置属性等，能否提供一个简易能复现的`demo project`便于我们确认？

**Comment by pkaq** [comment]
依赖情况
```properties
spring_dep=1.0.11.RELEASE
spring_boot_ver=2.7.0
alibaba=2021.1
cloud=2021.0.3
bootstrap=3.1.3
```

```gradle
 // web
  "web" : "org.springframework.boot:spring-boot-starter-web",
  "undertow" : "org.springframework.boot:spring-boot-starter-undertow",
  // spring cloud
  "cloud": "org.springframework.cloud:spring-cloud-dependencies:${cloud}",
  "cloud_bootstrap": "org.springframework.cloud:spring-cloud-starter-bootstrap:${bootstrap}",
  "alibaba":"com.alibaba.cloud:spring-cloud-alibaba-dependencies:${alibaba}",
  // nacos 注册 配置中心
  "nacos_config":"com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config",
  "nacos_client":"com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery",
```

JDK是openjdk11 配置中心是2.1.0的docker版

**Comment by yuhuangbin** [comment]
参考wiki版本说明进行使用，你这个可能是版本不匹配导致有问题？

**Comment by pkaq** [comment]
类似的问题在SCA和nacos的issue有很多 这种奇葩的解决方式也是蒙出来的 感觉不是版本问题

**Comment by yuhuangbin** [comment]
> 类似的问题在SCA和nacos的issue有很多 这种奇葩的解决方式也是蒙出来的 感觉不是版本问题

如你觉得不是版本不匹配导致问题，还请提供能复现问题的 `sample project`, 以便我们更好的确认

**Comment by yuhuangbin** [comment]
如果是通过`spring.cloud.nacos.config.fileExtension` 没应用到 `extensionConfigs` 配置上，可以在配置dataid时增加后缀，
或使用`2.2.8.RELEASE` 通过 `spring.cloud.nacos.config.extensionConfigs.fileExtension=yaml`来设置文件后缀.

建议使用按照对应example工程样例进行使用

**Comment by pkaq** [comment]
> 如果是通过`spring.cloud.nacos.config.fileExtension` 没应用到 `extensionConfigs` 配置上，可以在配置dataid时增加后缀， 或使用`2.2.8.RELEASE` 通过 `spring.cloud.nacos.config.extensionConfigs.fileExtension=yaml`来设置文件后缀.
> 
> 建议使用按照对应example工程样例进行使用

配置中心的yml格式配置文件dataid如果不加后缀 那么通过extension-configs配置的时候强行添加.yaml后缀 完全读取不到任何配置 所以只能配置中心的dataid和客户端的配置都带上后缀
