### ISSUE TITLE
About loading configuration files with group

### ISSUE THREAD

**Issue by liutongking** [alibaba/spring-cloud-alibaba#2617]
If I have many configuration files, can I specify a group to load all the configuration files under this group
> 如果我有很多配置文件，那么可不可以指定group去加载这个组下面的所有配置文件呢

**Comment by steverao** [comment]
Do you mean whether there is a way to load all config files from Nacos only by setting the group property?

**Comment by liutongking** [comment]
> Do you mean whether there is a way to load all config files from Nacos only by setting the group property?

Yes, pull all configuration files under group according to namespace and group

**Comment by steverao** [comment]
> > Do you mean whether there is a way to load all config files from Nacos only by setting the group property?
> 
> Yes, pull all configuration files under group according to namespace and group

We don't support the feature now. you can describe the demand and we evaluate effectiveness.

**Comment by li-xiao-shuang** [comment]
> > Do you mean whether there is a way to load all config files from Nacos only by setting the group property?
> 
> Yes, pull all configuration files under group according to namespace and group

I think it is also possible to implement this by yourself, through NacosConfigManager

**Comment by liutongking** [comment]
> > > Do you mean whether there is a way to load all config files from Nacos only by setting the group property?
> > 
> > 
> > Yes, pull all configuration files under group according to namespace and group
> 
> We don't support the feature now. you can describe the demand and we evaluate effectiveness.

OK, I see. Thank you

**Comment by liutongking** [comment]
> > > Do you mean whether there is a way to load all config files from Nacos only by setting the group property?
> > 
> > 
> > Yes, pull all configuration files under group according to namespace and group
> 
> I think it is also possible to implement this by yourself, through NacosConfigManager

Uh huh, I'm going to write one myself
