### ISSUE TITLE
rocketmq config item spring.cloud.stream.rocketmq.binder.access-channe is not  working

### ISSUE THREAD

**Issue by yingwu** [alibaba/spring-cloud-alibaba#2619]
**Which Component**
RocketMq

**Describe the bug**
I set spring.cloud.stream.rocketmq.binder.access-channe = CLOUD ,
but when produce/consume message from Aliyun RocketMqService , message trace is not working.

**Expected behavior**
目前 "查询消息轨迹" 没有只有发送数据, 接收和消费都是空白的, 希望能正常看到消息轨迹.

**Additional context**
e.g.  Windows10  、Java11 、 Version 2.2.7.RELEASE

**Comment by sollhui** [comment]
We'll solve it，and will feedback to you when we finish.

**Comment by yuhuangbin** [comment]
refer: `RocketMQConsumerFactory#initPushConsumer`. And need to set this configuration item.
