### ISSUE TITLE
Questions about version 2.2.8

### ISSUE THREAD

**Issue by yisirman** [alibaba/spring-cloud-alibaba#2623]
After we tried to upgrade springcloud Alibaba, we found that Dubbo(spring-cloud-starter-dubbo) was missing, What is the corresponding Dubbo version of this version ?

**Comment by shuangpai** [comment]
以后不会再有了，可以引入dubbo3.0  dubbo不要挂载在cloud上  api层面注册到dubbo一份 注册到cloud一份，实现gateway对api的调用

**Comment by yisirman** [comment]
> 以后不会再有了，可以引入dubbo3.0 dubbo不要挂载在cloud上 api层面注册到dubbo一份 注册到cloud一份，实现gateway对api的调用

So what are the advantages of this design?

**Comment by yisirman** [comment]
#2398
