### ISSUE TITLE
2.2.7.RELEASE版本nacos-client启动时异常

### ISSUE THREAD

**Issue by ipanocloud** [alibaba/spring-cloud-alibaba#2625]
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at com.alibaba.nacos.client.naming.cache.ConcurrentDiskUtil.getFileContent(ConcurrentDiskUtil.java:93)

**Comment by ipanocloud** [comment]
com.alibaba.nacos.client.naming.cache.ConcurrentDiskUtil#getFileContent(java.io.File, java.lang.String)
`ByteBuffer byteBuffer = ByteBuffer.allocate(fileSize);
            fcin.read(byteBuffer);
            byteBuffer.flip();
            return byteBufferToString(byteBuffer, charsetName);`

**Comment by ipanocloud** [comment]
类似解决方案: https://www.jianshu.com/p/8f219d981aa9

**Comment by yuhuangbin** [comment]
如果是高版本JDK兼容性问题，请提交issue给Nacos 社区。
