### ISSUE TITLE
如何知道自己本机的 InstanceId ？

### ISSUE THREAD

**Issue by l42111996** [alibaba/spring-cloud-alibaba#2637]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
使用 spring cloud nacos，如何知道自己本机的 InstanceId ？

**Comment by sollhui** [comment]
1.可以使用 访问指定路径/nacos/v1/ns/instance/list？参数名称=参数值的方式获得 例如：curl -X GET '127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=XXX'
2.
 private LoadBalancerClient loadBalancerClient;

 ServiceInstance instance = loadBalancerClient.choose("本机实例的服务名称");
 instance.getServiceId()；

**Comment by steverao** [comment]
Please explain more about the "InstanceId".

**Comment by steverao** [comment]
Long time without response and close.
