### ISSUE TITLE
Want to update Spring Cloud Alibaba : 2021.0.1.0  - Seata-1.4.2 ->>1.5.1 

### ISSUE THREAD

**Issue by edifangyi** [alibaba/spring-cloud-alibaba#2639]
Spring Cloud Alibaba Version:2021.0.1.0  -> Seata Version:1.4.2

but Seata 1.4.2 have “1.4.2及以下版本回滚时抛出Cannot construct instance of `java.time.LocalDateTime` ？”

Want to update Spring Cloud Alibaba Version:2021.0.1.0 - Seata 1.4.2 -> 1.5.1

**Comment by sollhui** [comment]
we'll discuss it

**Comment by kaori-seasons** [comment]
A version upgrade might be a good idea, but I would suggest a project using ``` TemporalQuery``` as an intermediary class to ```JSR-310```'s temporal classes in another scenario for [example](https://github.com/smallrye/smallrye-graphql/blob/1003b9ac14f61796c800fed07ebb7803bcd000ee/server/implementation/src/main/java/io/smallrye/graphql/transformation/DateTransformer.java)

At my suggestion, the discussion of IntervalShardingAlgorithm in ```apache/shardingsphere```'s database sharding has achieved great success, and sharding also supports ```seata ```transactions

refer to [Add support for more JSR-310 related classes in IntervalShardingAlgorithm](https://github.com/apache/shardingsphere/issues/17752)

**Comment by kaori-seasons** [comment]
The FAQ can be viewed through communication with the seata community
https://seata.io/en-us/docs/overview/faq.html#39

**Comment by edifangyi** [comment]
> The FAQ can be viewed through communication with the seata community https://seata.io/en-us/docs/overview/faq.html#39
I don't know why，service version number not the same

![0($K0T0RS48W{CO~`V$S7I7](https://user-images.githubusercontent.com/12421552/178179117-bf9134f3-f14c-4eed-8393-898fd6d9dbae.png)

**Comment by steverao** [comment]
You can update the module of Seata by yourself first and we will update the module in the next release.
