### ISSUE TITLE
如何处理restful风格的接口重复创建资源

### ISSUE THREAD

**Issue by hlcen66** [alibaba/spring-cloud-alibaba#2640]
/api/order/{orderid}

这种如何处理啊，我的是最新版的sentinel。

没有WebCallbackManager，只有WebFluxCallbackManager。

具体怎么实现呢，有没有人指导一下。

**Comment by sollhui** [comment]
you can refer https://github.com/alibaba/Sentinel/wiki/%E4%B8%BB%E6%B5%81%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%82%E9%85%8D#spring-webflux，which have different between WebCallbackManager and WebFluxCallbackManager
