### ISSUE TITLE
spring gateway + sentinel 是否支持form表单字段限流？？？

### ISSUE THREAD

**Issue by wangkang-ARM** [alibaba/spring-cloud-alibaba#2641]
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/64467312/177996578-118344ff-4e82-4a8e-9633-cf836a78866e.png">

**Comment by sollhui** [comment]
spring gateway + sentinel 是可以对针对热点参数限流或者针对head的某个字段限流的。

**Comment by wangkang-ARM** [comment]
参数是以form表单数据提交的，不在header中；

针对热点参数限流是要自己扩展SPI吗？如果不是sentinel控制哪里可以配置通过form表单中数据限流？
现在控制台只有ip host header url参数 cookie 没有form表单

**Comment by kaori-seasons** [comment]
通过sentinel dashboard配置热点参数 可以参考这里的实践

https://in4k.xyz/141123/spring-cloud-alibaba-sentinel%E4%B9%8B%E7%83%AD%E7%82%B9%E5%8F%82%E6%95%B0%E9%99%90%E6%B5%81%E7%AF%87

也可以通过如下demo拓展spi

https://sentinelguard.io/zh-cn/docs/parameter-flow-control.html
