### ISSUE TITLE
RocketMQ Example doc overview pic missing

### ISSUE THREAD

**Issue by TrevorLink** [alibaba/spring-cloud-alibaba#2642]
**Which Component**
RocketMQ Example
**Describe the bug**
When introducing the RocketMQ with Spring Cloud Stream ,the markdown doc contains a pic which shows the overview architechture design of Spring Cloud Stream, the url of the pic (refers to Spring.io)seems have changed location so there is no pic now for the doc of the example

The original url : `https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/images/SCSt-overview.png`

**To Reproduce**
1. Go to `spring-cloud-alibaba/spring-cloud-alibaba-examples/rocketmq-example/readme.md` or the `readme-zh.md`
2. See the missing pic

**Screenshots**
![](https://my-img-1.oss-cn-hangzhou.aliyuncs.com/image-20220709220529585.png)

**Comment by sollhui** [comment]
we'll fix it
