### ISSUE TITLE
spring cloud alibaba rocketmq example timeout not working

### ISSUE THREAD

**Issue by nzb15555196162** [alibaba/spring-cloud-alibaba#2644]
**Which Component**
rocketmq

**Describe the bug**
spring cloud rocketmq example, send message with timeout not working. 

**To Reproduce**
1. use spring cloud rocketmq send message demo
2. use customize timeout
3. timeout not working

**Expected behavior**
timeout should work

**Screenshots**
![springcloudalibaba](https://user-images.githubusercontent.com/18350673/178128284-17106bb8-f043-45e7-a9d2-3091b201ff63.gif)

**Additional context**
this should be spring-integration-core module AbstractSubscribableChannel.class doSend(Message<?> message, long timeout) bug, parameter timeout not use, when i debug 
e.g.  MacOS  、Java11 、 spring cloud ablibab master

**Comment by Sorieee** [comment]
I will check it.

**Comment by Sorieee** [comment]
Which version do you use?

**Comment by Sorieee** [comment]
Timeout is not supported by Spring intergration, you can create issue to [SpringIntergration](https://github.com/spring-projects/spring-integration).
![image](https://user-images.githubusercontent.com/8654292/178135206-05e9449d-1d10-46a6-80ff-8dc7b6244700.png)

**Comment by Sorieee** [comment]
Plz close this issue.
