### ISSUE TITLE
sentinel中SentinelBeanPostProcessor，在一些特殊情况下，导致一些bean被提前创建

### ISSUE THREAD

**Issue by zz-zhi54** [alibaba/spring-cloud-alibaba#2651]
Sentinelbeanpostprocessor of sentinel caused the sequence of the whole spring lifecycle to be broken

## Issue Description

Sentinelbeanpostprocessor of sentinel caused the sequence of the whole spring lifecycle to be broken

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
您好， 我在使用sharding - jdbc时候发现有一个问题。导致datasource在registerBeanPostProcessors(beanFactory);还没有处理完，就已经实例化了。 问题在 https://github.com/apache/shardingsphere/issues/18966 中。 
SentinelAutoConfiguration中sentinelBeanPostProcessor后置处理器 ， 加载时创建bean SentinelAutoConfiguration 会导致mbd.getFactoryBeanName();不为空，	factoryBean = this.beanFactory.getBean(factoryBeanName);被加载  然后初始化这个bean ，初始化这个bean时里面会经过一个叫methodvalidationpostprocessor的后置处理器。然后我们自定义了一个  Bean   public Validator validator()。导致我们自定义的Configuration也会被加载。而我们自定义的Configuration中有使用 Autowired引入了一个bean，这个bean又依赖了datasource，并把datasource也getBean。导致datasource在后置处理器之前实例化。 
![image](https://user-images.githubusercontent.com/85894494/178663007-02481932-317a-4cc6-aaa0-7c3ddac24993.png)

在https://gitlab.com/poo0054/test    中有一个案例
> @Bean public static SentinelBeanPostProcessor sentinelBeanPostProcessor
使用静态，mbd.getFactoryBeanName()就是一个空。不知道这样是否可行

### Describe what you expected to happen
SentinelAutoConfiguration不会在后处理器（registerBeanPostProcessors(beanFactory);）还没加载完之前。把这个bean实例化了

### How to reproduce it (as minimally and precisely as possible)
在gitlab地址中
>https://gitlab.com/poo0054/test

### Tell us your environment
    <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.2.5.RELEASE</version>
        </dependency>

  <parent>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-alibaba-starters</artifactId>
    <version>2.2.5.RELEASE</version>
  </parent>

**Comment by DanielLiu1123** [comment]
fixed, see #2654
