### ISSUE TITLE
When will Spring Boot 3.x be supported？

### ISSUE THREAD

**Issue by mars05** [alibaba/spring-cloud-alibaba#2653]
Spring Cloud 2022.x and Spring Boot 3.x have milestone versions available. When will spring-cloud-alibaba support it?

**Comment by 201206030** [comment]
I want to know too

**Comment by DanielLiu1123** [comment]
Spring Boot will release 3.x at the end of this year, so not particularly urgent. Need discuss.

**Comment by mars05** [comment]
@DanielLiu1123 When will this [commit ](https://github.com/alibaba/spring-cloud-alibaba/commit/88326fb17af2b111d47377e6e43a4ffcc9c77332)be released？

**Comment by DanielLiu1123** [comment]
> @DanielLiu1123 When will this [commit ](https://github.com/alibaba/spring-cloud-alibaba/commit/88326fb17af2b111d47377e6e43a4ffcc9c77332)be released？

Next version base on Spring Cloud 2021, 2021.0.1.1

**Comment by steverao** [comment]
We received this issues and discuss it later, but we don't suggest to use latest spring boot release in production environment.

**Comment by mars05** [comment]
> > @DanielLiu1123 When will this [commit ](https://github.com/alibaba/spring-cloud-alibaba/commit/88326fb17af2b111d47377e6e43a4ffcc9c77332)be released？
> 
> Next version base on Spring Cloud 2021, 2021.0.1.1

When will 2021.0.1.1 be released

**Comment by steverao** [comment]
> > > @DanielLiu1123 When will this [commit ](https://github.com/alibaba/spring-cloud-alibaba/commit/88326fb17af2b111d47377e6e43a4ffcc9c77332)be released？
> > 
> > 
> > Next version base on Spring Cloud 2021, 2021.0.1.1
> 
> When will 2021.0.1.1 be released

We release a new version in about 2~3 months.
