### ISSUE TITLE
SentinelAutoConfiguration is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by jackli0909** [alibaba/spring-cloud-alibaba#2655]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-starter-alibaba-sentinel

**Describe the bug**
[Bean 'com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration' of type [com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)]

**To Reproduce**
Import spring-cloud-starter-alibaba-sentinel(2.2.7.RELEASE) to my project ,when starting,it  SentinelAutoConfiguration，and SentinelProperties is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) message show in log

**Screenshots**

**Additional context**
Java8 、 Version 2.2.7.RELEASE

**Comment by DanielLiu1123** [comment]
Will fix the warning in next version.

**Comment by DanielLiu1123** [comment]
fixed, see #2654
