### ISSUE TITLE
When is the SpringCloudAlibaba2021.x will start to support Nacos2.x ?

### ISSUE THREAD

**Issue by zondacker** [alibaba/spring-cloud-alibaba#2656]
When is the SpringCloudAlibaba2021.x will start to support Nacos2.x ?

**Comment by DanielLiu1123** [comment]
Maybe the next version.

**Comment by JavaLionLi** [comment]
> Maybe the next version.

When will the next version be released

**Comment by steverao** [comment]
> > Maybe the next version.
> 
> When will the next version be released

We plan to release a version in about 2 months.

**Comment by steverao** [comment]
> When is the SpringCloudAlibaba2021.x will start to support Nacos2.x ?

You can do it by yourself and create a PR to our project.
