### ISSUE TITLE
yml, sentinel dashboard setting not work

### ISSUE THREAD

**Issue by ehejhrj** [alibaba/spring-cloud-alibaba#2668]
## Issue Description

Type:  bug report

### Describe what happened (or what feature you want)

i use yml file to set spring.cloud.sentinel.transport port and dashboard, but it not worked.
Through breakpoints, i found used default port.

![QQ截图20220720153616](https://user-images.githubusercontent.com/21004646/179924512-460ab79f-4167-4b73-bc24-14649390bc27.png)

![QQ截图20220720162948](https://user-images.githubusercontent.com/21004646/179935667-03efd35e-5af6-472a-8a74-4abb014b56fb.png)

### Tell us your environment

jdk 11
spring-cloud-starter-alibaba-sentinel 2021.0.1.0
sentinel-dashboard-1.8.4

**Comment by DanielLiu1123** [comment]
Just configure the `spring.cloud.sentinel.transport.dashboard`, `spring.cloud.sentinel.transport.port` is not for dashboard but `CommandCenter`.

**Comment by 15549335402** [comment]
不知道能否解决你的问题，如果你通过yml配置的方式去连接sentinel控制台，那么你的接入端就不能有代码相关的配置，例如你的initRules方法，你把这些代码注释掉，再启动看看，在服务启动的时候通过的第一次访问应该就可以了。
