### ISSUE TITLE
A way to customize Nacos XML parser

### ISSUE THREAD

**Issue by KerwinAusten** [alibaba/spring-cloud-alibaba#2678]
**Which Component**
Nacos Config

**Is your feature request related to a problem? Please describe.**
The com.alibaba.cloud.nacos.parser.NacosXmlPropertySourceLoader class has a very simple parse logic. Now we want to implement a more complex logic for our business, but the NacosXmlPropertySourceLoader's order is 'Integer.MIN_VALUE' which means HIGHEST_ORDER so our class can't take effect.

**Describe the solution you'd like**
Change the NacosXmlPropertySourceLoader‘s order to 'Integer.MIN_VALUE + 100'  to make other class effect

**Additional context**
Spring Cloud Alibaba 2021.0.1.0
Nacos Client 1.4.3

**Comment by sollhui** [comment]
Maybe you can overwrite the method in your business is more effective

**Comment by steverao** [comment]
Please overwrite the class in your application.

**Comment by KerwinAusten** [comment]
> Please overwrite the class in your application.

@steverao @HHoflittlefish777 Could you make it clear? The NacosXmlPropertySourceLoader  is loaded in 'spring.factories', I have no idea to overwrite it.

Now I use javassist to rewrite the class, is there another way to do it？

**Comment by steverao** [comment]
> > Please overwrite the class in your application.
> 
> @steverao @HHoflittlefish777 Could you make it clear? The NacosXmlPropertySourceLoader is loaded in 'spring.factories', I have no idea to overwrite it.
> 
> Now I use javassist to rewrite the class, is there another way to do it？

You can delete the default bean object in spring container by BeanDefinitionRegistryPostProcessor and use your owe bean.
