### ISSUE TITLE
十万火急,  nacos在maven仓库中找不到 !!!!!

### ISSUE THREAD

**Issue by sukai-cheng** [alibaba/spring-cloud-alibaba#2688]
1.4.2 nacos下载不了
![image](https://user-images.githubusercontent.com/35868545/181679572-b6a0645e-194e-4508-ac70-58db62cc6f3e.png)

**Comment by GeWiier** [comment]
你可以把version删了 , 看的我有点着急

**Comment by sukai-cheng** [comment]
![image](https://user-images.githubusercontent.com/35868545/181682745-85097c08-460b-4325-a806-02ec716da008.png)

**Comment by sukai-cheng** [comment]
还是没用啊, 他喵的, 服了, 被mentor一顿劈头盖脸吧, 内部maven仓库降级中...,

**Comment by sukai-cheng** [comment]
劳资真的他喵的的想砍人

**Comment by sukai-cheng** [comment]
# 官方文档
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/35868545/181684218-3fa8ea94-aca7-4679-8d3f-7032c6d59ed1.png">

**Comment by sukai-cheng** [comment]
阿里云仓库

**Comment by lushihuan** [comment]
`<type>pom<type>`你是来搞笑的吧，不知所云...
