### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by hitcp** [alibaba/spring-cloud-alibaba#2701]
建议：包名在阿里Java开发手册里不是要求统一单数形式吗？

![image](https://user-images.githubusercontent.com/36216908/183430397-8645f5a1-b275-4f13-a9e2-5ce53a1e4149.png)

**Comment by steverao** [comment]
> 建议：包名在阿里Java开发手册里不是要求统一单数形式吗？
> 
> ![image](https://user-images.githubusercontent.com/36216908/183430397-8645f5a1-b275-4f13-a9e2-5ce53a1e4149.png)

这个是之前项目这块代码没严格遵守这块规范，现在已经改过来了。
