### ISSUE TITLE
在Springboot 版本是 2.6.6 的情况下，nacos 客户端 依赖的actuator 也需要升级。

### ISSUE THREAD

**Issue by lyhu** [alibaba/spring-cloud-alibaba#2704]
```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>

<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-actuator</artifactId>
     <version>2.6.6</version>
</dependency>
```

Springboot 版本是 2.6.6 的情况下，报下面异常，希望 nacos client 能升级下 springboot 版本。

```
 java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorAutoConfiguration
```

**Comment by yunwz** [comment]
[官方文档](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x)版本支持说明：
> 2021.x branch: Corresponds to Spring Cloud 2021 & Spring Boot 2.6.x. JDK 1.8 or later versions are supported.
升级你的spring-cloud-alibaba，使用2021.x版本而不是2.2.x版本。

**Comment by steverao** [comment]
Please refer to the [Release Notes](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E), for Spring Boot 2.6.x, we provide relevant SCA release.

**Comment by lyhu** [comment]
> Please refer to the [Release Notes](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E), for Spring Boot 2.6.x, we provide relevant SCA release.

ok，问题已经解决。3ks

**Comment by Cilong** [comment]
> Please refer to the [Release Notes](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E), for Spring Boot 2.6.x, we provide relevant SCA release.
请问SCA2021版本 什么时候支持 nacos2.1呢
