### ISSUE TITLE
Seata starts by default

### ISSUE THREAD

**Issue by IvesQing** [alibaba/spring-cloud-alibaba#2707]
seata 会默认启动，配置设置为false也没有效果
Seata starts by default

 version: 
springcloudalibaba:2021.0.1.0

**Describe what problem you have encountered**
![image](https://user-images.githubusercontent.com/26543986/183867692-6d2fb542-973f-4371-9527-bc00bd84a362.png)
![image](https://user-images.githubusercontent.com/26543986/183867791-337a35dd-2c85-4c68-a882-2220c8d0ac1a.png)
![image](https://user-images.githubusercontent.com/26543986/183867914-6770da60-8639-411e-b538-d749b4f0d514.png)

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by steverao** [comment]
Could you provide a demo to help us to reproduce the problem? In our example of seata-example, we didn't encounter this problem.

**Comment by steverao** [comment]
Did you find the problem?
