### ISSUE TITLE
Spring Cloud Stream 支持 RocketMQ 能力重构方案

### ISSUE THREAD

**Issue by LeBW** [alibaba/spring-cloud-alibaba#2712]
# 背景
目前 RocketMQ 和 Spring Cloud Stream 整合度不够，没有充分利用到各自的特性，比如 Stream 相关 binding 配置项和 header 的处理，RocketMQ 资源开销优化和 pop 模式的支持等。因此本方案考虑从 Producer 复用、Consumer 复用、原生 header 配置支持等方面，对相关能力进行优化。
# 目标

1. 优化 Spring Cloud Stream 中 output binding 配置与 RocketMQ 中 Producer 的对应关系，使得配置多个 binding 时，可以复用同一个 Producer，从而减小资源开销。
1. 优化 Spring Cloud Stream 中 input binding 配置与 RocketMQ 中 Consumer 的对应关系，使得同一个订阅关系组可以订阅多个 topic，从而减小资源开销。
1. 优化对于 Message 中对原生 header 的利用，例如通过 header 的形式自定义序列化方式。
# 详细方案
## 1. 优化 output binding 与 Producer 的对应关系
在生产中，开发者往往通过 `streamBridge`的方式来使用 output binding，通过调用 `streamBridge.send(String bindingName, Object data)`来向 binding 发送消息。
这里 `streamBridge#send`的定义如下：
```java
public boolean send(String bindingName, Object data) {
	return this.send(bindingName, data, MimeTypeUtils.APPLICATION_JSON);
}
```
其中会根据 bindingName，向相应的 output binding 发送数据。
这里如果相应的 output binding 不存在的话，会根据 bindingName，创建一个新的 outputBinding，从而使得该方法可以支持动态目的地。相应的代码主要存在于 `StreamBridge.resolveDestination`函数中
```java
SubscribableChannel resolveDestination(String destinationName, ProducerProperties producerProperties) {
    // 首先从缓存里根据 bindingName 查找，是否存在该 binding
    SubscribableChannel messageChannel = this.channelCache.get(destinationName);
    // 如果不存在的话，需要新建该 output binding
    if (messageChannel == null && this.applicationContext.containsBean(destinationName)) {
        messageChannel = this.applicationContext.getBean(destinationName, SubscribableChannel.class);
        this.addInterceptors((AbstractMessageChannel) messageChannel);
    }
    if (messageChannel == null) {
        messageChannel = new DirectWithAttributesChannel();
        if (this.destinationBindingCallback != null) {
            Object extendedProducerProperties = this.bindingService
                .getExtendedProducerProperties(messageChannel, destinationName);
            this.destinationBindingCallback.configure(destinationName, messageChannel,
                                                      producerProperties, extendedProducerProperties);
        }
        // 创建 output binding 的主要逻辑就在这里
        this.bindingService.bindProducer(messageChannel, destinationName, false);
        this.channelCache.put(destinationName, messageChannel);
        this.addInterceptors((AbstractMessageChannel) messageChannel);
    }
    // 如果存在，直接返回该 messageChannel 即可
    return messageChannel;
}
```
在创建 output binding 时，会调用 `RocketMQMessageChannelBinder` 的 `createProducerMessageHandler `方法，在 binder 中创建一个 `RocketMQProducerMessageHandler`，这个 MessageHandler 会和刚才创建的 messageChannel 绑定，共同组成这个 output binding。
所以这里的逻辑是：

1. `streamBridge`在执行 send 逻辑时，根据 bindingName，判断是否存在相应 binding。如果存在的话，直接调用相应 messageChannel 的 send 即可；如果不存在的话，进入 2.
1. 根据 bindingName，新建一个 messageChannel，然后在 binder 中新建一个 `RocketMQProducerMessageHandler`，用来处理该 messageChannel 的发送请求。
1. 在创建 `RocketMQProducerMessageHandler` 的时候，会调用其中的 `onInit`方法，其中会调用 `RocketMQProduceFactory._initRocketMQProducer_(**destination**.getName(), **mqProducerProperties**)`方法，新建一个 RocketMQProducer

也就是说，每次创建一个 output binding 的时候，都会新建一个 RocketMQProducer。但是这个操作是比较消耗资源的，尤其是当 output binding 数量较多时，创建很多的 RocketMQProducer 并无必要，其实是可以复用 RocketMQProducer 的，因为同一个 RocketMQProducer，也可以向不同的 topic 发送消息，并且 RocketMQProducer 是线程安全的。
由于 RocketMQProducer 的创建利用了工厂模式，这里我们可以修改 `RocketMQProduceFactory._initRocketMQProducer_(**destination**.getName(), **mqProducerProperties**)`的逻辑，使得在某些情况下， RocketMQProducer 可以得到复用。

那么接下来的问题是：在何种情况下，RocketMQProducer 可以复用呢？
由于在配置 binding 时，我们可以配置不同的属性，只有在特定属性相同时，才能对 producer 进行复用。我们判断是否可以复用的属性有：

- group：生产者组名（不配置时，使用默认组名）
- nameServer：连接 RocketMQ 的 nameServer 地址
- sendMessageHook：发送消息的回调操作

只有当以上属性相同时，才能对 producer 进行复用。
在实现上，可以使用 Map 来缓存 producer，Map 的 key 为上述属性，value 为 producer 实例。

另外，由于每个 RocketMQProducerMessageHandler 都会调用 start 和 stop 等生命周期方法，并且在其中对 producer 进行启动和停止。在对 producer 进行复用后，为了保证功能正常执行，这里我们需要对 producer 进行封装，采用计数逻辑才处理 start 和 shutdown 方法，使得其正常作用。

**Comment by chen-junl** [comment]
第三点,优化针对消息中对原始 header 的利 用，例如通过 header 的形式自定义顺序化方式。
有解决方式吗?
