### ISSUE TITLE
feign+sentinel  warn more than one bean cleint  

### ISSUE THREAD

**Issue by IvesQing** [alibaba/spring-cloud-alibaba#2720]
![image](https://user-images.githubusercontent.com/26543986/185321334-abfa8e9d-19e3-474b-a8c0-c739ca950d5d.png)

### Describe what you expected to happen
1、引用了feign的client包后，idea警告提示more than one bean cleint  ，虽然可以加@Qualifier解决，能否有其他更友好方法

**Comment by steverao** [comment]
Did you use Spring Cloud Alibaba in your project? We didn't provide the class of upmTenantConfigFeignClientFallback in our project. Could you show your maven dependency?

**Comment by steverao** [comment]
Long time without response and close first.
