### ISSUE TITLE
why are nacos versions inconsistent?

### ISSUE THREAD

**Issue by sky-dawn** [alibaba/spring-cloud-alibaba#2735]
<nacos.client.version>2.1.0</nacos.client.version>
<nacos.config.version>0.8.0</nacos.config.version>

**Comment by helloichen** [comment]
Which version of springcloud alibaba is it? Dependency in which component? Please provide more information.

**Comment by steverao** [comment]
> <nacos.client.version>2.1.0</nacos.client.version> <nacos.config.version>0.8.0</nacos.config.version>

Because, we don't use `<nacos.config.version>0.8.0</nacos.config.version>` actually and update it's version. we will delete relevant properties, dependency and code.

**Comment by steverao** [comment]
I deleted `<nacos.config.version>0.8.0</nacos.config.version>`.
