### ISSUE TITLE
nacos config 控制台修改 spring.cloud.nacos.discovery.metadata 导致 com.alibaba.cloud.nacos.registry.NacosRegistrationCustomizer 初始化的值丢失

### ISSUE THREAD

**Issue by galaxy-sea** [alibaba/spring-cloud-alibaba#2736]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Nacos Config

**Describe the bug**

nacos 控制台修改 spring.cloud.nacos.discovery.metadata 导致 com.alibaba.cloud.nacos.registry.NacosRegistrationCustomizer#customize 初始化的值丢失

大概就是
com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration#onNacosDiscoveryInfoChangedEvent  没有去调用 com.alibaba.cloud.nacos.registry.NacosRegistrationCustomizer

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 2021.0.1.0.RELEASE

**Comment by galaxy-sea** [comment]
目前重新编译2021.X (2021.0.1.1-SNAPSHOT)进行测试, 

1. nacos config 控制台修改 spring.cloud.nacos.discovery.metadata , Java程序保留了NacosRegistrationCustomizer 初始化进去的参数,  但是nacos discovery控制台 展示的元数据与Java程序展示的元数据 不一致

**Comment by steverao** [comment]
We don't support to do that.
