### ISSUE TITLE
spring-cloud-bus整合rocketmq 无法消费自定义的事件

### ISSUE THREAD

**Issue by guzongbo** [alibaba/spring-cloud-alibaba#2742]
**问题：**

服务A作为发起方可以创建本地事件，并发送消息到rocketmq，消费端也可以接收消息,但是无法将接收到的消息关联本地事件监听

**简单打个断点:**

在 ```org.springframework.cloud.bus.BusConsumer.accept(RemoteApplicationEvent event)```  添加断点，event参数类型是```UnknownRemoteApplicationEvent```

**对比rabbitMq:**
一模一样的代码 将实现类从 ```spring-cloud-starter-bus-rocketmq``` 切换到 ```spring-cloud-starter-bus-amqp``` 问题就解决了

[我创建的测试项目](https://github.com/skylarkn/test-sca-bus)

**Comment by pumbf** [comment]
我也遇到这个问题，初步判断是序列化反序列化没走同一个Converter。
反序列化 从Message<?> 反序列化 payload 是走 BusJacksonAutoConfiguration.BusJacksonMessageConverter。但是BusJacksonMessageConverter转换到指定子类是依赖RemoteApplicationEvent里的注解@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")。但反序列化是Message里payload发现没有type值。故Jackson无法将其转换成自定义事件。
关键代码处 
BusJacksonAutoConfiguration.BusJacksonMessageConverter#convertFromInternal(179)

**Comment by pumbf** [comment]
springboot版本：2.6.11
springcloud版本：2021.0.3
springcloudalibaba版本：2021.0.1.0

**Comment by sollhui** [comment]
hi @pumbf @skylarkn ，if you have some idea to solve it, welcome to create pull request.If not,we will solve it later.

**Comment by pumbf** [comment]
> hi @pumbf @skylarkn ，if you have some idea to solve it, welcome to create pull request.If not,we will solve it later.

hi , i found the reason. Because s-c-b-rocketmq will create MappingFastJsonMessageConverter. it will replace ApplicationJsonMessageMarshallingConverter to convert the message. so "type"  property will not exist

**Comment by pumbf** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/16176243/189051580-4c8343e2-893c-490d-a5ea-b1cc2843157d.png">

core method:
SimpleFunctionRegistry.FunctionInvocationWrapper::convertOutputMessageIfNecessary

**Comment by pumbf** [comment]
temporarily solve this problem by overriding the bean and removing the FastJsonConverter. @skylarkn 
```java
 /**
     * fix issue https://github.com/alibaba/spring-cloud-alibaba/issues/2742
     * @return  CompositeMessageConverter
     */
    @Bean(RocketMQMessageConverter.DEFAULT_NAME)
    public CompositeMessageConverter rocketMqMessageConvert() {
        Set<MessageConverter> messageConverters = new HashSet();
        ByteArrayMessageConverter byteArrayMessageConverter = new ByteArrayMessageConverter();
        byteArrayMessageConverter.setContentTypeResolver((ContentTypeResolver)null);
        messageConverters.add(byteArrayMessageConverter);
        messageConverters.add(new StringMessageConverter());
        return new CompositeMessageConverter(messageConverters);
    }
```

**Comment by Sorieee** [comment]
Plz keep open util I check 2.2.x.

**Comment by dream0708** [comment]
还是不行
