### ISSUE TITLE
ParamFlowRule类找不到

### ISSUE THREAD

**Issue by duguxiaobiao** [alibaba/spring-cloud-alibaba#2744]
springboot版本：2.3.12.RELEASE
springcloud版本：Hoxton.SR12
springcloudalibaba版本：2.2.7.RELEASE

项目启动提示：

Error creating bean with name 'sentinel-json-param-flow-converter' defined in class path resource [com/alibaba/cloud/sentinel/custom/SentinelAutoConfiguration$SentinelConverterConfiguration$SentinelJsonConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.cloud.sentinel.datasource.converter.JsonConverter]: Factory method 'jsonParamFlowConverter' threw exception; nested exception is java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/slots/block/flow/param/ParamFlowRule

提示 ParamFlowRule类找不到

**Comment by steverao** [comment]
Please provide your dependency information, it seems miss relevant dependencies.

**Comment by steverao** [comment]
Long time without response and close first.
