### ISSUE TITLE
The old dingtalk group is full. Are there any new groups

### ISSUE THREAD

**Issue by demoManito** [alibaba/spring-cloud-alibaba#2760]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/27986239/189641656-ddb6424f-6fde-4199-b367-0a9e447d2153.png">

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by steverao** [comment]
Please add dingtalk group: 2415000986.
