### ISSUE TITLE
The official recommanded version dependencies is wrong

### ISSUE THREAD

**Issue by fromXin** [alibaba/spring-cloud-alibaba#2761]
**Which Component**
Nacos Discovery

**Describe the bug**
NacosException: Client not connected,current status:STARTING

**To Reproduce**
1. using SpringCloud (Hoxton.SR12)+Springboot(2.3.12.RELEASE)+Spring Cloud Alibaba(2.2.7.RELEASE) to create a spring cloud project.
2. using spring-cloud-starter-alibaba-nacos-discovery.
3. start the project.
4. See error.

**Why I'm sure**
I change the version of Spring Cloud Alibaba to 2.2.6.RELEASE (just rewrite the configuration of <dependencyManagement> in the pom.xml), and then, the error was gone. Everything be ok.

**Comment by cevencheng** [comment]
Which version of `nacos` server are you using ?
I guess it's likely that your client's version doesn't match the Nacos server. You can see below
![image](https://user-images.githubusercontent.com/2274720/189802798-09a173c9-e6a8-43d3-b71c-df13faf59147.png)

**Comment by fromXin** [comment]
Thanks for your reply.
I'm using the nacos server of version 2.0.3 just like the image.
I used docker to deploy the nacos server, the version of docker image is 2.0.3.

And I can see the version info in the console of nacos:

About my client version. I use dependency management like this:

And use dependency of discovery like this:

Before, I use the 2.2.7.RELEASE version of&nbsp;spring-cloud-alibaba-dependencies
But it didn't work well.
So I change the version, and it's done.
I find the solution in&nbsp;https://blog.csdn.net/qq_46122292/article/details/125185138?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125185138%22%2C%22source%22%3A%22qq_46122292%22%7D.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] The official recommanded version dependencies is wrong (Issue #2761)





 
Which version of nacos server are you using ?
 I guess it's likely that your client's version doesn't match the Nacos server. You can see below

**Comment by cevencheng** [comment]
> Thanks for your reply. I'm using the nacos server of version 2.0.3 just like the image. I used docker to deploy the nacos server, the version of docker image is 2.0.3. And I can see the version info in the console of nacos: About my client version. I use dependency management like this: And use dependency of discovery like this: Before, I use the 2.2.7.RELEASE version of&nbsp;spring-cloud-alibaba-dependencies But it didn't work well. So I change the version, and it's done. I find the solution in&nbsp;https://blog.csdn.net/qq_46122292/article/details/125185138?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125185138%22%2C%22source%22%3A%22qq_46122292%22%7D.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/spring-cloud-alibaba" ***@***.***&gt;; 发送时间:&nbsp;2022年9月13日(星期二) 中午11:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] The official recommanded version dependencies is wrong (Issue #2761) Which version of nacos server are you using ? I guess it's likely that your client's version doesn't match the Nacos server. You can see below — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I will try it tomorrow, and then reply you .

**Comment by cevencheng** [comment]
I using SpringCloud (Hoxton.SR12)+Springboot(2.3.12.RELEASE)+Spring Cloud Alibaba(2.2.7.RELEASE) every thing is ok .  Here is my screenshot 。

You can refer to my example project 
https://github.com/cevencheng/sca-demo

![image](https://user-images.githubusercontent.com/2274720/190089781-88b1f90e-ecf2-422c-a2be-4d331e819c79.png)

**Comment by fromXin** [comment]
Thanks for advising.
I boot the porject you provide, with my nacos server and seata server of docker container.
Eyerything is ok. But I update my project's pom as yours, it's still report the same error.
It's strange.
Anyway, I will use your project to finish my demo.
Thanks for your help.
