### ISSUE TITLE
nacos做配置中心 @value获取不到配置中心配置文件的值

### ISSUE THREAD

**Issue by XiLuoJun** [alibaba/spring-cloud-alibaba#2764]
https://github.com/alibaba/nacos/issues/9123#issue-1368974991
原帖指路，希望路过的大佬来看看

网上的方法也试过，加了bootstrap的依赖也没效果

somebody，who can help me？

**Comment by yuhuangbin** [comment]
使用demo参考示例项目[nacos-config-example](https://github.com/alibaba/spring-cloud-alibaba/tree/2.2.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example)

**Comment by yuhuangbin** [comment]
prefix + fileExtend

**Comment by TrevorLink** [comment]
@Value中key的名称和实际配置文件的key不一致，@Value取的是hero.name，实际上配置文件里key是lbw.name，导致Bean没有初始化
还有就是配置文件的DataID需要包含文件后缀的，没有后缀获取不到配置文件
具体可以参考 [Nacos Spring Cloud 使用文档](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html)

**Comment by lwx314781** [comment]
我是用最新版的2.2.8版本，外部tomcat，按照文档操作，无法获取，直接报错

**Comment by XiLuoJun** [comment]
> @value中key的名称和实际配置文件的key不一致，@value取的是hero.name，实际上配置文件里key是lbw.name，导致Bean没有初始化 还有就是配置文件的DataID需要包含文件后缀的，没有后缀获取不到配置文件 具体可以参考 [Nacos Spring Cloud 使用文档](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html)

感谢大佬，经过修改，能够注入了，之前更换版本之后，发现还不行，创建了几个新的配置文件，后续反复修改之后，忽略了属性值这里的没有变更。

**Comment by XiLuoJun** [comment]
> 

嗯嗯，大佬niubility
