### ISSUE TITLE
Improve Nacos examples docs

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2799]
In configuration items, there are inconsistent between [nacos examples readme.md](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example) and [nacos user's docs](https://spring-cloud-alibaba-group.github.io/github-pages/2021/zh-cn/index.html#_%E5%A6%82%E4%BD%95%E5%BC%95%E5%85%A5_nacos_discovery_%E8%BF%9B%E8%A1%8C%E6%9C%8D%E5%8A%A1%E6%B3%A8%E5%86%8C%E5%8F%91%E7%8E%B0).
Such as, in users' docs, it show how to close Nacos Watch by `spring.cloud.nacos.discovery.watch.enabled`, but there isn't in nacos examples readme.md.
We need they are consistent.

**Comment by pandaapo** [comment]
By the way, [nacos user's docs](https://spring-cloud-alibaba-group.github.io/github-pages/2021/zh-cn/index.html#_%E5%A6%82%E4%BD%95%E5%BC%95%E5%85%A5_nacos_discovery_%E8%BF%9B%E8%A1%8C%E6%9C%8D%E5%8A%A1%E6%B3%A8%E5%86%8C%E5%8F%91%E7%8E%B0) lacks these items compared to [readme.md](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example): `ribbon.nacos.enabled`, `spring.cloud.nacos.discovery.enabled`.

**Comment by steverao** [comment]
> nacos user's docs

`ribbon.nacos.enabled` is belong to the branch of [2.2.x use's docs](https://spring-cloud-alibaba-group.github.io/github-pages/hoxton/zh-cn/index.html#_%E6%9C%8D%E5%8A%A1%E6%B3%A8%E5%86%8C%E5%8F%91%E7%8E%B0_nacos_discovery). `spring.cloud.nacos.discovery.enabled` will added later.
