### ISSUE TITLE
Nacos Server can‘t support use IPv6 

### ISSUE THREAD

**Issue by sollhui** [alibaba/spring-cloud-alibaba#2805]
Recently,we support register IPv6 in nacos,but nacos self can't support IPv6

`spring.cloud.nacos.discovery.server-addr=IPv6 address` it would be error.
`spring.cloud.nacos.discovery.server-addr=IPv4 address` it would be ok.

**Comment by steverao** [comment]
I don't understand what you described? Nacos don't influence the IPv6 register and subscribe.

**Comment by sollhui** [comment]
Nacos don't influence the IPv6 register and subscribe, but nacos can't use IPv6 address, related issue: #2740

**Comment by yuhuangbin** [comment]
Nacos Server does not support ipv6, you can report to [Nacos community](https://github.com/alibaba/nacos).

**Comment by steverao** [comment]
The problem need to reported to Nacos community.
