### ISSUE TITLE
2021.0.4.0版本使用的nacos-client 2.0.4和nacos-server 1.x版本不兼容

### ISSUE THREAD

**Issue by cxzucc** [alibaba/spring-cloud-alibaba#2812]
升级到2021.0.4.0版本后，发现nacos-client 2.0.4版本和我们用的nacos-server 1.x版本不兼容。
不知道回退到nacos-client 1.4.x版本会不会有问题？或者有没有别的解决方法？
升级nacos-server到2.x是不可能升级的。

**Comment by steverao** [comment]
不能使用Nacos-client 2.x 连接 Nacos-server 1.x，你可以使用2021.0.1.0，这个版本是社区适配了1.4.2版本的，2021.0.4.0降级Nacos-client一般也没问题，因为做了兼容，但是还是需要自测验证一下。
