### ISSUE TITLE
Spring Cloud Alibaba2.2.9.RELEASE版本中，没有Dubbo版本的对应关系了

### ISSUE THREAD

**Issue by 2227324689** [alibaba/spring-cloud-alibaba#2823]
最近我发现Spring Cloud Alibaba2.2.7.RELEASE版本以后，去掉了spring-cloud-starter-dubbo版本的维护。
目前我看到spring-cloud-starter-dubbo 2.x维护的版本最新的是2.2.7.RELEASE，然后就是2020.x版本了

我想问一下，Spring Cloud Alibaba2.2.9.RELEASE版本以后对应Spring-Cloud-Starter-Dubbo的版本。
以及如果我直接使用Spring-Cloud-Starter-Dubbo 2020.x版本，那对于spring-cloud-alibaba中的其他组件nacos、sentinel的版本兼容对应是什么？

**Comment by steverao** [comment]
> 最近我发现Spring Cloud Alibaba2.2.7.RELEASE版本以后，去掉了spring-cloud-starter-dubbo版本的维护。 目前我看到spring-cloud-starter-dubbo 2.x维护的版本最新的是2.2.7.RELEASE，然后就是2020.x版本了
> 
> 我想问一下，Spring Cloud Alibaba2.2.9.RELEASE版本以后对应Spring-Cloud-Starter-Dubbo的版本。 以及如果我直接使用Spring-Cloud-Starter-Dubbo 2020.x版本，那对于spring-cloud-alibaba中的其他组件nacos、sentinel的版本兼容对应是什么？

方便问一下，你使用Spring-Cloud-Starter-Dubbo模块的目的是什么？从2.2.8.RELEASE和2021.0.1.0版本开始就都停止维护相关模块了。具体讨论可参见#2398

**Comment by 2227324689** [comment]
嗯，我是想着Dubbo既然拥抱了Spring Cloud生态，那么无法避免的和Spring Cloud中的各个技术组件进行融合的问题。
只是最近看到没有维护Dubbo这个版本了，所以就问一下。
确实Dubbo本身的生态就足够成熟，特别是在Dubbo3.0以后，融入到Spring Cloud中的必要性不大。
没问题了，感谢您的回复。
