### ISSUE TITLE
spring-cloud-starter-alibaba-nacos 2.2.9.RELEASE 的server-addr 不能用https://xxxx.com

### ISSUE THREAD

**Issue by lhyxcxy** [alibaba/spring-cloud-alibaba#2824]
我用 nacos 2.2.6.RELEASE版本，spring.cloud.nacos.discovery.server-addr 是支持https://xxxx 注册的。

但是用2.2.9.RELEASE,会报错 ：
Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host https, cause=java.lang.RuntimeException: java.net.UnknownHostException: https

我想在2.2.9.RELEASE版本中， 注册中心地址为https的，如何解决

**Comment by 2227324689** [comment]
你直接增加这个配置就行`spring.cloud.nacos.discovery.secure=true`。
然后spring.cloud.nacos.discovery.server-addr直接填写ip:port。

**Comment by steverao** [comment]
> 

一般都不建议把注册中心暴露在外网的，一般都是在内网配置个注册中心的IP或者域名就好了，另外就算2.2.9.RELEASE使用`spring.cloud.nacos.discovery.server-addr=https://xxxx.com`形式也是可以正常找到注册中心注册上服务的。

![image](https://user-images.githubusercontent.com/25423978/194735010-7733a1fa-3096-4ab9-87c6-26bb4fb852e6.png)
![image](https://user-images.githubusercontent.com/25423978/194735029-76076c5f-f4a8-44b6-96e6-bda3fb730c0f.png)

**Comment by steverao** [comment]
Long time without response and close first.
