### ISSUE TITLE
RouteDefinition进行redis序列化失败

### ISSUE THREAD

**Issue by Klayt11** [alibaba/spring-cloud-alibaba#2829]
使用的是springcloudalibaba的gateway版本3.1.4，该版本已经提供了RedisRouteDefinitionRepository可作为接入路由redis存储。
但是我在使用中报错了，下面是错误内容
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [org.springframework.cloud.gateway.route.RouteDefinition]

错误原因是：RouteDefinition没有实现Serializable，看了源码确实没有

**Comment by steverao** [comment]
This is problem about `spring-cloud-gateway`, you should ask them for help!
