### ISSUE TITLE
com.netflix.client.ClientException: Load balancer does not have available server for client:

### ISSUE THREAD

**Issue by dandan1234565** [alibaba/spring-cloud-alibaba#2834]
近期升级了springboot版本为2.7.3，同时将spring-cloud-starter-alibaba-nacos-config与spring-cloud-starter-alibaba-nacos-discovery版本升级为了2021.0.1.0，另外nacos-client版本使用的是1.4.1。本地启动两个服务，并使用feign进行调用，openfiegn版本使用的是2.1.3.RELEASE，现在启动服务后，nacos服务列表可正常显示两个服务，但是在实际调用过程中，出现了com.netflix.client.ClientException: Load balancer does not have available server for client:错误

**Comment by steverao** [comment]
针对你的问题：
1.尽量不要随便任意搭配各个组件版本，否则兼容性难以得到保证，建议使用[社区推荐版本搭配](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)。
2.`Load balancer does not have available server for client` 这行日志其实已经很清楚了，就是这个客户端没有实例，你需要排查一下消费端的服务名、所在分组和命名空间等参数和注册中心的是否一致。

**Comment by dandan1234565** [comment]
我的服务已经注册进nacos了，在服务列表是可见的，而且之前这样配置是可以调用到的，问题出现在版本升级以后。而且想问下nacos2021版本之后，是否必须引用loadbalancer呢，我看2021之后是不是就不支持ribbon负载均衡了

**Comment by HaojunRen** [comment]
Ribbon从2020第一个版本就被Spring Cloud官方移除掉了
