### ISSUE TITLE
请教大佬一个关于提交pr的问题

### ISSUE THREAD

**Issue by DeBruyne2020** [alibaba/spring-cloud-alibaba#2844]
![image](https://user-images.githubusercontent.com/68886035/195977356-d3e634b9-975f-4828-aa98-882f17f46e73.png)

请教下大佬，“如何贡献代码”（https://github.com/alibaba/spring-cloud-alibaba/wiki/%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81）里要说执行“rebase master分支的代码”，但是我在源码项目里没查到有master分支，
![image](https://user-images.githubusercontent.com/68886035/195977478-67f298ea-3eee-45e8-9b7a-aaf60afedb7b.png)

，想请问下大佬[抱拳],如果想提交 PR ，现在是 rebase哪个分支号啊？

---------------------------------------------------------------------------------------------------------------------------------------------------
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by sollhui** [comment]
目前我们主要维护的是2021.x和2.2.x这两个分支，修改哪个分支就向哪个分支合并

**Comment by DeBruyne2020** [comment]
> 目前我们主要维护的是2021.x和2.2.x这两个分支，修改哪个分支就向哪个分支合并

收到，了解了，感谢大佬[抱拳]

**Comment by steverao** [comment]
Added relevant explanation in document now.
