### ISSUE TITLE
使用@EventListener监听服务注册事件,事件内容不符合预期

### ISSUE THREAD

**Issue by guyuexue** [alibaba/spring-cloud-alibaba#2846]
```java
@EventListener
public void instanceRegiterdEvent(InstanceRegiterdEvent<ServiceInstance> event) {
    // TODO 
}
```
实际接收到的event中config类型是`NacosDiscoveryProperties`,预期应该是`NacosServiceInstance`
导致使用`@EventListener`中condition进行条件判断时报错,找不到`ServiceInstance`中的属性

nacos版本:1.4.1
spring cloud alibaba版本: 2021.0.1.0

**Comment by BillLthree** [comment]
spring cloud alibaba版本: 2021.0.1.0 适配的 nacos版本是1.4.2 ，Spring Cloud 2021.0.1，Spring Boot Version是2.6.3，有没有可能是版本适配出现了问题

**Comment by BillLthree** [comment]
版本应该没有问题。
![屏幕截图 2022-10-30 113956](https://user-images.githubusercontent.com/54893683/198861481-1dc20aa8-9b97-4939-93d2-a78750d6f908.png)
我自己跑了一下，实际接收到的event中的config类型确实是NacosDiscoveryProperties，您说的：“预期应该是NacosServiceInstance”，我认为这个说法是有问题的。我们预期接收到的应该是ServiceInstance的配置信息，而ServiceInstance的配置信息的类型就是NacosDiscoveryProperties。
通过看这个源码 org.springframework.cloud.client.discovery.event.InstanceRegisteredEvent

```
public class InstanceRegisteredEvent <T> extends org.springframework.context.ApplicationEvent {
    private T config;

    public InstanceRegisteredEvent(java.lang.Object source, T config)

    public T getConfig()
}
```


我们通过getConfig() 获取的是服务实例的配置信息，所以显示的是NacosDiscoveryProperties。
这是我对这个问题的理解，如有错误，请指正。

**Comment by guyuexue** [comment]
spring cloud并没有提供`ServiceInstance的配置信息`相关的上层接口/vo,所以我理解监听器监听实例注册事件返回应该是实例本身.
个人理解使用`@EventListener`注解来进行服务微服务注册监听是spring cloud体系提供的不依赖具体微服务实现的一种上层api封装,如果将InstanceRegiterdEvent<?> event 中的泛型定义为NacosDiscoveryProperties确实在spring cloud alibaba体系下能够工作,如果按该方式实现那么这个监听就深度绑定spring cloud alibaba实现,无法切换.
目前是设想基于spring cloud体系开发一个小的框架需要做实例监听,虽然一开始肯定会用spring cloud alibaba做默认支持,但不想直接绑死spring cloud alibaba
