### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discovery 2021.0.4.0 It seems that Ribon has been abandoned. How to achieve load balancing of weights?

### ISSUE THREAD

**Issue by 412111959** [alibaba/spring-cloud-alibaba#2853]
Component:  nacos

question:
spring-cloud-starter-alibaba-nacos-discovery 2021.0.4.0 It seems that Ribon has been abandoned. How to achieve load balancing of weights? I have tried to modify the weights on the web side of the nacos or in the service configuration file. It seems that they do not take effect. Polling is used by default. How can I make the load balancing of weights take effect?

问题:
spring-cloud-starter-alibaba-nacos-discovery 2021.0.4.0 它似乎放弃了ribbon,如何做到权重的负载均衡? 我尝试过修改nacos网页端或者是服务配置文件中的权重,似乎都没有生效,都是默认使用轮询的方式.请问如何让权重的负载均衡生效?

**Comment by 412111959** [comment]
In addition, I see that you can customize a load balancer? So does the load balancing of the weights provided by the previous ribbon need to be implemented in the new version?
另外我看到,可以自定义一种负载均衡?所以所之前的ribbon那种提供的权重的负载均衡在新版本中需要自己去实现吗?

**Comment by yuhuangbin** [comment]
`NacosLoadBalancer` is an alternative implementation of `NacosRule`.

**Comment by 412111959** [comment]
> `NacosLoadBalancer` is an alternative implementation of `NacosRule`.


不好意思,这么久才回复你.
我是一个初学者,我不是很明白你说的意思. 比较想知道,旧版中是用ribbon做负载均衡的nacos利用下面的配置,以及在nacos的UI中调整对应应用的权重,即可实现权重的负载均衡. 那么我想知道,spring-cloud-starter-alibaba-nacos-discovery 2021.0.4.0要是用什么方法可以实现同样的效果呢
I'm sorry to reply to you so late
I'm a beginner. I don't quite understand what you mean. I want to know that in the old version, using the following configuration and adjusting the weight of the corresponding application in the UI of NACOS, that can mplement weight load balancing. Then I want to know how spring cloud starter alibaba nacos discovery 2021.0.4.0 can achieve the same effect

> xxxService:
&nbsp;&nbsp;ribbon:
&nbsp;&nbsp;&nbsp;&nbsp;NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

我在新版本中先引入了这个spring-cloud-starter-loadbalancer,然后再nacos的ui中调整权重,比如0.1和1,或者1和10,都无法实现权重,都是默认轮询.
In the new version, I first introduced the loadbalancer, and then adjusted the weights in the ui of nacos, such as 0.1 and 1, or 1 and 10. The weights cannot be achieved, and they are all polling by default
(
而且我在网上查找相关问题,有人给出了自己去实现权重的负载均衡,所以我才有这个问题,是不是新版本nacos权重的负载均衡需要自己去实现
In addition, I searched for related problems on the Internet, and someone gave me the idea of implementing load balancing with weights. That's why I have this problem. Is it true that the load balancing with weights of the new version of nacos needs to be implemented by myself
)
`<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-loadbalancer</artifactId>
</dependency>`

**Comment by 412111959** [comment]
> `NacosLoadBalancer` is an alternative implementation of `NacosRule`.

我查看了NacosLoadBalancer的源码,里面有一行代码,似乎拿到了权重,但是我不清楚为什么权重负载均衡没有出现,而是一直是默认的轮询. 是我需要在应用的配置文件中加入某些配置之类的吗?
I checked the source code of the NacosLoadBalancer. There is a line of code in it, which seems to have gained weight. But I don't know why my code is not effective. Do I need to add some configurations to the application configuration file?
`ServiceInstance instance = NacosBalancer
					.getHostByRandomWeight3(instancesToChoose);`
@yuhuangbin

**Comment by sollhui** [comment]
@412111959 你好，这个NacosRule需要ribbon作为负载均衡才能向你之前一样使用，上面所说的意思是naocosrule这个类不作为自动装配的类，是一个用户可选的增强功能，如果你要在loadbalance中使用它，需要实现对应的接口即可

**Comment by 412111959** [comment]
@HHoflittlefish777 好的，谢谢，我再研究研究
