### ISSUE TITLE
Upgrade 'spring - cloud - alibaba met injection problem in the process of' org. Springframework. Session. ReactiveSessionRepository that could not be found '

### ISSUE THREAD

**Issue by luankun88** [alibaba/spring-cloud-alibaba#2855]
**A version number**

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.1</version>
        <relativePath/>
</parent>

<spring-cloud.version>2021.0.3</spring-cloud.version>

<spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>

<dubbo.version>2.7.18</dubbo.version>

<spring-cloud-starter-oauth2.version>2.1.2.RELEASE</spring-cloud-starter-oauth2.version>
        <spring-cloud-starter-security.version>2.1.2.RELEASE</spring-cloud-starter-security.version>

**spring-session  version number**
![image](https://user-images.githubusercontent.com/29765300/197320198-d2b1d25f-c2be-4843-91ad-6914b45250b1.png)

**The error message**

2022-10-22 12:32:05.175 ERROR 17736 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method webSessionManager in org.springframework.session.config.annotation.web.server.SpringWebSessionConfiguration required a bean of type 'org.springframework.session.ReactiveSessionRepository' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.session.ReactiveSessionRepository' in your configuration.

**Comment by yuhuangbin** [comment]
The version correspondence you used is confused, please refer [wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)

**Comment by steverao** [comment]
Long time without response and close first.
