### ISSUE TITLE
Nacos Config NacosPropertySourceBuilder parse error

### ISSUE THREAD

**Issue by Xyk859852** [alibaba/spring-cloud-alibaba#2857]
When using SpringCloudAlibaba, Nacos configuration center, using sharedConfigs or extensionConfigs to load the configuration, when the configuration is in JsonArray format, is there any exception when the configuration is refreshed? For example, can the parse object only be a JsonObject Object not a JSONArray??

The corresponding version is SpringCloudAlibaba: 2021.0.1.0 SpringCloud: 2021.0.1, SpringBoot: 2.6.8

**Comment by yuhuangbin** [comment]
Can you provide details? Eg: configuration content, error stack information.

**Comment by Xyk859852** [comment]
configuration content ：
[
    {
        "filters": [{
            "name":"RewritePath",
            "args":{
                "regexp":"/system-web-app/(?<segment>.*)",
                "replacement":"/${segment}"
            }
        }],
        "id": "system-web-app",
        "order": 0,
        "predicates": [{
            "args": {
                "pattern": "/system-web-app/**"
            },
            "name": "Path"
        }],
        "uri": "lb://system-web-app"
    },
    {
        "filters": [],
        "id": "baidu_route",
        "order": 1,
        "predicates": [{
            "args": {
                "pattern": "/blibli-1"
            },
            "name": "Path"
        }],
        "uri": "https://www.bilibili.com/"
    }
]
error stack information
![image](https://user-images.githubusercontent.com/39120949/197463446-a8804918-1243-4632-b641-4a4bf72a7dea.png)

![image](https://user-images.githubusercontent.com/39120949/197463479-b1196889-7d19-42f6-bd15-c8c1af416e1b.png)

**Comment by Xyk859852** [comment]
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/39120949/197464094-31210050-814a-4367-a4d0-6feaff52cf80.png">
From the source code here, it can only be resolved JsonObject

**Comment by yuhuangbin** [comment]
Your application scenario should be dynamic routing.  You can refer:
```java
  @Autowired
  private NacosConfigManager nacosConfigManager;

  @Autowired
  private RouteDefinitionWriter routeDefinitionWriter;

  @Autowired
  private ApplicationEventPublisher publisher;

  public void refreshRoutes(String configInfo) {
   String config = nacosConfigManager.getConfigService().getConfig(dataId, group, 5000);
   List<RouteDefinition> routeDefinitions = covertoRouteDefinition(configInfo);
   modifyRoutes(routeDefinitions);
   this.publisher.publishEvent(new RefreshRoutesEvent(this));
  }
   
  private void modifyRoutes(List<RouteDefinition> routeDefinitions) {
          routeDefinitions.forEach(routeDefinition -> routeDefinitionWriter.save(Mono.just(routeDefinition)).subscribe());
  }
```

**Comment by Xyk859852** [comment]
I try

**Comment by Xyk859852** [comment]
Using the method you provided, there will still be a problem and the existing error reporting problem will not be solved
<img width="976" alt="image" src="https://user-images.githubusercontent.com/39120949/197485020-f75e83ed-ff68-4969-ac30-e8c8d943040b.png">
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/39120949/197485099-dd80a8b1-e69a-443d-ad32-6290c6049b2d.png">
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/39120949/197485130-947c9b65-c343-4f33-af9d-a410a73a0e5e.png">

**Comment by yuhuangbin** [comment]
> Your application scenario should be dynamic routing. You can refer:
> 
> ```java
>   @Autowired
>   private NacosConfigManager nacosConfigManager;
> 
>   @Autowired
>   private RouteDefinitionWriter routeDefinitionWriter;
> 
>   @Autowired
>   private ApplicationEventPublisher publisher;
> 
>   public void refreshRoutes(String configInfo) {
>    String config = nacosConfigManager.getConfigService().getConfig(dataId, group, 5000);
>    List<RouteDefinition> routeDefinitions = covertoRouteDefinition(configInfo);
>    modifyRoutes(routeDefinitions);
>    this.publisher.publishEvent(new RefreshRoutesEvent(this));
>   }
>    
>   private void modifyRoutes(List<RouteDefinition> routeDefinitions) {
>           routeDefinitions.forEach(routeDefinition -> routeDefinitionWriter.save(Mono.just(routeDefinition)).subscribe());
>   }
> ```

File separate configuration. eg:
```properties
dynamic-route.data-id=xxx.json
dynamic-route.group=DEFAULT
```

**Comment by Xyk859852** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/39120949/197497319-c62ab658-6417-453a-bc3b-4b30fdc505b4.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/39120949/197497356-38a74bea-09c4-4012-9498-8d0da5b0dc89.png">

**Comment by yuhuangbin** [comment]
You need to pull the configuration information through ConfigService and write it through `routeDefinitionWriter#save`

**Comment by Xyk859852** [comment]
This is what I did. My route reads and writes are OK, but there is a problem when Nacos is refreshed at the end. I understand that it has nothing to do with the Gateway route

**Comment by Xyk859852** [comment]
The piece of code that my Nacos listens to is fine, but there is a problem with the last Nacos refresh itself

**Comment by yuhuangbin** [comment]
Don't use onfiguration Item `spring.cloud.nacos.config.shared-configs`. You can use ConfigService to pull configuration from nacos.

**Comment by ruansheng8** [comment]
它实际上是通过这个JSON对象从根路径一层层解析成为properties格式的key , 如果是数组类型,那么就没有根节点了.

如果是要做网关路由动态发布的话,可以生成这样的格式 
```
{
    "spring":
    {
        "cloud":
        {
            "gateway":
            {
                "routes":
                [
                  // 路由配置...
                ]
            }
        }
    }
}
```
网关层只需监听这个配置 , Spring Cloud Gateway 官方的 PropertiesRouteDefinitionLocator 会自动实时加载路由变更 , 因为上面这个格式的JSON被解析后对应的yaml就是
```
spring:
  cloud:
    gateway:
      routes:
        - 路由配置...
```
使用该方式需要注意Nacos上是否已经有其他配置文件也配置了 "spring.cloud.gateway.routes" (会相互覆盖) , 解决方案也比较简单 , 监听对应的配置文件 , 参考
```
@Component
public class CustomPropertiesRouteDefinitionLocator implements RouteDefinitionLocator {

    private final Environment environment;

    public CustomPropertiesRouteDefinitionLocator(Environment environment) {
        this.environment = environment;
    }

    @Override
    public Flux<RouteDefinition> getRouteDefinitions() {
        List<RouteDefinition> routes = Binder.get(this.environment)
                .bindOrCreate("spring.cloud.gateway.custom-routes", GatewayProperties.class)
                .getRoutes();
        return Flux.fromIterable(routes);
    }
}


```
