### ISSUE TITLE
seata xid can't transmit if use httpclient

### ISSUE THREAD

**Issue by zhuangzhuangdashen** [alibaba/spring-cloud-alibaba#2862]
具体描述：引入httpclient组件后seata无法透传xid
源码表现为Feign调用不会进入SeataFeignClient类的execute方法
把httpclient组件依赖去除掉之后可以正常透传

材料
1. httpclient依赖pom
<dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-httpclient</artifactId>
           <version>10.0.1</verion>
        </dependency>
</dependency>

2. spring-cloud-alibaba-seata版本为2.2.0-RELEASE
3. feign-core 9.7
4. spring-cloud-starter-openfeign-core 2.0.2.RELEASE

**Comment by zhuangzhuangdashen** [comment]
Wish your reply, thanks

**Comment by HaojunRen** [comment]
Refer to code as blow:
```java
public class  MyInterceptor implements RequestInterceptor {
    @Override
    public void apply(RequestTemplate requestTemplate) {
         String xid = RequestContextHolder.getRequestAttributes().getRequest().getHeader("xid");
         requestTemplate.header("xid", xid);
    }
}
```

RequestContextHolder is a threadlocal class based on Spring Web Context. You need to pay attention to async scene, that means threadlocal value will be lost with async scene
