### ISSUE TITLE
Nacos Config的wiki中单词拼写错误

### ISSUE THREAD

**Issue by yangdx101** [alibaba/spring-cloud-alibaba#2863]
https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config
Nacos Config 的wiki页面中"支持自定义 namespace 的配置"部分，9个"namespace"中有2个错误拼写成了"namespae"，缺少了"c"

**Comment by BillLthree** [comment]
I want to fix them.

**Comment by BillLthree** [comment]
Need I modify this part? How should I submit it

**Comment by steverao** [comment]
> Need I modify this part? How should I submit it

I solved it just now. Just Committer can deal with wiki problem.
