### ISSUE TITLE
spring-cloud-starter-alibaba-seata 2021.0.1.0+ 去掉了hystrix xid传递的代码支持?

### ISSUE THREAD

**Issue by 2012110325** [alibaba/spring-cloud-alibaba#2865]
spring-cloud-starter-alibaba-seata 2.2.8.RELEASE 中有hystrix xid传递的支持. 功能类: SeataHystrixConcurrencyStrategy.
而 2021.0.1.0+版本 将这个类去掉了, 导致程序中 hystrix调用时, xid不传递了. 是出于什么考虑 去掉对hystrix 传递xid的支持.

**Comment by HaojunRen** [comment]
Spring Cloud 202x官方已经不集成Hystrix，也不推荐用Hystrix，就是说官方不会对Hystrix下相关行为做任何处理，有问题的地方需要自行解决

**Comment by 2012110325** [comment]
Spring Cloud 202x官方已经不集成Hystrix,   但是hystrix作为一个独立框架, 还是被大量使用的.  seata作为一个平台类工具, 需要兼容各种普遍情况,  直接就在新版去掉支持, 感觉不太友好.

**Comment by HaojunRen** [comment]
![图片](https://user-images.githubusercontent.com/42354711/198012810-0518a7ed-4f4b-4eae-a7e6-0372d4aaf98e.png)

**Comment by 2012110325** [comment]
业务方自己处理下吧.   感谢回复.

**Comment by HaojunRen** [comment]
2021版的依赖的父pom上，官方已经把hystrix去掉了，无法引用到了

**Comment by 2012110325** [comment]
嗯,  为了保证事务的传递性,  已基于2021.x 切分支,  手动加入依赖hystrix-core,  在处理xid的传递问题.  已处理

**Comment by githust66** [comment]
2021版Feign里面也去掉了hystrix的依赖，但是@FeignClient注解还能写fallbackFactory和fallback参数，这没效果了吧
