### ISSUE TITLE
Refactory Spring Cloud Seata

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/spring-cloud-alibaba#2866]
# Optimization
- For `Feign` module, it needs to reactory with Feign Interceptor, that will be much simple
- For `Rest` module, it needs to remove `HttpRequestWrapper` which is unnecessary

# New feature
- WebClient needs to be added
- Support a common modul to transform Seata `xid`, suggest the module much generic
- Support sca seata overrides the common module

**Comment by kaori-seasons** [comment]
2020版的spring cloud gateway 不支持基于feign去加载xid上下文
