### ISSUE TITLE
Nacos client parameter settings are compatible with `public` namespace

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2869]
### Problem Description
In some versions of Nacos client, the configuration can be obtained by setting the public namespace through `spring.cloud.nacos.config.namespace=public`, but when the client is upgraded, the configuration may not be obtained normally. There are some background reasons for this problem. For details, please refer to: [#7919](https://github.com/alibaba/nacos/issues/7919), and some users have encountered related issues: #2852.

### Solutions
After parsing the namespace configured by the user, when the value is public, it can be automatically set to: "".

**Comment by ruansheng8** [comment]
@@i will solve it @@

**Comment by ruansheng8** [comment]
see [#9420](https://github.com/alibaba/nacos/pull/9420)

**Comment by steverao** [comment]
Solved it in #2874.
