### ISSUE TITLE
Contribute Appactive module

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2890]
### Background
Recently, we have developed the Appactive module related to microservices high availability. The current state is completed. There are many areas that need to be optimized and improved. We welcome everyone to contribute, improve the documentation, and optimize the code.

### Reference

- code branch: https://github.com/alibaba/spring-cloud-alibaba/tree/2.2.x/spring-cloud-alibaba-examples/appactive-example

**Comment by ayushdubey755** [comment]
Can I work on this issue?
@steverao 
 thank you for your insightful comment is there anything else should I know as the first time contributing to this project, I would love to work on it since I have previously used the spring framework and currently working on spring boot.
From which module I can start updating this new feature?

**Comment by HaojunRen** [comment]
Refer some suggestions in the attachement
[Appactive的优化建议.docx](https://github.com/alibaba/spring-cloud-alibaba/files/10391185/Appactive.docx)

**Comment by yuluo-yx** [comment]
> 参考附件 [Appactive的优化建议.docx中的一些建议](https://github.com/alibaba/spring-cloud-alibaba/files/10391185/Appactive.docx)
File failed to open!
![image](https://user-images.githubusercontent.com/77964041/212660567-16198cb1-c0ab-40b2-b804-c740485d57dc.png)

**Comment by HaojunRen** [comment]
> > 参考附件 [Appactive的优化建议.docx中的一些建议](https://github.com/alibaba/spring-cloud-alibaba/files/10391185/Appactive.docx)
> > File failed to open!
> > ![image](https://user-images.githubusercontent.com/77964041/212660567-16198cb1-c0ab-40b2-b804-c740485d57dc.png)

it can be open in my browser and mobile

**Comment by yuluo-yx** [comment]
After I downloaded it, my phone and computer could not be opened, it may be a problem with my environment, I found this file in the communication group. 
Thanks!

**Comment by yuluo-yx** [comment]
> > > 参考附件 [Appactive的优化建议.docx中的一些建议](https://github.com/alibaba/spring-cloud-alibaba/files/10391185/Appactive.docx)
> > > File failed to open!
> > > ![image](https://user-images.githubusercontent.com/77964041/212660567-16198cb1-c0ab-40b2-b804-c740485d57dc.png)
> 
> it can be open in my browser and mobile

After I downloaded it, my phone and computer could not be opened, it may be a problem with my environment, I found this file in the communication group.
Thanks!
