### ISSUE TITLE
nacos配置中转义符丢失

### ISSUE THREAD

**Issue by SevenBlue2018** [alibaba/spring-cloud-alibaba#2891]
环境：
spring-cloud-starter-alibaba-nacos-config 1.5.1.RELEASE，在mse中配置键值对，value值包含转义符，例如：
test.regex=\\<img.*?\\>
bean中获取该值，转义符丢失：值为：\<img.*?\>
```
@Value("${test.regex}")
private String regex;

@GetMapping("/test")
public String test(){
    System.out.println(regex);
    return regex;
}
```
问题：
为何转义符丢失？

**Comment by steverao** [comment]
In latest 2.2.9.RELASE version, I can't reproduce the problem.
This is my config in nacos server:
![image](https://user-images.githubusercontent.com/25423978/200297856-6bb5edea-9d4e-4090-8e12-b74de368ff6b.png)
This is value in local environment:
![image](https://user-images.githubusercontent.com/25423978/200297989-6d09ddcd-1c2e-4109-b168-134626d8b708.png)

**Comment by SevenBlue2018** [comment]
In 1.5.1.RELEASE version, I got the problem. Because all of us use Spring Cloud Edgware.SR3, so I can not upgrade spring-cloud-starter-alibaba-nacos-config version.

**Comment by steverao** [comment]
> In 1.5.1.RELEASE version, I got the problem. Because all of us use Spring Cloud Edgware.SR3, so I can not upgrade spring-cloud-starter-alibaba-nacos-config version.

You can refer to our [release list](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E). 1.5.1.RELEASE is very old version, we don't recommend use in future, you can try to update to 2.1.2.RELEASE. It alright when I test just now.
