### ISSUE TITLE
loadApplicationConfiguration debug log【Ignore the empty nacos configuration】

### ISSUE THREAD

**Issue by zjg1993** [alibaba/spring-cloud-alibaba#2892]
please move issue to spring cloud alibaba community

_Originally posted by @KomachiSion in https://github.com/alibaba/nacos/issues/9496#issuecomment-1305367065_

**Comment by steverao** [comment]
It can't close now, it just print log once and give some informations for users when your app starts,.

**Comment by zjg1993** [comment]
ok! thanks
