### ISSUE TITLE
Spring boot version 2.7.5 @ SentinelRestTemplate does not take effect

### ISSUE THREAD

**Issue by XW512** [alibaba/spring-cloud-alibaba#2894]
My version is as follows:
<properties>
        <spring-boot.version>2.7.5</spring-boot.version>
        <alibaba-cloud.version>2021.0.4.0</alibaba-cloud.version>
        <springcloud.version>2021.0.4</springcloud.version>
    </properties>

It is found that @ SentinelRestTemplate does not take effect when it is placed in the restTemplate. There is no problem with calls between feigns. I guess the version is incompatible,
Can you give me a compatible version? I used the version of spring boot recommended on the official website, which is 2.6.11, and it doesn't work

**Comment by steverao** [comment]
You can refer to [example module](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example) and check whether miss some configurations or dependencies. It works in our example.

**Comment by XW512** [comment]
> You can refer to [example module](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example) and check whether miss some configurations or dependencies. It works in our example.

I copied the dependency in the demo and found that it still doesn't work. If the version is changed to the following version, @ SentinelRestTemplate will take effect
<properties>
        <spring-boot.version>2.5.14</spring-boot.version>
        <alibaba-cloud.version>2021.1</alibaba-cloud.version>
        <springcloud.version>2020.0.6</springcloud.version>
    </properties>

**Comment by XW512** [comment]
> > You can refer to [example module](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example) and check whether miss some configurations or dependencies. It works in our example.

I mean, the @ SentinelRestTemplate annotation does not mean that load balancing is not possible, but that the circuit breaker policy cannot take effect. The circuit breaker policy invoked by feign is OK

**Comment by steverao** [comment]
@ SentinelRestTemplate annotation in RestTemplate is alright.
![image](https://user-images.githubusercontent.com/25423978/200537153-1820b7e7-5b45-4d5a-ae34-590b0f41a56c.png)

**Comment by XW512** [comment]
> @ SentinelRestTemplate annotation in RestTemplate is alright. ![image](https://user-images.githubusercontent.com/25423978/200537153-1820b7e7-5b45-4d5a-ae34-590b0f41a56c.png)

You can limit the flow in this way. I have already run in the demo. However, what I am simulating now is that the provider has two nodes, one of which returns slowly, and the other returns normally The json file is configured with a fusing policy. It is found that the nodes are always polled and no fusing occurs
The file degraderule.json has the following contents
[
  {
    "resource": "GET:http://service-provider/echo/{str}",
    "count": 1,
    "grade": 2,
    "timeWindow": 5,
    "statIntervalMs": 10000,
    "minRequestAmount": 3
  }
]

**Comment by XW512** [comment]
@steverao Can you help me with this question?

**Comment by steverao** [comment]
> @steverao Can you help me with this question?

ok, I reproduced the problem, it seems come from Sentinel. If you want to use degrade in RestTemplate, you can adjust version. If we solved it, we will tell you in the issue.

**Comment by XW512** [comment]
> > @steverao Can you help me with this question?
> 
> ok, I reproduced the problem, it seems come from Sentinel. If you want to use degrade in RestTemplate, you can adjust version. If we solved it, we will tell you in the issue.

OK，thank you so much

**Comment by steverao** [comment]
> > @ SentinelRestTemplate annotation in RestTemplate is alright. ![image](https://user-images.githubusercontent.com/25423978/200537153-1820b7e7-5b45-4d5a-ae34-590b0f41a56c.png)
> 
> You can limit the flow in this way. I have already run in the demo. However, what I am simulating now is that the provider has two nodes, one of which returns slowly, and the other returns normally The json file is configured with a fusing policy. It is found that the nodes are always polled and no fusing occurs The file degraderule.json has the following contents [ { "resource": "GET:http://service-provider/echo/{str}", "count": 1, "grade": 2, "timeWindow": 5, "statIntervalMs": 10000, "minRequestAmount": 3 } ]

I found the result, because, your configuration is wrong. You can refer to [Sentinel document](https://sentinelguard.io/zh-cn/docs/circuit-breaking.html) to see how to configure slow response.
![image](https://user-images.githubusercontent.com/25423978/216913046-269c4f76-9319-425b-9709-c28f6e37e10b.png). In your configuration, you grade is 2, it means mode of error count.

**Comment by XW512** [comment]
> > > @ SentinelRestTemplate annotation in RestTemplate is alright. ![image](https://user-images.githubusercontent.com/25423978/200537153-1820b7e7-5b45-4d5a-ae34-590b0f41a56c.png)
> > 
> > 
> > You can limit the flow in this way. I have already run in the demo. However, what I am simulating now is that the provider has two nodes, one of which returns slowly, and the other returns normally The json file is configured with a fusing policy. It is found that the nodes are always polled and no fusing occurs The file degraderule.json has the following contents [ { "resource": "GET:http://service-provider/echo/{str}", "count": 1, "grade": 2, "timeWindow": 5, "statIntervalMs": 10000, "minRequestAmount": 3 } ]
> 
> I found the result, because, your configuration is wrong. You can refer to [Sentinel document](https://sentinelguard.io/zh-cn/docs/circuit-breaking.html) to see how to configure slow response. ![image](https://user-images.githubusercontent.com/25423978/216913046-269c4f76-9319-425b-9709-c28f6e37e10b.png). In your configuration, you grade is 2, it means mode of error count.

At present, I want to control the fusing strategy through the error number. However, I found that the lower version of Sentinel can control the fusing

**Comment by XW512** [comment]
> > > @ SentinelRestTemplate annotation in RestTemplate is alright. ![image](https://user-images.githubusercontent.com/25423978/200537153-1820b7e7-5b45-4d5a-ae34-590b0f41a56c.png)
> > 
> > 
> > You can limit the flow in this way. I have already run in the demo. However, what I am simulating now is that the provider has two nodes, one of which returns slowly, and the other returns normally The json file is configured with a fusing policy. It is found that the nodes are always polled and no fusing occurs The file degraderule.json has the following contents [ { "resource": "GET:http://service-provider/echo/{str}", "count": 1, "grade": 2, "timeWindow": 5, "statIntervalMs": 10000, "minRequestAmount": 3 } ]
> 
> I found the result, because, your configuration is wrong. You can refer to [Sentinel document](https://sentinelguard.io/zh-cn/docs/circuit-breaking.html) to see how to configure slow response. ![image](https://user-images.githubusercontent.com/25423978/216913046-269c4f76-9319-425b-9709-c28f6e37e10b.png). In your configuration, you grade is 2, it means mode of error count.

I tried to introduce Sentinel-core instead of spring-cloud-alibaba, and found that the 1.8.6 slow call ratio of Sentinel-core is not effective. If this version is changed to 1.6.4, it can be effective. Is there any processing done by Sentinel that causes the fuse to fail
