### ISSUE TITLE
spring cloud alibaba config should change bootstrap.propeties to application.properties

### ISSUE THREAD

**Issue by nzb15555196162** [alibaba/spring-cloud-alibaba#2899]
**Which Component**
 in the new spring boot version mention, bootstrap.prroperties is deprecated, but spring cloud alibaba nacos config still use bootstrap.problem use bootstrap.problem, should support application.problem for spring cloud alibaba nacos config, hope for 
your reply

**To Reproduce**
1. newest verion for spring cloud alibaba
2. spring boot version above 2.5.x 
3. spring cloud verson above 2020.0.x aka Ilford 

**Expected behavior**
bootstrap.propertis should loaded

**Screenshots**

**Additional context**
 windows10, java17

**Comment by steverao** [comment]
We support `spring.config.import` in 2021.0.1.0 and 2021.0.4.0, more detail, you can refer to [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-2.4.x-example).

**Comment by nzb15555196162** [comment]
> We support `spring.config.import` in 2021.0.1.0 and 2021.0.4.0, more detail, you can refer to [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-2.4.x-example).
great!!!, it's will be better if can modify use case in doc
