### ISSUE TITLE
Add using of spring.config.import in document.

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2905]
### Background
Spring Boot 2.4 introduced a new way to import configuration data via the spring.config.import property. This is now the default way to bind to Config Server.
We need to update our [document](https://spring-cloud-alibaba-group.github.io/github-pages/2021/en-us/index.html#_spring_cloud_alibaba_nacos_config) and recommend users to use new property `spring.config.import` instead of import dependency of spring-cloud-starter-bootstrap.

### How to do
You need modify the [file](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc).

**Comment by BillLthree** [comment]
I want to try to solve this problem. First, I will use the spring-cloud-starter-bootstrap method to run through the demo, and then I will use spring.config.import property to run through the demo. let me try.

**Comment by ayushdubey755** [comment]
@steverao I want to contribute, Also in the documentation, do we have to remove the dependency and mention the above

**Comment by steverao** [comment]
We achieved it in #3010 and close now.
