### ISSUE TITLE
sidecar集成后低版本的调用成功，高版本的显示404

### ISSUE THREAD

**Issue by Jing52** [alibaba/spring-cloud-alibaba#2909]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/39614241/202076223-71cf709d-0569-418c-8dc8-5cb45c63164d.png">

Spring Cloud Alibaba Version:2021.0.1.0
Spring Cloud Version:2021.0.1
Spring Boot:2.7.3

<img width="536" alt="image" src="https://user-images.githubusercontent.com/39614241/202076911-ab3c06d8-6d27-4034-abf1-28e129fef896.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/39614241/202076951-1883fdb6-6524-46af-9e0e-27f06b10f0c6.png">

开发一个sidecar项目调用异构项目，我使用2.2.x 分支的版本是可以的，但是2021.x的版本就不行，查看nacos的服务信息，ip端口是正确映射了

**Comment by 52Hertz-C** [comment]
也有显示503

**Comment by 52Hertz-C** [comment]
显示的是503，不是404

**Comment by Jing52** [comment]
显示的是503，不是404，503是过载或者性能出现问题，但是同时启动高低版本，低版本能访问，而高版本就会出现503

**Comment by steverao** [comment]
It' a bug in branch of 2021.x, refer to #2912
