### ISSUE TITLE
Refactor spring-cloud-alibaba-governance module

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2913]
### 背景
当前微服务治理模块模块之间组织和划分有些复杂和繁琐，比如`governance-core`下面每个模块都有xxx-core和xxx-data两个单独模块。

1. xxx-core是主要的功能实现，比如auth-core，其中实现了像应用鉴权逻辑。
2. xxx-data作用是定义一些规则实例用来实现在xxx-core模块进行功能处理，其数据来源与具体的控制面（对接数据面实现`xxx-resource-transform`），可能是istio的CRD或者其他控制面传输过来的规则，但是目前其中来包括了数据存储内容。具体比如：`AuthRepository`和`RouteDataRepository`。

### 优化
个人觉得，把相关规则实例都统一存放在外部的`spring-cloud-alibaba-commons`中，但是需要把`AuthRepository`和`RouteDataRepository`数据存储逻辑剥离掉，通过定义一个接口定义一些相关规则推送逻辑，在`xxx-resource-transform`中定义推送动作，具体的存储实现放在xxx-core中，由xxx-core实现即可。

**Comment by sollhui** [comment]
以labelroute-data为例，在此模块中有三个子模块，控制面接口，CRD数据规则以及具体的存储逻辑，若要除去此模块，只需把相应的CRD规则以及控制面接口放入common模块中，规则数据存储逻辑可以合并至core模块，而在此模块中，控制面接口以及存储逻辑已经是解耦的

**Comment by steverao** [comment]
> 规则数据存储逻辑可以合并至core模块，

是的，我就是这个意思。

**Comment by 123liuziming** [comment]
有一些额外的建议：
对于目前方案的实现，控制面的接口放在common模块里，实际的存储逻辑在core模块，这样每增加一个新的治理模块就要增加一个接口以及实现，**并且这个接口通常只有一个保存控制面数据至缓存的方法**。
现提出一种更符合Spring通用做法的解耦方案，我们在拿到控制面的数据后，发送一个Spring的自定义事件，并且在具体的治理模块中监听此自定义事件(xxx-data与xxx-core模块都被删除，只留下一个starter模块)。这样利用Spring的event做解耦，相对来说会更符合Spring中的通用做法。

**Comment by steverao** [comment]
> 有一些额外的建议： 对于目前方案的实现，控制面的接口放在common模块里，实际的存储逻辑在core模块，这样每增加一个新的治理模块就要增加一个接口以及实现，**并且这个接口通常只有一个保存控制面数据至缓存的方法**。 现提出一种更符合Spring通用做法的解耦方案，我们在拿到控制面的数据后，发送一个Spring的自定义事件，并且在具体的治理模块中监听此自定义事件(xxx-data与xxx-core模块都被删除，只留下一个starter模块)。这样利用Spring的event做解耦，相对来说会更符合Spring中的通用做法。

不错的建议。
