### ISSUE TITLE
Cannot find a @StreamListener matching for message with id: e5373a09-e8e9-bcbf-bc2d-14b49241f66d

### ISSUE THREAD

**Issue by joenali** [alibaba/spring-cloud-alibaba#2916]
spring-cloud-starter-stream-rocketmq

when i use rocketmq，got a warn：
Cannot find a @StreamListener matching for message with id: e5373a09-e8e9-bcbf-bc2d-14b49241f66d

I used “condition = "headers['ROCKET_TAGS'] == 'cancel'"”, so the message was not consumed，but how to avoid it! thanks.

**Comment by steverao** [comment]
Please provide more information, such as version of `spring-cloud-starter-stream-rocketmq`, configurations and using demo. Otherwise, we don't have way to help you.

**Comment by steverao** [comment]
Long time without response and close first.
