### ISSUE TITLE
When will support JDK17 and SpringBoot3.0

### ISSUE THREAD

**Issue by shuangpai** [alibaba/spring-cloud-alibaba#2923]
When will support JDK17 and SpringBoot3.0

**Comment by shuangpai** [comment]
In addition, the update speed of the current framework is too slow

**Comment by yuhuangbin** [comment]
Refer #2917

**Comment by Deathef** [comment]
Spring Boot 3 GA is released. We are also concerned about when Spring Boot 3 will be supported.

**Comment by steverao** [comment]
We create an issue to discuss supporting spring boot 3.0, you can leave message in https://github.com/alibaba/spring-cloud-alibaba/issues/2926.
