### ISSUE TITLE
📣 Spring Boot 3.0 release General Availability(GA) version, about it you want to say?

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2926]
### Background
Spring Boot 3.0 release General Availability(GA) version yesterday, you can refer to https://spring.io/blog/2022/11/24/spring-boot-3-0-goes-ga

### Discussion
About Spring Boot 3.0, What is your demand? You can tell us by leaving message below.

**Comment by SimingZiling** [comment]
目前配置中心处于不可用的状态，希望能够尽快对spring boot 3.0.0 支持

**Comment by shuangpai** [comment]
尽快升级生态里边的所有组件，迫不及待想升级，JDK8太难用，17有很多好用的特性

**Comment by usbwc** [comment]
隔壁鹅厂3.0的支持下周发M版，赶紧卷起来。https://github.com/Tencent/spring-cloud-tencent/issues/709#issuecomment-1326963143

**Comment by steverao** [comment]
其实对于大部分起来来说，稳定才是第一位的，如果冒然使用最新版本对项目本身来说还是会带来一定风险的，所以不太建议企业用户急着升级。个人开发者如果着急使用，其实也可以自己先尝试去升级试用，不必要等着社区。社区一般都有自身的发版本节奏会稳定持续的进行推进。但也欢迎有相关使用经验的用户，将Spring Boot 3.0的一些使用经验在该issues中进行分享，帮助社区推进相关的支持。

**Comment by Comven** [comment]
先把spring-boot-2.6和2.7的新版适配完毕，然后在去适配3.0，发几个测试版本让有精力有条件去尝试的先去踩坑。很多企业应该都处于而且长期处于JAVA8，那么spring-boot-2.x版本将会是很长一段时间内使用最多的版本。

**Comment by Deathef** [comment]
企业追求的其实就两点，稳定和低成本，不只是开发成本还有性能上的成本、资源调配上的成本等等。我们现在的JVM语言是8、11、17（很少一部分），另一部分服务是Go和C++的。我们升级到17的是基于Vert.x + Kotlin的一些服务，不需要做太多的额外工作就能得到和做过一些分析和调优后的程序一样的性能和资源利用率，这个是最让我们期待的一点。
我觉得可以考虑先行一些Preview版本和Milestone，让有能力并且愿意参与社区建设的团队和个人一起适配Spring Boot3。

**Comment by Deathef** [comment]
企业追求的其实就两点，稳定和低成本，不只是开发成本还有性能上的成本、资源调配上的成本等等。我们现在的JVM语言是8、11、17（很少一部分），另一部分服务是Go和C++的。我们升级到17的是基于Vert.x + Kotlin的一些服务，不需要做太多的额外工作就能得到和做过一些分析和调优后的程序一样的性能和资源利用率，这个是最让我们期待的一点。
我觉得可以考虑先行一些Preview版本和Millstone，让有能力并且愿意参与社区建设的团队和个人一起适配Spring Boot 3。

**Comment by jaimyjie** [comment]
希望年内和Spring cloud 2022一起发个版本，不要等明年了哈

**Comment by pigping88** [comment]
好歹出个beta版本，让我们玩一玩，弄的出了boot3.0，玩也不是，不玩也不是，落后太多了

**Comment by imyxiao** [comment]
Spring boot推荐2.7.x以下的先升级2.7.x再升级到3，Spring cloud现在适配到2.6.13

建议跟随Spring cloud的适配脚步。

**Comment by ryanshummmm** [comment]
springcloud 2022应该快ga了

**Comment by herodotus-ecosystem** [comment]
个人的项目近期在适配 spring boot 3、spring cloud 2022、jdk17。总结下来遇到的问题大概是以下几类：

1. 更换 JDK 17 后，少部分第三方依赖包版本选择和控制问题（需要选择合适的版本）
2. javax 等包名变更 jakarta 问题（就是体力活）。
3. 新的依赖包中标记为过时代码替换。大多数情况没问题，就怕遇到像 spring security 6 存在使用方法变化的依赖升级
4. starter 自动配置注册格式不同导致的，大多数第三方依赖都倒在这里
5. 最怕的就是核心机制的变化，比如说反射。原有的一些反射机制在 JDK 17 会有问题。

总体上还是要看具体的代码。

个人拙见：

如果可以腾出一点资源，现在做一下适配的尝试也未尝不可。
1. 尝试一下，可能不会有想象的那么复杂和那么大的工作量，难说就是一些导入包的变化。那么适配也很快可以完成。比如说 Nacos，目前测试下来就是服务发现和注册失效，配置中心运行还是正常的。
2. 就算存在一些变动较大、甚至是短时间难以适配的内容，适配一下也是一种评估。至少对适配的难易度和工作量有了一个直观的了解，也好有所准备和安排。如果等到真正开展适配的时候，现去评估，倒是问题也不大只不过势必会让新版本更吃面市。

**Comment by spidersq** [comment]
没啥需求，跟上最新版，适配能用就行

**Comment by Deathef** [comment]
@herodotus-cloud 还有一个是很棘手的问题，就是Native。不过Native化的需求对于一部分人来说是有的，但不是很必要。

**Comment by steverao** [comment]
Welcome to add my dingtalk steverao2021, I create a relevant interesting group.

**Comment by puddingnet** [comment]
把选择权交给使用者。
可以提供支持spring boot 3.0的版本，beta的都行。使用者会根据自己的情况决定是预研还是直接上生产

**Comment by Phixsura** [comment]
I think it's best to give priority to the pursuit of stability and low cost at present, and to adapt springboot and springcloud. If you have enough ability, it's not a bad idea to give us an early taste of a BETA version that supports SpringBoot3.0.

**Comment by Comven** [comment]
Spring-Cloud-Tencent已经发布了一个1.8.1-2022.0.0-RC2版本来给大家尝试兼容性了。感觉好快

**Comment by zhangbinhub** [comment]
始终觉得sca比sct更好，sca与spring生态结合更加丝滑。本人一直在使用nacos+sca……可是隔壁sct都紧跟spring cloud节奏，发布了2022.0.0-RC2，sca大佬们能不能也跟上spring社区脚步？实在不想弃坑换sct，希望年内和spring cloud一起ga个版本

**Comment by zhangbinhub** [comment]
sca从0.x开始孵化时就是被spring官方认可的优质项目，希望sca在发版节奏和适配进度上不要懈怠

**Comment by zhangbinhub** [comment]
sca从0.x开始孵化时就是被spring官方认可的优质项目，希望sca在发版节奏和适配进度上不要懈怠

**Comment by steverao** [comment]
我们社区始终觉得扎扎实实为社区用户提供有价值的功能是最为重要的，因此我们近几个月在微服务治理，在应用高可用方面都在持续推进相关工作。具体大家可以见相关issues #2890,#2889,#2888,#2887。所以请大家稍安勿躁，社区做任何事情都是会综合考虑站在主要用户群体的立场去进行演进，比较资源有限，需要做的事情也比较多。目前也已经成立了相关Spring Boot 3.0的研发兴趣小组（钉钉群：13440021405），有兴趣和时间参与社区贡献的同学我们欢迎你的加入！但是也希望大家理解，如果仅仅是把SCA所依赖的Spring Boot版本号修改一下给大家使用宣传支持了3.0，这样做很快也可以让催促的同学不在催促，但这不是我们希望做的事情，肯定也不是广大用户对社区的期待，比较这种事不要社区你们自己也可以把源代码下载下来改一下打个包，我们需要花时间去做一些更深层次的框架之间的整合或者适配以后再发布，这也是SCA社区做事的标准。

**Comment by jaimyjie** [comment]
> 我们

有个东西叫迭代，现在新项目都逼着上jdk17等，使用新的spring生态体系。这次spring生态各项目变动太大了，如果用老的，上线后不是想升级就能升级，知道你们人少，事多，可以更新频率快点，先满足基本需求，谢谢

**Comment by jaimyjie** [comment]
我们

有个东西叫迭代，现在新项目都逼着上jdk17等，使用新的spring生态体系。这次spring生态各项目变动太大了，如果用老的，上线后不是想升级就能升级，知道你们人少，事多，可以更新频率快点，先满足基本需求，谢谢

**Comment by zuihou** [comment]
先出个Alpha或者beta版本吧。 你等我先升级，我等你先升级，就死循环了呀。
各自都先出个beta 版本，用不用是用户的事，社区不出版本，用户怎么用呢

**Comment by puras** [comment]
可以先把一些基础的能力适配。比如注册中心和配置中心，其他的逐步的完善吧，现在版本差的有些多呢

**Comment by admintertar** [comment]
Spring Native

**Comment by weir2010** [comment]
3.0 都出来了 社区还在问卷调查  spring官方一年前都在布局3.0  为什么社区不能一年前就开始准备 
这就是没规划

**Comment by steverao** [comment]
> 3.0 都出来了 社区还在问卷调查 spring官方一年前都在布局3.0 为什么社区不能一年前就开始准备 这就是没规划

你了解开源吗？你做过开源吗？不要什么都没做就站在道德制高点指责别人！开源不是商业化，开源也不是别人一直必须给你提供免费服务。社区不是为你一个人或者几个人服务的，我们什么时候支持Spring Boot 3.0我们是要照顾到大部分用户来谨慎决定的（我们也不是有无穷无尽的人力来什么都做）。另外，不是你今天说想尝鲜3.0，我们就给你提供3.0，明天说想尝鲜4.0就给你提供4.0。真的有探索欲的人，我想应该就算是社区还没做，你自己也会尝试做好了再贡献给别人使用，而不是伸手找别人要，还想说自己对技术有追求，喜欢探索新事物！

**Comment by HaojunRen** [comment]
经过几天研究和尝试集成，如下是个人观点，仅供参考

觉得Spring Boot 3.0战略思想很可能是失败的，首先从官方发布文档上看，除了支持少数新特性【例如，GraalVM native images】非常吸引人之外，带来的收益在付出的代价面前很苍白无力的。就如同上面的朋友提到
1. javax 等包名变更 jakarta 问题，这个实在太暴力，很多中间件使用了上一版的Servlet包，基本上就瘫痪了，例如，现在版本的Sentinel很多功能在Spring Boot 3.0上根本不能用
2. Java17，反射机制的代码，很多地方需要重新考虑和优化了
3. 很多中间件，都不能兼容，很多不是顶级的插件，都被移掉

**Comment by weir2010** [comment]
> > 3.0 都出来了 社区还在问卷调查 spring官方一年前都在布局3.0 为什么社区不能一年前就开始准备 这就是没规划
> 
> 你了解开源吗？你做过开源吗？不要什么都没做就站在道德制高点指责别人！开源不是商业化，开源也不是别人一直必须给你提供免费服务。社区不是为你一个人或者几个人服务的，我们什么时候支持Spring Boot 3.0我们是要照顾到大部分用户来谨慎决定的（我们也不是有无穷无尽的人力来什么都做）。另外，不是你今天说想尝鲜3.0，我们就给你提供3.0，明天说想尝鲜4.0就给你提供4.0。真的有探索欲的人，我想应该就算是社区还没做，你自己也会尝试做好了再贡献给别人使用，而不是伸手找别人要，还想说自己对技术有追求，喜欢探索新事物！

如果你理解我是站在道德制高点指责别人，我向社区道歉。没什么好说的了

**Comment by HaojunRen** [comment]
> 

建议先去Spring Boot官方看看issue，就算Spring Cloud Alibaba短时间内推出Spring Boot 3.0，是否有信心去集成并上线？

https://github.com/spring-projects/spring-boot/issues?q=Spring+Boot+3

**Comment by zxuanhong** [comment]
> > 
> 
> 建议先去Spring Boot官方看看issue，就算Spring Cloud Alibaba短时间内推出Spring Boot 3.0，是否有信心去集成并上线？
> 
> https://github.com/spring-projects/spring-boot/issues?q=Spring+Boot+3

不管他失不失败，历史的洪流总是要前进的。boot3很多新特性确实能带来跨域式的发展（个人认为）。总不能为了难而止步不前吧。。。永远都只坚守那一亩三分地。这和打仗一回事，敌人强大那就投降？？？？？你不愿意动，总有人愿意动，看到商机以及新的玩法，但对于坚守陈旧的总有可能被替代的一天。

**Comment by zxuanhong** [comment]
我就只关系一个问题，是不是不适配，如果不适配那就只能永远在2.7左右，停止不前了。如果要一直维护升级下去，那就肯定要接收现在的现实。

所以重点在于官方还要不要维护，既然要维护那还有啥可讨论的。难不成自己要维护boot,cloud不去使用spring官方的。

所以我觉得谈不讨论不是重点，重点是ali cloud是否还要支持boot以及cloud。要支持那就得适配，不支持那就不用适配。

所以谈不讨论没啥意义。

**Comment by zxuanhong** [comment]
所以还不如拿出一个肯定的说法，要不要支持。

或者支持计划，大家开个投票。比如第一步适配boot3（排除aot），第二步支持aot。一步步来。而不是还在讨论要不要适配boot3，这不是无聊吗。

**Comment by zxuanhong** [comment]
说得不好听点，这个讨论就是在瞎扯淡。
1. 要支持那就直接发计划更实在。
2. 不支持那就直接发通知。

## 实实在在不好？？？？？

**Comment by pigping88** [comment]
社区就是人手不够，而且目前3.0刚发，都不愿意踩坑，社区开源项目维护，人力，财力都不少呢，没有利益的驱使下，躺平，让他人先踩坑，也挺好的，实在受不了的，用spring官方的consul，替代。这边不等个大半年，没戏的。

**Comment by steverao** [comment]
> 说得不好听点，这个讨论就是在瞎扯淡。
> 
> 1. 要支持那就直接发计划更实在。
> 2. 不支持那就直接发通知。
> 
> ## 实实在在不好？？？？？

这个issues讨论的目的是希望大家如果之前有相关spring boot 3.0使用经验的，可以分享出来，帮助社区一起去进行支持与演进，这个issues并不是用来讨论是否支持spring boot 3.0的。3.0我们也创建了相关研发小组了，相关工作也在投入进行适配中了。不过我们短期内（未来1个月左右）不会发布相关适配版本，我们未来1个月内的新版本会包含其他内容，社区也有自己的功能迭代演进策略，具体这块我们都会在社区双周会中同步。具体可以后续参加双周会来了解或者看之前的[会议纪要](https://www.yuque.com/spring-cloud-alibaba/xgu1l3/pgmd2a)。

**Comment by steverao** [comment]
> > > 
> > 
> > 
> > 建议先去Spring Boot官方看看issue，就算Spring Cloud Alibaba短时间内推出Spring Boot 3.0，是否有信心去集成并上线？
> > https://github.com/spring-projects/spring-boot/issues?q=Spring+Boot+3
> 
> 不管他失不失败，历史的洪流总是要前进的。boot3很多新特性确实能带来跨域式的发展（个人认为）。总不能为了难而止步不前吧。。。永远都只坚守那一亩三分地。这和打仗一回事，敌人强大那就投降？？？？？你不愿意动，总有人愿意动，看到商机以及新的玩法，但对于坚守陈旧的总有可能被替代的一天。

首先他的意思是不要这么着急，短期内确实对企业用户来说升级不是一个最佳选择，个人用户另说，希望不要太激动！

**Comment by zxuanhong** [comment]
> 社区就是人手不够，而且目前3.0刚发，都不愿意踩坑，社区开源项目维护，人力，财力都不少呢，没有利益的驱使下，躺平，让他人先踩坑，也挺好的，实在受不了的，用spring官方的consul，替代。这边不等个大半年，没戏的。

你说的那些都理解，也都知道。我只是想说还不如发一个适配计划或规划来讨论实在，而不是讨论这个问题(当然除非不再支持)

**Comment by steverao** [comment]
> > 社区就是人手不够，而且目前3.0刚发，都不愿意踩坑，社区开源项目维护，人力，财力都不少呢，没有利益的驱使下，躺平，让他人先踩坑，也挺好的，实在受不了的，用spring官方的consul，替代。这边不等个大半年，没戏的。
> 
> 你说的那些都理解，也都知道。我只是想说还不如发一个适配计划或规划来讨论实在，而不是讨论这个问题(当然除非不再支持)

他不是社区的维护者，只是作为一个旁观者来留言的，并不是代表社区。另外这个issues的目的希望你理解并不是在讨论我们支持还是不支持，请你看清楚我发的相关信息。我们的目的是希望大家分享相关特性使用经验，帮助社区站在大家经验之上来更好更快的进行支持与适配。

**Comment by RebelTinker** [comment]
,预计会在什么时间可以发布GA版本
