### ISSUE TITLE
Optimize the code of nacos discovery example and add comments.

### ISSUE THREAD

**Issue by Phixsura** [alibaba/spring-cloud-alibaba#2931]
I found that there is still system output in the example code of Nacos discovery example, and I hope it can be optimized to log output. At the same time, I hope I can optimize the code specification and add comments to the code for reading.

**Comment by steverao** [comment]
We are welcome you to create a PR to optimize it.

**Comment by Phixsura** [comment]
I think this document also needs to be updated.
