### ISSUE TITLE
3个月了 还不发个版本吗

### ISSUE THREAD

**Issue by systemview2018** [alibaba/spring-cloud-alibaba#2937]
从2.2.7开始有好几个bug都导致功能不能用了。

**Comment by steverao** [comment]
2.2.7以后都发了4个新版本了，请看[发布公告](https://github.com/alibaba/spring-cloud-alibaba/releases)。

**Comment by systemview2018** [comment]
搞笑的吗。 一个log的issue，推了好几个月都不发版。 看看2.2.8以后的能用吗。
