### ISSUE TITLE
一个logger的issue，推了好几个月都不发版。看看2.2.8以后的能用吗。

### ISSUE THREAD

**Issue by systemview2018** [alibaba/spring-cloud-alibaba#2938]

**Comment by steverao** [comment]
Please provide relevant issue's url.

**Comment by systemview2018** [comment]
https://github.com/alibaba/spring-cloud-alibaba/pull/2788

这个问题，我想使用spring cloud stream的partition功能。 因为这个就用不了了

**Comment by steverao** [comment]
> #2788
> 
> 这个问题，我想使用spring cloud stream的partition功能。 因为这个就用不了了

We will release new version in future a week or two week.
