### ISSUE TITLE
nacos Ignore the empty nacos configuration and get it based on dataId[{}] & group[{}]

### ISSUE THREAD

**Issue by chenyao99** [alibaba/spring-cloud-alibaba#2944]
nacos默认加载配置通过${spring.cloud.nacos.config.name}加载一次，又通过${spring.cloud.nacos.config.name}+${spring.cloud.nacos.config.name.file-extension}加载一次。这两个配置一般来说都是主配置，个人觉得保留一个就可以了，这样重复加载有点过于繁杂。

**Comment by 123liuziming** [comment]
这个逻辑应该只是启动去拉取的时候会执行两次，代价不是很大，从设计角度讲这样的冗余应该是可以接受的

**Comment by ccenjie** [comment]
我觉得，从严谨角度讲，这里应该打debug日志
