### ISSUE TITLE
Is "spring-cloud-alibaba-sentinel-gateway" necessary in the gateway project?

### ISSUE THREAD

**Issue by Waylon-Firework** [alibaba/spring-cloud-alibaba#2946]
**Which Component**
Sentinel
```
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2021.1</version>
        </dependency>
```

**Describe what problem you have encountered**
The document said that we shoud add the 3 dependencies. But I test it and I found we don't need to add the `spring-cloud-alibaba-sentinel-gateway`. 

Q1: What is the function of this lib? 
Q2: Is it necessary?
Q3: When I set `spring.cloud.sentinel.filter.enabled=true`， the limiting function will not work. Is this expected?
Q4: I didn't see the api group rule menu in the sentinel dashboard.

```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
</dependency>

<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-gateway</artifactId>
</dependency>
```

https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel#spring-cloud-gateway-%E6%94%AF%E6%8C%81

**Comment by 123liuziming** [comment]
Q1:In the case of Spring Cloud Gateway, firstly the starter adds a GlobalFilter, which extracts the route and API group to which the request belongs, and adds the statistics to the corresponding sentinel resource. Secondly, the starter adds a global exception handler for Spring Cloud Gateway, if we catch a BlockException, we can execute our custom handler in this global exception handler.
Q2: I think it is useful when you use or develop Spring Cloud Gateway.
Q3: Please provide a little bit more detail information, your code, configuration and etc
Q4: Please contact with Sentinel community

**Comment by steverao** [comment]
Long time without response and close first.
