### ISSUE TITLE
When will it integrate with SpringBoot3

### ISSUE THREAD

**Issue by lzwt** [alibaba/spring-cloud-alibaba#2947]
When will it integrate with SpringBoot3

**Comment by Phixsura** [comment]
I think SCA officials may not have integrated SpringBoot3 so quickly. There are still many compatibility problems in SpringBoot3, which need to be fully considered in consideration of the use of most users. At the same time, many middleware are incompatible at present, and some mechanisms need to be reconsidered and optimized. All in all, it takes time.
