### ISSUE TITLE
Version selection

### ISSUE THREAD

**Issue by wangyandong1994** [alibaba/spring-cloud-alibaba#2952]
Spring Cloud Alibaba Version：2021.0.4.0
Spring Boot Version：2.7.5
Spring Cloud Version：2021.0.5
JDK Version:11.0.16.1
https://github.com/alibaba/spring-cloud-alibaba/wiki/版本说明 recommends Nacos Version: 2.0.4.
At present, the stable version recommended for the rapid start of nacos is 2.1.1.
What is the specific version recommendation?
If nacos uses version 2.1.1, such logs are always printed in the startup log. Will normal use be affected?
WARN There are no [com.alibaba.nacos.common.trace.event.naming.RegisterInstanceTraceEvent] publishers for this event, please register
WARN There are no [com.alibaba.nacos.common.trace.event.naming.SubscribeServiceTraceEvent] publishers for this event, please register
WARN There are no [com.alibaba.nacos.common.trace.event.naming.PushServiceTraceEvent] publishers for this event, please register

**Comment by ruansheng8** [comment]
这个和 `nacos-client` 版本无关 , 它是一个Nacos服务端事件追踪的功能模块 , 日志的警告不会影响正常使用 , 因为`nacos-server` 2.1.1 版本没有实现相关的`TraceEvent` , 2.1.2 版本已经解决了该问题 ,
