### ISSUE TITLE
com.alibaba.cloud.seata.feign.SeataFeignClientAutoConfiguration

### ISSUE THREAD

**Issue by enla5** [alibaba/spring-cloud-alibaba#2956]
![2022-12-10_020933](https://user-images.githubusercontent.com/49264147/206766281-4644dca1-c6ae-4ddb-b793-2a467fa5faae.png)

**Describe what problem you have encountered**
Error:Error:line (46)java: 找不到符号
符号:   变量 SeataSentinelFeignBuilder
位置: 类 com.alibaba.cloud.seata.feign.SeataFeignClientAutoConfiguration
**只要一编译这个demo就报错**😥
**有解决的同学吗🙋‍♂️🙋‍♀️**

**Comment by Phixsura** [comment]
Give you a few suggestions, maybe you can try them,
The first is to reload maven configuration, then use mvn clean install  at the terminal  and  re-run demo.
The second is to clean up the cache of idea. Perhaps the cache caused this problem.
If the above suggestions can't solve your problem, can you describe the situation where you encountered this problem? Which example are you running? I can try to reproduce your problem and see how to solve it.

**Comment by steverao** [comment]
Long time without response and close first.
