### ISSUE TITLE
The configuration of bootstrap.yaml will cause the problem of nospring.config.import property has been defined.

### ISSUE THREAD

**Issue by Phixsura** [alibaba/spring-cloud-alibaba#2958]
When I run some examples of integrated example in the 2021.x branch, I found that he would report one as no spring.config.import property has been defined.

`15:25:37.411 [main] DEBUG org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception
org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor$ImportException: No spring.config.import set
`

Based on this problem, I know that SrpingCloud has disabled Bootstrap in the 2020 version, in order to prevent the configuration from being repeatedly loaded and affecting the performance.

There are two solutions,
one is to introduce the following dependencies.
`
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
`
But I think this seems to be contrary to the original intention, so I think I can use the second method, that is, spring.config.import to solve this method. The following is my example to solve this problem in integrated gateway.

I created a yaml configuration file named nacos-config.
![image](https://user-images.githubusercontent.com/100568933/206838428-a53c0213-27a0-4f10-a450-868d7a9ffbd5.png)

Then I put all the configurations in bootstrap.yaml into my new application.yaml, and used spring.config.import to import nacos-related configurations.
![image](https://user-images.githubusercontent.com/100568933/206838588-c2871c45-ad0b-4cb1-9cbf-18842ab6a6c5.png)

After the above operation, the program can run normally.

#2905 And I found the relevant issue, but nothing seems to happen.

**Comment by steverao** [comment]
> When I run some examples of integrated example in the 2021.x branch, I found that he would report one as no spring.config.import property has been defined.
> 
> `15:25:37.411 [main] DEBUG org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception org.springframework.cloud.commons.ConfigDataMissingEnvironmentPostProcessor$ImportException: No spring.config.import set `
> 
> Based on this problem, I know that SrpingCloud has disabled Bootstrap in the 2020 version, in order to prevent the configuration from being repeatedly loaded and affecting the performance.
> 
> There are two solutions, one is to introduce the following dependencies. `<dependency> <groupId>org.springframework.cloud</groupId> <artifactId>spring-cloud-starter-bootstrap</artifactId> </dependency>` But I think this seems to be contrary to the original intention, so I think I can use the second method, that is, spring.config.import to solve this method. The following is my example to solve this problem in integrated gateway.
> 
> I created a yaml configuration file named nacos-config. ![image](https://user-images.githubusercontent.com/100568933/206838428-a53c0213-27a0-4f10-a450-868d7a9ffbd5.png)
> 
> Then I put all the configurations in bootstrap.yaml into my new application.yaml, and used spring.config.import to import nacos-related configurations. ![image](https://user-images.githubusercontent.com/100568933/206838588-c2871c45-ad0b-4cb1-9cbf-18842ab6a6c5.png)
> 
> After the above operation, the program can run normally.
> 
> #2905 And I found the relevant issue, but nothing seems to happen.

This is a bug, in branch of 2021.x, it requires using the default spring.config.import way to load external config. You can fix by referring to [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-2.4.x-example).

**Comment by sachinsude04** [comment]
if i put spring cloud starter bootstrap it reads 8888 port and run but config server service is running on 8095 port.\
so it can't create the connection with config server and didn't read the info from git
