### ISSUE TITLE
Nacos启动报错NacosRibbonClientConfiguration required a bean of type 'com.netflix.client.config.IClientConfig' that could not be found.

### ISSUE THREAD

**Issue by ljj0915** [alibaba/spring-cloud-alibaba#2967]
我的本地项目如果以com为开头。我发现Nacos就会去加载本地项目中是否包含com.netflix.client.config.IClientConfig这个类。
如果没有，就会报错。最简单的解决方案就是不以com为开头作为包路径。
我想了解下为什么会有这样的机制。

My local project starts with com. I found Nacos will be whether to load the local project contains com.net flix. Client. Config. IClientConfig this class.
If not, an error will be reported. The simplest solution is not to start with com as the package path.
I want to understand why this mechanism exists.

**Comment by Phixsura** [comment]
Please refer to #1902 .The discussion in this issue may solve your problem

**Comment by Phixsura** [comment]
Simply put, if you use com as a single-tier package to develop your business, this will add redundant scanning when loading the configuration, which may lead to problems as described by you

**Comment by ljj0915** [comment]
> Simply put, if you use com as a single-tier package to develop your business, this will add redundant scanning when loading the configuration, which may lead to problems as described by you

Thanks
