### ISSUE TITLE
Use new features of jdk17 to optimize code in 2022.x branch.

### ISSUE THREAD

**Issue by Phixsura** [alibaba/spring-cloud-alibaba#2971]
### BackGround
SpringCloudAlibaba's 2022.x branch is adapted to SpringBoot3 and jdk17. The leap between JDK8 and JDK17 has many new features, such as instanceof pattern matching, switch expressions, record classes, etc., which can reduce the amount of code, reduce maintenance costs, and improve performance. Next, I'll list new features that I think can optimize the 2022.x branch.

### instanceof pattern matching
The instanceof operator in Java is used to check the type of an object. The following code shows the code paradigm that typically uses the instanceof operator. Use instanceof in the if statement for checking, and if the check passes, use a cast to convert the input object obj to a String str, and finally use the variable str.
![image](https://user-images.githubusercontent.com/100568933/207393988-729719ce-34f9-427f-9a94-1c7791ea09fe.png)
As you can see from the above code, the paradigm of using the instanceof operator is very cumbersome, and the target type String that needs to be checked appears three times. With instanceof pattern matching, the code can be simplified a lot. In the following code, Strings represents the type pattern, where String is the type that needs to be matched and str is the variable used to capture the target object after the match is successful. The variable str can be used directly in an if statement block.
![image](https://user-images.githubusercontent.com/100568933/207394401-20b34fb1-5d70-4232-bf38-c5138a72a9d1.png)

### switch expressions
In JDK8 traditional switch has a long-term problem that has plagued users, Java's switch closely follows C and C++ languages, and supports fall through control by default. And the reason why the motivation for switching is enhanced is that while this traditional flow of control is often useful for writing low-level code (such as binary-encoded parsers), as switch is used in high-level contexts, its error-prone nature is starting to outstrip its flexibility. Many break statements make it unnecessarily verbose, and this visual noise often masks errors that are difficult to debug, where the absence of break statements means unexpected failure. As the following code example
![image](https://user-images.githubusercontent.com/100568933/207397371-4a7e5d49-194f-42a3-b2db-ce5c0e5b2b36.png)
Now the JDK introduces a new form of Switch tag "case L ->" to indicate that if the tag matches, only the code to the right of the tag is executed. Each case also allows multiple constants, separated by commas. The previous code can now be written as:
![image](https://user-images.githubusercontent.com/100568933/207398409-4b1c73ae-89a3-4be6-af6f-d687004f5af9.png)
The code to the right of the "case L ->" switch tag is limited to expressions, blocks, or (for convenience) throw statements, and many existing switch statements are essentially simulations of switch expressions, where each branch is either assigned to a common target variable or returns a value, in such a way that the statement is roundabout, repetitive, and error-prone, as shown in the following code:
![image](https://user-images.githubusercontent.com/100568933/207399635-f17f8878-7203-48c8-9a74-a7048189664e.png)
If we use the switch expression, the code is clear and secure, as follows:
![image](https://user-images.githubusercontent.com/100568933/207400146-2228637d-2e6f-415c-9e01-e49e03e6bdea.png)
Look, how simple and secure today's switch is. The switch expression has an expression to the right of the "case L ->" switch tag. If a complete block is needed, I can introduce a new yield statement to produce a value that becomes the value of the enclosing switch expression.

### text block
Text blocks is a syntax feature new in jdk15.Prior to jdk15, String objects were delimited using double quotes (single), while text blocks were delimited using three double quotes, and the syntax format was as follows:
![image](https://user-images.githubusercontent.com/100568933/207401577-10fa5dea-0bab-4c90-a576-02d3f6793e6d.png)
In the text block, the line terminator does not need to be escaped, so that we can declare a multi-line String object, which improves the readability of the program.Double quotation marks used to delimit string constants in a text block can appear directly without escaping.

The contents of the text blocks we declare are fully determined during compilation (when we write the code), which is rare in actual development. In the real world, we usually generate data based on user actions (such as input or drop-down list options, etc.), but how the user operates, we cannot predict during compilation, we need a solution.

For example, we dynamically generate text content for links based on user input:
![image](https://user-images.githubusercontent.com/100568933/207402832-3c0fe2f7-9ddf-411f-8745-e7d5fd8d1238.png)
As we can see, such a stitching is quite cumbersome, and since we do not adjust the indentation between multiple blocks of text and the String variable (link), the output of the program is not friendly. In this way, there is no advantage to using text blocks. Fortunately, though, we can solve this problem with the formatted method provided by the String class.
![image](https://user-images.githubusercontent.com/100568933/207403207-0dd8bfb4-322f-42be-b4f6-209b5996e8f8.png)

So much for my current examples, I'll add to the examples of record classes and sealed classes later.

**Comment by steverao** [comment]
By the way, in branch of 2022.x, we can add some necessary plugins and modify relevant readme.md documents in examples, so that users can build a native app and experience start speed of GraalVM. how to do can refer to [Spring Boot 3.0 document](https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/native-image.html).

**Comment by ayushdubey755** [comment]
Can I work on this issue?
@steverao @MieAh thank you for your insightful comment is there anything else should I know as the first time contributing to this project, I would love to work on it since I have previously used the spring framework and currently working on spring boot.
From which module I can start updating this new feature?

**Comment by ayushdubey755** [comment]
From which module i can start updating this new feature

**Comment by Phixsura** [comment]
@ayushdubey755 I'm very sorry because I didn't see your comments until now for some things before. You can refer to them first through the contribution guide in the document [Related links](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81). At present, these two new features, record classes and sealed classes, still need to be considered, because this may affect the sensory experience of many people. I suggest that you first optimize some parts of this project according to the text block feature of jdk17, which will also make you familiar with how to contribute.

**Comment by steverao** [comment]
We achieved it and close now.
