### ISSUE TITLE
spring.cloud.sentinel.transport.dashboard can not effective

### ISSUE THREAD

**Issue by toyr** [alibaba/spring-cloud-alibaba#2978]
**Which Component**
eg. Sentinel

**Describe what problem you have encountered**
Use spring.cloud.sentinel.transport Dashboard cannot register to sentinel,
Use sentinel.properties can register to sentinel

spring-boot-starter-parent version: 2.7.3
spring-cloud-alibaba-dependencies version: 2021.0.4.0

**Describe what information you have read**
[eg. I have read the reference doc of Sentinel](https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel)

**Comment by 123liuziming** [comment]
![image](https://user-images.githubusercontent.com/32130965/207806137-284b2634-0ad3-4f93-a462-905d46eff81f.png)
![image](https://user-images.githubusercontent.com/32130965/207806661-a188063a-3a85-4465-8a33-3968b6fbac70.png)
![image](https://user-images.githubusercontent.com/32130965/207806748-c153d073-314f-43f0-bdbc-789000a7f6fc.png)

I start a sentinel application and report it to a sentinel-dashboard, it seems ok. My sentinel-dashboard starts on port 8086.
application.yml:
```
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8086
```
Sentinel application code
```
package com.alibaba.scademo;


import com.alibaba.csp.sentinel.annotation.SentinelResource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class SentinelApplication {

	public static void main(String[] args) {
		SpringApplication.run(SentinelApplication.class, args);
	}
}

@Service
class TestService {

	@SentinelResource(value = "sayHello")
	public String sayHello(String name) {
		return "Hello, " + name;
	}
}

@RestController
class TestController {

	@Autowired
	private TestService service;

	@GetMapping(value = "/hello/{name}")
	public String apiHello(@PathVariable String name) {
		return service.sayHello(name);
	}
}
```
You may check your log in sentinel-dashboard, the log of my sentinel-dashboard which is initialized successfully is:
![image](https://user-images.githubusercontent.com/32130965/207807264-7637933a-3c2e-4c3d-9f20-33babbedeaf9.png)

**Comment by steverao** [comment]
Long time without response and close first.
