### ISSUE TITLE
Spring Cloud Alibaba Version	2021.0.4.0* 什么时候支持nacos-V2.2.0

### ISSUE THREAD

**Issue by Lvbuqing** [alibaba/spring-cloud-alibaba#2980]
nacos 2.2.0版本已经发布，
https://github.com/alibaba/nacos/releases/tag/2.2.0

Spring Cloud Alibaba Version2021.0.4.0官方推荐还是使用 Nacos Version 2.0.4，什么时候适配更新？

**Comment by steverao** [comment]
It needs some time. recently, we will release a version supporting Spring Boot 3.0 that brings a lot of changes. Taking stability into consideration,  we don't plan to adapt Nacos 2.2.0 in relevant version.

**Comment by Lvbuqing** [comment]
Nacos 2.2.0会向下兼容Spring Cloud Alibaba Version2021.0.4.0吗

**Comment by steverao** [comment]
> Nacos 2.2.0会向下兼容Spring Cloud Alibaba Version2021.0.4.0吗

In general, it's alright! But we don't test it. For this question, maybe you ask help for Nacos community that is appropriate.
