### ISSUE TITLE
Nacos config in other group dont work

### ISSUE THREAD

**Issue by Autrui** [alibaba/spring-cloud-alibaba#2981]
Nacos config

This is my dependence 
`        <spring-boot.version>2.6.11</spring-boot.version>
        <spring-cloud.version>2021.0.4</spring-cloud.version>
        <spring-cloud-alibaba.version>2021.0.4.0</spring-cloud-alibaba.version>
        <alibaba.nacos.version>2.0.4</alibaba.nacos.version>
`
as spring recommend to use spring.config.import , I put most config on nacos , I have same configuration on public namespace with DEFAULT_GROUP ，and the dev namespace with group dev. I can run my order module success when the spring.cloud.nacos.config.group use default. When I set the group: dev ,the idea show the configuration is empty.Here is my application.yml and the console.

`server:
  port: 8081

spring:
  application:
    name: order
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: f46302e3-f087-47a2-83a0-4b0484d5367b
        group: dev
        extension-configs:
      discovery:
        namespace: f46302e3-f087-47a2-83a0-4b0484d5367b
        group: learn
  config:
    import:
      - optional:nacos:order-dev.yaml
 `

`2022-12-15 11:05:53.347  WARN 11256 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[order] & group[DEFAULT_GROUP]
2022-12-15 11:05:53.350  WARN 11256 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[order.properties] & group[DEFAULT_GROUP]
2022-12-15 11:05:53.350  INFO 11256 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-order.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-order,DEFAULT_GROUP'}]
2022-12-15 11:05:53.353  INFO 11256 --- [           main] com.dwg.OrderApplication                 : No active profile set, falling back to 1 default profile: "default"
2022-12-15 11:05:53.363  WARN 11256 --- [           main] c.a.c.n.c.NacosConfigDataLoader          : [Nacos Config] config[dataId=order-dev.yml, group=dev] is empty
2022-12-15 11:05:53.756  INFO 11256 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=6d036264-6e63-319c-95ba-7e548b98a893
2022-12-15 11:05:53.922  INFO 11256 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)`

**Comment by Phixsura** [comment]
I tried to implement it using the version and configuration information you gave. I created a namespace for dev, and I created test.yaml with groups of DEFAULT_GROUP or dev in public and dev, respectively. But when I ran it, I found that there was no problem, and when I configured the group name and namespace for my configuration center to be dev, I could get the corresponding configuration. When I don't configure groups and namespaces, I can get the corresponding configurations.

Then I found that in the error message you gave, the dataId of the configuration of the listening external configuration is order-dev.yml, not the yaml file, maybe your configuration file name is wrong?
![image](https://user-images.githubusercontent.com/100568933/207806450-7c697321-c8d4-42b6-9caf-54ea8aabb950.png)
![image](https://user-images.githubusercontent.com/100568933/207806498-e713e021-995f-4e38-8ed1-5a76b8eddfc6.png)

**Comment by Autrui** [comment]
> 

That's my once try.Because this problem is really strange.
![image](https://user-images.githubusercontent.com/57823255/207808010-f92b74ab-6b77-4755-b5cc-c9ebe3968729.png)
Even it is yaml ，it still doesn't work

**Comment by Autrui** [comment]
> I tried to implement it using the version and configuration information you gave. I created a namespace for dev, and I created test.yaml with groups of DEFAULT_GROUP or dev in public and dev, respectively. But when I ran it, I found that there was no problem, and when I configured the group name and namespace for my configuration center to be dev, I could get the corresponding configuration. When I don't configure groups and namespaces, I can get the corresponding configurations.
> 
> Then I found that in the error message you gave, the dataId of the configuration of the listening external configuration is order-dev.yml, not the yaml file, maybe your configuration file name is wrong? ![image](https://user-images.githubusercontent.com/100568933/207806450-7c697321-c8d4-42b6-9caf-54ea8aabb950.png) ![image](https://user-images.githubusercontent.com/100568933/207806498-e713e021-995f-4e38-8ed1-5a76b8eddfc6.png)

That's my once try.Because this problem is really strange.
![image](https://user-images.githubusercontent.com/57823255/207808362-c85ba70b-86ed-48c8-b0e3-ce1025920555.png)
Even it is yaml ，it still doesn't work

**Comment by Phixsura** [comment]
> > I tried to implement it using the version and configuration information you gave. I created a namespace for dev, and I created test.yaml with groups of DEFAULT_GROUP or dev in public and dev, respectively. But when I ran it, I found that there was no problem, and when I configured the group name and namespace for my configuration center to be dev, I could get the corresponding configuration. When I don't configure groups and namespaces, I can get the corresponding configurations.
> > Then I found that in the error message you gave, the dataId of the configuration of the listening external configuration is order-dev.yml, not the yaml file, maybe your configuration file name is wrong? ![image](https://user-images.githubusercontent.com/100568933/207806450-7c697321-c8d4-42b6-9caf-54ea8aabb950.png) ![image](https://user-images.githubusercontent.com/100568933/207806498-e713e021-995f-4e38-8ed1-5a76b8eddfc6.png)
> 
> That's my once try.Because this problem is really strange. ![image](https://user-images.githubusercontent.com/57823255/207808362-c85ba70b-86ed-48c8-b0e3-ce1025920555.png) Even it is yaml ，it still doesn't work

I know where your problem lies, since SpringBoot 2.4 and later versions disable bootstrap dependencies, we need to manually refer to this bootstrap dependency or use spring.config.import. Instead, you choose to use spring.config.import and introduce bootstrap dependencies, which leads to the problem of not being able to listen to configuration files

Remove this dependency and your configuration file will be able to listen
![image](https://user-images.githubusercontent.com/100568933/207820430-6210bbd6-f573-4a84-8173-4fdc3d2264f2.png)

**Comment by steverao** [comment]
> 

In Spring Boot 2.4+, add `spring-cloud-starter-bootstrap` dependency and then use `spring.config.import` is alright.

**Comment by steverao** [comment]
> Nacos config
> 
> This is my dependence ` <spring-boot.version>2.6.11</spring-boot.version> <spring-cloud.version>2021.0.4</spring-cloud.version> <spring-cloud-alibaba.version>2021.0.4.0</spring-cloud-alibaba.version> <alibaba.nacos.version>2.0.4</alibaba.nacos.version>` as spring recommend to use spring.config.import , I put most config on nacos , I have same configuration on public namespace with DEFAULT_GROUP ，and the dev namespace with group dev. I can run my order module success when the spring.cloud.nacos.config.group use default. When I set the group: dev ,the idea show the configuration is empty.Here is my application.yml and the console.
> 
> `server: port: 8081
> 
> spring: application: name: order cloud: nacos: server-addr: localhost:8848 config: namespace: f46302e3-f087-47a2-83a0-4b0484d5367b group: dev extension-configs: discovery: namespace: f46302e3-f087-47a2-83a0-4b0484d5367b group: learn config: import: - optional:nacos:order-dev.yaml `
> 
> `2022-12-15 11:05:53.347 WARN 11256 --- [ main] c.a.c.n.c.NacosPropertySourceBuilder : Ignore the empty nacos configuration and get it based on dataId[order] & group[DEFAULT_GROUP] 2022-12-15 11:05:53.350 WARN 11256 --- [ main] c.a.c.n.c.NacosPropertySourceBuilder : Ignore the empty nacos configuration and get it based on dataId[order.properties] & group[DEFAULT_GROUP] 2022-12-15 11:05:53.350 INFO 11256 --- [ main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-order.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-order,DEFAULT_GROUP'}] 2022-12-15 11:05:53.353 INFO 11256 --- [ main] com.dwg.OrderApplication : No active profile set, falling back to 1 default profile: "default" 2022-12-15 11:05:53.363 WARN 11256 --- [ main] c.a.c.n.c.NacosConfigDataLoader : [Nacos Config] config[dataId=order-dev.yml, group=dev] is empty 2022-12-15 11:05:53.756 INFO 11256 --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory id=6d036264-6e63-319c-95ba-7e548b98a893 2022-12-15 11:05:53.922 INFO 11256 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 8081 (http)`

Please set group by `spring.config.import`. you can refer to our [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-2.4.x-example).

**Comment by Autrui** [comment]
> > Nacos config
> > This is my dependence ` <spring-boot.version>2.6.11</spring-boot.version> <spring-cloud.version>2021.0.4</spring-cloud.version> <spring-cloud-alibaba.version>2021.0.4.0</spring-cloud-alibaba.version> <alibaba.nacos.version>2.0.4</alibaba.nacos.version>` as spring recommend to use spring.config.import , I put most config on nacos , I have same configuration on public namespace with DEFAULT_GROUP ，and the dev namespace with group dev. I can run my order module success when the spring.cloud.nacos.config.group use default. When I set the group: dev ,the idea show the configuration is empty.Here is my application.yml and the console.
> > `server: port: 8081
> > spring: application: name: order cloud: nacos: server-addr: localhost:8848 config: namespace: f46302e3-f087-47a2-83a0-4b0484d5367b group: dev extension-configs: discovery: namespace: f46302e3-f087-47a2-83a0-4b0484d5367b group: learn config: import: - optional:nacos:order-dev.yaml `
> > `2022-12-15 11:05:53.347 WARN 11256 --- [ main] c.a.c.n.c.NacosPropertySourceBuilder : Ignore the empty nacos configuration and get it based on dataId[order] & group[DEFAULT_GROUP] 2022-12-15 11:05:53.350 WARN 11256 --- [ main] c.a.c.n.c.NacosPropertySourceBuilder : Ignore the empty nacos configuration and get it based on dataId[order.properties] & group[DEFAULT_GROUP] 2022-12-15 11:05:53.350 INFO 11256 --- [ main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-order.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-order,DEFAULT_GROUP'}] 2022-12-15 11:05:53.353 INFO 11256 --- [ main] com.dwg.OrderApplication : No active profile set, falling back to 1 default profile: "default" 2022-12-15 11:05:53.363 WARN 11256 --- [ main] c.a.c.n.c.NacosConfigDataLoader : [Nacos Config] config[dataId=order-dev.yml, group=dev] is empty 2022-12-15 11:05:53.756 INFO 11256 --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory id=6d036264-6e63-319c-95ba-7e548b98a893 2022-12-15 11:05:53.922 INFO 11256 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 8081 (http)`
> 
> Please set group by `spring.config.import`. you can refer to our [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-2.4.x-example).

You are right, after I remove the bootstrap dependence , I can read the application in other group ,and then I get anoter question. The reason I didnt  think of this is because i can load the application in the default group , I am curious about the why the application in default group can be loaded by spring.config.import even the bootstrap dependency also have.

**Comment by Phixsura** [comment]
Because of the introduction of bootstrap dependencies, the beans in NacosConfigBootstrapConfiguration were initialized first. Since bootstrap.yaml is not configured in the project, here NacosConfigProperties cannot obtain user-defined configuration information, the first NacosConfigProperties load can only have the initial configuration, ConfigService can only have a default configuration, and then the second NacosConfigProperties load is to have the correct configuration under application.yaml, but because ConfigService has been created , the configuration content cannot take effect, resulting in the pull configuration can only be obtained in localhost:8848, public namespace and DEFAULT_GROUP. This can be a good explanation for why your problem arises.

As shown in the figure below, this is where the configuration is loaded twice, and ConfigService will only be created according to the configuration that comes in the first time.
![image](https://user-images.githubusercontent.com/100568933/208337157-b59a3630-eabf-4dd2-8a35-e1ecf8ee7f44.png)

**Comment by Autrui** [comment]
> 因为因为引入了bootstrap依赖，所以所以先nacosconFigbootStrapConfiguration中bean bean bean。。。由于由于中中没有配置配置配置配置配置配置配置配置nacosconfigproperties加载好地解释为什么会出现现在的问题。
> 
> 如下图，这里是两次加载配置的地方，只会根据第一次进入的配置创建ConfigService。 ![图片](https://user-images.githubusercontent.com/100568933/208337157-b59a3630-eabf-4dd2-8a35-e1ecf8ee7f44.png)

Thank you very much,your explanation is very helpful to me.
