### ISSUE TITLE
the nacosDiscoveryProperties properties of NacosSeviceManager is null sometimes [2021.0.4.0]

### ISSUE THREAD

**Issue by Linzyoo** [alibaba/spring-cloud-alibaba#2982]
NacosDiscoveryAutoConfiguration : 
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnDiscoveryEnabled
@ConditionalOnNacosDiscoveryEnabled
public class NacosDiscoveryAutoConfiguration {

	@Bean
	**@ConditionalOnMissingBean**
	public NacosDiscoveryProperties nacosProperties() {
		return new NacosDiscoveryProperties();
	}
...
```

NacosServiceAutoConfiguration
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnDiscoveryEnabled
@ConditionalOnNacosDiscoveryEnabled
public class NacosServiceAutoConfiguration {

	@Bean
	public NacosServiceManager nacosServiceManager() {
		return new NacosServiceManager();
	}
}
```

And the only way to set nacosDiscoveryProperties property for NacosServiceManager Bean:
NacosDiscoveryProperties
```java
@PostConstruct
public void init() throws Exception {
  nacosServiceManager.setNacosDiscoveryProperties(this);
}
```

That means there is some possiblity that the nacosDiscoveryProperties of NacosServiceManager is null. Here is an example:
```java
    @Test
    public void testNacosServiceManager(){
        AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext();
        ctx.register(UtilIPv6AutoConfiguration.class, UtilAutoConfiguration.class);
        ctx.register(NacosServiceAutoConfiguration.class, NacosDiscoveryAutoConfiguration.class);
        ctx.refresh();

        AnnotationConfigApplicationContext childCtx = new AnnotationConfigApplicationContext();
        childCtx.setParent(ctx);
        childCtx.register(NacosServiceAutoConfiguration.class, NacosDiscoveryAutoConfiguration.class, NacosServiceRegistryAutoConfiguration.class);
        childCtx.refresh();

        NacosServiceRegistry registry = childCtx.getBean(NacosServiceRegistry.class);
        Registration registration = new MyRegistration();
        registry.register(registration);

    }
```
It throws NullPointerException as following
```
   java.lang.NullPointerException
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:46)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.namingService(NacosServiceRegistry.java:192)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:67)
	at com.example.test.NacosServiceManagerTest.testNacosServiceManager(NacosServiceManagerTest.java:33)
```

**Comment by steverao** [comment]
It's influenced by class load sequence, you test case isn't from Spring Cloud Alibaba. that isn't our code problem.

**Comment by Linzyoo** [comment]
The test case is not from Spring Cloud Alibaba, and it simulates the situation that the nacosdiscoveryproperrties property of NacosServiceMananger will be null when NacosServiceMananger is initialed in child context. As the post shows, the property of NacosServiceManager is only set when the NacosDiscoveryProperties be created. But the different lifecycle of two beans (NacosDiscoveryProperties - uniq in context including ancestors, and children, NacosServiceManager - uniq in current context), so the NacosDIscoveryProperties will not be created, and not set the property of NacosServiceManager when NacosServiceManager has a new bean in child context.

The issue is that the nacosdiscoveryproperrties property of NacosServiceManager    setting depends on the post construct of NacosDiscoveryProperty bean, while NacosServiceMananger bean has different scope of NacosDiscoveryProperty. When NacosServiceManager bean is created in Child context, the NacosDiscoveryProperty will not.
