### ISSUE TITLE
[Spring Boot 3.0 Adaptive] Integrated examples module

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2983]
背景说明
在 [integrated-example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/integrated-example) 中，有部分关于Spring Cloud Stream的内容，随着Spring Cloud依赖升级到了2022.0.0-RC版本，部分原来的老的使用方式已经失效了，因此需要替换成Reactive方式的形式。

如何做
具体可以参考 [rocketmq-example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/rocketmq-example) 模块进行调整。

Background
In [integrated-example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/integrated-example), there are parts about Spring Cloud Stream Content, with the Spring Cloud dependency upgrade to the 2022.0.0-RC version, some of the original old usage methods have become invalid, so they need to be replaced with the Reactive method.

How to do
For details, please refer to the [rocketmq-example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/rocketmq-example) module for adjustment.

**Comment by 123liuziming** [comment]
I will work on it
