### ISSUE TITLE
[Spring Boot 3.0 Adaptive] Build Native Image about example modules

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#2984]
背景说明
当前的 examples 模块由于都不是直接引入的 `spring-boot-starter-parent` 模块进行的构建，不能直接构建成为 Native Image。需要添加部分 plugin 以及对已存在 plugin 做一些调整，另外需要提供一份相关 Native Image 构建文档。

如何做
具体可以参考 [Spring Boot 3.0 相关文档](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.developing-your-first-application) 进行实现

Background
Since the current examples module is not built by the directly imported `spring-boot-starter-parent` module, it cannot be directly built into a Native Image. It is necessary to add some plugins and make some adjustments to the existing plugins. In addition, a related Native Image construction document needs to be provided.

How to do
For details, please refer to [Spring Boot 3.0 related documents](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.developing-your-first-application) to implement

**Comment by ruansheng8** [comment]
Ralated #2987
