### ISSUE TITLE
A null pointer occurred when sentinel got feignClientsRegistrarFactoryBean

### ISSUE THREAD

**Issue by twelvet-s** [alibaba/spring-cloud-alibaba#2994]
**Which Component**
Sentinel

**Describe the bug**
After the introduction of sentinel in version 2022, a null pointer will occur when fetching feignClientsRegistrarFactoryBean

Com.alibaba.cloud.sentinel.feign.SentinelFeign 90

**Comment by steverao** [comment]
Please provide relevant error log and tell us which Spring Cloud Alibaba's version you used.

**Comment by twelvet-s** [comment]
> Please provide relevant error log and tell us which Spring Cloud Alibaba's version you used.

2022.0.x version,Cannot invoke "org.springframework.cloud.openfeign.FeignClientFactoryBean.getFallback()" because "feignClientFactoryBean" is null

**Comment by twelvet-s** [comment]
> Please provide relevant error log and tell us which Spring Cloud Alibaba's version you used.

FeignClientFactoryBean feignClientFactoryBean = (FeignClientFactoryBean) def.getAttribute("feignClientsRegistrarFactoryBean");
The BeanDefinition obtained from the def in this line has been modified by Spring and is incompatible

**Comment by ruansheng8** [comment]
> > Please provide relevant error log and tell us which Spring Cloud Alibaba's version you used.
> 
> FeignClientFactoryBean feignClientFactoryBean = (FeignClientFactoryBean) def.getAttribute("feignClientsRegistrarFactoryBean"); The BeanDefinition obtained from the def in this line has been modified by Spring and is incompatible

hello , you can set `spring.cloud.openfeign.lazy-attributes-resolution` to `true` , maybe it can solve your problem.
and i will fix this issues tomorrow.

**Comment by twelvet-s** [comment]
> > > Please provide relevant error log and tell us which Spring Cloud Alibaba's version you used.
> > 
> > 
> > FeignClientFactoryBean feignClientFactoryBean = (FeignClientFactoryBean) def.getAttribute("feignClientsRegistrarFactoryBean"); The BeanDefinition obtained from the def in this line has been modified by Spring and is incompatible
> 
> hello , are you trying to use `spring-aot` for your project ? if not , set `spring.aot.enabled` to `false` can solve your problem. when `spring.aot.enabled` is set to `true` , spring-aot will be enabled . and sentinel does not yet support the feign on `spring-aot mode` , it will be supported in the next version.

OK, thank you very much. I will try it
