### ISSUE TITLE
spring-cloud-bus-rocketmq-example has recurring dependencies

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3006]
在我解决#2961问题的时候，发现spring-cloud-bus-rocketmq-example的pom.xml文件中引入了两次相同的依赖

![~UC4R SB99K5%D3PL81 WY5](https://user-images.githubusercontent.com/77964041/209269004-b55200db-a5aa-4395-a599-7aaf5921a5e8.png)

**Comment by steverao** [comment]
> 在我解决#2961问题的时候，发现spring-cloud-bus-rocketmq-example的pom.xml文件中引入了两次相同的依赖
> 
> ![~UC4R SB99K5%D3PL81 WY5](https://user-images.githubusercontent.com/77964041/209269004-b55200db-a5aa-4395-a599-7aaf5921a5e8.png)

Please create a PR to delete redundant content.
