### ISSUE TITLE
感觉2022适配是一个全新的的版本,包括jdk等等,是否可以将一些过期引用等等直接迁移至新的版本

### ISSUE THREAD

**Issue by dujie-js** [alibaba/spring-cloud-alibaba#3013]
感觉社区在做兼容历史版本会花费大量的时间,而现阶段企业级一般都是jdk8为主,主要使用的是2.2.x版本基线,
是否可以通过Spring 和jdk的这次升级让2022.x版本完全去除掉里的历史的版本兼容呢,本身Spring的这次升级也严格限制了17为最低版本
企业级的依旧大部分是jdk1.8

**Comment by steverao** [comment]
没有特别明白你的描述，过期引用直接迁移直新版本什么意思呢？另外历史版本问题指的是什么？

**Comment by dujie-js** [comment]
就是相关调用的过期方法之类的

**Comment by steverao** [comment]
> 就是相关调用的过期方法之类的

这块社区优先处理了一些过期并在本次升级中已失效的一些用法，比如Spring Cloud Stream注解进行消息发送与接受，还能使用的过期方法暂时未替换，欢迎参与到社区一起来完成相关工作。
