### ISSUE TITLE
IPv4 to IPv6 address migration way

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3014]
We need to provide a method to help enterprises realize the smooth migration of the large-scale Spring Cloud Alibaba microservice system IP address stack from IPv4 to IPv6. The specific method is to achieve migration through dual registration and double subscription. The specific migration steps of this solution are as follows:
1. First, upgrade the Spring Cloud Alibaba framework for all microservice applications in the system to enable them to have dual-stack address extraction and resolution functions.
2. Transform the IP address protocol stack of the host machine where some microservices in the system are located, so that it supports dual-stack IPv4 and IPv6 addresses at the same time.
3. The dual-stack address extraction module in the microservice application modified in step 2 extracts the dual-stack addresses in the application host, and registers the dual-stack addresses to the registration center through the service registration module.
4. Consumers subscribe to the dual-stack IPv4 and IPv6 addresses of a service in the registration center, and compare the address stack types supported by the host through the dual-stack address resolution module in the application. If the host only supports IPv4, use The provider’s IPv4 address initiates a service call; if only IPv6 is supported or dual-stack is supported at the same time, the provider’s IPv6 address is used to initiate a service call. If the call fails, it is best to use the IPv4 address to retry.
5. When all Spring Cloud microservices in the system have completed supporting the IPv6 address stack, gradually close the IPv4 address stack for all application hosts, thereby smoothly completing the migration of the large-scale microservice system from the IPv4 address stack to the IPv6 address stack .

## IPv4地址向IPv6地址迁移方案
我们需要提供一种帮助企业实现大规模Spring Cloud Alibaba微服务系统IP地址栈从IPv4平滑迁移到IPv6的方法，具体方法就是双注册双订阅实现迁移，该方案的具体迁移步骤：
1. 首先对所有的系统中的微服务应用进行Spring Cloud Alibaba框架升级，让其具备双栈地址提取和解析功能。
2. 对系统中的部分微服务所在宿主机进行IP地址协议栈改造，让其同时支持双栈IPv4和IPv6地址。
3. 经过步骤2改造的微服务应用中的双栈地址提取模块，提取应用宿主机中的双栈地址，并通过服务注册模块，将双栈地址都注册到注册中心。
4. 消费者订阅注册中心中的某个服务的双栈IPv4和IPv6地址，通过应用中的双栈地址解析模块，比对宿主机所支持的地址栈类型，如果宿主机仅支持IPv4，则使用提供者的IPv4地址发起服务调用；如果仅支持IPv6或同时支持双栈，则用提供者的IPv6地址发起服务调用，调用失败最好能使用IPv4地址进行重试。
5. 当系统中的所有Spring Cloud微服务都完成支持IPv6地址栈的支持后，逐步对所有应用宿主机关闭IPv4地址栈，从而平滑完成大规模微服务系统从IPv4地址栈到IPv6地址栈的迁移。

**Comment by sollhui** [comment]
please assign to me

**Comment by steverao** [comment]
We finished it.
