### ISSUE TITLE
How soon can Spring CloudAlibaba support Spring Cloud-2021.0.5 and nacos-2.2.0 be released

### ISSUE THREAD

**Issue by Comven** [alibaba/spring-cloud-alibaba#3019]
As shown in the title, the most used version is spring boot-2. x, so I hope that the Spring Cloud Alibaba component can follow up in a timely manner after the release of new versions of the Nacos client and Spring Cloud.

**Comment by steverao** [comment]
This is our [milestone plan](https://github.com/alibaba/spring-cloud-alibaba/milestone/22).
