### ISSUE TITLE
📣 Spring Cloud Alibaba unified console

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3025]
Regarding the Spring Cloud Alibaba unified console, what do you expect?

1. Can create traffic limiting and downgrading rules and query service registration information in the console?
2. Can common microservice governance rules through the console?

In the near future, Alibaba Open Source will build a console suitable for a variety of open source middleware. If you have any expectations, you can leave a message below.

**Comment by Phixsura** [comment]
I hope to integrate the console of all the middleware used in SCA, and sometimes it is more troublesome to look at it separately, and the benefits of integration are naturally relatively large.
