### ISSUE TITLE
datasource.ds1.file.file 加载本地规则文件，打包后报错

### ISSUE THREAD

**Issue by ylwang66** [alibaba/spring-cloud-alibaba#3033]
1、加载类路径下的规则，本地启动没有问题，打包在linux运行会出现问题
![image](https://user-images.githubusercontent.com/32428245/210525634-b42699c7-3b16-4c95-8604-2a6e93e559fc.png)

2、会说文件找不到
![image](https://user-images.githubusercontent.com/32428245/210525800-4810853f-c9fa-4f5b-9709-1a14fb886b8d.png)

3、究其原因是因为用了ResourceUtils.getFile("classpath:flowrule.json");  如何解决
![image](https://user-images.githubusercontent.com/32428245/210526025-f9a4056c-d5a8-4f79-9796-55ff67b1dbab.png)

**Comment by ruansheng8** [comment]
Related https://github.com/alibaba/Sentinel/pull/646 , https://github.com/alibaba/Sentinel/issues/3018

This may require the `Sentinel` community to provide a `Spring Resource` mode.
