### ISSUE TITLE
Update Spring Boot to 2.6.13 in Spring Cloud Alibaba 2021.x branch

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3039]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software.

Which Component
eg. Spring Boot,

Is your feature request related to a problem? Please describe.
We are prepared to release a new version of Spring Cloud Alibaba in 2021.x branch, we are plan to update some components.

Describe the solution you'd like
Update Spring Boot to 2.6.13 in Spring Cloud Alibaba 2021.x branch, and test the reliability.

**Comment by yuluo-yx** [comment]
I want to try it, please assign me!

**Comment by steverao** [comment]
> 

Great! Please finish it today, we plan to release tomorrow.

**Comment by yuluo-yx** [comment]
Hello, when I updated the spring boot and nacos versions, it was appropriate for me to change the boot version to 2.6.13 in the local test, but the github integration test reported an error in the `spring cloud circuitbreaker sentinel`. See #3048

**Comment by steverao** [comment]
> Hello, when I updated the spring boot and nacos versions, it was appropriate for me to change the boot version to 2.6.13 in the local test, but the github integration test reported an error in the `spring cloud circuitbreaker sentinel`. See #3048

There is something wrong, we will fix it!

**Comment by steverao** [comment]
We solved it in #3054 , you can try again now.

**Comment by yuluo-yx** [comment]
> We solved it in #3054 , you can try again now.

Ok! I try it now.

**Comment by yuluo-yx** [comment]
> We solved it in #3054 , you can try again now.

The code passed the test. Please see #3059

**Comment by yuluo-yx** [comment]
The Spring Boot version has been upgraded to version 2.6.13 in the 2021 branch
