### ISSUE TITLE
Unit Test error

### ISSUE THREAD

**Issue by sollhui** [alibaba/spring-cloud-alibaba#3042]
unit test has different result. The results of multiple tests may be different

**Comment by steverao** [comment]
You should copy the specific failed case in the issue in order to solve it later.

**Comment by HHoflittlefish777** [comment]
![Uploading image.png…]()

**Comment by sollhui** [comment]
the error test:ReactiveSentinelCircuitBreakerIntegrationTest,more detail can refer to #3029

**Comment by steverao** [comment]
We solved it in https://github.com/alibaba/spring-cloud-alibaba/pull/3054.
