### ISSUE TITLE
do not support comment in json?

### ISSUE THREAD

**Issue by gMan1990** [alibaba/spring-cloud-alibaba#3043]
https://github.com/alibaba/spring-cloud-alibaba/blob/92d7be80d844ce60daaa1b8023e11a599d4528b5/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosJsonPropertySourceLoader.java#L64

```json
{
    "a": 1, // test case
    "b": 2
}
```

**Comment by ruansheng8** [comment]
It's not a valid JSON format

**Comment by gMan1990** [comment]
@ruansheng8 yep. 但是在`nacos-server` web console 上往json配置里写入 comment 也没提示报错。jackson也支持 `com.fasterxml.jackson.core.JsonParser.Feature#ALLOW_COMMENTS`

**Comment by ruansheng8** [comment]
@gMan1990 感谢反馈 , 后续会考虑增加一个配置开关来支持这个功能
