### ISSUE TITLE
spring-cloud-bus-rocketmq-example Introduced duplicate dependencies

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3049]
在`spring-cloud-alibaba` 2021.x 分支中的`spring-cloud-bus-rocketmq-example` 引入了两次相同的依赖，
如下图：
![image](https://user-images.githubusercontent.com/77964041/210753765-c5a001d7-fcdd-47d0-80f5-a48f24ddb28b.png)

**Comment by yuluo-yx** [comment]
I removed duplicate dependencies, see #3050

**Comment by steverao** [comment]
The issue was solved and close now.
