### ISSUE TITLE
When the sidecar service is registed in nacos, the port is the value of sidcar.port, why?

### ISSUE THREAD

**Issue by MuAndDao** [alibaba/spring-cloud-alibaba#3060]
Nacos Discovery, Sidecar

![image](https://user-images.githubusercontent.com/19743480/210977127-058ad557-e36b-43ec-9525-c9bd7cc83a0b.png)
![image](https://user-images.githubusercontent.com/19743480/210977343-804b3b19-e537-4743-b7cc-4433684ee437.png)
As showed in the picture. the port of the instance is 80 , not 8099, is that right? 
And should the ip value of the instance be the value of sidecar.ip or the value of sidecar service???

**Comment by galaxy-sea** [comment]
hello @RealMuDao。Sidecar does not provide load balancing. Sidecar only registers the IP, ports, metadata of heterogeneous services to nacos。

**Comment by MuAndDao** [comment]
so what the ip should be?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月08日 09:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alibaba/spring-cloud-alibaba] When the sidecar service is registed in nacos, the port is the value of sidcar.port, why? (Issue #3060) |

hello @RealMuDao。Sidecar does not provide load balancing. Sidecar only registers the IP, ports, metadata of heterogeneous services to nacos。

**Comment by galaxy-sea** [comment]
sidecar.ip should fill in the IP address of heterogeneous services

**Comment by MuAndDao** [comment]
> 
And should the ip value of the instance be the value of sidecar.ip or the value of sidecar service???

**Comment by MuAndDao** [comment]
@galaxy-sea

**Comment by MuAndDao** [comment]
![image](https://user-images.githubusercontent.com/19743480/211258462-fcf60985-1b8c-4ee0-9891-8d403b292501.png)
I do not understand the code here, why the value of sidecar.ip is discarded?

**Comment by galaxy-sea** [comment]
@RealMuDao What version of Spring Cloud Alibaba is used

**Comment by MuAndDao** [comment]
my sidecar version is 2021.0.1.0

**Comment by galaxy-sea** [comment]
@RealMuDao You're right. It looks like a bug.

**Comment by galaxy-sea** [comment]
@RealMuDao This bug has been fixed, but a new version has not been released
see [commit](https://github.com/alibaba/spring-cloud-alibaba/commit/8576e90af1dc26e61c3ca53c41ddb6f3dcf9e5c7)

**Comment by MuAndDao** [comment]
Looking forward to you fixing this soon!

| |
Young
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/9/2023 15:53 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [alibaba/spring-cloud-alibaba] When the sidecar service is registed in nacos, the port is the value of sidcar.port, why? (Issue #3060) |

@RealMuDao You're right. It looks like a bug.

**Comment by MuAndDao** [comment]
This means I have to use the version 2022.x?

**Comment by galaxy-sea** [comment]
> This means I have to use the version 2022.x?

yes

**Comment by steverao** [comment]
The problem was solved and released in 2022.0.0.0-RC1 and close now.
