### ISSUE TITLE
seate-example run failed

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3071]
### question
When I run 'spring-cloud-alibaba-example seate-example', when I change the database password to my own, I get the following exception 'Access denied for user 'root'@'localhost' (using password: YES)'

### reason
I debugged the source code and found that the problem was that when yml processed the database password, it would convert numbers starting with 0 to base 8, causing database connection problems

### Problem solving
I think it should be in the yml config file, enclosing the username and password in single quotes.

If this issue needs to be modified, please assign it to me and I will fix it!

**Comment by steverao** [comment]
It means your password is wrong!

**Comment by yuluo-yx** [comment]
> It means your password is wrong!

I don't quite understand, meaning my password is wrong, or in the case of this example, my password is wrong.

**Comment by steverao** [comment]
> 'Access denied for user 'root'@'localhost' (using password: YES)'

You can type the error log `'Access denied for user 'root'@'localhost' (using password: YES)'` in search engine, it's a  well known error information in MySQL.

**Comment by yuluo-yx** [comment]
> > '拒绝用户'root'@'localhost'的访问（使用密码：YES）'
> 
> 你可以在搜索引擎中输入错误日志`'Access denied for user 'root'@'localhost' (using password: YES)'`，它是MySQL中众所周知的错误信息。

Yes, but I'm pretty sure my password is correct, it's '082916',
The fundamental problem I want to express is that in YML, the configuration information of strings containing special symbols needs to be quoted in quotation marks, otherwise YML will parse into other information, such as starting with 0 in YML will be recognized as an 8-base number, which does not match the database password, resulting in this error!

**Comment by yuluo-yx** [comment]
> > '拒绝用户'root'@'localhost'的访问（使用密码：YES）'
> 
> 你可以在搜索引擎中输入错误日志`'Access denied for user 'root'@'localhost' (using password: YES)'`，它是 MySQL 中众所周知的错误信息。

Please see https://blog.csdn.net/m0_55849362/article/details/126738163,  
I think that for normalization, usernames and passwords should be put in quotation marks to guarantee their correctness

**Comment by steverao** [comment]
> > > '拒绝用户'root'@'localhost'的访问（使用密码：YES）'
> > 
> > 
> > 你可以在搜索引擎中输入错误日志`'Access denied for user 'root'@'localhost' (using password: YES)'`，它是 MySQL 中众所周知的错误信息。
> 
> Please see https://blog.csdn.net/m0_55849362/article/details/126738163, I think that for normalization, usernames and passwords should be put in quotation marks to guarantee their correctness

Ok, I understand your idea. You can create a PR to fix it, I misunderstand it because of your issues name firstly.

**Comment by yuluo-yx** [comment]
Okay, I'll finish it. Will pay attention to the accuracy of the problem name in the future!

**Comment by yuluo-yx** [comment]
I have updated the yml file format of the 2022.x branch. Please see #3095 
In addition, I also formatted the code using the equals, isNull, and nonNull methods in Objects. As shown in the PR, I didn't test the code locally, everything was done in the web version of vscode.
I will deal with the yml format of other branches as soon as possible.
