### ISSUE TITLE
SCA 2022.0.0.0可以跳过直接上SCA 2022.0.0.1，对接新出来的spring cloud 2022.0.1

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/spring-cloud-alibaba#3116]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

  spring cloud 2022.0.1，Spring boot 3.0.2已发布，主要是修复bug，但SCA最新的版本规划2022.0.0不好对应spring cloud 2022.0.1，可否考虑直接跳过SCA 2022.0.0，直接上SCA 2022.0.1，也可以节约时间去开发2个版本，一定要的话可以SCA 2022.0.0和SCA 2022.0.1同时发布。谢谢
  

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by steverao** [comment]
It can't skip 2022.0.0.0, because, we released relevant RC version. We will evaluate the timeline about you mentioned two version later.

**Comment by StringKe** [comment]
目前下一个正式版本什么时候发布呢？

**Comment by zzhujing** [comment]
when release 2022.0.0.0 ?  i just feel RC2  version support  GraalVM not great , manual collect metadata always produce all kinds of mistakes ...
