### ISSUE TITLE
gateway docking sentinel use spring-cloud-alibaba-sentinel-gateway csp.sentinel.app.type configuration is not easy to use.

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#3123]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

sca 2021.0.4.0
sentinel 1.8.6

Debug see `spring-cloud-alibaba-sentinel-gateway` `SentinelSCGAutoConfiguration`  `initAppType` function has been executed
But the console does not take effect

![image](https://user-images.githubusercontent.com/31852897/215380431-a358d4cd-482b-43f3-a258-59343fc9aa04.png)
![image](https://user-images.githubusercontent.com/31852897/215380399-cce2906d-4547-4382-9240-fcb74c8795f1.png)

Copy the content of this method to the main method at the beginning.
Console takes effect

![image](https://user-images.githubusercontent.com/31852897/215380479-722ed931-ccfa-4372-8410-afe2604d7fe2.png)
![image](https://user-images.githubusercontent.com/31852897/215380712-06d06163-9292-4b38-9d0f-ef015696460c.png)

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by 123liuziming** [comment]
I 've reproduced it, the sentinel gatewayFlow rule took effect, but the sentinel dashboard does not show the gateway flow control rule. You can submit a issue to Sentinel community. @sczyh30

**Comment by sczyh30** [comment]
Please check the order of Sentinel initialization (implicit, or eagerly explicit in SCA) and `initAppType` in gateway starter.

**Comment by JavaLionLi** [comment]
>  Please check the order of Sentinel initialization (implicit, or eagerly explicit in SCA) and `initAppType` in gateway starter.

![image](https://user-images.githubusercontent.com/31852897/216018278-3c8feed9-609b-412f-ba4e-15846d2f983a.png)
All other configurations default
