### ISSUE TITLE
在sleuth跟踪链路的前提下,spring-cloud-starter-stream-rocketmq接收消息 header类型转换错误

### ISSUE THREAD

**Issue by chen-junl** [alibaba/spring-cloud-alibaba#3124]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
spring-cloud-starter-stream-rocketmq

**Describe the bug**
使用@StreamListener接收消息的时候,在sleuth追踪链路开启的情况下 报错
` nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map, failedMessage=GenericMessage [payload=byte[8046], headers={ROCKET_MQ_FLAG=0, ROCKET_MQ_SYS_FLAG=1, ROCKET_MQ_QUEUE_ID=0, ROCKET_KEYS=guoyuan_1, b3=e0abbd2e137d8c92-d11d73b4c41fb477-1, nativeHeaders={b3=[e0abbd2e137d8c92-9dd11d85f6fdd72f-1]}, ROCKET_TAGS=resource_guoyuan, ROCKET_MQ_BORN_TIMESTAMP=1675068845421, ROCKET_MQ_MESSAGE_ID=7F000001D81018B4AAC298F8D96D0012, ROCKET_MQ_TOPIC=chenjl, METHOD=UPDATE, ROCKET_MQ_BORN_HOST=192.168.55.1, id=3fff8cf1-ecd7-4f27-369c-6db987bbff10, contentType=application/json, timestamp=1675070463377}]`

**Expected behavior**
能够正常接收sleuth的链路信息

**Screenshots**
错误信息
![image](https://user-images.githubusercontent.com/38237837/215448744-a88c5272-e2a5-42d8-86c2-92af7c3f61cf.png)
![image](https://user-images.githubusercontent.com/38237837/215448864-2a40c7cc-2bc0-4bd0-9c96-e5005f03d8c0.png)
debug调试  nativeHeaders字符串无法转为map
![image](https://user-images.githubusercontent.com/38237837/215449394-d2ca2e85-a7c3-4194-b85f-e63bd364e134.png)

**Additional context**
spring-cloud-starter-stream-rocketmq  2021.0.1.0
spring-cloud-starter-sleuth 3.1.1

如果配置

**Comment by steverao** [comment]
There is a similar problem solved in 2021.0.4.0, you can try by upgrading dependency version. Relevant PR you can refer to #2571

**Comment by chen-junl** [comment]
> This problem was solved in 2021.0.4.0, you can try by upgrading dependency version. Relevant PR you can refer to #2571

pring-cloud-starter-stream-rocketmq 2021.0.4.0版本还是没有效果,依然会报错, 就是没有兼容HeaderMethodArgumentResolver中的getNativeHeaders这个方法
![image](https://user-images.githubusercontent.com/38237837/215693446-6f162fa1-44f9-4170-aff1-ac1237b05bfc.png)

**Comment by chen-junl** [comment]
> This problem was solved in 2021.0.4.0, you can try by upgrading dependency version. Relevant PR you can refer to #2571

在开启sleuth的前提下 消息发送的时候nativeHeaders的类型是是Map
![image](https://user-images.githubusercontent.com/38237837/215697510-6f3696af-1399-423e-b897-f7447b11e053.png)

但是消息接收的时候 就已经转为String
![image](https://user-images.githubusercontent.com/38237837/215697636-417277ef-6a1b-4799-96ca-c54c183abdb9.png)

这时再把string转为map就报错了

**Comment by yuluo-yx** [comment]
Can you provide a complete demo example, or illustrate the version of `Spring Cloud` and `Spring Cloud Alibaba` used in your pom file?

**Comment by chen-junl** [comment]
> Can you provide a complete demo example, or illustrate the version of Spring Cloud and Spring Cloud Alibaba used in your pom file?

spring-cloud-stream 3.2.2
spring-cloud-starter-stream-rocketmq 2021.0.1.0
spring-cloud-starter-sleuth 3.1.1
![image](https://user-images.githubusercontent.com/38237837/216505525-53681f01-8b96-4c2f-89de-b02b907ce62e.png)

**Comment by yuluo-yx** [comment]
> > Can you provide a complete demo example, or illustrate the version of Spring Cloud and Spring Cloud Alibaba used in your pom file?
> 
> spring-cloud-stream 3.2.2 spring-cloud-starter-stream-rocketmq 2021.0.1.0 spring-cloud-starter-sleuth 3.1.1 ![image](https://user-images.githubusercontent.com/38237837/216505525-53681f01-8b96-4c2f-89de-b02b907ce62e.png)
I can't accurately reproduce your problem scenario locally, and in my existing situation, my code runs normally...
![image](https://user-images.githubusercontent.com/77964041/216520043-c87e52a7-c9ab-4cb6-af33-58c7e2115496.png)
Please provide your message body class structure.
**I recommend breaking down your project into the minimum module needed to replicate the problem and provide the GitHub repository address so that the problem scenario can be accurately reproduced**

**Comment by chen-junl** [comment]
> > > Can you provide a complete demo example, or illustrate the version of Spring Cloud and Spring Cloud Alibaba used in your pom file?
> > 
> > 
> > spring-cloud-stream 3.2.2 spring-cloud-starter-stream-rocketmq 2021.0.1.0 spring-cloud-starter-sleuth 3.1.1 ![image](https://user-images.githubusercontent.com/38237837/216505525-53681f01-8b96-4c2f-89de-b02b907ce62e.png)
> > I can't accurately reproduce your problem scenario locally, and in my existing situation, my code runs normally...
> > ![image](https://user-images.githubusercontent.com/77964041/216520043-c87e52a7-c9ab-4cb6-af33-58c7e2115496.png)
> > Please provide your message body class structure.
> > **I recommend breaking down your project into the minimum module needed to replicate the problem and provide the GitHub repository address so that the problem scenario can be accurately reproduced**


demo项目
https://github.com/cjl111/starter-stream-rocketmq-test

调用接口发送消息
![image](https://user-images.githubusercontent.com/38237837/216542567-6730d44d-1e54-4bca-8d41-77c7732e073d.png)
接收消息仍然报错
![image](https://user-images.githubusercontent.com/38237837/216542724-b1451a1b-bac9-4c3a-9282-4ee9db104dcd.png)
![image](https://user-images.githubusercontent.com/38237837/216542750-f9dfcac2-fba4-44af-9863-558b051f4742.png)

**Comment by yuluo-yx** [comment]
> > > > 能否提供一个完整的demo例子，或者说明一下你的pom文件中使用的Spring Cloud和Spring Cloud Alibaba的版本？
> > > 
> > > 
> > > spring-cloud-stream 3.2.2 spring-cloud-starter-stream-rocketmq 2021.0.1.0 spring-cloud-starter-sleuth 3.1.1
> > > 我无法在本地准确复现你的问题场景，在我现有的情况下，我的代码运行通常...
> > > 请提供您的消息正文类结构。**我建议将你的项目分解成复现问题所需的最小模块，并提供GitHub仓库地址，以便准确复现问题场景**![图像](https://user-images.githubusercontent.com/38237837/216505525-53681f01-8b96-4c2f-89de-b02b907ce62e.png)
> > > ![图像](https://user-images.githubusercontent.com/77964041/216520043-c87e52a7-c9ab-4cb6-af33-58c7e2115496.png)
> > > ****
> 
> demo项目 https://github.com/cjl111/starter-stream-rocketmq-test
> 
> 调用接口发送消息 接收消息仍然报错 ![图像](https://user-images.githubusercontent.com/38237837/216542567-6730d44d-1e54-4bca-8d41-77c7732e073d.png) ![图像](https://user-images.githubusercontent.com/38237837/216542724-b1451a1b-bac9-4c3a-9282-4ee9db104dcd.png) ![图像](https://user-images.githubusercontent.com/38237837/216542750-f9dfcac2-fba4-44af-9863-558b051f4742.png)

Well, the community is going to talk about this.

**Comment by haitachi** [comment]
私たちも同様の問題に直面しました。どう解決すればよいでしょうか？

**Comment by haitachi** [comment]
?
