### ISSUE TITLE
springcloud gateway整合nacos读取不到配置文件

### ISSUE THREAD

**Issue by yujunchengg** [alibaba/spring-cloud-alibaba#3130]
version：springcloud Hoxton.SR9 + spring-cloud-alibaba-dependencies 2.2.6.RELEASE
question:  use nacos to manage gateway routing information,but it does not work,when gateway server started, unable to read configuration

![gatewayproperties](https://user-images.githubusercontent.com/36986915/215931036-fa9f9e84-2c27-4412-b96d-f270eac24961.png)
the following image shows the configuration of bootstrap. yml
![bootstrap yml](https://user-images.githubusercontent.com/36986915/215931738-69234fed-11c5-49a8-9b7e-fd5073ed2305.png)
the following image shows the configuration in nacos
![gateway](https://user-images.githubusercontent.com/36986915/215931982-0811baee-9916-444a-b77a-3c0be91b60d6.png)

**Comment by 123liuziming** [comment]
You can refer to https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md. It seems that you do not set the spring.config.import field in bootstrap.yml?

**Comment by yujunchengg** [comment]
> You can refer to https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md. It seems that you do not set the spring.config.import field in bootstrap.yml?

nacos version in spring-cloud-alibaba-dependencies 2.2.6.RELEASE is 1.4.2

**Comment by 123liuziming** [comment]
please refer to https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md.  It only supports properties, yaml is not supported. I just turned it to properties configuration, and it works!
![image](https://user-images.githubusercontent.com/32130965/215990257-efec3648-8016-40bd-a923-9938ed1630c2.png)

![image](https://user-images.githubusercontent.com/32130965/215990113-0930b6d6-7bfd-4e89-9b9f-c9a3369af63d.png)

**Comment by 123liuziming** [comment]
Configuration in nacos is as below:
```
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.cloud.gateway.routes[0].id=base
spring.cloud.gateway.routes[0].uri=lb://base
spring.cloud.gateway.routes[0].predicates[0]=Path=/base/**
```

**Comment by yujunchengg** [comment]
file-extension: yml, I forgot to configure this
