### ISSUE TITLE
Nacos-Client log print to application logs, not print to nacos' log

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/spring-cloud-alibaba#3133]
**Which Component**
Nacos Discovery/Config

**Describe the bug**
Relative issue #1931.

After the issue fix problem, the problem fixed by some old version.

But in some new version, the problem started again. After my debug and research. I fount that the problem is caused by the spring will call the `LoggingSystem.initialize` from `PropertySourceBootstrapConfiguration` after all `ApplicationEnvironmentPreparedEvent`.

But `NacosLoggingListener` in Nacos Discovery/Config only handle `ApplicationEnvironmentPreparedEvent` not loadConfiguration again after `PropertySourceBootstrapConfiguration`. So the log config still be overwrite by spring.

**To Reproduce**
1. Go to 'nacos-discovery-spring-cloud-config-client-example' in tag `2.2.9.RELEASE`
2. Run on 'SpringCloudConfigClientApplication'
3. See nacos client log print into console.

**Expected behavior**
nacos client log print into ${user.home}/naming.log or config.log 

**Screenshots**

**Additional context**
MacOS  、Java8 、 Version 2.2.6.RELEASE ~ 2.2.9.RELEASE

I don't test for 2021.X and 2022.X. Please community to check and fix.

**Comment by wang3develop** [comment]
# Environment 环境

- JDK:17
- SpringToolSuite:4.17.0.release
- spring.cloud.version:2022.0.1/2022.0.0
- spring.cloud.alibaba.version:2022.0.0.0-RC1

# Launch启动

![图片](https://user-images.githubusercontent.com/44887680/217155176-d8d5dc86-9670-4185-bbfa-55139ab19169.png)



# Question问题

  我在YAML、PROPERTIES、JVM、ENV尝试了配置参数都不能令其消失，这应该如何进行配置？
  I tried configuration parameters in YAML，PROPERTIES，JVM and ENV but couldn't make them disappear. What should I do?

**Comment by ruansheng8** [comment]
In `Spring Boot 2.4` and later versions, `StaticLoggerBinder` was removed from `logback-classic 1.3.x` version, so it will cause `NoClassDefFoundError` exception.

See more details: https://github.com/alibaba/nacos/issues/9970

**Comment by ruansheng8** [comment]
The console logs are not printed correctly to the nacos log file because the `LogbackLoggingSystem` reset the `LoggerContext` in the `prepareContext` phase of the SpringApplication. Fixed in PR #3160
