### ISSUE TITLE
Support the Dubbo RPC protocol?

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3134]
Due to some problems in the design of the Spring Cloud Dubbo module, the value of related functions has not been clear, resulting in a complicated design, and few users can use it normally. However, as a microservice framework, Dubbo provides a `Dubbo RPC protocol` that does have certain performance advantages over http. The community hopes to know whether external users have any appeals for the Spring Cloud Alibaba community to access the Dubbo protocol, so that users can use OpenFeign Or RestTemplate uses the http protocol for service call dependencies, or uses the above annotations to use the Dubbo protocol.

If we support Dubbo RPC protocol, the module will be named `spring-cloud-starter-dubbo-rpc-protocol`? 
About this proposal, what do you think? Welcome to leave a message below.

**Comment by DanielLiu1123** [comment]
Spring Cloud and Dubbo belong to two different ecologies and use different communication protocols. Forcing the integration of two different protocols will lead to significant maintenance costs in the future.

My suggestion is that Dubbo should have better intergration with Spring Boot as an RPC framework, not Spring Cloud.

**Comment by ruansheng8** [comment]
Although `Dubbo` provides a relatively comprehensive suite of ecosystem components, many users still utilize a mix of `Dubbo` and `Spring Cloud` in their projects. 

Integrating Dubbo into Spring Cloud Alibaba may require consideration of the following issues : 
1. Compatibility with `SCA Governance` module.
2. Whether to retain only the `RPC` and `Load Balancing` capabilities of Dubbo.

**Comment by funky-eyes** [comment]
> Although `Dubbo` provides a relatively comprehensive suite of ecosystem components, many users still utilize a mix of `Dubbo` and `Spring Cloud` in their projects.
> 
> Integrating Dubbo into Spring Cloud Alibaba may require consideration of the following issues :
> 
> 1. Compatibility with `SCA Governance` module.
> 2. Whether to retain only the `RPC` and `Load Balancing` capabilities of Dubbo.

I think so too, but I hope sca can get the service's protocol from dubbo's metadata, which will allow sca to support multiple protocol calls, such as tri, dubbo

**Comment by kaori-seasons** [comment]
cc @steverao @ruansheng8 @a364176773 @DanielLiu1123
related to https://github.com/apache/dubbo/issues/10803
For the implementation of obtaining information from dubbo metadata, please refer to [PR#11017](https://github.com/apache/dubbo/pull/11017/files#diff-0b838fed016d55371f31c20710724d29050e3e2bfbe983e1202e997029fffd60) and [PR#11098](https://github.com/apache/dubbo/pull/11098/files#diff-6b4332ce9d09bc77ec9acd7d0f24d9d3b5facf4c8bc9564f033b3b480d30f0f7).

In [PR#11017](https://github.com/apache/dubbo/pull/11017/files#diff-0b838fed016d55371f31c20710724d29050e3e2bfbe983e1202e997029fffd60) , first transform the logic of obtaining RestMetadataService, and then add AbstractNoAnnotatedParameterProcessor based on dubbo in [PR#11098](https://github.com/apache/dubbo/pull/11098/files#diff-6b4332ce9d09bc77ec9acd7d0f24d9d3b5facf4c8bc9564f033b3b480d30f0f7) to register the metadata in it to the runtime context of dubbo. We can refer to the partial implementation of dubbo Spring's [PR#11098](https://github.com/apache/dubbo/pull/11098/files#diff-6c1d10b978b4408032377e2ebccd1ed744614992b31258be0288e110780693b9)
