### ISSUE TITLE
Spring Cloud Alibaba Kubernetes Config module artifactId

### ISSUE THREAD

**Issue by DanielLiu1123** [alibaba/spring-cloud-alibaba#3137]
## Which artifactId should we choose?

`spring-cloud-starter-alibaba-kubernetes-config` or `spring-cloud-starter-kubernetes-config`.

If we use `spring-cloud-starter-kubernetes-config`, it looks like a module of [Spring Cloud Kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes), but have a different groupId.

```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-config</artifactId>
</dependency>
```

**Comment by yuluo-yx** [comment]
我认为这样命名更好：`spring-cloud-starter-alibaba-kubernetes-config`

**Comment by steverao** [comment]
补充一点，Spring Cloud Alibaba社区经过社区Steering Committee管理委员会提议与投票决定，从2023年起，社区新模块命名规则按照：`spring-cloud-starter-(组件所属公司名)-(组件名)-功能名(子功能名)`
进行模块命名，其中（）内容表示非必须可省略，子功能名最多一级。

例如：`spring-cloud-starter-alibaba-nacos-config`符合以上命名规则，alibaba是组件所属公司名，nacos是组件名，config是功能名。该issue所讨论的kubernetes是由Google开发捐献给了CNCF基金会，所以命名可以叫:`spring-cloud-starter-kubernetes-config`，只是会跟[Spring Cloud Kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes)该项目中的一个组件artifactId相同，但是groupId还是不同的（另外这个组件改项目命名新版本已经不在使用，而是在2.0版本以后替换成了`spring-cloud-kubernetes-fabric8-config`，确实叫`spring-cloud-starter-kubernetes-config`也有可能引起用户搜索依赖时的困扰）。
![image](https://user-images.githubusercontent.com/25423978/216754201-5d03e26a-6383-47d7-a045-4050431c2012.png)

**Comment by ruansheng8** [comment]
以 `spring-cloud-starter-kubernetes-config` 命名的话，可能会让用户以为这两个是同一个项目（虽然他们的`groupid`不同，但实际上大多数情况下只关注`artifactid`）。

例如`Dubbo`项目从`Alibaba`组织迁移到`Apache`组织，其实是同一个项目，只不过后续新版本在`Apache`维护：
![image](https://user-images.githubusercontent.com/24709538/216890664-85953241-480b-4cd0-a418-1d8def7c844c.png)

**Comment by DanielLiu1123** [comment]
I prefer `spring-cloud-starter-alibaba-kubernetes-config`.

**Comment by steverao** [comment]
After the community discussion at the weekly meeting on February 16, it was decided to use `spring-cloud-starter-alibaba-kubernetes-config` to name the new module. This module naming exists as a special case that violates the current community new module naming rules.
