### ISSUE TITLE
 Modify the weight in the Nacos 2.1.0 console input box, which is not effective in Dubbo 2.7.21

### ISSUE THREAD

**Issue by November22** [alibaba/spring-cloud-alibaba#3145]
**Which Component**
Nacos 2.1.0 
![image](https://user-images.githubusercontent.com/26109828/217137052-bbbf89bb-0624-448d-a592-e3ec1a78fe79.png)

**Describe what problem you have encountered**

Modifying the weight does not take effect

**Describe what information you have read**
After reading the source code, the content is shown in the figure

The weight information delivered by Nacos is in the field weight
![image](https://user-images.githubusercontent.com/26109828/217137735-035e5db1-99da-4083-b9e2-5bae5d6fed99.png)

Dubbo 2.7.21 is not used when splicing URL information
![image](https://user-images.githubusercontent.com/26109828/217137972-2ee7f82c-162e-43de-9b11-f16a1e1889bb.png)

**Comment by steverao** [comment]
This is a Dubbo relevant problem, please go to the Dubbo community to ask questions.

**Comment by November22** [comment]
sorry ，wrong place
