### ISSUE TITLE
A question about com.alibaba.cloud.nacos.NacosConfigManager. Is it a bug?

### ISSUE THREAD

**Issue by me0106** [alibaba/spring-cloud-alibaba#3148]
The ConfigService object 'service' in the NacosConfigManager that the Nacos configuration listens to uses static variables.

![image]( https://user-images.githubusercontent.com/22869648/218425649-392e63cf-4a78-4768-bb37-583d1b845a8d.png )

This results in that if multiple NacosConfigManager coexist, the first NacosConfigManager will overwrite all other NacosConfigManager.

Does this meet expectations? .

-- 

Nacos配置监听的NacosConfigManager中ConfigService对象`service`使用的是静态变量。
![image](https://user-images.githubusercontent.com/22869648/218425649-392e63cf-4a78-4768-bb37-583d1b845a8d.png)

这导致如果多个NacosConfigManager并存的情况下，第一个ConfigService会覆盖所有的其他ConfigService。

这符合预期吗。

**Comment by steverao** [comment]
Add Spring Cloud Alibaba's specific module dependencies, and you can directly get the only NacosConfigManager object through dependency injection. How can you have multiple objects?

**Comment by me0106** [comment]
I want to monitor configuration files under multiple namespaces, so I created multiple NacosConfigManager ...

**Comment by steverao** [comment]
> I want to monitor configuration files under multiple namespaces, so I created multiple NacosConfigManager ...

We don't recommend to monitor configuration in an application under multiple namespaces. Because, the concept of namespace is designed to make application isolation in different environment. If you want to achieve it, you can use Nacos Client to create multiple ConfigService objects to do that.

**Comment by steverao** [comment]
Long time without response and close firstly.
