### ISSUE TITLE
Does the latest version of spring cloud alibaba have an example of integrating dubbo

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3153]
Does the latest version of spring cloud alibaba have an example of integrating dubbo.
we need to do that.
any help for me?

**Comment by yuluo-yx** [comment]
Perhaps you can find some inspiration in these two warehouses:
- https://github.com/aliyun/alibabacloud-microservice-demo
- https://github.com/yuhuangbin/spring-cloud-alibaba-samples

**Comment by steverao** [comment]
Long time without response and close now.

**Comment by imgoby** [comment]
the version of sca is too old.
