### ISSUE TITLE
Provide the docker-compose file in integration-example to create the run sample environment

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3164]
**Is your feature request related to a problem? Please describe.**
I suggest providing `docker-compose` file in `integration-example` to provide a basic environment for running example instead of creating a runtime environment locally.
Similar to `compoent-quickstart.yml` in `appactive-example`.
![image](https://user-images.githubusercontent.com/77964041/220323191-b868853a-8318-42e0-a63a-990fc5278edb.png)

**Comment by steverao** [comment]
We also provide helm way now. In Kubernetes, it very convenient. But docker compose is necessary. Thank you for your mention.

**Comment by yuluo-yx** [comment]
> We also provide helm way now. In Kubernetes, it very convenient. But docker compose is necessary. Thank you for your mention.

Happy to contribute to that!
