### ISSUE TITLE
can you upgrade the 2021 branch version,for example: seata,nacos...?

### ISSUE THREAD

**Issue by markr512** [alibaba/spring-cloud-alibaba#3169]

**Comment by yuluo-yx** [comment]
Do you want to upgrade the version of components such as nacos and seata in the 2021.x branch to the latest or?

**Comment by yuluo-yx** [comment]
Relatively speaking, the relevant components we use are the latest versions of the components that are currently available. You can use our latest release version 2022.x. 
Or do you have any good ideas that we can discuss together.

**Comment by markr512** [comment]
My project uses springboot 2.6.x, alibaba Cloud only use 2021 branch 
I hope 2021 branch can only upgrade seata, nacos and other software version
Thank you!

**Comment by steverao** [comment]
We have relevant plan, you can refer to https://github.com/alibaba/spring-cloud-alibaba/milestone/22
