### ISSUE TITLE
spring-cloud-alibaba-dependencies版本切换到2021.0.4.0后无法读取到nacos配置

### ISSUE THREAD

**Issue by 112921482** [alibaba/spring-cloud-alibaba#3183]
spring-cloud-alibaba-dependencies版本切换到2021.0.4.0后无法读取到nacos配置，之前用2021.0.1.0没问题

**Comment by yuluo-yx** [comment]
请参考[`nacos-config-example`](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example)示例，我们确保示例可以正常运行！
