### ISSUE TITLE
Spring Gateway在使用Nacos配置中心，某个Gateway的Bean被加载时会读不到配置信息，对Nacos加载配置有些疑问

### ISSUE THREAD

**Issue by perfumescent** [alibaba/spring-cloud-alibaba#3190]
**Which Component**
Nacos Config
依赖包是spring-cloud-starter-alibaba-nacos-config-2021.0.1.0

**Describe what problem you have encountered**
大佬们好！有疑问需要咨询一下！问题如下
# 问题描述
我在搭建Spring Gateway服务时，使用Nacos来记录配置。具体的，我是在application.yml+application-dev.yml两个文件里放了连接nacos的初始配置，然后在nacos server上放所有其他的配置。程序可以正常启动，最后日志也显示服务注册和配置读取成功。

但是，发现gateway里的一个bean没有加载。

断点追踪后发现，是spring准备加载这个bean时，发现已加载的所有配置信息里没有gateway的配置，于是根据```@ConditionalOnProperty```的规则就没有加载这个bean。如下图，此时环境信息里没有从nacos server来的信息。

![Untitled](https://user-images.githubusercontent.com/31856209/222065254-a03785ed-5eca-478d-b469-17f64ed24e18.png)

然后我看日志最开始三行是由nacos发出，但是是warn信息，如下图。

![Untitled](https://user-images.githubusercontent.com/31856209/222068247-f2b256cc-97d3-4b49-ac21-455fe80a5ae2.png)

所以此前是有nacos加载配置的。断点追踪后发现，最开始nacos是在向本地的127.0.0.1:8848发送请求，也就是说使用的默认配置。
再次断点发现，如下所示，spring最先是通过NacosConfigBootstrapConfiguration下的```nacosConfigProperties()```来new一个默认的配置对象NacosConfigProperties，并注入到spring容器里。然后127.0.0.1:8848等默认配置信息就来自于这个无参构造的对象。
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(name = "spring.cloud.nacos.config.enabled", matchIfMissing = true)
public class NacosConfigBootstrapConfiguration {

	@Bean
	@ConditionalOnMissingBean
	public NacosConfigProperties nacosConfigProperties() {
		return new NacosConfigProperties();
	}

	@Bean
	@ConditionalOnMissingBean
	public NacosConfigManager nacosConfigManager(
			NacosConfigProperties nacosConfigProperties) {
		return new NacosConfigManager(nacosConfigProperties);
	}

	@Bean
	public NacosPropertySourceLocator nacosPropertySourceLocator(
			NacosConfigManager nacosConfigManager) {
		return new NacosPropertySourceLocator(nacosConfigManager);
	}

}
```
我再去看了NacosConfigProperties这个类，发现会在NacosConfig**Bootstrap**Configuration和NacosConfig**Auto**Configuration这两个配置类的方法```nacosConfigProperties()```中被注入到spring里。重新启动再打断点发现，NacosConfig**Bootstrap**Configuration会先启动，注入一个默认配置，NacosConfig**Auto**Configuration后启动，注入一个从本地application.yml读取的配置（此时上下文里是有nacosConfigProperties这个bean的，内容是默认配置）。

# 疑问
1. 我也不太懂spring跟nacos的原理，像这样先加载NacosConfig**Bootstrap**Configuration，再加载NacosConfig**Auto**Configuration，这个顺序就是固定的吗，是故意设计的吗？
2. 我也不知道是不是使用用问题。像我这种情况，相当于nacos通过NacosConfig**Bootstrap**Configuration直接注入一个死对象。我看代码就感觉，是不是每个系统使用都会先用这个死对象去请求127.0.0.1:8848？为什么不通过```@ConfigurationProperties```+```@Component```来注入带自定义配置的NacosConfigProperties对象呢？我问了几个别的系统，好像都有这种warn日志，而这个日志似乎就是因为访问127.0.0.1:8848后拿到返回数据为空而报出来的。
```
2023-03-01 10:51:12.976 [main] WARN  c.a.cloud.nacos.client.NacosPropertySourceBuilder:87  - Ignore the empty nacos configuration and get it based on dataId[ucenter-gateway] & group[DEFAULT_GROUP] 
```
3. 我看NacosConfig**Bootstrap**Configuration和NacosConfig**Auto**Configuration这两个配置类的```nacosConfigProperties()```上都有注解```@ConditionalOnMissingBean```，按理说当spring里有nacosConfigProperties这个bean的时候，就不应该继续注入新的nacosConfigProperties了吧？可是我调试时候发现，这两个类下的```nacosConfigProperties()```方法都走进来了。不知道是我哪里理解错了。

我真的很菜，第一次用，遇到这个问题，感觉自己有点钻牛角尖了。可能这个提问能看出来我基础很差，还请大佬们不喜勿喷...

**Comment by steverao** [comment]
Loading twice is not as expected. Your problem is similar with #2981.

**Comment by 123liuziming** [comment]
> Loading twice is not as expected. Your problem is similar with #2981.
![image](https://user-images.githubusercontent.com/32130965/222363251-e730f5f5-839d-4e14-bfb0-91b0ed94cb62.png)
![image](https://user-images.githubusercontent.com/32130965/222363677-249c51dc-70e0-4d79-b6ee-d33241dc5bac.png)

![image](https://user-images.githubusercontent.com/32130965/222365795-e8fa5713-ddd7-436c-b8c0-00044828cb89.png)

加载两次应该是正常的，在Bootstrap上下文会被优先加载，之后加载Spring的上下文，这两个Spring容器是父子关系。
![image](https://user-images.githubusercontent.com/32130965/222364264-a54813d0-1e08-4d9d-88fe-39054fae998d.png)
这个ConditionalOnMissingBean指定了范围为current，所以不会去父上下文找有没有此类bean，所以也会被加载。

**Comment by steverao** [comment]
Normally, it should only need to be loaded once. Loading twice is because the `spring-cloud-starter-gateway` dependency is added, but the `bootstrap.yaml` information is not configured, resulting in the use of the default configuration, and the configuration center information configured in `application.yaml` cannot be accessed. I can delete `spring-cloud-starter-gateway` in your `pom.xml` to solve the problem.

**Comment by 1113126226** [comment]
兄弟，你后面怎么解决的，我也遇到这个问题了

**Comment by 1113126226** [comment]
兄弟，你后面怎么解决的，我也遇到这个问题了

**Comment by perfumescent** [comment]
> 兄弟，你后面怎么解决的，我也遇到这个问题了

加那个bootstrap的依赖后，用bootstrap.yaml来写nacos的配置，不用application.yaml
