### ISSUE TITLE
Are there plans to upgrade the nacos version to 2.2.0.1 ?

### ISSUE THREAD

**Issue by dylan-tao** [alibaba/spring-cloud-alibaba#3195]
**Which Component**
Nacos Discovery, Config

**Is your feature request related to a problem? Please describe.**
Are there plans to upgrade nacos version to 2.2.0.1 in Cloud-2021.0.5.0?

**Describe the solution you'd like**
Update new version.

**Describe alternatives you've considered**
None.

**Additional context**
A more stable service base.

**Comment by yuluo-yx** [comment]
Your question is the same as #3169, you can refer to #3169.
In addition, We have relevant plan, you can refer to https://github.com/alibaba/spring-cloud-alibaba/milestone/22.

**Comment by dylan-tao** [comment]
thanks
