### ISSUE TITLE
failed to req API:/nacos/v1/ns/service/list

### ISSUE THREAD

**Issue by zhonghuazhi** [alibaba/spring-cloud-alibaba#3196]
当使用 getNamingService().getServicesOfServer(1, 100) 、 getNamingService().getAllInstances()，获取某个服务实例的详细信息 、 获取所有服务实例列表的时候，提示这个 failed to req API:/nacos/v1/ns/service/list

提前是 nacos 开启了认证。
nacos.core.auth.enabled=true

**Comment by steverao** [comment]
This is nacos problem, It means that your authentication failed. You can refer to the Nacos documentation to see how to carry the authentication information in the request. If you don't know how to solve it, please create a PR to Nacos community.
