### ISSUE TITLE
dubbo一直发送rocketmq消息，Topic=dubboProtocolConfigSupplier

### ISSUE THREAD

**Issue by zhirong-ning** [alibaba/spring-cloud-alibaba#3198]
spring-cloud-alibaba 2021.0.1.0 版本下，spring-cloud-starter-dubbo和spring-cloud-starter-stream-rocketmq同时使用时，如果rocketmq没有配置消费队列的时候，dubbo会不断的发送rocketmq消息Topic=dubboProtocolConfigSupplier。

![screenshot-20230308-170234](https://user-images.githubusercontent.com/127295336/223669582-514c8d45-3b99-4e5c-a1c4-081537b9f972.png)

**Comment by yuluo-yx** [comment]
> 

Consider providing a minimal demo that can reproduce the problem. Convenient community students to repeat and solve problems.

**Comment by yuluo-yx** [comment]
It is worth mentioning that you can modify some of the words in issues such as: dobbo,dobo -> dubbo, etc

**Comment by zhirong-ning** [comment]
> 

The problem still exists
