### ISSUE TITLE
spring-boot 2.7.1版本开启鉴权 报403 unknown user!

### ISSUE THREAD

**Issue by OldOldLiu** [alibaba/spring-cloud-alibaba#3199]
<spring.boot.version>2.7.1</spring.boot.version>
<spring.cloud.version>2021.0.3</spring.cloud.version>
<alibaba.cloud.version>2021.0.1.0</alibaba.cloud.version>
Nacos客户端版本2.2.0

![c0bafefb5296f3b7808da098a9d93ec](https://user-images.githubusercontent.com/31083659/224050225-9f8bc336-722c-4ebb-80b1-f516812386c1.png)

我看了下版本说明
spring-boot 2.7.x的 全家桶版本没找到
这个全家桶版本该怎么修改?

**Comment by yuluo-yx** [comment]
Hello, not sure what you mean? Is Nacos authentication incorrect, or is Spring Security used? 
From the stack exception, it seems to be a Nacos problem. Check whether the user configuration in the configuration file is correct.
Also, see the community's release notes for collocation.
[版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)
