### ISSUE TITLE
Add docker support in SCA example

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3202]
**Which Component**
eg. `Spring Clouud Alibaba Example`

**Is your feature request related to a problem? Please describe.**
Add docker support to the sample module.
To eliminate tedious steps when you need to run multiple components locally at the same time.
For example, in the Seta-example, you need to start three components locally at the same time: mysql5.7, nacos2.1, and Seta-Server 1.5.0. The creation process is tedious.

**Describe the solution you'd like**
Add docker-compose support in the various example modules

**Comment by steverao** [comment]
We completed it and close now.
