### ISSUE TITLE
Springcloud服务启动异常，code=403,msg=unknown user

### ISSUE THREAD

**Issue by miaoyahong** [alibaba/spring-cloud-alibaba#3210]
配置信息如图
![image](https://user-images.githubusercontent.com/30410291/225343067-72b94a13-b0b7-4704-8f1b-2808d06a4ab1.png)

JDK17，依赖如下
[image](https://user-images.githubusercontent.com/30410291/224733118-db36acba-e2bb-4b18-aac9-d6bda15701f0.png)
[image](https://user-images.githubusercontent.com/30410291/224732817-156cfd8b-a90e-47bd-be4d-1bb8ac5ea7a2.png)
报错信息
![image](https://user-images.githubusercontent.com/30410291/225343229-a6ebf991-188f-4a16-a9ab-86c5f7d764a6.png)
我debugger一下发现启动时NacosConfigProperties的init方法被执行了三次，第一次没有注入配置信息，后面两次有注入
![image](https://user-images.githubusercontent.com/30410291/225343282-007774d0-b5e6-4bbd-92d2-8d8cfac096b8.png)
![image](https://user-images.githubusercontent.com/30410291/225343334-fd770904-4f8c-4451-a8d1-9ce11df97210.png)
但是服务注册是正常的
![image](https://user-images.githubusercontent.com/30410291/225343392-6d68c7f7-1c25-4ba4-83e1-8d054073b6c5.png)

**Comment by steverao** [comment]
Please create an issue according to issue template next time, your information is incomplete. Please give us a simplest demo that contains project's pom.xml and resource module to reproduce it.

**Comment by usedssl** [comment]
他的注入是没问题的，被@PostConstruct会在初始化bean的initializeBean()时候调用element.invoke,方法为被注解修饰的方法（在被定义为bd的时候）。

**Comment by usedssl** [comment]
然后nacos希望配置为spring.cloud.nacos.name /password为服务自带的密码 或 auth验证，而配置里面是spring.cloud.nacos.config.username  和 password 你少了一个config

**Comment by yllstudy** [comment]
新建一个项目，想简单实现nacos服务发现功能。项目依赖版本如下图，nacos服务安装版本是2.0.4，开启了鉴权。服务启动后提示不知道用户。
<img width="344" alt="pom依赖" src="https://github.com/user-attachments/assets/24de7c37-7e18-44fb-953e-8ce13724e711">
![Uploading nacos配置.png…]()
