### ISSUE TITLE
How to upgrade dubbo2 to 3

### ISSUE THREAD

**Issue by Lingzhou314** [alibaba/spring-cloud-alibaba#3212]
**Which Component**
spring-cloud-alibaba.2.2.6.RELEASE

**Describe what problem you have encountered**
我们很多服务都是使用的 spring-cloud://nacos-url 来注册使用dubbo服务，所以我不能直接升级成dubbo3，如何在不改动旧服务的情况下兼容 dubbo3 的新服务
Many of our services use spring-cloud://nacos-url to register for the Dubbo service, so I cannot upgrade to Dubbo3 directly. How can I be compatible with the new service of Dubbo3 without changing the old service?

**Describe what information you have read**
我之前已经问过dubbo社区的解决方案，他们说不支持兼容升级，需要由sca这边处理兼容升级
I have previously asked the Dubbo community about the solution, and they said that compatibility upgrades are not supported and need to be handled by the sca side

**Comment by HelloToGithub** [comment]
spring-cloud-alibaba后续版本已经将spring-cloud-starter-dubbo去除了 
https://github.com/alibaba/spring-cloud-alibaba/issues/2398 
建议可以升级spring-cloud-alibaba 如2021.0.4.0同时Dubbo部分升级为apache的dubbo3
```scala
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-bom</artifactId>
    <version>3.1.8</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<!-- dubbo -->
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-spring-boot-starter</artifactId>
</dependency>

```             
  这样也可以将spring-cloud-alibaba和dubbo 版本进行独立维护/

**Comment by steverao** [comment]
We don't maintain module of `spring-cloud-starter-dubbo` with main branch now, you can refer to https://github.com/alibaba/spring-cloud-alibaba/issues/2398.
If you don't use relevant ability in module of `spring-cloud-starter-dubbo`. you can try to update dubbo module alone by upgrading following dependency. Maybe you need to deal with some problems from compatibility
```pom.xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo</artifactId>
    <version>3.x.x</version>
</dependency>
```

**Comment by Lingzhou314** [comment]
> spring-cloud-alibaba后续版本已经将spring-cloud-starter-dubbo去除了 #2398 建议可以升级spring-cloud-alibaba 如2021.0.4.0同时Dubbo部分升级为apache的dubbo3
> 
> ```scala
> <dependency>
>     <groupId>org.apache.dubbo</groupId>
>     <artifactId>dubbo-bom</artifactId>
>     <version>3.1.8</version>
>     <type>pom</type>
>     <scope>import</scope>
> </dependency>
> 
> 
> <dependency>
>     <groupId>org.apache.dubbo</groupId>
>     <artifactId>dubbo-spring-boot-starter</artifactId>
> </dependency>
> ```
> 
> 这样也可以将spring-cloud-alibaba和dubbo 版本进行独立维护/
我了解后续版本已经移除了，也了解之前的注册方式有问题，现在你们已经分道扬镳了，就连examples里都没有集成dubbo的例子了，所以后续版本也完全不考虑兼容dubbo升级的问题了吗，#2398 这里的解决方案是需要改造旧服务加一层RESTful API进行暴露，这其实已经不符合兼容升级的策略了，因为现状是不能改造旧服务，或者说改造的成本很大，比如已经上线了100个服务，就为了其中一个服务升级dubbo3，要改造其他99个旧服务吗？显然是不现实的，期望的应该是在升级dubbo3的服务中依然可以使用类似spring-cloud://nacos-uri的方式交给容器管理注册，只不过内部已经做了兼容处理，比如多上传一份旧服务的元数据等，让新旧服务可以互通。

**Comment by Lingzhou314** [comment]
> > spring-cloud-alibaba后续版本已经将spring-cloud-starter-dubbo去除了 #2398 建议可以升级spring-cloud-alibaba 如2021.0.4.0同时Dubbo部分升级为apache的dubbo3
> > ```scala
> > <dependency>
> >     <groupId>org.apache.dubbo</groupId>
> >     <artifactId>dubbo-bom</artifactId>
> >     <version>3.1.8</version>
> >     <type>pom</type>
> >     <scope>import</scope>
> > </dependency>
> > 
> > 
> > <dependency>
> >     <groupId>org.apache.dubbo</groupId>
> >     <artifactId>dubbo-spring-boot-starter</artifactId>
> > </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样也可以将spring-cloud-alibaba和dubbo 版本进行独立维护/
我了解后续版本已经移除了，也了解之前的注册方式有问题，现在你们已经分道扬镳了，就连examples里都没有集成dubbo的例子了，所以后续版本也完全不考虑兼容dubbo升级的问题了吗，#2398 这里的解决方案是需要改造旧服务加一层RESTful API进行暴露，这其实已经不符合兼容升级的策略了，因为现状是不能改造旧服务，或者说改造的成本很大，比如已经上线了100个服务，就为了其中一个服务升级dubbo3，要改造其他99个旧服务吗？显然是不现实的，期望的应该是在升级dubbo3的服务中依然可以使用类似spring-cloud://nacos-uri的方式交给容器管理注册，只不过内部已经做了兼容处理，比如多上传一份旧服务的元数据等，让新旧服务可以互通。

**Comment by steverao** [comment]
> 

其实你理解的有一点问题，没有什么分道扬镳这种说法：）是社区这边认为Spring Cloud Alibaba和Dubbo都是在Spring Boot基础上提供的微服务解决方案，两者本身都是独立存在的，一般企业没必要采用两个微服务框架给维护带来较大的复杂性，另外原来的模块无论是在功能还是实现设计上都有一些问题，所以把之前的相关模块和内容都移除了，不推荐使用。

**Comment by Lingzhou314** [comment]
> > 
> 
> 其实你理解的有一点问题，没有什么分道扬镳这种说法：）是社区这边认为Spring Cloud Alibaba和Dubbo都是在Spring Boot基础上提供的微服务解决方案，两者本身都是独立存在的，一般企业没必要采用两个微服务框架给维护带来较大的复杂性，另外原来的模块无论是在功能还是实现设计上都有一些问题，所以把之前的相关模块和内容都移除了，不推荐使用。

了解，但是对于曾经使用scad，并且所有服务都已经上线的用户来说，怎么在不改动旧服务的情况下，兼容升级dubbo3呢，按您的建议是无法做到兼容升级的。虽然现在两者是独立的微服务解决方案，但是依然可以在选择使用sca的情况下，使用dubbo进行rpc通信，而非restful，所以期望的应该是部分服务暂时兼容升级到dubbo3，后续一步一步的把其他的服务升级，直到所有的服务升级完成后，再移除兼容配置，完全使用dubbo3。

**Comment by steverao** [comment]
> > > 
> > 
> > 
> > 其实你理解的有一点问题，没有什么分道扬镳这种说法：）是社区这边认为Spring Cloud Alibaba和Dubbo都是在Spring Boot基础上提供的微服务解决方案，两者本身都是独立存在的，一般企业没必要采用两个微服务框架给维护带来较大的复杂性，另外原来的模块无论是在功能还是实现设计上都有一些问题，所以把之前的相关模块和内容都移除了，不推荐使用。
> 
> 了解，但是对于曾经使用scad，并且所有服务都已经上线的用户来说，怎么在不改动旧服务的情况下，兼容升级dubbo3呢，按您的建议是无法做到兼容升级的。虽然现在两者是独立的微服务解决方案，但是依然可以在选择使用sca的情况下，使用dubbo进行rpc通信，而非restful，所以期望的应该是部分服务暂时兼容升级到dubbo3，后续一步一步的把其他的服务升级，直到所有的服务升级完成后，再移除兼容配置，完全使用dubbo3。

因为相关模块暂时不提供维护了，所以目前没有平滑迁移方案。
