### ISSUE TITLE
如何升级spring-cloud-starter-dubbo这个jar里面dubbo版本到2.7.15

### ISSUE THREAD

**Issue by scauzhangzhimu** [alibaba/spring-cloud-alibaba#3226]
<img width="728" alt="企业微信截图_16796436912061" src="https://user-images.githubusercontent.com/93377327/227456088-12715894-294e-400c-9e93-35c762efd568.png">

The project uses spring cloud+dubbo, and uses the spring cloud starter dubbo jar to configure it. Currently, I only want to upgrade the dubbo version in this jar package to 2.7.15. What should I do

项目使用的是springcloud+dubbo,用的spring-cloud-starter-dubbo这个jar去配置的，现在只想升级这个jar包里面dubbo版本到2.7.15，该怎么处理？

**Comment by steverao** [comment]
We don't maintain module of `spring-cloud-starter-dubbo` with main branch now, you can refer to #2398.
If you don't use relevant ability in module of `spring-cloud-starter-dubbo`. you can try to update dubbo module alone by upgrading following dependency.
```pom.xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.7.15</version>
</dependency>
```
