### ISSUE TITLE
ErrCode:-400, ErrMsg:Could not initialize class com.alibaba.nacos.common.http.HttpClientBeanHolder

### ISSUE THREAD

**Issue by superYangYang** [alibaba/spring-cloud-alibaba#3230]
The project was started many times before it got up.
spring-cloud-starter-alibaba-nacos-discovery 2021.0.1.0
spring-boot 2.6.4
nacos-server 2.0.2

error:
2023-03-24 21:57:04.602 ----> [/] [main] ---> ERROR com.alibaba.cloud.nacos.discovery.NacosWatch - namingService unsubscribe failed, properties:NacosDiscoveryProperties{serverAddr='xx:8848', username='xx', password='xx', endpoint='', namespace='', watchDelay=30000, logName='', service='service-portal-new-api', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.16.0.126', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}
2 java.lang.RuntimeException: ErrCode:-400, ErrMsg:Could not initialize class com.alibaba.nacos.common.http.HttpClientBeanHolder
3         at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:101)
4         at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:89)
5         at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:52)
6         at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:175)
7         at com.alibaba.cloud.nacos.discovery.NacosWatch.destroy(NacosWatch.java:206)
8         at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:212)
9         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
10         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
11         at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161)
12         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
13         at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154)
14         at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
15         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:596)
16         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
17         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
18         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
19         at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
20         at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
21         at com.suncloud.portal.RootApplication.main(RootApplication.java:22)
22         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
24         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25         at java.lang.reflect.Method.invoke(Method.java:498)
26         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
27         at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
28         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
29         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
30 Caused by: com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
31         at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:63)
32         at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77)
33         at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:98)
34         ... 26 common frames omitted
35 Caused by: java.lang.reflect.InvocationTargetException: null
36         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
37         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
38         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
39         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
40         at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:60)
41         ... 28 common frames omitted
42 Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.nacos.common.http.HttpClientBeanHolder
43         at com.alibaba.nacos.client.naming.net.NamingHttpClientManager.getNacosRestTemplate(NamingHttpClientManager.java:67)
44         at com.alibaba.nacos.client.naming.net.NamingProxy.<init>(NamingProxy.java:84)
45         at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:93)
46         at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81)
47         ... 33 common frames omitted

**Comment by yuluo-yx** [comment]
Can you provide a simplest demo to help us reproduce the problem?

**Comment by 123liuziming** [comment]
The unsubscribe method in NacosWatch is executed when the spring container is closed, which in the web scenario is usually when your web server is closed. Can you tell me how you do the shutdown of the web server process?

**Comment by superYangYang** [comment]
I don't know, it's a springboot project, using nacos as a registry center, and this error will be reported when the project starts。The project is deployed as a docker service, and it will start successfully after several failures

**Comment by yuluo-yx** [comment]
> I don't know, it's a springboot project, using nacos as a registry center, and this error will be reported when the project starts。The project is deployed as a docker service, and it will start successfully after several failures

Can you provide the Docker file for deploying Nacos?
Or consider Spring Cloud Alibaba's best practices example, which uses docker-compose to deploy Nacos services.
https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/integrated-example/docker-compose/docker-compose-env.yml

**Comment by steverao** [comment]
From your error report information of `ERROR com.alibaba.cloud.nacos.discovery.NacosWatch - namingService unsubscribe failed`. It seems to be related to the original logic of NacosWatch, which is related to the failure caused by subscribing to its own instance change logic at startup.You can refer to #2868, we addressed it in `2021.0.5.0`. It is recommended to upgrade to the relevant version and try again to see if it will reappear.
