### ISSUE TITLE
📣 Spring Cloud Alibaba 2021.0.5.0 is released

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3231]
Hello Community,

We are very glad to announce that Spring Cloud Alibaba 2021.0.5.0 is released.

You can check detailed release notes here:

- Release notes: https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2021.0.5.0
- Relevant article: https://mp.weixin.qq.com/s/mAKnysJxkSzQEIqheTpTwQ

If you have any questions using this version, please report the issue on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by imyxiao** [comment]
Awesome job on the new release! Can't wait to give it a try, thanks for your effort!
