### ISSUE TITLE
Adjust governance module component naming discussion

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3238]
## Background
The microservices governance capability built by the community was released in version 2.2.10-RC1. For related content, please refer to:

- Release notes: https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.10-RC1
- Relevant article: https://mp.weixin.qq.com/s/dAdtv1QvW1MQbVqpfbprkA

We named the relevant modules at that time:

- Routing: `spring-cloud-starter-alibaba-governance-routing`
- Security: `spring-cloud-starter-alibaba-governance-auth`

We did them according to following rule:
The Spring Cloud Alibaba community has been proposed and voted by the Community Steering Committee Management Committee. From 2023, the new module naming rules of the community will follow: 
`spring-cloud-starter-(component's company name)-(component name)-function name(subfunction name)`
Name the module, where the content of () indicates that it is not necessary and can be omitted, and the sub-function name is at most one level.
But we will develop some new abilities in the future, such as mTLS, Outlier instance removal and so on, I think we need to contain them in our above module, because, if we create new module, relevant abilities will be very scattered, not concentrated. But inclusiveness of above module names is not high, generalization is not enough.

## New Plan
I think following naming of relevant modules is more suitable.

- Routing: `spring-cloud-starter-alibaba-governance-traffic`
- Security: `spring-cloud-starter-alibaba-governance-security`

In the future, we can put mTLS and some other security abilities into `spring-cloud-starter-alibaba-governance-security`, and put Outlier instance removal and some other traffic management abilities into `spring-cloud-starter-alibaba-governance-traffic`.

**Comment by yuluo-yx** [comment]
I agree with you!

**Comment by qakqs** [comment]
I agree with you!

**Comment by qakqs** [comment]
Can it be named according to the concept and specification of DDD？

**Comment by steverao** [comment]
> Can it be named according to the concept and specification of DDD？

Please explain your thinking and reason, it's hard to modify naming rule. Because, it was proposed and voted by the Community Steering Committee Management Committee.

**Comment by ruansheng8** [comment]
Is there a plan to further decompose the `traffic` module into sub-modules, given that it encompasses multiple functionalities such as `routing`, `rate limiting`, `circuit breaking`, and `retrying`?

**Comment by steverao** [comment]
> Is there a plan to further decompose the `traffic` module into sub-modules, given that it encompasses multiple functionalities such as `routing`, `rate limiting`, `circuit breaking`, and `retrying`?

Rate limiting and circuit breaking will be contained in modules of Sentinel. Others that if we plan to develop will be contained in module of traffic directly.
