### ISSUE TITLE
add relevant additional-spring-configuration-metadata.json in governance modules

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3243]
**Which Component**
eg. `spring-cloud-starter-xds-adapter`, `spring-cloud-starter-opensergo-adapter`, `spring-cloud-starter-alibaba-governance-routing`, `spring-cloud-starter-alibaba-governance-auth`

**Is your feature request related to a problem? Please describe.**
Add relevant files of `additional-spring-configuration-metadata.json`, provide more readability of setting configuration.

**Describe the solution you'd like**
You can learn how to achieve it in Nacos module.

**Comment by 123liuziming** [comment]
Please assign it to me.

**Comment by qakqs** [comment]
Please assign it to me.
