### ISSUE TITLE
add helm support for governance module

### ISSUE THREAD

**Issue by 123liuziming** [alibaba/spring-cloud-alibaba#3244]
To deploy the examples in the Governance module better, we can provide Helm support to the Governance module so that we can easily build a whole set of service governance demo applications！

**Comment by steverao** [comment]
> To deploy the examples in the Governance module better, we can provide Helm support to the Governance module so that we can easily build a whole set of service governance demo applications！

Good idea!

**Comment by yuluo-yx** [comment]
That's sounds good. Please assign to me. I'll try to finish it!

**Comment by qakqs** [comment]
good!!! Please assign to me,let's code!

**Comment by 123liuziming** [comment]
Is there any PR proposed? If not I will open a pr this Saturday to solve this issue.

**Comment by yuluo-yx** [comment]
> Is there any PR proposed? If not I will open a pr this Saturday to solve this issue.

I am very sorry that I have been doing documention related things recently, so I may not have time to deal with this issue.

**Comment by yuluo-yx** [comment]
No feedback, now closed
