### ISSUE TITLE
The integrated-example  module test result is inconsistent with the expected result

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3255]
**Which Component**
*Integrated-example*

**Describe the bug**
Visit `http://integrated-frontend:8080/sentinel`;
![image](https://user-images.githubusercontent.com/77964041/230753250-9d472ed5-c74d-4aae-b17b-82a5a58a8774.png)
Visit `http://integrated-frontend:8080/rocketmq`;
![image](https://user-images.githubusercontent.com/77964041/230753262-fe8a65ad-fd6c-49ab-a319-7be25febab76.png)
And the console has no related error log.

**Simplest demo**
`https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/integrated-example`

**To Reproduce**
1.Follow the instructions in `local-deploy.md` to start Nacos Server and RocketMQ locally and configure the database information in MySQL Server;
2. Start `frontend, gateway, praise-provider and praise-consumer` modules in `integrated-exmaple` module respectively;
3. Enter the address `http://integrated-frontend:8080/sentinel` and `http://integrated-frontend:8080/rocketmq` in the browser;
4. Press Enter to see the result displayed in the browser compared to the result in the document;
5. My local MySQL Server version is 8.0.x, so I need to add `allowPublicKeyRetrieval=true` to the url link suffix.

**Expected behavior**
The expected result is the same as described in the documentation.
sentinel
![image](https://user-images.githubusercontent.com/77964041/230753274-e57e3536-73b1-4e2f-ac5b-977da13eddb0.png)
rocketmq
![image](https://user-images.githubusercontent.com/77964041/230753279-8e5ec004-a708-4107-ba57-68b313dd59b5.png)

**Screenshots**
The service is successfully registered with Nacoa.
![image](https://user-images.githubusercontent.com/77964041/230753311-f1f8d46c-6012-43b2-8b50-d53dcde60fca.png)
RocketMQ is started successfully.
![image](https://user-images.githubusercontent.com/77964041/230753321-772140a1-5364-4ccf-a7d6-5108cded072e.png)

**Additional context**
Nacos 2.2.0, RocketMQ 4.9.4, MySQL 8.0.28, Win10, Spring Cloud Alibaba2022.x.

**Comment by qakqs** [comment]
i flower you

**Comment by qakqs** [comment]
Please assign it to me and I will try to solve it

**Comment by yuluo-yx** [comment]
> Please assign it to me and I will try to solve it

Is there any progress?
