### ISSUE TITLE
can we chang NacosServiceDiscovery method getInstances to support customer cross group invoke provider?

### ISSUE THREAD

**Issue by chengyouling** [alibaba/spring-cloud-alibaba#3259]
**Which Component**
eg. Nacos Discovery

**Describe what problem you have encountered**
definition  one customer, group: CUSTOMER;
definition  one provider, group: PROVIDER;

then consumer can not invoke the provider, can you add this sample code in “NacosServiceDiscovery.java” to support cross group invoke？
code such as：

public List<ServiceInstance> getInstances(String serviceId) throws NacosException {
        int idxAt = serviceId.indexOf(".");
        String group = idxAt == -1 ? discoveryProperties.getGroup() : serviceId.substring(0, idxAt);
        String providerServiceId = idxAt == -1 ? serviceId : serviceId.substring(idxAt + 1);
        List<Instance> instances = namingService().selectInstances(providerServiceId, group,
                true);
        return hostToServiceInstanceList(instances, providerServiceId);
   }

customer invoke url can be like this:
http://groupName.serviceName/sayHello.

**Describe what information you have read**
eg. I have read the reference doc of discovery.

**Comment by steverao** [comment]
Why do you need the ability? we had relevant discussion before, you can refer to #2150

**Comment by chengyouling** [comment]
i see，but it have no PR to solve this question;

the scene that i need cross group invoke：
background: there have two team develop two business application, separate definition Nacos groupA and groupB, using one Nacos server.

personal understanding：
1、from business perspective, definition two group is reasonable and necessary, and namespace is using for environment isolation as same group.
2、some times groupA service need invoke groupB service, if change  definition same group as #2150 discussion, not acceptable for business.

so that what i need croos group invoke.

**Comment by chengyouling** [comment]
@steverao 
Can this ability be added？
