### ISSUE TITLE
Slf4j StaticLoggerBinder Error

### ISSUE THREAD

**Issue by zhangbinhub** [alibaba/spring-cloud-alibaba#3261]
Environment:
Spring Boot 3.0.5
Spring Cloud 2022.0.2
Spring Cloud Alibaba 2022.0.0.0-RC1
Slf4j Api 2.0.7

Warning when launching the application
`2023-04-11T23:29:47.726+08:00  WARN 20832 --- [           main] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: org/slf4j/impl/StaticLoggerBinder`

**Comment by steverao** [comment]
This is a problem from Nacos client, it was solved before, for detail, you can refer to [#9860](https://github.com/alibaba/nacos/issues/9860).

**Comment by zhangbinhub** [comment]
nacos-client already has version 2.2.1, but SCA 2022.0.0.0-RC1 dependency nacos-client 2.2.1-RC. We hope SCA can release the next RC version or RELEASE version as soon as possible

**Comment by steverao** [comment]
> nacos-client already has version 2.2.1, but SCA 2022.0.0.0-RC1 dependency nacos-client 2.2.1-RC. We hope SCA can release the next RC version or RELEASE version as soon as possible

Ok, we got it.

**Comment by MQPearth** [comment]
got the same problem
