### ISSUE TITLE
springcloud2022.x 集成springcloud alibaba2022.0.0.0-RC1 无法读取配置的nacos地址

### ISSUE THREAD

**Issue by airufei** [alibaba/spring-cloud-alibaba#3262]
1、环境：
JDK 17+
Nacos 2.2.0
SpringBoot 3.x
SpringCloud 2022.0.0
SpringCloud Alibaba 2022.0.0.0-RC1

2、问题
com.alibaba.nacos.common.remote.client - [d968c999-e5f8-42ef-b15e-23e274fc70b7_config-0] Try to connect to server on start up, server: {serverIp = '127.0.0.1', server main port = 8848}
2023-04-12 10:58:14 342  printIfErrorEnabled  [,][main] ERROR com.alibaba.nacos.common.remote.client.grpc.GrpcClient - Server check fail, please check server 127.0.0.1 ,port 9848 is available , error ={}

3、问题截图

![image](https://user-images.githubusercontent.com/22907133/231338961-ce59071f-92e0-4451-a2f8-85b544aae13b.png)

4、pom配置截图
![image](https://user-images.githubusercontent.com/22907133/231344912-e8cbbe58-eb8c-4b60-bfdb-74f5d7eea183.png)

**Comment by steverao** [comment]
You can refer to [update guide](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc) to check whether there is wrong using. If everything is alright, you can refer to [relevant example]( https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example) to find the difference.

**Comment by yuluo-yx** [comment]
nacos 2.2.0 has added grpc communication port. If you run nacos server on a server or docker, you need to open port 9848.

**Comment by airufei** [comment]
> nacos 2.2.0 has added grpc communication port. If you run nacos server on a server or docker, you need to open port 9848.

nacos server is fine, other applications are normal.

**Comment by airufei** [comment]
> You can refer to [update guide](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc) to check whether there is wrong using. If everything is alright, you can refer to [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example) to find the difference.

I didn't see any special difference, but spring-cloud-alibaba-dependencies 2022.0.0.0-RC2 was used in the case, but this version cannot pull dependencies

**Comment by yuluo-yx** [comment]
> > nacos 2.2.0 has added grpc communication port. If you run nacos server on a server or docker, you need to open port 9848.
> 
> nacos server is fine, other applications are normal.

You mean that other services can connect to the server normally. Is this the only service that went wrong?
Also, can you provide a complete error log?

**Comment by yuluo-yx** [comment]
> > You can refer to [update guide](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc) to check whether there is wrong using. If everything is alright, you can refer to [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example) to find the difference.
> 
> I didn't see any special difference, but spring-cloud-alibaba-dependencies 2022.0.0.0-RC2 was used in the case, but this version cannot pull dependencies

2022.0.0.0-RC2 is not published in the central repository and requires its own local packaging to be used.

**Comment by airufei** [comment]
> > > You can refer to [update guide](https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc) to check whether there is wrong using. If everything is alright, you can refer to [relevant example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example) to find the difference.
> > 
> > 
> > I didn't see any special difference, but spring-cloud-alibaba-dependencies 2022.0.0.0-RC2 was used in the case, but this version cannot pull dependencies
> 
> 2022.0.0.0-RC2 is not published in the central repository and requires its own local packaging to be used.

It has been solved, it is the problem of spring configuration loading (import), I did not notice this matter. Thank you very much.

**Comment by youngledo** [comment]
请问你这个是什么原因导致的，我也遇到同样的问题。

**Comment by 24kkkkkk** [comment]
> 请问您这是什么原因导致的，我也遇到了同样的问题。

我遇到是的在容器运行不行，宿主机可以运行
