### ISSUE TITLE
2022 版本大概要什么时候正式发布呢

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#3264]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by bestrevens** [comment]
I want to know

**Comment by steverao** [comment]
The next version is 2022.0.0.0-RC2, It will release this month in our plan.

**Comment by bestrevens** [comment]
thank you very much
