### ISSUE TITLE
Spring Cloud Alibaba2021.0.5.0参考文档中关于4.5. 支持profile粒度的配置的问题请教

### ISSUE THREAD

**Issue by mashirro** [alibaba/spring-cloud-alibaba#3265]
https://spring-cloud-alibaba-group.github.io/github-pages/2021/zh-cn/2021.0.5.0/index.html#_%E6%94%AF%E6%8C%81profile%E7%B2%92%E5%BA%A6%E7%9A%84%E9%85%8D%E7%BD%AE

按照上述链接4.5节中的配置，启动应用后，获取的env参数为null。看了下控制台的输出，只加载了dev.properties,没有加载dev.yaml配置文件
![image](https://user-images.githubusercontent.com/43327739/232402829-4aea2715-386b-489c-8530-1acdf7b3195b.png)

**Comment by mashirro** [comment]
文档这里需补充下：
![image](https://user-images.githubusercontent.com/43327739/232410128-38330c1d-16b2-4b34-847b-0179e6fdbfea.png)

**Comment by yuluo-yx** [comment]
> 文档这里需补充下： ![image](https://user-images.githubusercontent.com/43327739/232410128-38330c1d-16b2-4b34-847b-0179e6fdbfea.png)



> 文档这里需补充下： ![image](https://user-images.githubusercontent.com/43327739/232410128-38330c1d-16b2-4b34-847b-0179e6fdbfea.png)

我没理解你这句话说的是什么意思？
配置文件的优先级是bootstrap.properties要高于yaml，在nacos项目中配置项目属性要放在properties文件中去
