### ISSUE TITLE
something wrong when I run it.

### ISSUE THREAD

**Issue by luyanfeng** [alibaba/spring-cloud-alibaba#3268]
my project dependencies like this:
```xml
<dubbo.version>3.1.6</dubbo.version>
<spring-cloud-alibaba.version>2022.0.0.0-RC1</spring-cloud-alibaba.version>
<spring-cloud.version>2022.0.2</spring-cloud.version>
```

when I run it:
![图片](https://user-images.githubusercontent.com/5779510/232705732-ad3d063e-1668-4e70-ae26-93f3a7bfdb6d.png)

what`s wrong？

**Comment by luyanfeng** [comment]
springboot version is 3.0.2
```xml
<spring-boot.version>3.0.2</spring-boot.version>
```

**Comment by yuluo-yx** [comment]
We don't recommend mixing spring cloud alibaba with dubbo.
