### ISSUE TITLE
NacosLoadBalancer cannot be used with HintBasedServiceInstanceListSupplier

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/spring-cloud-alibaba#3269]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**

NacosLoadBalancer

**Describe the bug**

When using NacosLoadBalancer, HintBasedServiceInstanceListSupplier does not work.

> 使用  NacosLoadBalancer 时 HintBasedServiceInstanceListSupplier  不会起作用

**Additional context**

https://github.com/alibaba/spring-cloud-alibaba/blob/80ab5e6ab4a1bacc86f947222a28a4e23343ce1b/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/loadbalancer/NacosLoadBalancer.java#L122-L125 

supplier.get().next().map(this::getInstanceResponse) should be replaced with supplier.get(request).next().map(this::getInstanceResponse), otherwise it will not go through the processing logic of [HintBasedServiceInstanceListSupplier](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplier.java#L56-L58).

> `supplier.get().next().map(this::getInstanceResponse)` 应该换成 `supplier.get(request).next().map(this::getInstanceResponse)` ，不然不会走到 [HintBasedServiceInstanceListSupplier ](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplier.java#L56-L58)的处理逻辑里面去。

---

The implementation of [RoundRobinLoadBalancer](https://github.com/spring-cloud/spring-cloud-commons/blob/51ee78555d7ae614e1d4f1ecbdaff515aa55304c/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java#L79-L83)：
> [RoundRobinLoadBalancer 的实现](https://github.com/spring-cloud/spring-cloud-commons/blob/51ee78555d7ae614e1d4f1ecbdaff515aa55304c/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java#L79-L83)：
```java
	@SuppressWarnings("rawtypes")
	@Override
	// see original
	// https://github.com/Netflix/ocelli/blob/master/ocelli-core/
	// src/main/java/netflix/ocelli/loadbalancer/RoundRobinLoadBalancer.java
	public Mono<Response<ServiceInstance>> choose(Request request) {
		ServiceInstanceListSupplier supplier = serviceInstanceListSupplierProvider
				.getIfAvailable(NoopServiceInstanceListSupplier::new);
		return supplier.get(request).next()
				.map(serviceInstances -> processInstanceResponse(supplier, serviceInstances));
	}
```

**Comment by 123liuziming** [comment]
我配置了一个HintBasedServiceInstanceListSupplier
```
@Bean
	public ServiceInstanceListSupplier discoveryClientServiceInstanceListSupplier(
			ConfigurableApplicationContext context) {
		return ServiceInstanceListSupplier.builder()
				.withBlockingDiscoveryClient()
				.withHints()
				.build(context);
	}
```
![image](https://user-images.githubusercontent.com/32130965/233268106-339727d8-5531-4fbf-ab34-4bcbbf63de29.png)
似乎是能进到它的get方法里的呢，你这边的具体诉求是什么？

**Comment by liuweiGL** [comment]
进的是无参 `get()` 而不是有参 `get(request)`，导致 [HintBasedServiceInstanceListSupplier](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplier.java#L56-L58) 的过滤逻辑没执行

**Comment by 123liuziming** [comment]
> 进的是无参 `get()` 而不是有参 `get(request)`，导致 [HintBasedServiceInstanceListSupplier](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplier.java#L56-L58) 的过滤逻辑没执行

是的，貌似只能进到无参的get()中， @steverao  @XuDaojie 这块这么实现有什么特殊原因吗？

**Comment by steverao** [comment]
> > 进的是无参 `get()` 而不是有参 `get(request)`，导致 [HintBasedServiceInstanceListSupplier](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplier.java#L56-L58) 的过滤逻辑没执行
> 
> 是的，貌似只能进到无参的get()中， @steverao @XuDaojie 这块这么实现有什么特殊原因吗？

I think there is wrong here before, we should modify it to `get(request)` like other LoadBalancer achieved in Spring Cloud LoadBalancer.
