### ISSUE TITLE
FeignClient 在 SpringBoot 3.X 中不可用

### ISSUE THREAD

**Issue by ITSweets** [alibaba/spring-cloud-alibaba#3276]
嗨，最近升级到 SpringBoot 3.X 发现 Sentinel 的服务降级不可用，原因是通过 FeignContext 查找降级策略时，FeignContext 已经在 Boot 3.X 中被移除。请问有什么替代品吗？

**Comment by steverao** [comment]
Please refer to [our release list](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E) to update. In 2022.0.0.0-RC1 of Spring Cloud Alibaba, degrade ability of sentinel is alright!
