### ISSUE TITLE
2021.0.5.0版本使用openfeign根据服务名访问，找不到服务实例，请问应该使用哪个版本的ribbon和feign？

### ISSUE THREAD

**Issue by kingsley1215** [alibaba/spring-cloud-alibaba#3282]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**Simplest demo**
The URL of the simplest demo to reproduce the problem.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by icodening** [comment]
应该使用`spring-cloud-loadbalancer`

**Comment by steverao** [comment]
Please check whether you add following dependency in Consumer application:

``` xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-loadbalancer</artifactId>
</dependency>
```
Relevant reason you can refer to #3115

**Comment by Pengfei-Lu** [comment]
Please add the important usage instructions on Nacos document for better referrence.

**Comment by yuluo-yx** [comment]
> 请在 Nacos 文档中添加重要的使用说明，以便更好地参考。

good idea, I will improve the nacos documentation!
