### ISSUE TITLE
The 2021.0.5.0 version uses openfeign to access according to the service name, but the service instance cannot be found. Which version of ribbon and feign should I use?

### ISSUE THREAD

**Issue by kingsley1215** [alibaba/spring-cloud-alibaba#3283]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**Simplest demo**
The URL of the simplest demo to reproduce the problem.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by steverao** [comment]
Duplicate problem with #3282
