### ISSUE TITLE
Discussion: Whether to delete the spring cloud alibaba doc module

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3285]
Soon, the community will officially release the official documentation website, and then we will maintain the README file in the official website document, the example file, and the doc file at the same time, which will increase the workload. Would you consider deleting the doc document?

**Comment by 123liuziming** [comment]
After the document is deleted from the github repository, if someone wants to contribute the document, then where do they submit pr？Do they submit pr to the new official website repository?

**Comment by yuluo-yx** [comment]
> 文档从github仓库删除后，如果有人想贡献文档，那么他们在哪里提交pr？他们提交pr到新的官网仓库吗？

Yes, there will be a link at the bottom of the higress homepage after the official launch. See the Higress homepage.
![image](https://user-images.githubusercontent.com/77964041/234215595-3d8609a4-92c3-4dbc-aa07-ed4559f381c7.png)

**Comment by yuluo-yx** [comment]
the community is currently building an official website. You can refer to the https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io warehouse. Contributions are very welcome.

**Comment by yuluo-yx** [comment]
The issue is completed, closed now.
