### ISSUE TITLE
Configuration format error printing error message contains config

### ISSUE THREAD

**Issue by awith** [alibaba/spring-cloud-alibaba#3288]
com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.
When the configuration file format is incorrect, printing abnormal log information will print out all the configuration information, which poses a high risk factor for production environments. Is there any way to avoid it?

![image](https://user-images.githubusercontent.com/13742941/234781553-64c3391f-e887-46d9-88d1-202cea505f26.png)

**Comment by steverao** [comment]
I think the wrong configuration format is very serious problem. In normal condition, it needs to print relevant log. Now we don't support stopping relevant log, in general, you should try to avoid above problem.

**Comment by awith** [comment]
thanks
