### ISSUE TITLE
Fix typo in nacos-discovery readme

### ISSUE THREAD

**Issue by 123liuziming** [alibaba/spring-cloud-alibaba#3289]
There is a misspelling in nacos-discovery readme. "同事" should be "同时"
![image](https://user-images.githubusercontent.com/32130965/234790526-de218062-a8a8-42d4-a9dd-2d3397c7b71a.png)

**Comment by yuluo-yx** [comment]
reference: https://github.com/alibaba/spring-cloud-alibaba/pull/3253
