### ISSUE TITLE
Why does the 2022 and 2021 versions of spring-cloud-alibaba-dependencies not have spring-cloud-starter-dubbo dependencies

### ISSUE THREAD

**Issue by haozhi-ly** [alibaba/spring-cloud-alibaba#3297]
Why does the 2022 and 2021 versions of spring-cloud-alibaba-dependencies not have spring-cloud-starter-dubbo dependencies? Is dubbo no longer supported, or is it not recommended?

**Comment by yuluo-yx** [comment]
We don't maintain module of spring-cloud-starter-dubbo with main branch now, you can refer to https://github.com/alibaba/spring-cloud-alibaba/issues/2398.

**Comment by haozhi-ly** [comment]
> We don't maintain module of spring-cloud-starter-dubbo with main branch now, you can refer to #2398.

ok，thank you
