### ISSUE TITLE
nacos-log4j2.xml lost Root logger 

### ISSUE THREAD

**Issue by johndudo** [alibaba/spring-cloud-alibaba#3313]
nacos-log4j2.xml lost Root logger  in 2022.0.0.0-RC2

**Comment by johndudo** [comment]
nacos-log4j2.xml lost Root logger , when App boot up , the following log print...
main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender

**Comment by yuluo-yx** [comment]
You can set nacos log properties at project startup: `System.setProperty("nacos.logging.default.config.enabled","false");`

**Comment by yuluo-yx** [comment]
You can take a look at the `com.alibaba.nacos.client.utils.LogUtils` class. Internally, according to your log framework, it will read the configuration files corresponding to the log framework, such as log4j2.json, log4j2.xml, etc. of log4j2, and then refresh the log configuration. If log4j2 is used in the project, but the log configuration file is Other formats, such as `log4j2-spring.xml`, will cause the configuration to not be read, then read `nacos-log4j2.xml` configuration in `nacos-client.jar`. This configuration file does not set Root.

This is a question of the nacos community, please go to the relevant community to ask questions. **https://github.com/alibaba/nacos/issues**

**Comment by yuluo-yx** [comment]
Maybe you can see `https://github.com/alibaba/nacos/issues/1121`
