### ISSUE TITLE
nacos client not log error message

### ISSUE THREAD

**Issue by renshui1983** [alibaba/spring-cloud-alibaba#3316]
**application config**

<spring-cloud.version>2021.0.5</spring-cloud.version>
<spring-cloud-alibaba.version>2021.0.5.0</spring-cloud-alibaba.version>
<spring-boot.version>2.6.13</spring-boot.version>

application.properties

spring.application.name=aicc
app.output=/tmp/output/${spring.application.name}
logging.file.path=${app.output}
logging.level.root=INFO
logging.config=classpath:logback-spring.xml
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
spring.config.import=optional:nacos:aicc.properties

**problem** 

when spring.cloud.nacos.config.server-addr value is wrong, spring application can start success, but no error message is printed。

expected:  

LoggerUtils.printIfErrorEnabled(LOGGER, "Server check fail, please check server {} ,port {} is available , error ={}", new Object[]{ip, port, var8}); can print error message

**Comment by renshui1983** [comment]
I have located the cause. There's a nacos-logback.xml file in the nacos-client.jar, and the logs are directed to the log directory configured in this file.

**Comment by steverao** [comment]
> I have located the cause. There's a nacos-logback.xml file in the nacos-client.jar, and the logs are directed to the log directory configured in this file.

Yes, in 2021.0.5.0 of Spring Cloud Alibaba, the error logs of Nacos Client will be printed in default log file of Nacos.
