### ISSUE TITLE
spring-cloud-alibaba-2021.0.5.0 Incompatible with Spring Boot version 2.7

### ISSUE THREAD

**Issue by XW512** [alibaba/spring-cloud-alibaba#3317]
I integrated spring cloud alibaba 2021.0.5.0 with spring boot 2.7 and found that the dynamic refresh of nacos was not effective. When will this spring cloud alibaba adapt to spring boot 2.7

**Comment by yuluo-yx** [comment]
Please refer to the version description to adapt the component version, other version combinations cannot guarantee correctness. **https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E**

**Comment by yuluo-yx** [comment]
In addition, please check whether you have enabled the ability to configure dynamic refresh.

**Comment by XW512** [comment]
> Please refer to the version description to adapt the component version, other version combinations cannot guarantee correctness. **https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E**

Okay, I will downgrade according to the version correspondence on the official website. Thank you
