### ISSUE TITLE
[BUG] Failed to bind properties under 'spring.cloud.sentinel.datasource.flow.nacos' to com.alibaba.cloud.sentinel.datasource.config.NacosDataSourceProperties:

### ISSUE THREAD

**Issue by pikachu623** [alibaba/spring-cloud-alibaba#3327]
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.sentinel.datasource.flow.nacos' to com.alibaba.cloud.sentinel.datasource.config.NacosDataSourceProperties:

    Reason: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotEmpty' validating type 'java.lang.String'. Check configuration for 'groupId'

nacos 当中配置
spring:
  cloud:
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: wallet
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow

jdk version：1.8.0_202
spring-cloud-alibaba.version ：2.2.10-RC1
spring-cloud.version ：Hoxton.SR12
spring-boot.version：2.3.12.RELEASE
配置没问题但报错了

**Comment by ruansheng8** [comment]
Here is a provisional workaround: manually import the validator dependency as 
```xml
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
```

**Comment by pikachu623** [comment]
已解决
