### ISSUE TITLE
自定义的Resttemplate，无法被SentialResttemplate注解强化

### ISSUE THREAD

**Issue by linzhiqiang0514** [alibaba/spring-cloud-alibaba#3329]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
Sentinel

**Describe the bug**
当我使用自定义的RestTemplate时，com.alibaba.cloud.sentinel.custom.SentinelBeanPostProcessor#postProcessMergedBeanDefinition
判断逻辑错误，无法判断自定义的RestTemplate
		if (beanName == null || beanType != RestTemplate.class) {

**Simplest demo**
The URL of the simplest demo to reproduce the problem.

public class CustomRestTemplate extends RestTemplate {
}

@Bean("internalRestTemplate")
    @LoadBalanced
    @Primary
    @SentinelRestTemplate(fallbackClass = ExceptionUtil.class, fallback = "handleFallback",
        blockHandler = "handleBlock",blockHandlerClass = ExceptionUtil.class)
    public RestTemplate internalRestTemplate(
        @Autowired @Qualifier("restHttpClient") CloseableHttpClient httpClient,
        PlatformHttpRequestInterceptor platformHttpRequestInterceptor,
        PlatformResponseErrorHandler platformResponseErrorHandler) {
        logger.info("SentinelPlatformRestTemplate开始!");

        CustomRestTemplate restTemplate = new CustomRestTemplate(
            new HttpComponentsClientHttpRequestFactory(httpClient));
        logger.info("SentinelPlatformRestTemplate创建成功!ClientInfo:{}", httpClient);
        return restTemplate;
    }

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE
version: [2022.0.0.0-RC2](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-sentinel/2022.0.0.0-RC2)

**Comment by ruansheng8** [comment]
I willl fix it
