### ISSUE TITLE
When use the custom balancer and use the defaultServiceInstace throw ClassCaseException #3325

### ISSUE THREAD

**Issue by zt9788** [alibaba/spring-cloud-alibaba#3346]
I extended the LoadBalance of Nacos by converting the internal IP to the public IP after obtaining the Nacos service IP. Therefore, when processing the `choose` method, I used `DefaultServiceInstance`. Additionally, due to the use of a new ServiceInstance, there may be no `nacos.weight` and `nacos.health` metadatas.
Then call `NacosBalancer.getHostByRandomWeight3` to be compatible

pull request #3325

**Comment by 123liuziming** [comment]
How do you extend the LoadBalance of Nacos? Could you please give an example to us? Sorry I don't get your idea clearly according to your description...

**Comment by zt9788** [comment]
@123liuziming 
1. when restTemplate set @Loadbalacer then it only can call uri is serviceId,but when i call the full url it will tell me can not find service 
2. our env just have internal IP, when i want to call the service ,i want to get public ip(by aliyun's api) 

I register a  `CustomLoadBalancer extends NacosLoadBalancer`  and rewrite `choose` when got IP, call api to get public ip and build  serviceInstance, and if uri is full url ,i will build a new serviceInstance.

**Comment by 123liuziming** [comment]
Do you think this scenario is generic enough? It feels like a more customized requirement. @ruansheng8 @steverao

**Comment by steverao** [comment]
> Do you think this scenario is generic enough? It feels like a more customized requirement. @ruansheng8 @steverao

Yes, I agree with you. We can't modify framework code for personal customized requirement.

**Comment by steverao** [comment]
> @123liuziming
> 
> 1. when restTemplate set @Loadbalacer then it only can call uri is serviceId,but when i call the full url it will tell me can not find service
> 2. our env just have internal IP, when i want to call the service ,i want to get public ip(by aliyun's api)
> 
> I register a `CustomLoadBalancer extends NacosLoadBalancer` and rewrite `choose` when got IP, call api to get public ip and build serviceInstance, and if uri is full url ,i will build a new serviceInstance.

你的这个需求本身我有点不理解，一般微服务为了安全都是集群内调用，你为什么要将内网地址转换为公网地址呢？直接在服务注册的时候注册公网地址是否可以解决你的需求呢？

**Comment by zt9788** [comment]
> > @123liuziming
> > 
> > 1. when restTemplate set @Loadbalacer then it only can call uri is serviceId,but when i call the full url it will tell me can not find service
> > 2. our env just have internal IP, when i want to call the service ,i want to get public ip(by aliyun's api)
> > 
> > I register a `CustomLoadBalancer extends NacosLoadBalancer` and rewrite `choose` when got IP, call api to get public ip and build serviceInstance, and if uri is full url ,i will build a new serviceInstance.
> 
> 你的这个需求本身我有点不理解，一般微服务为了安全都是集群内调用，你为什么要将内网地址转换为公网地址呢？直接在服务注册的时候注册公网地址是否可以解决你的需求呢？

@steverao 
1. restTemplate 支持完整URL和ServiceId调用,这个时候,构建了一个新的ServiceInstance,默认使用了SpringCloud默认的DefaultServiceInstance.
2. 测试环境或预发布环境下,在个别环境下,需要本地调用测,所以实际扩展的时候,只判断了在本地会转换IP(这个确实比较定制化:joy:)

pr仅针对NacosLoadBalancer中在IPV4转IPV6时的NacosServiceInstance多支持一个DefaultServiceInstance,这样如果有DefaultServiceInstance也不会报错.

**Comment by steverao** [comment]
Welcome to our weekly meeting and discuss about this issues by dingtalk tonight.
```
Theme：Spring Cloud Alibaba社区双周会
Time：06-25 20:00 - 06-25 21:00
Conference No.：28309471498
Incoming call: 057128095818
                         02162681677
More Incoming Numbers：https://meeting.dingtalk.com/dialin/?corpId=dingd8e1123006514592
The membership link：https://meeting.dingtalk.com/j/1QVM3crF92O
```
