### ISSUE TITLE
SpringBoot版本2.7，Seata版本1.6.1，AT事务回滚失败问题

### ISSUE THREAD

**Issue by ChienSun666** [alibaba/spring-cloud-alibaba#3348]
因为主键大小写问题，导致回滚时无法匹配到pk，导致delete语句不完整。出现下面现象：
错误sql：delete from table where ;

<img width="1748" alt="1" src="https://github.com/alibaba/spring-cloud-alibaba/assets/136292070/6f4cd0c6-ad6a-4526-88b3-fccfd7298eca">
<img width="1713" alt="2" src="https://github.com/alibaba/spring-cloud-alibaba/assets/136292070/b3ab24fe-7547-4108-9476-8ab17197843e">

**Comment by yuluo-yx** [comment]
This looks like a problem with seata, please go to the relevant community to ask questions! https://github.com/seata/seata/issues/new/choose
