### ISSUE TITLE
Spring Boot3.1 version is not supported

### ISSUE THREAD

**Issue by jiangqiang1996** [alibaba/spring-cloud-alibaba#3351]
**Describe what problem you have encountered**
Spring Boot3.1 version is not supported
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/44720422/49942cd2-5d37-42c2-9333-f2abc4ec564e)

springboot3.0.7 is supported

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/44720422/af85e11e-05fe-46df-a358-87b8b5c95fc9)

Because springcloud does not support springboot3.1
[https://spring.io/projects/spring-cloud#overview](https://spring.io/projects/spring-cloud#overview)

But if I introduce the springcloud2022.0.3 version separately in the project, it can start normally.

**Comment by yuluo-yx** [comment]
So what do you mean by that?
If you need to use Spring Cloud Alibaba, please refer to the release notes https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by steverao** [comment]
The community has not done adaptation yet.
