### ISSUE TITLE
Image build request failed with exit status 1

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3355]
enviroment: spring-cloud-alibaba-2022.0.0.0-RC2   + graalvm-ee-java17-22.3.2 
in dir: spring-cloud-alibaba-2022.0.0.0-RC2/spring-cloud-alibaba-examples/integrated-example/integrated-praise-provider 
execute：mvn -Pnative native:compile -DskipTests   to build native-image

error was found：
Error: Image build request failed with exit status 1

detail:

[2/7] Performing analysis...  [*]                                                                       (53.7s @ 3.19GB)
  20,701 (89.29%) of 23,183 classes reachable
  33,225 (61.76%) of 53,799 fields reachable
 108,215 (60.64%) of 178,468 methods reachable
   1,136 classes,   532 fields, and 5,744 methods registered for reflection
       2 native libraries: m, stdc++

Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. To see why org.apache.commons.logging.LogFactory got initialized use --trace-class-initialization=org.apache.commons.logging.LogFactory
org.apache.commons.logging.LogFactoryService was unintentionally initialized at build time. To see why org.apache.commons.logging.LogFactoryService got initialized use --trace-class-initialization=org.apache.commons.logging.LogFactoryService
To see how the classes got initialized, use --trace-class-initialization=org.apache.commons.logging.LogFactory,org.apache.commons.logging.LogFactoryService
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
------------------------------------------------------------------------------------------------------------------------
                        3.8s (5.6% of total time) in 27 GCs | Peak RSS: 5.87GB | CPU load: 5.39

how to resolve it?

**Comment by ruansheng8** [comment]
Try adding `buildArgs` to maven plugin: 
```xml
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <buildArgs>
                        --no-fallback
                        --initialize-at-build-time=org.apache.commons.logging.LogFactory
                        --initialize-at-build-time=org.apache.commons.logging.LogFactoryService
                        --initialize-at-build-time=org.slf4j.MDC
                        --initialize-at-build-time=ch.qos.logback.classic.Level
                        --initialize-at-build-time=ch.qos.logback.classic.Logger
                        --initialize-at-build-time=ch.qos.logback.core.util.StatusPrinter
                        --initialize-at-build-time=ch.qos.logback.core.status.StatusBase
                        --initialize-at-build-time=ch.qos.logback.core.status.InfoStatus
                        --initialize-at-build-time=ch.qos.logback.core.spi.AppenderAttachableImpl
                        --initialize-at-build-time=org.slf4j.LoggerFactory
                        --initialize-at-build-time=ch.qos.logback.core.util.Loader
                        --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder
                        --initialize-at-build-time=ch.qos.logback.classic.spi.ThrowableProxy
                        --initialize-at-build-time=ch.qos.logback.core.CoreConstants
                        --report-unsupported-elements-at-runtime
                        --allow-incomplete-classpath
                        -H:+ReportExceptionStackTraces
                    </buildArgs>
                </configuration>
            </plugin>
```

**Comment by imgoby** [comment]
Thanks.
I have tow question:
(1)How to know the --initialize-at-build-time 's class? Is it found by checking exception one by one?
(2) --no-fallback is not set in pom.xml file of spring cloud alibaba example project. Is --no-fallback  default  ?

**Comment by ruansheng8** [comment]
> Thanks. I have tow question: (1)How to know the --initialize-at-build-time 's class? Is it found by checking exception one by one? (2) --no-fallback is not set in pom.xml file of spring cloud alibaba example project. Is --no-fallback default ?

1. Yes, it can usually be found in the build's error log.
2. `--no-fallback` is not a required configuration, it means `build a standalone image or report a failure`.

Other more relevant build parameters can be found in https://www.graalvm.org/22.3/reference-manual/native-image/overview/BuildOptions/
