### ISSUE TITLE
缺少nacos最新版本与spring cloud nacos config/nacos discovery版本的对应关系

### ISSUE THREAD

**Issue by jiehao2019** [alibaba/spring-cloud-alibaba#3358]
nacos 官网上（ https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html ）说Nacos与spring-cloud-starter-alibaba-nacos-config/ spring-cloud-starter-alibaba-nacos-discovery 的版本对应关系在spring-cloud-alibaba的wiki上维护的，网址是https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E ，如下图
<img width="996" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/60006900/c00a26dc-2d6b-4846-b7b2-67bdb0a09402">

但上图中nacos 2.x的版本最新只到2.2.1， 1.x的版本最新只到1.4.2. 而目前2.x的最新版本是2.2.3，1.x的最新版本是1.4.6. 也就是说缺少2.2.2/2.2.3，1.4.3/1.4.4/1.4.5/1.46这几个版本对应关系。

另外，在maven中央仓库上查看spring-cloud-starter-alibaba-nacos-discovery最近的几个版本，可以看到其引用的nacos版本分别如下：
<img width="1346" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/60006900/7ad564e1-02f0-43c4-a461-ef977fd5eaf0">

spring-cloud-starter-alibaba-nacos-discovery版本为2020.0.RC1， nacos-client版本为1.4.1
spring-cloud-starter-alibaba-nacos-discovery版本为2021.0.1.0， nacos-client版本为1.4.2
spring-cloud-starter-alibaba-nacos-discovery版本为2021.0.4.0， nacos-client版本为2.0.4
spring-cloud-starter-alibaba-nacos-discovery版本为2021.0.4.0， nacos-client版本为2.2.0
spring-cloud-starter-alibaba-nacos-discovery版本为[2021.1](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2021.1)， nacos-client版本为1.4.1
spring-cloud-starter-alibaba-nacos-discovery版本为[2022.0.0.0-RC1](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2022.0.0.0-RC1)， nacos-client版本为2.2.1-RC
spring-cloud-starter-alibaba-nacos-discovery版本为[2022.0.0.0-RC1](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2022.0.0.0-RC2)， nacos-client版本为2.2.1
也没有2.2.2/2.2.3，1.4.3/1.4.4/1.4.5/1.4.6这几版本。还是说这几个版本可以和上述的discovery版本都兼容？

**Comment by steverao** [comment]
社区这边一般会针对有较大特性改变的版本做适配，你说的这些社区暂时未做适配。

**Comment by jiehao2019** [comment]
> 

@steverao 好的，感谢回答。那是否可以理解nacos版本找最近的sca版本即可（如nacos1.4.4没有对应的sca版本，使用最接近版本1.4.2或者更早的版本均可）

**Comment by steverao** [comment]
> > 
> 
> @steverao 好的，感谢回答。那是否可以理解nacos版本找最近的sca版本即可（如nacos1.4.4没有对应的sca版本，使用最接近版本1.4.2或者更早的版本均可）

是的
