### ISSUE TITLE
使用@RefreshScope注解导致跨域配置失效

### ISSUE THREAD

**Issue by wzgl998877** [alibaba/spring-cloud-alibaba#3369]
我在解决跨域问题，我使用了一个跨域配置类，他是生效的，前端访问没有任何问题，但我想让跨域的配置实时生效，所以我使用了@RefreshScope注解，我用的配置中心是nacos，我使用这个注解后直接导致了跨域配置失效，前端访问我接口的时候报了跨域错误
I am now solving cross-domain problems,I added a cross domain configuration，He is effective and solved the cross-domain problem for me，Now I want to refresh the cross-domain configuration in real time，So I used @RefreshScope annotation，But even the cross-domain configuration is invalid

I added a cross domain configuration

@Slf4j
@Configuration
public class FilterConfiguration {
    @Value("${jlpay.business.filter.allowCredentials:true}")
    private boolean allowCredentials;
    @Value("${jlpay.business.filter.allowedHeader:*}")
    private String allowedHeader;
    @Value("${jlpay.business.filter.allowedMethod:*}")
    private String allowedMethod;
    @Value("${jlpay.business.filter.allowedOrigin:*}")
    private String allowedOrigin;
    @Value("${jlpay.business.filter.corsPath:/**}")
    private String corsPath;

    /**
     * 跨域请求配置
     * @return
     */
    private CorsConfiguration buildCorsConfig() {
        CorsConfiguration corsConfig = new CorsConfiguration();
        corsConfig.setAllowCredentials(allowCredentials);
        corsConfig.addAllowedHeader(allowedHeader);
        corsConfig.addAllowedMethod(allowedMethod);
        //指定域名拦截配置
        if (!StringUtils.isEmpty(allowedOrigin) && !CorsConfiguration.ALL.equals(allowedOrigin)) {
            String[] originArr = allowedOrigin.split(",");
            for (String origin : originArr) {
                corsConfig.addAllowedOrigin(origin);
            }
        } else {
            corsConfig.addAllowedOrigin(CorsConfiguration.ALL);
        }

        return corsConfig;
    }

    /**
     * 跨域请求过滤器配置
     */
    @Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource configSource = new UrlBasedCorsConfigurationSource();
        //注：暂定所有接口均允许跨域,建议针对具体接口配置允许跨域
        configSource.registerCorsConfiguration(corsPath, buildCorsConfig());

        log.info("跨域请求过滤器配置:{}", JSONObject.toJSONString(configSource.getCorsConfigurations()));
        return new CorsFilter(configSource);
    }

    /**
     * 跨域请求配置注册至过滤器
     * @return
     */
    @Bean
    public FilterRegistrationBean corsFilterRegist() {
        FilterRegistrationBean filterRegistration = new FilterRegistrationBean();
        filterRegistration.setFilter(corsFilter());
        filterRegistration.setName("corsFilter");
        filterRegistration.setOrder(0);
        return filterRegistration;
    }
}
He is effective and solved the cross-domain problem for me，Now I want to refresh the cross-domain configuration in real time，So I used @RefreshScope annotation

@Slf4j
@Configuration
@RefreshScope
public class FilterConfiguration {
    @Value("${jlpay.business.filter.allowCredentials:true}")
    private boolean allowCredentials;
    @Value("${jlpay.business.filter.allowedHeader:*}")
    private String allowedHeader;
    @Value("${jlpay.business.filter.allowedMethod:*}")
    private String allowedMethod;
    @Value("${jlpay.business.filter.allowedOrigin:*}")
    private String allowedOrigin;
    @Value("${jlpay.business.filter.corsPath:/**}")
    private String corsPath;

    /**
     * 跨域请求配置
     * @return
     */
    private CorsConfiguration buildCorsConfig() {
        CorsConfiguration corsConfig = new CorsConfiguration();
        corsConfig.setAllowCredentials(allowCredentials);
        corsConfig.addAllowedHeader(allowedHeader);
        corsConfig.addAllowedMethod(allowedMethod);
        //指定域名拦截配置
        if (!StringUtils.isEmpty(allowedOrigin) && !CorsConfiguration.ALL.equals(allowedOrigin)) {
            String[] originArr = allowedOrigin.split(",");
            for (String origin : originArr) {
                corsConfig.addAllowedOrigin(origin);
            }
        } else {
            corsConfig.addAllowedOrigin(CorsConfiguration.ALL);
        }

        return corsConfig;
    }

    /**
     * 跨域请求过滤器配置
     */
    @Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource configSource = new UrlBasedCorsConfigurationSource();
        //注：暂定所有接口均允许跨域,建议针对具体接口配置允许跨域
        configSource.registerCorsConfiguration(corsPath, buildCorsConfig());

        log.info("跨域请求过滤器配置:{}", JSONObject.toJSONString(configSource.getCorsConfigurations()));
        return new CorsFilter(configSource);
    }

    /**
     * 跨域请求配置注册至过滤器
     * @return
     */
    @Bean
    @RefreshScope
    public FilterRegistrationBean corsFilterRegist() {
        FilterRegistrationBean filterRegistration = new FilterRegistrationBean();
        filterRegistration.setFilter(corsFilter());
        filterRegistration.setName("corsFilter");
        filterRegistration.setOrder(0);
        return filterRegistration;
    }
}
But he can't refresh the configuration in real time, and what's worse, he makes my cross-domain configuration invalid，A cross-domain error occurred when the front end accessed my interface，The error is as follows has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. I hope everyone can help me to solve it, thank you

**Comment by BLineHouse** [comment]
我试了没问题啊，版本问题吧

**Comment by BLineHouse** [comment]
> 
或者使用 ConfigurationProperties bean 方式使用 然后还得动态调整过滤器的配置

**Comment by haidi-kong** [comment]
这个是因为@RefreshScope 导致FilterConfiguration  变成了一个facotorybean,  导致无法加载了serverletContext的filter链中。 建议使用ConfigurationProperties bean 方式使用，@RefreshScope并不是一个很好的使用方式。
