### ISSUE TITLE
相关文档需要更新

### ISSUE THREAD

**Issue by ghdong366** [alibaba/spring-cloud-alibaba#3373]
旧版的文档内容在新版中已经不适用，文档需要被更新
The content of the old version of the document is no longer applicable in the new version, and the document needs to be updated.

eg:
Netflix Ribbon is not in Nacos Discovery 2022.X, But it's still written here.
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/114221449/d09bd83d-15e2-432e-8992-273e5ea6b217)

**Comment by yuluo-yx** [comment]
社区最近正在建设官网，之后会在文档官网修复此问题。此文档模块将会被舍弃。
相关讨论issues：https://github.com/alibaba/spring-cloud-alibaba/issues/3285
欢迎参与：https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io
