### ISSUE TITLE
spring cloud gateway return 500

### ISSUE THREAD

**Issue by wanghu198343** [alibaba/spring-cloud-alibaba#3397]
**Which Component**
spring cloud gateway

**Describe what problem you have encountered**

spring cloud alibaba version is:2021.0.1.0
spring cloud version is: 2021.0.1

When the response time of a microservice's interface exceeds 30 seconds, Spring Cloud Gateway returns a 500 error.
I have set response-timeout and connect-timeout in application.yml:
 - id: per_route_timeouts
        uri: https://example.org
        predicates:
          - name: Path
            args:
              pattern: /delay/{timeout}
        metadata:
          response-timeout: 300000
          connect-timeout: 300000
and when api return result  whithin 20 seconds, It can work properly.
For example, if the timeout is set to 3 seconds and the API takes 5 seconds to respond, a 504 error will be returned.
but when api return result exceeds 30 seconds, Spring Cloud Gateway returns a 500 error, even though it hasn't exceeded the set timeout value.Error information like this:
   The connection observed an error
  reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

  2023-07-19 09:35:16.092 ERROR 30934 --- [or-http-epoll-5] a.w.r.e.AbstractErrorWebExceptionHandler : [85e0cead-12]  500 Server 
 Error for HTTP GET "/api/testTimeout?version=2.04.01"
 
  reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
  Error has been observed at the following site(s):

**Describe what information you have read**
I have read the reference doc of spring cloud gateway

**Comment by 123liuziming** [comment]
If the client does not send a request to the server for a long time, the server may be forced to close this TCP connection actively. The gateway returns this exception to the client when the downstream service does not send a response but the connection is terminated.

**Comment by 123liuziming** [comment]
One more thing, spring cloud gateway is not a project maintained by spring cloud alibaba. Please submit an issue to the spring cloud gateway community.  https://github.com/spring-cloud/spring-cloud-gateway

**Comment by wanghu198343** [comment]
Hi：
I'm sorry, I didn't explain it clearly. 
There is no problem if the backend microservice is written in Java. 
The current situation is that the backend service is written in Go and registered to Nacos using Sidecar，and this service not set connect timeout. 
The version of Sidecar is spring-cloud-alibaba-sidecar:2.2.0-RELEASE.




Do you have any solution for this? 


Thanks a lot.










At 2023-07-20 21:15:18, "Liu Ziming" ***@***.***> wrote:

One more thing, spring cloud gateway is not a project maintained by spring cloud alibaba. Please submit an issue to the spring cloud gateway community. https://github.com/spring-cloud/spring-cloud-gateway
