### ISSUE TITLE
question about healthcheck.

### ISSUE THREAD

**Issue by eacdy** [alibaba/spring-cloud-alibaba#3399]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery

**Describe the bug**
1. 我有两个服务：provider与consumer，consumer会调用provider
2. provider的配置如下：
```yaml
server:
  port: 8000
spring:
  application:
    name: provider
spring:
  cloud:
    nacos:
      discovery:
        ephemeral: false
```
同时，编写了Spring Boot Actuator健康指示器，如代码所示，健康指示器总是返回down
```
@Component
public class MyHealthIndicator extends AbstractHealthIndicator {
    @Override
    protected void doHealthCheck(Health.Builder builder) throws Exception {
        Health.Builder up = builder.up();
        up.withDetail("key", "value")
        up.down();
    }
}
```
来到Nacos界面，配置健康检查：
<img width="604" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/9031050/adaaf848-bcd9-4252-8651-fe2929ea470d">
检查结果，可以看到，Nacos Server已经认为实例不健康了。
<img width="1149" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/9031050/abd27c8b-8ac1-4c29-a0bd-54d5eb161929">

但是，我在consumer侧调试，获得结果却是这样的，也就是说，nacos client并没有过滤不健康的实例，而且还显示healthy为true。
<img width="1265" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/9031050/013d9302-68ee-4cf5-ac90-4e3ddad857b5">

**Additional context**
e.g.  MacOS  、Java 17、Spring Boot 3.0.2、Spring Cloud Alibaba 2022.0.0.0-RC2、Nacos Server 2.2.3

**Comment by ruansheng8** [comment]
使用以下Demo测试，看起来获取结果是符合预期的（单机和集群模式下都可以验证通过）

```java
    public static void main(String[] args) throws NacosException, InterruptedException {
        String serviceName = "test-service";
        NamingService namingService = NacosFactory.createNamingService("192.168.4.89:8848");
        // 构建实例信息
        Instance instance = new Instance();
        instance.setIp("127.0.0.1");
        instance.setPort(18081);
        instance.setHealthy(false);
        // 注册实例
        namingService.registerInstance(serviceName, instance);

        new Thread(() -> {
            while (true) {
                try {
                    List<Instance> instances = namingService.selectInstances(serviceName, true);
                    if (instances.isEmpty()) {
                        System.out.println("No healthy instance");
                        instances = namingService.selectInstances(serviceName, false);
                    }
                    for (Instance onlineInstance : instances) {
                        if (instances.isEmpty()) {
                            System.out.println("No instance");
                        } else {
                            String text = String.format("Host = %s:%s , Health = %s", onlineInstance.getIp(), onlineInstance.getPort(), onlineInstance.isHealthy());
                            System.out.println(text);
                        }
                    }
                    Thread.sleep(1000);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        }).start();
        Thread.sleep(10000000);
    }
```
