### ISSUE TITLE
The annotation @RefreshScope is used on the class annotated @Configuration, and the refreshed value of nacos cannot be obtained

### ISSUE THREAD

**Issue by ximenfeixue** [alibaba/spring-cloud-alibaba#3405]
Describe the bug

Expected behavior
After nacos is changed, the caller gets the changed value

Actually behavior
2023-07-24 08:04:13,365 [INFO] [TID: N/A ] [GID:] (nacos.client.cachedata.internal.notifier) o.s.c.e.e.RefreshEventListener.handle:73 - Refresh keys changed: [data.provider.sets]

After nacos is changed, the caller gets the value before the change

How to Reproduce

Go to `@Configuration
@RefreshScope
public class SportDataServiceConfig {
https://github.com/value("#{${data.provider.sets:}}")
public Map<SportType, Set> sportTypeSetMap;

public Map<SportType, Set> getSportTypeSetMap() {
return sportTypeSetMap;
}
}
@service
@RefreshScope
public class Test {

https://github.com/resource
private SportDataServiceConfig sportDataServiceConfig;

public Set getPrimaryDataProviderSet(SportType sportType) {
if (sportDataServiceConfig.getSportTypeSetMap().containsKey(sportType)) {
return sportDataServiceConfig.getSportTypeSetMap().get(sportType);
}
return Sets.immutableEnumSet(DataProvider.ALL);
}
}
`

Click on 'update naos value',

Scroll down to 'getPrimaryDataProviderSet'

See errors

Desktop (please complete the following information):

OS: [ Centos]
Version [nacos-server 2.04, nacos-client 2.04]
SDK [ spring-cloud-alibaba-nacos, dubbo]
Additional context

**Comment by yuluo-yx** [comment]
Please provide a complete example, so that students in the community can reproduce and fix the problem

**Comment by ximenfeixue** [comment]
@Configuration
@RefreshScope
public class SportDataServiceConfig {
    @Value("#{${data.provider.sets:}}")
    public Map<SportType, Set<String>> sportTypeSetMap;

    public Map<SportType, Set<String>> getSportTypeSetMap() {
        return sportTypeSetMap;
    }
}


@service
@RefreshScope
public class Test {

@Resource
private SportDataServiceConfig sportDataServiceConfig;

public Set<String> getPrimaryDataProviderSet(SportType sportType) {
if (sportDataServiceConfig.getSportTypeSetMap().containsKey(sportType)) {
return sportDataServiceConfig.getSportTypeSetMap().get(sportType);
}
return Sets.immutableEnumSet("");
}
}

public enum SportType {
    ALL(-1, "All"),
    FOOTBALL(1, "Football"),
    BASKETBALL(2, "Basketball"),;
}

Kindly hope to get help from all students!

**Comment by yuluo-yx** [comment]
你可以将代码上传到 github 仓库，在这里贴出 github 仓库连接，你在这里贴的代码没有任何格式，并且复制过去报错。顺便也可以将 nacos 配置文件中的配置一起贴出来

```
Cannot resolve method 'immutableEnumSet(String)'
'SportType()' cannot be applied to '(int, java.lang.String)'
```
