### ISSUE TITLE
使用docker滚动更新服务，nacos注册中心，dubbo provider重启 有几率会导致consumer始终去连旧的ip 导致服务一直不可用

### ISSUE THREAD

**Issue by xiekong** [alibaba/spring-cloud-alibaba#3406]
spring-cloud-alibaba 版本  2.2.5.RELEASE
dubbo 版本 2.7.18
nacos-client 2.0.2

当使用容器滚动更新 provider的时候，consumer始终使用旧的ip去调用 provider

![123321321312312](https://github.com/alibaba/spring-cloud-alibaba/assets/16237228/648ef6d5-0a95-471c-9a9e-eac3127e7133)

不知道何种原因，旧的provider下线之后 ReconnectTimerTask 未被注销，一直重连

类似issues #1259 #1253 #1595

**Comment by zhangjh1984** [comment]
遇到同样问题
spring-cloud-alibaba版本：2.2.7.RELEASE
dubbo版本：2.7.15
nacos-client：1.4.2

**Comment by a490726690** [comment]
这个问题解决了吗
我的版本：
springboot: 2.6.13
spring-cloud-alibaba 版本 2021.0.5.0
dubbo 版本 2.7.23
nacos-client 2.0.2
provider重启后生成新的ip元信息，consumer使用调用老的ip元信息

**Comment by elvislou** [comment]
> 这个问题解决了吗 我的版本： springboot: 2.6.13 spring-cloud-alibaba 版本 2021.0.5.0 dubbo 版本 2.7.23 nacos-client 2.0.2 provider重启后生成新的ip元信息，consumer使用调用老的ip元信息

你们是只是心跳会连老的ip，还是业务调用也会调老的ip，导致调用失败?

**Comment by a490726690** [comment]
> > 这个问题解决了吗 我的版本： springboot: 2.6.13 spring-cloud-alibaba 版本 2021.0.5.0 dubbo 版本 2.7.23 nacos-client 2.0.2 provider重启后生成新的ip元信息，consumer使用调用老的ip元信息
> 
> 你们是只是心跳会连老的ip，还是业务调用也会调老的ip，导致调用失败?

我感觉是都会
