### ISSUE TITLE
📣 Spring Cloud Alibaba 2022.0.0.0 is released

### ISSUE THREAD

**Issue by steverao** [alibaba/spring-cloud-alibaba#3408]
Hello Community,

We are very glad to announce that Spring Cloud Alibaba 2022.0.0.0 is released.

You can check detailed release notes here:

- Release notes: https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2022.0.0.0
- Relevant article: https://mp.weixin.qq.com/s/4haTyXUmh8m-dBQaEzwDJw

If there are no notable bugs, the official version will be released shortly!

If you have any questions using this version, please report the issue on Github.

Best regards,
Spring Cloud Alibaba Team

**Comment by wang3develop** [comment]
等待对SpringBoot3.1.x（Spring Cloud 2022.0.3）的支持！
试着升级一个项目到SpringBoot3，Spring Cloud Alibaba 2022.0.0.0需要SpringBoot3.0，而对应的SpringBoot3.0.x的hibernate版本过低。

Waiting for support for SpringBoot3.1.x (Spring Cloud 2022.0.3)!
Try upgrading a project to SpringBoot3. Spring Cloud Alibaba 2022.0.0.0 requires SpringBoot3.0, and the corresponding hibernate version of SpringBoot3.0. x is too low.

**Comment by motcs** [comment]
When the gateway service is registered with NACOS and restarted using Docker scrolling update, the IP registered in the NACOS registry is inconsistent with that in the Docker, causing the gateway to be unable to communicate with other microservices. The problem has not been found yet, please solve it

**Comment by muzhi9018** [comment]
When do you plan to release versions that are compatible with Spring Cloud 2023. x and Spring Boot 3.2. x? I can't wait anymore

**Comment by ruansheng8** [comment]
> When do you plan to release versions that are compatible with Spring Cloud 2023. x and Spring Boot 3.2. x? I can't wait anymore

@muzhi9018 `2023.0.0.0-RC1` has been released
