### ISSUE TITLE
lose graalvm metadata with nacos config module

### ISSUE THREAD

**Issue by zzhujing** [alibaba/spring-cloud-alibaba#3409]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Config

**Describe the bug**
config refresh with native image error, tips lose some class method reflection
- ConfigQueryResponse#setEncryptedDataKey
- ConfigChangeNotifyRequest#setsetTenant
**Simplest demo**
The URL of the simplest demo to reproduce the problem.

**To Reproduce**
1. import nacos config
2. native-image -Pnative native:compile
3. config change on nacos dashboard

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Kotlin With Java17 、 Version 2022.0.0.0.RELEASE

**Comment by zzhujing** [comment]
Is this scenario underconsidered when generating metadata through the graalvm agent?

**Comment by zzhujing** [comment]
<img width="1068" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/40297160/c2904477-628f-4f9c-8f7f-7298330b2858">
it's work by add RuntimeHints with spring aot processing api

**Comment by ruansheng8** [comment]
@zzhujing 
Thanks for your feedback. This is because some configurations were overwritten when we finally integrated with other modules. We will fix it in the next version.
