### ISSUE TITLE
java程序升级了nacos客户端版本到建议版本(升级至2.2.6.RELEASE)，启动时报错

### ISSUE THREAD

**Issue by khxkang** [alibaba/spring-cloud-alibaba#3417]
java程序升级了nacos客户端版本到建议版本后，启动时报错
nacos客户端 从2.0.3升级至2.2.6.RELEASE 后报错。如图
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/85337276/79289baa-e6dd-4b5e-9744-1e045c73601f)

After upgrading the Nacos client version to the recommended version in the Java program, an error occurred during startup
An error was reported after upgrading the nacos client from 2.0.3 to 2.2.6.RELEASE. As shown in the figure

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuluo-yx** [comment]
Can you explain in detail the versions of spring cloud alibaba and spring cloud you are using?
