### ISSUE TITLE
AOT and Native Image Support: Spring Boot 3.0 集成 Nacos，无法刷新配置文件的问题

### ISSUE THREAD

**Issue by sk142857** [alibaba/spring-cloud-alibaba#3422]
- 依赖版本

```
<spring-boot.version>3.1.2</spring-boot.version>
<spring-cloud.version>2022.0.4</spring-cloud.version>
<spring-cloud.alibaba.version>2022.0.0.0</spring-cloud.alibaba.version>
```
- 问题描述

不使用`Spring Native`部署是没有问题的，刷新也是正常的。但是，如果使用`Spring Cloud `官方说明了，如果要启用 `openFeign` 或者 `gateway` 之类的，都是必须要关闭`spring.cloud.refresh`的。

https://docs.spring.io/spring-cloud-openfeign/docs/4.0.4/reference/html/#aot-and-native-image-support

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/75599950/340e5429-efba-43b5-a83e-0434d440ff0c)

```xml
spring.cloud.refresh.enabled: false
```

经过验证，Nacos配置文件刷新的问题可以重现。请问，有没有什么办法解决这个问题？

**Comment by yuluo-yx** [comment]
You can refer to the release notes to reselect the component version and try again, or refer to the official [example](https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example) provided by the community to configure.
