### ISSUE TITLE
nacos服务列表中看不到名字？

### ISSUE THREAD

**Issue by piaohailin** [alibaba/spring-cloud-alibaba#3423]
软件版本
nacos 2.2.3
alibaba.cloud 2022.0.0.0
spring.cloud 2022.0.3
spring.boot 3.0.8
jdk 17
docker 桌面版本

开发环境，docker 中运行 nocos，开发环境可以正常连接配置中心、注册中心。namespace与nacos 空间id一致。nacos服务列表正常。

gateway打包docker环境后（相同网络），从控制台显示已经正常加载配置中心、注册中心。但是nacos服务列表没有信息。

**Comment by yuluo-yx** [comment]
Can you provide an example demo, so that there is no way to reproduce the problem you described, and it is not convenient for students in the community to deal with it in time.

**Comment by SurpriseWang** [comment]
如果你是使用gateway无法注册的话，看一看你的gateway是不是用了”同步阻塞相关的操作“。例如：注册OpenFeign客户端给gatewayFilter。

**Comment by piaohailin** [comment]
> 如果你是使用gateway无法注册的话，看一看你的gateway是不是用了”同步阻塞相关的操作“。例如：注册OpenFeign客户端给gatewayFilter。

问题是这个现象，只有在gateway docker打包后才出现nacos无法看到名字（同一网络）连接配置中心、注册中心没有问题从控制台上看数据加载ok，gateway jar 运行 以及idea环境运行都没这个问题。
