### ISSUE TITLE
Test cases cannot achieve project readme functionality

### ISSUE THREAD

**Issue by MBAI-Bill** [alibaba/spring-cloud-alibaba#3427]
According to the self described file of the project, when running the test example after one step of operation, it was found that the number of likes for the function of "circuit breaker current limiting, peak shaving and valley filling capacity" did not change

**Comment by yuluo-yx** [comment]
Similarly https://github.com/alibaba/spring-cloud-alibaba/issues/3255
Can you make a pr for this to fix it?

**Comment by MBAI-Bill** [comment]
> 同样#3255 你能为此做一个公关来修复它吗？
Of course, because it's my first time using GitHub to participate in an open source project, it may take me some time to understand the rules

**Comment by yuluo-yx** [comment]
> > 同样#3255 你能为此做一个公关来修复它吗？
> > Of course, because it's my first time using GitHub to participate in an open source project, it may take me some time to understand the rules

Thanks! @China-MBAI

**Comment by MBAI-Bill** [comment]
> > > 同样#3255 你能为此做一个公关来修复它吗？
> > > Of course, because it's my first time using GitHub to participate in an open source project, it may take me some time to understand the rules
> 
> Thanks! @China-MBAI
I am currently facing this issue. Do I lack the permission to submit a new branch"remote: Permission to alibaba/spring-cloud-alibaba.git denied to China-MBAI"

**Comment by ruansheng8** [comment]
Refer https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6%E5%B0%86%E5%85%B6-clone-%E5%88%B0%E6%9C%AC%E5%9C%B0

**Comment by yuluo-yx** [comment]
> > > > 同样#3255 你能为此做一个公关来修复它吗？
> > > > Of course, because it's my first time using GitHub to participate in an open source project, it may take me some time to understand the rules
> > 
> > 
> > Thanks! @China-MBAI
> > I am currently facing this issue. Do I lack the permission to submit a new branch"remote: Permission to alibaba/spring-cloud-alibaba.git denied to China-MBAI"

You can refer to https://github.com/alibaba/spring-cloud-alibaba/wiki/%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB% A3%E7%A0%81

**Comment by yuluo-yx** [comment]
> > > > 同样#3255 你能为此做一个公关来修复它吗？
> > > > Of course, because it's my first time using GitHub to participate in an open source project, it may take me some time to understand the rules
> > 
> > 
> > Thanks! @China-MBAI
> > I am currently facing this issue. Do I lack the permission to submit a new branch"remote: Permission to alibaba/spring-cloud-alibaba.git denied to China-MBAI"

1. You should fork the project to your github space,
2. git pull to your local machine,
3. Create a branch and modify the code
4. Then push your local branch to your github space,
5. pr to the main warehouse of the project

**Comment by China-MBAI** [comment]
> 参考[https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6% E5%B0%86%E5%85%B6-克隆-%E5%88%B0%E6%9C%AC%E5%9C%B0](https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6%E5%B0%86%E5%85%B6-clone-%E5%88%B0%E6%9C%AC%E5%9C%B0)
Thank you.

**Comment by MBAI-Bill** [comment]
> > > > > #3255你能为此做一个公关来修复它吗？当然
> > > > > ，因为我是第一次使用GitHub参与开源项目，所以可能需要一些时间来理解规则
> > > 
> > > 
> > > 谢谢！@China-MBAI
> > > 我目前正面临这个问题。我是否缺少提交新分支的权限“远程：中国-MBAI 拒绝 alibaba/spring-cloud-alibaba.git 的权限”
> 
> 1. 你应该将项目 fork 到你的 github 空间，
> 2. git pull 到你的本地机器，
> 3. 创建分支并修改代码
> 4. 然后将你的本地分支推送到你的github空间，
> 5. pr到项目主仓库

Thank you.

**Comment by MBAI-Bill** [comment]
> 参考[https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6% E5%B0%86%E5%85%B6-克隆-%E5%88%B0%E6%9C%AC%E5%9C%B0](https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6%E5%B0%86%E5%85%B6-clone-%E5%88%B0%E6%9C%AC%E5%9C%B0)

Thank you.

**Comment by MBAI-Bill** [comment]
> Refer https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6%E5%B0%86%E5%85%B6-clone-%E5%88%B0%E6%9C%AC%E5%9C%B0

I would like to ask about the "git checkout master" under the "Merge latest code" in this document, but it seems that this project does not have this branch. What should I do

**Comment by ruansheng8** [comment]
> > Refer https://sca.aliyun.com/zh-cn/community/developer/contributor-guide/new-contributor-guide_dev#fork-%E4%BB%93%E5%BA%93%E5%B9%B6%E5%B0%86%E5%85%B6-clone-%E5%88%B0%E6%9C%AC%E5%9C%B0
> 
> I would like to ask about the "git checkout master" under the "Merge latest code" in this document, but it seems that this project does not have this branch. What should I do

You can use `2022.x` or `2.2.x`
