### ISSUE TITLE
YAMLException Deploy springcloud in docker, using springcloudaliba 

### ISSUE THREAD

**Issue by fatebugs** [alibaba/spring-cloud-alibaba#3434]
服务器环境：Windowsserver 2019
使用docker版本:Docker Desktop 4.21.1 (114176)
使用docker镜像：eclipse-temurin:11.0.19_7-jre-windowsservercore-1809
nacos版本：2.2.0
spring.cloud.alibaba.version：2021.0.1.0

Server environment: Windows server 2019
Use docker version: Docker Desktop 4.21.1 (114176)
Use the docker image: eclipse-temurin:11.0.19_7-jre-windowsservercore-1809
Nacos version: 2.2.0
spring.cloud.alibaba.version: 2021.0.1.0

出现问题：
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/65278566/c984680b-5a51-4db1-9c61-a5bec711caaf)

原因是我在配置文件中使用了中文导致的

我想问一下，我是否有办法将启动时读取nacos配置文件使用的读取yaml方法进行替换或者修改
使得我能够在nacos中保留中文配置

由于是WindowsServerdocker，所以docker镜像中貌似并不能修改系统的字符集

The reason is that I used Chinese in the configuration file

I would like to ask, is there a way for me to replace or modify the method of reading yaml used to read nacos configuration files at startup
Allows me to keep the Chinese configuration in nacos

Since it is WindowsServerdocker, it seems that the character set of the system cannot be modified in the docker image

**Comment by ruansheng8** [comment]
Refer to https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md

**Comment by yuluo-yx** [comment]
Maybe you can try properties configuration files?

**Comment by pei-han** [comment]
> 服务器环境：Windowsserver 2019 使用docker版本:Docker Desktop 4.21.1 (114176) 使用docker镜像：eclipse-temurin:11.0.19_7-jre-windowsservercore-1809 nacos版本：2.2.0 spring.cloud.alibaba.version：2021.0.1.0
> 
> Server environment: Windows server 2019 Use docker version: Docker Desktop 4.21.1 (114176) Use the docker image: eclipse-temurin:11.0.19_7-jre-windowsservercore-1809 Nacos version: 2.2.0 spring.cloud.alibaba.version: 2021.0.1.0
> 
> 出现问题： ![image](https://private-user-images.githubusercontent.com/65278566/263144056-c984680b-5a51-4db1-9c61-a5bec711caaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzA1ODYsIm5iZiI6MTczNDA3MDI4NiwicGF0aCI6Ii82NTI3ODU2Ni8yNjMxNDQwNTYtYzk4NDY4MGItNWE1MS00ZGIxLTljNjEtYTViZWM3MTFjYWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA2MTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MmZhZjMxYjA3ZTZiNThmOTY2ODhkYzRjYTIwMDc4YzQ4ZDg3NWQ4ZTVkNWVlNzkxYmNhNGYzZGU0MDJmYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1H_ANjqItFik9hcyt2jlUj2ctpQ6wudOUUpuZhyyYpI)
> 
> 原因是我在配置文件中使用了中文导致的
> 
> 我想问一下，我是否有办法将启动时读取nacos配置文件使用的读取yaml方法进行替换或者修改 使得我能够在nacos中保留中文配置
> 
> 由于是WindowsServerdocker，所以docker镜像中貌似并不能修改系统的字符集
> 
> The reason is that I used Chinese in the configuration file
> 
> I would like to ask, is there a way for me to replace or modify the method of reading yaml used to read nacos configuration files at startup Allows me to keep the Chinese configuration in nacos
> 
> Since it is WindowsServerdocker, it seems that the character set of the system cannot be modified in the docker image

我这边环境是spring boot3 ，spring 6 ，spring cloud alibaba 2003，nacos server 2.3.0-beta
在windows上从，命令行mvn spring-boot:run运行服务，会报这样的异常信息，然而从IDE，例如eclipse却没有这个问题。
不知道这个问题怎么解决？
同时，我本地环境eclipse运行开发的服务，可以正常启动，但是在nacos的服务列表中看不到
