### ISSUE TITLE
In Spring Boot 3.X, nacos config is used with the "application" configuration file, and the "shared-configs|extension-configs" configuration no longer takes effect

### ISSUE THREAD

**Issue by ztgoto** [alibaba/spring-cloud-alibaba#3435]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
spring-cloud-starter-alibaba-nacos-config:2022.0.0.0
spring-cloud:2022.0.4
spring-boot:3.1.2

**Describe what problem you have encountered**
spring boot 当前好像不再推荐bootstrap配置文件，而是推荐将配置放到application配置文件当中，application导入外部配置改用了`spring.config.import`来导入。
然后我按当前spring boot的规范来使用nacos config，但发现`spring.cloud.nacos.config.shared-configs`一些配置不生效了。在spring boot当前推荐的这种模式下（不使用bootstrap配置文件和库）我该如何使用`spring.cloud.nacos.config.shared-configs|extension-configs` 配置项？
Spring Boot no longer seems to recommend bootstrap configuration files, but recommends putting the configuration in the application configuration file, and the application import external configuration is imported using 'spring.config.import' instead.
Then I used nacos config according to the current spring boot specification, but found that some of the 'spring.cloud.nacos.config.shared-configs' configuration did not work. In this mode currently recommended by Spring Boot (without bootstrap configuration files and libraries), how do I use the 'spring.cloud.nacos.config.shared-configs|extension-configs' configuration item?

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by ruansheng8** [comment]
Refer to https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc
