### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config没有生效

### ISSUE THREAD

**Issue by jiangjinggit** [alibaba/spring-cloud-alibaba#3439]
NACOS服务端 版本 2.2.2

spring cloud项目添加如下依赖：（使用云原生应用脚手架生成）

<java.version>11</java.version>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
<spring-boot.version>2.4.2</spring-boot.version>
<spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
org.springframework.boot spring-boot-starter-web
    <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
添加如下配置：bootstrap.properties

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
server.port=8080
spring.application.name=nacos-study
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
spring.cloud.nacos.config.namespace=dev

服务启动不会去连接nacos服务端，感觉nacos客户端没有启动
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/35126441/90b48c58-558e-4f49-8731-f2bed22c3047)

我的问题：为什么引入了依赖：spring-cloud-starter-alibaba-nacos-config，不会自动注入nacos配置客户端，连接nacos服务，是因为客户端版本跟服务端版本不匹配导致的吗？可是我是使用云原生脚手架生成出来的，版本不是会配对好吗？麻烦官方大佬帮忙分析一下，谢谢了

**Comment by yuluo-yx** [comment]
分享一下你用的组件的版本？
或者你可以去官网参考一下组件版本配置，许多离谱的问题大多都是组件版本没有选合适导致的

**Comment by XiaoleLee** [comment]
2021.1这个版本的example好像有问题，按他那个，根本不可能根据bootstrap去连nacos，要加上这个依赖
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
            <version>3.0.1</version>
        </dependency>
```
好像高版本，已经不推荐从bootstrap去读取配置了。
