### ISSUE TITLE
Gateway service registration IP issue

### ISSUE THREAD

**Issue by motcs** [alibaba/spring-cloud-alibaba#3440]
When the gateway service is registered with NACOS and restarted using Docker scrolling update, the IP registered in the NACOS registry is inconsistent with that in the Docker, causing the gateway to be unable to communicate with other microservices. The problem has not been found yet, please solve it

**Comment by yuluo-yx** [comment]
Please check your port configuration in DockerFile and you can enter container try to ping other microservices, ensure docker network connectivity.

BTW, you can refer [docker-compose-env.yml](https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/integrated-example/docker-compose/docker-compose-env.yml) to the configuration.
