### ISSUE TITLE
2021.0.6.0 what time?

### ISSUE THREAD

**Issue by markr512** [alibaba/spring-cloud-alibaba#3444]

**Comment by yuluo-yx** [comment]
社区暂时没有明确的 roadmap

**Comment by Caratacus** [comment]
@yuluo-yx I also want to ask this question because 2021.0.5.0 introduces a new BUG.

**Comment by yuluo-yx** [comment]
> @yuluo-yx I also want to ask this question because 2021.0.5.0 introduces a new BUG.

What is the specific problem? You can raise an issue and discuss it together. @Caratacus

**Comment by Caratacus** [comment]
@yuluo-yx Thanks for your reply, I said the problem is this [Nacos integration with SpringBootAdmin](https://github.com/alibaba/spring-cloud-alibaba/pull/3307), hopefully alibaba group can release a new version to solve this problem.

**Comment by yuluo-yx** [comment]
> @yuluo-yx Thanks for your reply, I said the problem is this [Nacos integration with SpringBootAdmin](https://github.com/alibaba/spring-cloud-alibaba/pull/3307), hopefully alibaba group can release a new version to solve this problem.

okay, got it.

**Comment by Caratacus** [comment]
@yuluo-yx Many thanks.
