### ISSUE TITLE
项目启动时InetIPv6Utils无法注入到NacosDiscoveryProperties

### ISSUE THREAD

**Issue by fqtrnt** [alibaba/spring-cloud-alibaba#3445]
**Which Component**
Nacos Discovery

**Describe the bug**
项目启动InetIPv6Utils无法注入到NacosDiscoveryProperties

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field inetIPv6Utils in com.alibaba.cloud.nacos.NacosDiscoveryProperties required a bean of type 'com.alibaba.cloud.nacos.util.InetIPv6Utils' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)
```

**Simplest demo**
git clone https://github.com/fqtrnt/nacos-issue.git

**To Reproduce**
1. gradle bootRun

**Expected behavior**

**Additional context**
SpringBoot: 3.0.2
StringCloud: 2022.0.4
StirngCloudAlibaba: 2022.0.0
JDK: 17

**Comment by chickenlj** [comment]
> **Which Component** Nacos Discovery
> 
> **Describe the bug** 项目启动InetIPv6Utils无法注入到NacosDiscoveryProperties
> 
> ```
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Field inetIPv6Utils in com.alibaba.cloud.nacos.NacosDiscoveryProperties required a bean of type 'com.alibaba.cloud.nacos.util.InetIPv6Utils' that could not be found.
> 
> The injection point has the following annotations:
>         - @org.springframework.beans.factory.annotation.Autowired(required=true)
> ```
> 
> **Simplest demo** git clone https://github.com/fqtrnt/nacos-issue.git
> 
> **To Reproduce**
> 
> 1. gradle bootRun
> 
> **Expected behavior**
> 
> **Additional context** SpringBoot: 3.0.2 StringCloud: 2022.0.4 StirngCloudAlibaba: 2022.0.0 JDK: 17

I had your demo downloaded but failed to compile and run it.

**Comment by fqtrnt** [comment]
> > **Which Component** Nacos Discovery
> > **Describe the bug** 项目启动InetIPv6Utils无法注入到NacosDiscoveryProperties
> > ```
> > ***************************
> > APPLICATION FAILED TO START
> > ***************************
> > 
> > Description:
> > 
> > Field inetIPv6Utils in com.alibaba.cloud.nacos.NacosDiscoveryProperties required a bean of type 'com.alibaba.cloud.nacos.util.InetIPv6Utils' that could not be found.
> > 
> > The injection point has the following annotations:
> >         - @org.springframework.beans.factory.annotation.Autowired(required=true)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Simplest demo** git clone https://github.com/fqtrnt/nacos-issue.git
> > **To Reproduce**
> > 
> > 1. gradle bootRun
> > 
> > **Expected behavior**
> > **Additional context** SpringBoot: 3.0.2 StringCloud: 2022.0.4 StirngCloudAlibaba: 2022.0.0 JDK: 17
> 
> I had your demo downloaded but failed to compile and run it.
I'm add the mavenCentral to repositories. Please update and try again.
