### ISSUE TITLE
Starting two clients in the Docker results in messages being consumed by all clients and messages not being consumed at all times

### ISSUE THREAD

**Issue by java001** [alibaba/spring-cloud-alibaba#3452]
I installed Rocketmq: V4 on the server_ 4_ 0, client uses spring cloud stream: 3.1.4
When I start two clients on a server using Docker as the startup method, a group failure occurs, and all messages can be consumed by both clients, or messages are never consumed
When I started two services in Idea, everything was normal

我在服务端安装了 rocketmq:V4_4_0, 客户端使用spring-cloud-stream:3.1.4
当我在一台服务器启动两个客户端时, 启动方式为docker, 则出现group失效, 所有消息两个客户端都能消费, 或者是消息一直不被消费.
当我在idea中启动两个服务的时候, 一切都是正常的.

这是我的配置文件:
spring:
	  cloud:
	    stream:
	      function:
	        #消费者端配置
	        definition: notify_fail
	      rocketmq:
	        binder:
	          group: wap
	        bindings:
	          notify_fail-out-0:
	            producer:
	              group: notify_fail
	              sync: true
	          notify_fail-in-0:
	            consumer:
	              tags: PAY_IN:NOTIFY_FAIL
	              group: wap-notify
	              maxMessagesPerPoll: 40
	      bindings:
	        notify_fail-out-0:
	          destination: notify_fail
	        notify_fail-in-0:
	          destination: notify_fail
	          group: wap-notify

When I start Docker:
![2](https://github.com/alibaba/spring-cloud-alibaba/assets/21332033/8b051392-b97a-460c-9b0e-324d035271e7)

When I start in the operating system:
![l-2](https://github.com/alibaba/spring-cloud-alibaba/assets/21332033/9519383b-1560-4929-bafb-be462d106ffe)

**Comment by yuluo-yx** [comment]
检查下 docker 的网络设置，或许是容器通信有问题

**Comment by java001** [comment]
我启动的两个客户端都加了 --net host ,rocketmq 服务端没有设置 --net host是通过-p映射端口的.  需要给我启动的客户端单独设置一个网卡, 映射端口吗?

**Comment by yuluo-yx** [comment]
最好是将这些容器都放在同一个网络环境下，避免出现一些奇怪的问题。
