### ISSUE TITLE
java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.census.InternalCensusTracingAccessor

### ISSUE THREAD

**Issue by five-wang** [alibaba/spring-cloud-alibaba#3453]
jdk openJDK17
springboot 3.0.2
springcloudalibaba 2022.0.0.0
When the project started, it reported an error, and then checked the directory structure of nacos
项目启动的时候 报错，然后 看了下nacos的目录结构
<img width="364" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/66893381/176e5e46-2b8a-4c8f-a0e3-0b99e50c0654">
并没有census.InternalCensusTracingAccessor

**Comment by yuluo-yx** [comment]
有没有更多得报错信息？这样看不出来什么问题，最好能提供一个复现问题的 demo ？

**Comment by five-wang** [comment]
> 有没有更多得报错信息？这样看不出来什么问题，最好能提供一个复现问题的demo？

<img width="1136" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/66893381/cb1af23c-90d0-4f9e-bff7-13b747ebb36c">
就服务启动的时候 报了这个错

**Comment by yuluo-yx** [comment]
参考版本说明，调整下 nacos sca 的组件版本再试试呢？
