### ISSUE TITLE
Add Description of Parameter spring.cloud.nacos.discovery.group to the Documents

### ISSUE THREAD

**Issue by tangrui** [alibaba/spring-cloud-alibaba#3455]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
Nacos Discovery

**Is your feature request related to a problem? Please describe.**
Parameter `spring.cloud.nacos.discovery.group` does exist in the code, but there is no description for it in doc  https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery-en.

**Describe the solution you'd like**
Please add some explanation about this parameter into the table.

**Describe alternatives you've considered**

**Additional context**

**Comment by why-ohh** [comment]
Good Idea, We now have a new offical website and the documents in the github wiki section are not ready for further maintenance. If you have any contribution ideas, you can submit pull requeset to the new document repository, The github address is: https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io.
