### ISSUE TITLE
springcloud整合nacos拉取配置失败

### ISSUE THREAD

**Issue by jiangyy7** [alibaba/spring-cloud-alibaba#3456]
在nacos中配置属性，在配置文件中通过三个横杆隔开(---),项目启动无法获取配置属性。由于在拉取配置的时候三个横杆隔开会被分隔两个文档，导致spring在绑定属性的时候根据属性名获取属性值为空。
![截屏2023-09-08 10 56 58](https://github.com/alibaba/spring-cloud-alibaba/assets/143685573/11b28cb2-f1ba-4963-a138-3e8e877c940c)
<img width="786" alt="截屏2023-09-08 10 53 08" src="https://github.com/alibaba/spring-cloud-alibaba/assets/143685573/b0af01cf-f57a-47eb-85ae-ad25ea083b45">

截图是获取属性的方法，当没有三个横杆隔开的时候属性值是平铺的这样就能获取

**Comment by yuluo-yx** [comment]
为什么你要这样用，你的需求场景是啥样子？并不推荐这样使用
