### ISSUE TITLE
Is RocketMQ 5.0 supported now?

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/spring-cloud-alibaba#3459]
**Which Component**

RocketMQ

**Describe what problem you have encountered**

阿里云现在售卖的都是 RocketMQ 5.0 版本的服务，但是仓库里面用的 RocketMQ 客户端是 4.9 的，请问我购买之后能正常对接使用吗？
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/21048878/7a7fca9a-9b24-48d7-9fcc-5200174dfa2b)

**Comment by yuluo-yx** [comment]
社区并没有适配 rocketmq 5.0.
