### ISSUE TITLE
Which version of nacos， with Spring Cloud 2021.0.8 ？

### ISSUE THREAD

**Issue by streetbaby** [alibaba/spring-cloud-alibaba#3462]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery, Sentinel

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yuluo-yx** [comment]
I don’t understand what you mean. Are you saying that spring cloud 2021.8 should use that version of the nacos component?

**Comment by streetbaby** [comment]
> I don’t understand what you mean. Are you saying that spring cloud 2021.8 should use that version of the nacos component?

Yes.   Spring Cloud 2021.0.8， Which version of nacos to use?

**Comment by yuluo-yx** [comment]
> > I don’t understand what you mean. Are you saying that spring cloud 2021.8 should use that version of the nacos component?
> 
> Yes. Spring Cloud 2021.0.8， Which version of nacos to use?

okay, you can  see https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E. Get some information from it,
