### ISSUE TITLE
注册服务元数据

### ISSUE THREAD

**Issue by rxb1992** [alibaba/spring-cloud-alibaba#3470]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
nacos-api.jar 和 nacos-client.jar 版本是2.0.4

**Describe what problem you have encountered**
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/5337222/ce4f0c1f-eb85-40cb-8acc-3549bcc2910a)
如上图，需要在基于java sdk注册service时，注册一些自定义的元数据信息。
但是目前sdk中只发现了注册instance元数据的接口，请问如何注册service元数据

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuluo-yx** [comment]
没有太懂什么意思？具体说一下？

**Comment by rxb1992** [comment]
> 没有太懂什么意思？具体说一下？
如下图所示，我们自己构造了service对象（用于添加metadata）和instance对象，然后通过namingService.registerInstance接口来进行服务注册，但是我在instance对象上并没有找到用来关联上我自定义service对象的接口，同时在namingService.registerInstance上也没有可用来注册自定义service的参数接口。这种我应该怎么在注册instance时关联上我的service而不是用默认的？
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/5337222/a629fc77-8918-45eb-aeb3-ad4ecc28b35c)
