### ISSUE TITLE
[Discussion]: Delete `spring-cloud-alibaba-docs` module

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3473]
**module**

`spring-cloud-alibaba-docs` module.

**Is your feature request related to a problem? Please describe.**

Now that we have the official documentation website https://sca.aliyun.com, the docs module creates redundancy to a certain extent, making the central warehouse document

**Describe the solution you'd like**

- [ ] Delete `spring-cloud-alibaba-docs` module;
- [ ] Update WIKI page, guide users to the official website.

**Comment by chickenlj** [comment]
Agree.

But I think we need to think of a way to smoothly guide users to the official site instead of simply delete all docs which results in 404 for all visitors.

**Comment by chickenlj** [comment]
Wiki pages should also be marked as deprecated and gradually guide users to the official site.

**Comment by yuluo-yx** [comment]
> Wiki pages should also be marked as deprecated and gradually guide users to the official site.

yep, I'll make a todo list.

**Comment by ruansheng8** [comment]
`README.md` needs to be adjusted together.

**Comment by yuluo-yx** [comment]
> `README.md` needs to be adjusted together.

got it.
