### ISSUE TITLE
jasypt导致spring-cloud-stream-rocketmq问题

### ISSUE THREAD

**Issue by qfyl56** [alibaba/spring-cloud-alibaba#3475]
spring-boot3.0.9
spring-cloud2022.0.4
spring-cloud-alibaba2022.0.0.0
jdk21

当项目引入
<dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot</artifactId>
            <version>3.0.5</version>
        </dependency>
且配置了
@Configuration
@EnableEncryptableProperties
public class JasyptConfig {
    private final String keyLeft = "ssssssssssssssss";

    @Value("${jasypt.encryptor.password}")
    private String keyRight;

    @Bean("jasyptStringEncryptor")
    public StringEncryptor stringEncryptor() {
        PooledPBEStringEncryptor encryptor = new PooledPBEStringEncryptor();
        SimpleStringPBEConfig config = new SimpleStringPBEConfig();
        config.setPassword(keyLeft + keyRight);
        config.setAlgorithm("PBEWITHHMACSHA512ANDAES_256");
        config.setKeyObtentionIterations(1000);
        config.setPoolSize(1);
        config.setProviderName("SunJCE");
        config.setSaltGeneratorClassName("org.jasypt.salt.RandomSaltGenerator");
        config.setIvGeneratorClassName("org.jasypt.iv.RandomIvGenerator");
        config.setStringOutputType("base64");
        encryptor.setConfig(config);
        return encryptor;
    }
}

会导致项目启动正常但消费者无法注册到rocketmq

**Comment by qfyl56** [comment]
spring-boot2.7.13
spring-cloud2021.0.8
spring-cloud-alibaba2021.0.5.0
jdk1.8

无上述问题

**Comment by jiayaoO3O** [comment]
`spring:
  cloud:
    stream:
      function.autodetect : false`
      
关闭函数自动发现就可以了

**Comment by qfyl56** [comment]
> `spring: cloud: stream: function.autodetect : false`
> 
> 关闭函数自动发现就可以了

增加上述配置后还是不行
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/148169185/afde8a1d-c666-4662-9df4-54117b655eed)

**Comment by qfyl56** [comment]
> `spring: cloud: stream: function.autodetect : false`
> 
> 关闭函数自动发现就可以了

我现在处理事不引入jasypt-spring-boot，如果按照你说的配置了，本来还可以注册消费者配置后直接注册不了了
