### ISSUE TITLE
SpringBoot2.7，SpringCloudAlibaba 2021.1 读取 Nacos 配置信息，不支持 --- 符号

### ISSUE THREAD

**Issue by lukeliujun** [alibaba/spring-cloud-alibaba#3476]
SpringBoot2.7，SpringCloudAlibaba 2021.1 读取 Nacos 配置信息，不支持 --- 符号

**Comment by yuluo-yx** [comment]
yep, pls see https://github.com/alibaba/spring-cloud-alibaba/issues/3456.

**Comment by chickenlj** [comment]
Could you please provide more information about how `---` is not working? Your expectation and the actual result?

**Comment by yuluo-yx** [comment]
> Could you please provide more information about how `---` is not working? Your expectation and the actual result?https://github.com/alibaba/spring-cloud-alibaba/issues/3456#issue-1900562501

okay, In yaml, a document can be composed of many parts. "---" indicates the division of document content. His requirement may be to split the yaml document through the "---" symbol, but such a scenario is rare. In the spring project In , the configuration file is usually a whole yml document and does not need to be split. 

I think this requirement needs to be discussed in detail with the poster of the question.
In addition, more information can be found in https://github.com/alibaba/spring-cloud-alibaba/issues/3456#issue-1900562501 @chickenlj
