### ISSUE TITLE
何时进行springboot3.0.9支持

### ISSUE THREAD

**Issue by guoderu157** [alibaba/spring-cloud-alibaba#3481]
现在spring官方推荐的springboot版本跟springcloud版本为3.0.9和2022.0.4，这块打算什么时候进行支持？使用2022.0.0.0版本与springboot3.0.9搭配，会出现Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml错误。

**Comment by app2smile** [comment]
我现在用的就是3.0.9 和2022.0.4  alibaba为2022.0.0.0
1. 你可以切换为log4j2
2. 如果用logback,看看这个 https://github.com/alibaba/nacos/issues/10890#issuecomment-1659761681
