### ISSUE TITLE
Spring Cloud Stream 4 对于RocketMQ的文档未更新

### ISSUE THREAD

**Issue by witt-bit** [alibaba/spring-cloud-alibaba#3483]
https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/rocketmq-example/readme-zh.md

4.X版本Spring Cloud Stream已经弃用县官注解,文档尚未更新

**Comment by yuluo-yx** [comment]
关于文档问题，可以在 文档仓库 提 issue。
https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/issues/new/choose
