### ISSUE TITLE
能否发布一下2.2.10 RELEASE 版本呀？现在公司还在用 2.2.x的版本

### ISSUE THREAD

**Issue by LusiferCoder** [alibaba/spring-cloud-alibaba#3487]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by ruansheng8** [comment]
近期部分BUG修复后会发一个正式版本

**Comment by Caratacus** [comment]
@ruansheng8 Can you take a look at this https://github.com/alibaba/spring-cloud-alibaba/issues/3444, Thank you very much!
