### ISSUE TITLE
jdk21包名报错

### ISSUE THREAD

**Issue by pigeon-fancier** [alibaba/spring-cloud-alibaba#3493]
java版本：21
springboot：3.0.2
spring-cloud-starter-alibaba-nacos-discovery： 2022.0.0.0
java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'

**Comment by yuluo-yx** [comment]
目前项目没有适配 jdk21，可以换个jdk17试试

**Comment by karl-chanel** [comment]
Spring boot 版本的问题,升级高版本spring boot,这个错误是因为lombok低版本的问题,不升级spring boot直接把lombok的版本改为1.18.30也可以
