### ISSUE TITLE
Is jvmArguments and paketobuildpacks/builder:tiny needed?

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3499]
This following file:
https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/pom.xml

I found through testing that this configuration can be deleted？Is That So?
What is the impact of deletion？
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/27885492/a5754d47-619b-48fb-9828-4c6f7fbf6801)

**Comment by ruansheng8** [comment]
This `jvmArguments` is only enabled when maven profile=native.
For example `mvn -Pnative clean native:compile`.
If you remove it, you will need to manually configure the `agent` parameters yourself when you need to build a Native Image.

**Comment by imgoby** [comment]
There was an error when integrating with dubbo native. It is OK when I  delete it.
