### ISSUE TITLE
Can you provide an example of spring cloud alibaba 2022+dubbo 3.3+native image?

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3501]
This is my example, which can compile successfully but cannot run。
https://github.com/imgoby/spring-cloud-alibaba-graalvm/tree/main/dubbo-samples-spring-boot-provider
https://github.com/imgoby/spring-cloud-alibaba-graalvm/tree/main/dubbo-samples-spring-boot-consumer

**Comment by yuluo-yx** [comment]
Maybe you say spring cloud 2022 is spring cloud alibaba 2022？

**Comment by imgoby** [comment]
spring cloud alibaba 2022

**Comment by yuluo-yx** [comment]
okay. got it!

**Comment by yuluo-yx** [comment]
It is not recommended to use sca and dubbo together. They both belong to the microservice framework.

**Comment by imgoby** [comment]
Resolved. in my project: https://github.com/imgoby/spring-cloud-alibaba-graalvm
