### ISSUE TITLE
Strongly request the addition of spring-cloud-starter-dubbo on top of spring-cloud-alibaba 2022.0.0

### ISSUE THREAD

**Issue by imgoby** [alibaba/spring-cloud-alibaba#3505]
Our project adopts spring-cloud-alibaba-2.2.6.RELEASE, which provides spring-cloud-starter-dubbo support for Dubbo integration and support for Consul registry. Currently, upgrading to the latest spring-cloud-alibaba 2022.0.0+Dubbo 3.0 and integrating native-image is challenging.

(1) spring-cloud-alibaba 2022.0.0 is difficult to integrate with Dubbo 3.0,because there is not spring-cloud-starter-dubbo plugin.

(2) When Dubbo integrates Consul separately, there may be a limit of exceeding the maximum length when the name of the Service method is too long or there are too many methods.This is a Consul issue，and spring-cloud-alibaba-2.2.6.RELEASE will not have this issue.because of having spring-cloud-starter-dubbo plugin.

Strongly request the addition of spring-cloud-starter-dubbo on top of spring-cloud-alibaba 2022.0.0, which supports the following registration centers:

```
dubbo:
  registry:
    address: spring-cloud://localhost
```

**Comment by chickenlj** [comment]
The previous way of integrating Dubbo with Spring Cloud Alibaba has been deprecated. We are thinking of a better way to do that.

**Comment by imgoby** [comment]
I implement this function on my project which is based on  spring-cloud-alibaba-2.2.6.RELEASE 's spring-cloud-starter-dubbo

https://github.com/imgoby/spring-cloud-alibaba-graalvm/tree/main/spring-cloud-alibaba-starter-dubbo
