### ISSUE TITLE
nacos开启鉴权后，discovery能正常通过鉴权，config无法通过鉴权

### ISSUE THREAD

**Issue by Asunqingwen** [alibaba/spring-cloud-alibaba#3511]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Nacos Config**

**Describe what problem you have encountered**
discovery能通过鉴权，config无法通过鉴权，只有默认的账户名和密码，依赖版本匹配，也是最新的
参考这个issue：https://github.com/alibaba/spring-cloud-alibaba/issues/1305
但是并没有解决问题

**配置和错误截图**
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/16719561/edd206ec-2360-4f90-9795-72ea2f46f1ca)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/16719561/2f2df2db-6731-4a98-a182-12ab9db172f8)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/16719561/f4cd4042-16de-4d78-b0ac-49b1b16222dc)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/16719561/2f8d652d-191d-4bc6-9c86-3656f433cd9e)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/16719561/c8794364-bb9d-4e57-a179-da6dd139bedd)

**Comment by yuluo-yx** [comment]
可以补充一下使用的版本或者提供一个 demo 示例吗？
