### ISSUE TITLE
Spring Boot 3.2. x version Sentinel will cause it to fail to start

### ISSUE THREAD

**Issue by twelvet-s** [alibaba/spring-cloud-alibaba#3514]
**Which Component**
Sentinel

**Describe the bug**
Due to the upgrade of Spring Boot's dependency on Feign to 13.1, Sentinel's method was rewritten as final
![1701607032810](https://github.com/alibaba/spring-cloud-alibaba/assets/31510505/979eceac-b92d-402a-b6e3-30ca12c7b098)

**Simplest demo**
This situation occurs when using Spring boot3.2. x, Spring Cloud 2023, and Spring Cloud Alibaba 2022.0.0.0

**Comment by twelvet-s** [comment]
At present, the solution is available on com. alibaba. cloud. sentinel. feign. sentinelFeignAutoConfiguration
Rewrite and overwrite it before injection, but still hope that the official can support Spring Cloud 2023 faster

**Comment by ruansheng8** [comment]
> At present, the solution is available on com. alibaba. cloud. sentinel. feign. sentinelFeignAutoConfiguration Rewrite and overwrite it before injection, but still hope that the official can support Spring Cloud 2023 faster

`Spring Cloud 2023` has not yet been released. We will make corresponding adaptations after the official version is released.

**Comment by twelvet-s** [comment]
ok

**Comment by zt9788** [comment]
+1 the springcloud 2023.0.0 has released

**Comment by twelvet-s** [comment]
> +1 the springcloud 2023.0.0 has released

Adaptation has been made here, which can be referred to for use: [twelvet](https://github.com/twelvet-projects/twelvet/blob/master/twelvet-framework/twelvet-framework-openfeign/src/main/java/com/twelvet/framework/openfeign/sentinel/ext/TwSentinelFeign.java#L57)

**Comment by Apelx** [comment]
when will the official fit it
