### ISSUE TITLE
logback重复初始化

### ISSUE THREAD

**Issue by haoyi68** [alibaba/spring-cloud-alibaba#3518]
**Which Component**
spring-cloud-starter-alibaba-nacos-discovery

**Describe what problem you have encountered**
spring-cloud-starter-alibaba-nacos-discovery 引用了nacos-client.

针对logback初始化都调用了 NacosLogging.getInstance().loadConfiguration();

出现在了两处
1、com.alibaba.nacos.client.utils.LogUtils   23行
2、com.alibaba.cloud.nacos.logging.NacosLoggingAppRunListener  21行

直接导致了项目在启动中有一下异常
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[CONFIG_LOG_FILE] - 'File' option has the same value "C:\Users\XXX\logs/nacos/config.log" as that given for appender [CONFIG_LOG_FILE] defined earlier.
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[CONFIG_LOG_FILE] - Collisions detected with FileAppender/RollingAppender instances defined earlier. Aborting.
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[CONFIG_LOG_FILE] - For more information, please visit http://logback.qos.ch/codes.html#earlier_fa_collision
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[NAMING_LOG_FILE] - 'File' option has the same value "C:\Users\XXX\logs/nacos/naming.log" as that given for appender [NAMING_LOG_FILE] defined earlier.
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[NAMING_LOG_FILE] - Collisions detected with FileAppender/RollingAppender instances defined earlier. Aborting.
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[NAMING_LOG_FILE] - For more information, please visit http://logback.qos.ch/codes.html#earlier_fa_collision
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[REMOTE_LOG_FILE] - 'File' option has the same value "C:\Users\XXX\logs/nacos/remote.log" as that given for appender [REMOTE_LOG_FILE] defined earlier.
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[REMOTE_LOG_FILE] - Collisions detected with FileAppender/RollingAppender instances defined earlier. Aborting.
|-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[REMOTE_LOG_FILE] - For more information, please visit http://logback.qos.ch/codes.html#earlier_fa_collision

版本：
Spring Cloud Alibaba Version 2021.0.5.0

**Comment by yuluo-yx** [comment]
@haoyi68 请提供一个复现问题的 demo，方便复现和解决问题
