### ISSUE TITLE
Can the 2022.0.0 version support SpringBoot3.2.0? If not, what are the solutions?

### ISSUE THREAD

**Issue by xiaoxiaostar** [alibaba/spring-cloud-alibaba#3522]
Can the 2022.0.0 version support SpringBoot3.2.0? If not, what are the solutions?

**Comment by yuluo-yx** [comment]
There is currently no adaptation in the community. You can adapt and explore by yourself, or participate in community adaptation.

**Comment by shuangpai** [comment]
Of course, it can support 3.2

**Comment by chickenlj** [comment]
Follow this issue https://github.com/alibaba/spring-cloud-alibaba/issues/3574
