### ISSUE TITLE
Docs: Update nacos-example readme file.

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3525]
## Backgorund

In the nacos 2.2.x version, the authentication function was added, causing most users to have errors such as `user not found` or `login failed` when upgrading to the nacos 2.2.x version. I think it is necessary to update the readme document to add This part of the content.
Now nacos-example has three examples, and each example module has a readme file. I think they need to be uniformly placed in the nacos-example directory to reduce the cost of maintaining documents.

## Reference

https://nacos.io/zh-cn/blog/announcement-token-secret-key.html
https://nacos.io/zh-cn/docs/auth.html

**Comment by yuluo-yx** [comment]
If updates are needed, please assign them to me. @ruansheng8

**Comment by chickenlj** [comment]
Please, also update the documentation on our official website

**Comment by yuluo-yx** [comment]
> Please, also update the documentation on our official website

got it.

**Comment by yuluo-yx** [comment]
mark!
