### ISSUE TITLE
Why is it invalid to modify the port in nacos?为什么修改nacos端口无效

### ISSUE THREAD

**Issue by xuechen-zed** [alibaba/spring-cloud-alibaba#3538]
**Nacos Discovery**

**Describe what problem you have encountered**
我的两个spring cloud服务在启动时使用nacos读取配置，我在application.properties文件中修改了server.port=36000，两个服务的bootstrap.yml都是写的本地nacos服务地址。在本地启动nacos后，其中一个服务可以运行，但是另一个会报错**request：/nacos/v1/ns/instance/beat failed,servers:localhost:8848,code:500,msg:Connection refused:connect**，我明明修改了port为何还会向8848端口发送心跳
My two spring cloud services use nacos to read the configuration when starting. I modified server.port=36000 in the application.properties file. The bootstrap.yml of both services is written with the local nacos service address. After starting nacos locally, one of the services can run, but the other one will report an error **request:/nacos/v1/ns/instance/beat failed, servers: localhost:8848, code: 500, msg: Connection refused: connect* *, I have obviously modified the port, why do I still send heartbeats to port 8848?

**Comment by xuechen-zed** [comment]
nacos 1.1.4

**Comment by yuluo-yx** [comment]
可以提供一个 demo 方便复现问题，这样描述并不能很好在本地复现出来

**Comment by chickenlj** [comment]
Please provide the full configuration file and reopen this issue.
