### ISSUE TITLE
How to configure multiple services for a module【一个模块怎么配置多个服务】

### ISSUE THREAD

**Issue by XSWClevo** [alibaba/spring-cloud-alibaba#3539]
我有一个模块，我希望在这个模块里面配置多个服务名与端口（一个服务一个端口），nacos中有这样子的配置方式吗。
我的模块里面有多个socket服务，我希望将他们都注册到nacos之中，然后在gateway里面拿到服务名或者组名直接进行路由转发。

-------------------------

I have a module where I want to configure multiple service names and ports. Is there such a configuration method in Nacos.
There are multiple socket services in my module, and I hope to register them all in Nacos, and then directly route and forward them by obtaining the service or group name in the gateway.

**Comment by yuluo-yx** [comment]
并没有很清楚的理解到你的意思，如果是多个 spring boot 应用，在里面写不同的配置文件就可以解决，如果是一个应用，可以在应用启动时设置 jvm 配置来实现。

**Comment by XiaZhouxx** [comment]
很明显不行，参考NacosServiceRegistry自己实现呗

**Comment by XSWClevo** [comment]
已解决，官方有提供注册到nacos的java sdk包
