### ISSUE TITLE
The pictures on the official website are not displayed.

### ISSUE THREAD

**Issue by youngledo** [alibaba/spring-cloud-alibaba#3540]
<img width="1039" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/3d96db36-d0b5-4090-8404-d77f92aa4d15">

**Screenshots**
<img width="894" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/3547d042-5300-4c2f-957b-6f79d4ff8457">

**Comment by yuluo-yx** [comment]
Thanks for the feedback, the official website images will be uniformly migrated to oss storage in the near future.

**Comment by youngledo** [comment]
The problem still persists, when can it be fixed?

**Comment by yuluo-yx** [comment]
> The problem still persists, when can it be fixed?

It will be updated later, and the new official website is being redone.
