### ISSUE TITLE
不要懒惰

### ISSUE THREAD

**Issue by rola0411** [alibaba/spring-cloud-alibaba#3551]
确认一下你们是否准备停止维护了，我们好做打算废弃掉你们得依赖。你们得更新如此缓慢，最少springboot升级，你们不受影响的话也要跟随springboot得版本进行版本号迭代，让我们使用的人心里有点着落好嘛？最少你们ali系得seata啊，nacos啊升级了，你们得升升级OK？

**Comment by rola0411** [comment]
还有rocketmq。

**Comment by chickenlj** [comment]
Thanks for the suggestion.

2022.0.0.0 is our latest version that can work with spring boot 3.0.x and jdk 17.

We have made a Roadmap here and are working on integration with those components, but it will still take some time. Please follow the latest process with this issue, https://github.com/alibaba/spring-cloud-alibaba/issues/3502

**Comment by liuxuzxx** [comment]
> Thanks for the suggestion.
> 
> 2022.0.0.0 is our latest version that can work with spring boot 3.0.x and jdk 17.
> 
> We have made a Roadmap here and are working on integration with those components, but it will still take some time. Please follow the latest process with this issue, #3502

咨询个问题，就是rocketmq-stream如何对所有的Topic只创建一个MQClientInstance对象，现在遇到一个问题，就是我们有个服务需要投递给：600个Topic，这个导致生成了600个MQClientInstance，然后是:6000个线程，导致内存占用很大，线程也多，看到是rocketmq-stream里面设置InstanceName的时候，使用了topic信息，所以这块有其他钩子一类的来辅助处理下吗？

**Comment by chickenlj** [comment]
关于这个具体问题，我先尝试看一下当前的适配流程 @liuxuzxx 。

如果有对mq这块比较熟悉的开发者也可以协助解答，另外，建议在 rocketmq github 社区也咨询一下这个问题。

**Comment by liuxuzxx** [comment]
> 关于这个具体问题，我先尝试看一下当前的适配流程 @liuxuzxx 。
> 
> 如果有对mq这块比较熟悉的开发者也可以协助解答，另外，建议在 rocketmq github 社区也咨询一下这个问题。

#3533 就是这个问题

**Comment by liuxuzxx** [comment]
不过从spring-cloud-stream的设计角度来看，它其实觉得，消息生产者服务，能投递给10来个Topic就算不少了，所以，整个代码的设计和逻辑都是以：集群+Topic作为维度来做的，包括缓存了，创建的对象了等等。和Topic的关联度和耦合度很大，很多都是根据Topic来确定对应的缓存和数据

**Comment by markr512** [comment]
支持楼组,2021很久都没升级相关依赖了

**Comment by laizuan** [comment]
虽然我们属于白嫖党，没有理由去催更开源作者。作为国内顶尖的科技企业这样对待优秀的开源项目挺难受的，不单是阿里太多国内的开源项目都是带利益开源，当收益覆盖不了支出的时候项目就会变的没人维护。我很支持开源项目能推出商业版本之类的产品，这样反而能更好的促进项目的发展。

免费的可能会是最贵的。我们真在寻求去SCA方案，比如直接使用Springboot + k8s。如果大家有更好的方案可以借楼讨论

**Comment by weir2010** [comment]
马上2024年了 国内大厂的难处是有目共睹的。而且java体系架构也在有新的有生力量产生 比如红帽的quarkus，oracle的Helidon，如果你们公司真的要上分布式微服务的架构，那需要重新审视当前的技术变革，成熟的保守，新的架构有挑战，这个就看领导的眼光和公司本身的技术储备，我关注quarkus有两年多了，目前国内还真有使用的，这是好事。

**Comment by steverao** [comment]
项目一直在进行维护，近期社区也在进行相关组件的升级适配，可以从提交历史中看到，也欢迎大家一起参与到社区贡献中来。
