### ISSUE TITLE
Is there a problem with the getInstanceResponse method of the NacosLoadBalancer class?

### ISSUE THREAD

**Issue by laizixiang0720** [alibaba/spring-cloud-alibaba#3570]
**Which Component**
spring-cloud-starter-alibaba-nacos-discovery:2022.0.0.0
**Describe what problem you have encountered**
When I use nacos to make cross-cluster calls, I find that there is no warning like in previous versions. I feel that there is a problem with the following code.
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/41117477/cc3f04e0-fbb0-4ce7-838a-c66335b94312)

**Comment by chickenlj** [comment]
Yes, I think it would be better to move the log to the point you suggested.  Would you like to submit a pull request?

**Comment by Suzzt** [comment]
Hi, this task looks very simple. Can I do it? I happen to want to complete a PR process for the first time

**Comment by yuluo-yx** [comment]
> Hi, this task looks very simple. Can I do it? I happen to want to complete a PR process for the first time

You can submit PR directly to complete it. 👍

**Comment by Suzzt** [comment]
@chickenlj @laizixiang0720 @yuluo-yx 
I have reviewed my code myself I was wondering if we made a mistake? We shouldn't just put it at the end here. There should be a judgment here that there is no 'sameClusterinstances', and only with a warning prompt can it be reasonable

BWT, is there any ambiguity in the prompt text here? Would it be better to change it to "No specified cluster service node found"? Or do you have any better ideas?

<img width="844" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/27397567/cfb4b44b-2d3d-43a7-82b2-2d561f4ede84">

**Comment by yuluo-yx** [comment]
Good job, you can submit your idea to PR along with your code implementation and we'll review your changes there. 
@Suzzt  cc @chickenlj

**Comment by Suzzt** [comment]
👌,Let's go to CR together to discuss.
