### ISSUE TITLE
Best practices for deploying Spring Cloud Alibaba on Kubernetes

### ISSUE THREAD

**Issue by chickenlj** [alibaba/spring-cloud-alibaba#3573]
Provide articles on [sca.aliyun.com](https://sca.aliyun.com/) giving best practices for deploying Spring Cloud Alibaba on Kubernetes.

One typical case that could benefit from the practice: https://github.com/alibaba/spring-cloud-alibaba/issues/3535

**Comment by yuluo-yx** [comment]
pls assign to me. I will write it. @chickenlj
