### ISSUE TITLE
Supporting Spring Cloud 2023.x and Spring Boot 3.2.x

### ISSUE THREAD

**Issue by chickenlj** [alibaba/spring-cloud-alibaba#3574]
Spring Cloud has officially announced its first 2023 stable release - `2023.0.0` at the beginning of the last month of 2023. Together with this version, it also had the underlying Spring Boot upgraded to 3.2.x while still requires JDK 17 as the lowest JDK version.

So based on the regular plan and also the voices we hear recently from the community, I think it's time to add the Spring Cloud Alibaba 2023.0.0.0 release to the schecule. Along with Spring Cloud and Spring Boot upgrading, we will also have the core SCA components upgraded to their latest major versions respectively:
* Nacos, 2.3.0
* Sentinel, 1.8.7
* Seata, 2.0.0
* RocketMQ, 5.1.4

References:
1. [Spring Cloud Release Train](https://spring.io/projects/spring-cloud/)
2. [Spring Cloud 2023.0 Release Notes](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes)
3. [Spring Boot 3.2 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes)

**Comment by axeon** [comment]
要加快了，spring 3.2是最重要的一次更新，支持了jdk21的虚拟线程。
我估计很多公司都会趁着这次机会全面迁移到jdk21。

**Comment by me0106** [comment]
Is an optional module provided to support RocketMQ 4.0 and RocketMQ 5.0?

**Comment by yuluo-yx** [comment]
pls assign to me, I will completed. @chickenlj

**Comment by ruansheng8** [comment]
Sentinel 1.8.7 does not currently support Spring 6.x ( Sentinel 1.8.6 Adopting a temporary solution ).
I will follow up on this.

**Comment by chickenlj** [comment]
> Sentinel 1.8.7 does not currently support Spring 6.x ( Sentinel 1.8.6 Adopting a temporary solution ). I will follow up on this.

Sure, we can stick to the version that is proved to work well with Spring 6.x, not necessarily need to be the latest version.

**Comment by muzhi9018** [comment]
When do you plan to release versions that are compatible with Spring Cloud 2023. x and Spring Boot 3.2. x? I can't wait anymore

**Comment by yuluo-yx** [comment]
RocketMQ reference documentation #3606

**Comment by xueyitt** [comment]
2023.0.0得RC 请问有定期吗

**Comment by jaimyjie** [comment]
建议等Nacos 2.3.1， Seata 2.1.0修复bug版本再一起发布吧

**Comment by ruansheng8** [comment]
> 2023.0.0得RC 请问有定期吗

@1455668754  `2023.0.0.0-RC1` 发布了，可以试一下
