### ISSUE TITLE
java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.netty.NettyChannelProvider

### ISSUE THREAD

**Issue by Fengxici** [alibaba/spring-cloud-alibaba#3582]
![1704608031782](https://github.com/alibaba/spring-cloud-alibaba/assets/7898827/762e5268-70c1-4056-8cf0-16916aed33ac)

**Comment by yuluo-yx** [comment]
Please provide a demo to facilitate reproduction and problem solving. @Fengxici
