### ISSUE TITLE
NacosLoadBalancer.getServiceCache()报空指针，导致通过feign远程调用接口Unknown Source

### ISSUE THREAD

**Issue by HeZhanfeng** [alibaba/spring-cloud-alibaba#3588]
spring-cloud-starter-alibaba-nacos-discovery-2021.0.1.0
spring-cloud-starter-alibaba-nacos-config-2021.0.1.0
spring-cloud-starter-loadbalancer-3.1.1
spring-boot-starter-parent-2.6.3
spring-cloud-starter-openfeign-3.1.1
错误如下，这个错误不是一直有，基本上会半个月到一个月出现一次，所以不好复现，程序内部多线程通过feign远程调用一个接口，麻烦帮看看：
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/f5021b75-b171-4f2d-8c23-61c5a6093e83)

**Comment by HeZhanfeng** [comment]
补充几张可能有用的图（生产环境不让导出，照片都是冒着杀头拍的）
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/e9830754-706f-4a79-bd57-61657bf6eece)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/2615da31-0a74-4c84-aa67-99cce2907d4f)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/02e66f53-39a3-4a56-8533-a667d02e46c4)

**Comment by ruansheng8** [comment]
@HeZhanfeng 建议对堆栈中的相关公司包名进行涂抹以保护隐私性

**Comment by galaxy-sea** [comment]
hello @HeZhanfeng @ruansheng8 
NacosLoadBalancer.getServiceCache() 我没有在源码中找到这个方法。

**Comment by ruansheng8** [comment]
> hello @HeZhanfeng @ruansheng8 NacosLoadBalancer.getServiceCache() 我没有在源码中找到这个方法。

@HeZhanfeng 是否有使用 MSE 相关 Agent

**Comment by HeZhanfeng** [comment]
> > 你好@HeZhanfeng @ruansheng8NacosLoadBalancer.getServiceCache() 我没有在源码中找到这个方法。
> 
> @HeZhanfeng是否有使用MSE相关代理

可能存在，能具体说一下这个为何引发问题吗，我去问问云平台的人

**Comment by HeZhanfeng** [comment]
> @HeZhanfeng建议对Stack中的相关公司包名进行修改以保护隐私性

感谢提醒

**Comment by HeZhanfeng** [comment]
> 你好@HeZhanfeng @ruansheng8 NacosLoadBalancer.getServiceCache() 我没有在源码中找到这个方法。

确实没，找到只有getInstanceResponse方法，我问了一下底层自己有基于sca封装了一层，然后给我们使用的

**Comment by galaxy-sea** [comment]
> > 你好@HeZhanfeng @ruansheng8 NacosLoadBalancer.getServiceCache() 我没有在源码中找到这个方法。
> 
> 确实没，找到只有getInstanceResponse方法，我问了一下底层自己有基于sca封装了一层，然后给我们使用的

com.alibaba.cloud.nacos.discovery.ServiceCache 已经实现了缓存，可以考虑切换到sca默认实现

**Comment by HeZhanfeng** [comment]
> > > 你好@HeZhanfeng @ruansheng8 NacosLoadBalancer.getServiceCache() 我没有在源码中找到这个方法。
> > 
> > 
> > 确实没，找到只有getInstanceResponse方法，我问了一下底层自己有基于sca封装了一层，然后给我们使用的
> 
> com.alibaba.cloud.nacos.discovery.ServiceCache 已经实现了缓存，可以考虑切换到sca默认实现

受人限制，只能用甲方要求的技术栈
