### ISSUE TITLE
RocketmqTemplate conain rocket-client v4.9.4

### ISSUE THREAD

**Issue by lucky-lbc** [alibaba/spring-cloud-alibaba#3589]
**Which Component**
rocketmq

**Is your feature request related to a problem? Please describe.**
hello, i want ask something about rocketmq version. 
in project i use spring-cloud-alibaba version: 2023.0.0
rocketmqTemplate pom :

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.2.3</version>
        </dependency>

the rocketmqTemplate message version is  4.9.4 : 
<img width="854" alt="1704936742543_2F0B9252-E63D-4bc4-ADBE-B1B99B54DAB2" src="https://github.com/alibaba/spring-cloud-alibaba/assets/17894730/77c26f71-7f0b-4a3f-aa96-e0f18816ccb6">

so cant`t use the rocketmq 5.x method

in other project no spring cloud alibaba the message version was 5.0

my english was pool . can u understand me ? if not i will repeat that

**Describe the solution you'd like**
is spring cloud alibaba limit rocketmq version? 
if true , can us upgrade rocketmq version?

**Describe alternatives you've considered**

**Additional context**

**Comment by yuluo-yx** [comment]
yep, I understand your means. 

The project is currently not adapted to rocketmq 5.x version.
Related issues: 
- https://github.com/alibaba/spring-cloud-alibaba/issues/3502
- https://github.com/alibaba/spring-cloud-alibaba/issues/3574
