### ISSUE TITLE
Spring Boot 2.7.x版本支持

### ISSUE THREAD

**Issue by bbdd33442** [alibaba/spring-cloud-alibaba#3593]
Currently, version 2. x supports up to 2.6.13. Will version 2.7. x be supported in the future? Do you have a specific time?
目前2.x版本最高支持到2.6.13，请问下2.7.x版本后续会支持吗？有具体的时间吗？

**Comment by yuluo-yx** [comment]
指的是那个分支？现在社区有三个版本在并行维护状态。
有关 issue 可以参考 #3584

**Comment by bbdd198989** [comment]
Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？

**Comment by bbdd33442** [comment]
> 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584

Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？

**Comment by yuluo-yx** [comment]
> > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> 
> Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？

暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。

**Comment by bbdd33442** [comment]
> > > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> > 
> > 
> > Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？
> 
> 暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。

好的，看到#3348#3199也存在一些使用2.7.x出现的问题，那还是等官方毕业版本吧，谢谢

**Comment by yuluo-yx** [comment]
> > > > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> > > 
> > > 
> > > Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？
> > 
> > 
> > 暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。
> 
> 好的，看到#3348#3199也存在一些使用2.7.x出现的问题，那还是等官方毕业版本吧，谢谢

上面提到的两个问题应该都不是 sca 的版本问题。网上查查就解决了

**Comment by imyuyu** [comment]
虽然写的只支持`2.6.13`，但实际上`2.7.15`也能用。

**Comment by bbdd33442** [comment]
> > > > > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> > > > 
> > > > 
> > > > Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？
> > > 
> > > 
> > > 暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。
> > 
> > 
> > 好的，看到#3348#3199也存在一些使用2.7.x出现的问题，那还是等官方毕业版本吧，谢谢
> 
> 上面提到的两个问题应该都不是 sca 的版本问题。网上查查就解决了

好的，谢谢，我一直以为是

> > > > > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> > > > 
> > > > 
> > > > Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？
> > > 
> > > 
> > > 暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。
> > 
> > 
> > 好的，看到#3348#3199也存在一些使用2.7.x出现的问题，那还是等官方毕业版本吧，谢谢
> 
> 上面提到的两个问题应该都不是 sca 的版本问题。网上查查就解决了

好的，我之前看疑问有说降低spring boot版本的，我就以为是不支持，谢谢

**Comment by yuluo-yx** [comment]
> > > > > > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> > > > > 
> > > > > 
> > > > > Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？
> > > > 
> > > > 
> > > > 暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。
> > > 
> > > 
> > > 好的，看到#3348#3199也存在一些使用2.7.x出现的问题，那还是等官方毕业版本吧，谢谢
> > 
> > 
> > 上面提到的两个问题应该都不是 sca 的版本问题。网上查查就解决了
> 
> 好的，谢谢，我一直以为是
> 
> > > > > > 指的是那个分支？现在社区有三个版本在并行维护状态。 有关 issue 可以参考 #3584
> > > > > 
> > > > > 
> > > > > Spring Cloud Alibaba 2021.0.x分支，目前最高对应的spring boot版本是2.6.13，是否会考虑有2.7.x的spring boot版本支持？
> > > > 
> > > > 
> > > > 暂时没有。不过在一些情况下，可以试着使用 spring boot 2.7.x 看看。社区最近会有新的 roadmap 出来。
> > > 
> > > 
> > > 好的，看到#3348#3199也存在一些使用2.7.x出现的问题，那还是等官方毕业版本吧，谢谢
> > 
> > 
> > 上面提到的两个问题应该都不是 sca 的版本问题。网上查查就解决了
> 
> 好的，我之前看疑问有说降低spring boot版本的，我就以为是不支持，谢谢

组件可用的版本范围最近会更新一下，同步到官网里面去的。

**Comment by yuluo-yx** [comment]
mark!
