### ISSUE TITLE
There are many warnings for using springboot3.2

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/spring-cloud-alibaba#3596]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

https://github.com/alibaba/nacos/issues/11616
https://github.com/apache/incubator-seata/issues/6249

There are warnings after the nacos sentinel seata update to springboot 3.2

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**Simplest demo**
The URL of the simplest demo to reproduce the problem.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by yuluo-yx** [comment]
社区还没适配 spring boot 3.2 最近正在做 

具体可以看 https://github.com/alibaba/spring-cloud-alibaba/issues/3574

**Comment by ruansheng8** [comment]
`lbRestClientPostProcessor` 是 Spring Cloud 官方项目中存在的问题，不过不影响使用，Spring Cloud 计划在下一个版本中修复该问题，SCA 会在Spring Cloud 下个版本发布后集成最新版本。
https://github.com/spring-cloud/spring-cloud-commons/issues/1315
