### ISSUE TITLE
Changes of 2.2.x branch since 2.2.10-RC1 release

### ISSUE THREAD

**Issue by chickenlj** [alibaba/spring-cloud-alibaba#3603]
## Features/Enhancements

- Add additional-spring-configuration-metadata.json for governance module (#3246)
- Add helm support for governance module (#3256[)](https://github.com/alibaba/spring-cloud-alibaba/commit/09d1f389e6317e3683b323a338d8686df658332d)
- Add configuration-processor to xDS adapter (#3241)

## Bugfixes

- [Nacos], Fix #3322, get outdated value on cofig refresh with nacos-client 2.1.x (#3600)
- [Nacos] Fix** **#3314, set default nacos server address when** **spring.config.import** **enabled (#3601)
- [Nacos] Nacos integration with SpringBootAdmin (#3308)
- [Nacos] Added IPv6 address replace condition (#3232)
- [Nacos] Fix #3133, nacos discovery/config log (#3160)
- [Nacos] Fix #3133, nacos discovery/config log (#3160)
- [Nacos] Remove useless suffix of IPv6 address.
- Optimize the Appactive module (#3107)
- [Sentinel] Fix #3329, SentinelRestTemplate support custom RestTemplate (#3345)
- [Sentinel] Fix #3135, fallback support factoryBean (#3163)
- [Sentinel] Remove sentinel @validated annotation (#3121)
- [RocketMQ] Fix #3235, pollable consumer doesn't ack the message correctly (#3247)
- [RocketMQ] fix RocketMQ SecretKey leakage risk (#3092)
- [xDS] fix the bug that the eds protocol is never observed (#3109)

**Comment by ruansheng8** [comment]
Related to https://github.com/alibaba/spring-cloud-alibaba/pull/3609
