### ISSUE TITLE
Start Nacos with source code, error reported read application.properties failed

### ISSUE THREAD

**Issue by MaWenDa** [alibaba/spring-cloud-alibaba#3607]
nacos2.1.0

Start Nacos with source code, console error reported read application.properties failed,

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/39353958/112e6ffe-c30d-4a52-9542-27fcd70a9e57)

**Comment by yuluo-yx** [comment]
@MaWenDa, pls ask the nacos community. From the stack information, you are not using `spring-cloud-alibaba` related functional components.
