### ISSUE TITLE
[Feature] RocketMQ client SDK adapt

### ISSUE THREAD

**Issue by ruansheng8** [alibaba/spring-cloud-alibaba#3614]
**相关组件**
RocketMQ

## 背景说明
Apache RocketMQ 5.0 版本发布后，客户端 SDK 提供了 `gRPC` 协议的支持，以前版本均采用 `Remoting` 协议。
- **Remoting 协议**
RocketMQ 早期组件间默认的通信协议, 是 RocketMQ 官方仓库中自带的实现
- **gRPC 协议**
5.0 版本以后开始支持, 旨在以云原生主流技术演进更加轻量、标准、易扩展的客户端服务端通信协议.

## 组件适配
SCA 将对两个不同版本的客户端 SDK 进行适配，由用户根据使用的 RocketMQ 服务端版本来自行选择客户端 SDK。

## 选型问题建议 

以下章节列出一些场景场景下，推荐的选型策略。[官网说明](https://rocketmq.apache.org/zh/docs/sdk/01overview/#%E9%80%89%E5%9E%8B%E9%97%AE%E9%A2%98%E5%BB%BA%E8%AE%AE)

- **服务端版本是4.x版本，是否可以使用gRPC SDK ？**

不支持，gRPC SDK 仅支持版本大于等于5.0的服务端，建议先平滑升级服务端到5.0再更换SDK。

- **从 Remoting SDK 更换到 gRPC SDK 是否需要修改代码？**

需要，gRPC SDK 重新优化设计了客户端API，和Remoting SDK API 并不兼容，因此需要对照修改代码。

- **新业务使用 RocketMQ 推荐使用什么SDK？**

全新的业务系统接入 RocketMQ，推荐使用gRPC SDK，可以获得更好的使用体验和多语言环境支持。

<hr>

## Background
After the release of Apache RocketMQ 5.0, the client SDK provides support for the gRPC protocol, while previous versions used the Remoting protocol.

- Remoting Protocol
The default communication protocol between components in early versions of RocketMQ, implemented in the official RocketMQ repository.
- gRPC Protocol
Supported since version 5.0, aiming to provide a lightweight, standard, and easily scalable client-server communication protocol using cloud-native mainstream technologies.

## Component Adapt
SCA will adapt two different versions of the client SDK, and users can choose the client SDK based on the version of RocketMQ server they are using.

## FAQ
The following sections list some recommended selection strategies for certain scenarios.[Official Site](https://rocketmq.apache.org/docs/sdk/01overview/#faq)
- **Can gRPC SDK be used with a server version of 4.x?**
No, gRPC SDK is only supported by server versions equal to or greater than 5.0. It is recommended to first smoothly upgrade the server to version 5.0 and then replace the SDK.

- **Is it necessary to modify the code when switching from Remoting SDK to gRPC SDK?**
Yes, it is necessary. The client API of gRPC SDK has been redesigned and is not compatible with the Remoting SDK API. Therefore, it is necessary to modify the code accordingly.

- **What's the best choice of sdk when use rocketmq in new system?**
If a new business system is integrating with RocketMQ, it is recommended to use gRPC SDK, as it provides a better user experience and support for multiple language environments.

**Comment by yuyu1025** [comment]
Has anyone completed this quest yet? If not, I would like to try to complete this quest, is that ok?

**Comment by ruansheng8** [comment]
> Has anyone completed this quest yet? If not, I would like to try to complete this quest, is that ok?

@yuyu1025 Welcome to contribute
