### ISSUE TITLE
NacosWatch$sLambda.run is using opentelemetry with a lot of duplicate requests.

### ISSUE THREAD

**Issue by yunzck8s** [alibaba/spring-cloud-alibaba#3620]
I'm using opentelemtry for link monitoring of services and I'm getting a lot of Get nacos requests

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/86189975/0cb3ab98-51b3-4423-bd7d-20914ac5c9ce)

opentelemetry version: v0.89.0
nacos: 2.2.3

**Comment by ruansheng8** [comment]
What's the version of `spring-cloud-starter-alibaba-nacos-discovery`?

**Comment by yunzck8s** [comment]
@ruansheng8 We are now using a version of spring-cloud-starter-alibaba-nacos-discovery, which is 2.2.9.

**Comment by ruansheng8** [comment]
@yunzck8s We have optimized `NacosWatch` in the latest version. Please upgrade `spring-cloud-starter-alibaba-nacos-discovery` to version `2.2.10-RC2` to verify whether the problem still exists.

**Comment by yuluo-yx** [comment]
No feedback from users, now closed.
