### ISSUE TITLE
profiles and file-extension are used in NacosConfigDataLoader 

### ISSUE THREAD

**Issue by spairy** [alibaba/spring-cloud-alibaba#3627]
`spring.profiles.active` and `spring.cloud.nacos.config.file-extension` are not used when pullConfig from nacos server.
but they are used on old version with bootstrap method.

**Comment by ruansheng8** [comment]
`bootstrap` is deprecated by default in spring boot 2.4 and above.

- For the latest configuration method, please refer to
https://sca.aliyun.com/zh-cn/docs/2022.0.0.0/user-guide/nacos/advanced-guide/#springcconfigimport-%E5%BC%95%E5%85%A5

- Or You can solve it in the following way (**not recommended**):
1. Append bootstrap dependency
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```
2. Set `spring.cloud.bootstrap.enabled=true`

**Comment by spairy** [comment]
Thank your answers. But I meas that we can config 
`spring:
  profiles:
    active: prod
  config:
    import:
      - nacos:example` 
for `example，example.yml，example-prod.yml` like bootstrap in the old version.

Any way, Anyway, this is just a discussion as I submit it as a feature.

**Comment by ruansheng8** [comment]
> Thank your answers. But I meas that we can config `spring: profiles: active: prod config: import: - nacos:example` for `example，example.yml，example-prod.yml` like bootstrap in the old version.
> 
> Any way, Anyway, this is just a discussion as I submit it as a feature.

This feature looks great

**Comment by yuluo-yx** [comment]
No feedback from users, now closed.
