### ISSUE TITLE
Comma-separated list of server-addr is not support in NacosConfigDataLocationResolver

### ISSUE THREAD

**Issue by spairy** [alibaba/spring-cloud-alibaba#3628]
`String uri = properties.getServerAddr() + path;` 
The code is not take into comma-separated list of server-addr.

**Comment by ruansheng8** [comment]
If you are using Nacos cluster mode, you only need to configure a single address

**Comment by spairy** [comment]
Thank you for answers. I test it with nacos cluster`ip1,ip2,ip3`:
`server-addr: http://ip1:8848` when stop nacos in ip1, nacos is invalid.
`server-addr: http://ip1:8848,ip2:8848` when stop nacos in ip1, nacos is valid.
`server-addr: http://ip1:8848,http://ip2:8848` get illegal error when stratup.

**Comment by ruansheng8** [comment]
I misunderstood what you meant at first. Usually when we use nacos cluster, we will configure a load balancing in front.

**Comment by spairy** [comment]
Load balancing may not always be used.
Comma-separated list of server-addr is supported in nacos-client. I think NacosConfigDataLocationResolver should keep pace with nacos-client. 
`String uri = properties.getServerAddr() + path;` is not used to connect to server, just for `getPath()` and `getQuery()` and illegal error will be throwed with multi `server-addr: http://ip1:8848,http://ip2:8848`.

I think we can take a discussion as a feature for it.

**Comment by ruansheng8** [comment]
In fact, SCA should not process the Nacos cluster address because this is the specification of `nacos-client`. SCA only needs to pass the original address according to the `nacos-client` configuration specification.

See `com.alibaba.nacos.client.config.impl.ServerListManager` 

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/97888dca-ac51-45df-9e1f-9fc7d8030de9)

**Comment by ruansheng8** [comment]
> Thank you for answers. I test it with nacos cluster`ip1,ip2,ip3`: `server-addr: http://ip1:8848` when stop nacos in ip1, nacos is invalid. `server-addr: http://ip1:8848,ip2:8848` when stop nacos in ip1, nacos is valid. `server-addr: http://ip1:8848,http://ip2:8848` get illegal error when stratup.

And you should use 3 nacos nodes to test cluster availability, nacos client will automatically retry 
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/b2d7eebe-3d9e-411e-b649-20f738cef35d)
