### ISSUE TITLE
which version of spring-cloud-cloud adapt to spring boot 2.1.8.RELEASE?

### ISSUE THREAD

**Issue by CHENXCHEN** [alibaba/spring-cloud-alibaba#3639]
**Which Component**
Sentinel

**Describe what problem you have encountered**
My spring boot version is 2.1.8.RELEASE, but spring-cloud-starter-alibaba-sentinel does not seem to have this version number. Which version should I use to adapt Spring Boot 2.1.8.RELEASE ? 

**Describe what information you have read**
https://github.com/alibaba/spring-cloud-alibaba/wiki/Sentinel
https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-sentinel

**Comment by yuluo-yx** [comment]
spring-cloud-starter-alibaba-sentinel is a starter for spring-cloud-alibaba

sb power can be viewed on the official website:：https://sca.aliyun.com/zh-cn/docs/2022.0.0.0/overview/version-explain
![1709294507414](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/95abd858-bb2e-4141-ab7f-3af7f0b446cd)

**Comment by yuluo-yx** [comment]
This issue is temporarily closed due to no response for a long time. It will be opened again after the submitter responds.
