### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discovery 中权重的更新间隔

### ISSUE THREAD

**Issue by yoboygo** [alibaba/spring-cloud-alibaba#3649]
在控制台更新了实例的权重之后，等30s才会生效，我尝试了spring.cloud.nacos.discovery.watch-delay这个参数，不起作用，请问这个更新的时间间隔有参数可以设置吗？

   <groupId>com.alibaba.cloud</groupId>
   <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2021.0.4.0</version>

**Comment by ruansheng8** [comment]
默认情况下，在 Nacos 界面改完权重，应用服务会实时更新相关服务元数据信息。

另外，Spring Cloud Gateway 4.x 以前的版本 或 Ribbon 等框架默认会对服务实例信息做缓存，想要达到实时刷新效果需要手动清理相应框架的实例缓存列表。可以通过  Nacos 的 `Subscriber<InstancesChangeEvent> ` 来监听实例信息变更事件，在里面的逻辑清理对应的实例缓存。

**Comment by yoboygo** [comment]
好的，我看下，谢谢

**Comment by yuluo-yx** [comment]
No feedback from users, now closed.
