### ISSUE TITLE
属性spring.cloud.nacos.discovery.connect-timeout没有了？？

### ISSUE THREAD

**Issue by startjava** [alibaba/spring-cloud-alibaba#3658]
属性spring.cloud.nacos.discovery.connect-timeout没有了？？

**Comment by yuluo-yx** [comment]
https://sca.aliyun.com/zh-cn/docs/2022.0.0.0/user-guide/nacos/advanced-guide#%E9%85%8D%E7%BD%AE%E9%A1%B9%E5%8F%82%E8%80%83-1


https://github.com/alibaba/spring-cloud-alibaba/blob/4de42b3170a37fa58a3f6215ab8d7276d700f322/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java#L212C11-L212C13


https://github.com/alibaba/spring-cloud-alibaba/blob/4de42b3170a37fa58a3f6215ab8d7276d700f322/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java#L207
