### ISSUE TITLE
 Using @RefreshScope in nacos cannot refresh the remote configuration file

### ISSUE THREAD

**Issue by hxm2234098193** [alibaba/spring-cloud-alibaba#3663]
I use @RefreshScope in nacos but cannot refresh the remote configuration file.
I wrote a controller and used the @Value annotation to inject the test.token property in the configuration file.When I start the springboot project, I can get the test.token attribute value when I access the api. But when I modified the nacos configuration file, the results of my access to the API again were not updated. 

This is the controller I wrote:

![1711091381847](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/439e08cd-eaff-4e8f-a22b-a1d4d3a0af3f)

This is the configuration file for test.token on the nacos server:

![1711091739717](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/a68299cc-9fe6-4803-b5fe-67a8de026781)

This is the result of accessing the API in the browser:
![1711091656660](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/a4ff4f2a-33d6-43e9-b1e9-9e9fc9dbc3c3)

But when I modified the configuration file in the nacos service and accessed the API again, the attribute value of test.token did not change, and there was no real-time refresh effect.

The configuration file after modifying test.token on the nacos server:

![1711091941067](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/73855f30-2778-4a79-b6b4-d5373e9efc90)

This is the result of accessing the API in the browser (not change):
![1711091656660](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/a4ff4f2a-33d6-43e9-b1e9-9e9fc9dbc3c3)

This is the configuration file of springboot:

![1711092060962](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/476da298-2c81-4cc8-bacf-51f4ee764276)
![1711092089490](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/345a8916-dfc7-4388-89e4-208396cc35ec)

**Comment by hxm2234098193** [comment]
springboot and springcloudalibaba 's version
![1711094396607](https://github.com/alibaba/spring-cloud-alibaba/assets/70274189/774cff1d-49d1-4b9b-a352-9a3a3c56da9a)

**Comment by hxm2234098193** [comment]
nacos version : 2.1.2

**Comment by hxm2234098193** [comment]
After I changed application.yml to bootstrap.yml, the function became normal！

**Comment by yuluo-yx** [comment]
you can refer `https://sca.aliyun.com/zh-cn/docs/2022.0.0.0/user-guide/nacos/advanced-guide#nacos-%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%BF%9B%E9%98%B6%E6%8C%87%E5%8D%97 `

**Comment by dongguo4812** [comment]
https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/application.yaml          我看到  - nacos:nacos-config-example.properties?refresh=true，我这样配置      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?refresh=true测试是可以的
