### ISSUE TITLE
引入spring-cloud-starter-alibaba-seata  会导致 shared-configs 配置失效

### ISSUE THREAD

**Issue by Anymous526** [alibaba/spring-cloud-alibaba#3664]
<spring-boot.version>3.1.10</spring-boot.version>
   <spring-cloud-alibaba.version>2022.0.0.0</spring-cloud-alibaba.version>
    <spring-cloud.version>2022.0.0</spring-cloud.version>

在引入
<dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
    </dependency>
后会让
shared-configs 配置失效

**Comment by yuluo-yx** [comment]
@Anymous526 `shared-configs` Is this property a configuration item in nacos config?

if so, Can you provide an example?

**Comment by Anymous526** [comment]
https://gitlab.tospinomall.com/sunxun/springcloud-seata.git

**Comment by yuluo-yx** [comment]
@Anymous526 Can you delete the extra files in it? Can you keep only the smallest unit that reproduces the problem?

You can also provide demos in the form of github repository addresses.

**Comment by ruansheng8** [comment]
For Spring Boot 2.4 and above, we recommend using `spring.config.import`, for example:
```yaml
spring:
  config:
    import:
      - nacos:nacos-config-example.properties?refresh=true
```

**Comment by Anymous526** [comment]
> @Anymous526 Can you delete the extra files in it? Can you keep only the smallest unit that reproduces the problem?
> 
> You can also provide demos in the form of github repository addresses.

OK,

https://gitlab.tospinomall.com/sunxun/springcloud-seata.git

**Comment by Anymous526** [comment]
好像已经搞定了。

**Comment by yuluo-yx** [comment]
> 好像已经搞定了。

Congratulation!

**Comment by Anymous526** [comment]
> For Spring Boot 2.4 and above, we recommend using `spring.config.import`, for example:
> 
> ```yaml
> spring:
>   config:
>     import:
>       - nacos:nacos-config-example.properties?refresh=true
> ```

正确的操作。
