### ISSUE TITLE
access_log接口返回的客户端版本号不对

### ISSUE THREAD

**Issue by ztw-cmd** [alibaba/spring-cloud-alibaba#3674]
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/58285316/2d522a38-64c9-41e2-9739-5eb190cd9b03)

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/58285316/adb18bd1-39ec-42cf-afc9-f776b3de7c82)

**Comment by yuluo-yx** [comment]
nacos 没有 2.1.0.RELEASE 这个版本. 会以 spring-cloud-alibaba 中的 nacos 版本拉依赖，sca 2.2.8的 nacos 是 2.1.0 版本。
2.2.8 存在一些已知问题，可以升级到最新版本试试。

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/c0722c4a-4628-4569-8292-125b6b6fe4a9)


下面的图片有更多的上下文信息吗，这样什么都看不出来

**Comment by ztw-cmd** [comment]
这是nacos服务端
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/58285316/207234ea-c325-4c9f-9015-3e99b19d09b7)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/58285316/4408d162-f65c-4f37-87f0-d29bdeba6791)
第二张图也是nacos官方给的对照图
注册端往服务端发送心跳 服务端记录接口信息的时候 客户端明明是2.1.0接口日志为什么一直是V1.2.0  
nacos 1.4.1 
nacos 1.3.3
这俩客户端的版本就是对的!

**Comment by yuluo-yx** [comment]
```xml
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>2.1.0</version>
</dependency>
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>2.1.0.RELEASE</version>
</dependency>
```
这是两个不同的版本，最开始的图 nacos 版本写的是 xxx.RELEASE 这个依赖不存在。第二个问题 access_log 给个最简 demo 本地复现不出来。

> nacos 1.4.1
> nacos 1.3.3
> 这俩客户端的版本就是对的!

没有理解你想表达什么意思 🥲🥲 
（ps：第二张图是 sca 官网的组件版本对应关系，不是 nacos 给的。地址： https://sca.aliyun.com/zh-cn/docs/next/overview/version-explain#%E7%BB%84%E4%BB%B6%E7%89%88%E6%9C%AC%E5%85%B3%E7%B3%BB）

**Comment by ztw-cmd** [comment]
第一步:自己搭建个nacos2.1.0的服务端
第二步:按照官方的文档
https://nacos.io/docs/v2/ecology/use-nacos-with-spring-boot/
用springboot搭建一个客户端  需要把这个客户端注册到 第一步搭建好的服务端中

第三步分别用着两个坐标去注册到nacos服务列表中

<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-discovery-spring-boot-starter</artifactId>
    <version>0.2.12</version>
</dependency>


<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-discovery-spring-boot-starter</artifactId>
    <version>0.2.8</version>
</dependency>

第四步:然后分别查看access_log中的接口例如:
/nacos/v1/ns/instance/beat
/nacos/v1/ns/instance/list
当nacos client pom坐标为0.2.12时候返回的客户端版本为:Nacos-Java-Client:v1.2.0
当nacos client pom坐标为0.2.8时候返回的客户端版本为:Nacos-Java-Client:v1.4.2

实际正确的结果(个人认为):
当nacos client pom坐标为0.2.12时候返回的客户端版本为:Nacos-Java-Client:v2.1.0
当nacos client pom坐标为0.2.8时候返回的客户端版本为:Nacos-Java-Client:v1.4.2

**Comment by ztw-cmd** [comment]
第一步:自己搭建个nacos2.1.0的服务端
第二步:按照官方的文档
https://nacos.io/docs/v2/ecology/use-nacos-with-spring-boot/
用springboot搭建一个客户端  需要把这个客户端注册到 第一步搭建好的服务端中(不用搭建配置中心)

第三步分别用着两个坐标去注册到nacos服务列表中
`
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-discovery-spring-boot-starter</artifactId>
    <version>0.2.12</version>
</dependency>


<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-discovery-spring-boot-starter</artifactId>
    <version>0.2.8</version>
</dependency>`

第四步:然后分别查看access_log中的接口例如:
/nacos/v1/ns/instance/beat
/nacos/v1/ns/instance/list
当nacos client pom坐标为0.2.12时候返回的客户端版本为:Nacos-Java-Client:v1.2.0
当nacos client pom坐标为0.2.8时候返回的客户端版本为:Nacos-Java-Client:v1.4.2

实际正确的结果(个人认为):
当nacos client pom坐标为0.2.12时候返回的客户端版本为:Nacos-Java-Client:v2.1.0
当nacos client pom坐标为0.2.8时候返回的客户端版本为:Nacos-Java-Client:v1.4.2

**Comment by ztw-cmd** [comment]
`
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-discovery-spring-boot-starter</artifactId>
    <version>0.2.12</version>
</dependency>


<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-discovery-spring-boot-starter</artifactId>
    <version>0.2.8</version>
</dependency>`

**Comment by ztw-cmd** [comment]
怎么说 是有问题还是怎么回事?

**Comment by ztw-cmd** [comment]
?
