### ISSUE TITLE
Is it able to use discovery without registering itself? 

### ISSUE THREAD

**Issue by craynic** [alibaba/spring-cloud-alibaba#3675]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
Scenario: I start a local instance for development. It needs to call dev deployments, but it shouldn't be called by dev deployments.

**Describe what information you have read**
There is no option to disable auto registering according to the doc.
I tried marking the instance offline on nacos web. It worked, while it turned online every time I restart the instance. It's annoyed to click the offline button every time I restart the instance.
I tried setting `-Dspring.cloud.nacos.discovery.weight=0`. It worked, while it is not documented. I'm afraid this will not function some day.
So what's the formal way to do this?

**Comment by yuluo-yx** [comment]
You can try `spring.cloud.nacos.discovery.register-enabled=false`

**Comment by craynic** [comment]
Cool. Hope it documented in wiki.

**Comment by yuluo-yx** [comment]
https://sca.aliyun.com/en-us/docs/2023.0.0.0-RC1/user-guide/nacos/advanced-guide/#configuration-items-1 

It's documented, but it doesn't look like the documentation has been updated, so we'll update this configuration item later!
