### ISSUE TITLE
[AI-Task]: Adapt TongYi LLM  speech transcription by Spring AI API.

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3703]
https://help.aliyun.com/zh/dashscope/developer-reference
https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiAudioTranscriptionClient.java
https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/api/transcriptions.html

**Comment by why-ohh** [comment]
assign

**Comment by n3A87** [comment]
assign

**Comment by yuluo-yx** [comment]
> assign

lgtm. pls go ahead

**Comment by lltx** [comment]
review了一下相关实现 ，目前适配 spring ai v0.8.1 版本 ，相关API 在 1.0 版本 已经做了大量重构， 不再兼容

**Comment by yuluo-yx** [comment]
> review了一下相关实现 ，目前适配 spring ai v0.8.1 版本 ，相关API 在 1.0 版本 已经做了大量重构， 不再兼容

你说的是这个 https://docs.spring.io/spring-ai/reference/api/audio/transcriptions.html 吗?
