### ISSUE TITLE
SpringCloudAlibab and SpringBoot version?

### ISSUE THREAD

**Issue by becage** [alibaba/spring-cloud-alibaba#3711]
```https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E```
<img width="732" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/41765271/dd2a6927-c26c-4628-90a8-eb9490b07ff0">

Can SpringBoot be used directly with versions 3.2.5 and above?

**Comment by yuluo-yx** [comment]
Yep, you can try it locally, there is no official update for the new sb version yet. sca is adapted to a small range of sb versions.

btw, the latest version is:

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/6e0e75c3-f401-4184-8521-e5f5ed2313ce)
