### ISSUE TITLE
[AI]thread safety issues with TongYiChatClient TongYiChatClient线程安全问题

### ISSUE THREAD

**Issue by sailorzheng** [alibaba/spring-cloud-alibaba#3719]
AI  TongYiChatClient
spring cloud alibaba version：2023.0.1.0

The Alibaba Cloud DashScope official website mentions that Generation Class is not thread-safe. However, in the Spring Cloud Alibaba AI, the TongYiChatClient is a singleton, and the Generation it holds is also a singleton. Could you please clarify if there might be any thread safety issues with TongYiChatClient?
阿里云 DashScope官网中提到Generation不是线程安全的，但看spring cloud alibaba ai中的TongYiChatClient是单例的 ，并且其持有的Generation也是单例的，麻烦问下是否会TongYiChatClient 是否会有线程安全问题呢
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/14822974/c0796095-9348-4401-ae15-5579ce65e255)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/14822974/8aee2959-7c8c-466c-886d-9e57da91a973)

I have read the reference doc of spring ai and spring cloud alibaba ai

**Comment by yuluo-yx** [comment]
According to the description on the website, it does have a security issue, can you submit a pr to finish it? @sailorzheng
