### ISSUE TITLE
[AI] custom chatOptions not working

### ISSUE THREAD

**Issue by zddgg** [alibaba/spring-cloud-alibaba#3730]
**Which Component**

AI

**Describe what problem you have encountered**

When I use the streaming interface of TongYiChatClient, the data returned each time is not incremental because the default value of ChatOptions.incrementalOutput is false.
I passed in a custom ChatOption through the Prompt constructor, but it did not take effect. I found that when ChatOptions are merged, the priority of the default configuration is higher than that of the custom configuration. Is there a problem with the method I am using?

我在使用 TongYiChatClient 的流式接口时每次返回的数据并不是增量，因为 ChatOptions.incrementalOutput 默认值时false。
我通过 Prompt 构造器传入了自定义的 ChatOption 没有生效，发现在 ChatOptions 合并时默认配置的优先级高于自定义配置，是我使用的方法有问题吗？

![Snipaste_2024-05-13_13-06-58](https://github.com/alibaba/spring-cloud-alibaba/assets/41278122/b37c9f5b-4251-4ff1-8f75-c8800c391389)

![Snipaste_2024-05-13_13-09-51](https://github.com/alibaba/spring-cloud-alibaba/assets/41278122/1fd9e5ec-d459-4ebf-9a7d-f927150607c1)

**Describe what information you have read**

not found

**Comment by yuluo-yx** [comment]
看看 spring-cloud-ai-example,  配置优先级问题可以参考下测试类

https://help.aliyun.com/zh/dashscope/developer-reference/api-details

```
true -> 开启增量输出模式，后面输出不会包含已经输出的内容
false -> 会包含已输出的内容
```

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/0fd9fec3-8320-48f6-98b0-d26d5a690010)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/9830b880-ef52-4786-8170-f73bc72a438e)

**Comment by 18200533099** [comment]
@yuluo-yx 
![8640ac7ace83600d579d70ea7aa919b](https://github.com/alibaba/spring-cloud-alibaba/assets/56868830/f75a1ff4-d9e7-4560-9cc7-d63e96edf242)
作者大大麻烦看下这个方法好像会因为ConversationParam类中incrementalOutput默认设置为false的情况导致incrementalOutput参数设置不生效

**Comment by yuluo-yx** [comment]
> @yuluo-yx ![8640ac7ace83600d579d70ea7aa919b](https://private-user-images.githubusercontent.com/56868830/332011289-f75a1ff4-d9e7-4560-9cc7-d63e96edf242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTA4NTUsIm5iZiI6MTcxNjIxMDU1NSwicGF0aCI6Ii81Njg2ODgzMC8zMzIwMTEyODktZjc1YTFmZjQtZDllNy00NTYwLTljYzctZDYzZTk2ZWRmMjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEzMDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MmY2ODM1ZmZjZWU2NjQ1MjIwZGUwMTgyMmUxYmEyZTMwNDUwN2U3ZDkxZjZlYWU2OWU2YWUzNDYzNDlkNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FBwoL2ssGa3CQvaBaqYCOIp0GtGdAATeLAQ0MSrKDE8) 作者大大麻烦看下这个方法好像会因为ConversationParam类中incrementalOutput默认设置为false的情况导致incrementalOutput参数设置不生效

简单给个 demo 我看看？

**Comment by yuluo-yx** [comment]
奇怪，为什么我写 example 是好的没，确实是增量输出的，我用stirngbuilder拼接的，你参考下看看 ？@18200533099
