### ISSUE TITLE
Client not connected, current status:STARTING

### ISSUE THREAD

**Issue by wuwei0727** [alibaba/spring-cloud-alibaba#3736]
**Which Component**
use [pring-cloud-alibaba](https://github.com/alibaba/spring-cloud-alibaba)

Startup error

**Screenshots**
Startup error：
![PixPin_2024-05-16_15-48-36](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/265805cb-df47-401b-8156-ece8011662b2)

docker-compose：
![PixPin_2024-05-16_15-50-24](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/8a241c7b-40a0-40eb-a5a7-8d2cfc63b97e)

springboot nacos yml ：
![PixPin_2024-05-16_15-50-38](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/85d196a8-cf83-44c5-b8b8-b6d845c9d211)

aliyun  The security group has been released
![PixPin_2024-05-16_15-51-17](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/ba72e35c-1a98-4930-80ab-5a35774e9563)

**Additional context**
<spring-boot.version>2.7.13</spring-boot.version>
        <spring-cloud.version>2021.0.8</spring-cloud.version>
        <spring-cloud-alibaba.version>2021.0.5.0</spring-cloud-alibaba.version>

**Comment by wuwei0727** [comment]
Why do I configure the public ip address :8848, but the error message is 127.0.0.1:8848?

**Comment by yuluo-yx** [comment]
if use docker container, pls mapping 9848 port. try again

**Comment by wuwei0727** [comment]
I mapped it, Ali Cloud also mapped it
![PixPin_2024-05-17_09-57-10](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/4f15031d-ef37-474e-8ee5-14c48101a58f)

**Comment by yuluo-yx** [comment]
Can you provide a simple demo?

**Comment by wuwei0727** [comment]
The gateway connects to the nacos demo

[YunNian-Cloud-demo.zip](https://github.com/alibaba/spring-cloud-alibaba/files/15343424/YunNian-Cloud-demo.zip)

**Comment by yuluo-yx** [comment]
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/836cb8d5-6ced-4b25-acff-cc672074f8b6)

```
:21.287 [main] INFO  c.a.c.n.r.NacosContextRefresher - [registerNacosListener,129] - [Nacos Config] Listening config: dataId=yunnian-gateway-dev.yml, group=DEFAULT_GROUP
12:22:21.288 [main] INFO  c.a.c.n.r.NacosContextRefresher - [registerNacosListener,129] - [Nacos Config] Listening config: dataId=yunnian-gateway, group=DEFAULT_GROUP
12:22:21.288 [main] INFO  c.a.c.n.r.NacosContextRefresher - [registerNacosListener,129] - [Nacos Config] Listening config: dataId=yunnian-gateway.yml, group=DEFAULT_GROUP
(♥◠‿◠)ﾉﾞ  网关启动成功   ლ(´ڡ`ლ)ﾞ 
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: C:\Users\Administrator\logs\csp\
INFO: Sentinel log name use pid is: false
INFO: Sentinel log level is: INFO
```

This is a network issue between the containers, you can check if the nacos container and the gateway container can communicate properly.

**Comment by wuwei0727** [comment]
ThenThen should I use the container name yunnian-nacos:8848？

I've tried this before. No.

**Comment by yuluo-yx** [comment]
> ThenThen should I use the container name yunnian-nacos:8848？
> 
> I've tried this before. No.

a simple way, you can run `ping yunnian-nacos` on gateway app container.

**Comment by wuwei0727** [comment]
Hello, I configured server-addr: 8.136.114.59:8848 in bootstrap.yml. Why is the value 127.0.0.1:8848 when I start the connection?

**Comment by wuwei0727** [comment]
![Uploading PixPin_2024-05-19_12-38-13.png…]()

**Comment by wuwei0727** [comment]
![PixPin_2024-05-19_12-38-13](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/9ca13e6f-7743-44eb-8de8-c7b05378d474)

**Comment by yuluo-yx** [comment]
> ![PixPin_2024-05-19_12-38-13](https://private-user-images.githubusercontent.com/100761249/331850925-9ca13e6f-7743-44eb-8de8-c7b05378d474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDIxNDIsIm5iZiI6MTcxNjEwMTg0MiwicGF0aCI6Ii8xMDA3NjEyNDkvMzMxODUwOTI1LTljYTEzZTZmLTc3NDMtNDRlYi04ZGU4LWM3YjA1Mzc4ZDQ3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNjU3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTZkZmExOTgxODUyMjMyZDgwZjcwZDg2ODM4NGY4YWE0YWEyYmUwZTVmY2FiZmNhYmY3ZDU0MmI3ZTg4YzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EaSS-qzvBlECbw_pp1Wjkfw6a7iW22SAOlkdL-DhFz4)

What about configuration in application.yml? This may be a bug.
You can check that the preconfiguration file is correctly loaded into the

**Comment by yuluo-yx** [comment]
Please take a closer look at your project configuration, I ran the demo you provided locally and it ran successfully without any errors and without changing any configuration properties.

this is my local running log:

```
15:08:29.076 [main] INFO  c.a.n.c.e.SearchableProperties - [sortPropertySourceDefaultOrder,197] - properties search order:PROPERTIES->JVM->ENV->DEFAULT_SETTING
15:08:29.121 [background-preinit] INFO  o.h.v.i.util.Version - [<clinit>,21] - HV000001: Hibernate Validator 6.2.5.Final
15:08:29.467 [main] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [init,56] - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.
15:08:29.468 [main] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [init,56] - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.
Spring Boot Version: 2.7.13
Spring Application Name: yunnian-gateway

15:08:31.646 [main] WARN  c.a.c.n.c.NacosPropertySourceBuilder - [loadNacosData,87] - Ignore the empty nacos configuration and get it based on dataId[yunnian-gateway] & group[DEFAULT_GROUP]
15:08:31.700 [main] WARN  c.a.c.n.c.NacosPropertySourceBuilder - [loadNacosData,87] - Ignore the empty nacos configuration and get it based on dataId[yunnian-gateway.yml] & group[DEFAULT_GROUP]
15:08:31.777 [main] INFO  c.y.g.YunNianGatewayApplication - [logStartupProfileInfo,637] - The following 1 profile is active: "dev"
15:08:36.457 [main] INFO  c.a.c.s.g.s.SentinelSCGAutoConfiguration - [sentinelGatewayFilter,144] - [Sentinel SpringCloudGateway] register SentinelGatewayFilter with order: -2147483648
15:08:36.831 [main] INFO  c.a.c.s.g.s.SentinelSCGAutoConfiguration - [sentinelGatewayBlockExceptionHandler,134] - [Sentinel SpringCloudGateway] register SentinelGatewayBlockExceptionHandler
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: C:\Users\Administrator\logs\csp\
INFO: Sentinel log name use pid is: false
INFO: Sentinel log level is: INFO
15:08:37.058 [main] WARN  o.s.c.l.c.LoadBalancerCacheAutoConfiguration$LoadBalancerCaffeineWarnLogger - [logWarning,83] - Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
15:08:37.077 [main] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [init,56] - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.
15:08:37.077 [main] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [init,56] - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.
15:08:37.442 [main] INFO  c.a.c.s.d.c.SentinelConverter - [convert,79] - converter can not convert rules because source is empty
15:08:39.606 [main] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [init,56] - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.
15:08:39.606 [main] INFO  c.a.n.p.a.s.c.ClientAuthPluginManager - [init,56] - [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.
15:08:39.940 [main] INFO  c.a.c.n.r.NacosServiceRegistry - [register,76] - nacos registry, DEFAULT_GROUP yunnian-gateway 192.168.235.1:1080 register finished
15:08:40.138 [main] INFO  c.a.c.n.d.NacosDiscoveryHeartBeatPublisher - [start,66] - Start nacos heartBeat task scheduler.
15:08:40.152 [main] INFO  c.y.g.YunNianGatewayApplication - [logStarted,61] - Started YunNianGatewayApplication in 12.507 seconds (JVM running for 13.522)
15:08:40.156 [main] INFO  c.a.c.n.r.NacosContextRefresher - [registerNacosListener,129] - [Nacos Config] Listening config: dataId=yunnian-gateway-dev.yml, group=DEFAULT_GROUP
15:08:40.156 [main] INFO  c.a.c.n.r.NacosContextRefresher - [registerNacosListener,129] - [Nacos Config] Listening config: dataId=yunnian-gateway, group=DEFAULT_GROUP
15:08:40.156 [main] INFO  c.a.c.n.r.NacosContextRefresher - [registerNacosListener,129] - [Nacos Config] Listening config: dataId=yunnian-gateway.yml, group=DEFAULT_GROUP
(♥◠‿◠)ﾉﾞ  网关启动成功   ლ(´ڡ`ლ)ﾞ 
15:08:43.424 [RMI TCP Connection(4)-192.168.1.3] INFO  c.a.c.s.d.c.SentinelConverter - [convert,79] - converter can not convert rules because source is empty
```

btw, You should ensure that the nacos deployed on your server is secure
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/77964041/2ce17ce8-9a07-438d-be18-f56d956d78c5)

**Comment by wuwei0727** [comment]
Thank you for your patient answer. I can connect to nacos by running gateway locally. My local debug breakpoint read nacos source code configuration and loaded my configuration 8.136.114.59:8848, but the online environment, as you see, reported an error. I see the environmental error on the line: NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='127.0.0.1:8848', The Client is not connected and current status:STARTING. Why is it 127.0.0.1:8848? I checked the configuration file and there are no configuration errors. Can you give me some ideas for troubleshooting?

**Comment by yuluo-yx** [comment]
Is the online environment configured the same way? dev config file

**Comment by wuwei0727** [comment]
Yes, the environment is the same online

**Comment by wuwei0727** [comment]
Oh, by the way, I use docker-compose for my online environment, and I have no problem executing it online using java-jar. But you can't use docker-compose
![PixPin_2024-05-19_15-31-28](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/5bab378e-7839-42a2-8789-aeee38f56a6c)

**Comment by yuluo-yx** [comment]
imo, In an online environment, it is possible that the dev configuration file is not loaded correctly, but instead, a default is loaded, which you can see more about in the logs

Looking at the online environment
``
15:08:31.777 [main] INFO c.y.g.YunNianGatewayApplication - [logStartupProfileInfo,637] - The following 1 profile is active: "dev"
`` 
What is output here? dev or default

**Comment by yuluo-yx** [comment]
if is `default`, you can see `https://github.com/yuluo-yx/sca-k8s-demo/blob/f4e92d38c4752e7e34cc3e2b1c52dfc8efcdb992/docker-compose/apps/provider/Dockerfile#L18` setting

**Comment by wuwei0727** [comment]
![PixPin_2024-05-19_15-37-54](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/3c33b80a-a030-486c-8d16-95335f94ca9f)

**Comment by wuwei0727** [comment]
My environment here is dev

**Comment by yuluo-yx** [comment]
Make sure your config file is loaded correctly, or is it present in the container? It looks like the config file is loaded correctly

**Comment by yuluo-yx** [comment]
maybe you can refer : https://github.com/yuluo-yx/sca-k8s-demo/blob/master/docker-compose/apps/provider/Dockerfile#L18

**Comment by wuwei0727** [comment]
![PixPin_2024-05-20_15-33-39](https://github.com/alibaba/spring-cloud-alibaba/assets/100761249/e90b9c47-8ada-4e63-8a1a-0638833f74e3)

Hi, I checked docker's network and they are on the same network！

**Comment by wuwei0727** [comment]
Now I can not locate what is the problem, this problem makes me confused, no idea

**Comment by wuwei0727** [comment]
Hello, thank you very much! I've solved my problem。
The problem is that the old one was not updated before I built the docker image. The configuration file of the old image was 127.0.0.1, so I just updated the docker image

**Comment by yuluo-yx** [comment]
> Hello, thank you very much! I've solved my problem。 The problem is that the old one was not updated before I built the docker image. The configuration file of the old image was 127.0.0.1, so I just updated the docker image

Good job, config file not load or network question.
