### ISSUE TITLE
[AI] SpringCloudAlibaba官网中AI部分的应用开发实例所对应的链接失效了！

### ISSUE THREAD

**Issue by sichenyong** [alibaba/spring-cloud-alibaba#3745]
SpringCloudAlibaba官网中AI部分的应用开发实例所对应的链接失效了！
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/91589693/425abf81-5788-4774-98b7-5910b498c798)

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/91589693/b52190ef-9413-4b8a-a97c-355e1de31cc4)

**Comment by yuluo-yx** [comment]
got it, I moved, pls see https://github.com/alibaba/spring-cloud-alibaba/pull/3743. after we update related links.

cc @chickenlj
