### ISSUE TITLE
声明式动态刷新不生效

### ISSUE THREAD

**Issue by Mredust** [alibaba/spring-cloud-alibaba#3747]
版本：boot：2.4.2 cloud：2020.0.1 cloud alibaba：2021.1 nacos：1.4.1
spring:
  application:
    name: nacos-demo
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.91.131:8848
      discovery:
        namespace: ${spring.profiles.active}
        group: nacos-demo
        cluster-name: gz
      config:
        namespace: ${spring.profiles.active}
        group: nacos-demo
        file-extension: yaml
        refresh-enabled: true
        extension-configs:
          - data-id: nacos-demo-api-${spring.profiles.active}.yaml
            group: nacos-demo
            refresh: true
          - data-id: nacos-demo-service-${spring.profiles.active}.yaml
            group: nacos-demo
            refresh: true
        shared-configs:
          - data-id: common-${spring.profiles.active}.yaml
            group: common-dev
            refresh: true

对动态刷新测试过@RefreshScope是可以的，换成声明式的refresh-enabled: true就不行。在nacos服务配置修改文件并发布后控制台是有日志说明我修改过文件，最后请求时还是之前的配置信息，但是重启后配置信息是重新读取了。请问这个声明式的配置是可以用的吗

**Comment by ruansheng8** [comment]
基于 `@ConfigurationProperties` 声明的属性配置类，可以实时动态刷新（refresh-enabled 默认为开启状态），如果使用 Spring 中的 `@Value` 方式，在类上添加 `@RefreshScope` 也可以实现动态刷新。

如果你的动态刷新功能失效，可以贴一下你代码中具体是如何使用的

**Comment by Mredust** [comment]
> 基于 `@ConfigurationProperties` 声明的属性配置类，可以实时动态刷新（refresh-enabled 默认为开启状态），如果使用 Spring 中的 `@Value` 方式，在类上添加 `@RefreshScope` 也可以实现动态刷新。
> 
> 如果你的动态刷新功能失效，可以贴一下你代码中具体是如何使用的

如果不使用 @ConfigurationProperties 、@RefreshScope和 @NacosValue ，单单只是使用 refresh-enabled 能否生效。但是我用了后发现不生效并不会实时刷新
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/124856279/f0d274e5-1bb6-4c4f-82bd-961c8f6173d6)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/124856279/81dc0e71-d425-484e-ba95-f01122d2d939)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/124856279/1479ef42-2c14-4d3e-b934-64d49d1cdadd)

**Comment by ruansheng8** [comment]
@Mredust ，`@Value` 必须配合 `@RefreshScope` 一起使用才行实现动态刷新，这个机制和 Spring Cloud 官方的定义保持一致，因为有的场景是希望启动后值就固定，不允许动态刷新，所以需要动态刷新的场景需要手动添加  `@RefreshScope`

**Comment by Mredust** [comment]
> @Mredust ，`@Value` 必须配合 `@RefreshScope` 一起使用才行实现动态刷新，这个机制和 Spring Cloud 官方的定义保持一致，因为有的场景是希望启动后值就固定，不允许动态刷新，所以需要动态刷新的场景需要手动添加 `@RefreshScope`

明白了，感谢感谢
