### ISSUE TITLE
配置格式为properties时，换行符\n读取后变成\\n

### ISSUE THREAD

**Issue by maohc** [alibaba/spring-cloud-alibaba#3748]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.3.RELEASE</version>
</dependency>

NacosDataPropertiesParser方法doParse处理data数据，拿到value后，此时换行符“\n”变成了"\\\\n"，未做处理。是否应该将"\\\\n"替换成“\n”

**Comment by yuluo-yx** [comment]
试下最新版本有没有这个问题

**Comment by maohc** [comment]
升级到2.2.4.RELEASE版本解析properteis文件有中文乱码问题，升级到2.2.5.RELEASE好了。看了源码，2.2.4及之后版本调整了解析机制。
