### ISSUE TITLE
idea 导入项目无法自动识别源根，

### ISSUE THREAD

**Issue by LordVoldemt** [alibaba/spring-cloud-alibaba#3749]
![微信截图_20240603154153](https://github.com/alibaba/spring-cloud-alibaba/assets/90120114/524de78e-d115-4108-a2ac-531e8a209648)
![Uploading 微信截图_20240603154153.png…]()

**Comment by yuluo-yx** [comment]
刷 maven

**Comment by LordVoldemt** [comment]
刷maven 没用的,必须要用jdk17, 而且是高版本的idea, 低版本的idea还不支持jdk

**Comment by yuluo-yx** [comment]
> 刷maven 没用的,必须要用jdk17, 而且是高版本的idea, 低版本的idea还不支持jdk

这不是常识吗，sca 2023 适配 17 了
