### ISSUE TITLE
[GLCC] Spring Cloud Admin

### ISSUE THREAD

**Issue by chickenlj** [alibaba/spring-cloud-alibaba#3752]
### Background
Spring Cloud Alibaba (SCA), as a comprehensive solution for microservices, greatly simplifies the development process of microservice applications. But how to check and view the status of SpringCloud microservice clusters, including the number of services, instances, applications, etc., has always been a lack of content in the community ecosystem. Therefore, through this project, we expect to develop a Spring Cloud Admin console that can visually display and monitor the status of microservice clusters.

### Task details
Develop a visual console for the Spring Cloud Admin backend. Admin positioning is a visual microservice management platform that allows users to view the entire status of Spring Cloud microservices, including the number of services, instances, applications, and more. At the same time, SpringCloudAdmin should also integrate with mainstream Prometheus and Grafana systems, providing the ability to query and monitor cluster status indicators. Related reference implementation Spring Boot Admin

### Deliverables
1. Complete backend implementation of Spring Cloud Admin
2. Related user documentation and examples

### Related skills
1. Familiar with Java
2. Familiar with Spring Spring Boot、Spring Cloud

### 背景
Spring Cloud Alibaba (SCA) 作为微服务整体解决方案，极大的简化了微服务应用应用开发过程。但如何查查看 SpringCloud 微服务集群状态，包括服务数、实例数、应用数等，一直都是社区生态欠缺的内容。因此，通过此项目，我们期望开发一个 Spring Cloud Admin 的控制台，能够可视化的展示、监控微服务集群状态。
﻿
### 任务详情
﻿
开发可视化控制台 Spring Cloud Admin  后端，Admin 定位是一款可视化的微服务管控平台，通过它能够查看整个 SpringCloud 微服务状态，包括服务数、实例数、应用数等。同时 SpringCloudAdmin 还应与主流的 Prometheus、Grafana 系统集成，提供对集群状态的指标查询与监控能力。相关参考实现 Spring Boot  Admin
﻿
### 交付内容
1. Spring Cloud Admin 完整的后端实现
2. 相关的用户文档与示例
﻿
### 相关技能
1. 熟悉Java
4. 熟悉 Spring、Spring Boot、Spring Cloud

**Comment by java-acc** [comment]
@chickenlj Check out this [repository](https://github.com/codecentric/spring-boot-admin) for your business needs!
