### ISSUE TITLE
The dependency groupId of spring-ai-core in spring-cloud-starter-alibaba-ai module is not found.

### ISSUE THREAD

**Issue by LinQi0777** [alibaba/spring-cloud-alibaba#3753]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
Spring Cloud Starter Alibaba AI,2023.0.1.0

**Describe the bug**
The dependency groupId of spring-ai-core in spring-cloud-starter-alibaba-ai module is not found.

**Simplest demo**
Local Demo：
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/97254796/5ea8ecbc-c49f-4f19-9078-77e63e9963f6)
The search results of the Alibaba Cloud Maven warehouse are as follows:
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/97254796/711eec50-b801-4567-ad34-7e3bf582a3db)

**To Reproduce**
1. Create a new Maven project and import dependence.
```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2023.0.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-ai</artifactId>
        </dependency>
    </dependencies>
```
2. Refresh the Maven file.
3. See error 
```
Could not find artifact org.springframework.ai:spring-ai-core:pom:0.8.1 in aliyunmaven (https://maven.aliyun.com/repository/public)
```
**Expected behavior**
Relying on normal introduction.

**Screenshots**
Local Demo：
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/97254796/5ea8ecbc-c49f-4f19-9078-77e63e9963f6)

**Additional context**
Could not find artifact org.springframework.ai:spring-ai-core:pom:0.8.1 in spring‘s website.
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/97254796/7c94bddf-2014-4731-8a74-36e83835208e)

Maven repository description:
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/97254796/e7363dd1-f56f-4807-9f2c-6828e4b17a5a)

**Comment by yuluo-yx** [comment]
你可以参考 https://github.com/alibaba/spring-cloud-alibaba/issues/3712 配置 pom.xml 

另外 pr 对项目的意义并不是很大，现在 maven 中央仓库的包是抢注的，官方并没有发布正式的包，更多信息你可以看这个 issue https://github.com/alibaba/spring-cloud-alibaba/issues/3712 
升级版本对相应的 API 也要做更新，spring ai core 对一些接口作了比较大的改动。不是只修改版本号就可以升级成功的

**Comment by LordVoldemt** [comment]
https://blog.csdn.net/qq_35080796/article/details/111355515
参考上边文章,手动下载
具体网址:
https://[repo.spring.io](https://repo.spring.io/ui/repos/tree/General/snapshot/org/springframework/ai)/ui/repos/tree/General/snapshot/org/springframework/aihttps://[repo.spring.io](https://repo.spring.io/ui/repos/tree/General/snapshot/org/springframework/ai)/ui/repos/tree/General/snapshot/org/springframework/ai

**Comment by LinQi0777** [comment]
好的，谢谢

github-actions[bot] ***@***.***> 于2024年7月6日周六 02:52写道：
