### ISSUE TITLE
spring-cloud-starter-dubbo 2021.0.1.0 中 feign-core版本大于11.8时，feign.MethodMetadata中queryMapEncoded方法不存在

### ISSUE THREAD

**Issue by 5433zzz** [alibaba/spring-cloud-alibaba#3758]
在spring-cloud-starter-dubbo 2021.0.1.0 时升级alibaba-spring-cloud 2021.0.5.0后，feign-core同步升级，造成 feign.MethodMetadata中有两个方法不存在了，queryMapEncoded和queryMapEncoded ，造成整合失败。能否官方升级解决下此问题。

**Comment by yuluo-yx** [comment]
看下 dubbo 提供的 starter sca 这边已经移除了 dubbo 相关的依赖

**Comment by 5433zzz** [comment]
> 看下 dubbo 提供的 starter sca 这边已经移除了 dubbo 相关的依赖

那如果dubbo想直接用   整合springcloud的地址   spring-cloud://xxx   这种怎么办呢。只能整合 spring-cloud-starter-dubbo 使用吧

**Comment by yuluo-yx** [comment]
> > 看下 dubbo 提供的 starter sca 这边已经移除了 dubbo 相关的依赖
> 
> 那如果dubbo想直接用 整合springcloud的地址 spring-cloud://xxx 这种怎么办呢。只能整合 spring-cloud-starter-dubbo 使用吧

看下 dubbo 那边的文档之类的，我不太清楚

**Comment by JavaLionLi** [comment]
已经整合好的 欢迎查看 https://gitee.com/dromara/RuoYi-Cloud-Plus

**Comment by LovingCoder** [comment]
这个问题没有同学解决吗？

**Comment by yuluo-yx** [comment]
> 这个问题没有同学解决吗？

已经不推荐使用 sca 的 dubbo starter 了，现在的 spring 集成由 dubbo 提供，你可以去 dubbo 看看。
