### ISSUE TITLE
Is the spring-cloud-starter-alibaba-ai version wrong?

### ISSUE THREAD

**Issue by BubblingXuYijie** [alibaba/spring-cloud-alibaba#3761]
**Which Component**
spring-cloud-starter-alibaba-ai

**Screenshots**
On the right is my own new project, using pom to download spring-cloud-starter-alibaba-ai 2023.0.1.0, but the downloaded jar package content is inconsistent with the source code.

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/45624106/f9800c54-202d-42a8-8926-0cbbd115c00b)

**Comment by yuluo-yx** [comment]
这是截止 2023.0.1.0 版本之后的修改，暂时没有发布版本而已

**Comment by BubblingXuYijie** [comment]
好的，谢谢，我一度怀疑我的maven出问题了哈哈哈

**Comment by BubblingXuYijie** [comment]
> 这是截止 2023.0.1.0 版本之后的修改，暂时没有发布版本而已
好的，谢谢，我一度怀疑我的maven出问题了哈哈哈

**Comment by onlinedog** [comment]
我把类都拷贝进去了，测试成功了。

**Comment by yuluo-yx** [comment]
本周之内 sca 会发新版本的，就不用拷贝了

onlinedog ***@***.***>于2024年6月19日 周三14:08写道：
