### ISSUE TITLE
Nacos无法读取全部远程配置文件, 报is empty

### ISSUE THREAD

**Issue by zsm5833** [alibaba/spring-cloud-alibaba#3763]
java版本:17
spring-cloud-alibaba版本:2023.0.1.0
spring boot版本:3.3.0
spring cloud版本: 2023.0.2
nacos客户端版本:2.2.4

application文件是这样的(有多个application-${profile}.yml文件), 连的是远程Nacos(standalone版本), 版本2.3.0
<img width="500" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/35306242/762e66cb-9b58-47f6-803b-8818e15c23ce">

如果本地启动服务就没有问题
<img width="715" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/35306242/7aeac186-f5e0-4c42-af79-2732b4c7a5d3">

但是如果一部署到服务器的docker上面, application-common.yml(这里common-config.yml内容跟application-common.yml完全一样只是名字不同)一直报is empty, nacos里面有这个文件
<img width="891" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/35306242/53b82a74-2ae1-4f3a-ac02-c66e4e9495d8">

如果把图2的spring.cloud.nacos.server-addr改成本地地址再部署就没有问题, 我不知道是哪里出的问题, 难道springboot降到3.2.4或者nacos升到2.3.2才可以用吗

**Comment by yuluo-yx** [comment]
这种问题是你自己 docker 使用的问题，社区没精力帮你排查 docker 使用的 bug。 

https://github.com/alibaba/spring-cloud-alibaba/issues/3736 可以参考这个排查过程

**Comment by zsm5833** [comment]
> 这种问题是你自己 docker 使用的问题，社区没精力帮你排查 docker 使用的 bug。
> 
> #3736 可以参考这个排查过程

他这个是Nacos在Docker上面, 我这边Nacos没有部署在Docker上面, 如果把Gateway的Nacos地址改成远程的直接报`Client not connected,current status:UNHEALTHY`
