### ISSUE TITLE
[AI] SpringCloudAlibaba

### ISSUE THREAD

**Issue by MaRuifu** [alibaba/spring-cloud-alibaba#3767]
**Which Component**
Custom AI Model Integration

**Is your feature request related to a problem? Please describe.**
I often find it frustrating when I cannot integrate custom AI models seamlessly into our system. This limits our ability to leverage various AI capabilities from models such as Ollama and Baidu.

**Describe the solution you'd like**
I would like the capability to integrate custom AI models, such as those from Ollama and Baidu, into the existing system. This would allow us to harness the specialized capabilities of different models depending on our use-case requirements.

**Describe alternatives you've considered**
I have considered using pre-built general models that are already supported, but they often do not meet the specific needs we have for our projects. Developing models from scratch internally is another alternative, but it is resource-intensive and time-consuming.

**Additional context**
Integrating custom AI models will provide greater flexibility and efficiency when dealing with varying project requirements. For instance, Ollama is known for natural language processing while Baidu offers robust image recognition models. Having the ability to choose and integrate these models will significantly enhance our system’s AI performance.

**Comment by yuluo-yx** [comment]
In sca ai, the adaptation of tongyi llm is accomplished by adapting the interface provided by the core of spring ai. If you need to access other AI models, you can adapt them through the Spring AI interface.
