### ISSUE TITLE
如何看待阿里巴巴数学竞赛造假？

### ISSUE THREAD

**Issue by ghost** [alibaba/spring-cloud-alibaba#3770]
如何看待2024阿里达摩院全球数学竞赛公然造假？

**Comment by WangZhangQuan** [comment]
如何看待有心人公然造谣？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月24日(周一) 上午8:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [alibaba/spring-cloud-alibaba] 如何看待阿里巴巴数学竞赛造假？ (Issue #3770)




 
Closed #3770 as completed.
