### ISSUE TITLE
[AI] sca ai rag example run failed

### ISSUE THREAD

**Issue by 793834982** [alibaba/spring-cloud-alibaba#3773]
when i run spring-cloud-ai-rag-example get a error
Parameter 1 of constructor in com.alibaba.cloud.example.ai.rag.service.RAGService required a bean of type 'org.springframework.ai.vectorstore.VectorStore' that could not be found
Is it the person in charge who missed submitting the code

**Comment by yuluo-yx** [comment]
My local startup is fine. Check your local environment. @793834982 

```
信息: Starting service [Tomcat]
6月 25, 2024 11:04:46 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet engine: [Apache Tomcat/10.1.19]
6月 25, 2024 11:04:46 下午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring embedded WebApplicationContext
[main] INFO org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1267 ms
[main] INFO org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port 8081 (http) with context path ''
[main] INFO com.alibaba.cloud.example.ai.rag.RAGApplication - Started RAGApplication in 3.042 seconds (process running for 3.474)
[main] INFO com.alibaba.cloud.example.ai.rag.loader.RAGDataLoader - Creating Embeddings...
```

**Comment by airufei** [comment]
Error creating bean with name 'RAGController': Unsatisfied dependency expressed through field 'ragService': Error creating bean with name 'RAGService' defined in file [E:\hiscene-microservice\hiscene-cloud-base-service\hiscene-cloud-demo-ai-rag\target\classes\com\hiscene\ai\rag\service\RAGService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'vectorStore' defined in class path resource [org/springframework/ai/autoconfigure/vectorstore/redis/RedisVectorStoreAutoConfiguration.class]: Invalid rule type: JSON

**Comment by airufei** [comment]
Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'vectorStore' defined in class path resource [org/springframework/ai/autoconfigure/vectorstore/redis/RedisVectorStoreAutoConfiguration.class]: Invalid rule type: JSON

**Comment by airufei** [comment]
![image](https://github.com/user-attachments/assets/fba97bc0-2665-458e-9609-eb39ae1579bd)

**Comment by yuluo-yx** [comment]
![image](https://github.com/user-attachments/assets/b4c45985-a15c-462b-b043-f7b858864fb6)
failed.

**Comment by airufei** [comment]
> ![image](https://private-user-images.githubusercontent.com/77964041/355731141-b4c45985-a15c-462b-b043-f7b858864fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTg1NTMsIm5iZiI6MTcyMzAxODI1MywicGF0aCI6Ii83Nzk2NDA0MS8zNTU3MzExNDEtYjRjNDU5ODUtYTE1Yy00NjJiLWIwNDMtZjdiODU4ODY0ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4MTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDZjMGMwZjExM2NlNzg0MjkzYWQ0MGUzMzExNGEwOTQ2MTY1ODZiZjc1NDkwMzA3MjZiNTk1MGJlNTk2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3nar27IjPw5k7K_e5pdCbJdVQdjSf2QQ01VxLHaFVMQ) failed.

Every time the spring cloud ai rag example application is launched, Redis will automatically restart (presumably due to a hang, increasing memory and CPU may not solve the problem)

**Comment by airufei** [comment]
> ![image](https://private-user-images.githubusercontent.com/77964041/355731141-b4c45985-a15c-462b-b043-f7b858864fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTg1NTMsIm5iZiI6MTcyMzAxODI1MywicGF0aCI6Ii83Nzk2NDA0MS8zNTU3MzExNDEtYjRjNDU5ODUtYTE1Yy00NjJiLWIwNDMtZjdiODU4ODY0ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4MTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDZjMGMwZjExM2NlNzg0MjkzYWQ0MGUzMzExNGEwOTQ2MTY1ODZiZjc1NDkwMzA3MjZiNTk1MGJlNTk2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3nar27IjPw5k7K_e5pdCbJdVQdjSf2QQ01VxLHaFVMQ) failed.

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.
```
2024-08-07T16:15:48.026406273+08:00 

2024-08-07T16:15:48.026418263+08:00 ------ DUMPING CODE AROUND EIP ------

2024-08-07T16:15:48.026423335+08:00 Symbol: _Z27FP32_InnerProductSIMD16_SSEILh0EEfPKvS1_m (base: 0x7fcde915ff70)

2024-08-07T16:15:48.026427784+08:00 Module: /opt/redis-stack/lib/redisearch.so (base 0x7fcde8e54000)

2024-08-07T16:15:48.026432120+08:00 $ xxd -r -p /tmp/dump.hex /tmp/dump.bin

2024-08-07T16:15:48.026443220+08:00 $ objdump --adjust-vma=0x7fcde915ff70 -D -b binary -m i386:x86-64 /tmp/dump.bin

2024-08-07T16:15:48.026447758+08:00 ------

2024-08-07T16:15:48.026451896+08:00 8:M 07 Aug 2024 08:15:48.026 # dump of function (hexdump of 136 bytes):

2024-08-07T16:15:48.026457789+08:00 f30f1efa488d0497c5f057c90f1f4000c5f8101fc5e059064883c7404883c640c5f81067d0c5f8106fe0c5f81056f0c5f858c1c5d8594ed0c5f858c1c5d0594ee0c5f858c1c5f8104ff0c5f059cac5f058c84839f877b9c5f0c6c155c5fa58c1c5f015d1c5f0c6c9ffc5fa58c2c5fa58c9c5fa1005efb91a00c5fa5cc1c36690f30f1efac5fa100e

2024-08-07T16:15:48.026461676+08:00 

2024-08-07T16:15:48.026465740+08:00 === REDIS BUG REPORT END. Make sure to include from START to END. ===

2024-08-07T16:15:48.026469404+08:00 

2024-08-07T16:15:48.026474064+08:00        Please report the crash by opening an issue on github:

2024-08-07T16:15:48.026477784+08:00 

2024-08-07T16:15:48.026482443+08:00            http://github.com/redis/redis/issues

2024-08-07T16:15:48.026486054+08:00 

2024-08-07T16:15:48.026489994+08:00   If a Redis module was involved, please open in the module's repo instead.

2024-08-07T16:15:48.026493694+08:00 

2024-08-07T16:15:48.026497593+08:00   Suspect RAM error? Use redis-server --test-memory to verify it.

2024-08-07T16:15:48.026501208+08:00 

2024-08-07T16:15:48.026505221+08:00   Some other issues could be detected by redis-server --check-system

2024-08-07T16:15:48.118811530+08:00 Illegal instruction (core dumped)

```

**Comment by airufei** [comment]
> ![image](https://private-user-images.githubusercontent.com/77964041/355731141-b4c45985-a15c-462b-b043-f7b858864fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTg1NTMsIm5iZiI6MTcyMzAxODI1MywicGF0aCI6Ii83Nzk2NDA0MS8zNTU3MzExNDEtYjRjNDU5ODUtYTE1Yy00NjJiLWIwNDMtZjdiODU4ODY0ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4MTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDZjMGMwZjExM2NlNzg0MjkzYWQ0MGUzMzExNGEwOTQ2MTY1ODZiZjc1NDkwMzA3MjZiNTk1MGJlNTk2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3nar27IjPw5k7K_e5pdCbJdVQdjSf2QQ01VxLHaFVMQ) failed.

Redis uses the m.daocloud.io/docker.io/redis/redis-stack-server: latest image and deploys it in k8s using Deployment mode

**Comment by yuluo-yx** [comment]
maybe you can provide an example.
