### ISSUE TITLE
代码遗漏

### ISSUE THREAD

**Issue by zhangjiaguo** [alibaba/spring-cloud-alibaba#3775]
import com.alibaba.cloud.ai.example.tongyi.service.AbstractTongYiServiceImpl;
import com.alibaba.cloud.ai.example.tongyi.service.TongYiService;
import com.alibaba.cloud.ai.tongyi.audio.speech.api.SpeechModel;
import com.alibaba.cloud.ai.tongyi.audio.transcription.TongYiAudioTranscriptionModel;
import com.alibaba.cloud.ai.tongyi.audio.transcription.api.AudioTranscriptionPrompt;
import com.alibaba.cloud.ai.tongyi.audio.transcription.api.AudioTranscriptionResult;
springai中还有其他audio下的包也存在遗漏

**Comment by yuluo-yx** [comment]
@zhangjiaguo 遗漏是什么意思？没有更改？
