### ISSUE TITLE
show case code may contains wrong configuration

### ISSUE THREAD

**Issue by nooooorth** [alibaba/spring-cloud-alibaba#3778]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
Show case contanis wrong configuration，wrong [page](https://sca.aliyun.com/docs/2023/user-guide/ai/quick-start/)
文档演示代码错误

**Describe the bug**
See screenshot

**Simplest demo**
See screenshot

**To Reproduce**
no

**Expected behavior**
use spring.cloud.ai.tongyi.api-key

**Screenshots**
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/54655031/9a5d00ef-04e4-439b-aa9d-72068e3180bc)
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/54655031/957c59e8-02d8-46bc-8ec2-1cba5c62b004)

**Additional context**
java 17
springboot 3.0.6
spring-cloud-starter-alibaba-ai 2023.0.1.0

**Comment by yuluo-yx** [comment]
the website contentThe content of the official website is lagging behind, and will be synchronized with the code afterwards.

**Comment by nooooorth** [comment]
tks
