### ISSUE TITLE
nacos  .yaml格式文件解析属性错误

### ISSUE THREAD

**Issue by TianjinQin** [alibaba/spring-cloud-alibaba#3779]
I used springcloudalibba to build a project and used nacso as the configuration center. In the file format of nacos, which is ". yaml", I customized a configuration "com: no: 123". Java applications can obtain this configuration item, but the key parsed is "com [false]", resulting in the inability to obtain the value of "com. no". If the configuration is modified to "com: no1:123", the value can be obtained. Has the project done keyword processing on "no"

**Comment by yuluo-yx** [comment]
no, sca doesn't have a word for no.
Can you provide example to recreate it?

**Comment by TianjinQin** [comment]
maybe the configuration parsed exists bug

**Comment by yuluo-yx** [comment]
> maybe the configuration parsed exists bug

Maybe, sca just integrates with nacos, you can ask questions to the nacos community and see!
