### ISSUE TITLE
graalvm build success but run fail

### ISSUE THREAD

**Issue by mulzhang** [alibaba/spring-cloud-alibaba#3806]
**win10** 

java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14, mixed mode, sharing)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.1\plugins\maven\lib\maven3\bin\..
Java version: 17.0.8, vendor: Oracle Corporation, runtime: C:\Users\Administrator\.jdks\graalvm-jdk-17.0.8+9.1
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**pom info:**

      <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.2</spring-cloud-alibaba.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
    </parent>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

**run cmd:**
       mvn native:compile -Pnative

![image](https://github.com/user-attachments/assets/ed2d3cfe-0665-4faf-a327-163aa168293b)
![image](https://github.com/user-attachments/assets/b2b2b6f7-5ebe-4341-aefe-6cdb52bdb885)
![image](https://github.com/user-attachments/assets/b5a9db2d-aed3-4da5-818c-9242d9fa37dd)

**Comment by mulzhang** [comment]
<properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.2</spring-cloud-alibaba.version>
    </properties>

**Comment by mulzhang** [comment]
@yuluo-yx  
Is there a solution? At present, it is ruled out that there are some objects that have not implemented reflection

**Comment by mulzhang** [comment]
@yuluo-yx Found that @ RefreshScope is not effective in the application

**Comment by yuluo-yx** [comment]
maybe the question from nacos, let me check.

**Comment by yuluo-yx** [comment]
@mulzhang Can you provide an example to recurrent it?

**Comment by mulzhang** [comment]
@yuluo-yx ok let me commit code  https://github.com/mulzhang/operation-manager-native

**Comment by mulzhang** [comment]
I also noticed that @ RefreshScope is not working

**Comment by mulzhang** [comment]
I am trying to provide feedback through AI

exec: 
```
java -agentlib:native-image-agent=config-output-dir=./src/main/resources/META-INF/native-image -jar
then 
mvn --no-transfer-progress native:compile -Pnative
```
is runing ok ！！
I have reason to believe that some configuration files are missing.

**Comment by yuluo-yx** [comment]
> I am trying to provide feedback through AI
> 
> exec: java -agentlib:native-image-agent=config-output-dir=./src/main/resources/META-INF/native-image -jar then mvn --no-transfer-progress native:compile -Pnative is runing ok ！！ I have reason to believe that some configuration files are missing.

amazing,

**Comment by suhengli** [comment]
> I also noticed that @ RefreshScope is not working

https://github.com/spring-cloud/spring-cloud-release/wiki/AOT-transformations-and-native-image-support

Refresh Scope is not supported for any Spring Cloud applications in AOT and native image. The spring.cloud.refresh.enabled flag needs to be set to false。

**Comment by mulzhang** [comment]
> > 我还注意到@RefreshScope 不起作用
> 
> https://github.com/spring-cloud/spring-cloud-release/wiki/AOT-transformations-and-native-image-support
> 
> AOT 和原生镜像中的任何 Spring Cloud 应用程序均不支持 Refresh Scope。需要将 spring.cloud.refresh.enabled 标志设置为 false。

OK . You're right. This is enough to show that Java still needs a long way to go on the road of cloud native！Many excellent features cannot be used.
