### ISSUE TITLE
How Spring Cloud Stream RocketMQ Binder connect to the RocketMQ 5.x proxy ?

### ISSUE THREAD

**Issue by jluncc** [alibaba/spring-cloud-alibaba#3808]
**Which Component**

RocketMQ 5.x, Spring Cloud Stream RocketMQ Binder

**Describe what problem you have encountered**

RocketMQ 5.x use proxy replace to name-server: https://rocketmq.apache.org/zh/version/#whats-new-in-rocketmq-50,    

and if i use RocketMQ 5.x and Spring Cloud Stream ( `spring-cloud-starter-stream-rocketmq:2023.0.0.0-RC1` ) , can i connect to the RocketMQ 5.x proxy instead of name-server ?  

**Describe what information you have read**

1. i had read this doc but can not find the solution : https://github.com/alibaba/spring-cloud-alibaba/issues/3606  
2. i had read this doc but seem still connect to the RocketMQ name-server by `spring.cloud.stream.rocketmq.binder.name-server` : https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ-en

**Comment by dyrnq** [comment]
@jluncc Hi, have you found a solution?
