### ISSUE TITLE
com.alibaba.spring---->spring-context-support 1.0.11看看是否升级还是替代掉

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/spring-cloud-alibaba#3809]
spring-cloud-starter-alibaba-nacos-config
引用的albaba自己的spring-context-support版本1.0.11，其spring-context is based on Spring Framework 3.2.x ，版本太低了，漏洞很多的，请看看是升级albaba自己的spring-context-support，还是改用spring官发自己的，谢谢

            <dependency>
                <groupId>com.alibaba.spring</groupId>
                <artifactId>spring-context-support</artifactId>
                <version>${spring.context.support.version}</version>
            </dependency>

          https://github.com/alibaba/spring-context-support

**Comment by jaimyjie** [comment]
刚看了下代码好像只用到几个工具类，我尝试处理下

**Comment by jaimyjie** [comment]
我加一个工具类文件，编译时报错：Line has leading space characters; indentation should be performed with tabs only. [RegexpSinglelineJava]
用tab键去替换也是一样，同样的代码放到已有的文件中，编译就正常，是什么原因？

**Comment by yuluo-yx** [comment]
不晓得
我来试试看
