### ISSUE TITLE
[Community] Increased retirement mechanism for community-based positions

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3812]
The sca community has so many inactive contributor members that should retire.

e.g. https://github.com/envoyproxy/gateway/blob/main/OWNERS

**Comment by yuluo-yx** [comment]
cc @chickenlj @steverao @ruansheng8

**Comment by steverao** [comment]
> cc @chickenlj @steverao @ruansheng8

I think we can set some rules to do it.

**Comment by yuluo-yx** [comment]
> > cc @chickenlj @steverao @ruansheng8
> 
> I think we can set some rules to do it.

If have time, we can initiate a discussion at the next weekly meeting.
