### ISSUE TITLE
How to disable RocketMQ in the development environment?

### ISSUE THREAD

**Issue by java001** [alibaba/spring-cloud-alibaba#3815]
When I'm developing and debugging locally, I don't want to use RocketMQ. How should I configure it? It keeps giving me an error: connect to [127.0.0.1:9876] failed. It's okay if the error occurs when I send a message too.

当我在本地开发调试的时候，我不想使用rocketmq，要怎样配置？一直报错：connect to [127.0.0.1:9876] failed，当我发消息的时候再报错也可以啊。

**Comment by yuluo-yx** [comment]
？？？你是引入了 rocketmq 的依赖？然后报错了？

**Comment by java001** [comment]
> ？？？你是引入了 rocketmq 的依赖？然后报错了？

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
            <version>2022.0.0.0</version>
        </dependency>

忘了说了，我用的是这个包。可以正常用，但是我们开发的时候，公网的mq经常被攻击，就想把开发的mq端口关了，但是关了后，本地一起来就报错。没有找到关闭的配置在哪儿。

**Comment by yuluo-yx** [comment]
就是引入依赖，但是不用呗？

java001 ***@***.***>于2024年7月30日 周二18:02写道：

**Comment by java001** [comment]
就这个意思，其他环境能正常用，开发机器就屏蔽了就行。发消息报错也无所谓。能指教一二吗？

**Comment by yuluo-yx** [comment]
看下能不能把 rocketmq 相关的自动注入给 关掉
应该有一个 spring.cloud.stream.rocketmq.enable 的配置，默认是 true，改成 false 就不会注入 bean，应该不会报错

**Comment by java001** [comment]
> 看下能不能把 rocketmq 相关的自动注入给 关掉 应该有一个 spring.cloud.stream.rocketmq.enable 的配置，默认是 true，改成 false 就不会注入 bean，应该不会报错

试了这个，没生效；我这个版本有点老了，也不知道有没有真正的配置了。

**Comment by yuluo-yx** [comment]
> > 看下能不能把 rocketmq 相关的自动注入给 关掉 应该有一个 spring.cloud.stream.rocketmq.enable 的配置，默认是 true，改成 false 就不会注入 bean，应该不会报错
> 
> 试了这个，没生效；我这个版本有点老了，也不知道有没有真正的配置了。

这个东西好像不生效似的。也许是个 bug。
可以考虑下在应用启动的时候排除一些 bean，不要加载
