### ISSUE TITLE
Missing artifact org.springframework.ai:spring-ai-core:jar:1.0.0-M1

### ISSUE THREAD

**Issue by zyhyuheng** [alibaba/spring-cloud-alibaba#3818]
spring-ai-core maven仓库已转移

**Comment by yuluo-yx** [comment]
so?

**Comment by yuluo-yx** [comment]
![image](https://github.com/user-attachments/assets/e9dba978-0941-4395-9ca0-74573db68008)

![image](https://github.com/user-attachments/assets/d55b863b-8cfa-4ff0-9e39-89fa4920aff0)

? @zyhyuheng
