### ISSUE TITLE
[Task] Convert the properties configuration file in example to yml type.

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3819]
e.g. https://github.com/alibaba/spring-cloud-alibaba/tree/2023.x/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/src/main/resources

**Comment by jieefeng** [comment]
HI，do all properties in the example have to be converted to yml?

**Comment by yuluo-yx** [comment]
> HI，do all properties in the example have to be converted to yml?

yep

**Comment by jieefeng** [comment]
> > HI，do all properties in the example have to be converted to yml?嗨，示例中的所有属性都必须转换为yml吗？
> 
> yep 是的

After this issue is resolved, can I upload it to Alibaba Cloud's Tianchi Competition?

**Comment by yuluo-yx** [comment]
> After this issue is resolved, can I upload it to Alibaba Cloud's Tianchi Competition?

sorry, I`m not sure, I'll go ask.

**Comment by jieefeng** [comment]
> > After this issue is resolved, can I upload it to Alibaba Cloud's Tianchi Competition?解决该问题后，我可以上传到阿里云的天池竞赛吗？
> 
> sorry, I`m not sure, I'll go ask.对不起，我不确定，我会去问。

thanks

**Comment by yuluo-yx** [comment]
@jieefeng hi, sca did not participate in this Tenchi competition, but did participate in the Tongyi Spirit Code. Regardless, any kind of contribution from our community
