### ISSUE TITLE
[New Feat] If sca website need AOS animations for enhanced scroll effects .I can try to pull request

### ISSUE THREAD

**Issue by LofiSu** [alibaba/spring-cloud-alibaba#3822]
Add AOS animations

Integrated AOS (Animate On Scroll) library
Applied animations to various sections of the site
Improved user experience with smooth scroll effects
just like:
https://streampark.apache.org/zh-CN/
https://[michalsnik.github.io](https://michalsnik.github.io/aos/)/aos/

**Comment by yuluo-yx** [comment]
Amazing, I'll be talking to other community members about that.

**Comment by LofiSu** [comment]
> Amazing, I'll be talking to other community members about that.

Can you give me a link to the official website code repository?

**Comment by yuluo-yx** [comment]
> > Amazing, I'll be talking to other community members about that.
> 
> Can you give me a link to the official website code repository?

you can see: https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io
