### ISSUE TITLE
recommended that the wiki page of the release notes be updated

### ISSUE THREAD

**Issue by pci-rain** [alibaba/spring-cloud-alibaba#3834]
It is suggested to add the version dependency of 2023.x branch.
wiki page url:
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by yuluo-yx** [comment]
The documentation has been migrated to the official website, please see: https://sca.aliyun.com/docs/2023/overview/what-is-sca/?spm=5176.29160081.0.0.74801d28aBMsVk
