### ISSUE TITLE
 How to pass the user information obtained in the gateway to the sub-service elegantly

### ISSUE THREAD

**Issue by ranLee1** [alibaba/spring-cloud-alibaba#3838]
**Which Component**
```bash
spring-cloud-alibaba: 2022.0.0.0
dubbo: 3.2.10
```

**Describe what problem you have encountered**
I have a springcloud alibaba project, which references gateway and dubbo services. I am now facing a business implementation problem. How should I deal with it? Problem description: How to pass the user information obtained in the gateway to the sub-service elegantly? In addition to using link tracking, can the dubbo context be used to achieve this effect, as shown below:

我有一个springcloud alibaba项目，其中引用了gateway，dubbo服务，我现在遇到一个业务实现问题，请问我应该如何处理。问题描述：
如何让gateway中获取到的用户信息优雅的传递给子服务，除了采用链路追踪的方式以外，能否使用dubbo上下文实现该效果，如下图：

![image](https://github.com/user-attachments/assets/ddbc86a6-12df-4f38-9317-2bad553aba45)

I wrote a test project and tried to use dubbo in the gateway to get user information and then pass it to the sub-service, but it failed. Can you help me fix this problem? If it is not recommended or there is a better implementation method, please point it out. Thank you!

我写了一个测试项目，尝试在网关使用dubbo获取到用户信息然后在传递给子服务，但是失败了，您可以帮助我修复这个问题吗，如果不建议这么做或者有更好的实现方法，请指出，谢谢！

 [Test project address](https://github.com/ranLee1/dubbo-demo)
**Describe what information you have read**
I have read the reference doc of Dubbo

**Comment by ruansheng8** [comment]
- Dubbo 使用 `RpcContext` 来传递。
参考：https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/service/attachment/

- Http 使用请求头来传递
参考：
```
@Component
public class TestGatewayFilter implements GlobalFilter {
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        request.mutate().header("xxx", "xxx");        
        return chain.filter(exchange);
    }
}
```

**Comment by ranLee1** [comment]
@ruansheng8 Thanks for your reply. I tried to use dubbo for contextual parameter passing, but it didn't work. Can you help me modify this [Test project address](https://github.com/ranLee1/dubbo-demo) project? If it's convenient, please put a payment. I'm willing to ask for paid advice. Thank you!

感谢您的回复，我尝试使用dubbo进行上下文传参，但是没能实现，您能帮助我修改下这个[Test project address](https://github.com/ranLee1/dubbo-demo)项目吗？方便的话放个收款，愿意有偿请教，谢谢！

**Comment by ruansheng8** [comment]
@ranLee1 简单看了下你的代码，主要问题在于你使用 Dubbo 获取权限信息后，将权限信息设置在了 Dubbo 的 RPC 上下文中，但是转发到其他服务的时候使用的是 HTTP 转发，这两个上下文肯定是隔离的，信息不会共享，使用 HTTP 转发时，你需要将对应的上下文信息设置到请求头才行，参考上面给的 HTTP 请求头设置方式

**Comment by ranLee1** [comment]
明白，感谢解惑，方便放收款码吗？请你喝杯咖啡！

**Comment by ruansheng8** [comment]
> 明白，感谢解惑，方便放收款码吗？请你喝杯咖啡！

哈哈，不用，开源社区都是用爱发电
