### ISSUE TITLE
open redirect on sign in 

### ISSUE THREAD

**Issue by kurdhrr1** [alibaba/spring-cloud-alibaba#3841]

**Comment by yuluo-yx** [comment]
This seems to be not related to this project. We have already reported it to Alibaba. You can try to raise an Alibaba ticket.

**Comment by chickenlj** [comment]
@kurdhrr1 Please report to our dedicated mailing list, I have deleted the details from this issue.

**Comment by kurdhrr1** [comment]
This email is valid??? security@service.alibaba.com

Already i sent report to this email
But no one has answered

**Comment by yuluo-yx** [comment]
> This email is valid??? [security@service.alibaba.com](mailto:security@service.alibaba.com)
> 
> Already i sent report to this email But no one has answered

This bug has been reported to the security team

**Comment by kurdhrr1** [comment]
Can you show me the report ??
when the bug is sent ???

**Comment by yuluo-yx** [comment]
> Can you show me the report ?? when the bug is sent ???

cc @chickenlj

**Comment by kurdhrr1** [comment]
Sorry but can you send me the url report i cant find it

**Comment by yuluo-yx** [comment]
I am just the maintainer of the spring cloud alibaba project. This issue has nothing to do with this project, and this security issue has been reported to the security team. Finally, security issues should not be discussed in public issue lists. If you have any other questions, you can initiate a work order, or directly contact the relevant person in charge of Alibaba. I don’t know the things you asked.

> Sorry but can you send me the url report i cant find it
