### ISSUE TITLE
spring-cloud-alibaba-sentinel-zuul shows 404

### ISSUE THREAD

**Issue by zengwenliang416** [alibaba/spring-cloud-alibaba#3849]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**
Sentinel

**Describe what problem you have encountered**
I'm trying to integrate the sentinel component in zuul and find that I can't do it in the same way as spring cloud gateway. spring cloud gateway works like this: https://github.com/karl-chanel/sentinel-prometheus- The documentation states “If you are using Spring Cloud Zuul Starter, you can make it easier to integrate Sentinel by introducing spring-cloud-alibaba-sentinel-zuul”. But accessing spring-cloud-alibaba-sentinel-zuul reports an error 404.

Translated with DeepL.com (free version)
**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuluo-yx** [comment]
提供个 example 或者相信配置信息

**Comment by zengwenliang416** [comment]
> 提供个 example 或者相信配置信息

目前通过配置依赖版本解决了。
