### ISSUE TITLE
 是否需要取消maven插件Javadoc？

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/spring-cloud-alibaba#3852]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

很多方法都没有注释参数，导致Javadoc生成很多问题，这种Javadoc是否有意义？是否需要取消？

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by yuluo-yx** [comment]
就目前来说，存在是有意义的，之前有 good first issue 提出对项目代码添加注释，一直没人认领，进度比较慢

**Comment by jaimyjie** [comment]
> 就目前来说，存在是有意义的，之前有 good first issue 提出对项目代码添加注释，一直没人认领，进度比较慢

我边熟悉代码边补充下吧

**Comment by yuluo-yx** [comment]
可以哇，欢迎贡献，社区很缺人🤗

jaimyjie ***@***.***>于2024年9月19日 周四18:04写道：
