### ISSUE TITLE
[Nacos Config] config[dataId=apu-gateway-prod.yaml, group=PROD] is empty

### ISSUE THREAD

**Issue by UpdateCw** [alibaba/spring-cloud-alibaba#3855]
启动报错，nacos能正常访问，请各位大佬帮忙看看呢。
![image](https://github.com/user-attachments/assets/fa2c88b6-7ce7-4958-a410-f59946a91590)
读取不到配置
![image](https://github.com/user-attachments/assets/7ab56984-80dc-4664-bf32-b13517906ad0)

springBoot 2.6.13
springCloudAlibaba 2021.0.5.0

**Comment by yuluo-yx** [comment]
给个复现例子
