### ISSUE TITLE
Nacos configuration cannot automatically refresh in specific scenarios.

### ISSUE THREAD

**Issue by sunl888** [alibaba/spring-cloud-alibaba#3859]
**Which Component**
`spring-cloud-starter-alibaba-nacos-config` component

**Describe the bug**
When I tried to get the app configuration in the bean, I found that it was not the latest value. Even if I updated it from nacos, I could only get the old value. At first, I suspected that @ RefreshScope was not effective, but after experimentation, I found out that it was not the case. This only happened when I used webService at the same time. Is there any difference between webService beans and regular beans? In theory, nacos should destroy the eConfig bean and recreate it when it listens for configuration changes.

**Simplest demo**
[This is a testing project.](https://github.com/sunl888/nacos-sync)

**To Reproduce**
1. Start a temporary `Nacos server`
2. Create a yml configuration
3. Configure the `nacos server` address and other information for the `application.yml` file of the project
4. Start the project
5. Call `http://localhost:8088/config` Address
6. Observe the configuration information output by the console
7. Modify the configuration on Nacos and re execute steps 5 and 6
8. At this point, it will be found that the configuration that has not been updated has not been output

**Expected behavior**
In theory, the configuration obtained through the service interface after modifying the configuration on the Nacos server should be the latest.

**Screenshots**
0. Initial nacos configuration value
<img width="996" alt="截屏2024-09-24 23 23 29" src="https://github.com/user-attachments/assets/e8523c3a-461d-41c6-b3bd-a94c30c5d360">

1. this is the first time calling
<img width="1335" alt="截屏2024-09-24 23 17 39" src="https://github.com/user-attachments/assets/85954cab-1047-498d-8ec4-a65c9f4f8e4f">

2. modified nacos configuration values.
<img width="1071" alt="截屏2024-09-24 23 22 07" src="https://github.com/user-attachments/assets/0ab417ef-f6d8-4cb4-8363-fe50ca187b95">

3. this is the second call 
<img width="1373" alt="截屏2024-09-24 23 21 13" src="https://github.com/user-attachments/assets/e5260a0e-00fe-4135-9379-ac6e8c330107">

**Additional context** 
OS: MacOS
JDK: Java17
spring-cloud-starter-alibaba-nacos-config: 2023.0.1.2
cxf-spring-boot-starter-jaxws: 4.0.5
spring-boot-starter-web: 3.2.10

**Comment by sunl888** [comment]
looking forward to your reply very much.

**Comment by misakacoder** [comment]
当类使用了@RefreshScope后在容器中会有2个bean，apache cxf在处理Resource注解时，默认获取的是第一个bean，也就是图中的scopedTarget开头的bean，这个bean是原始bean，所以无法获取刷新后的配置，可以将TestWebServiceImpl中的Resource改为Resource(name = "appConfig")或者Autowired，这样2个地方就都会刷新配置了

![image](https://github.com/user-attachments/assets/18b2a877-472f-40d3-8399-11d38667d1ba)

![image](https://github.com/user-attachments/assets/c6c8fb58-3d2b-45f3-bf2d-8688ca7a0c0a)

**Comment by sunl888** [comment]
> 当类使用了@RefreshScope后在容器中会有2个bean，apache cxf在处理Resource注解时，默认获取的是第一个bean，也就是图中的scopedTarget开头的bean，这个bean是原始bean，所以无法获取刷新后的配置，可以将TestWebServiceImpl中的Resource改为Resource(name = "appConfig")或者Autowired，这样2个地方就都会刷新配置了
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/371047798-18b2a877-472f-40d3-8399-11d38667d1ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDExNTAsIm5iZiI6MTcyNzM0MDg1MCwicGF0aCI6Ii8zNjI1MjkzNy8zNzEwNDc3OTgtMThiMmE4NzctNDcyZi00MGQzLTgzOTktMTFkMzg2NjdkMWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZGQ0MTQ2ZGFlOTVmYWUxYTFjMTE1MjE5MTcyNWYxNjQwMmIwOTVmZjk3YTM3ZGZmNTMxZDQxNGVlZjE3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PrwUcE3Ap8lsgk3aQ79FHAEqKEb2okbRMsgadBgAPXg)
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/371048412-c6c8fb58-3d2b-45f3-bf2d-8688ca7a0c0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDExNTAsIm5iZiI6MTcyNzM0MDg1MCwicGF0aCI6Ii8zNjI1MjkzNy8zNzEwNDg0MTItYzZjOGZiNTgtM2QyYi00NWYzLWJmMmQtODY4OGNhN2EwYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTZjZjk5NzU0ZTU2NzAxNTg5ODI4Y2Y5OWQ1YmZiMDY1YjgwMjcwOTY1ZjgxODkwNzAzOTAwOTM0Njk3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gcM7U7nyXImuGtSTwjpXXhqEJI2cxgHUwsV2kRYVE4Q)

哇，谢谢大佬告知，我试一下看看

**Comment by sunl888** [comment]
> 当类使用了@RefreshScope后在容器中会有2个bean，apache cxf在处理Resource注解时，默认获取的是第一个bean，也就是图中的scopedTarget开头的bean，这个bean是原始bean，所以无法获取刷新后的配置，可以将TestWebServiceImpl中的Resource改为Resource(name = "appConfig")或者Autowired，这样2个地方就都会刷新配置了
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/371047798-18b2a877-472f-40d3-8399-11d38667d1ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDExNTAsIm5iZiI6MTcyNzM0MDg1MCwicGF0aCI6Ii8zNjI1MjkzNy8zNzEwNDc3OTgtMThiMmE4NzctNDcyZi00MGQzLTgzOTktMTFkMzg2NjdkMWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZGQ0MTQ2ZGFlOTVmYWUxYTFjMTE1MjE5MTcyNWYxNjQwMmIwOTVmZjk3YTM3ZGZmNTMxZDQxNGVlZjE3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PrwUcE3Ap8lsgk3aQ79FHAEqKEb2okbRMsgadBgAPXg)
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/371048412-c6c8fb58-3d2b-45f3-bf2d-8688ca7a0c0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDExNTAsIm5iZiI6MTcyNzM0MDg1MCwicGF0aCI6Ii8zNjI1MjkzNy8zNzEwNDg0MTItYzZjOGZiNTgtM2QyYi00NWYzLWJmMmQtODY4OGNhN2EwYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTZjZjk5NzU0ZTU2NzAxNTg5ODI4Y2Y5OWQ1YmZiMDY1YjgwMjcwOTY1ZjgxODkwNzAzOTAwOTM0Njk3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gcM7U7nyXImuGtSTwjpXXhqEJI2cxgHUwsV2kRYVE4Q)

我改为了@Resource(name = "appConfig")，果然可以了，非常感谢兄弟指导

**Comment by misakacoder** [comment]
不客气

**Comment by sunl888** [comment]
> 不客气

还有个问题想请教一下大佬，请问 **apache cxf处理Resource注解** 的逻辑在哪个包里呢，我之前也调试了一段时间，也发现了会注册两个bean，但是因为没看到您标记的这段逻辑，所以没想到会是这个导致的。想跟大佬学习一下这个调试方法，下次遇到这个问题就会了

**Comment by misakacoder** [comment]
这个是入口

![image](https://github.com/user-attachments/assets/d1867fd1-4ee0-4ed5-996f-027e58c537e5)

代码方法调用的顺序
org.apache.cxf.jaxws.EndpointImpl#getServer(java.lang.String)
org.apache.cxf.jaxws.JaxWsServerFactoryBean#create
org.apache.cxf.jaxws.JaxWsServerFactoryBean#initializeResourcesAndHandlerChain
org.apache.cxf.jaxws.JaxWsServerFactoryBean#injectResources
org.apache.cxf.common.injection.ResourceInjector#inject(java.lang.Object, java.lang.Class<?>)
org.apache.cxf.common.annotation.AnnotationProcessor#processFields
org.apache.cxf.common.injection.ResourceInjector#visitField
org.apache.cxf.bus.spring.BusApplicationContextResourceResolver#resolve

**Comment by sunl888** [comment]
> 这个是入口
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/371071803-d1867fd1-4ee0-4ed5-996f-027e58c537e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDM0ODMsIm5iZiI6MTcyNzM0MzE4MywicGF0aCI6Ii8zNjI1MjkzNy8zNzEwNzE4MDMtZDE4NjdmZDEtNGVlMC00ZWQ1LTk5NmYtMDI3ZTU4YzUzN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMGMzYTlmNzg0NGExMTQwNjdjMDdlYmFjZGE0OWI2OTNhZTZhMDYwOGYzNjZhZGY5Mjc5ZjcxNmJiY2EzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EBQks2W1usVzhPfWCddFnIUdPytSfy8m3RbYPDYtZT4)
> 
> 代码方法调用的顺序 org.apache.cxf.jaxws.EndpointImpl#getServer(java.lang.String) org.apache.cxf.jaxws.JaxWsServerFactoryBean#create org.apache.cxf.jaxws.JaxWsServerFactoryBean#initializeResourcesAndHandlerChain org.apache.cxf.jaxws.JaxWsServerFactoryBean#injectResources org.apache.cxf.common.injection.ResourceInjector#inject(java.lang.Object, java.lang.Class<?>) org.apache.cxf.common.annotation.AnnotationProcessor#processFields org.apache.cxf.common.injection.ResourceInjector#visitField org.apache.cxf.bus.spring.BusApplicationContextResourceResolver#resolve

太强了，学习到了，跟着大佬给的这个入口走下去也发现了，这个bug相关的知识总算串联起来了，太感谢大佬啦 :^^:

**Comment by sunl888** [comment]
> 这个是入口
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/371071803-d1867fd1-4ee0-4ed5-996f-027e58c537e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDM0ODMsIm5iZiI6MTcyNzM0MzE4MywicGF0aCI6Ii8zNjI1MjkzNy8zNzEwNzE4MDMtZDE4NjdmZDEtNGVlMC00ZWQ1LTk5NmYtMDI3ZTU4YzUzN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMGMzYTlmNzg0NGExMTQwNjdjMDdlYmFjZGE0OWI2OTNhZTZhMDYwOGYzNjZhZGY5Mjc5ZjcxNmJiY2EzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EBQks2W1usVzhPfWCddFnIUdPytSfy8m3RbYPDYtZT4)
> 
> 代码方法调用的顺序 org.apache.cxf.jaxws.EndpointImpl#getServer(java.lang.String) org.apache.cxf.jaxws.JaxWsServerFactoryBean#create org.apache.cxf.jaxws.JaxWsServerFactoryBean#initializeResourcesAndHandlerChain org.apache.cxf.jaxws.JaxWsServerFactoryBean#injectResources org.apache.cxf.common.injection.ResourceInjector#inject(java.lang.Object, java.lang.Class<?>) org.apache.cxf.common.annotation.AnnotationProcessor#processFields org.apache.cxf.common.injection.ResourceInjector#visitField org.apache.cxf.bus.spring.BusApplicationContextResourceResolver#resolve

太强了，学习到了，跟着大佬给的这个入口走下去也发现了，这个bug相关的知识总算串联起来了，太感谢大佬啦 :^^:

**Comment by misakacoder** [comment]
哈哈，客气了，都是在学习中

**Comment by sunl888** [comment]
> 客气了，都是

嘿嘿，大佬 这个issue我就关闭了哈 ^^
