### ISSUE TITLE
Is it normal that the service can be started normally without exception when using the wrong address?

### ISSUE THREAD

**Issue by youngledo** [alibaba/spring-cloud-alibaba#3860]
**Which Component**
Nacos

**Describe the bug**
- Bad server address
![image](https://github.com/user-attachments/assets/55031030-44b1-4683-b243-15a7f92c6858)
![image](https://github.com/user-attachments/assets/17991186-5aef-4362-a37d-e30b3e458ddf)

- Good server address
![image](https://github.com/user-attachments/assets/c911898e-c022-4ff9-890f-c6187a20967a)

**Simplest demo**
[demo.zip](https://github.com/user-attachments/files/17135275/demo.zip)

**Additional**
```shell
docker run --env PREFER_HOST_MODE=hostname   --env MODE=standalone   --env NACOS_AUTH_ENABLE=true   -e NACOS_AUTH_TOKEN=SecretKeyM1Z2WDc4dnVyZkQ3NmZMZjZ3RHRwZnJjNFROdkJOemEK   -e NACOS_AUTH_IDENTITY_KEY=nacos   -e NACOS_AUTH_IDENTITY_VALUE=nacos   -p 8848:8848 -p 9848:9848 --name nacos nacos/nacos-server
```

This should be a bug in the low version (2021.0.5.0), and an exception will be thrown in the high version (2023.0.1.0).

**Comment by yuluo-yx** [comment]
最新版本应该处理过了，你可以切到最新版本试试
