### ISSUE TITLE
All the `spring.cloud.stream.function.definition` in the RocketMQ examples should be `spring.cloud.stream.definition`

### ISSUE THREAD

**Issue by Camio1945** [alibaba/spring-cloud-alibaba#3861]
Based on this log:
```
WARN 4864 --- [order] [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : 
Multiple functional beans were found [replenishStockConsumer, consumer], 
thus can't determine default function definition. 
Please use 'spring.cloud.function.definition' property to explicitly define it. 
```
all the `spring.cloud.stream.function.definition` in the RocketMQ examples should be `spring.cloud.stream.definition`.

The examples don't get the warning above, because there is only one consumer in each example.

**Comment by limng06** [comment]
pls check the title, it should be "spring.cloud.function.definition" .   it works with multi functions
