### ISSUE TITLE
关于Spring Boot(3.2.4)及Spring Cloud(2023.0.1)出现的漏洞采用升级方式，升级后alibaba技术体系没有对应版本的问题

### ISSUE THREAD

**Issue by Tea-Zhi** [alibaba/spring-cloud-alibaba#3869]
版本关系：
spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0

目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？

**Comment by yuluo-yx** [comment]
在小版本范围内使用应该没有什么问题 你可以本地替换试试

**Comment by Tea-Zhi** [comment]
> 在小版本范围内使用应该没有什么问题 你可以本地替换试试

好的

**Comment by jaimyjie** [comment]
> 版本关系： spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0
> 
> 目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？

可以本地升级大胆用，我已经升级到最新版本，没有什么问题

**Comment by Tea-Zhi** [comment]
> > 版本关系： spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0
> > 目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？
> 
> 可以本地升级大胆用，我已经升级到最新版本，没有什么问题

好的，感谢

**Comment by herodotus-ecosystem** [comment]
> > > 版本关系： spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0
> > > 目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？
> > 
> > 
> > 可以本地升级大胆用，我已经升级到最新版本，没有什么问题
> 
> 好的，感谢

3.2 及后面的版本没有像 3.1，3.0 那么大的破坏性变化，仅有变化就是 Spring Boot 3.2 绑定 Spring Cloud 2023。如果都已经使用了  Spring Boot 3.2 和 Spring Cloud 2023，后面的版本尽管升级就行了。我已经升到 Spring Boot 3.3.5 + Spring Cloud 2023.0.3 + Spring Cloud Alibaba 2023.0.1.3。

**Comment by Comven** [comment]
> > > > 版本关系： spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0
> > > > 目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？
> > > 
> > > 
> > > 可以本地升级大胆用，我已经升级到最新版本，没有什么问题
> > 
> > 
> > 好的，感谢
> 
> 3.2 及后面的版本没有像 3.1，3.0 那么大的破坏性变化，仅有变化就是 Spring Boot 3.2 绑定 Spring Cloud 2023。如果都已经使用了 Spring Boot 3.2 和 Spring Cloud 2023，后面的版本尽管升级就行了。我已经升到 Spring Boot 3.3.5 + Spring Cloud 2023.0.3 + Spring Cloud Alibaba 2023.0.1.3。

为什么我们尝试升级到Spring Cloud Alibaba 2023.0.1.3之后，无法从配置中心拉取配置文件内容了，nacos中内容变更发布后再程序这一侧也没有任何反应

**Comment by herodotus-ecosystem** [comment]
> > > > > 版本关系： spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0
> > > > > 目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？
> > > > 
> > > > 
> > > > 可以本地升级大胆用，我已经升级到最新版本，没有什么问题
> > > 
> > > 
> > > 好的，感谢
> > 
> > 
> > 3.2 及后面的版本没有像 3.1，3.0 那么大的破坏性变化，仅有变化就是 Spring Boot 3.2 绑定 Spring Cloud 2023。如果都已经使用了 Spring Boot 3.2 和 Spring Cloud 2023，后面的版本尽管升级就行了。我已经升到 Spring Boot 3.3.5 + Spring Cloud 2023.0.3 + Spring Cloud Alibaba 2023.0.1.3。
> 
> 为什么我们尝试升级到Spring Cloud Alibaba 2023.0.1.3之后，无法从配置中心拉取配置文件内容了，nacos中内容变更发布后再程序这一侧也没有任何反应

是我手误写错了，是 Spring Cloud Alibaba 2023.0.1.2。我发信息的时候 2023.0.1.3 还没有发。2023.0.1.3 试过确实无法拉取配置信息。看这个 ISSUE #3877

**Comment by herodotus-ecosystem** [comment]
> > > > > 版本关系： spring boot:3.2.4；spring cloud:2023.0.1 spring cloud alibaba:2023.0.1.0
> > > > > 目前spring boot 3.2.4及spring cloud 2023.0.1版本存在安全漏洞，如果我要解决需要升级spring boot和spring cloud 的版本，而spring cloud alibaba并没有与之对应的升级版本，要解决这个安全漏洞问题会出现版本差异，这个有什么要解决方案吗？
> > > > 
> > > > 
> > > > 可以本地升级大胆用，我已经升级到最新版本，没有什么问题
> > > 
> > > 
> > > 好的，感谢
> > 
> > 
> > 3.2 及后面的版本没有像 3.1，3.0 那么大的破坏性变化，仅有变化就是 Spring Boot 3.2 绑定 Spring Cloud 2023。如果都已经使用了 Spring Boot 3.2 和 Spring Cloud 2023，后面的版本尽管升级就行了。我已经升到 Spring Boot 3.3.5 + Spring Cloud 2023.0.3 + Spring Cloud Alibaba 2023.0.1.3。
> 
> 为什么我们尝试升级到Spring Cloud Alibaba 2023.0.1.3之后，无法从配置中心拉取配置文件内容了，nacos中内容变更发布后再程序这一侧也没有任何反应

2023.0.1.3 应该是这个问题导致 #3878
