### ISSUE TITLE
spring cloud alibaba 2023.0.1.3 无法读取读取配置文件

### ISSUE THREAD

**Issue by KouShenhai** [alibaba/spring-cloud-alibaba#3874]
**Describe the bug**
![image](https://github.com/user-attachments/assets/b665ed7c-13b4-446a-be6d-fef3775074ba)

**Additional context**
jdk21

**Comment by OctoberSouth** [comment]
真是麻雀嘬了牛屁股

**Comment by caoliang1918** [comment]
从2023.0.1.2版本升级到2023.0.1.3版本，也出现了无法读取到nacos的配置，nacos版本是2.3.2

**Comment by KouShenhai** [comment]
> 从2023.0.1.2版本升级到2023.0.1.3版本，也出现了无法读取到nacos的配置，nacos版本是2.3.2

哥们，我sca 2023.0.1.2可以读取nacos，最新版的sca有问题，他们分离spring.cloud.nacos.config的配置，导致出现问题

**Comment by KouShenhai** [comment]
> > 从2023.0.1.2版本升级到2023.0.1.3版本，也出现了无法读取到nacos的配置，nacos版本是2.3.2
> 
> 哥们，我sca 2023.0.1.2可以读取nacos，最新版的sca有问题，他们分离spring.cloud.nacos.config的配置，导致出现问题

我这个sca 2023.0.1.2已经跑在生产啦，没有什么问题

**Comment by jaimyjie** [comment]
看看最新的配置文件格式，早就换了，如：
![WechatIMG86](https://github.com/user-attachments/assets/374413bd-9ab7-40f0-920c-70546382c044)

**Comment by KouShenhai** [comment]
> 看看最新的配置文件格式，早就换了，如： ![WechatIMG86](https://private-user-images.githubusercontent.com/50560855/381040173-374413bd-9ab7-40f0-920c-70546382c044.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTEwNTIsIm5iZiI6MTczMDE5MDc1MiwicGF0aCI6Ii81MDU2MDg1NS8zODEwNDAxNzMtMzc0NDEzYmQtOWFiNy00MGYwLTkyMGMtNzA1NDYzODJjMDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTkzZDQ3ZDYyOGIzMTMxZmJmZTdmMWQ0ZWFkNzk2NWZkYWE0ZmQ2ZTE2OWZhMzA3N2UyZDUxMjgzMDU0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tJ0JHnXkvHcx-wRw9N1X5BOM6CEoPrfDlhDjRA56-V0)

是无法读取group，namespace这些

**Comment by jaimyjie** [comment]
> > 看看最新的配置文件格式，早就换了，如： ![WechatIMG86](https://private-user-images.githubusercontent.com/50560855/381040173-374413bd-9ab7-40f0-920c-70546382c044.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTEwNTIsIm5iZiI6MTczMDE5MDc1MiwicGF0aCI6Ii81MDU2MDg1NS8zODEwNDAxNzMtMzc0NDEzYmQtOWFiNy00MGYwLTkyMGMtNzA1NDYzODJjMDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTkzZDQ3ZDYyOGIzMTMxZmJmZTdmMWQ0ZWFkNzk2NWZkYWE0ZmQ2ZTE2OWZhMzA3N2UyZDUxMjgzMDU0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tJ0JHnXkvHcx-wRw9N1X5BOM6CEoPrfDlhDjRA56-V0)
> 
> 是无法读取group，namespace这些

读取不到group，namespace变量值？

**Comment by KouShenhai** [comment]
> > > 看看最新的配置文件格式，早就换了，如： ![WechatIMG86](https://private-user-images.githubusercontent.com/50560855/381040173-374413bd-9ab7-40f0-920c-70546382c044.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTEwNTIsIm5iZiI6MTczMDE5MDc1MiwicGF0aCI6Ii81MDU2MDg1NS8zODEwNDAxNzMtMzc0NDEzYmQtOWFiNy00MGYwLTkyMGMtNzA1NDYzODJjMDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTkzZDQ3ZDYyOGIzMTMxZmJmZTdmMWQ0ZWFkNzk2NWZkYWE0ZmQ2ZTE2OWZhMzA3N2UyZDUxMjgzMDU0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tJ0JHnXkvHcx-wRw9N1X5BOM6CEoPrfDlhDjRA56-V0)
> > 
> > 
> > 是无法读取group，namespace这些
> 
> 读取不到group，namespace变量值？

升级最新版的sca，无法读取配置

**Comment by jaimyjie** [comment]
> > > > 看看最新的配置文件格式，早就换了，如： ![WechatIMG86](https://private-user-images.githubusercontent.com/50560855/381040173-374413bd-9ab7-40f0-920c-70546382c044.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTEwNTIsIm5iZiI6MTczMDE5MDc1MiwicGF0aCI6Ii81MDU2MDg1NS8zODEwNDAxNzMtMzc0NDEzYmQtOWFiNy00MGYwLTkyMGMtNzA1NDYzODJjMDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTkzZDQ3ZDYyOGIzMTMxZmJmZTdmMWQ0ZWFkNzk2NWZkYWE0ZmQ2ZTE2OWZhMzA3N2UyZDUxMjgzMDU0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tJ0JHnXkvHcx-wRw9N1X5BOM6CEoPrfDlhDjRA56-V0)
> > > 
> > > 
> > > 是无法读取group，namespace这些
> > 
> > 
> > 读取不到group，namespace变量值？
> 
> 升级最新版的sca，无法读取配置

看看能不能发个简单demo出来看看

我用私用包（nacos. 2.4.3, spring boot 3.3.5, JDK 21），也是基于2023.0.1.3代码，丝滑升级到生产环境了.

**Comment by yuluo-yx** [comment]
@KouShenhai 给个复现的简易 example 我本地试试看

**Comment by KouShenhai** [comment]
> @KouShenhai 给个复现的简易 example 我本地试试看

我先改一改吧，如果有问题，我再搞一个例子

**Comment by yuluo-yx** [comment]
> 我先改一改吧，如果有问题，我再搞一个例子

https://github.com/alibaba/spring-cloud-alibaba/pull/3871/files 这次的版本发布对 nacos config 做了一些更改，一些使用方式可能需要变更下

**Comment by KouShenhai** [comment]
> > 我先改一改吧，如果有问题，我再搞一个例子
> 
> https://github.com/alibaba/spring-cloud-alibaba/pull/3871/files 这次的版本发布对 nacos config 做了一些更改，一些使用方式可能需要变更下
@jaimyjie @yuluo-yx 

ok，谢谢，问题解决了，但是有一些nacos配置的提示信息缺失，我提交了一个pr #3875
