### ISSUE TITLE
After attempting the upgrade of springcloud-alibaba-2023.0.1.3, the configuration center function is not available

### ISSUE THREAD

**Issue by Comven** [alibaba/spring-cloud-alibaba#3876]
The normal version is spring-cloud-2023.0.3+spring-boot-3.2.11+spring-cloud-alibaba-2023.0.1.2 or spring-cloud-2023.0.3+spring-boot-3.3.5+spring-cloud-alibaba-2023.0.1.2

The abnormal version is spring-cloud-2023.0.3+spring-boot-3.2.11+spring-cloud-alibaba-2023.0.1.3 or spring-cloud-2023.0.3+spring-boot-3.3.5+spring-cloud-alibaba-2023.0.1.3

The logs under normal circumstances are as follows
![正常情况nacos-config日志](https://github.com/user-attachments/assets/736fbe06-3670-494a-930c-663c4ba2a798)

The logs of abnormal situations are as follows
![异常情况nacos-config日志](https://github.com/user-attachments/assets/b718bf56-dfb7-486f-a93b-37458f9d9bdf)

By comparison, there are no startup logs related to nacos config in version 2023.0.1.3

**Comment by herodotus-ecosystem** [comment]
猜测是这个问题导致的 #3878

**Comment by chickenlj** [comment]
@Comven Could you please provide more information for us to reproduce:
1. configuration details in your application.yaml or application.properties
2. the code snippet you use to get nacos config data

**Comment by chickenlj** [comment]
The log screenshot you given here is expected. The missing logs actually belong to nacos-client and has been logged to the logging files of nacos-client in the new version.

**Comment by Comven** [comment]
Finally, the following configuration was successfully set up in bootstrap
````
spring.config.import[0]=nacos:${spring.application.name}
spring.config.import[1]=nacos:${spring.application.name}.properties
````
The 2023.0.1.3 version no longer supports pulling and configuring default names, which feels like there are more configurations. If each program uses the configuration center, it must configure this parameter.

Additionally, this prompt issue still needs to be resolved

![image](https://github.com/user-attachments/assets/aeeee816-2eaf-491e-8863-a0a54f35359f)
