### ISSUE TITLE
Failed to obtain nacos information after upgrading to 2023.0.1.3

### ISSUE THREAD

**Issue by jfly-cloud** [alibaba/spring-cloud-alibaba#3877]
**Which Component**
 Nacos config

**Describe the bug**
After upgrading to 2023.0.1.3, the namespace and group under nacos config cannot be configured, causing failure to obtain nacos configuration information.

**Screenshots**
![image](https://github.com/user-attachments/assets/ee4ea4ed-b316-4908-8016-ee998814aecc)

**Additional context**
 MacOS  、Java21 、 Version 2023.0.1.3

**Comment by jfly-cloud** [comment]
![image](https://github.com/user-attachments/assets/5e591436-43ce-4f56-afb1-1cfe53233f8e)

**Comment by herodotus-ecosystem** [comment]
难说是这个问题导致的 #3878

**Comment by chickenlj** [comment]
@jfly-cloud Could you please provide more details.

Do you have `spring.config.import` specified? 

`causing failure to obtain nacos configuration information.` What's the exact failure? How do you use nacos config to get the new value?

**Comment by chickenlj** [comment]
Would be great if you can provide a demo that can reproduce the issue

**Comment by yuluo-yx** [comment]
@jfly-cloud you can first refer to the documentation to compare whether the configuration file is correct.

**Comment by jfly-cloud** [comment]
If I upgrade to 2023.0.1.3, spring.cloud.nacos.config.namespace and spring.cloud.nacos.config.group no longer take effect, please check.

**Comment by yuluo-yx** [comment]
> If I upgrade to 2023.0.1.3, spring.cloud.nacos.config.namespace and spring.cloud.nacos.config.group no longer take effect, please check.

refer to the advanced guide. It is recommended to use the `spring.config.import` configuration method in 2021 and above versions.

https://sca.aliyun.com/docs/2022/user-guide/nacos/advanced-guide/?spm=5176.29160081.0.0.74805c72TsH1o1#%E8%87%AA%E5%AE%9A%E4%B9%89-namespace-%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by jfly-cloud** [comment]
Please note that versions before 2023.0.1.3 are available.

**Comment by chickenlj** [comment]
> @jfly-cloud Could you please provide more details.
> 
> Do you have `spring.config.import` specified?
> 
> `causing failure to obtain nacos configuration information.` What's the exact failure? How do you use nacos config to get the new value?

@jfly-cloud Can you provide the above information, thanks.

**Comment by jfly-cloud** [comment]
The screenshot is very clear, According to the documentation, I am using（bootstrap.yml）:

**User-defined namespace configurations**

**User-defined Group configuration**

It is no longer available after upgrading to 2023.0.1.3.

**Comment by jfly-cloud** [comment]
![image](https://github.com/user-attachments/assets/a338b027-613e-429f-9e04-1936c43c319d)
![image](https://github.com/user-attachments/assets/cd08bc31-4125-494e-8d9e-70cefbe7aeab)
