### ISSUE TITLE
Low level error in package naming in 2023.0.1.3

### ISSUE THREAD

**Issue by herodotus-ecosystem** [alibaba/spring-cloud-alibaba#3878]
Spring Cloud Alibaba 2023.0.1.3 将 spring-cloud-starter-alibaba-nacos-config 拆分为 spring-cloud-starter-alibaba-nacos-config 和 spring-alibaba-nacos-config

升级之后会出现无法拉去配置中心配置的问题。

最初还以为是新版本引入了新的配置方式，所以导致老配置方式不可用。

通过查看 spring-alibaba-nacos-config 模块代码，发现是包名命名的低级错误，导致不可用。

这个错误部分代码被放置在了 `com.alibaba.cloud.nacos` **文件夹** 下，而不是 `com` -> `alibaba` ->`cloud` -> `nacos` 下面。

![image](https://github.com/user-attachments/assets/c9eec0cd-046a-4ef5-9015-17ae2e7428d5)

**Comment by newblushL** [comment]
com.alibaba.cloud.nacos就是包名 并不是文件夹的名称哈

**Comment by newblushL** [comment]
com.alibaba.cloud.nacos 不就是包名么？

**Comment by herodotus-ecosystem** [comment]
> com.alibaba.cloud.nacos 不就是包名么？

正常的包名，`com.alibaba.cloud.nacos` 应该对应实际文件系统中 4 层文件夹，即 `com/alibaba/cloud/nacos`。对应实际的代码结构就是：`src/main/java/com/alibaba/cloud/nacos`

而代码中错误，虽然看着是也是 `com.alibaba.cloud.nacos` ，但他对应实际文件夹只有一层，把一整个文件夹命名成了 `com.alibaba.cloud.nacos` 。对应实际的代码结构就是：`src/main/java/com.alibaba.cloud.nacos`

java 中 packages 命名包含点不是不可以。但是在当前环境下就变成了两个不同的包，在 Spring Boot 环境下不同的包会出现 Bean 扫描不到或者注入失败的问题

**Comment by yuluo-yx** [comment]
Thank you very much, the community will fix it as soon as possible

**Comment by chickenlj** [comment]
> > com.alibaba.cloud.nacos 不就是包名么？
> 
> 正常的包名，`com.alibaba.cloud.nacos` 应该对应实际文件系统中 4 层文件夹，即 `com/alibaba/cloud/nacos`。对应实际的代码结构就是：`src/main/java/com/alibaba/cloud/nacos`
> 
> 而代码中错误，虽然看着是也是 `com.alibaba.cloud.nacos` ，但他对应实际文件夹只有一层，把一整个文件夹命名成了 `com.alibaba.cloud.nacos` 。对应实际的代码结构就是：`src/main/java/com.alibaba.cloud.nacos`
> 
> java 中 packages 命名包含点不是不可以。但是在当前环境下就变成了两个不同的包，在 Spring Boot 环境下不同的包会出现 Bean 扫描不到或者注入失败的问题

这个确实是个源文件命名问题，我们这边反馈到社区修复版本，但当前应该并不会影响正常逻辑运转

**Comment by herodotus-ecosystem** [comment]
> > > com.alibaba.cloud.nacos 不就是包名么？
> > 
> > 
> > 正常的包名，`com.alibaba.cloud.nacos` 应该对应实际文件系统中 4 层文件夹，即 `com/alibaba/cloud/nacos`。对应实际的代码结构就是：`src/main/java/com/alibaba/cloud/nacos`
> > 而代码中错误，虽然看着是也是 `com.alibaba.cloud.nacos` ，但他对应实际文件夹只有一层，把一整个文件夹命名成了 `com.alibaba.cloud.nacos` 。对应实际的代码结构就是：`src/main/java/com.alibaba.cloud.nacos`
> > java 中 packages 命名包含点不是不可以。但是在当前环境下就变成了两个不同的包，在 Spring Boot 环境下不同的包会出现 Bean 扫描不到或者注入失败的问题
> 
> 这个确实是个源文件命名问题，我们这边反馈到社区修复版本，但当前应该并不会影响正常逻辑运转

确实是啊，我也是才知道。看了编译后的包，竟然是会合并的。这样确实是不影响代码运行。
