### ISSUE TITLE
能否更新下当前项目的wiki文档？

### ISSUE THREAD

**Issue by yjr251314** [alibaba/spring-cloud-alibaba#3883]
您好，能否更新下 https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E 对应版本信息，已经很久没有更新了

**Comment by yuluo-yx** [comment]
文档都迁移到了 sca.aliyun.com ,wiki 已经不更新了

**Comment by yjr251314** [comment]
> 文档都迁移到了 sca.aliyun.com ,wiki 已经不更新了

非常感谢，已经找到了，https://sca.aliyun.com/docs/2023/best-practice/spring-boot-to-spring-cloud/?spm=5176.29160081.0.0.74805c72vNgBrp
