### ISSUE TITLE
Announcement: AI project migration announcement

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-cloud-alibaba#3892]
Hi, community. The Spring Cloud Alibaba AI project started in Spring Cloud Alibaba. During the project incubation period, it attracted the attention of many developers and users in the community. In order to better develop the Spring Cloud Alibaba AI application development framework, we have migrated the project to alibaba/spring-ai-alibaba repo , so far, the community ecology is active and positive. Star is welcome to follow and participate in Spring AI Alibaba open source contribution. 

<hr>

Hi, community。Spring Cloud Alibaba AI 项目开始于 Spring Cloud Alibaba。在项目初期开发阶段，吸引了社区众多开发者和用户的关注。为了更好的发展和建设 Spring Cloud Alibaba AI 应用开发框架，我们已将项目迁移到 alibaba/spring-ai-alibaba 仓库下。目前社区生态活跃、积极向上。欢迎 Star 并参与 Spring AI Alibaba 开源贡献。

钉钉交流群：64485010179

![image](https://github.com/user-attachments/assets/6301dd70-e0cd-482f-a9cb-ef3edaadc98e)

**Comment by Sorieee** [comment]
Expired
