### ISSUE TITLE
使用spring.config.import时，不能使用 jasypt-spring-boot-starter 解密密码

### ISSUE THREAD

**Issue by liqiang7070** [alibaba/spring-cloud-alibaba#3913]
---：shared-configs 已经不推荐使用，未来版本会废弃，统一通过spring.config.import进行导入

如上述描述，spring.config.import启动时，没有加载bean，也就不能使用 jasypt-spring-boot-starter 解密nacos的账号和密码了，是否会提供一个推荐方案。

**Comment by shiyiyue1102** [comment]
可以使用nacos的加解密插件，在SCA层加解密是无感的，https://nacos.io/zh-cn/docs/v2/plugin/config-encryption-plugin.html

**Comment by liqiang7070** [comment]
需要加密和解密的是连接nacos的用户名和密码。

**Comment by shiyiyue1102** [comment]
> 需要加密和解密的是连接nacos的用户名和密码。

用户名和密码建议通过JVM或者环境变量注入
