### ISSUE TITLE
[spring-cloud-alibaba-fescar] The problem of no rollback after hystrix service degradation

### ISSUE THREAD

**Issue by lkyaist16** [alibaba/spring-cloud-alibaba#430]
A calls B's method, and B throws an exception, triggering the hystrix service degradation defined by A, resulting in two stages of _commit execution for both services. How to solve this problem？

**Comment by flystar32** [comment]
It's seems the Exception threw by A has been caught by Hystrix, Fescar rollbacks when exception has been caught by Fescar Interceptor.

**Comment by lkyaist16** [comment]
Thank you. I see. Can fescar solve this problem? How can an exception be intercepted by fescar before it is caught by hystrix? Because in this case, both A and B services need to be rolled back.

**Comment by slievrly** [comment]
mark
