### ISSUE TITLE
spring-cloud-dubbo-provider-web-sample started with warning

### ISSUE THREAD

**Issue by crazythinking** [alibaba/spring-cloud-alibaba#434]
when i try to running spring-cloud-dubbo-provider-web-sample, it have some warning as following, but it can be registered to Nacos:
`
WARN 39340 --- [           main] o.s.c.a.d.r.RegistrationFactoryProvider  : Registration implementation can't be resolved by ServiceRegistry[org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry]
`
`
WARN 39340 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.0, current host: 192.168.10.1
`
`
WARN 39340 --- [           main] o.a.d.c.s.e.SpringExtensionFactory       :  [DUBBO] No spring extension (bean) named:applicationContext, try to find an extension (bean) of type org.springframework.context.ConfigurableApplicationContext, dubbo version: 2.7.0, current host: 192.168.10.1
2019-03-15 12:54:18.575  WARN 39340 --- [           main] o.a.d.c.s.e.SpringExtensionFactory       :  [DUBBO] No spring extension (bean) named:applicationContext, type:org.springframework.context.ConfigurableApplicationContext found, stop get bean., dubbo version: 2.7.0, current host: 192.168.10.1
`
`
WARN 39340 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Ignore empty notify urls for subscribe url provider://192.168.10.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-web-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=192.168.10.1&bind.port=20880&category=configurators&check=false&default.timeout=5000&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=39340&qos.enable=false&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552625657786&version=1.0.0, dubbo version: 2.7.0, current host: 192.168.10.1
`
so is there have any problem?

Version: 0.2.2.BUILD-SNAPSHOT

**Comment by halower** [comment]
org.springframework.cloud.alibaba.dubbo.registry.DelegatingRegistration cannot be cast to org.springframework.cloud.alibaba.nacos.registry.NacosRegistration

**Comment by fangjian0423** [comment]
Closing this issue due to long time, some codes have been changed.
