### ISSUE TITLE
Is the any way to walk around the exception when using custom response type on RestTemplate?

### ISSUE THREAD

**Issue by vipweihua** [alibaba/spring-cloud-alibaba#483]
Component: Sentinel

Description:
JsonParseException throws when we use custom response type on RestTemplate and traffic meets the threshold of the resource and fallback method invoked.

STR:
1. Define the API like http://localhost:8001/{id} which returns a User json.
2. Use RestTemplate on client-side to call the API and specify the response type as User.class
`
User user = restTemplate.getForEntity("http://localhost:8001/{id}", User.class, Collections.singletonMap("id", id)).getBody();
`
3. Exception  throws when calling the snippet code.

Investigation:
The blockHandler method defined on SentinelRestTemplate returns SentinelClientHttpResponse which has nothing containing User info.
Refer to the code:
class: HttpMessageConverterExtractor
method: public T extractData(ClientHttpResponse response) throws IOException

**Comment by fangjian0423** [comment]
I think you could using `blockHandler` and `blockHandlerClass` of `@SentinelRestTemplate` to handle this:

```java
@SentinelRestTemplate(blockHandler = "handleException", blockHandlerClass = ExceptionUtil.class)
```

Then construct `User` in `ExceptionUtil#handleException`:

```java
public class ExceptionUtil {

	public static SentinelClientHttpResponse handleException(HttpRequest request,
			byte[] body, ClientHttpRequestExecution execution, BlockException ex) {
        ObjectMapper objectMapper = Utils.getObjectMapper();
        User user = new User(-1L, "block");
        try {
            return new SentinelClientHttpResponse(objectMapper.writeValueAsString(user));
        } catch (JsonProcessingException e) {
            // ignore
        }
        return new SentinelClientHttpResponse("RestTemplate request block by sentinel");
    }

}
```

It seems that we should define more `RestTemplate` when there is more than 1 POJO.

**Comment by fangjian0423** [comment]
I think it can not walk around the exception because the convert action worked after interceptor.

**Comment by zkzlx** [comment]
*my solution* :
1.Convert the degraded Response using the `MessageConvert` in `RestTemplate`;
   The `MessageConverter`  need to define a special `MediaType`, such as `degraded/degraded;charset=UTF-8` ; because its preconditions are distinguished by 'MediaType',at last,the 'MediaType' needs to be reset to the original value after the conversion is completed.
2.In `BeanPostProcessor` intercept `SentinelRestTemplate` annotation tag bean of `RestTemplate` and inject customized `DegradedMessageConverter`
> In addition :
I may have an optimization of the original code,I need your help if I have any shortcomings

**Comment by fangjian0423** [comment]
I have read the code, it'a tricky way to do this, not suggest.

**Comment by fangjian0423** [comment]
In my view, it could be handled by `blockHandler` and `blockHandlerClass` of `@SentinelRestTemplate`.

Handle different POJOs by different request url like this:

```java
public static SentinelClientHttpResponse handleException(HttpRequest request,
		byte[] body, ClientHttpRequestExecution execution, BlockException ex) {
    ObjectMapper objectMapper = new ObjectMapper();
    Object pojo = null;
    if(request.getURI().toString().contains("user")) {
        pojo = new User(-1L, "block");
    } else if(request.getURI().toString().contains("good")) {
        pojo = new Good("blockSeqNo", "blocking");
    }
    
    try {
        return new SentinelClientHttpResponse(objectMapper.writeValueAsString(pojo));
    } catch (JsonProcessingException e) {
        // ignore
    }
    return new SentinelClientHttpResponse("RestTemplate request block by sentinel");
}
```
