### ISSUE TITLE
Spring Boot 2.x 的Endpoint为actuator

### ISSUE THREAD

**Issue by zzx0421** [alibaba/spring-cloud-alibaba#494]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md中的Spring Boot 2.x 的Endpoint为actuator

**Comment by fangjian0423** [comment]
Don't understand what you mean, can you describe it more clearly?

**Comment by fangjian0423** [comment]
Welcome to create pull request to fix this.
