### ISSUE TITLE
A component required a bean of type 'org.springframework.cloud.client.serviceregistry.ServiceRegistry' that could not be found

### ISSUE THREAD

**Issue by futong-liu** [alibaba/spring-cloud-alibaba#506]
spring-cloud-alibaba-dubbo-provider 
我运行了这个demo但是控制台提示错误

Description:

A component required a bean of type 'org.springframework.cloud.client.serviceregistry.ServiceRegistry' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.cloud.client.serviceregistry.ServiceRegistry' in your configuration.

nacos 版本  1.0.0-RC2

**Comment by fangjian0423** [comment]
How did you run it?

It runs well in my local.

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
