### ISSUE TITLE
关于缓存 jetcache的集成

### ISSUE THREAD

**Issue by qq240996777** [alibaba/spring-cloud-alibaba#512]
后续会有计划集成jetcache吗？

**Comment by fangjian0423** [comment]
Contributions are welcomed :)

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/608.

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/jetcache/tree/master/jetcache-starter.
