### ISSUE TITLE
nacos配置中心加载配置问题（ nacos配置中心加载配置问题 Nacos configuration center loading configuration problem）

### ISSUE THREAD

**Issue by hysora** [alibaba/spring-cloud-alibaba#539]
![image](https://user-images.githubusercontent.com/27765808/55865966-fa687700-5bb1-11e9-97de-27bca18c7b8d.png)

配置中心中的datasource数据源配置获取不到，判断是加载顺序问题，既先获取bootstrap.yml的内容再去加载DataSource，之后才会加载配置中心的配置 。这样的过程导致加载DataSource获取不到jdbc url等配置信息，这要怎么解决？我用了多数据源的配置，所以禁用了DataSourceAutoConfiguration。
The data source configuration in the configuration center can not be obtained, so it is a problem of loading order to determine. First, the content of bootstrap. YML is acquired, then the data source is loaded, and then the configuration of the configuration center is loaded. This process results in the loading of DataSource to obtain configuration information such as JDBC url. How to solve this problem?
I used the configuration of multiple data sources, so Data Source AutoConfiguration was disabled.

**Comment by fangjian0423** [comment]
You could refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config.

**Comment by jumkey** [comment]
多数据源出现同样的问题，并且会导致30秒刷新一下配置
#530 这位兄弟估计也是同样的问题

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
