### ISSUE TITLE
NamingService management not support `spring.cloud.nacos.discovery.group` ?

### ISSUE THREAD

**Issue by baobeidaodao** [alibaba/spring-cloud-alibaba#540]
Configuration management support `spring.cloud.nacos.config.group` , but NamingService management not support `spring.cloud.nacos.discovery.group` ?
I do not find `group` in `NacosDiscoveryProperties` .
Is this a bug or feature?
thanks.

**Comment by fangjian0423** [comment]
It will be supported in 2.1.1.RELEASE version and welcome to contribute it.

**Comment by baobeidaodao** [comment]
> It will be supported in 2.1.1.RELEASE version and welcome to contribute it.

Exciting!
