### ISSUE TITLE
alibaba dubbo整合nacos分布式调用有问题

### ISSUE THREAD

**Issue by xingcun** [alibaba/spring-cloud-alibaba#545]
**Which Component**
alibaba dubbo + Nacos

**Describe the bug**
alibaba dubbo整合nacos分布式调用有问题！

**To Reproduce**
1.先启动一个dubbo service A,
2.再启动一个dubbo customer,
3,再启动一个dubbo serviceB,
4. 当运行customer时，只会调用A,而不会调用B,nacos上service A与serviceB是属于同一服务，两个单例

服务名|分组|集群数目|实例数|健康实例数
--|:--:|--:|:--:|--:
xc-service| DEFAULT_GROUP|1|2|2
xc-customer| DEFAULT_GROUP|1|1|1

5.但是当启动dubbo service A,B,再启动dubbo customer,分布式服务调用正常
**Expected behavior**

**Screenshots**

**Additional context**
e.g.  window10  、Java8 、 spring-cloud-alibaba-0.2.1.RELEASE

	<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>2.6.6</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo-registry-nacos</artifactId>
			<version>2.6.6</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.0.0-RC3</version>
		</dependency>

dubbo service代码
```
public interface TestCacosService {
	public String send(String msg);
}
```

```
import com.alibaba.dubbo.config.annotation.Service;
import com.xc.service.TestCacosService;
@Service
public class TestCacosServiceImpl implements TestCacosService{

	@Override
	public String send(String msg) {
		System.out.println("msg:"+msg);
		return msg;
	}

}
```

dubbo customer代码
```
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.alibaba.dubbo.config.annotation.Reference;
import com.alibaba.fastjson.JSONObject;

import com.xc.service.TestCacosService;


@RestController
public class TestControl {

	@Reference
	private TestCacosService testCacosService;


	@RequestMapping(value = "/test")
	public JSONObject test(String msg) {
		JSONObject obj = new JSONObject();
		testCacosService.send(msg);
		obj.put("status", 1);
		return obj;
	}
```
当调用127.0.0.1:8080/test时，只有一个service有响应

**Comment by mercyblitz** [comment]
Did you mean the service client invocations are not balanced?

**Comment by xingcun** [comment]
> Did you mean the service client invocations are not balanced?

yes

**Comment by ninjachen** [comment]
Steps to reproduce the behavior:
1.先启动一个dubbo service A,
2.再启动一个dubbo customer,
3,再启动一个dubbo serviceB,

这个情况的时候会发现dubbo customer中serviceB的instance注入失败，一直是null。期望在serviceB启动后，有个机会让customer中的serviceB实力注入成功。
