### ISSUE TITLE
[spring-cloud-stream-binder-rocketmq]I can't set the queue selection when sending messages and get the returned results. I can't set the offsetStore when consuming messages.

### ISSUE THREAD

**Issue by ABI700badu** [alibaba/spring-cloud-alibaba#547]
**Which Component**
spring-cloud-stream-binder-rocketmq

**Describe what problem you have encountered**
对于消费者或者生产者的一些配置，在整合到spring-stream框架下面，未提供配置。
比如consumer.setOffsetStore(remoteBrokerOffsetStore)? 
正常的代码能设置的希望在spring-stream框架下也能设置

**Comment by fangjian0423** [comment]
可以提供一下需要设置的属性吗？

看到你说的，你需要 `MessageQueueSelector` 和 `OffsetStore`。

---------------

Could you please provide which properties you need?

As you said, you need `MessageQueueSelector` and `OffsetStore`.

**Comment by fangjian0423** [comment]
refer #667
