### ISSUE TITLE
spring cloud dubbo qos.enable don't take effect

### ISSUE THREAD

**Issue by SmileTower** [alibaba/spring-cloud-alibaba#551]
registry://localhost:9090/org.apache.dubbo.registry.RegistryService?application=spring-cloud-alibaba-dubbo-provider&dubbo=2.0.2&export=dubbo%3A%2F%2F192.168.29.8%3A20881%2Forg.springframework.cloud.alibaba.dubbo.service.RestService%3Fanyhost%3Dtrue%26application%3Dspring-cloud-alibaba-dubbo-provider%26bean.name%3Dproviders%3Adubbo%3Aorg.springframework.cloud.alibaba.dubbo.service.RestService%3A1.0.0%26bind.ip%3D192.168.29.8%26bind.port%3D20881%26default.deprecated%3Dfalse%26default.dynamic%3Dfalse%26default.register%3Dtrue%26deprecated%3Dfalse%26dubbo%3D2.0.2%26dynamic%3Dfalse%26generic%3Dfalse%26interface%3Dorg.springframework.cloud.alibaba.dubbo.service.RestService%26methods%3Dheaders%2CrequestBodyUser%2CpathVariables%2Cform%2Cparam%2CrequestBodyMap%2Cparams%26pid%3D16520%26register%3Dtrue%26release%3D2.7.1%26revision%3D1.0.0%26side%3Dprovider%26timestamp%3D1555135773249%26version%3D1.0.0&pid=16520&registry=spring-cloud&release=2.7.1&timestamp=1555135773243

url can't find qos

![image](https://user-images.githubusercontent.com/17945169/56075490-43107200-5df6-11e9-8649-e15fb5917ecb.png)
![image](https://user-images.githubusercontent.com/17945169/56077391-43b50280-5e0e-11e9-984b-23a749bab1f5.png)

java8、nacos 1.0.0 、dubbo 2.7.1

**Comment by wadezyj** [comment]
Regardless of whether I change the QoS enabled or QoS port, it has no effect, the startup log already has java.net.BindException: the address is already in use: binding error.

**Comment by yub1ng** [comment]
<img width="530" alt="屏幕快照 2019-05-15 01 14 23" src="https://user-images.githubusercontent.com/34766340/57718064-15497200-76af-11e9-8406-9a9073bb67c5.png">
yes, qos.enable unable to bind

**Comment by EyoungShieh1992** [comment]
use
`dubbo:
  application:
    qos:
      enable: false`

**Comment by EyoungShieh1992** [comment]
use
![image](https://user-images.githubusercontent.com/31103392/61276363-77734000-a7e2-11e9-8251-72471886326c.png)

**Comment by mercyblitz** [comment]
Fixed
