### ISSUE TITLE
spring-cloud-alibaba-sentinel Service downgrade

### ISSUE THREAD

**Issue by ghost** [alibaba/spring-cloud-alibaba#570]
**Which Component**
 spring-cloud-starter-alibaba-sentinel

**Describe what problem you have encountered**
I need sentinel to perform special handling on the specific exception state returned by the service provider, instead of causing the service to be downgraded. What should I do? I see that the method of the SentinelInvocationHandler class in spring-cloud-alibaba-sentinel does not make any distinction between exceptions, all of which will cause service downgrades.

**Describe what information you have read**
There are no related descriptions in the document.

**Comment by fangjian0423** [comment]
Hi @Lemon-mx 

You could use `fallbackFactory` of `@FeignClient`.  It is a type of `feign.hystrix.FallbackFactory`.

Then you could catch exceptions what you wanted.

```java
T create(Throwable cause);
```

**Comment by Lemon-mx** [comment]
After the experiment, the FeignException is caught in the create method and the correct exception is thrown after the relevant processing, so as to end the current request and return to the front end. But the correct exception thrown here will still be captured by the relevant code of SentinelInvocationHandler and enter the record processing flow. Using hystrix will have the same problem, but you can not enter the service downgrade process by throwing a specific exception in the decode method of the ErrorDecoder class. So, is this framework the same way? Or will it be supported in the future? Of course, there are other ways to deal with this situation can achieve the same effect, but I want to keep the platform consistent.

**Comment by fangjian0423** [comment]
Could you please describe it with some code? It is not clearly as you said.

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
