### ISSUE TITLE
How to get the exception when stream fail to send message 

### ISSUE THREAD

**Issue by slinpq** [alibaba/spring-cloud-alibaba#577]
How can I get the exception, if stream fail to send message?I only see the log of error now.

**Comment by fangjian0423** [comment]
Hi.

You could see this example https://github.com/fangjian0423/rocketmq-binder-demo/tree/master/rocketmq-binder-error-produce-demo when failed to send message.

**Comment by fangjian0423** [comment]
make sure `error-channel-enabled` has been configured, like this:

```
spring.cloud.stream.bindings.output.producer.errorChannelEnabled
```

**Comment by slinpq** [comment]
I want to get the exception in my service, but it just throw the exception in rocketMQ's thread.

**Comment by fangjian0423** [comment]
It is not supported in Stream Binder because it is using `MessageChannel` to handle exception.

You could using `RocketMQTemplate` to send message.
