### ISSUE TITLE
when nacos-discovery can support registration by group name

### ISSUE THREAD

**Issue by seas521** [alibaba/spring-cloud-alibaba#580]
![image](https://user-images.githubusercontent.com/11845088/56548299-54a20880-65b2-11e9-8d00-9d1f9fbd119c.png)
while the 1.0 nacos client has supported registering service by group name，hoping cloud way can add this feature，thx！

**Comment by fangjian0423** [comment]
Could you please help to contribute it?

**Comment by flystar32** [comment]
#540

**Comment by seas521** [comment]
> Could you please help to contribute it?

I start a pull request,
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/pull/593
