### ISSUE TITLE
使用spring-cloud-alibaba启动报空指针异常

### ISSUE THREAD

**Issue by mmmmarcos** [alibaba/spring-cloud-alibaba#582]
![image](https://user-images.githubusercontent.com/26370284/56564025-c17fc780-65df-11e9-8554-59b4fcb2f193.png)
项目地址（可复现）：https://github.com/mmmmarcos/wdcloud-gateway.git

**Comment by whthomas** [comment]
我也是报这个错，这个MetadataRepository是做什么的。

**Comment by fuyongde** [comment]
我也报这个错，但是跑例子程序里的网关就可以

**Comment by fuyongde** [comment]
升级`feign-jaxrs2`版本可以解决这个问题。参照这个 #690

**Comment by cmonkey** [comment]
#591 已经修复了

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback. Maybe is has been fixed.
