### ISSUE TITLE
how to use spring-cloud-alibaba-dubbo?

### ISSUE THREAD

**Issue by mostcool** [alibaba/spring-cloud-alibaba#584]
how to use spring-cloud-alibaba-dubbo?
we need detailed usage readme.

**Comment by mostcool** [comment]
@mercyblitz

**Comment by mercyblitz** [comment]
I will update as soon as possible

**Comment by haydonchou** [comment]
变化很大，目前提示必须连一个元数据中心，没有开关。只能等文档。太慢了

**Comment by mercyblitz** [comment]
> 变化很大，目前提示必须连一个元数据中心，没有开关。只能等文档。太慢了

No, please take a look at this : https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/README_CN.md
