### ISSUE TITLE
seata DataSourceProxy

### ISSUE THREAD

**Issue by w5185552** [alibaba/spring-cloud-alibaba#586]
项目中使用druid-spring-boot-starter该如何注入 com.alibaba.fescar.rm.datasource.DataSourceProxy

How to inject com.alibaba.fescar.rm.datasource.DataSourceProxy into Seata project using druid-spring-boot-starter

**Comment by flystar32** [comment]
I've never used druid-spring-boot-starter before, but I think this issue can be changed to an issue of druid-spring-boot-starter:

How to inject an custom `javax.sql.DataSource` in `druid-spring-boot-starter`.

**Comment by w5185552** [comment]
Is the reason that the data in undo_log is empty due to the problem of DataSourceProxy? How should I investigate

**Comment by oldmanl** [comment]
seata support auto datasource proxy since 0.9。

>  1.1.0: 取消属性配置，改由注解@EnableAutoDataSourceProxy开启，并可选择jdk proxy或者cglib proxy
    1.0.0: client.support.spring.datasource.autoproxy=true
    0.9.0: support.spring.datasource.autoproxy=true

or you can do it by yourslef, like this:

1. exclude `DruidDataSourceAutoConfigure`
```
@SpringBootApplication(exclude = {
       DruidDataSourceAutoConfigure.class
})
```

2. Configuration Datasource Proxy

```
@Configuration
@ConditionalOnClass(DruidDataSource.class)
@AutoConfigureBefore(DataSourceAutoConfiguration.class)
public class MyDataSourceConfig {
 
    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.druid")
    public DataSource druidDataSource() {
        DruidDataSource druidDataSource = new DruidDataSource();
        return druidDataSource;
    }

    @Primary
    @Bean("dataSource")
    public DataSourceProxy dataSourceProxy(DataSource druidDataSource) {
        return new DataSourceProxy(druidDataSource);
    }
}
```
