### ISSUE TITLE
yml配置订阅多个服务不生效 dubbo.cloud.subscribed-services doesn't work in yml

### ISSUE THREAD

**Issue by TulleyT** [alibaba/spring-cloud-alibaba#603]
1.在yml文件中配置dubbo.cloud.subscribed-services 订阅多个服务用","分隔,最终的结果是一个服务都没订阅成功,而在properties文件中配置这个属性,同样用","分隔,则可以生效
2.此外,在yml文件中主动配置dubbo.cloud.subscribed-services 并设置为默认值"*",启动会直接报错,如果不配置此属性,则可启动成功,并且可以订阅多个服务

1. When I try to subscribe multiple services and use "dubbo.cloud.subscribed-services" and split by "," in yml file,it dosen't work. But in properties file it work 
2.Then I try to use "dubbo.cloud.subscribed-services" and set default value "*" in yml file.The startup will report an error directly.But when I remove this property , it can be started successfully and can subscribe to multiple services.

**Comment by mercyblitz** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/533114/56846856-c22d9c00-6906-11e9-9bb8-e6d7236c231a.png)

![image](https://user-images.githubusercontent.com/533114/56846860-cbb70400-6906-11e9-94e3-569e5616cfa0.png)

How about your yaml file?

**Comment by TulleyT** [comment]
I mean it will throw a no provider exception  when I actually call the remote interface ，but Providers are already registered in Nacos

**Comment by mercyblitz** [comment]
@TulleyT 

Did your client application call service after the provider being ready?

**Comment by TulleyT** [comment]
yes of course

**Comment by mercyblitz** [comment]
Fixed

**Comment by niuzhiweimr** [comment]
2.1.2 How to fix the version？

**Comment by lw5946** [comment]
2.2.2 仍然有此问题，猜测是跟服务启动的顺序有关，provider比consumer启动的晚

**Comment by pangshuqiang** [comment]
2.7.6，不订阅反而正常能启用并能调用到提供者，设置这个参数订阅了服务后，能注册到Nacos，反而找不到提供者接口，请求失败！
