### ISSUE TITLE
[Feature Request] Integration with Alibaba Cloud Product

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#607]
Now we have integrated with ACM, ANS, SchedulerX, SMS, OSS. 

Need more components to be integrated.

**Comment by Dhiraj240** [comment]
@fangjian0423 Hello!!
Can Indian students participate in it?
I have opensource experience as a mentor for Google Code-In 2018 and also opensource contributor to coala, Public Lab organisation. You can check my github profile.
Can you guide me on how to write specific proposal for this project and prior contribution is needed here?
Need some pointers for this project.I have used Microsoft Azure as a Microsoft Student Partner and love cloud services.

**Comment by fangjian0423** [comment]
Hi @Dhiraj240 

Idea list about Spring Cloud Alibaba you can refer to: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/labels/SoC2019
The official website of Alibaba Summer of Code: https://developer.aliyun.com/special/summerofcode2019en
Feel free to contact us via aliopensource@alibabacloud.com

**Comment by Dhiraj240** [comment]
I am interested in this project may i know what all components you want to integrate? Should i make a proposal over it?

**Comment by fangjian0423** [comment]
@Dhiraj240 You could look for the [components](https://www.alibabacloud.com/) which you are interested in.

Now we have integrated with [Enterprise Distributed Application Service (EDAS)](https://www.alibabacloud.com/product/edas), which including ANS, ACM and SchedulerX.

Application Naming Service (ANS) is a service discovery component provided by EDAS, which is a commercial version of open source [Nacos](https://github.com/alibaba/nacos/).

Alibaba Cloud Configuration Center (ACM) is a distributed configuration component provided by EDAS, which is a commercial version of open source [Nacos](https://github.com/alibaba/nacos/).

[Alibaba Cloud SchedulerX](https://help.aliyun.com/document_detail/43136.html)  is a distributed task scheduling product developed by Alibaba Cloud. Now it is only supported in chinese region.

[Alibaba Cloud Object Storage Service (OSS)](https://www.alibabacloud.com/product/oss) is an encrypted and secure cloud storage service which stores, processes and accesses massive amounts of data from anywhere in the world.

[Alibaba Cloud's Short Message Service (SMS)](https://www.alibabacloud.com/product/short-message-service) provides convenient, efficient, and intelligent communication capabilities that help businesses quickly contact their customers.

**Comment by Dhiraj240** [comment]
@fangjian0423 Wow, thank you for this detailed information. Also sorry, I had my exams which are over now.
Now, the internship length is 2 months so how many [components](https://www.alibabacloud.com/product?spm=a3c0i.254666.1332343.82.4d206210bowyb0) I should add. As of now, I have decided 5 components 
1. [Object Storage](https://www.alibabacloud.com/product/oss?spm=a3c0i.11270126.209577.17.2e3b25b3tQifP2)
2. [Enterprise Email](https://www.alibabacloud.com/products/alibaba-mail?spm=a3c0i.11270126.209577.89.2e3b25b3tQifP2)
3. [Server Load Balancer](https://www.alibabacloud.com/product/server-load-balancer?spm=a3c0i.11270126.209577.29.2e3b25b3tQifP2)
4. [Anti DDoS Basic](https://www.alibabacloud.com/product/anti-ddos?spm=a3c0i.11270126.209577.49.2e3b25b3tQifP2)
5. [Machine Learning Platform for AI](https://www.alibabacloud.com/product/machine-learning?spm=a3c0i.11270126.209577.80.2e3b25b3tQifP2)

So, should I start working on the proposal and start contributions for the above-related components?
Please do provide any other pointers.

**Comment by fangjian0423** [comment]
Please leave an email and i will invite you to slack.

**Comment by Dhiraj240** [comment]
dhiraj.8.sharma@gmail.com

**Comment by Dhiraj240** [comment]
Didn't receive it yet?
