### ISSUE TITLE
Nacos能更符合springboot的配置文件降级策略吗

### ISSUE THREAD

**Issue by tanyunpeng** [alibaba/spring-cloud-alibaba#613]
springboot应用是按 spring.active.profile区分配置的，在使用配置中心的时候，希望是文件隔离的（同一个命名空间里面，我只能看见一个环境的配置），因为DBA不想让我知道线上的密码。Nacos的namespace，我第一眼认为它就是这个隔离策略（spring.active.profile模式），现实告诉我呵呵哒，并且它还限制了200个配置，用id做标识真心不好用。在试了一段时间后，我感觉这个namespace又有点像组的概念。Nacos本身又有组（这个组真不知道有啥用），好混乱的感觉。

例如下面的，我可以指定默认的配置和文件扩展名。
xxx-{profile}.yml
xxx.yml
xxx-{profile}.properties
xxx.properties
application-{profile}.yml
application.yml
application-{profile}.properties
application.properties

可能我的要求有点过分，毕竟又不是只给springboot用的

**Comment by flystar32** [comment]
refer to WIKI ，https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config#%E5%8F%AF%E6%94%AF%E6%8C%81profile%E7%B2%92%E5%BA%A6%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by SoyMeng** [comment]
我的理解是namespace用于环境隔离，group用于应用隔离

**Comment by ynych** [comment]
我也是同样的理解，但这样一个namespace200条配置限制是不是太少了

> 我的理解是namespace用于环境隔离，group用于应用隔离
