### ISSUE TITLE
[Enhancement] Dubbo Check on start up

### ISSUE THREAD

**Issue by Abnerring** [alibaba/spring-cloud-alibaba#622]
i add config in consumer ymal, beacuse i have circular dependency in my project
eg:
dubbo:
  consumer:
     check: false

question:
i started consumer service ,  When the provider service service is restored, the service can not automatically reconnect.

**Comment by haydonchou** [comment]
我现在也碰到这个问题了，设置false，provider后启动无法重连，需要关注服务启动顺序，对维护人员很不友好。

**Comment by Abnerring** [comment]
目前没有好办法，只能在服务架构设计上，避免循环依赖，
比如，


 消费层                                 服务消费


 业务服务层                   订单服务 商品服务    


 基础设施服务                文件服务，短信服务



在 2019-08-02 15:10:46，"haydonchou" <notifications@github.com> 写道：


我现在也碰到这个问题了，设置false，provider后启动无法重连，需要关注服务启动顺序，对维护人员很不友好。

**Comment by mercyblitz** [comment]
Please set the check to be false, and void the recursive dependences on services.
