### ISSUE TITLE
Service registration found namespace invalidation problem

### ISSUE THREAD

**Issue by cel105302** [alibaba/spring-cloud-alibaba#629]
When I use the service registration discovery function, I configured the namespace, which is the namespace ending in "-test" in the attachment, but I still registered it under the default public. Does this require special configuration? I use it. The nacos version is 1.0.0 and the spring boot version is 2.1.2.RELEASE
![image](https://user-images.githubusercontent.com/32325588/57186950-5658be00-6f1a-11e9-8d40-ab209c68b3b1.png)

**Comment by cel105302** [comment]
modify pic.

**Comment by flystar32** [comment]
refer to this  https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery
search for spring.cloud.nacos.discovery.namespace
