### ISSUE TITLE
springboot:2.1.4.RELEASE+cloud:Greenwich.RELEASE+alibaba:0.9.0.RELEASE。nacos1.0持久化mysql下 客户端获取不到配置文件，nacos控制台显示没有监听

### ISSUE THREAD

**Issue by wuShanYunYu0612** [alibaba/spring-cloud-alibaba#630]
**pom文件**
![image](https://user-images.githubusercontent.com/40649746/57189318-da716c80-6f3f-11e9-9ec8-6fc91f58b57d.png)

**配置文件**
![image](https://user-images.githubusercontent.com/40649746/57189333-199fbd80-6f40-11e9-92b7-0d6687409866.png)
![image](https://user-images.githubusercontent.com/40649746/57189335-23292580-6f40-11e9-9e5f-11c9f349ab22.png)

**Comment by flystar32** [comment]
could you provider more information? such as your nacos console, logs  and so on.
a Minimal, Complete, and Verifiable example is better.

**Comment by wuShanYunYu0612** [comment]
https://github.com/wuShanYunYu0612/cloud-demo.git  demo 的地址

**Comment by wuShanYunYu0612** [comment]
> could you provider more information? such as your nacos console, logs and so on.
> a Minimal, Complete, and Verifiable example is better.

https://github.com/wuShanYunYu0612/cloud-demo.git demo地址

**Comment by flystar32** [comment]
ensure you has configured nacos config address in you bootstrap file, found no information in  https://github.com/wuShanYunYu0612/cloud-demo/blob/master/spring-cloud/service-module/basics-module/gateway-server/src/main/resources/bootstrap.yml

**Comment by flystar32** [comment]
you can refer to this https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md

**Comment by wuShanYunYu0612** [comment]
> ensure you has configured nacos config address in you bootstrap file, found no information in https://github.com/wuShanYunYu0612/cloud-demo/blob/master/spring-cloud/service-module/basics-module/gateway-server/src/main/resources/bootstrap.yml

nacos的地址都在 dev里 
https://github.com/wuShanYunYu0612/cloud-demo/blob/master/spring-cloud/service-module/basics-module/gateway-server/src/main/resources/bootstrap-dev.yml

**Comment by wuShanYunYu0612** [comment]
> you can refer to this https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md

我使用https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example 下载下来的工程 更改为nacos1.0的客户端同时持久化到mysql 时依旧监听不到nacos上的配置信息

**Comment by luohaoGit** [comment]
我也遇到这个问题，你解决了吗
