### ISSUE TITLE
The shared configuration of Nacos now using DEFAULT_GROUP and could not be modified.

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#633]
**Which Component**

Nacos Config

**Is your feature request related to a problem? Please describe.**

Now the shared configuration of Nacos now using DEFAULT_GROUP and could not be modified. see `NacosPropertySourceLocator#loadSharedConfiguration`:

```java
loadNacosDataIfPresent(compositePropertySource, dataId, "DEFAULT_GROUP",
					fileExtension, isRefreshable);
```

It is necessary to use `NacosConfigProperties#group` to load shared configuration?

**Comment by crazy6995** [comment]
Although we can use data-ids, use group will be better.

**Comment by flystar32** [comment]
I think it it wrong to  use NacosConfigProperties#group to load shared configuration.

different Applications can  set different `NacosConfigProperties#group`, SharedConfiguration are designed to be shared by a lot of Applications.

If you want to use another group  to load shared configuration, you should use spring.cloud.nacos.config.ext-config instead.

refer to this https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config#%E6%94%AF%E6%8C%81%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E7%9A%84-data-id-%E9%85%8D%E7%BD%AE

**Comment by fangjian0423** [comment]
Agree with @flystar32, shared configuration is using by multi applications. The group should be the same.

**Comment by camellibby** [comment]
I wanner submit a issue same as above. It's very strange with hard code 'DEFAULT_GROUP'.

**Comment by fangjian0423** [comment]
> I wanner submit a issue same as above. It's very strange with hard code 'DEFAULT_GROUP'.

Shared configuration is using by multi applications. The group should be the same and with hard code `DEFAULT_GROUP`(or other value, but i think default group is better). How do you think about it?

**Comment by kerns-huang** [comment]
if you use the DEFAULT_GROUP why the config provides group Option ， this is strange。

**Comment by fangjian0423** [comment]
> if you use the DEFAULT_GROUP why the config provides group Option ， this is strange。

This is shared configuration, not generic configuration.

**Comment by ynfatal** [comment]
I use 1.2.1. What's the difference between shared-configs and extension-configs? Their implementation is based on `com.alibaba.cloud.nacos.NacosConfigProperties.Config`.
