### ISSUE TITLE
本地启动nacos 1.0 ，使用github上的0.9的cloud的项目nacos  config的 demo获取不到nacos上的配置信息。

### ISSUE THREAD

**Issue by wuShanYunYu0612** [alibaba/spring-cloud-alibaba#662]
用 curl 请求可以获取到配置文件  但是程序就不能获取到

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example or https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config.

**Comment by wuShanYunYu0612** [comment]
> 参考https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example或[https://github.com / spring-cloud-incubator / spring-cloud-alibaba / wiki / Nacos-config](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config)。

就是直接使用的https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example这个项目，从本地的nacos中获取不到配置信息

**Comment by fangjian0423** [comment]
Make sure your nacos-server address and port is right. You could debug in `NacosPropertySourceLocator` to see what happened.

**Comment by zjinying** [comment]
> Make sure your nacos-server address and port is right. You could debug in `NacosPropertySourceLocator` to see what happened.
遇到同样的问题，断点查看的结果返回
![image](https://user-images.githubusercontent.com/19943107/60074190-ecf46f00-9754-11e9-8289-5887ed28a24c.png)

**Comment by wuShanYunYu0612** [comment]
> > Make sure your nacos-server address and port is right. You could debug in `NacosPropertySourceLocator` to see what happened.
> > 遇到同样的问题，断点查看的结果返回
> > ![image](https://user-images.githubusercontent.com/19943107/60074190-ecf46f00-9754-11e9-8289-5887ed28a24c.png)

仔细看一下文档，cloud 配置文件需要带后缀 我的是这个原因

**Comment by HaojunRen** [comment]
I close this issue first, any problems to reopen it please
