### ISSUE TITLE
Dubbo Alibaba Cloud项目中搭建错误

### ISSUE THREAD

**Issue by MyZhouGit** [alibaba/spring-cloud-alibaba#665]
**Which Component**
Dubbo

**Describe what problem you have encountered**
I made a mistake after setting up the project according to your consumer example.The error message is 
No provider available for the service com.xiaozhi.alibaba.inter.EchoService from the url spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?application=xiaozhi-Alibaba-consumer&default.lazy=false&default.sticky=false&dubbo=2.0.2&interface=com.xiaozhi.alibaba.inter.EchoService&lazy=false&methods=echo&pid=5436&register.ip=192.168.1.198&release=2.7.1&side=consumer&sticky=false&timestamp=1558673701087 to the consumer 192.168.1.198 use dubbo version 2.7.1

**Describe what information you have read**
i think i need your help to resolve this error,i just for study,thank you

**Comment by cdy1996** [comment]
昨天我也运行master上的example例子,在client-sample启动时出现了和你一样的问题,但是今天我仔细检查了client-sample中nacos的版本发现master上用的nacos-client是1.0.0 ,而昨天我启动的nacos是0.8.0, 然后换成1.0.0.RC3, 然后就能拉取到服务了成功启动了,不知道你是不是和我一样的问题.

nacos控制台
![image](https://user-images.githubusercontent.com/22991270/58756255-3b806600-8527-11e9-9193-e428eaf31d1a.png)

调用也是成功的
![image](https://user-images.githubusercontent.com/22991270/58756266-71bde580-8527-11e9-80ec-79c02482d674.png)

**Comment by wuyibo126** [comment]
相同问题，求解..
