### ISSUE TITLE
Rocketmq binder in the future whether to consider supporting the sending of orderly message (via stream api)

### ISSUE THREAD

**Issue by wangxing-git** [alibaba/spring-cloud-alibaba#667]
**Which Component**
`rocketmq stream binder`

**Is your feature request related to a problem? Please describe.**
Currently, `orderly` messages can only be sent through the `RocketMqTemplate` api, hopefully it can be done through the `stream` api.

**Comment by fangjian0423** [comment]
Stream api seems don't include feature about queue index.

RocketMQ select messagequeue by `MessageQueueSelector`.

We will integrate with `MessageQueueSelector` in the future and welcome to discuss how to integrate with it.

**Comment by wangxing-git** [comment]
@fangjian0423 Is it possible to pass relevant parameters through the header just like setting tags?

**Comment by fangjian0423** [comment]
> @fangjian0423 Is it possible to pass relevant parameters through the header just like setting tags?

Not setting tag, setting messagequeue index.

How can we make sure which binding with which `MessageQueueSelector` like this?

Binding1 -> CustomMessageQueueSelector1
Binding2 -> CustomMessageQueueSelector2
Binding3 -> CustomMessageQueueSelector3

Configuration properties is a way to solve this:

`spring.cloud.stream.rocketmq.bindings.output1.producer.message-queue-selector=fullClassNameOfMessageQueueSelector`.

But i think this is not a graceful solution.

**Comment by wangxing-git** [comment]
I just want to be as small as possible involving message middleware, but spring-cloud-stream doesn't have similar operations, maybe this is not what it should do.

**Comment by wangxing-git** [comment]
@fangjian0423 Perhaps can use a partition implementation, use `partitionKeyExpression` to parse the hash key, and use `PartitionSelectorStrategy` to filter the queue.It also supports passing partition values from outside using the `BinderHeaders.PARTITION_OVERRIDE` header.

**Comment by wangxing-git** [comment]
> @fangjian0423 Perhaps can use a partition implementation, use `partitionKeyExpression` to parse the hash key, and use `PartitionSelectorStrategy` to filter the queue.It also supports passing partition values from outside using the `BinderHeaders.PARTITION_OVERRIDE` header.

This implementation is not compliant and has been deprecated.

**Comment by wangxing-git** [comment]
Use the header `RocketMQBinderConstants.ROCKET_QUEUE_SELECT_KEY` to set the hash key, and the `RocketMQBinderConstants.ROCKET_QUEUE_INDEX_OVERRIDE` header to override the queue index (once set to skip the execution of the MessageQueueSelector).
```java
 source.transactionalAccountOutput().send(
                MessageBuilder.withPayload("test1")
                        .setHeader(RocketMQHeaders.TAGS, RocketMqTags.TAG2)
                        .setHeader(RocketMQBinderConstants.ROCKET_QUEUE_SELECT_KEY, "1")
                        .build()
        );
source.transactionalAccountOutput().send(
                MessageBuilder.withPayload("test3")
                        .setHeader(RocketMQHeaders.TAGS, RocketMqTags.TAG2)
                        .setHeader(RocketMQBinderConstants.ROCKET_QUEUE_INDEX_OVERRIDE, 1)
                        .build()
        );
```
The `@RocketMQBinding` annotation can be used to associate a `MessageQueueSelector` bean with a binding.
```java
    @Bean
    @RocketMQBinding(Processor.TRANSACTIONAL_ACCOUNT_OUTPUT)
    public MessageQueueSelector messageQueueSelector(){
        return (mqs, msg, arg) -> mqs.get(0);
    }
```
```java
@Component
@RocketMQBinding(Processor.TRANSACTIONAL_ACCOUNT_OUTPUT)
public class TestMessageQueueSelector implements MessageQueueSelector {

    @Override
    public MessageQueue select(List<MessageQueue> mqs, Message msg, Object arg) {
        return mqs.get(2);
    }

}
```
