### ISSUE TITLE
How to customize Spring Cloud Nacos log dir and log name

### ISSUE THREAD

**Issue by tuser4198** [alibaba/spring-cloud-alibaba#672]
**Which Component**
eg. Nacos Discovery, Nacos Config

**Describe what problem you have encountered**
I found that nacos make dir path like '/Users/someone/logs/nacos'.
and log files like 'config.log' and 'naming.log'.
I want to customize the log directory and file name, but I only find one property 'spring.cloud.nacos.discovery.log-name' related to log. So what should I do?

**Describe what information you have read**
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery

**Comment by fangjian0423** [comment]
It seems nacos-client is not support customized log info. Refer https://github.com/alibaba/nacos/issues/1276.
