### ISSUE TITLE
i don't kown what's  wrong with my rocketmq 

### ISSUE THREAD

**Issue by zzhujing** [alibaba/spring-cloud-alibaba#687]
this is my console error log
```java
2019-05-31 00:12:52.406 ERROR 17704 --- [enderExecutor_1] o.s.c.s.b.r.i.RocketMQMessageHandler     : RocketMQ Message hasn't been sent. Caused by No route info of this topic, test
```

this is my programing and config
```java  
    @Autowired
    private MessageChannel output;

    @GetMapping("/send")
    public void send(String... args) throws Exception {
        output.send(MessageBuilder.withPayload("Hello,RocketMq").build());
    }
```

```yaml
spring:
  application:
    name: rocketmq-provier
  cloud:
    stream:
      bindings:
        output: {destination: test,content-type: application/json}
        rocketmq:
          binder:
            namesrv-addr: 192.168.152.131:9876

`

**Comment by fangjian0423** [comment]
"No route info of this topic" means you can't connect name-server or topic not exists in name-server.

**Comment by Kimmyzhao** [comment]
![QQ20190806-134719](https://user-images.githubusercontent.com/11455494/62514268-47ebac80-b851-11e9-9787-90c4ff894bff.png)

当我使用阿里云的 Rocket MQ 时，向 topic 中发送消息时，报以上错误，配置如下：
![QQ20190806-135333](https://user-images.githubusercontent.com/11455494/62514381-9dc05480-b851-11e9-8226-a8974f73ffac.png)

控制台 TOPIC 列表如下：
![QQ20190806-135505](https://user-images.githubusercontent.com/11455494/62514461-e11ac300-b851-11e9-9ef9-a5c94309d834.png)

如果用原生 rocket mq 是可以发送消息到 topic 中，是配置有错误么？

**Comment by fangjian0423** [comment]
@Kimmyzhao refer https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ#%E9%98%BF%E9%87%8C%E4%BA%91-mq-%E6%9C%8D%E5%8A%A1

**Comment by Kimmyzhao** [comment]
> @Kimmyzhao refer https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ#%E9%98%BF%E9%87%8C%E4%BA%91-mq-%E6%9C%8D%E5%8A%A1

谢谢，按照文档中配置还是提示相同的错误，配置信息如下
![QQ20190806-171215](https://user-images.githubusercontent.com/11455494/62527266-61025680-b86d-11e9-855f-940432bb28fe.png)

**Comment by fangjian0423** [comment]
本地只支持公网 region，上海 region 需要部署到 ECS 上。

**Comment by Kimmyzhao** [comment]
> 本地只支持公网 region，上海 region 需要部署到 ECS 上。

也就是说就算上海 region有公网 HTTP 接入点，也必须得把服务给部署到 ECS 上才能使用是么

**Comment by Kimmyzhao** [comment]
> 本地只支持公网 region，上海 region 需要部署到 ECS 上。

那是否有计划支持其他 region

**Comment by casparcao** [comment]
> 本地只支持公网 region，上海 region 需要部署到 ECS 上。

我的北京region无论是在本地还是部署到ECS都是报这个错.

`## 阿里云rocketmq注意事项
## topic 和 group 请以 实例id% 为前缀进行配置。比如 topic 为 "test"，需要配置成 "实例id%test"
## NameServer 的获取(配置中请去掉 http:// 前缀)

spring.cloud.stream.rocketmq.binder.name-server=xxxxxxxxxxxx.mqrest.cn-beijing.aliyuncs.com
spring.cloud.stream.rocketmq.binder.access-key=xxxxxxxxxx
spring.cloud.stream.rocketmq.binder.secret-key=xxxxxxxxxxxxxxxxxxxxxxx
spring.cloud.stream.rocketmq.binder.enable-msg-trace=false

spring.cloud.stream.binders.rabbit.type= rocketmq

##用户状态过期的交换机定义
spring.cloud.stream.bindings.user_state_expire_output.destination= MQ_INST_1132631421057777_BceQhE0M%TEST_TOPIC
spring.cloud.stream.bindings.user_state_expire_output.tags=user-state-expire`

而且也消费不到消息。
spring-cloud-stream-binder-rocketmq版本是2.2.0.RELEASE，
spring-cloud版本是Hoxton.SR3，spring boot版本2.2.X

**Comment by casparcao** [comment]
@fangjian0423 帮忙看下吧，谢谢
