### ISSUE TITLE
How to expose the REST metadata in the Dubbo services

### ISSUE THREAD

**Issue by fuyongde** [alibaba/spring-cloud-alibaba#690]
I wrote a demo like `spring-cloud-dubbo-provider-web-sample`，but when I use the gateway to access dubbo service, it warning `The Spring application[name : product-service] does not expose The REST metadata in the Dubbo services.`，the demo github is https://github.com/fuyongde/thanos
dubbo provider is `product-service` and gateway is `gateway2` in the demo. Where is the mistake?

**Comment by fangjian0423** [comment]
Hi @fuyongde 

add this dependency this `product-service` module:

```
<dependency>
    <groupId>io.github.openfeign</groupId>
    <artifactId>feign-jaxrs2</artifactId>
    <version>10.1.0</version>
</dependency>
```

There is some conflicts with feign-jaxrs2 of spring-cloud-alibaba-duboo.
