### ISSUE TITLE
Add more examples and improve documentation for spring-cloud-alibaba

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#692]
Now we have many examples about spring-cloud-alibaba.

Like sentinel-core, sentinel-zuul, sentinel-spring-cloud-gateway, nacos-discovery, nacos-config, rocketmq-produce-example, rocketmq-consumer-example, seata-example, dubbo-examples and so on.

Also we have docs about these in https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-docs/src/main .

Need adding more examples and improving documentation for spring-cloud-alibaba.

**Comment by panda-luo** [comment]
hands up for claiming this issue
