### ISSUE TITLE
springcloud-dubbo nacos做注册中心 不能动态动态发现服务

### ISSUE THREAD

**Issue by a59871442** [alibaba/spring-cloud-alibaba#695]
阐述一下我的想法。在dubbo动态目录组件RegistryDirectory，需要服务注册到注册中心，注册中心回调走此组件的notify方法。但是由于springcloud-alibaba容器整合dubbo的关系，用的也是此容器的注册组件，所以需要从容器中得到注册中心的新配置调用转入RegistryDirectory组件动态改变。我觉得问题可能是出现在AbstractSpringCloudRegistry的doSubscribeDubboServiceURLs方法中。 
ps：此框架非常好，希望支持的越来越多

**Comment by yandeyu** [comment]
同意

**Comment by q1991108** [comment]
me too

**Comment by liulongworm** [comment]
参考nacos与dubbo的整合方案后, 在配置文件中替换dubbo的注册中心地址为:`
dubbo:
   protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848`
可以实现先启动消费者再启动生产者仍可以正常访问, 但是如果重启生产者需要等待一段时间消费者才能正常访问

**Comment by xinmh1338863** [comment]
`dubbo.registry.address=nacos://127.0.0.1:8848`这种方式貌似不能支持Nacos的命名空间

**Comment by laiweijia** [comment]
2.1.1 R 
is fixed!

**Comment by lmxdawn** [comment]
怎么现在还是有这个问题，必须先启动服务提供者

**Comment by zhifuchen** [comment]
> 
ali的东西bug就是多
