### ISSUE TITLE
  Will all requests be defined as resources when Springboot is used to integrate Sentinel?(使用springboot 集成Sentinel 的时候所有请求都会被定义为资源吗？)

### ISSUE THREAD

**Issue by a120610114** [alibaba/spring-cloud-alibaba#697]
When I integrated Sentinel using the "spring-cloud-starter-alibaba-sentinel" approach, I found that even if I entered a non-existent URL request, I could see it in the cluster link and set flow control rules. Why? Isn't a request tagged with @SentinelResource defined as a resource?
（我在使用 “spring-cloud-starter-alibaba-sentinel“ 方式集成Sentinel 的时候发现，就算我输入不存在的URL请求 我在 簇点链路中也可以看的到 并且可以设置流控规则，这是为什么？ 难道不是只有用@SentinelResource标记的请求才会被定义为资源吗？）

**Comment by a120610114** [comment]
![图片](https://user-images.githubusercontent.com/26463863/58876455-bc468a00-8700-11e9-8cee-ebfcc3d2d76c.png)
![图片](https://user-images.githubusercontent.com/26463863/58876473-c8cae280-8700-11e9-8302-670a9944a862.png)

**Comment by fangjian0423** [comment]
see `CommonFilter`, you could set the url-pattern with `spring.cloud.sentinel.filter.url-patterns`
