### ISSUE TITLE
nacos config starter support more file format except yaml, properties

### ISSUE THREAD

**Issue by glameyzhou** [alibaba/spring-cloud-alibaba#698]
org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder#loadNacosData
当前仅支持properties、yaml文件格式，其他格式不支持。

场景是：我在配置一个value的时候，这个value可能是一个经过base64加密过的证书，如果使用yaml或者properties支持不了，因此想通过xml格式来实现。

**Comment by fangjian0423** [comment]
welcome to contribute it!

**Comment by zkzlx** [comment]
hands up for claiming this issue.

I am planning to extend the configuration to support both `json` and `xml` (扩展成可支持`json`和`xml`形式的配置)

The general idea is to append the hierarchical transformation key in `json` or `xml`. If `key` conflicts, the `value` of the latter will override the `value` of the former.

大致思路是将`json`或`xm`l中层级转换key的追加,若`key`有冲突,则`value`会覆盖;
* 覆盖的优先级:后面覆盖前面的.

for example: 

`xml` / `json` transform to `properties`

```xml
<top>
    <first>one</first>
    <sencond value="two">
        <third>three</third>
    </sencond>
</top>
```
```json
{
    "top":{
        "first":"one",
        "sencond":{
            "value":"two",
            "third":"three"
        }
    }
}
```
The result of the transformation(上述的`xml` / `json`转换成以下内容):

```properties
top.first=one
top.sencond=two
top.sencond.third=three
```

**Comment by fangjian0423** [comment]
👍

**Comment by Pocsd** [comment]
good

**Comment by zkzlx** [comment]
fix #866
