### ISSUE TITLE
Cloud-nacos should support temporary or non-temporary settings for instances

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/spring-cloud-alibaba#703]
**Which Component**
Nacos Discovery

**Is your feature request related to a problem? Please describe.**

Cloud-nacos should support temporary or non-temporary settings for instances

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fangjian0423** [comment]
spring cloud commons do not have some features about temporary instance and zookeeper discovery do not have any configuration items about temporary instance in `ZookeeperDiscoveryProperties`.

so i think we don't need to do it.

**Comment by chuntaojun** [comment]
However, there are some temporary or non-temporary setting items in the setting of nacos instance type. I think it is necessary to consider some characteristics of nacos itself when comparing with other horizontal Settings

**Comment by fangjian0423** [comment]
ok, need more guys to discuss this and need this feature.

So it it worth to do it.

**Comment by flystar32** [comment]
I don't think it is necessary to do this. 

Spring Cloud Application can't provider service after Application is Down. 

could you please provide a specific scene to describe why you need to register a  non-temporary service in you Spring Cloud Application.
