### ISSUE TITLE
EndpointId has a warning when registering and cannot be registered successfully

### ISSUE THREAD

**Issue by Tank-zhu** [alibaba/spring-cloud-alibaba#723]
spring-boot 版本是2.1.6

public final class EndpointId {
    private static final Log logger = LogFactory.getLog(EndpointId.class);
    private static Set<String> loggedWarnings = new HashSet();
    private static final Pattern VALID_PATTERN = Pattern.compile("[a-zA-Z0-9\\.\\-]+");
//这里有指定不可以使用 - 而我们的名字是叫 nacos-discovery   所以注册不成功
    private static final Pattern WARNING_PATTERN = Pattern.compile("[\\.\\-]+");
    private final String value;
    private final String lowerCaseValue;
    private final String lowerCaseAlphaNumeric;

    private EndpointId(String value) {
        Assert.hasText(value, "Value must not be empty");
        Assert.isTrue(VALID_PATTERN.matcher(value).matches(), "Value must only contain valid chars");
        Assert.isTrue(!Character.isDigit(value.charAt(0)), "Value must not start with a number");
        Assert.isTrue(!Character.isUpperCase(value.charAt(0)), "Value must not start with an uppercase letter");
//此处会进入警告日志
        if(WARNING_PATTERN.matcher(value).find()) {
            logWarning(value);
        }

        this.value = value;
        this.lowerCaseValue = value.toLowerCase(Locale.ENGLISH);
        this.lowerCaseAlphaNumeric = this.getAlphaNumerics(this.lowerCaseValue);
    }

log日志：
2019-06-28 21:13:50.122  WARN 13916 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'nacos-discovery' contains invalid characters, please migrate to a valid format.
2019-06-28 21:13:50.893  WARN 13916 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.

**Comment by fangjian0423** [comment]
The strategy of spring boot endpoint id in actuator is different in each version.

It's warning log and don't effect your application.

Service register failure is another problem. check your application and nacos log.
