### ISSUE TITLE
when the latest version(Spring Cloud Alibaba ) will be released?

### ISSUE THREAD

**Issue by GreyZeng** [alibaba/spring-cloud-alibaba#724]
**Which Component**
Nacos Discovery / Nacos Config

**Describe what problem you have encountered**
Since we need use some feature of nacos 1.0.1.RELEASE:
https://github.com/alibaba/nacos/issues/1416#issuecomment-507044650

But we use Spring Cloud Alibaba 0.9.0.RELEASE, it seems the latest RELEASE version of Spring Cloud Alibaba, in 0.9.0.RELEASE , the version of nacos is 1.0.0.RELEASE.

I want to know when the latest version(Spring Cloud Alibaba ) will be released.

**Comment by fangjian0423** [comment]
You could use 0.9.1.BUILD-SNAPSHOT firstly.

we are trying to release as soon as possible.

**Comment by fangjian0423** [comment]
related https://github.com/spring-cloud-incubator/spring-cloud-alibaba/pull/727.
