### ISSUE TITLE
Why is there no configuration format field for configuration details

### ISSUE THREAD

**Issue by bigbenfather** [alibaba/spring-cloud-alibaba#735]
**Which Component**
Nacos 

**Is your feature request related to a problem? Please describe.**
Why is there no configuration format field for configuration details？
配置详情页面为啥没有了“配置格式”字段？

**Comment by fangjian0423** [comment]
Format has always been there, pls put some screen captures to describe it.

**Comment by bigbenfather** [comment]
第二天就好了，缓存吗？

**Comment by fangjian0423** [comment]
Maybe it's a front-end bug.
