### ISSUE TITLE
spring-cloud-stream-binder-rocketmq Header value Codec Question

### ISSUE THREAD

**Issue by liudaomanbu** [alibaba/spring-cloud-alibaba#737]
**Which Component**
spring-cloud-stream-binder-rocketmq

**Describe the bug**
After using the spring-cloud-stream-binder-rocketmq module, since the value of the header in the message in the rocketmq must be a string, the message header value is currently converted to a string using the toString method when the non-string is set.

I think this behavior is not appropriate.

Especially for numeric types such as int, long, etc., the receiver of the message is likely to think that the value should be the type of the number placed.

Moreover, the toString method of the normal object has no way to deserialize most of the time, because the toString method is not considered to be a data format, nor is it recommended to deserialize from the toString method to an object, so there is no ready-made tool class that can be used. 
Such an operation.

According to my understanding, Spring's design Since the Header value is Object, it should be the object that needs to be serialized and deserialized as both the header and the body. It should be serialized and deserialized in the same way.

It should be a set of HttpMessageConvert that is shared or a separate set of Http requests....

Now it’s a bit tangled, how to deal with it.

Because in theory the serialization format of Message can be any format including jdk serialization, json, xml, produf, the final format can be non-string.

This way there is no way to follow Spring's original design ideas.

使用spring-cloud-stream-binder-rocketmq模块后,由于rocketmq 中 message里的 header 的 value 必须是 string,所以 message header value设置非字符串时当前会直接使用toString方法转换成string.
我认为这样的行为不太妥当.
尤其是int,long之类的数字类型,消息接收方很可能会认为值应该就是放入的数字类型.
而且普通对象的toString方法大部分时候没有办法反序列化的,因为toString方法并不被认为是一个数据格式,也不提倡从toString方法反序列化为对象,因此也没有什么现成工具类可以用于这样的操作.

按照我的理解,Spring的设计既然Header值是Object,那其实应该是把Header和body都作为需要序列化和反序列化的对象的,应该是用同样的方式序列化和反序列化的.
应该是共用或者另起一套Http请求的那套HttpMessageConvert列表的.....

现在这样有点纠结,怎么处理好呢.
因为理论上Message的序列化格式可以是包括jdk序列化,json,xml,produf的任何格式,最终格式可以是非字符串的.
这样就没办法遵循Spring原来的设计想法了.

**Expected behavior**
Think of alternatives

1. ToString like this, with specific instructions and hints in the documentation and doc (still can't solve the problem that the object toString method is difficult to deserialize)

2. Error reporting, the caller must pass in a String by error, and force the caller to manually process

3. Fixed the final format of json or xml is the internal conversion of the string converter, which is converted in advance between the sender and the consumer, so that the user has no perception (hopefully this)

想到的可选方案
1.像现在这样ToString,在文档和doc进行特定说明和提示(还是无法解决对象toString方法难以反序列化的问题)
2.进行报错,通过报错约束调用方必须传入String,强制调用方人工处理
3.固定用json或者xml这种最终格式是字符串的转换器内部转换,在发送者和消费者中都提前转换,使用户无感知(希望是这种)

**Screenshots**

**Comment by fangjian0423** [comment]
I will see how we can enhance it.

**Comment by liudaomanbu** [comment]
I see the logic of Kafka Header Mapper. SimpleKafka Header Mapper's logic is to serialize the value of header as String or byte [] header, so there is no need to deserialize it.

The logic of DefaultKafka Header Mapper is to serialize the value of header into byte [], and then deserialize it with jackson.

When deserialized, it is divided into two object types.

One is the class of trusted packages, the other is the class of untrusted packages.

If it is a trusted package class, it will be directly deserialized into the corresponding object, which is user-insensitive.

If it's a class of untrusted packages, it deserializes into the NonTrusted HeaderType object, which has a value and type, which is the full name of the String type class.



That is to say, on the whole, it is exactly what I thought before. Headers also need to be serialized and deserialized. They are basically user-insensitive.

Kafka's On Trusted Header Type is for security reasons.

KafkaHeaderMapper的逻辑我看了,SimpleKafkaHeaderMapper的逻辑是只把header的value为String或者byte[]的header进行序列化,所以也就不用反序列化.
而DefaultKafkaHeaderMapper的逻辑是用jackson去把header的value序列化为byte[],然后再反序列化.
然后反序列化的时候,它分两种对象类型.
一种是受信任的包的类,一种是不受信任的包的类.
如果是受信任的包的类,它会直接反序列化成对应对象,这就是用户无感知的.
如果是不受信任的包的类,它会反序列化成NonTrustedHeaderType这个对象,里面有一个value和type,type是String类型的类全名.

也就是说总体上来说,的确是我之前想的那样,Header也是需要序列化和反序列化的,基本上是用户无感知的.
Kafka的NonTrustedHeaderType是出于安全考虑的.

![image](https://user-images.githubusercontent.com/21155988/60864311-d15d8e00-a255-11e9-9052-8d45afe59a19.png)
