### ISSUE TITLE
I think We Should add a filter configuration property so that we Can honor HTTP_METHOD_SPECIFY.

### ISSUE THREAD

**Issue by eacdy** [alibaba/spring-cloud-alibaba#741]
在 `com.alibaba.csp.sentinel.adapter.servlet.CommonFilter#init` 中，有个
```
httpMethodSpecify = Boolean.parseBoolean(filterConfig.getInitParameter(HTTP_METHOD_SPECIFY));
```
而ComonFilter初始化时，代码：`org.springframework.cloud.alibaba.sentinel.SentinelWebAutoConfiguration#sentinelFilter`
并没有设置这个参数。

---

我认为应该在 `org.springframework.cloud.alibaba.sentinel.SentinelProperties.Filter` 加个属性，例如：httpMethodSpecify；
然后在
`org.springframework.cloud.alibaba.sentinel.SentinelWebAutoConfiguration#sentinelFilter`
初始化CommonFilter的时候，改成：
```
Filter filter = new CommonFilter();
registration.setFilter(filter);
registration.setOrder(filterConfig.getOrder());
registration.addInitParameter("HTTP_METHOD_SPECIFY", filterConfig.getHttpMethodSpecify());
```
这样，就可以实现资源名称带有`HTTP方法:` 的前缀了。

希望改进下，最近996，不然我就提PR了。

**Comment by eacdy** [comment]
@fangjian0423 @flystar32

**Comment by fangjian0423** [comment]
After upgrade pkg name & maven coordinate, i will add this param.

**Comment by eacdy** [comment]
Thanks a lot.
