### ISSUE TITLE
spring cloud alibaba sentinel 

### ISSUE THREAD

**Issue by WunHwanTseng** [alibaba/spring-cloud-alibaba#742]
spring cloud alibaba sentinel version can update to v 1,6,2?

**Comment by fangjian0423** [comment]
we have updated it in https://github.com/alibaba/spring-cloud-alibaba/blob/master/alibaba-spring-cloud-dependencies/pom.xml#L21.

Also we will release new version next week.

**Comment by WunHwanTseng** [comment]
@fangjian0423 thx
