### ISSUE TITLE
Sentinel Dashboard - How to support more than 500 application cluster?

### ISSUE THREAD

**Issue by ghost0224** [alibaba/spring-cloud-alibaba#745]
Sentinel Dashboard

I noticed that "the aggregated runtime info of a cluster with less than 500 nodes."

So how to support more than 500 nodes?

**Comment by fangjian0423** [comment]
i think @sczyh30 is well suited to answer the question.

**Comment by sczyh30** [comment]
Hi, for large-scale clusters, it's necessary to build a **cluster** of Sentinel dashboard for yourself (refactor is needed). You may refer to https://github.com/alibaba/Sentinel/issues/363 and https://github.com/alibaba/Sentinel/issues/241
