### ISSUE TITLE
nacos Unable to register dynamically

### ISSUE THREAD

**Issue by huangyangcong** [alibaba/spring-cloud-alibaba#753]
**Which Component**
nacos,spring-cloud-alibaba-dubbo

**Describe the bug**
先启动消费者（check=false），然后启动提供者无法自动发现注册
Starting a consumer and then starting a provider does not automatically discover the registration

**Additional context**
e.g.  spring-cloud-alibaba0.9.1.BUILD-SNAPSHOT,nacos1.0.1

**Comment by q1991108** [comment]
我也是
me too

**Comment by tenmatrix** [comment]
me too.
i tried to run examples in 0.9.0release and 2.1.0release,with nacos 1.0.1
run spring-cloud-dubbo-consumer-sample first,and then run spring-cloud-dubbo-provider-sample.
the print in "spring-cloud-dubbo-consumer-sample" is

**Comment by fangjian0423** [comment]
I will try to fix it soon.

**Comment by LayJustDoIt** [comment]
> I will try to fix it soon.

Hey, bro fangjian. 
        After my test, this problem has been fixed, but there is a new problem. When I stop all the services, start the consumer immediately and then start the provider. The call is still unsuccessful, and vice versa. Please verify. thank you :)

**Comment by yub1ng** [comment]
This error occurred on the server，use WebHook trigger Jenkins execute docker-compose to rebuild and restart services image, then some consumer service will report the error.
This is log:

![dubbo error](https://user-images.githubusercontent.com/34766340/64154392-597d9f80-ce63-11e9-892c-17a3a6560e34.png)

But when i test a little demo project, the error doesn't occurred, maybe the demo project has not enough services to trigger the error.

**Comment by huangyangcong** [comment]
@fangjian0423 
这个还是没有处理成功，
com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry#doSubscribeDubboMetadataServiceURLs，只有一次获取元数据，只绑定一个provider，如果代理的提供者关闭，那提供者就无法更新暴露服务的路由信息
建议：
1：添加nacos监听事件，如果提供者关闭了，删除代理重新获取实例生成代理
2：com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#initSubscribedDubboMetadataServiceURL，方法中一直添加```subscribedDubboMetadataServiceURLs.add(serviceKey, dubboMetadataServiceURL);``url没法删除已经失效的，建议在生成代理时```com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#initSubscribedDubboMetadataService(java.lang.String, java.util.List<org.springframework.cloud.client.ServiceInstance>)```，先删除service的MetadataServiceURL

**Comment by wangzihaogithub** [comment]
大家好, 我已经提交了改正的代码, 请过目.

https://github.com/alibaba/spring-cloud-alibaba/pull/1250


解决注册中心推送新IP的时候，dubbo服务一直不替换老IP或端口的BUG。


刷新客户端的逻辑是，先去元数据服务查询接口定义信息， 再用接口信息去重建客户端内部的Invoker对象 {@link Invoker}

但是如果元数据服务的IP或端口发生了变化，那么就无法获取接口信息，客户端Invoker对象也就无法重建。

我提交的这个代码就是在执行查询元数据前，先把元数据服务的实例换成最新的IP， 这样查询元数据就能正常获取到元数据了。

**Comment by wangzihaogithub** [comment]
> @fangjian0423
> 这个还是没有处理成功，
> com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry#doSubscribeDubboMetadataServiceURLs，只有一次获取元数据，只绑定一个provider，如果代理的提供者关闭，那提供者就无法更新暴露服务的路由信息
> 建议：
> 1：添加nacos监听事件，如果提供者关闭了，删除代理重新获取实例生成代理
> 2：com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#initSubscribedDubboMetadataServiceURL，方法中一直添加`` subscribedDubboMetadataServiceURLs.add(serviceKey, dubboMetadataServiceURL);``url没法删除已经失效的，建议在生成代理时 ``com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#initSubscribedDubboMetadataService(java.lang.String, java.util.List<org.springframework.cloud.client.ServiceInstance>)```，先删除service的MetadataServiceURL

你可以用我发的这个类先解决问题.
用这个
https://github.com/wangzihaogithub/spring-cloud-alibaba-dubbo-issues-1595

1. 重写AbstractSpringCloudRegistry.class以解决获得支持

  同时需要在yml里加 
    dubbo.cloud.registry-type: 'spring-cloud'
    dubbo.consumer.reconnect: true
    dubbo.consumer.parameters.send.reconnect: true

  1.服务挂不上No provider
  2.一直掉老IP/端口 
  3.允许提供者与消费者无序启动 
  4.允许 -kill 9
2. 重写DubboGenericServiceFactory.class以解决获得支持

  1.解决接入其他注册中心(例：zk)的dubbo接口时，接口元信息可能会掉到其他注册中心上
  2.解决一直掉老IP/端口
3. 重写ReferenceAnnotationBeanPostProcessor.class以解决获得支持

  1.解决升级dubbo-2.7.15后，自定义注解用不了
4. 重写NetUtils.class以解决获得支持

  1.解决开VPN时, 有时获取VPN的IP，有时获取正常IP，导致服务掉不通。 
  2.解决开发环境多网卡时，IP总随机。

**Comment by ChiHoc** [comment]
> > @fangjian0423
> > 这个还是没有处理成功，
> > com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry#doSubscribeDubboMetadataServiceURLs，只有一次获取元数据，只绑定一个provider，如果代理的提供者关闭，那提供者就无法更新暴露服务的路由信息
> > 建议：
> > 1：添加nacos监听事件，如果提供者关闭了，删除代理重新获取实例生成代理
> > 2：com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#initSubscribedDubboMetadataServiceURL，方法中一直添加` subscribedDubboMetadataServiceURLs.add(serviceKey, dubboMetadataServiceURL);`url没法删除已经失效的，建议在生成代理时 ``com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#initSubscribedDubboMetadataService(java.lang.String, java.util.List<org.springframework.cloud.client.ServiceInstance>)```，先删除service的MetadataServiceURL
> 
> 你可以用我发的这个类先解决问题.
> 
> @bean
> public IGDubboRegistryInvokerRebuildListener dubboRegistryInvokerRebuildListener(){
> return new IGDubboRegistryInvokerRebuildListener();
> }
> 
> [IGDubboRegistryInvokerRebuildListener.txt](https://github.com/alibaba/spring-cloud-alibaba/files/4328894/IGDubboRegistryInvokerRebuildListener.txt)

测试过可以解决provider ip改变的问题，但是发现消费者会不停对已关闭的provider做doconnect操作，如果provider的ip改变10次，就会有10个时间轮实例做轮询。

**Comment by wangzihaogithub** [comment]
是的, 那个解决起来比较麻烦, 需要改动较多, 我已经提了issue, 但是起码现在能保证你的业务能正常用了.

https://github.com/alibaba/spring-cloud-alibaba/issues/753#issuecomment-599349746

**Comment by lcg72** [comment]
@wangzihaogithub
https://github.com/alibaba/spring-cloud-alibaba/pull/1277真正在最后一个provider关闭通道以后，如果新注册provider，repository.initializeMetadata(serviceName)将报错。
其实将[fix #753] https://github.com/alibaba/spring-cloud-alibaba/issues/753 #1274回滚以后，只要最后一个provider关闭的时候，关闭通道，就不会有问题。何况一些清理工作还是需要在最后一个provider关闭的时候清理为好。
