### ISSUE TITLE
[Discuss] the package name & maven groupId & version number

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#761]
## [Discuss] the package name & maven groupId & version number

Hi, everyone! now spring-cloud-alibaba have moved away from spring-cloud repository.

The official policy will be announced in the future by spring-cloud team to explain why spring-cloud-alibaba move away from spring-cloud repository.

The package name will be changed from `org.springframework.cloud.alibaba` to `com.alibaba.cloud`.

The maven groupId change from `org.springframework.cloud` to `com.alibaba.cloud`. maven artifactId will be keep, we think the fewer modification the better.

since the package name & maven groupId modification, the version number will be changed. This is the mapping table between version number modification and Spring Cloud version number.

|  Spring Cloud Alibaba Version before change      |    Spring Cloud Alibaba Version after change    |  Spring Cloud Version  |
| :----  | :---- | :----- |
| 0.1.x    |  1.0.x    |    Spring Cloud Edgware     |
| 0.2.x   |  1.1.x   |        Spring Cloud Finchley         |
| 0.9.x   |  1.2.x   |        Spring Cloud Greenwich         |

These modifications will effect the usage of spring-cloud-alibaba, we need the suggestions about package name & maven groupId & version number from community, please reply & discuss in the issue.

## [讨论] 关于包名 & maven groupId & 版本号的修改

大家好，spring-cloud-alibaba 目前已经从 spring-cloud 的 github 仓库迁移到了 alibaba 仓库下。

spring-cloud 团队会在未来发出官方的公告解释为什么 spring-cloud-alibaba 会迁移到 alibaba 仓库下。

迁移意味着修改，下面是一些改动点的说明。

包名从 `org.springframework.cloud.alibaba` 变成 `com.alibaba.cloud`。

maven groupId 从 `org.springframework.cloud` 变成 `com.alibaba.cloud`. maven artifactId 会保持原有的名字，我们认为我们改的越少，大家的改动也就越少。

由于包名和 maven groupId 进行了修改，版本号也需要进行修改，这是版本号修改前后跟 Spring Cloud 版本号的映射关系表：

|  Spring Cloud Alibaba 修改前的版本      |    Spring Cloud Alibaba 修改后的版本    |  Spring Cloud 版本  |
| :----  | :---- | :----- |
| 0.1.x    |  1.0.x    |    Spring Cloud Edgware     |
| 0.2.x   |  1.1.x   |        Spring Cloud Finchley         |
| 0.9.x   |  1.2.x   |        Spring Cloud Greenwich         |

这些包名和 maven groupId 以及版本号的修改会影响目前 spring-cloud-alibaba 的使用者，我们需要社区的意见，也想听听社区的声音。大家可以在 issue 里进行答复和讨论。

**Comment by xiejiashuai** [comment]
This looks very good. Well Done.

**Comment by xshans** [comment]
perfect

**Comment by caorenpeng-kaer** [comment]
我觉得OK，希望阿里巴巴 越来越好

**Comment by anpu2018** [comment]
The promotion of nacos products is obviously lagging behind with other components. Can we speed up the iteration?

**Comment by nisiyong** [comment]
`com.alibaba.cloud`感觉这个名字含义太大了，有点歧义。这里的`cloud`其实是特定spring而言

**Comment by vikenlove** [comment]
唯一的建议 是希望 其他如nacos、seata sentinel  dubbo 等 cloud 依赖POM版本号能及时更新。是在是更新的太慢了。导致无法升级。

**Comment by senzhu** [comment]
com.alibaba.springframework.cloud

**Comment by pigxcloud** [comment]
**前排支持！**

**Comment by zhendong590** [comment]
666

**Comment by yanzhaohu** [comment]
非常好，希望未来有一个完整的独立的微服务体系，赶超spring cloud!

**Comment by eacdy** [comment]
我认为如果

| 前版本 | After |
| ------ | ----- |
| 0.1    | 1.0   |
| 0.2    | 1.1   |
| 0.3    | 1.2   |

这样的方式有点模糊，特别是对使用0.9的童鞋来说，很可能会懵。

正常的逻辑，1.0比0.9新，应该支持更高版本；但却不是这样……

我建议采用类似Spring Cloud的版本命名方式：

| 前版本 | After     |
| ------ | --------- |
| 0.1    | Edgware   |
| 0.2    | Finchley  |
| 0.9    | Greenwich |

这样相对清晰一些。

**Comment by weixing1204** [comment]
包名改了之后，感觉像是alibaba的云组件，跟spring-cloud没啥关系了。
不知道这样改了之后，最终还是按照spring-cloud的标准，还是会脱离spring-cloud，发展自己标准的微服务组件？

**Comment by fangjian0423** [comment]
> 包名改了之后，感觉像是alibaba的云组件，跟spring-cloud没啥关系了。
> 不知道这样改了之后，最终还是按照spring-cloud的标准，还是会脱离spring-cloud，发展自己标准的微服务组件？

并没有脱离 spring-cloud，跟 spring cloud 官方还是合作的关系，可以参考 spring-cloud leader spencer 的留言:  https://github.com/alibaba/spring-cloud-alibaba/issues/739#issuecomment-509394980

**Comment by fangjian0423** [comment]
> The promotion of nacos products is obviously lagging behind with other components. Can we speed up the iteration?

now we have our own release train, we can release new version by ourselves.

but we must make sure the modifications about pkg name & maven groupId & version number, it can't be changed if we use these new value.

**Comment by penghao03** [comment]
包名，groupId 我觉得ok,关于版本号，有个个人想法：是不是可以参考sb和sc的版本号规律，毕竟sca三个主版本是根据sb和sc的不同版本来区分的；如果是1.0/1.1/1.2可能还需要专门理解相应的版本对应关系，对于刚接触的来说并不是太友好，何不如遵照sb的版本特点:

before | After
-- | --
0.1 | 1.5.x
0.2 | 2.0.x
0.9 | 2.1.x
第三位x可以根据alibaba体系下各个组件的版本迭代速度来自由把控；

也可以像上面周立大佬说的

前版本 | After
-- | --
0.1 | Edgware
0.2 | Finchley
0.9 | Greenwich

哈哈，个人意见，大佬勿喷！

**Comment by IsaacZhang0614** [comment]
是否修改个人建议是找到或者可以给筒子们阐述一下为什么要修改？
1. 目前来看，修改为`com.alibaba.cloud`确实会带来很大的歧义，毕竟这里的`cloud` 和我们常用的`ali cloud`很容易混淆。
2. 从长远来说，这样的修改意义非凡，但是不要像17年之前的dubbo一样'伟'了...广大国内用户其实蛮希望能出一个领头羊来做技术演进的...而且目前阿里是首选也是唯一。
3. 培养用户转变`spring cloud`到`alibaba cloud`的难度系数多大，如何能加速落地，增强认知。

**Comment by Isaac-Zhang** [comment]
> The project did not get kicked out :-) One of the reasons for the move is so that the Alibaba team is not bottlenecked by the spring team for releases. By moving to their own org, they are administrators of the project and #734 allows Alibaba to perform their own releases using their own maven coordinates. Look for continued cooperation, joint blog posts announcing releases and more!  

看到这个，我理解的迁移项目是因为release受阻，确实没看出来为什么要改`groupId & version`...

**Comment by Lovnx** [comment]
同觉得版本没有什么辨识度！

before | After
-- | --
0.1 | 1.5.x
0.2 | 2.0.x
0.9 | 2.1.x

既然SC官方用伦敦地铁站来命名版本，那我们可以用北京地铁站或者中国地名啊，比如这样

前版本 | SC | SCA version
-- | -- | --
0.1 | Edgware |  xiErqi
0.2 | Finchley | Fuxingmen
0.9 | Greenwich | yongheGong

**Comment by fangjian0423** [comment]
> > The project did not get kicked out :-) One of the reasons for the move is so that the Alibaba team is not bottlenecked by the spring team for releases. By moving to their own org, they are administrators of the project and #734 allows Alibaba to perform their own releases using their own maven coordinates. Look for continued cooperation, joint blog posts announcing releases and more!
> 
> 看到这个，我理解的迁移项目是因为release受阻，确实没看出来为什么要改`groupId & version`...

1. release 受阻只是其中一个原因
2. maven central 发版本，不同的 org 是有不同的账号的，无法跨 org 发版本。所以必须切换成 alibaba oss 对应的 groupId。 version 的话因为 pkg name & maven coordinate 都改了，换个全新的版本号更加适合

**Comment by Isaac-Zhang** [comment]
> > > The project did not get kicked out :-) One of the reasons for the move is so that the Alibaba team is not bottlenecked by the spring team for releases. By moving to their own org, they are administrators of the project and #734 allows Alibaba to perform their own releases using their own maven coordinates. Look for continued cooperation, joint blog posts announcing releases and more!
> > 
> > 
> > 看到这个，我理解的迁移项目是因为release受阻，确实没看出来为什么要改`groupId & version`...
> 
> 1. release 受阻只是其中一个原因
> 2. �maven central 发版本，不同的 org 是有不同的账号的，无法跨 org 发版本。所以必须切换成 alibaba oss 对应的 groupId。 version 的话因为 pkg name & maven coordinate 都改了，换个全新的版本号更加适合

将[http://maven.aliyun.com/mvn/](http://maven.aliyun.com/mvn/) 作为主 `maven central`,让他们follow us. ( ̀⌄ ́)

**Comment by liudaomanbu** [comment]
> > > The project did not get kicked out :-) One of the reasons for the move is so that the Alibaba team is not bottlenecked by the spring team for releases. By moving to their own org, they are administrators of the project and #734 allows Alibaba to perform their own releases using their own maven coordinates. Look for continued cooperation, joint blog posts announcing releases and more!
> > 
> > 
> > 看到这个，我理解的迁移项目是因为release受阻，确实没看出来为什么要改`groupId & version`...
> 
> 1. release 受阻只是其中一个原因
> 2. �maven central 发版本，不同的 org 是有不同的账号的，无法跨 org 发版本。所以必须切换成 alibaba oss 对应的 groupId。 version 的话因为 pkg name & maven coordinate 都改了，换个全新的版本号更加适合

个人感觉com.alibaba.cloud也是有点误导性的包名,感觉像是阿里云体系一样的概念.
虽然有org的relase问题,所以必须以com.alibaba开头.
那是不是可以考虑包名是com.alibaba.spring.cloud?
这样能够让人明白这不是阿里云体系而是spring cloud体系?

**Comment by liaocanjie** [comment]
别争了，用汉字做版本号。

**Comment by WhaleCloud-platform** [comment]
我觉得alibaba-cloud算spring-cloud里面的一个体系，基于spring-cloud来的。首先包名没有spring-cloud，这样感觉是跟spring-cloud平等的。其实不是。还有版本 我觉得还是跟spring-cloud走，不要用数字。如果使用数字1.x、2.x ，会让不懂的人无法跟spring-cloud版本做映射。还要去百度才知道。

**Comment by GreedyPirate** [comment]
关于版本号，个人支持用数字做版本号，简单直观，对新人友好，也容易表示小版本，而且我很好奇SC 26个字母用完了该用啥

**Comment by xiejiashuai** [comment]
> 别争了，用汉字做版本号。


> 我觉得alibaba-cloud算spring-cloud里面的一个体系，基于spring-cloud来的。首先包名没有spring-cloud，这样感觉是跟spring-cloud平等的。其实不是。还有版本 我觉得还是跟spring-cloud走，不要用数字。如果使用数字1.x、2.x ，会让不懂的人无法跟spring-cloud版本做映射。还要去百度才知道。

- 版本号确实使用官方的英文字母让新手更加容易上手，用户体验度更好

**Comment by novicezk** [comment]
数字版本号+1 ， 文档首页写明跟 Spring Cloud 版本号的映射关系就好了

**Comment by slievrly** [comment]
可否直接使用spring cloud的版本号，E,F,G系列，这样减少了版本对齐的思维转换，更贴近spring cloud.

**Comment by anpu2018** [comment]
I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
The point is: why is netflix still available?like ribbon, etc.

**Comment by nisang** [comment]
改动包名，什么的都是小事了，但是改动了，能否针对阿里系的所有组件进行支持
如fastjson，druid,dubbo
能比spring cloud 迭代要快些，jdk方面的支持能否向jdk11靠，编码方面，能否采用更灵活的新特性支持。
jdk 11 比 jdk 8 其提升的效率是1.2 倍，cpu中断时间大幅缩小
grpc支持什么的，都能使用最新的更快的工具

**Comment by xiejiashuai** [comment]
> I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
> The point is: why is netflix still available?like ribbon, etc.

- I think the answer is this netlifx oss has already been used widely,once moved from spring cloud can cause to many users to changed

**Comment by Isaac-Zhang** [comment]
> I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
> The point is: why is netflix still available?like ribbon, etc.

Ali is the company that can challenge Spring's dominance.
Is Spring afraid? (>_<)

**Comment by xiejiashuai** [comment]
> > I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
> > The point is: why is netflix still available?like ribbon, etc.
> 
> Ali is the company that can challenge Spring's dominance.
> Is Spring afraid? (>_<)

- I think It's a partnership for Ali and Spring

**Comment by anpu2018** [comment]
> > I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
> > The point is: why is netflix still available?like ribbon, etc.
> 
> * I think the answer is this netlifx oss has already been used widely,once moved from spring cloud can cause to many users to changed

As said, the so-called spring requirements change becomes meaningless because there is no concept of "unification"

**Comment by anpu2018** [comment]
> Ali is the company that can challenge Spring's dominance.

this is a joke,hah

**Comment by yanzhaohu** [comment]
阿里的员工都有花名，其实开源项目的版本也可以按照花名，或者按照修真类的小说的等级来进行版本号

**Comment by ly641921791** [comment]
I think using numbers as version numbers is more intuitive for the order of the versions.
Not everyone wants to know how many stations in London's subway, what is the name of each station?

**Comment by fangjian0423** [comment]
I prefer using version numbers, 1.0 for E, 1.1 for F & 1.2 for G.

when spring-cloud-alibaba in spring-cloud-incubator repository, we use 0.1 & 0.2 & 0.9 version number.

1.0 means a new start and we should start with it.

but some developers will confuse about it, because 1.0 is higher than 0.9, but 1.0 is for E, 0.9 is for G.

=============

我个人更喜欢数字的版本号，1.0 对应 E，1.1 对应 F，1.2 对应 G。

当 spring-cloud-alibaba 在 spring-cloud-incubator 孵化器仓库的时候，我们就使用了 0.1, 0.2 和 0.9 版本号。

1.0 意味着一个新的开始，我们应该从 1.0 开始。

但是肯定有一些开发者对版本号有疑惑，因为 1.0 版本号高于 0.9，但是 1.0 对应 E 版本，0.9 却对应 G 版本。

**Comment by wuShanYunYu0612** [comment]
maven groupId 的毕竟是SB的实现com.alibaba.cloud 让人感觉有点脱离 可以 com.alibaba.spring.cloud.
版本好，更倾向于使用字母，根随sc的版本字母

**Comment by mgliang** [comment]
版本号+1 应该是的大多数人的共识吧

**Comment by xiejiashuai** [comment]
> > > I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
> > > The point is: why is netflix still available?like ribbon, etc.
> > 
> > 
> > 
> > * I think the answer is this netlifx oss has already been used widely,once moved from spring cloud can cause to many users to changed
> 
> As said, the so-called spring requirements change becomes meaningless because there is no concept of "unification"

- Hours ago ,I ask Spencer Gibb same question , his answer is following
  - Because the spring team maintains them and owns springframework.org

**Comment by anpu2018** [comment]
> > > > I believe that more than one person is curious: why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not, is it just because of release? Or because of some other reasons for project incubation, Sorry, some of the previous dubbo things affected the view of this matter.
> > > > The point is: why is netflix still available?like ribbon, etc.
> > > 
> > > 
> > > 
> > > * I think the answer is this netlifx oss has already been used widely,once moved from spring cloud can cause to many users to changed
> > 
> > 
> > As said, the so-called spring requirements change becomes meaningless because there is no concept of "unification"
> 
> * Hours ago ,I ask Spencer Gibb same question , his answer is following
>   
>   * Because the spring team maintains them and owns springframework.org

So? Netfilx also needs to be changed?

**Comment by fangjian0423** [comment]
天干地支，简称为干支，源自中国远古时代对天象的观测。

版本号使用 "天干地支" 是个不错的建议:

十天干：
甲（jiǎ）、乙（yǐ）、丙（bǐng）、丁（dīng）、戊（wù）、己（jǐ）、庚（gēng）、辛（xīn）、壬（rén）、癸（guǐ）

十二地支：
子（zǐ）、丑（chǒu）、寅（yín）、卯（mǎo）、辰（chén）、巳（sì）、午（wǔ）、未（wèi）、申（shēn）、酉（yǒu）、戌（xū）、亥（hài）。其中子、寅、辰、午、申、戌为阳支，丑、卯、巳、未、酉、亥为阴支

十二地支对应十二生肖，十二生效也有对应的英文名:

对应关系: 子-鼠，丑-牛，寅-虎，卯-兔，辰-龙，巳-蛇， 午-马，未-羊，申-猴，酉-鸡，戌-狗，亥-猪。

Rat 鼠，Ox 牛，Tiger 虎，Rabbit 兔，Dragon 龙，Snake 蛇，Horse 马，Goat 羊，Monkey 猴，Rooster 鸡，Dog 狗，Boar 猪

更加倾向于选择十二生效 😁

**Comment by Lovnx** [comment]
> 天干地支，简称为干支，源自中国远古时代对天象的观测。
> 
> 版本号使用 "天干地支" 是个不错的建议:
> 
> 十天干：
> 甲（jiǎ）、乙（yǐ）、丙（bǐng）、丁（dīng）、戊（wù）、己（jǐ）、庚（gēng）、辛（xīn）、壬（rén）、癸（guǐ）
> 
> 十二地支：
> 子（zǐ）、丑（chǒu）、寅（yín）、卯（mǎo）、辰（chén）、巳（sì）、午（wǔ）、未（wèi）、申（shēn）、酉（yǒu）、戌（xū）、亥（hài）。其中子、寅、辰、午、申、戌为阳支，丑、卯、巳、未、酉、亥为阴支
> 
> 十二地支对应十二生肖，十二生效也有对应的英文名:
> 
> 地支和生肖的对应关系: 子-鼠，丑-牛，寅-虎，卯-兔，辰-龙，巳-蛇， 午-马，未-羊，申-猴，酉-鸡，戌-狗，亥-猪。
> 
> 生肖英文名: Rat 鼠，Ox 牛，Tiger 虎，Rabbit 兔，Dragon 龙，Snake 蛇，Horse 马，Goat 羊，Monkey 猴，Rooster 鸡，Dog 狗，Boar 猪
> 
> 更加倾向于选择十二生肖 😁
> 
> 从 Edgware 开始支持， Rat 支持 Edgware， Ox 支持 Finchley， Tiger 支持 Greenwich，Rabbit 支持 Hoxton ....

感觉要首字母相同才好😁
还真不好找。。。

**Comment by fangjian0423** [comment]
> > 天干地支，简称为干支，源自中国远古时代对天象的观测。
> > 版本号使用 "天干地支" 是个不错的建议:
> > 十天干：
> > 甲（jiǎ）、乙（yǐ）、丙（bǐng）、丁（dīng）、戊（wù）、己（jǐ）、庚（gēng）、辛（xīn）、壬（rén）、癸（guǐ）
> > 十二地支：
> > 子（zǐ）、丑（chǒu）、寅（yín）、卯（mǎo）、辰（chén）、巳（sì）、午（wǔ）、未（wèi）、申（shēn）、酉（yǒu）、戌（xū）、亥（hài）。其中子、寅、辰、午、申、戌为阳支，丑、卯、巳、未、酉、亥为阴支
> > 十二地支对应十二生肖，十二生效也有对应的英文名:
> > 地支和生肖的对应关系: 子-鼠，丑-牛，寅-虎，卯-兔，辰-龙，巳-蛇， 午-马，未-羊，申-猴，酉-鸡，戌-狗，亥-猪。
> > 生肖英文名: Rat 鼠，Ox 牛，Tiger 虎，Rabbit 兔，Dragon 龙，Snake 蛇，Horse 马，Goat 羊，Monkey 猴，Rooster 鸡，Dog 狗，Boar 猪
> > 更加倾向于选择十二生肖 😁
> > 从 Edgware 开始支持， Rat 支持 Edgware， Ox 支持 Finchley， Tiger 支持 Greenwich，Rabbit 支持 Hoxton ....
> 
> 感觉要首字母相同才好😁
> 还真不好找。。。

如果选择中国特色的东西的话，首字母确实是不好对上的。

不过感觉还可以，Edgware 开始支持，从十二生肖 Rat 鼠可以。 😁

**Comment by khiker007** [comment]
when the new version will release is my only want to know

**Comment by fangjian0423** [comment]
official policy announcement: https://spring.io/blog/2019/07/24/simplifying-the-spring-cloud-release-train

**Comment by ACXNX** [comment]
> 关于版本号，个人支持用数字做版本号，简单直观，对新人友好，也容易表示小版本，而且我很好奇SC 26个字母用完了该用啥

参考Ubuntu使用两位首字母作版本号

**Comment by fangjian0423** [comment]
目前决定 bom 版本号采用跟 Spring Cloud 一样的伦敦地铁站名，starter & 模块版本号采用数字:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>Greenwich.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Greenwich.RELEASE 内部的 starter 版本号为 1.2.x:

```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>1.2.0</version>
</dependency>
```

版本对应关系:

|  Spring Cloud Alibaba Bom 版本号      |    Starter & 模块名 版本号    |  Spring Cloud 版本号  |
| :----  | :---- | :----- |
| Spring Cloud Alibaba Edgware    |  1.0.x  |    Spring Cloud Edgware     |
| Spring Cloud Alibaba Finchley   |  1.1.x   |        Spring Cloud Finchley         |
| Spring Cloud Alibaba Greenwich  |  1.2.x   |        Spring Cloud Greenwich         |

**Comment by fangjian0423** [comment]
由于两边版本节奏不一样，以 Greenwich 为例

|  Spring Cloud Alibaba Bom 版本号      |    Starter & 模块名 版本号    |  Spring Cloud 版本号  |
| :----  | :---- | :----- |
| Spring Cloud Alibaba Greenwich.RELEASE    |  1.0.0  |    Spring Cloud Greenwich.SR2     |
| Spring Cloud Alibaba Greenwich.SR1    |  1.0.1  |    Spring Cloud Greenwich.SR3     |
| Spring Cloud Alibaba Greenwich.SR2    |  1.0.2  |    Spring Cloud Greenwich.SR3     |
| Spring Cloud Alibaba Greenwich.SR3    |  1.0.3  |    Spring Cloud Greenwich.SR4     |

虽然都是 Greenwich 大版本，但是小版本号不一样。以 Spring Cloud Greenwich.SR4 为例，需要记住 Spring Cloud Alibaba 的版本为 Greenwich.SR3，Starter & 模块名版本为 1.0.3。这样需要记住 3 个版本号。

参考孵化器时的做法，Bom 的版本号跟 Starter & 模块名 版本号一致。这样需要记住 2 个版本号:

|  Spring Cloud Alibaba Bom 版本号      |    Starter & 模块名 版本号    |  Spring Cloud 版本号  |
| :----  | :---- | :----- |
| Spring Cloud Alibaba 1.0.0    |  1.0.0  |    Spring Cloud Greenwich.SR2     |
| Spring Cloud Alibaba 1.0.1    |  1.0.1  |    Spring Cloud Greenwich.SR3     |
| Spring Cloud Alibaba 1.0.2    |  1.0.2  |    Spring Cloud Greenwich.SR4     |

**Comment by romeoblog** [comment]
只需记住 2 个版本号 比 记住 3 个版本号 显得更方便直接

**Comment by flystar32** [comment]
倾向于这种模式的，请给这条回复点赞。

|  Spring Cloud Alibaba Bom 版本号      |    Starter & 模块名 版本号    |  Spring Cloud 版本号  |
| :----  | :---- | :----- |
| Spring Cloud Alibaba 1.0.x    |  1.0.x  |    Spring Cloud Edgware     |
| Spring Cloud Alibaba 1.1.x    |  1.1.x  |    Spring Cloud Finchley     |
| Spring Cloud Alibaba 1.2.x    |  1.2.x  |    Spring Cloud Greenwich     |

**Comment by flystar32** [comment]
倾向于这种模式的，请给这条回复点赞。

|  Spring Cloud Alibaba Bom 版本号      |    Starter & 模块名 版本号    |  Spring Cloud 版本号  |
| :----  | :---- | :----- |
| Spring Cloud Alibaba 1.5.x    |  1.5.x  |    Spring Cloud Edgware     |
| Spring Cloud Alibaba 2.0.x    |  2.0.x  |    Spring Cloud Finchley     |
| Spring Cloud Alibaba 2.1.x    |  2.1.x  |    Spring Cloud Greenwich     |

**Comment by HaojunRen** [comment]
跟随Spring Boot版本号，SCA的发布频率和SB的发布频率不一致，例如SB版本为2.1.7，SCA也许是2.1.12，也会造成一定的困惑。

**Comment by HaojunRen** [comment]
1.0.x，1.1.x，1.2.x方式也有缺陷，无论到多少年，SCA大版本号永远是1。不懂的人以为SCA永远没在升级。
建议E版1.x，F版2.x，G版3.x，H版4.x...这样就更加一目了然

**Comment by flystar32** [comment]
> 跟随Spring Boot版本号，SCA的发布频率和SB的发布频率不一致，例如SB版本为2.1.7，SCA也许是2.1.12，也会造成一定的困惑。

是的，不过目前没有想到更好的版本，军哥有其他想法也提一下。主要是希望社区使用起来不需要理解太多的东西，越简单越好。

**Comment by flystar32** [comment]
> 1.0.x，1.1.x，1.2.x方式也有缺陷，无论到多少年，SCA大版本号永远是1。不懂的人以为SCA永远没在升级。
> 建议E版1.x，F版2.x，G版3.x，H版4.x...这样就更加一目了然

好的，我把你的原贴编辑一下，也参与到投票中。

**Comment by liresky** [comment]
版本号的要求其实就是简单易懂，一看就知道怎么个情况，再说清楚点，就是你看到SCA的版本号就知道对应的SpringCloud的版本。起码大版本应该是比较清楚的。但是其内部还牵扯的一个就是SpringBoot的版本。SpringCloud决定了整体技术路线，SpringBoot可以决定一些具体的编码特性和细节。所以个人觉得从易读性考虑，能把SpringBoot和SpringCloud的信息能直接表达出来最好。
单纯来看，数字是最好的选择。

Spring Cloud Alibaba Bom 版本号 | Spring Cloud 版本号 | Starter或主版本
-- | -- | --
Spring Cloud Alibaba 1.x.y | Spring Cloud Edgware | 1.x
Spring Cloud Alibaba 2.x.y | Spring Cloud Finchley | 2.x
Spring Cloud Alibaba 3.x.y | Spring Cloud Greenwich | 3.x

1.x与Starter保持同步，y这个代表SCA的自我修复版本。

**Comment by charlesvhe** [comment]
我觉得还是要在一定的原则下设计版本号，这个原则是“以我为主”，即按照自己的版本号规则即可，不用强制绑定spring boot或spring cloud版本。x.y.z；x代表重大架构/设计变化；y代表不兼容的升级或特性；z代表兼容的bug修改或特性升级；
只要在readme显著位置以表格形式标明spring-cloud-alibaba和spring cloud版本兼容关系和推荐组合即可

由于spring cloud E版本的特殊性（长期维护到spring boot 1.5.x EOL） 1.0.0 对应 spring boot 1.5.x 和 spring cloud E

2.0.0 对应 spring boot 2.x 和 spring cloud F版本及以上，如果spring-cloud-alibaba不用修改代码即可兼容spring cloud G则不升级版本

如果由于架构或设计发生重大变化，即使对应的兼容spring cloud版本没有发生变化，我们自己也可以独立升级大版本 例如 2.0.0 和 3.0.0 都对应 spring cloud G

Spring Cloud Alibaba Bom 版本号 | Starter & 模块名 版本号 | Spring Cloud 版本号 | 修改内容
-- | -- | -- | --
Spring Cloud Alibaba 1.0.0 | 1.x | Spring Cloud Edgware | spring cloud E初始版本
Spring Cloud Alibaba 1.0.1 | 1.x | Spring Cloud Edgware | spring-cloud-alibaba-nacos-config组件安全升级
Spring Cloud Alibaba 2.0.0 | 2.x | Spring Cloud Finchley | spring cloud F初始版本
Spring Cloud Alibaba 2.1.0 | 2.x | Spring Cloud Greenwich | spring cloud G初始版本
Spring Cloud Alibaba 3.0.0 | 3.x | Spring Cloud Finchley and Greenwich | 重大架构设计升级 兼容spring cloud F和G

**Comment by flystar32** [comment]
> 我觉得还是要在一定的原则下设计版本号，这个原则是“以我为主”，即按照自己的版本号规则即可，不用强制绑定spring boot或spring cloud版本。x.y.z；x代表重大架构/设计变化；y代表不兼容的升级或特性；z代表兼容的bug修改或特性升级；
> 只要在readme显著位置以表格形式标明spring-cloud-alibaba和spring cloud版本兼容关系和推荐组合即可
> 
> 由于spring cloud E版本的特殊性（长期维护到spring boot 1.5.x EOL） 1.0.0 对应 spring boot 1.5.x 和 spring cloud E
> 
> 2.0.0 对应 spring boot 2.x 和 spring cloud F版本及以上，如果spring-cloud-alibaba不用修改代码即可兼容spring cloud G则不升级版本
> 
> 如果由于架构或设计发生重大变化，即使对应的兼容spring cloud版本没有发生变化，我们自己也可以独立升级大版本 例如 2.0.0 和 3.0.0 都对应 spring cloud G
> 
> Spring Cloud Alibaba Bom 版本号	Starter & 模块名 版本号	Spring Cloud 版本号	修改内容
> Spring Cloud Alibaba 1.0.0	1.x	Spring Cloud Edgware	spring cloud E初始版本
> Spring Cloud Alibaba 1.0.1	1.x	Spring Cloud Edgware	spring-cloud-alibaba-nacos-config组件安全升级
> Spring Cloud Alibaba 2.0.0	2.x	Spring Cloud Finchley	spring cloud F初始版本
> Spring Cloud Alibaba 2.1.0	2.x	Spring Cloud Greenwich	spring cloud G初始版本
> Spring Cloud Alibaba 3.0.0	3.x	Spring Cloud Finchley and Greenwich	重大架构设计升级 兼容spring cloud F和G

很好的建议，我把你这条也加入到投票中。

**Comment by flystar32** [comment]
> 我觉得还是要在一定的原则下设计版本号，这个原则是“以我为主”，即按照自己的版本号规则即可，不用强制绑定spring boot或spring cloud版本。x.y.z；x代表重大架构/设计变化；y代表不兼容的升级或特性；z代表兼容的bug修改或特性升级；
> 只要在readme显著位置以表格形式标明spring-cloud-alibaba和spring cloud版本兼容关系和推荐组合即可
> 
> 由于spring cloud E版本的特殊性（长期维护到spring boot 1.5.x EOL） 1.0.0 对应 spring boot 1.5.x 和 spring cloud E
> 
> 2.0.0 对应 spring boot 2.x 和 spring cloud F版本及以上，如果spring-cloud-alibaba不用修改代码即可兼容spring cloud G则不升级版本
> 
> 如果由于架构或设计发生重大变化，即使对应的兼容spring cloud版本没有发生变化，我们自己也可以独立升级大版本 例如 2.0.0 和 3.0.0 都对应 spring cloud G
> 
> Spring Cloud Alibaba Bom 版本号	Starter & 模块名 版本号	Spring Cloud 版本号	修改内容
> Spring Cloud Alibaba 1.0.0	1.x	Spring Cloud Edgware	spring cloud E初始版本
> Spring Cloud Alibaba 1.0.1	1.x	Spring Cloud Edgware	spring-cloud-alibaba-nacos-config组件安全升级
> Spring Cloud Alibaba 2.0.0	2.x	Spring Cloud Finchley	spring cloud F初始版本
> Spring Cloud Alibaba 2.1.0	2.x	Spring Cloud Greenwich	spring cloud G初始版本
> Spring Cloud Alibaba 3.0.0	3.x	Spring Cloud Finchley and Greenwich	重大架构设计升级 兼容spring cloud F和G

很好的建议，我把你这条也加入到投票中。和 @HaojunRen 的那条合并了，免得分散了票数。

**Comment by heqq-github** [comment]
E版 1.x，F版 2.x，G 版 3.x，H 版 4.x...

**Comment by fangjian0423** [comment]
Thanks for the vote.
