### ISSUE TITLE
SentinelRestTemplate注解优化

### ISSUE THREAD

**Issue by eacdy** [alibaba/spring-cloud-alibaba#762]
建议优化SentinelRestTemplate 注解。
当使用RestTemplate访问例如：http://user-center/users/{id} 的路径时，会为每个参数生成资源。
是否能够支持配置UrlCleaner或者其他东西，自己定义URL规则。这样更加灵活一些。

**Comment by Rivers-Shall** [comment]
As mentioned in the last comment, we can add additional `CleanerClass` and `CleanerMethod` configurations to `SentinelRestTemplate` annotation.  And when those are provided, we can use them to clean the URLs  in `SentinelProtectInterceptor`.

**Comment by fangjian0423** [comment]
how @eacdy think about it?

**Comment by eacdy** [comment]
@fangjian0423 I think it's a good idea.

**Comment by eacdy** [comment]
@Rivers-Shall @fang
666 和我想法差不多 这是一种玩法
不过这样的话 用户可能需要自己写cleanMethod
===
除此以外，我觉得还可以用反射 拿到this，然后拿到是在哪个方法调用的  以类名:方法名称 作为资源名称
这样用户的使用障碍可能更低一点 
不过这种方案我没有试过  不一定能实现
