### ISSUE TITLE
When does release support sentinel 1.6.2?

### ISSUE THREAD

**Issue by Lovnx** [alibaba/spring-cloud-alibaba#763]
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>0.9.0.RELEASE</version>
        </dependency>

目前最新版本只支持sentinel1.5.2版本，希望尽快release新版本！

**Comment by fangjian0423** [comment]
when we make sure the new pkg name & maven groupId & version number, we will release new version. related https://github.com/alibaba/spring-cloud-alibaba/issues/761

**Comment by Lovnx** [comment]
ok
