### ISSUE TITLE
about Aliyun RocketMQ trace topic name

### ISSUE THREAD

**Issue by Nitsuya** [alibaba/spring-cloud-alibaba#764]
现象：使用ONS连接阿里云RocketMq，消费后后台可以看见消息轨迹，使用rocketmq stream binder无法上报消息轨迹。

描述：分别跟踪了 ONS 和 RocketMq Client，
RocketMq Client中默认使用 RMQ_SYS_TRACE_TOPIC
ONS中使用 [rmq_sys_TRACE_DATA_ + currentRegionId], RegionId是从消息中解析出来的

问题：这个traceTopicName 是否可以从选择的区进行固定，当然这个不是binder的锅，有没有好的方式去支持 阿里云RocketMq的消息轨迹
-------------------------------------------------------------------------------------
Machine translation：

Phenomenon: use ONS link RocketMq ali cloud, background news trajectory can be seen after consumption, use RocketMq stream binder is unable to report the news.

Description: tracking the ONS and RocketMq Client,
Use the default RMQ_SYS_TRACE_TOPIC RocketMq Client
Use the [rmq_sys_TRACE_DATA_ + currentRegionId] ONS, RegionId is parsed from the news

Question: whether the traceTopicName can be fixed, the chosen area, of course, this is not a binder of wrong, is there a good way to support ali cloud RocketMq message path

**Comment by fangjian0423** [comment]
configuration item: `spring.cloud.stream.rocketmq.binder.customizedTraceTopic`.

| Region名称  | RegionId              | customizedTraceTopic                     |
| --------- | --------------------- | ---------------------------------------- |
| 华东1(杭州)   | cn-hangzhou           | rmq_sys_TRACE_DATA_cn-hangzhou           |
| 华东2(上海)   | cn-shanghai           | rmq_sys_TRACE_DATA_cn-shanghai           |
| 华北1(青岛)   | cn-qingdao            | rmq_sys_TRACE_DATA_cn-qingdao            |
| 华北2(北京)   | cn-beijing            | rmq_sys_TRACE_DATA_cn-beijing            |
| 华北3(张家口)  | cn-zhangjiakou        | rmq_sys_TRACE_DATA_cn-zhangjiakou        |
| 华北5(呼和浩特) | cn-huhehaote          | rmq_sys_TRACE_DATA_cn-huhehaote          |
| 华南1(深圳)   | cn-shenzhen           | rmq_sys_TRACE_DATA_cn-shenzhen           |
| 香港        | cn-hongkong           | rmq_sys_TRACE_DATA_cn-hongkong           |
| 公网        | cn-qingdao-publictest | rmq_sys_TRACE_DATA_cn-qingdao-publictest |

**Comment by Nitsuya** [comment]
@fangjian0423 
谢谢~~~

**Comment by HallenW** [comment]
现在我贴了对应的属性还是后台还是无法看到消息轨迹。spring.cloud.stream.rocketmq.binder.customizedTraceTopic=rmq_sys_TRACE_DATA_cn-qingdao-publictest
我使用的版本是
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
            <version>2.0.0.RELEASE</version>
        </dependency>

Machine translation：


affixed the corresponding attributes or background or can not see the message trajectory. Spring. cloud. stream. rocketmq. binder. customizedTraceTopic = rmq_sys_TRACE_DATA_cn-qingdao-publictest

The version I use is

<dependency>

<groupId>com.alibaba.cloud</groupId>

<artifactId>spring-cloud-starter-stream-rocketmq</artifactId>

<version>2.0.0.RELEASE</version>

</dependency>

**Comment by HallenW** [comment]
> @fangjian0423
> 谢谢~~~

加上这个还是无法解决,spring.cloud.stream.rocketmq.binder.customizedTraceTopic=rmq_sys_TRACE_DATA_cn-qingdao-publictest
后面你解决了吗?

**Comment by HallenW** [comment]
> 现象：使用ONS连接阿里云RocketMq，消费后后台可以看见消息轨迹，使用rocketmq stream binder无法上报消息轨迹。
> 
> 描述：分别跟踪了 ONS 和 RocketMq Client，
> RocketMq Client中默认使用 RMQ_SYS_TRACE_TOPIC
> ONS中使用 [rmq_sys_TRACE_DATA_ + currentRegionId], RegionId是从消息中解析出来的
> 
> ## 问题：这个traceTopicName 是否可以从选择的区进行固定，当然这个不是binder的锅，有没有好的方式去支持 阿里云RocketMq的消息轨迹
> Machine translation：
> 
> Phenomenon: use ONS link RocketMq ali cloud, background news trajectory can be seen after consumption, use RocketMq stream binder is unable to report the news.
> 
> Description: tracking the ONS and RocketMq Client,
> Use the default RMQ_SYS_TRACE_TOPIC RocketMq Client
> Use the [rmq_sys_TRACE_DATA_ + currentRegionId] ONS, RegionId is parsed from the news
> 
> Question: whether the traceTopicName can be fixed, the chosen area, of course, this is not a binder of wrong, is there a good way to support ali cloud RocketMq message path

目前发现的问题是,output ,input在同一个配置文件,并且 output 和 input 的destination 和 group都不同,就会出现在阿里云后台看到消息尚未消费的情况,实际情况是已经消费成功的。

**Comment by liuoqiang** [comment]
> @fangjian0423
> 谢谢~~~

请问你有解决么 添加了还是没有 有时候会显示消费失败未返回 有时候又是未消费

**Comment by liuoqiang** [comment]
> > 现象：使用ONS连接阿里云RocketMq，消费后后台可以看见消息轨迹，使用rocketmq stream binder无法上报消息轨迹。
> > 描述：分别跟踪了 ONS 和 RocketMq Client，
> > RocketMq Client中默认使用 RMQ_SYS_TRACE_TOPIC
> > ONS中使用 [rmq_sys_TRACE_DATA_ + currentRegionId], RegionId是从消息中解析出来的
> > ## 问题：这个traceTopicName 是否可以从选择的区进行固定，当然这个不是binder的锅，有没有好的方式去支持 阿里云RocketMq的消息轨迹
> > Machine translation：
> > Phenomenon: use ONS link RocketMq ali cloud, background news trajectory can be seen after consumption, use RocketMq stream binder is unable to report the news.
> > Description: tracking the ONS and RocketMq Client,
> > Use the default RMQ_SYS_TRACE_TOPIC RocketMq Client
> > Use the [rmq_sys_TRACE_DATA_ + currentRegionId] ONS, RegionId is parsed from the news
> > Question: whether the traceTopicName can be fixed, the chosen area, of course, this is not a binder of wrong, is there a good way to support ali cloud RocketMq message path
> 
> 目前发现的问题是,output ,input在同一个配置文件,并且 output 和 input 的destination 和 group都不同,就会出现在阿里云后台看到消息尚未消费的情况,实际情况是已经消费成功的。

升级rocketmq-client后 我已经解决了

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-acl</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
            
            <exclusions>
                <exclusion>
                    <groupId>org.apache.rocketmq</groupId>
                    <artifactId>rocketmq-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.rocketmq</groupId>
                    <artifactId>rocketmq-acl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by liuoqiang** [comment]
之前我是4.8.0版本，也是和你一样的情况，现在可以了
![image](https://user-images.githubusercontent.com/45333423/131616429-d603b5be-d36f-4976-92f7-b1e3e9e8f95c.png)

**Comment by YooLin** [comment]
> > > 现象：使用ONS连接阿里云RocketMq，消费后后台可以看见消息轨迹，使用rocketmq stream binder无法上报消息轨迹。
> > > 描述：分别跟踪了 ONS 和 RocketMq Client，
> > > RocketMq Client中默认使用 RMQ_SYS_TRACE_TOPIC
> > > ONS中使用 [rmq_sys_TRACE_DATA_ + currentRegionId], RegionId是从消息中解析出来的
> > > ## 问题：这个traceTopicName 是否可以从选择的区进行固定，当然这个不是binder的锅，有没有好的方式去支持 阿里云RocketMq的消息轨迹
> > > Machine translation：
> > > Phenomenon: use ONS link RocketMq ali cloud, background news trajectory can be seen after consumption, use RocketMq stream binder is unable to report the news.
> > > Description: tracking the ONS and RocketMq Client,
> > > Use the default RMQ_SYS_TRACE_TOPIC RocketMq Client
> > > Use the [rmq_sys_TRACE_DATA_ + currentRegionId] ONS, RegionId is parsed from the news
> > > Question: whether the traceTopicName can be fixed, the chosen area, of course, this is not a binder of wrong, is there a good way to support ali cloud RocketMq message path
> > 
> > 
> > 目前发现的问题是,output ,input在同一个配置文件,并且 output 和 input 的destination 和 group都不同,就会出现在阿里云后台看到消息尚未消费的情况,实际情况是已经消费成功的。
> 
> 升级rocketmq-client后 我已经解决了
> 
> ```
>     <dependency>
>         <groupId>org.apache.rocketmq</groupId>
>         <artifactId>rocketmq-client</artifactId>
>         <version>4.9.1</version>
>     </dependency>
>     <dependency>
>         <groupId>org.apache.rocketmq</groupId>
>         <artifactId>rocketmq-acl</artifactId>
>         <version>4.9.1</version>
>     </dependency>
>     <dependency>
>         <groupId>com.alibaba.cloud</groupId>
>         <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
>         
>         <exclusions>
>             <exclusion>
>                 <groupId>org.apache.rocketmq</groupId>
>                 <artifactId>rocketmq-client</artifactId>
>             </exclusion>
>             <exclusion>
>                 <groupId>org.apache.rocketmq</groupId>
>                 <artifactId>rocketmq-acl</artifactId>
>             </exclusion>
>         </exclusions>
>     </dependency>
> ```

4.9.1版本是可用的 4.9.1 以上版本的消息轨迹都用不了
