### ISSUE TITLE
A little question about the dubbo-spring-cloud-alibaba-examples project

### ISSUE THREAD

**Issue by killersteps** [alibaba/spring-cloud-alibaba#768]
A little question about the dubbo-spring-cloud-alibaba-examples project:
The project uses dubbo instead of feign or ribbon for remote calls, but doing so must introduce the same interface on the calling side as the server, although the efficiency of the dubbo protocol is higher than the http protocol used by spring cloud, but this makes the code available. Reduced maintenance.
Question: Can the caller of the project use both the sample code and the spring-based default feign or ribbon to make the developer choose.
The code is similar to:

`@EnableDiscoveryClient
@EnableAutoConfiguration
@RestController
public class DubboSpringCloudClientBootstrap {

@Bean
RestTemplate restTemplate() {
    return new RestTemplate();
}

@Bean
IRule ribbonRule() {
    return new RandomRule();
}

@Reference
private EchoService echoService;

@Autowired
private LoadBalancerClient loadBalancerClient;

@Autowired
private RestTemplate restTemplate;

@GetMapping("/echo")
public String echo(String message) {
    ServiceInstance serviceInstance = loadBalancerClient.choose("spring-cloud-alibaba-dubbo-server");
    String url = serviceInstance.getUri() + "/echo";
// return echoService.echo(message);
return restTemplate.getForObject(url, String.class);
}

public static void main(String[] args) {
    SpringApplication.run(DubboSpringCloudClientBootstrap.class);
}
}`

**Comment by fangjian0423** [comment]
You mean we can choose invoke protocol by configuration item like this?

`spring.cloud.alibaba.service-call=dubbo`

**Comment by anpu2018** [comment]
> You mean we can choose invoke protocol by configuration item like this?
> 
> `spring.cloud.alibaba.service-call=dubbo`

我的意思是在使用dubbo-spring-cloud-alibaba-examples这个demo时，服务的调用是否可以走ribbon或者feign，因为在客户端引入接口走dubbo协议不太方便维护，是否可以使用ribbon走http协议调用dubbo发布的服务？
