### ISSUE TITLE
dubbo-spring-cloud-starter(Maybe it's a bug)

### ISSUE THREAD

**Issue by 382826843** [alibaba/spring-cloud-alibaba#770]
我在使用spring cloud alibaba的 dubbo-spring-cloud-starter 组件的时候回出现一种情况，先行启动了消费者b，再启动提供者a，b无法获取a的服务,报错找不到方法,参照官方例子中的配置的。于是，使用到nacos和dubbo官方提供的注册包就不会发生这种情况

　　When I used the dubbo-spring-cloud-starter component of spring cloud alibaba, there was a situation that started consumer b first, and then started provider a. B could not get the service of a, and could not find the method to report the error, referring to the configuration in the official example.This does not happen with the official nacos and dubbo registerpacks

**Comment by 382826843** [comment]
使用的是nacos注册中心
Nacos registries are used

**Comment by 382826843** [comment]
我使用的是nacos注册中心
I use the nacos registry

**Comment by guojing762** [comment]
我也发现了这个bug 用dubbo和nacos官方的dubbo-registry-nacos就没有顺序限制，

**Comment by q1991108** [comment]
我也是
me too
