### ISSUE TITLE
SentinelConverter不支持热点参数规则

### ISSUE THREAD

**Issue by eacdy** [alibaba/spring-cloud-alibaba#771]
```
org.springframework.cloud.alibaba.sentinel.datasource.converter.SentinelConverter
```
不支持热点参数限流。

我写了个Sentinel Dashboard，使用Nacos持久化数据。安装包、使用说明在这里：<https://github.com/eacdy/Sentinel-Dashboard-Nacos/releases>

其他规则都能正常解析，唯独热点参数限流规则无法正常解析。感觉这是个BUG，请修正。

PS. SentinelConverter的代码两层try...catch...，代码可读性不佳，而且报的异常上去就ignore，里面什么都不打印，很不友好。我调试时，就是会进到ignore异常的。

是否应该改进下？

**Comment by pigxcloud** [comment]
demo 中的热点规则，可以直接用 

```
[
  {
    "resource": "aa",
    "count": 0,
    "grade": 1,
    "limitApp": "default",
    "paramIdx": 0,
    "paramFlowItemList": [
      {
        "object": "2",
        "classType": "int",
        "count": 1
      }
    ]
  }
]
```

**Comment by eacdy** [comment]
@pigxcloud 我的热点规则：
```json
[
  {
    "resource": "/shares/1",
    "limitApp": "default",
    "grade": 1,
    "paramIdx": 1,
    "count": 0.0,
    "controlBehavior": 0,
    "maxQueueingTimeMs": 0,
    "burstCount": 0,
    "durationInSec": 1,
    "paramFlowItemList": [
      {
        "object": "1",
        "count": 1,
        "classType": "int"
      }
    ],
    "clusterMode": false,
    "clusterConfig": {
      "flowId": null,
      "thresholdType": 0,
      "fallbackToLocalWhenFail": true,
      "sampleCount": 10,
      "windowIntervalMs": 1000
    }
  }
]
```

**Comment by pigxcloud** [comment]
周老师 我测试了一下。如果直接用给的JSON 是没有问题的

nacos  1.1.0
sentinel  1.6.2
=========
如果我打开了 "clusterMode": true,
GG    就凉了 对于集群那块处理有问题
@eacdy

**Comment by fangjian0423** [comment]
> 周老师 我测试了一下。如果直接用你上边JSON 是没有问题的
> 
> # nacos 1.1.0
> sentinel 1.6.2
> 如果我打开了 "clusterMode": true,"flowId" 必须要设置 才行

限流规则解析完会通过 `FlowRuleUtil#isValidRule` 来验证，显然少了 flowId 的规则是不合法的，直接返回了 null。 体验做的不是很好

**Comment by pigxcloud** [comment]
@fangjian0423 

热点参数  是这个   zz 
ParamFlowRuleUtil.validClusterRuleId

> > 周老师 我测试了一下。如果直接用你上边JSON 是没有问题的
> > # nacos 1.1.0
> > sentinel 1.6.2
> > 如果我打开了 "clusterMode": true,"flowId" 必须要设置 才行
> 
> 限流规则解析完会通过 `FlowRuleUtil#isValidRule` 来验证，显然少了 flowId 的规则是不合法的，直接返回了 null。 体验做的不是很好

热点参数这个 ParamFlowRuleUtil.validClusterRuleId

**Comment by fangjian0423** [comment]
I remove the check code in `SentinelConverter`, it will be handle by Sentinel XXRuleManager.

if there is some problems in `SentinelConverter`, we can use custom converter.
