### ISSUE TITLE
Something about the spring cloud dependencies version in readme.md need updating

### ISSUE THREAD

**Issue by xz1996** [alibaba/spring-cloud-alibaba#772]
My spring project version is ```spring cloud Edgware``` and according to the readme.md, I ued ```spring-cloud-alibaba-dependencies0.1.1.RELEASE```, but when I plan to link to the ```RocketMQ``` on the Aliyun, I always got the error -- ```no route info of this topic```, but all configurations are right, it blocked me several days until I found there was a new release version--```0.1.2.RELEASE```, after updating that, I finally run my project successfully. By analysing the source code, I found the ```name-server``` configuration was different between this two versions. So I hope you can updating the document on ```readme.md```, thanks.

**Comment by fangjian0423** [comment]
thanks for your report.

It is recommanded to use 0.1.2.RELEASE and only this version support Aliware RocketMQ(Aliyun RocketMQ).

I will update it in the wiki right now.

**Comment by fangjian0423** [comment]
updated in wiki: https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ#%E9%98%BF%E9%87%8C%E4%BA%91-mq-%E6%9C%8D%E5%8A%A1.
