### ISSUE TITLE
如何构建问题

### ISSUE THREAD

**Issue by haochencheng** [alibaba/spring-cloud-alibaba#79]
![Uploading image.png…]()
我只想构建一个config-server可以吗，构建所有项目要下很久。

**Comment by flystar32** [comment]
图片看不清，按你所描述的问题  “构建 config-server”  这个有点不大明白
因为我们并没有一个叫 config-server 的模块

如果只是单纯地使用，我们已经发布到中央仓库，比如使用配置管理，可以直接这样使用

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
    </dependencies>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>0.2.0.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

**Comment by jliu666** [comment]
单独编译某个maven模块需要进入到目录下执行 @haochencheng
