### ISSUE TITLE
SentinelFeign not support FeignClient contextId！

### ISSUE THREAD

**Issue by Nitsuya** [alibaba/spring-cloud-alibaba#793]
**Which Component**
spring-cloud-alibaba-sentinel

**Describe the bug**
SentinelFeign not support contextId, can cause fallbackInstance not available, throw an exception

SentinelFeign中并未支持contextId，会导致fallbackInstance无法获取，抛出异常

**Expected behavior**
支持contextId

**Comment by fangjian0423** [comment]
FeignClient add `contextId` attribute in Spring Cloud Greenwich.

contributors are welcome.

**Comment by pigxcloud** [comment]
咋个回显出来。  contextId 只是给feignclient 搞了个 contexIdFeignClient 的名称 不会影响获取fallbackInstance啊

**Comment by fangjian0423** [comment]
@pigxcloud 

https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelFeign.java#L85

here. we should use `contextId`, not `name.

**Comment by Nitsuya** [comment]
@pigxcloud name 和 contextId 配置成不一样的名字，再配置fallback， SentinelFeign L91->L110, 判空然后抛出异常

**Comment by pigxcloud** [comment]
```
@FeignClient(contextId = "echoService", name = "service-provider", fallback = EchoServiceFallback.class)
public interface EchoService {

    /**
     * 调用服务提供方的输出接口
     *
     * @param str 用户输入
     * @return
     */
    @GetMapping(value = "/echo/{str}")
    String echo(@PathVariable("str") String str);
}
```

木有回显回来 好气

**Comment by Nitsuya** [comment]
`
public class EchoServiceFallback implements EchoService {
    @Override
    public String echo(String str) {
        return "consumer-fallback-default-str" + str;
    }
}

public  class FeignConfiguration {
     @Bean
    public EchoServiceFallback echoServiceFallback() {
        return new EchoServiceFallback();
    }
}

@FeignClient(contextId = "echoService", name = "service-provider", fallback = EchoServiceFallback.class, configuration = FeignConfiguration.class)
public interface EchoService {
    @GetMapping(value = "/echo/{str}")
    String echo(@PathVariable("str") String str);
}
`

这样写就会报错, 
----
抱歉描述问题的时候没有贴出使用方式
排版不太会-,-.

**Comment by pigxcloud** [comment]
> `
> public class EchoServiceFallback implements EchoService {
> @override
> public String echo(String str) {
> return "consumer-fallback-default-str" + str;
> }
> }
> 
> public class FeignConfiguration {
> @bean
> public EchoServiceFallback echoServiceFallback() {
> return new EchoServiceFallback();
> }
> }
> 
> @FeignClient(contextId = "echoService", name = "service-provider", fallback = EchoServiceFallback.class, configuration = FeignConfiguration.class)
> public interface EchoService {
> @GetMapping(value = "/echo/{str}")
> String echo(@PathVariable("str") String str);
> }
> `
> 
> ## 这样写就会报错,
> 抱歉描述问题的时候没有贴出使用方式
> 排版不太会-,-.

FeignConfiguration 加 @Configuration  才会被 注入到 容器

**Comment by xiejiashuai** [comment]
I will try to resolve this problem
