### ISSUE TITLE
nacos和spring-cloud-config混用报错，加载顺序有问题

### ISSUE THREAD

**Issue by zhanglei-1987** [alibaba/spring-cloud-alibaba#797]
Error creating bean with name 'configServerInstanceProvider' defined in class path resource [org/springframework/cloud/config/client/DiscoveryClientConfigServiceBootstrapConfiguration.class]: Unsatisfied dependency expressed through method 'configServerInstanceProvider' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.client.discovery.DiscoveryClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/spring-cloud-alibaba/issues/708, it has been fixed.
