### ISSUE TITLE
multi-module dependencies cannot be introduced automatically

### ISSUE THREAD

**Issue by Comven** [alibaba/spring-cloud-alibaba#799]
version of spring-cloud-alibaba-dependencies is 2.1.0.RELEASE

when i configure the dependency at parent like this
```
<dependency>
  <groupId>com.alibaba.cloud</groupId>
  <artifactId>spring-cloud-alibaba-dependencies</artifactId>
  <version>2.1.0.RELEASE</version>
  <type>pom</type>
<scope>import</scope>
</dependency>
```
and add dependency of `spring-cloud-starter-alibaba-nacos-discovery` like this
```
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
```
It does not take effect, i have to add the version to it.
![image](https://user-images.githubusercontent.com/8464801/62340202-46e51300-b511-11e9-87c1-96fef6febecb.png)

Did I miss something?

but when i change to old version 0.9.0, it work fine。

**Comment by fangjian0423** [comment]
`spring-cloud-starter-alibaba-nacos-discovery` has been deployed to maven central: https://search.maven.org/search?q=g:com.alibaba.cloud%20AND%20a:spring-cloud-starter-alibaba-nacos-discovery&core=gav

and it is included in bom: https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.0.RELEASE/pom

**Comment by Comven** [comment]
> `spring-cloud-starter-alibaba-nacos-discovery` has been deployed to maven central: https://search.maven.org/search?q=g:com.alibaba.cloud%20AND%20a:spring-cloud-starter-alibaba-nacos-discovery&core=gav
> 
> and it is included in bom: https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.0.RELEASE/pom

i had added the bom to my parent module `dependencyManagement`, but the sub-module can't  be introduced `be introduced automatically` automatically without version

**Comment by fangjian0423** [comment]
> > `spring-cloud-starter-alibaba-nacos-discovery` has been deployed to maven central: https://search.maven.org/search?q=g:com.alibaba.cloud%20AND%20a:spring-cloud-starter-alibaba-nacos-discovery&core=gav
> > and it is included in bom: https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.0.RELEASE/pom
> 
> i had added the bom to my parent module `dependencyManagement`, but the sub-module can't be introduced `spring-cloud-starter-alibaba-nacos-discovery` automatically without version

but it really included in bom, and works well in my local.

**Comment by Comven** [comment]
> > > `spring-cloud-starter-alibaba-nacos-discovery` has been deployed to maven central: https://search.maven.org/search?q=g:com.alibaba.cloud%20AND%20a:spring-cloud-starter-alibaba-nacos-discovery&core=gav
> > > and it is included in bom: https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.0.RELEASE/pom
> > 
> > 
> > i had added the bom to my parent module `dependencyManagement`, but the sub-module can't be introduced `spring-cloud-starter-alibaba-nacos-discovery` automatically without version
> 
> but it really included in bom, and works well in my local.

OK  i will retry again,3Q

**Comment by echooymxq** [comment]
maybe, you should close the ide and repoen it

**Comment by echooymxq** [comment]
maybe, you should close the ide and reopen it

**Comment by Comven** [comment]
> > > `spring-cloud-starter-alibaba-nacos-discovery` has been deployed to maven central: https://search.maven.org/search?q=g:com.alibaba.cloud%20AND%20a:spring-cloud-starter-alibaba-nacos-discovery&core=gav
> > > and it is included in bom: https://search.maven.org/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.0.RELEASE/pom
> > 
> > 
> > i had added the bom to my parent module `dependencyManagement`, but the sub-module can't be introduced `spring-cloud-starter-alibaba-nacos-discovery` automatically without version
> 
> but it really included in bom, and works well in my local.

I think maybe the maven central was delayed, after i wait for minutes, it worked fine.
