### ISSUE TITLE
dubbo springcloud  底层 是rpc 二进制调用，是如何做到兼容 feign http 调用的，使用feign和rpc二进制到底有什么区别？The bottom layer of Dubbo spring cloud is RPC binary call. How to make it compatible with feign http call? What's the difference between using feign and RPC binary?

### ISSUE THREAD

**Issue by xlzuijia** [alibaba/spring-cloud-alibaba#803]
The bottom layer of Dubbo spring cloud is RPC binary call. How to make it compatible with feign http call? What's the difference between using feign and RPC binary?

**Comment by xlzuijia** [comment]
Has Alibaba officially done a call efficiency test for HTTP and RPC binaries?
http 和  rpc 二进制的调用效率测试阿里巴巴官方 有做吗

**Comment by VolcanoOves** [comment]
feign基于HTTP调用，性能折损比dubbo协议高~
