### ISSUE TITLE
SchdeuleX 源码在哪里呢？Where is the source code for SchdeuleX?

### ISSUE THREAD

**Issue by zhaoyuguang** [alibaba/spring-cloud-alibaba#805]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
ScheduleX

**Describe what problem you have encountered**
SchdeuleX 源码在哪里呢？我在这个仓库里面只看到了一个简单的SchdeuleX-client的spring-boot 的简单封装，SchdeuleX服务端以及客户端的全部代码在哪里呢？
Where is the source code for SchdeuleX? I only saw a simple SchdeuleX-client spring-boot package in this repository. Where is the SchdeuleX server and all the code for the client?

**Describe what information you have read**
eg. I have read the reference doc of ScheduleX

**Comment by 1346735074** [comment]
ScheduleX Not open source

**Comment by zhaoyuguang** [comment]
> ScheduleX Not open source

Can I know the reason？

**Comment by 1346735074** [comment]
This you know the official page in detail.

**Comment by fangjian0423** [comment]
Related https://github.com/alibaba/spring-cloud-alibaba/issues/233.

**Comment by fangjian0423** [comment]
close it because it's a duplicate issue.
