### ISSUE TITLE
nacos-config-example示例无法获取到nacos配置内容

### ISSUE THREAD

**Issue by smshen** [alibaba/spring-cloud-alibaba#818]
github download 示例, 启动成功但是无法获取配置的内容.
版本信息如下:
    <artifactId>spring-cloud-alibaba-examples</artifactId>
    <version>2.1.1.BUILD-SNAPSHOT</version>
    <artifactId>nacos-config-example</artifactId>

@Value("${user.age:25}") 修改为 @Value("${user.age}"), 启动将报错 Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'user.age' in value "${user.age}"

**Comment by fangjian0423** [comment]
make the dataId & group is right and spring cloud version is Greenwich.

**Comment by smshen** [comment]
> make sure the dataId & group is right and spring cloud version is Greenwich.

nacos 管理控制台dataId配置是nacos-config-example.properties
nacos 管理控制台group配置是DEFAULT_GROUP
文件内容: 
user.name=123
user.age=22

项目 spring-cloud-alibaba/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/bootstrap.properties 与github上一致, 没改动

**Comment by fangjian0423** [comment]
put your pom here, i need know the version of each dependencies.

**Comment by smshen** [comment]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ nacos-config-example ---
[INFO] com.alibaba.cloud:nacos-config-example:jar:2.1.1.BUILD-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.1.6.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.6.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  |  \- org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  +- org.springframework:spring-core:jar:5.1.8.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.9:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.9:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.9:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.21:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.21:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.21:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.0.17.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  +- org.springframework:spring-web:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.1.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.1.8.RELEASE:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.1.8.RELEASE:compile
[INFO] |     +- org.springframework:spring-context:jar:5.1.8.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.1.8.RELEASE:compile
[INFO] +- com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:jar:2.1.1.BUILD-SNAPSHOT:compile
[INFO] |  \- com.alibaba.cloud:spring-cloud-alibaba-nacos-config:jar:2.1.1.BUILD-SNAPSHOT:compile
[INFO] |     +- com.alibaba.nacos:nacos-client:jar:1.1.1:compile
[INFO] |     |  +- com.alibaba.nacos:nacos-common:jar:1.1.1:compile
[INFO] |     |  |  +- commons-io:commons-io:jar:2.2:compile
[INFO] |     |  |  \- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] |     |  +- com.alibaba.nacos:nacos-api:jar:1.1.1:compile
[INFO] |     |  |  \- com.alibaba:fastjson:jar:1.2.47:compile
[INFO] |     |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |     |  +- commons-codec:commons-codec:jar:1.11:compile
[INFO] |     |  \- io.prometheus:simpleclient:jar:0.5.0:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-commons:jar:2.1.2.RELEASE:compile
[INFO] |     |  \- org.springframework.security:spring-security-crypto:jar:5.1.5.RELEASE:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-context:jar:2.1.2.RELEASE:compile
[INFO] \- org.springframework.boot:spring-boot-starter-actuator:jar:2.1.6.RELEASE:compile
[INFO]    +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.1.6.RELEASE:compile
[INFO]    |  \- org.springframework.boot:spring-boot-actuator:jar:2.1.6.RELEASE:compile
[INFO]    \- io.micrometer:micrometer-core:jar:1.1.5:compile
[INFO]       +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO]       \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by fangjian0423** [comment]
It seems the dependency is right, could you pls provide a project that reproduces the issue?

**Comment by smshen** [comment]
git clone https://github.com/alibaba/spring-cloud-alibaba.git

**Comment by fangjian0423** [comment]
but it works well in my local.

**Comment by smshen** [comment]
my local nacos server version is 1.1.0

**Comment by fangjian0423** [comment]
yes, my nacos server version also is 1.1.0.

**Comment by renkchina** [comment]
I have the same problem

**Comment by cxdhefei** [comment]
I have the same problem
spring-cloud-alibaba-dependencies：2.1.0.RELEASE
nacos：1.1.3

**Comment by zzqw** [comment]
I have the same problem

**Comment by fangjian0423** [comment]
Remember 3 key points:

1. spring boot version & spring cloud version & spring cloud alibaba version should be matched
2. remember adding `@RefreshScope` annotation
3. watch the logs with `[notify-ok]` key words to make sure nacos config is effected

**Comment by Xpectuer** [comment]
@smshen Plz check the group name, and keep @RefreshScope on. Then I resolve the problem.
