### ISSUE TITLE
Spring Cloud Alibaba version

### ISSUE THREAD

**Issue by a601942905git** [alibaba/spring-cloud-alibaba#820]
I saw in the spring cloud alibaba github wiki that the latest version is 2.1.0.RELEASE. When I introduce it as a pom, I can't add related dependencies, such as nacos.
```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

```xml
<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
    </dependencies>
```

**Comment by fangjian0423** [comment]
the groupId of `spring-cloud-starter-alibaba-nacos-discovery` is `com.alibaba.cloud`

**Comment by a601942905git** [comment]
thank you very much。A bit confusing, can you specifically specify in the document?

**Comment by fangjian0423** [comment]
the groupId must be the same in spring-cloud-alibaba-dependencies bom.

we have illustrated it in [wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E#spring-cloud-greenwich).

**Comment by fangjian0423** [comment]
And it also illustrated in [example README](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme-zh.md).

**Comment by a601942905git** [comment]
thank you
