### ISSUE TITLE
Disable Sentinel web filters when using Sentinel gateway starters

### ISSUE THREAD

**Issue by sczyh30** [alibaba/spring-cloud-alibaba#821]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**

Sentinel

**Describe the bug**

The web filters (e.g. the Spring WebFlux filter) should be disabled if current application is an API gateway. The URLs should not be marked as resources in Sentinel API gateway flow control (which only supports route and customized API groups).

**Additional context**

The 2.1.0.RELEASE version

**Comment by fangjian0423** [comment]
The configuration item `spring.cloud.sentinel.filter.enabled` can disable web filter initialization.

Maybe we can add the configuration item by `EnvironmentPostProcessor` in `spring-cloud-alibaba-sentinel-gateway` module.
