### ISSUE TITLE
when load config file which contains chinese , "input length = 1" error will occur

### ISSUE THREAD

**Issue by lwshiwook** [alibaba/spring-cloud-alibaba#822]
only on windows os , I guess its a String.getBytes() problem, using defaultCharset

**Comment by fangjian0423** [comment]
we have discussed this in DingDing.

![image](https://user-images.githubusercontent.com/5254035/62680268-684e6f00-b9e9-11e9-9bc6-06f2be23c822.png)

**Comment by fangjian0423** [comment]
Closing this issue due to no feedback.
