### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config 监听配置变化

### ISSUE THREAD

**Issue by stormbirds** [alibaba/spring-cloud-alibaba#830]
**Which Component**
spring-boot-starter-web:2.1.6.RELEASE
spring-cloud-starter-alibaba-nacos-config:2.1.0.RELEASE

**Describe what problem you have encountered**
我想注册监听器监听配置的变化，但是使用@NacosConfigListener无法得到任何消息
```
@NacosConfigListener(dataId = "example-dev.properties")
    public void onReceived(Properties value) {
        log.info("onReceived(Properties) : {}", value);
    }
```
但是日志中我可以看到的确是接收到了配置变化
```
2019-08-09 15:15:56.093  INFO 2505 --- [d0-fd101bbf6de8] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [test]
```
另外我试着添加如下代码，这里可以正常得到配置更新的消息，但是我想使用@NacosConfigListener这个注解来获取
```
    @PostConstruct
    public void init() throws NacosException {
        nacosConfigProperties.configServiceInstance().addListener("example-dev.properties", "DEFAULT_GROUP", new Listener() {
            @Override
            public Executor getExecutor() {
                return null;
            }

            @Override
            public void receiveConfigInfo(String s) {
                log.info("onReceived(Properties) : {}", s);
            }
        });
    }
```

**Comment by stormbirds** [comment]
** Which Component
spring-boot-starter-web:2.1.6.RELEASE
spring-cloud-starter-alibaba-nacos-config:2.1.0.RELEASE

** Describe what problem you have encountered
I want to register the listener to listen for configuration changes, but I can't get any messages with @NacosConfigListener
```
@NacosConfigListener(dataId = "example-dev.properties")
    public void onReceived(Properties value) {
        log.info("onReceived(Properties) : {}", value);
    }
```
But what I can see in the log is that I received the configuration change.
```
2019-08-09 15:15:56.093  INFO 2505 --- [d0-fd101bbf6de8] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [test]
```
In addition, I tried to add the following code, here I can get the configuration update message, but I want to use @NacosConfigListener this annotation to get

    @PostConstruct
    public void init() throws NacosException {
        nacosConfigProperties.configServiceInstance().addListener("example-dev.properties", "DEFAULT_GROUP", new Listener() {
            @Override
            public Executor getExecutor() {
                return null;
            }

            @Override
            public void receiveConfigInfo(String s) {
                log.info("onReceived(Properties) : {}", s);
            }
        });
    }

**Comment by fangjian0423** [comment]
we are working with spring cloud nacos config integrate spring boot nacos config.

related https://github.com/alibaba/spring-cloud-alibaba/issues/825

**Comment by 852675742** [comment]
@PostConstruct
    public void init() throws NacosException {
        nacosConfigProperties.configServiceInstance().addListener("example-dev.properties", "DEFAULT_GROUP", new Listener() {
            @Override
            public Executor getExecutor() {
                return null;
            }

            @Override
            public void receiveConfigInfo(String s) {
                log.info("onReceived(Properties) : {}", s);
            }
        });
    }


这个确实是能获取到所有的更新后的配置，但是我想知道是哪些key变化了，有什么办法吗？

**Comment by yang1320** [comment]
@PostConstruct
    public void init() throws NacosException {
        nacosConfigProperties.configServiceInstance().addListener("example-dev.properties", "DEFAULT_GROUP", new Listener() {
            @Override
            public Executor getExecutor() {
                return null;
            }

            @Override
            public void receiveConfigInfo(String s) {
                log.info("onReceived(Properties) : {}", s);
            }
        });
    } 使用这种方式也不生效，如下方式可以成功。什么原因呢，解决了吗？
![image](https://github.com/alibaba/spring-cloud-alibaba/assets/34766507/274cdaed-0477-4849-81c7-890ed9070eb0)

**Comment by yang1320** [comment]
解决了吗

**Comment by yang1320** [comment]
> **Which Component** spring-boot-starter-web:2.1.6.RELEASE spring-cloud-starter-alibaba-nacos-config:2.1.0.RELEASE
> 
> **Describe what problem you have encountered** 我想注册监听器监听配置的变化，但是使用@NacosConfigListener无法得到任何消息
> 
> ```
> @NacosConfigListener(dataId = "example-dev.properties")
>     public void onReceived(Properties value) {
>         log.info("onReceived(Properties) : {}", value);
>     }
> ```
> 
> 但是日志中我可以看到的确是接收到了配置变化
> 
> ```
> 2019-08-09 15:15:56.093  INFO 2505 --- [d0-fd101bbf6de8] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [test]
> ```
> 
> 另外我试着添加如下代码，这里可以正常得到配置更新的消息，但是我想使用@NacosConfigListener这个注解来获取
> 
> ```
>     @PostConstruct
>     public void init() throws NacosException {
>         nacosConfigProperties.configServiceInstance().addListener("example-dev.properties", "DEFAULT_GROUP", new Listener() {
>             @Override
>             public Executor getExecutor() {
>                 return null;
>             }
> 
>             @Override
>             public void receiveConfigInfo(String s) {
>                 log.info("onReceived(Properties) : {}", s);
>             }
>         });
>     }
> ```

需要添加nacos-spring-context.jar，并启用注解@EnableNacosConfig

**Comment by yang1320** [comment]
最终目的让@NacosConfigListener注解的注解处理器NacosConfigListenerMethodProcessor生效即可
这是我的解决排查过程：https://www.cnblogs.com/swz1104919/p/17562659.html
