### ISSUE TITLE
Pom needs to be corrected

### ISSUE THREAD

**Issue by taylorsfan** [alibaba/spring-cloud-alibaba#837]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**spring-cloud-alibaba-examples**
eg. Nacos Discovery, Sentinel

**Describe the bug**
There is a problem with the pom file path

![image](https://user-images.githubusercontent.com/31753007/62911712-eb8c0e00-bdb7-11e9-9329-f354b9839d84.png)

**Comment by fangjian0423** [comment]
It is correct, why you think is it not correct.
