### ISSUE TITLE
spring-cloud-dubbo-consumer-sample restTemplate  bug

### ISSUE THREAD

**Issue by jwf1173** [alibaba/spring-cloud-alibaba#841]
When I comment out this annotation, the startup will report an error.
![image](https://user-images.githubusercontent.com/31645649/62998714-fa99bb80-be9e-11e9-8ccf-9d138058cb6c.png)

**Comment by fangjian0423** [comment]
could you pls provide a project that reproduces the issue?

**Comment by jwf1173** [comment]
> could you pls provide a project that reproduces the issue?
That's it................................
https://github.com/alibaba/spring-cloud-alibaba/blob/v2.1.0.RELEASE/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample/src/main/java/com/alibaba/cloud/dubbo/bootstrap/DubboSpringCloudConsumerBootstrap.java
