### ISSUE TITLE
spring-cloud-dubbo服务注册获取到的本地IP和Dubbo自己获取到的IP不一致。

### ISSUE THREAD

**Issue by mostcool** [alibaba/spring-cloud-alibaba#844]
测试环境：
spring-cloud-alibaba : 2.1.0.RELEASE
使用 spring-cloud-starter-alibaba-nacos-discovery 和 spring-cloud-starter-dubbo 两个组件。
在本地单网卡情况下，一切正常，服务注册与发现都可用。
在测试环境，docker部署(net: "host")，多网卡情况下，
org.apache.dubbo.common.utils.NetUtils.getLocalHost() 得到的是 docker 的ip 172.17.0.1,
而 org.springframework.cloud.commons.util.InetUtils.findFirstNonLoopbackHostInfo().getIpAddress()得到的却是本机IP 10.133.0.123。
这样就会有一个问题，本地环境想消费测试环境里的某个服务时，找不到。本地向nacos注册的IP与测试环境IP 10.133.0.123 在同一网内。找不到 172.17.0.1, 这个IP。

**Comment by haydonchou** [comment]
org.apache.dubbo.config.ServiceConfig 类中
```java
      Register & bind IP address for service provider, can be configured separately.
      Configuration priority: environment variables -> java system properties -> host property in config file -> /etc/hosts -> default network address -> first available network address
```

findConfigedHosts方法
```java
                try {
                    hostToBind = InetAddress.getLocalHost().getHostAddress();
                } catch (UnknownHostException e) {
                    logger.warn(e.getMessage(), e);
                }
```

如果不指定ip，dubbo会自动用以上的方式获取ip，不支持spring.cloud.inetutils.preferred-networks。
dubbo提供的方式可以配置dubbo.protocol.host=ip。
但是感觉没有spring.cloud.inetutils.preferred-networks方便。

不知道spring cloud alibaba会不会封装 或者有其它什么建议。

**Comment by fangjian0423** [comment]
Dubbo Spring Cloud support InetUtils, you could use `spring.cloud.inetutils` prefix to configure some configurations.

**Comment by haydonchou** [comment]
> Dubbo Spring Cloud support InetUtils, you could use `spring.cloud.inetutils` prefix to configure some configurations.

Why do I see dubbo.metadata-service.urls metadata ip in nacos is incorrect?，I debug to run according to the code
```java
                try {
                    hostToBind = InetAddress.getLocalHost().getHostAddress();
                } catch (UnknownHostException e) {
                    logger.warn(e.getMessage(), e);
                }
```

**Comment by flying706** [comment]
在我的项目中，我通过添加类似以下配置来解决这个问题，也许你可以试试：
```yaml
spring.cloud.inetutils.ignored-interfaces[0]=lo

spring.cloud.inetutils.preferred-networks[0]=192.168

dubbo.protocols.dubbo.host: ${spring.cloud.client.ip-address}
```
