### ISSUE TITLE
nacos discovery 配置 server-addr 域名时候不能正常解析

### ISSUE THREAD

**Issue by cyejing** [alibaba/spring-cloud-alibaba#851]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Discovery

**Describe the bug**
nacos discovery 配置 server-addr 域名时候不能正常解析
The nacos discovery configuration server-addr domain name cannot resolve properly
比如配置： server.addr=http://dev.nacos.com
会被解析成http://dev.nacos.co
原因在于
https://github.com/alibaba/spring-cloud-alibaba/blob/de902a3813e982add1ab4f1cadfade7677e2ff74/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java#L194

**To Reproduce**

**Expected behavior**
期望配置域名的情况能够正常解析
Expect configuration domain names to resolve properly

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by fangjian0423** [comment]
use `dev.nacos.com` to try it.

**Comment by lyuzb** [comment]
> use `dev.nacos.com` to try it.

After testing this is indeed a bug because the error truncates the registered address. Http://dev.nacos.com is a successful registration. I have started a PR

**Comment by fangjian0423** [comment]
👍

**Comment by YSS-1987** [comment]
请问这个问题 解决了吗

**Comment by YSS-1987** [comment]
我 1.4.1  遇到了这个问题
