### ISSUE TITLE
NacosConfigHealthIndicator Always in UP state

### ISSUE THREAD

**Issue by yinjihuan** [alibaba/spring-cloud-alibaba#855]
**Which Component**
Nacos Config

**Describe the bug**
NacosConfigHealthIndicator Always in UP state

**To Reproduce**
1. project add spring-boot-starter-actuator
2. Stop Nacos service
3. Visit /actuator/health, Display results {"status":"UP"}

**Expected behavior**
{"status":"DOWN"}

**Screenshots**

The following code should add a judgement
```
builder.up().withDetail("dataIds", dataIds);
```
Change to
```
if( builder.build().getStatus() != Status.DOWN ) {
    builder.up().withDetail("dataIds", dataIds);
}
```

After modification, there is still a problem. Nacos also has cache configuration information locally. That is to say, when all Nacos services are deactivated, the health status can not be set to DOWN in time. Because configService. getConfig, the internal preference is to get the configuration from the local cache, so the configuration can be obtained, too. That is, health checks are invalid in this case.

If I want to do my personal sensory health check, then don't follow this logic. The easiest way is to read directly from the Nacos service every time. Reading exceptions can be set to DOWN at this time.

**Additional context**
spring-cloud-starter-alibaba-nacos-config.0.9.0.RELEASE

**Comment by echooymxq** [comment]
@yinjihuan  you are right,  the `NacosConfigHealthIndicator` should have a limt time on load local conf, after timeout , locate remote directly. @fangjian0423

**Comment by fangjian0423** [comment]
could you pls create a pr to fix it?

**Comment by fangjian0423** [comment]
consider using `ConfigService#getServerStatus` in https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java#L106.

**Comment by echooymxq** [comment]
> consider using `ConfigService#getServerStatus` in https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java#L106.

as you say, the nacos already existed a inteface of `getServerStatus`, we can get the server health status easily. the Long Poll task work perfectly, no need to do extra things. in addition,I think the old code is very redundancy,we usually only care the health status, so we don't need to pay attention to a single dataid

**Comment by fangjian0423** [comment]
Agree with you, there is no need to pay attention to the dataIds in HealthIndicator.

refer https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-config-spring-boot-actuator/src/main/java/com/alibaba/boot/nacos/actuate/health/NacosConfigHealthIndicator.java.

Spring Cloud Alibaba Nacos Config will integrate with Nacos Config Spring Boot in the future, see #825
