### ISSUE TITLE
com.alibaba.nacos.client.Worker.fixed-

### ISSUE THREAD

**Issue by mintonzhang** [alibaba/spring-cloud-alibaba#859]
About spring-cloud-starter-alibaba-nacos-config

CPU is up to 100% after a period of time
After debugging by visualVW, I found that there are many threads.
"com.alibaba.nacos.client.Worker.fixed-192.168.0.251_8848"
This problem does not occur when I disable the dependency. This should be the main reason for the high CPU usage. Is there any way to solve this problem?

你好，我现在使用的是spring-cloud-starter-alibaba-nacos-config 0.9版本
运行一段时间后，CPU高涨(设置过jvm的参数)。经过调试，线程列表中，出现了很多
com.alibaba.nacos.client.Worker.fixed-*** 
我这问题出现的原因可能有哪些情况？

**Comment by zkzlx** [comment]
Please provide as many instructions as possible.

**Comment by chuntaojun** [comment]
你可以把项目的jmap发一下吗？或者加我钉钉：dvxx6ro

**Comment by james-yuan** [comment]
谢谢！我没有遇到这个问题，只是想看看那些问题是怎么解决的。




------------------ 原始邮件 ------------------
发件人: "liaochuntao"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 上午10:01
收件人: "alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [alibaba/spring-cloud-alibaba]com.alibaba.nacos.client.Worker.fixed- (#859)




你可以把项目的jmap发一下吗？或者加我钉钉：dvxx6ro

**Comment by chuntaojun** [comment]
We have found the problem, and is being repaired

**Comment by mintonzhang** [comment]
我们的项目采用的springcloud for alibaba 0.9.0版本和mybaits-plus， 在mybaits-plus中有个打印sql的配置项。 当这个sql打印和nacos的配置中心一起使用时会出现这个问题，当关闭sql打印时，就不会出现这个问题，正式服中就没有这个问题。

Our project uses springcloud for alibaba 0.9.0 and mybaits-plus, and there is a sql configuration item in mybaits-plus. This problem occurs when this sql print is used with the nacos configuration center. This problem does not occur when sql printing is closed.

**Comment by chuntaojun** [comment]
这个问题的原因是因为springcloud在配置刷新时会触发Context的refresh操作，这里会导致nacos-client实例被重复创建，或者使用者自己排查下有没有自己操作nacos-client的创建并且没有自己维护单例的措施

**Comment by chuntaojun** [comment]
此类问题并非nacos客户端自身的问题
