### ISSUE TITLE
About com.alibaba.nacos.client.Worker.fixed-**

### ISSUE THREAD

**Issue by mintonzhang** [alibaba/spring-cloud-alibaba#860]
About spring-cloud-starter-alibaba-nacos-config

CPU is up to 100% after a period of time
After debugging by visualVW, I found that there are many threads.
"com.alibaba.nacos.client.Worker.fixed-192.168.0.251_8848"
This problem does not occur when I disable the dependency. This should be the main reason for the high CPU usage. Is there any way to solve this problem?

**Comment by fangjian0423** [comment]
duplicate https://github.com/alibaba/spring-cloud-alibaba/issues/859.
