### ISSUE TITLE
no providers available for calling the newly written Dubbo service

### ISSUE THREAD

**Issue by liuxx001** [alibaba/spring-cloud-alibaba#870]
In a development environment, multiple developers connect to the same registry and call the newly written Dubbo service throw an no provider available exception.

**Which Component**
Spring Cloud Alibaba Dubbo

**Describe the bug**

Developer A starts the service first, and developer B creates a new Dubbo interface and starts the service.

When B starts, all instances of the subscribed service are retrieved from the registry and an instance is selected to initialize the DubboMetadataServiceURL. When the selected instance is the service of developer A, the Dubbo interface created by developer B does not exist in the metadata. When the service is invoked, the no provider available exception is thrown.

**Expected behavior**

Providing an extension to decide which service to choose to create metadata information.

**Screenshots**

![image](https://user-images.githubusercontent.com/7148259/63418355-88445080-c435-11e9-8088-c6cf66dd3971.png)

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/spring-cloud-alibaba/issues/695, it has been fixed now.

**Comment by liuxx001** [comment]
@fangjian0423 

Thank you for your response，but it`s not the same issue。

I looked at the pr for [#695](https://github.com/alibaba/spring-cloud-alibaba/issues/695).
The `refreshInvoker` in `RegistryDirectory` is invoked through a heartbeat event, and he **picks one from all Service Instances to get the Metadata Service**. It works well in the production environment, because the Metadata Service provided by each service is always the same.


But in a development environment, different developers usually connect to the same Nacos, and their Metadata Service is not always the same, such as adding an interface. In this case, if you select Metadata Service that is not your own instance to refresh `RegistryDirectory`, when invoke the new interface, no provider available

**Comment by fangjian0423** [comment]
sorry for the misunderstanding.

i think it need to enhance and welcome to contribute it.

**Comment by liuxx001** [comment]
ok , i will fix it.
