### ISSUE TITLE
Nacos Config Read exception

### ISSUE THREAD

**Issue by renkchina** [alibaba/spring-cloud-alibaba#878]
nacos:1.1.0
spring-cloud-alibaba-nacos-config:0.9.0.RELEASE
---------------------------------
spring.application.name=search-server
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.file-extension=properties
------------------------
Data ID:   search-server.properties
Group  :    DEFAULT_GROUP
Format:    Properties
content：   user.name=admin
-----------------------------------
@RefreshScope
@RestController
@RequestMapping("/search")
public class SearchController {
    @Autowired
    private NameRepository nameRepository;

    @Value("${user.name}")
    String name;

    @GetMapping("/get")
    public Object getUserName() {
        return name;
    }
}
-------------------------------------------------------
result: >name :Administrator.
why "Administrator": that I never configured

**Comment by echooymxq** [comment]
you nacos config not work, reference example and check your configuration
"Administrator" is your system environment property, you may need to understand the springboot `externalized configuration`

**Comment by renkchina** [comment]
![nacos](https://user-images.githubusercontent.com/17176354/64181664-7f259b80-ce99-11e9-825e-526cd905ae8b.png)
After the project starts, the first time the configuration file is read, everything is null.Spring up, the second time in NacosConfigAutoConfiguration nacosContextRefresher() injection will call again nacosConfigProperties.configServiceInstance().That's where the value comes in.'placeholder '**' in value

**Comment by echooymxq** [comment]
> ![nacos](https://user-images.githubusercontent.com/17176354/64181664-7f259b80-ce99-11e9-825e-526cd905ae8b.png)
> After the project starts, the first time the configuration file is read, everything is null.Spring up, the second time in NacosConfigAutoConfiguration nacosContextRefresher() injection will call again nacosConfigProperties.configServiceInstance().That's where the value comes in.'placeholder '**' in value

pls print your configuration, I guess you didn't use bootstrap.properties to load

**Comment by renkchina** [comment]
server.port=9100
spring.data.elasticsearch.cluster-name=my-node-1
spring.data.elasticsearch.cluster-nodes=localhost:9300
spring.data.elasticsearch.repositories.enabled=true
#
spring.cloud.nacos.discovery.server-addr=localhost:9999
#
spring.application.name=search-server
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.serverAddr=localhost:9999
--------------------------------------------------
I could read the address in the configuration file when I used discovery, but it didn't work with config.I wonder if the bean was injected ahead of time.Can also be read by calling nacosContextRefresher().

**Comment by renkchina** [comment]
yes.That's the question.There are a lot of people here who have this problem.
Example: alibaba/ spring-cloud-alibaba-> #818.I think it's because the configuration content is not written in bootstrap.
I hope the document can be marked as a reminder
Thank you very much for your answer

**Comment by fangjian0423** [comment]
hi, it has been marked in [wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config).

![image](https://user-images.githubusercontent.com/5254035/64219877-e115ed80-cef9-11e9-9cda-0dc597213340.png)
