### ISSUE TITLE
when dubbo service register to Nacos, it always placed in the public namespace 

### ISSUE THREAD

**Issue by leoxu1719** [alibaba/spring-cloud-alibaba#890]
how could I config the namespace that dubbo service registgered ? it seem like just register in the public namespace when using nacos as the registry center.

**Comment by fangjian0423** [comment]
try to use `spring.cloud.nacos.namespace` configuration item, refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery#%E5%85%B3%E4%BA%8E-nacos-starter-%E6%9B%B4%E5%A4%9A%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E4%BF%A1%E6%81%AF.

**Comment by leoxu1719** [comment]
the suggestion which using spring.cloud.nacos.discovery.namespace to config, has been tried  at the beginning, but it still be registered to the public space;

**Comment by fangjian0423** [comment]
use namespace id, not name. Did you use it correct?

![image](https://user-images.githubusercontent.com/5254035/64109177-5f1aad00-cdb1-11e9-87cc-0677105cb207.png)

**Comment by leoxu1719** [comment]
just namespace id, not the name,but seems not work
![19_53_07__09_02_2019](https://user-images.githubusercontent.com/23058712/64112982-91310c80-cdbb-11e9-9738-01d847757163.jpg)
![19_53_46__09_02_2019](https://user-images.githubusercontent.com/23058712/64112983-91c9a300-cdbb-11e9-8a6c-b324a4e99745.jpg)

**Comment by fangjian0423** [comment]
It works well in my local.

![image](https://user-images.githubusercontent.com/5254035/64113691-84151d00-cdbd-11e9-9f83-db68aa1984e5.png)

**Comment by fangjian0423** [comment]
Any error logs?  console will print "nacos registry, spring-cloud-alibaba-dubbo-provider 30.5.120.231:8080 register finished" when register successfully.

**Comment by leoxu1719** [comment]
the service provider could be registered in my namespace, but the the service is exposed in the public space :
![image](https://user-images.githubusercontent.com/23058712/64120889-fd1d7000-cdcf-11e9-8e5c-d45ef7aae85b.png)
![image](https://user-images.githubusercontent.com/23058712/64120924-11fa0380-cdd0-11e9-85e6-44982816fca1.png)

is any other configuration I missed ? or you just config the "dubbo.registry.address" as spring-cloud:localhost ?

**Comment by fangjian0423** [comment]
Oh, sorry.

I thought you are use Dubbo Spring Cloud, but i found your registry address is `nacos://localhost:8848`.

You could create issue in [Apache Dubbo repo](https://github.com/apache/dubbo).

**Comment by echooymxq** [comment]
@leoxu1719 you can try 
`dubbo.registry.address=nacos://127.0.0.1:8848?namespace=xxxx`

**Comment by leoxu1719** [comment]
> Oh, sorry.
> 
> I thought you are use Dubbo Spring Cloud, but i found your registry address is `nacos://localhost:8848`.
> 
> You could create issue in [Apache Dubbo repo](https://github.com/apache/dubbo) about dubbo-registry-nacos.

I thought I have figured out what wrong with this, the service I subscribed was not matched ,but thx for your comment and suggestion~

**Comment by leoxu1719** [comment]
> `dubbo.registry.address=nacos://127.0.0.1:8848?namespace=xxxx`

marked~, that's a good suggestion

**Comment by fangjian0423** [comment]
👍
