### ISSUE TITLE
When will there be Go/Python versions?

### ISSUE THREAD

**Issue by ghosthamlet** [alibaba/spring-cloud-alibaba#892]
Thanks for the spring-cloud-alibaba project, it is wonderful. Are there plans to make Go/Rust/Python versions?

**Comment by fangjian0423** [comment]
hi, Spring Cloud Alibaba based on Spring Cloud Projects and Spring Cloud Projects are Java based projects. I think you could create issue in https://github.com/spring-projects/spring-cloud.
