### ISSUE TITLE
 about POM references ，关于pom引用    spring-cloud-starter-alibaba-sentinel，error

### ISSUE THREAD

**Issue by HaoYafei-leafy** [alibaba/spring-cloud-alibaba#896]
spring cloud gateway项目中引用如下代码：
The following code is referenced in the spring cloud gateway project:
```
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
  </dependency>
```
直接报错，项目找不到` com.alibaba.csp.sentinel.adapter.gateway.sc.SentinelGatewayFilter;`等类，
Direct error reporting, project can not find `com. alibaba. csp. sentinel. adapter. gateway. sc. Sentinel Gateway Filter; `etc.
查找相关资料发现项目如果要自己完全自己配置，可以使用如下
If you want to configure the project by yourself, you can use the following.
```
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-cloud-gateway-adapter</artifactId>
</dependency>
```

如果项目使用如下代码，刚好可以完成所有依赖，如下依赖中包含了sentinel-spring-cloud-gateway-adapter，
 If the project uses the following code, it can just complete all the dependencies, which include sentinel-spring-cloud-gateway-adapter.
```
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
  </dependency>
```

就spring-cloud-starter-alibaba-sentinel 的意义何在，不能完成自动化依赖和自动化配置，这是一个bug还 本身就要和 spring-cloud-alibaba-sentinel-gateway 配合使用？！！！

What's the meaning of spring-cloud-starter-alibaba-sentinel? It can't complete automation dependency and automation configuration. is this a bug and it should be used in conjunction with spring-cloud-alibaba-sentinel-gateway?!!

**Comment by echooymxq** [comment]
It not bug, if you use sentinel in gateway project, you need depend the `spring-cloud-alibaba-sentinel-gateway`

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-spring-cloud-gateway-example.

Sentinel with Spring Cloud Gateway/Zuul Projects depend the `spring-cloud-alibaba-sentinel-gateway`.
