### ISSUE TITLE
how about java11

### ISSUE THREAD

**Issue by hawkroc** [alibaba/spring-cloud-alibaba#897]
I try to compile the project base on win10 & java11. but it faulted. Can you please assign the timetable to support the java11? As I know, there are a lot of new projects which base on java11 are kickup every day all around the world.

**Comment by echooymxq** [comment]
it not support jdk11, for example the javaee module of java11, I think it will not support in a short time, because the most used in china is java 8.

**Comment by fangjian0423** [comment]
It's a big update. 

First of all, all the Alibaba & Apache open source projects integrated in Spring Cloud Alibaba should support JDK 11. Then Spring Cloud Alibaba will support JDK 11.
