### ISSUE TITLE
Upgrade to Spring Cloud Hoxton

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#917]
need new branch `greenwich` related Spring Cloud Greenwich & master branch related Spring Cloud Hoxton.

Also version number upgrade to `2.2.0`.

version mapping:

Spring Cloud Version |Spring Cloud Alibaba Version |Spring Boot Version
-|-|-
|Spring Cloud Hoxton|2.2.0.RELEASE|2.2.X.RELEASE
|Spring Cloud Greenwich|2.1.0.RELEASE|2.1.X.RELEASE
|Spring Cloud Finchley|2.0.0.RELEASE|2.0.X.RELEASE
|Spring Cloud Edgware|1.5.0.RELEASE|1.5.X.RELEASE

**Comment by mosakashaka** [comment]
Spring Cloud Alibaba 2.2.0.RELEASE 这个版本请问现在在maven仓库里是不是还没有呀。。

**Comment by fangjian0423** [comment]
> Spring Cloud Alibaba 2.2.0.RELEASE 这个版本请问现在在maven仓库里是不是还没有呀。。

官方还没发布 Hoxton.Release 版本，请关注 https://github.com/spring-cloud/spring-cloud-release/milestones?state=open.

**Comment by mosakashaka** [comment]
> > Spring Cloud Alibaba 2.2.0.RELEASE 这个版本请问现在在maven仓库里是不是还没有呀。。
> 
> 官方还没发布 Hoxton.Release 版本，请关注 https://github.com/spring-cloud/spring-cloud-release/milestones?state=open.

了解了，谢谢

**Comment by huodon** [comment]
Hoxton 已经 RELEASE 了.
