### ISSUE TITLE
nacos 1.1.3 config data not exist

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/spring-cloud-alibaba#921]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**

see nacos issue 1818：https://github.com/alibaba/nacos/issues/1818

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by zkzlx** [comment]
Currently, it is rather rigid, and the subsequent [nacos ](https://github.com/alibaba/nacos)can support the optimization of suffix reading into dynamic

**Comment by zkzlx** [comment]
I've done compatibility, and it's going to be dynamic

**Comment by fangjian0423** [comment]
👍
