### ISSUE TITLE
spring cloud stream rocketmq 希望支持延迟消息

### ISSUE THREAD

**Issue by dejish** [alibaba/spring-cloud-alibaba#924]
使用原生的rocketmq api时，是可以使用 message.setDelayLevel 方法设置延迟级别的。
跟了下源码是使用了名称为 "DELAY" 的属性。

现在我们想切换到 spring cloud stream rocketmq，官方的demo里没有延迟消息的用法，
org.apache.rocketmq.spring.support.RocketMQHeaders 里也并未有延迟消息的header，使用

`Message message = MessageBuilder.withPayload("data").setHeader("DELAY", "1").build();`

并没有延迟效果，请为spring cloud stream rocketmq增加延迟消息的特征

**Comment by shandianzhao** [comment]
已经解决了么？

**Comment by yanbangqing** [comment]
开源版是否支出演示消息的特性?

**Comment by JOJO0527** [comment]
2020/5/7 测试4.6版本仍然无延迟消息支持。

**Comment by 1078699311** [comment]
需要加上 spring.cloud.stream.rocketmq.bindings.<outputName>.producer.sync=true

**Comment by nanchengjiumeng123** [comment]
> 需要加上 spring.cloud.stream.rocketmq.bindings..producer.sync=true

是的，我加上了这个成功了，加上：spring.cloud.stream.rocketmq.bindings.你的消息通道.producer.sync=true
