### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config  2.1.0-RELEASE导入不了

### ISSUE THREAD

**Issue by yinlimin** [alibaba/spring-cloud-alibaba#925]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

没有发布到maven仓库吧，导入不了

**Comment by fangjian0423** [comment]
refer https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2.1.0.RELEASE
