### ISSUE TITLE
spingcloud Greenwich.RELEASE版本使用2.1.0的版本 启动服务找不到配置信息 ，nacos使用的是1.1.3版本

### ISSUE THREAD

**Issue by zoui520** [alibaba/spring-cloud-alibaba#927]
spingcloud Greenwich.RELEASE版本使用2.1.0的版本 启动服务找不到配置信息 ，nacos使用的是1.1.3版本

**Comment by zoui520** [comment]
![image](https://user-images.githubusercontent.com/26056504/64611526-383d2600-d404-11e9-8907-faf2e0893143.png)

**Comment by fangjian0423** [comment]
Refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config.
