### ISSUE TITLE
Integrate  SCA, Use nacos config center,    Modify parameter values  causes   Schedule Task   does't  work

### ISSUE THREAD

**Issue by LiujunjieALiling** [alibaba/spring-cloud-alibaba#932]
**dependency :**
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-quartz</artifactId>
</dependency>
**scene : Schedule Task**     
**operate :**  when i modify params in nacos config center, application  can  receive  change,   but  it  causes my  schedule  does not  work.   ****

**Comment by LiujunjieALiling** [comment]
**like  this :**

![image](https://user-images.githubusercontent.com/42363259/64720227-846b9180-d4fc-11e9-84c6-2b961197280f.png)

**Comment by fangjian0423** [comment]
Does other config center can reproduce the problem?

If so, it's not the problem of Nacos config center.

**Comment by LiujunjieALiling** [comment]
I haven't  attempt  other config center yet,    My goal is to integrate SCA and use Nacos as the config  center

**Comment by LiujunjieALiling** [comment]
thanks  for your reply ,   If  so,    when this  bug    will be  fixed ?   can  you  give   other suggestion  to avoid this problem ?    
If I want to configure timed task parameters, what should I do?

**Comment by LiujunjieALiling** [comment]
thanks  for your  reply , I'll revamp it later！

**Comment by LiujunjieALiling** [comment]
> > can you give me the solutions of this ?
> 
> It a spring cloud's original problem, maybe you can refer to https://stackoverflow.com/questions/50440468/refreshscope-stops-scheduled-task

Well done， I had resolved it .  thank you very much!
