### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config 2.1.0  does not currently support json type

### ISSUE THREAD

**Issue by lidong1665** [alibaba/spring-cloud-alibaba#942]
About `spring-cloud-starter-alibaba-nacos-config` does not currently support` json` issues

`NacosPropertySourceLocator` This class `checkDataIdFileExtension` method directly `throw new IllegalStateException(String.format("[%s] must contains file extension with properties|yaml|yml", result));`

Recommendation: The data-id is not restricted and limits the type of configuration format.

**Comment by fangjian0423** [comment]
It has been supported now, related https://github.com/alibaba/spring-cloud-alibaba/issues/698.
