### ISSUE TITLE
nacos-discovery-2.1.0依赖nacos-client版本过低

### ISSUE THREAD

**Issue by g1335333249** [alibaba/spring-cloud-alibaba#945]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>
依赖的nacos-client版本为1.0.0，启动报错
java.lang.ClassNotFoundException: com.alibaba.nacos.api.naming.NamingMaintainService
查看spring-cloud-alibaba-dependencies里面的nacos-client版本为1.1.1不知为何discovery里面的版本为1.0.0

**Comment by echooymxq** [comment]
you can check your dependencies tree, in my machine, it will not happen.

**Comment by fangjian0423** [comment]
some conflicts with your dependency.
