### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config   <version>0.2.0.RELEASE</version>  attribute  spring.profile.active is invalid 

### ISSUE THREAD

**Issue by zhuweimin1994** [alibaba/spring-cloud-alibaba#950]
spring-cloud-starter-alibaba-nacos-config   <version>0.2.0.RELEASE</version> 
dataid has nothing to do with attribute  spring.profile.active

**Comment by fangjian0423** [comment]
we don't recommand use old version. pls use graduation version. refer https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E.
