### ISSUE TITLE
`Dubbo-spring-cloud Example` is missing from the directory on the right

### ISSUE THREAD

**Issue by arugal** [alibaba/spring-cloud-alibaba#954]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
wiki

**Describe the bug**
`Dubbo-spring-cloud Example` is missing from the directory on the right

**Comment by fangjian0423** [comment]
thanks for the suggestion, i have added it in sidebar.
