### ISSUE TITLE
SpringCloud项目引用spring-cloud-starter-dubbo模块，将dubbo的注册中心挂载到SpringCloud的注册中心上，可以使用Dubbo Admin后台查看相关信息么

### ISSUE THREAD

**Issue by HusenHuang** [alibaba/spring-cloud-alibaba#956]
SpringCloud项目引用spring-cloud-starter-dubbo模块，将dubbo的注册中心挂载到SpringCloud的注册中心上，可以使用Dubbo Admin后台查看相关信息么

**Comment by zkzlx** [comment]
certainly

**Comment by HusenHuang** [comment]
thank you

**Comment by tyq0010** [comment]
@HusenHuang 我跟你一样，也是引用了spring-cloud-starter-dubbo，使用nacos作为注册中心，将dubbo的注册中心挂载到SpringCloud的注册中心上，但是在Dubbo Admin后台看不到相关信息。你后来能看到了吗？

**Comment by tyq0010** [comment]
@HusenHuang 我的情况是：
如果配置dubbo.registry.address=nacos://127.0.0.1:8848，就可以在Dubbo Admin看到服务；
如果配置dubbo.registry.address=spring-cloud://localhost，以及spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848, 在Dubbo Admin就看不到服务。

**Comment by zkzlx** [comment]
thanks for your feedback , if there is any problem , we will fix it as soon as possible .

**Comment by wghdir** [comment]
dubbo.registry.address=nacos://127.0.0.1:8848也看不到服务
