### ISSUE TITLE
SpringCloud-Dubbo模块启动顺序

### ISSUE THREAD

**Issue by HusenHuang** [alibaba/spring-cloud-alibaba#957]
假设A服务需要依赖于B服务，并且A服务配置了dubbo.consumer.check=false，先启动A服务，再启动B服务，一直是 No provider available for the service，注册中心使用nacos

**Comment by zkzlx** [comment]
you can look at this #695

**Comment by laiweijia** [comment]
2.1.1 R 
is fixed!
