### ISSUE TITLE
rocketmq配置死信队列无法触发

### ISSUE THREAD

**Issue by ciweigg2** [alibaba/spring-cloud-alibaba#959]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
rocketmq

**Describe what problem you have encountered**
配置input: {consumer.delayLevelWhenNextConsume: -1}但是重试2次后不会进入死信队列 怎样才能触发?已经配置过死信队列的消费者了，

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by fangjian0423** [comment]
Refer https://github.com/fangjian0423/rocketmq-binder-demo/tree/master/rocketmq-binder-concurrently-dlq-demo.

**Comment by ciweigg2** [comment]
这个demo只有死信的配置 然后service中也只有接收input的方法 没有提到input重试失败后进入指定的死信队列inputDlq这样的例子 我说的这个能实现吗？

**Comment by fangjian0423** [comment]
Input Binding 消费失败进入 DLQ 了，有什么问题吗？

**Comment by ciweigg2** [comment]
如果我不把DLQ队列的perm设置成6无法在代码中消费 消息的确是投递到DLQ了 但是自动生成的DLQ的perm是6除非手动创建

**Comment by fangjian0423** [comment]
SCS RocketMQ Binder 目前只负责投递到 DLQ 中的操作，没有涉及 perm 的操作。
