### ISSUE TITLE
使用@NacosInjected 注入Nacos 的NamingService实例以及ConfigService都为null

### ISSUE THREAD

**Issue by punge** [alibaba/spring-cloud-alibaba#969]
参考https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example 例子， 采用
Spring Cloud Greenwich 
Spring Cloud Alibaba Version  0.9.0.RELEASE
项目启动成功，在nacos server上也注册成功，
但是在代码controller层 使用@NacosInjected 注入Nacos 的NamingService实例以及ConfigService都为null ，请问是什么原因导致？？

还有个问题，在mac上开启shadowssocks代理情况下，服务注册成功，但是不停报心跳检查超时等问题，如何解决？

**Comment by fangjian0423** [comment]
we are working on it, refer https://github.com/alibaba/spring-cloud-alibaba/issues/825.

It's a duplicate issue and i close it.

**Comment by punge** [comment]
@fangjian0423 现在只能通过properties 获取service
![image](https://user-images.githubusercontent.com/6881633/65824810-7316d900-e2a1-11e9-8c5f-f3303fcf3991.png)

ConfigService configService = nacosConfigProperties.configServiceInstance();
NamingService namingService = nacosDiscoveryProperties.namingServiceInstance();

**Comment by bibichuan** [comment]
使用
ConfigService configService = nacosConfigProperties.configServiceInstance();
NamingService namingService = nacosDiscoveryProperties.namingServiceInstance();
可以的
