### ISSUE TITLE
not support change the contextPath of the nacos-server?

### ISSUE THREAD

**Issue by zzycreate** [alibaba/spring-cloud-alibaba#971]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
我使用docker启动了nacos-server, 启动命令如下：
I start a nacos-server by docker, the startup command is as follows:

```
docker run --name=nacos \
    --restart=always \
    -p 8848:8848 \
    -e MODE=standalone \
    -e MYSQL_MASTER_SERVICE_HOST=172.0.0.1 \
    -e MYSQL_MASTER_SERVICE_PORT=3306 \
    -e MYSQL_MASTER_SERVICE_DB_NAME=nacos \
    -e MYSQL_MASTER_SERVICE_USER=root \
    -e MYSQL_MASTER_SERVICE_PASSWORD=123456 \
    -e SERVER_SERVLET_CONTEXTPATH=/ \
    -d nacos/nacos-server:1.1.3
```

然后我可以直接访问 `127.0.0.1:8848/` 而不需要使用 `127.0.0.1:8848/nacos/` .
Then I can go directly to `127.0.0.1:8848/` without using `127.0.0.1:8848/nacos/` .

springboot 程序使用如下配置:
The springboot program uses the following configuration:

pom.xml:

```
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>2.1.8.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
      <version>2.1.0.RELEASE</version>
    </dependency>
  </dependencies>
```

application.yml:

```
server:
  port: 9999
spring:
  application:
    name: nacos-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
```

程序启动后，获得了异常报错：
start the program, i get this error info:

```
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: failed to req API:127.0.0.1:8848/nacos/v1/ns/instance. code:401 msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sat Sep 28 23:22:51 GMT+08:00 2019</div><div>There was an unexpected error (type=Unauthorized, status=401).</div><div>Unauthorized</div></body></html>

```

**Question**

我认为应该是请求 `/v1/nas/instance` 而不是 `/nacos/v1/ns/instance`, 直接访问 `http://127.0.0.1:8848/v1/ns/instance` 可以获得 `Param 'serviceName' is required.` 这样的信息; 访问 `http://127.0.0.1:8848/nacos/v1/ns/instance` 我只能看见 401 错误页面。
我应该怎么配置？

I think it should be requested `/v1/nas/instance` instead of `/nacos/v1/ns/instance`, open the url `http://127.0.0.1:8848/v1/ns/instance` can get the info page of `Param ' ServiceName' is required.` ; and open the url `http://127.0.0.1:8848/nacos/v1/ns/instance` I can only see the 401 error page.
How should I configure it?

**Comment by echooymxq** [comment]
You had better remove the `SERVER_SERVLET_CONTEXTPATH `, the context path use */nacos* default.
