### ISSUE TITLE
Spring Cloud Edgware release discussion

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#974]
Hi community.

Since [Spring Cloud Edgware EOL Aug 1st 2019](https://spring.io/blog/2018/07/30/spring-cloud-edgware-eol-aug-1st-2019), Spring Cloud Alibaba want follow the announcement.

We won't release versions based on Spring Cloud Edgware(the version number 0.1.x & 1.5.x based on Spring Cloud Edgware) in the next release time.

This is not absolute. We want to hear the voice of the community.

**Comment by HaojunRen** [comment]
我认为可以的。但事实还有很多公司都在用Edgware，建议先征集哪些公司还在用E版

**Comment by Kimmyzhao** [comment]
现在公司项目中版本已经升级到Greenwich.SR3了

**Comment by xiaolongyuan** [comment]
虽然线上在用E 但是支持淘汰掉E

**Comment by xiejiashuai** [comment]
> Hi community.
> 
> Since [Spring Cloud Edgware EOL Aug 1st 2019](https://spring.io/blog/2018/07/30/spring-cloud-edgware-eol-aug-1st-2019), Spring Cloud Alibaba want follow the announcement.
> 
> We won't release versions based on Spring Cloud Edgware(the version number 0.1.x & 1.5.x based on Spring Cloud Edgware) in the next release time.
> 
> This is not absolute. We want to hear the voice of the community.

我认为是可以的，Spring官方都不在维护E版本，我们这边也没有太大的必要去维护，这样就涉及到升级，如果能大致告诉用户升级方面的坑可能会更好。

**Comment by echooymxq** [comment]
approve it, but we need support to Edgware.SR6.

**Comment by HaojunRen** [comment]
建议Spring Cloud Alibaba最后再发一版支持E，接下去可以不必要去支持了

**Comment by fangjian0423** [comment]
> approve it, but we need support to Edgware.SR6.

We now support Edgware.SR5 and agree with you to support Edgware.SR6, then EOL after it 👍

**Comment by vnobo** [comment]
既然是spring cloud 我觉得和spring cloud 官网保持一致,更新策略和支持策略,最新Hoxton
