### ISSUE TITLE
How to set Rocketmq  enabled: false in application.yml

### ISSUE THREAD

**Issue by masankin** [alibaba/spring-cloud-alibaba#975]
**Which Component**
spring-cloud-stream-binder-rocketmq

**Describe what problem you have encountered**
How to set Rocketmq  enabled: false in application.yml ?  
The console println log:
[NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[] result: true

**Describe what information you have read**

**Comment by fangjian0423** [comment]
hi, what did you mean about the enable?

Enable RocketMQ Binder or Enable Binding, pls describe it clearly. Thanks

**Comment by masankin** [comment]
> hi, what did you mean about the enable?
> 
> Enable RocketMQ Binder or Enable Binding, pls describe it clearly. Thanks

I haven't config the spring.cloud.stream.bindings AND spring.cloud.stream.rocketmq , But the console always print the log:
[NettyClientSelector_1] INFO RocketmqRemoting - closeChannel: close the connection to remote address[] result: true

How to make the Rocketmq  not startup

**Comment by fangjian0423** [comment]
Did you mean adding `spring-cloud-stream-binder-rocketmq` dependency and do not want to startup RocketMQ Connection?

**Comment by fangjian0423** [comment]
try this configuration:

```properpties
spring.cloud.stream.bindings.<youtbindingname>.consumer.auto-startup=false
```

**Comment by kissliumin** [comment]
Why did I configure it and it didn't work

> try this configuration:
> 
> ```
> spring.cloud.stream.bindings.<youtbindingname>.consumer.auto-startup=false
> ```
