### ISSUE TITLE
启动两个使用nacos + cloud dubbo 的应用，它们互为消费者与提供者的时候，永远有一方找不到服务提供者，事实上这个提供者已经在线

### ISSUE THREAD

**Issue by WuQuDeRen** [alibaba/spring-cloud-alibaba#976]
1、启动两个互为消费者与提供者的应用，则其中一个应用永远找不到服务提供者，另一个却可以 
     nacos + cloud dubbo
  备注：如果不使用 nacos + cloud dubbo，而换成最原始的 nacos + dubbo 则一定可以找到服务提供者
2、bootstrap.yml配置
 1)
dubbo:
  application:
    qos-port: 20221
    qos-accept-foreign-ip: false
  scan:
    base-packages: com.fj.nacos.order.web.remote
  protocol:
      name: dubbo
      port: -1
  registry:
      address: spring-cloud://127.0.0.1
      check: false
  consumer:
    check: false
 
 2)
dubbo:
  scan:
    base-packages: com.fj.nacos.crm.web.remote
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  consumer:
    check: false
  application:
    qos-enable: true
    qos-accept-foreign-ip: false
    qos-port: 22223

--------
3. pom依赖
       <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Greenwich.SR1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        <dependency>
               <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
        </dependency>
       <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-dubbo</artifactId>
        </dependency>
        <dependency>
            
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

**Comment by fangjian0423** [comment]
请不要重复提交 issue，参考 https://github.com/alibaba/spring-cloud-alibaba/issues/695
