### ISSUE TITLE
I hope that one of shared-dataids and ext-config can support profile recognition.

### ISSUE THREAD

**Issue by somowhere** [alibaba/spring-cloud-alibaba#978]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Config

**Is your feature request related to a problem? Please describe.**
Microservices load the same public configuration can only be hard coded

**Describe the solution you'd like**
I hope that one of shared-dataids and ext-config can support profile recognition.

**Describe alternatives you've considered**
在 com.alibaba.cloud.nacos.NacosConfigProperties.Config 中增加是否启用profile属性，然后在NacosPropertySourceLocator.loadExtConfiguration 读取注入profile 
Add whether to enable the profile attribute in com.alibaba.cloud.nacos.NacosConfigProperties.Config and then read the injection profile in NacosPropertySourceLocator.loadExtConfiguration

**Comment by zkzlx** [comment]
Thank you for your suggestion. I will support it as soon as possible.

**Comment by zkzlx** [comment]
Configure load order : shared -> extensional -> application(default) ->application(suffix) -> application(profile).
There is therefore a priority for configuration items . 
The order of priorities is the reverse of the loading order.

**Comment by fangjian0423** [comment]
Yes, different configurations have different order, refer https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config#%E9%85%8D%E7%BD%AE%E7%9A%84%E4%BC%98%E5%85%88%E7%BA%A7

Refer the order of Spring Boot Externalized Configuration: https://stackoverflow.com/a/25862357
