### ISSUE TITLE
spring-cloud-alibaba-docs 文档图片过大，中文出现

### ISSUE THREAD

**Issue by mtcarpenter** [alibaba/spring-cloud-alibaba#979]
spring-cloud-alibaba-docs 文档图片太大，超出文档的边框。
![image](https://user-images.githubusercontent.com/42951781/66363497-15793f80-e9b9-11e9-9a68-3f5c7d7eeac5.png)
参考 Sentinel 网关限流 和 参考 Sentinel 网关限流 链接地址文字为中文

**Comment by fangjian0423** [comment]
It seems the new reference is better: https://spring-cloud-alibaba-group.github.io/github-pages/hoxton/en-us/index.html
