### ISSUE TITLE
Add default values for some configuration items

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/spring-cloud-alibaba#980]
For examples:

[Nacos Discovery Server Address](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java#L72)=localhost:8848
[Nacos Config Server Address](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java#L90)=localhost:8848
[Nacos DataSource Server Address](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/NacosDataSourceProperties.java#L33)=localhost:8848

**Comment by yuhuangbin** [comment]
I will fix it.
