### ISSUE TITLE
nacos config shared-dataids cont select group

### ISSUE THREAD

**Issue by khiker007** [alibaba/spring-cloud-alibaba#982]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config

**Is your feature request related to a problem? Please describe.**
I want to get the configuration file from Nacos according to the environment, but Shared-data IDS can only be obtained from DEFAULT_GROUP
我想从nacos按照环境获取配置文件，但是shared-dataids只能从DEFAULT_GROUP获取

**Describe the solution you'd like**
shared-dataids: group:dubbo-consumer.yaml
可以指定group，不指定则默认使用DEFAULT_GROUP

**Comment by zkzlx** [comment]
thanks for your suggestion, we will improve it later.
