### ISSUE TITLE
sentinel dashboard项目名错误

### ISSUE THREAD

**Issue by khiker007** [alibaba/spring-cloud-alibaba#983]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Sentinel

**Describe the bug**
spring.application.name=service-account,但是sentinel dashboard中显示为aliyun-java-sdk-core，项目中引用了aliyun的jar包

**Additional context**
Java8 、 Version 2.1.0.RELEASE

**Comment by khiker007** [comment]
aliyun-java-sdk-core 4.4.1版本中project.properties中含有project.name，与sentinel的project.name冲突导致，更换新版sdk解决

**Comment by wildwindwind** [comment]
赞，强
