### ISSUE TITLE
Maven install error：org.apache.maven.plugins:maven-gpg-plugin:1.4:sign (sign-artifacts) 

### ISSUE THREAD

**Issue by shingle2302** [alibaba/spring-cloud-alibaba#984]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by fangjian0423** [comment]
hi , maven-gpg-plugin is not exists in pom.  How did you find it?

**Comment by jang675953** [comment]
i didn‘t find it ,but when i install ,this error occurs




------------------ 原始邮件 ------------------
发件人: "format"<notifications@github.com>; 
发送时间: 2019年10月21日(星期一) 下午2:32
收件人: "alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/spring-cloud-alibaba] Maven install error：org.apache.maven.plugins:maven-gpg-plugin:1.4:sign (sign-artifacts)  (#984)




hi , maven-gpg-plugin is not exists in pom.  How did you find it?

**Comment by jang675953** [comment]
------------------ 原始邮件 ------------------
发件人: "format"<notifications@github.com>; 
发送时间: 2019年10月21日(星期一) 下午2:32
收件人: "alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/spring-cloud-alibaba] Maven install error：org.apache.maven.plugins:maven-gpg-plugin:1.4:sign (sign-artifacts)  (#984)




hi , maven-gpg-plugin is not exists in pom.  How did you find it?
