### ISSUE TITLE
Nacos Config with yaml file not in sequence

### ISSUE THREAD

**Issue by forfuns** [alibaba/spring-cloud-alibaba#987]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Nacos Config

**Describe the bug**
spring-cloud-starter-alibaba-nacos-config with yaml file convert data will not in sequence，
my project (a basic spring cloud project ) change to use spring-cloud-with-alibaba,use Nacos to alternative Eureka and Config, I found yml file can't convert in sequence.
so make my shiro config will wrong

is the same issue on Nacos Project : https://github.com/alibaba/nacos/issues/1910

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
MacOS
Spring Cloud 2.1.0
jdk1.8

**Comment by forfuns** [comment]
抱歉，我的英文实在不好，此处我主要使用中文来沟通，后续补充英文翻译版

我之前发现这个问题，然后issue提交到Nacos这个repo上，但后来经过调试，发现Spring Config没有问题，是因为在载入的过程中，默认使用的是properties（Spring Config会对格式进行转换），但同样是properties , Nacos Config 也会存在无序的问题，我查询了源码，发现转换的过程中解析是存储成properties 最后 properties 再转换成map，问题就在于转换成properties的时候顺序乱了

由于我的项目时候shiro，shiro在url过滤上是按照顺序来检查的，在更换的过程由于上述的问题，导致鉴权不符合预期。

**Comment by fangjian0423** [comment]
Thank you for you report, we will enhance it before next version release & contributors are welcome!

**Comment by forfuns** [comment]
@fangjian0423 I fixed this on my branch,but only for `2.1.0.RELEASE` , how can I commit my code on this repo ?

**Comment by fangjian0423** [comment]
> @fangjian0423 I fixed this on my branch,but only for `2.1.0.RELEASE` , how can I commit my code on this repo ?

of course & welcome, refer https://github.com/alibaba/spring-cloud-alibaba/wiki/%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81#%E9%85%8D%E7%BD%AE-spring-cloud-%E6%A0%87%E5%87%86%E7%9A%84%E4%BB%A3%E7%A0%81%E6%A0%BC%E5%BC%8F to create pr to fix it.

**Comment by forfuns** [comment]
fixed code is only for tag `2.1.0.RELEASE`,master is not the same

**Comment by forfuns** [comment]
@fangjian0423 I try made code on master branch,but IDEA tell me maven dependency wrong, can't build on only master

**Comment by forfuns** [comment]
@fangjian0423 hi，sorry bother you, I need this feature  on  spring-cloud-alibaba 2.1.x,how long it take ?

**Comment by echooymxq** [comment]
@fengshunli will finish it.

**Comment by fengshunli** [comment]
To ensure that the configuration files are orderly, there are two implementations: the first inherits Properties, overrides the put method, uses LinkedIn HashSet for storage, and the second directly uses LinkedIn HashSet or LinkedIn HashMap for receiving

**Comment by fengshunli** [comment]
> @fengshunli will fix it.

To ensure that the configuration files are orderly, there are two implementations: the first inherits Properties, overrides the put method, uses LinkedIn HashSet for storage, and the second directly uses LinkedIn HashSet or LinkedIn HashMap for receiving

**Comment by fengshunli** [comment]
> @fangjian0423 hi，sorry bother you, I need this feature on spring-cloud-alibaba 2.1.x,how long it take ?



> @fangjian0423 hi，sorry bother you, I need this feature on spring-cloud-alibaba 2.1.x,how long it take ?

wait for codereview. We'll be able to use it tomorrow.

**Comment by echooymxq** [comment]
@fengshunli Maybe there need some refactor. you can refer [PropertySourceLoader](https://github.com/spring-projects/spring-boot/blob/334f3e08aef942ee0df135cb8a80142e07b779af/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/PropertySourceLoader.java#L34).
