### ISSUE TITLE
Problems about the configuration of nacos discovery

### ISSUE THREAD

**Issue by yanglin1501804006** [alibaba/spring-cloud-alibaba#989]
1：在使用
 <spring-cloud.version>Greenwich.SR3</spring-cloud.version>
        <spring-cloud-alibaba.version>2.1.0.RELEASE</spring-cloud-alibaba.version>版本的时候:
2：配置文件配置如下：
server.port=8081
spring.application.name=provider
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
management.endpoints.web.exposure.include=*

3：报这个错误：
c.a.cloud.nacos.NacosConfigProperties    : create config service error!properties=NacosConfigProperties{serverAddr='null', encode='null', group='DEFAULT_GROUP', prefix='null', fileExtension='properties', timeout=3000, endpoint='null', namespace='null', accessKey='null', secretKey='null', contextPath='null', clusterName='null', name='null', sharedDataids='null', refreshableDataids='null', extConfig=null}
com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45) ~[nacos-api-1.1.1.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:43) ~[nacos-api-1.1.1.jar:na]

:4将配置内容文件以bootstrap.yml ，bootstrap.properties ，application.yml三种形式的方式重命名，依然上报 “NacosException”异常，但是不会影响服务发现，这里应该是有bug吗？望指正一下。

**Comment by yanglin1501804006** [comment]
补充如下为相应版本对应关系：

<spring-cloud.version>Greenwich.SR2</spring-cloud.version>
        <spring-cloud-alibaba.version>2.1.0.RELEASE</spring-cloud-alibaba.version>

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.6.RELEASE</version>
    </parent>

这三个对应关系也同样报上边的异常

**Comment by SoyMeng** [comment]
spring.cloud.nacos.config相关未配置

**Comment by fangjian0423** [comment]
The error log indicates that you are using Nacos Config, need `spring.cloud.nacos.config.server-addr` configuration item.

**Comment by fangjian0423** [comment]
Related https://github.com/alibaba/spring-cloud-alibaba/issues/998.

**Comment by HaojunRen** [comment]
I close this issue first, any problems to reopen it please
