### ISSUE TITLE
Spring cloud expose enable configuration control service as offline when registering with Nacos

### ISSUE THREAD

**Issue by zhunzhong** [alibaba/spring-cloud-alibaba#992]
I want to be offline when the service starts to register to Nacos by default. When the service is deployed in the production environment and verified to be OK, it will switch to the online state.

The analysis found that `com.alibaba.nacos.api.naming.pojo.Instance` has the attribute enabled, which can control the service offline and online, but `spring.cloud.nacos.discovery` does not expose the configuration. Can the configuration item be exposed in spring cloud?

**Comment by fangjian0423** [comment]
hi, refer [NacosServiceRegistry](https://github.com/alibaba/spring-cloud-alibaba/blob/v2.1.0.RELEASE/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java) and [ServiceRegistryEndpoint](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpoint.java#L51).

curl "/actuator/service-registry" to update the status of Instance.
