### ISSUE TITLE
about nacos servers

### ISSUE THREAD

**Issue by mintonzhang** [alibaba/spring-cloud-alibaba#995]
我写了一个BAT脚本来批量启动jar。 当注册到nacos时，它们都注册到了同一服务。 我怎么解决这个问题？
I wrote a BAT script to start the jar in batches. When registered to nacos, they are all registered to the same service. How can I solve this problem?
![image](https://user-images.githubusercontent.com/45935465/66969854-dedcac80-f0bd-11e9-8e47-85c9183bc812.png)

**Comment by mintonzhang** [comment]
我保证他们的端口和application-name不相同。
I guarantee that their application-name is not the same as the port.

**Comment by mintonzhang** [comment]
nacos版本为 1.1.3

**Comment by mintonzhang** [comment]
更新 不仅仅是批量启动，我单个的java-jar  也会注册到一个服务里面
Update. Not only is the batch startup, my single java-jar will also be registered to the service.

**Comment by mintonzhang** [comment]
nacos重启之后，出现同样的问题 版本 1.1.3
![image](https://user-images.githubusercontent.com/45935465/66970836-65df5400-f0c1-11e9-9b3f-024034798665.png)

**Comment by fangjian0423** [comment]
I don't why, how did you set the service name?

You could try to debug in [NacosServiceRegistry](https://github.com/alibaba/spring-cloud-alibaba/blob/v2.1.0.RELEASE/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java#L51).
